### ISSUE TITLE
Redis 사용 레퍼런스에 대해서 궁금합니다.

### ISSUE THREAD

**Issue by jdragonbae** [codingeverybody/codingyahac#100]
안녕하세요!

redis를 사용하는 적합한 예제가 데이터베이스 캐싱이라고 알고있는데요.

1. 실제로 서비스 되고 있는 레퍼런스에 대해서 알고싶습니다!

2. 작은 프로젝트를 진행하는데 있어서는 이러한 장점을 어떻게 활용할 수 있을까요?

감사합니다.

**Comment by cyppi** [comment]
redis와 유사한 meecached를 실제로 사용하고 있는데요, 
빈번하게 찾아봐야 하는 자료나, 변하지 않는 자료이면서 빠르게 찾아봐야 하는것들이 있으면 매우 유용하게 사용할수 있어요. 
제가 개발하고 있는 부분에서는 전화가 오면, 전화와 연결된사람이 누구인지 빠르게 찾아와서 전화가 울리면서(거의 ) 동시에 알려주는 부분에 사용하고 있어요. 

작은 프로젝트에서 어떤것을 만들지 좀더 자세하게 알수 있을까요? 프로젝트에 따라서 다양하게 응용할 수 있어서요. 
무엇보다도 툴이 좋아서 응용하기 보다는 프로젝트에 맞는 툴을 사용하는것이 더 중요한거 같아요
