### ISSUE TITLE
텐서플로우 3일차 두번째 딥러닝 관련 질문 있습니다. 

### ISSUE THREAD

**Issue by jjimini98** [codingeverybody/codingyahac#1006]
머신러닝 야학 텐서플로우 강의를 듣던 중에 궁금한게 생겨서 이슈 남겨요.
텐서플로우 3일차 '두번째 딥러닝- 보스턴 집값 예측' 강의 중 3번째 실습 동영상에 보면, 

모델을 학습시키고 나서 모델을 이용할 때, 

>>model.predict (독립[0:5]) 
>>종속[0:5]  

이 두 코드 실행 후 결과를 비교한다고 하셨어요. 

그런데 제생각엔 모델이 학습해서 출력한 값은 독립변수가 아니고 종속변수니까 

>> model predict (종속[0:5]) 

이렇게 작성해야 밑에 코드에서 출력된 원본 데이터의 종속변수와 비교할 수 있지 않을까요?

왜 model.predict(종속[0:5])이렇게 안하고 model.predict(독립[0:5]) 이렇게 하는지 궁금합니다.

**Comment by jiyongjung0** [comment]
`model.predict()`라는 것이 하나의 파이썬 함수입니다. [predict 레퍼런스](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict)를 보시면 나와있듯이, 입력 즉 우리가 알고 있는 값인 독립변수를 넣으면, 종속변수를 예측해주는 함수이지요. 따라서 `predict(독립[0:5])`가, **모델이 생각**하는 `종속[0:5]`인 것이지요.

함수의 입력과 출력에 대해서 헷갈리신다면 python의 함수에 대한 부분을 더 공부 해보시면 좋을 것 같습니다.

**Comment by jjimini98** [comment]
@jiyongjung0 헉 그러네요...이해됐어요 감사합니다!
