### ISSUE TITLE
local 환경?에서 pandas, tensorflow 사용

### ISSUE THREAD

**Issue by G3N0M3** [codingeverybody/codingyahac#1009]
# 해결하고자 하는 문제
Tensorflow 학습을 google colaboratory가 아닌 제 개인 노트북의 IDE(PyCharm)를 통해 하고 있습니다!
(이걸 local환경이라고 하는 것 같던데 아니면 죄송합니다...)
학습하는 도중 두가지의 질문이 생겼습니다!

1. Google colaboratory에서 Pandas와 Tensorflow를 사용하기 위해서는 따로 라이브러리 설치를 안해도 되는건가요? 혹시 이번 수업에서 Google colaboratory를 통한 학습이 권장되나요?

2. local 환경에서 Tensorflow를 사용하기 위해 명령 프롬프트에서 "pip install tensorflow"로 tensorflow를 설치하고 레모네이드 판매 예측 실습에서 아래와 같은 error가 발생했습니다! 무슨 문제가 있는것인가요?

# 코드 혹은 오류
![lemonade_tensorflow](https://user-images.githubusercontent.com/51051464/90724987-67d5fd00-e2fa-11ea-9e75-42555801621a.JPG)

작성한 코드는 변수명, 마지막에 model 사용 부분을 제외하고는 다 동일합니다!!
Error에 대한 메세지가 출력된 이후에
'''
print(model.predict(lemonade_indvar))
print(model.predict([[15]]))
'''
의 결과는 정상적으로 출력되었습니다.

# 환경
Window7, python

**Comment by progh2** [comment]
> Tensorflow 학습을 google colaboratory가 아닌 제 개인 노트북의 IDE(PyCharm)를 통해 하고 있습니다!
(이걸 local환경이라고 하는 것 같던데 아니면 죄송합니다...)

Local 환경 맞습니다. 👍 

> Google colaboratory에서 Pandas와 Tensorflow를 사용하기 위해서는 따로 라이브러리 설치를 안해도 되는건가요? 혹시 이번 수업에서 Google colaboratory를 통한 학습이 권장되나요?

기본적으로 필요한 라이브러리들이 세팅되어 있어서 바로 사용할 수 있고, 필요한 경우 pip으로 설치할 수도 있습니다. :)
꼭 코랩을 안쓰셔도 가능합니다.

> local 환경에서 Tensorflow를 사용하기 위해 명령 프롬프트에서 "pip install tensorflow"로 tensorflow를 설치하고 레모네이드 판매 예측 실습에서 아래와 같은 error가 발생했습니다! 무슨 문제가 있는것인가요?

GPU 관련 문제로 아래 방법을 해보시면 좋을 것 같습니다. 
https://junho0956.tistory.com/273 에 따르면 노트북이라서 gpu가 따로 없다면 단순히 `pip install tensorflow-cpu`로 설치해서 쓰시면 됩니다. 아니면 있어도 그냥 간편하게 CPU로 돌리겠다고 해도 이 패키지를 설치하면 됩니다.

만약 외장형 그래픽카드가 있고 활용하고 싶다면 아래 cudart64 설치해서 넣는 법을 참고하시면 될 것 같습니다.
https://beuracle77.tistory.com/5
https://mellowlee.tistory.com/entry/Windows-Tensorflow-Keras-%EC%82%AC%EC%A0%84-%EC%A4%80%EB%B9%84

**Comment by progh2** [comment]
추가로 로그가 에러가 아니고 워닝과 인포라서 무시하셔도 결과는 잘 나올 것입니다. 
저 워닝과 인포가 보기 싫으시면 로그 레벨을 올려서 안나오게 하는 것도 한 방법입니다.

https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information

```python
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
# 0 = all messages are logged (default behavior)
# 1 = INFO messages are not printed
# 2 = INFO and WARNING messages are not printed
# 3 = INFO, WARNING, and ERROR messages are not printed
```

**Comment by G3N0M3** [comment]
빠른 답변 감사합니다!! 감동입니다ㅜㅠ

답변해주신대로 tensorflow-cpu를 사용하고 싶은데 이 경우 tensorflow는 삭제하는 것이 좋을까요? 혹은 삭제해도 상관이 없나요?

**Comment by hephaex** [comment]
Tensorflow 1.15 나 Tensorflow 2.2 이상 버전이라면 XLA라는 기술이 적용되어  GPU와 CPU 구분 없이 사용하실 수 있습니다. 
물론 CPU로 동작하면 GPU보다는 많이 느립니다. 

Tensorflow 버전은 pip freeze 명령이나 python Ide에서 다음 코드로 확인하실 수 있습니다. 
```
import tensorflow as tf
print(tf.__version__)
```

**Comment by G3N0M3** [comment]
답변 감사합니다!!!
