### ISSUE TITLE
(github)웹호스팅강의내용중

### ISSUE THREAD

**Issue by schococake** [codingeverybody/codingyahac#101]
안녕하세요.
야학과 함께 웹페이지를 열심히 만들고 있는데요.
github에서 html파일 중에 사진이 여러장 들어가 있는 파일이 있습니다.
그렇다면 그 사진들도 깃헙 프로젝트 파일에 .html과 같이 올려야하는건가요?

**Comment by blackdew** [comment]
html에서 같은 폴더에 있는 이미지를 로딩하고 있다면 
서버에 올리실 때에 html이 있는 폴더에 동일하게 이미지도 올려주어야 해요.
