### ISSUE TITLE
//

### ISSUE THREAD

**Issue by ghost** [codingeverybody/codingyahac#1010]

**Comment by jiyongjung0** [comment]
혼자서 내지는 아주 적은 인원이 소프트웨어를 만드는 것이 꿈이신 것이 아니라면, 사실 디자인과 소프트웨어 개발을 한 사람이 할 일은 거의 없습니다. 특히나 기업 환경에서는요. `프로그래밍을 해본 적이 있는 디자이너` 같은 포지션이 아니라면 하나에 집중하시는 것이 더 낫지 않을까요?

이상 디자인은 ㄷ자도 모르는 소프트웨어 엔지니어의 답변이었습니다. 혹시 말씀하신 `디자인 전공을 유지하면서 프로그래밍 공부를 병행한 사람`혹은 전과를 하신 분을 주변에서 최대한 찾아보시고 조언을 구해보시면 어떨까요?

**Comment by agavero** [comment]
제 경험으로는 동아리 활동이나 복수전공 같은 것도 고려해보시는 건 어떨까 합니다.
제가 그래도 국내에서 꽤 큰 기업의 개발팀에 있었는데 인원을 충원할 때 동아리 활동 같은 것을 상당히 많이 고려하였고,
실제로 그런 인원들이 직접 무언가를 삽질하면서 만들어 본 경험이 많았기 때문에 업무에도 쉽게 적응하도 많은 도움이 되었습니다.
지금와서 보니 배워서 버리는 건 없더라고요...
저도 학부 때 뒤늦게 복수전공을 하였는데 다들 미쳤다고 했지만 그 때 처음으로 장학금까지 받았습니다.
지극히 개인적인 견해로 배울 수 있을 때 많은 것을 배워두는 것이 좋다고 생각합니다.
(스티브 잡스도 쓸데없다고 하는 서체를 공부해서 나중에 잘 써먹었잖아요 ㅋ)

**Comment by RayleighKim** [comment]
위 두분의 답변에서, 되려 제가 힌트를 얻고 즐거웠는데.
정리 요약 하면서 살짝 숟가락만 얹어볼까 합니다.
음. 논문작성을 이렇게 날로 먹을 수 있다면 참 좋을텐데

@jiyongjung0 협력자님 : 
1. 어떤 환경에서 일하느냐를 고려해보는 것이 좋다.
   --> 전과/집중/병행 등은 여기에 대한 답이 나오면 선택할 문제이고.
   --> 소규모가 아닌 기업환경이라면 집중하는 것이 더 나을 것이다.
2. 유사 고민을 한 선배를 찾아야 한다.
   --> 그 사람이 뭘 후회하고 있고, 지금 어떻게 하고 있는지를 알아야 구체적일 것이다.

@agavero 협력자님
1. 동아리를 고려해보라.
   --> 실제 인원 충원시 동아리 활동등을 많이 고려 한다.
   --> 왜냐하면, 삽질하며 만들어본자들이 업무에도 쉽게 적응한다.
2. 복수전공 했다. 다들 미쳤다 했지만 해냈다[!]
   --> 배워서 버리는 건 없다. 장기적으로 보라.
   --> 배울 수 있을 때 많이 배워야 한다.  ( 나중엔 힘들 수도 있다...?!)

덧붙임
1. 선택기준에 즐거움이 포함되었으면 좋겠습니다. 세상이 만만치가 않아서... 즐겁지 못하면 버틸수 조차 없을 수 있어요.
2. 조금 더 근본적인 질문을 하시는 것이 맞겠습니다. 컴공학과를 나온 다른 사람들에 비해 프로그래밍 공부에 뒤쳐지는 것이 '왜' 문제가 되는지. 끊임없이 스스로 '왜'를 던져보셔야 맞아요.  취업에 성공하기 위함인가요?  인공지능 연구자가 되려고 하시는걸까요?  뿌리가 될 키워드를 알려주세요.

**Comment by gendoh** [comment]
주 목표가 무엇인가에 따르겠지요.

평균적으로 보겠습니다. 업계엔 분명 "비정상"이 존재는 하지만요.

현재 대학 입학 전이고 디자인이 좋은 어플리케이션을 만드는 것이 목표라고 한다면, 일반적인 기대로 컴퓨터 전공에 디자인 부전공 혹은 복수 전공이 효율 적일 것입니다. 반대로 디자인을 함에 있어 어플리케이션 영역을 주 타겟으로 하고 싶다면 디자인 전공에 컴퓨터를 교양으로 들어도 될것입니다.

취업을 떠나서, 1인 혹은 소규모 업체에서 만들 거라 치면, 학위를 취득하냐 보다는 실제 지식이 중요하겠죠. 온라인 상의 많은 도구들로 복수 전공에 준하는 실력을 쌓을 수 있을 것입니다.

취업을 본다면, 주 활동 영역에 따라 전공을 선택해야 할것입니다. 디자인팀으로 취직할 것이냐 개발팀으로 취직할 것이냐. 개발할 줄 아는 디자이너, 혹은 디자인 할 줄 아는 개발자가 어드벤테이지가 될 수는 있겠지만 일단 해당 영역으로 취직이 되어야 합니다. 그리고 실무에선 전공자들이 자신의 영역을 잘 커버하며 협업으로 문제를 해결합니다. 특히나 전문 분야로 들어가서는, 디자인도 하면서 개발도 하기엔 일정 규모 이상의 프로젝트에선 힘듭니다.

대학, 전공, 학위라는게 자신의 전문분야라는 딱지를 붙이게 되고 신입 혹은 쥬니어 단계에선 큰 영향을 줄것입니다. 그동안 무엇을 주로 하고싶은 지에 따라 전공 선택하시면 될 듯 합니다. 시니어가 될때 쯤엔 어차피 공부 또 더해야 되고 시장이나 자신의 환경에 따라 새로운 선택지들이 생깁니다.
