### ISSUE TITLE
히든레이어의 원리가 무엇인가요?

### ISSUE THREAD

**Issue by sprel** [codingeverybody/codingyahac#1013]
# 히든레이어의 원리가 궁금합니다.
딥러닝에서 실제 신경망과 같은 구조를 구현하기 위해,
I/O 레이어 사이에 히든레이어를 넣는다고 배웠습니다.
그리고 이렇게 할 경우, Input 레이어에서 바로 Output 레이어로 연결되는 퍼셉트론보다도
정확도가 향상된다? 학습이 더 잘 이루어진다?고도 배웠습니다.

그런데 **히든레이어를 거치지 않는 방식과는 어떻게 다르길래**
**어떠한 원리로 히든레이어를 추가함으로 인해 정확도가 향상**되는지 궁급합니다.

더불어 **히든레이어 계층 수와 노드 수는 어떠한 기준으로 설정하는지**도 궁금합니다.

'딥러닝 히든레이어', '딥러닝 히든레이어의 필요성', '딥러닝 히든레이어의 원리' 등으로 구글링을 시도해보았습니다만
만족할 만한 답변을 얻지 못해 질문드립니다.

**Comment by jiyongjung0** [comment]
'다층 퍼셉트론' '멀티 레이어 퍼셉트론' 같은 걸로 검색을 해보시면 될 것 같은데요. :)

심하게 요약하자면 더 복잡한 구조를 표현할 수 있고, 따라서 더 복잡한 지식을 학습할 수 있다고 생각하시면 될 것 같습니다. 따라서 복잡한 문제에 대해서는 정확도가 향상될 수 있고요.

히든레이어 계층 수와 노드 수는 언뜻 생각하면 많을 수록 좋을 것 같지만, 과적합 문제도 있고해서 늘 그렇지는 않습니다. 그래서 여러 가지 구조를 다 돌려보면서 제일 좋은 결과가 나오는 구조를 찾아야 합니다. 심지어는 neural architecture search라고 계층 수와 노드 수를 포함하는 신경망 구조를 머신러닝으로 찾는 방식도 있습니다.

**Comment by RayleighKim** [comment]
> 그런데 히든레이어를 거치지 않는 방식과는 어떻게 다르길래 어떠한 원리로 히든레이어를 추가함으로 인해 정확도가 향상되는지 궁급합니다.

  멋진 질문을 던지셨어요. 하지만, 스스로 답을 내시기전에는 온전히 해결될 질문이 아닙니다. 딥러닝이 재미있다면  이 의문을 끝까지 끌어안고 가서 스스로 해결하셔야 맞아요. 스스로 해결하시는 순간 시야가 많이 바뀔겁니다.
  저는  **'연결'**과 **'특징 추출'**, **'추출할 특징의 수준'**, **end2end** 네가지 키워드로 딥러닝을 바라보고 있습니다.
  강아지 분류기를 만든다고 하면, 아웃풋 레이어는 아웃풋레이어의 인풋으로 부터 판단을 할 뿐입니다.
1.  아웃풋 레이어의 인풋이 바로 인풋레이어라면 가공되지 않은 정보를 바로 받아 판단하게 될 것이고
2. 아웃풋 레이어의 인풋이 히든레이어의 출력값이라면, 강아지orNot을 판단하는데 도움이 되는 특징들을 받아서 판단하게 될거에요.

  저는 이런 방식으로 이해하고 있습니다. 하지만 이게 질문자님의 답답함을 확 해소할 답변일지는 모르겠습니다.  하지만, 의문을 가지시는 것 자체가 매우 좋은 상황이고 발전의 밑거름이 될겁니다. 답답함을 즐기셔도 좋을 것 같아요. 공부를 잘하고 계신다는 근거입니다.
  이 의문이 Convolutional Neural Network를 공부하시게 되면 조금 더 직관적으로 답을 내리실 수 있게 될 수도 있을거에요. 이후에  feature engineering 과 representation learning 을 같이 공부해보시는 걸 추천드리겠습니다.

> 더불어 히든레이어 계층 수와 노드 수는 어떠한 기준으로 설정하는지도 궁금합니다.

  사실, 정말 궁금하여서 질문하시는 것이겠지만, 이 질문에 대해서는 위의 질문이 해결이 되어야 해결이 될거에요. 이 질문에만 한정하여 답변하자면... 딥러닝의 포문을 여신 아버지들 중 [한 분의 답변](https://www.quora.com/Artificial-Neural-Networks/Artificial-Neural-Networks-How-can-I-estimate-the-number-of-neurons-and-layers/answer/Yoshua-Bengio?share=7b58dc3b&srid=hqJd) 을 링크드리는 수 밖에 없습니다.
  먼저 해주신 위의 질문이 해결이 되어야 해요.

응원합니다.

**Comment by sprel** [comment]
두분의 답변 모두 감사합니다.
덕분에 말씀해주신 키워드들로 한번 더 찾아보고, 조금 더 공부하게 되었습니다.

답변의 내용을 처음에는 다 이해하지 못했지만,
공부해보고나니 답변해주신 내용들이 얼추 이해가 되었고, 제 궁금증에 대한 충분한 답변이 되었습니다.

진심 어린 답변 다시 한번 감사드립니다 :)
