### ISSUE TITLE
Tensorflow 1 - 13. 학습의 실제 파트 수식에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by eldertree777** [codingeverybody/codingyahac#1015]
# 해결하고자 하는 문제

1. 해당 스프레드시트에서 더하는값이 `0.0001` 이라고 적혀있습니다. 이값은  `Dloss/dt` 값에 의해 `0.0001`값을 더하거나 뺄수도있다는걸로 이해하였습니다. 이해한것이 맞는지 확인을 받고 싶습니다.

2.  `dt` 값의 의미와  `0.0001`값으로 설정된 이유에 대해 궁굼합니다. 영상에서는 미분값이라고 설명해주셨는데 이해가 부족하여 추가적인 설명을 부탁드립니다.

- 부족한 질문이지만 항상 고생하시고 이번 학습기회를 제공해신 머신러닝야학 선생님들에게 감사드립니다.

**Comment by blackdew** [comment]
1. 
맞습니다. 다만, 워크북은 0.0001을 더하는 것에 맞추어서 수식이 완성되어있습니다. 

2. 
미분이라는 건, 실제는 한 점에서의 순간 변화도를 계산하는 것인데요. 그것과 근사한 미분값을 구하는 방식이 아주 작은 값을 이동한 미분값을 사용하는 것입니다. 워크북은 해당 계산을 위해 사용한 아주 작은 값을 임의로 0.0001로 설정한 거에요. 그리고, 당연히 텐서플로우의 구현은 이렇게 되어있지 않습니다. :)
