### ISSUE TITLE
model warmstarting에 대한 질문입니다

### ISSUE THREAD

**Issue by tmtmaj** [codingeverybody/codingyahac#1018]
안녕하세요. 
자연어 처리를 공부하고 있는 학생입니다. 
model warmstarting에 대해 여쭙고자 이렇게 질문을 남기게 되었습니다.
 
# 해결하고자 하는 문제
저는 현재 pytroch를 사용하여 transformer 모델을 구성하고 기계 번역에 대한 연구를 진행하고 있습니다.
모델의 성능을 향상시켜보려고 여러가지 모듈을 추가해보거나 모델 구성을 바꾸면서 테스트를 하고 있는데요. 
현재까지는 모델을 변경할 때마다 매번 처음부터 훈련을 다시 시작했습니다. 
일정 수준의 성능을 위해서는 대략 30 epoch 정도를 훈련해야 하니 매번 수정할 때마다 결과를 확인하려면 하루 정도를 기다려야 했습니다. 
시간이 너무 아깝고 효율이 떨어져 방법을 찾아보니 model warmstarting (https://pytorch.org/tutorials/recipes/recipes/warmstarting_model_using_parameters_from_a_different_model.html) 이라는 방법이 있어서 적용했습니다. 

`modelB.load_state_dict(torch.load(modelA_checkpoint), strict=False)`

생각보다 간단하게 load_state_dict의 strict= False로 설정하면 modelA_checkpoint에 저장된 state가 modelB와 완전히 일치하지 않아도 오류가 발생하지 않았습니다. modelB에서 modelA_checkpoint에 저장된 state와 일치하는 부분만 load했습니다. 나머지 부분은 초기화되었습니다.

warmstarting 적용 과정에서 몇가지 의문이 생겼습니다.

1. 현재 제가 연구하고 있는 모델의 state는 

dict_keys(['args', 'model', 'optimizer_history', 'extra_state', 'last_optimizer_state'])

이러합니다.  

model은 load_state_dict 함수에 strict를 False로 설정할 수 있는데
optimizer는 load_state_dict 함수에 strict가 없어 checkpoint로부터 load하지 않고 처음부터 학습하도록 하였습니다.
optimizer의 파라미터를 load해오려고 하면 오류가 발생했습니다. 

`ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
(optimizer 부분을 수정해서 파라미터가 다른 것 같습니다)

먼저 default 모델을 훈련한 후, 모델의 일부를 수정했습니다.
그리고 default 모델의 파라미터로 그 수정된 모델을 초기화하고 싶을 경우에 model의 파라미터만 초기화하는 것이 맞나요? 

2.  모델을 수정한 후 학습해둔 default 모델의 파라미터를 이용하는 다른 방법이 있다면 알려주시면 감사하겠습니다.  

감사합니다!!

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
우분투(google colab)
pytorch 1.6.0

**Comment by RayleighKim** [comment]
파이토치에 능숙치 않음을 미리 말씀드립니다.

>default 모델의 파라미터로 그 수정된 모델을 초기화하고 싶을 경우에 model의 파라미터만 초기화하는 것이 맞나요?
>모델을 수정한 후 학습해둔 default 모델의 파라미터를 이용하는 다른 방법이 있다면 알려주시면 감사하겠습니다.

질문하신 내용이, model의 parameter만 initialize해야 하는가, 다른 hyper parameter들도 initialize 해야 하는가, 라면 모델의 parameter만 초기화 해야 하는것이 맞습니다만,  제가 질문을 명확히 이해를 못하고 있습니다. 아래와 같은 절차를 하고 싶으신걸까요?

1. 모델a의 구조를 잡았음.
2. 모델a를 학습시켰음
3. 학습된 모델a의 구조를 약간 변경하여 모델 b를 만들었음. (여길 어떻게 하느냐에 따라 답변이 많이 달라질텐데)
4. 모델 b에 모델 a의 가중치를 덮어씌우고 싶음.

위와 같은걸 원하시는 거라면, 공통된 layer들은 손쉽게 가중치를 덮어씌우는 기능이 반드시 있을거에요. 또한, 가중치를 하나하나 조정하실 수도 있습니다.

keras기준으로는 get_weights, set_weights로 굉장히 손쉽게 할 수 있습니다.
pytorch도 기능이 있는 것 같아요. [참고 링크](https://discuss.pytorch.org/t/replace-trained-layer-weights-with-modified-weights/23456)

**Comment by tmtmaj** [comment]
안녕하세요. 
답변 너무 감사드립니다. 
 
제가 질문을 장황하게 늘어놓기만 하고 제대로 설명을 하지 못한 것 같습니다. 
제 질문의 요지는 
 
1. 모델 a 훈련 후 checkpoint_epoch30 저장 (checkpoint에는 model parameter, criterion parameter, optimizer parameter.. 식으로 구분되어 저장)
2. 모델 a를 수정하여 모델 b를 구성 
3. checkpoint_epoch30을 모델 b로 load - 에러 (새로운 모듈에 대한 parameter가 없음)
4. pytorch의 기능 중 checkpoint에 저장된 파라미터 중 model parameter와 criterion parameter는 load시  모듈은 자동 초기화하는 기능을 활용하여 모델 b를 훈련 - 에러 없이 정상 훈련 가능
(알고보니 checkpoint의 model parameter는 dictionary 구조로 name에 따라 저장되는 반면 optimizer parameter는 name이 없이 저장되어 완전 일치하는 모델이 아니면 load가 불가능하다고 합니다.)
 
여기서 제 질문은 
 
"model parameter만 checkpoint로부터 load하고 다른 parameter들은 처음부터 train하는 것처럼 초기화하는 것" 과 
"optimizer parameter까지도 load 하는 것" 중 어떤 것이 제대로 된 model warmstarting인지 입니다.
 
이미 생활 코딩 학습 기간이 끝났지만, 혹시 답변이 가능하시다면 답변 부탁드립니다.
감사합니다.
 
 
-----Original Message-----

**Comment by RayleighKim** [comment]
아하. 몇가지 말씀을 드릴 수 있을 것 같아요.

1. 기본적으로는 잘 학습된 모델 parameter들만 잘 가져와서 사용한다면 warmstart가 맞습니다.

2. 기본은 있으나 어떤것이 제대로냐.... 하는 것은 무엇을 기준으로 두시냐에 따라 다르며.. 동시에, 성능이 더 좋은 선택이 제대로 된 것일겁니다. 성능이 말해줄거에요. 

3. 절차..를 조금 더 쉬운 방법을 찾으실 수도 있을 것 같습니다. 학습된 모델 a를 고쳤다면, 고친부분제외하고는 모델a의 가중치가 그대로 살아있는 방법이 파이토치에도 반드시 있을거에요.

4. Optimizer에 적용할 hyperparameter들은 다시 잡아주시는 것이 효율적일 수 있습니다.
