### ISSUE TITLE
오렌지3 시작이 안 됩니다ㅠㅠ

### ISSUE THREAD

**Issue by mm211** [codingeverybody/codingyahac#1022]
# 해결하고자 하는 문제

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도우10home 64비트 환경이고 오렌지3 설치할때는 기본 체크되어 있는 것 모두 체크해서 설치했습니다. 
파이썬 최신 버전이 이전에 설치되어있었는데 미니콘다라는 것 추가 설치를 하는 게 기본옵션이라 그렇게 진행했고요

# 시도해본 방법
프로그램을 지운 후 다시 재설치해 보았으나 에러 한 줄 뜨지 않고 그냥 프로그램이 열리지 않아요ㅠㅠ 어떻게 하면 될까요?
파이썬 버전끼리 뭔가 충돌하나 해서 파이썬다 지우고 다시 인스톨해도 안 되고
마지막으로 모든 프로그램 다 지웠다가 파이썬만 다시 깔고 cmd에서 pip를 통해 설치를 했더니 진행이 되다가 이런 에러 메시지가 뜹니다. 뭐가 문제인걸까요

C:\Users\gram>pip install orange3
Collecting orange3
  Using cached Orange3-3.26.0-cp38-none-win32.whl (2.5 MB)
Collecting orange-canvas-core<0.2a,>=0.1.15
  Using cached orange_canvas_core-0.1.15-py3-none-any.whl (451 kB)
Collecting scikit-learn!=0.23.0,>=0.22.0
  Downloading scikit_learn-0.23.2-cp38-cp38-win32.whl (6.0 MB)
     |████████████████████████████████| 6.0 MB 1.3 MB/s
Collecting scipy>=0.16.1
  Downloading scipy-1.5.2-cp38-cp38-win32.whl (28.4 MB)
     |████████████████████████████████| 28.4 MB 1.3 MB/s
Requirement already satisfied: requests in c:\users\gram\appdata\local\programs\python\python38-32\lib\site-packages (from orange3) (2.23.0)
Collecting orange-widget-base>=4.6.0
  Using cached orange_widget_base-4.7.0-py3-none-any.whl (225 kB)
Collecting serverfiles
  Using cached serverfiles-0.3.0.tar.gz (10 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.1-cp38-cp38-win32.whl (199 kB)
Requirement already satisfied: setuptools>=36.3 in c:\users\gram\appdata\local\programs\python\python38-32\lib\site-packages (from orange3) (47.1.0)
Collecting pyqtgraph>=0.10.0
  Downloading pyqtgraph-0.11.0-py3-none-any.whl (800 kB)
     |████████████████████████████████| 800 kB 2.2 MB/s
Collecting AnyQt>=0.0.8
  Using cached AnyQt-0.0.10-py2.py3-none-any.whl (45 kB)
Collecting numpy>=1.16.0
  Using cached numpy-1.19.1-cp38-cp38-win32.whl (10.9 MB)
Collecting keyring
  Using cached keyring-21.3.1-py3-none-any.whl (31 kB)
Collecting matplotlib>=2.0.0
  Using cached matplotlib-3.3.1-cp38-cp38-win32.whl (8.3 MB)
Collecting xlrd>=0.9.2
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 1.3 MB/s
Collecting openTSNE>=0.3.11
  Using cached openTSNE-0.4.4.tar.gz (876 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\gram\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gram\\AppData\\Local\\Temp\\pip-install-kqxa4u0q\\opentsne\\setup.py'"'"'; __file__='"'"'C:\\Users\\gram\\AppData\\Local\\Temp\\pip-install-kqxa4u0q\\opentsne\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\gram\AppData\Local\Temp\pip-pip-egg-info-9ah7sb2e'
         cwd: C:\Users\gram\AppData\Local\Temp\pip-install-kqxa4u0q\opentsne\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gram\AppData\Local\Temp\pip-install-kqxa4u0q\opentsne\setup.py", line 224, in <module>
        if has_c_library("fftw3"):
      File "C:\Users\gram\AppData\Local\Temp\pip-install-kqxa4u0q\opentsne\setup.py", line 116, in has_c_library
        compiler.link_executable(compiler.compile([name]), name)
      File "c:\users\gram\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 327, in compile
        self.initialize()
      File "c:\users\gram\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\gram\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\users\gram\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by progh2** [comment]
위 에러 내용 상으로 봐서는 
```
raise distutils.errors.DistutilsPlatformError(
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```
Visual Studio를  설치하면 될 것 같습니다. 뭔가 컴파일 해야하는데 필요한 라이브러리가 없어서 그렇다는 내용 같네요.. 

설치된 Orange를 관리자 권한으로 실행해도 꺼지나요? 
(파이썬 버전 문제로 실행이 안되는건 아닐까 조심스럽게 생각해봅니다)

정 안되면 번거롭더라도 윈도우 새 계정 만들어서 설치해서 실행해보실 수 있을까요? 
그래도 안되면 원격접속으로라도 해서 봐드릴까 하네요..

**Comment by mm211** [comment]
비주얼 스튜디오 C++ 환경 설치하고 나서 pip로 재설치하니 실행되네요, 도움에 감사드립니다 👍
