### ISSUE TITLE
프로그래밍 도중에 파일을 잘못 지웠습니다. 파일을 복구할 수 있는 방법이 있을까요? 

### ISSUE THREAD

**Issue by jungyun2916** [codingeverybody/codingyahac#103]
HTML 프로그래밍 문제에 대해 질문하겠습니다. 저는 HTML을 코딩할 때에는 아톰을 사용해서 프로그래밍을 하는데요. 제가 프로그래밍을 하다가 파일을 잘 못 지워버렸는데 이 파일을 다시 복구할 수 있는 방법이 없을 까요? (Ctrl+z를 해도 복구가 안되네요;;;)

**Comment by blackdew** [comment]
파일을 복구하는 방법은 어렵습니다. 
'파일 복구'라는 검색어로 검색하시면 여러가지 도구가 있는데요. 원하는 파일을 실제로 복구가 가능한지는 해보기 전에는 알 수 없어요. 복구를 못할 가능성이 높습니다. 

아쉽지만 고민하고 작업했던 내용은 jungyun2916님의 머리속에 그대로 남아있을 테니.. 
복습을 한다는 생각과 함께 머릿속에 있는 내용을 바탕으로 파일을 복구해 보시는 것을 권해드립니다.
