### ISSUE TITLE
운영체제

### ISSUE THREAD

**Issue by Juha3141** [codingeverybody/codingyahac#1032]
64비트에서 하드웨어 멀티태스킹은 어떻게 하는건가요? 소프트웨어 멀티태스킹도요

감사합니다

**Comment by egoing** [comment]
궁금하신 부분의 맥락을 조금 더 자세히 알려주시면 좋을 것 같습니다. 
64비트로 특정해서 질문하신 이유도 말씀해주세요.

**Comment by Juha3141** [comment]
아 이미 다 해결했어요, 저거 날짜 보면 3개월 전이잖아요...
