### ISSUE TITLE
select와 input 태그 옮기는 법

### ISSUE THREAD

**Issue by G0Dpapa** [codingeverybody/codingyahac#104]
<img width="1280" alt="2018-01-10 7 55 10" src="https://user-images.githubusercontent.com/34954785/34769197-6a1a1c8a-f640-11e7-9e2d-7a08c9cac841.png">
<img width="988" alt="2018-01-10 7 56 32" src="https://user-images.githubusercontent.com/34954785/34769217-79a211b2-f640-11e7-9b6a-a7893fc0bfd9.png">
select와 input의 태그를 크게한 후에 밑에 빈 여백을 없애고 가운데로 옮길 수 있는 방법이 있나요?

**Comment by cyppi** [comment]
html 안의 내용이 크게 보이거나 가운데로 옮기는 일들은 CSS를 공부해보시면 될거 같아요.
style 이라는 태그안에 해당 요소들을 어떻게 보이게 할것인지 정의하면 됩니다. 
아직 코딩야학3기에서는 그부분까지 진도가 나가진 않았는데, 아마도 이전 코딩야학 내용이나, 생활코딩에서 내용을 찾아보시면 될거 같아요
