### ISSUE TITLE
아톰 script 작동 오류

### ISSUE THREAD

**Issue by nuewsun** [codingeverybody/codingyahac#1040]
# 해결하고자 하는 문제
script로 파이썬을 실행하려 하면 자꾸 오류가 뜹니다

# 코드 혹은 오류
```
  
![1608299158758](https://user-images.githubusercontent.com/76214070/102621416-da5cc980-4182-11eb-9ffb-0d76a53804d3.png)

```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
windows 10, python 3.9

# 시도해본 방법
다 지웠다 깔아보기도 했는데 해결이 안돼요ㅜㅜㅠㅠ  
도와주세요

**Comment by nuewsun** [comment]
사진을 첨부했는데 보이지가 않네요... 코드의 결과가 실행되어야 하는 부분에 코드가 실행이 되지 않고 세모모양의 경고표시가 뜹니다ㅜㅠㅠㅠ 어떻게 해결해야 하나요??

**Comment by jeuxdeau** [comment]
아직도 같은 문제가 발생하고 계신가요? 경고 표시가 뜬다면, 경고 표시 삼각형 위에 마우스를 올렸을 때 어떤 경고 문구가 나오는지 함께 보여주시면 좋을 것 같습니다.

**Comment by nuewsun** [comment]
아무 문구도 나오지 않습니다 
그래서 무엇이 문제인지 더 모르겠어요

**Comment by jeuxdeau** [comment]
감사합니다. 우선 1) Windows에 Python이 설치되어 있는지 2) 설치되어 있다면 환경변수가 잘 설정되어 있는지 정도를 확인해볼 수 있을 것 같은데요, 

https://dojang.io/mod/page/view.php?id=2158 이 링크의 3.3.1번을 따라가면 실행이 잘 되시나요?

**Comment by nuewsun** [comment]
python 은 설치되어 있고 평소에도 명령 프롬프트로 코드를 실행하고 있었습니다.
IDLE로 실행시켜봐도 잘 작동이 되는데, 아톰 script만 안됩니다 ㅜㅠㅠ
그런데 (2)에서 말씀하신 환경변수가 어떻게 설정되어 있어야 하는지 알려주실 수 있을까요?

**Comment by jeuxdeau** [comment]
![image](https://user-images.githubusercontent.com/22112344/103120114-b258f300-46b9-11eb-87db-7b68a6a14eeb.png)

명령 프롬포트에서 python을 입력하셨을 때 실행이 잘 되신다면 환경 변수는 제대로 설정되어 있을 것 같은데요,
한 번 더 확인해 보고 싶으시면 명령 프롬포트에서 `python --version`을 입력해서 3.9.x 버전이 표시되는지 확인해보실 수 있습니다.

![image](https://user-images.githubusercontent.com/22112344/103119878-aa4c8380-46b8-11eb-928b-35515553ef17.png)

Run Script를 하신 후에 이 버튼을 클릭해 보시면 새로운 탭이 열리고 맨 첫번째 줄에 `[Command: python -u C:\...\...\...\hello.py]` 와 같은 명령어가 뜨는데,
버튼을 눌렀을 때 탭에 실행 결과가 어떻게 적혀 있었는지 저에게 보여주실 수 있나요?
또 python~...py 명령어 부분을 복사해서 명령 프롬포트에 붙여넣기 해도 실행이 잘 되시는지요?

예:
![image](https://user-images.githubusercontent.com/22112344/103120326-999d0d00-46ba-11eb-8e60-5d0c194a6a7a.png)

![image](https://user-images.githubusercontent.com/22112344/103120144-dddbdd80-46b9-11eb-80ef-9059ec737d63.png)

**Comment by nuewsun** [comment]
우선 python --version 을 입력하니 python 이라고만 나왔습니다. ![파이썬 버전 확인](https://user-images.githubusercontent.com/76214070/103121010-96575080-46bd-11eb-9652-c966db9449c9.PNG)


그리고 말씀하신 버튼을 눌러보니 아래 사진처럼 나왔고요
![script 실행 결과](https://user-images.githubusercontent.com/76214070/103121066-d3234780-46bd-11eb-989e-829ae10af6fc.PNG) 

명령어를 복사해 프롬프트에 옮겨보니 또 python 이라고만 나옵니다
![명령어 복사](https://user-images.githubusercontent.com/76214070/103121105-01a12280-46be-11eb-8ed5-e6dfd202a27c.PNG)

**Comment by jeuxdeau** [comment]
앗 그렇군요, 도움 주셔서 감사합니다. 명령어로 python을 부르면 python 3이 잘 불려져야 할 것 같은데요,

- https://allhpy35.tistory.com/m/24
- https://mechasolution718253976.wpcomstaging.com/2017/12/12/윈도우즈10에서-파이썬-환경변수-설정하기/
- https://somjang.tistory.com/249

이 링크들처럼 환경 변수를 다시 설정해보시겠어요? (구글에 "윈도우 10 파이썬 환경변수" 같은 식으로 검색하셔도 자세한 설명이 많이 나오는 것 같아요)

어려우시면... 파이썬을 삭제하고 재설치할 때 환경변수를 설정하도록 하는 옵션을 체크해주셔도 됩니다
https://medium.com/@psychet_learn/python-기초-2장-python-설치-및-환경설정-windows-ver-b030d96bcbd0

**Comment by nuewsun** [comment]
헐 됐어요!!!!!! 진짜 너무 감사합니다 ㅜㅠㅠㅠㅠ 지금 날아갈 것 같아요 진짜 완전 감사합니다
