### ISSUE TITLE
머신러닝야학 1기 자료 업데이트

### ISSUE THREAD

**Issue by jeuxdeau** [codingeverybody/codingyahac#1044]
안녕하세요,
머신러닝야학 1기 자료를 복습하다 발견한 몇 가지 (사소한) 것들이 있어서 질문 드립니다.

### 머신러닝1: 머신러닝머신
- 강의: https://opentutorials.org/course/4548/28899
- 애플리케이션: https://ml-app.yah.ac/
- 아래 화면과 같이, 텍스트를 입력하는 곳에 따옴표(')를 넣으면 에러가 발생합니다.

![스크린샷 2020-12-24 오전 12 33 01](https://user-images.githubusercontent.com/22112344/103012908-9d784480-457f-11eb-9382-91b5fb147ed3.png)

+) 목록에 있는 함수들 중 "전동", "자동차", "도로교통시스템", "국가 행정 시스템"은 무엇인가요?

### Tensorflow 101: 실습 환경 - Google Colaboratory
- 강의: https://opentutorials.org/module/4966/28969
- 영상: https://youtu.be/91E0qenm7W4?t=82
- 영상 1:22부터 G Suite Marketplace에서 Colaboratory 앱을 검색하도록 안내하고 있는데, 현재는 Marketplace에서 Colaboratory가 검색되지 않습니다.
  - https://workspace.google.com/u/2/marketplace

==========

감사합니다.

**Comment by opentutorialsorg** [comment]
버그 리포트에 추가하도록 하겠습니다.
우빈님 고맙습니다.

**Comment by egoing** [comment]
추가 질문을 못 봤네요. 

"전동", "자동차", "도로교통시스템", "국가 행정 시스템" 는 수업 뒷쪽에서 나오는데요. 
이런 것들을 머신러닝으로 제어 할 수 있다고 상상해보세요.라는 이야기를 하기 위한 가짜 기능들입니다. ㅎㅎ 

@blackdew 님 우빈님께서 아래와 같이 알려주셨습니다. 확인해보시면 좋을 것 같습니다.
 
강의: https://opentutorials.org/module/4966/28969
영상: https://youtu.be/91E0qenm7W4?t=82
영상 1:22부터 G Suite Marketplace에서 Colaboratory 앱을 검색하도록 안내하고 있는데, 현재는 Marketplace에서 Colaboratory가 검색되지 않습니다.
https://workspace.google.com/u/2/marketplace
