### ISSUE TITLE
코딩 잘하는 방법에 대해 배우고 싶습니다.

### ISSUE THREAD

**Issue by iwtbh** [codingeverybody/codingyahac#105]
제가 그나마 제일 할 줄아는 언어가 C언어인데요. 제가 c언어문법을 구조체까지 배웠습니다.
https://www.acmicpc.net/ 이 사이트에서 c언어 for문 관련 문제를 다 풀어봤습니다.
그런데 몇몇 문제가 아예 풀리지 않아서 이곳저곳을 다 찾아보았고 여러 시도를 하였으나 소용없었습니다.
문법만 할 줄 안다고 해서 코딩 실력이 늘지 않는다는 말이 딱 맞는 것 같습니다.
어떻게 하면 코딩 실력을 늘릴 수 있을까요? (다른 사람이 만들어 놓은 예제 해석은 나름 잘합니다)

**Comment by blackdew** [comment]
1000만개 이상의 혹은 1억개 이상의 데이터가 있을때에 
이 데이터를 어떻게 저장해 둘 것인지 (데이터 구조)
그 데이터 중에 내가 원하는 정보를 어떻게 빠르게 찾아올 수 있는지 (알고리즘)
두 가지를 여러가지 방법으로 고민해 보시면 도움이 됩니다. 

그리가, 기타 여러가지 프로그램들을 이 관점에서 바라보는 연습을 하시는 것도 도움이 될 거에요. 

즐겁고 재미있게 프로그래밍을 하고 있다면 그것이 코딩실력을 늘릴 수 있는 가장 좋은 방법일 것 같고요. 
더해서 작은 문제라도 자기의 것을 정의하고 그것을 프로그래밍을 활용해서 해결하면, 
그래서 작은 성취들을 쌓아나갈 수 있으면 더욱 좋을 것 같아요.
