### ISSUE TITLE
야학2기 신청자인데요. 주식예측 모델을 만들고 싶은데 조언 부탁합니다.

### ISSUE THREAD

**Issue by huniel** [codingeverybody/codingyahac#1050]
안녕하세요. 이번에 야학 2기 신청해서
1월 3일까지 올리셨던 좋은 강의들을 다 실습하고 시청했습니다.
좋은 강의 감사합니다.

# 해결하고자 하는 문제
그런데 평소에 제가 주식 예측 모델을 만들고 싶었는데,
어떻게 시작해야 할지 사실 주식도 잘은 모르고 캔들그래프 정도만 볼 수준입니다.
먼저, 현재 실제 주식 데이터를 어떻게 구해야 되고, 독립변수, 종속변수를 어떻게 분류하며,
어떤 학습방법으로 모델을 만들어야 하는지 정확히 모르겠네요.

질문이 너무 광범위해서 죄송합니다.

그리고 주식관련 예측모델을 이미 만든 예가 있다면 알려주시면 감사하겠습니다.

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 개발환경
intel i7, GTX1080

windows10,: 
1. colab
2. python2.4+vscode+Tensorflow 2.4.0 + Python 3.8.7 +  Cuda 11.1.0 + cuDNN 8.0.4 

Linux
1. WSL2 + 우부투18.04L + Docker + remote ssh vscode

# 시도해본 방법
먼저 실제 주식데이터를 어떻게 얻을지 부터 막히네요.

**Comment by tomeido** [comment]
유튜버 시간여행tv에서 추천해주신 책이 있습니다.
https://www.youtube.com/watch?v=jlQe0kH0UdM 여기 17분에 보시면
파이썬으로 배우는 알고리즘 트레이닝 책을 추천하십니다.
그런데 이분이 말씀하시길 이걸 해보면 
알고리즘으로 주식을 예측하는 것이 얼마나 말이 안되는 건지 알 수 있다네요.

**Comment by huniel** [comment]
책 추천감사합니다. 그런데 "알고리즘으로 주식을 예측하는 것이 말이 안된다는 것은" 무슨 뜻일까요?
주식예측은 DNN으로 예측이 어렵다는 얘기인가요?

**Comment by corazzon** [comment]
실제 주가 데이터를 얻는 방법은 여러 가지가 있습니다. 
직접 수집을 하는 방법도 있지만 수집 라이브러리를 통해 비교적 간단하게 해볼 수 있습니다.

pandas-datareader와 FinanceDataReader를 추천합니다.
주가 데이터 뿐만 아니라 각종 경제 지표도 함께 수집할 수 있습니다.

* [FinanceData/FinanceDataReader: Financial data reader](https://github.com/FinanceData/FinanceDataReader)
* [FinanceDataReader 사용자 안내서 | FinanceData](https://financedata.github.io/posts/finance-data-reader-users-guide.html)
* https://pandas-datareader.readthedocs.io/en/latest/readers/index.html

**Comment by huniel** [comment]
> 실제 주가 데이터를 얻는 방법은 여러 가지가 있습니다.
> 직접 수집을 하는 방법도 있지만 수집 라이브러리를 통해 비교적 간단하게 해볼 수 있습니다.
> 
> pandas-datareader와 FinanceDataReader를 추천합니다.
> 주가 데이터 뿐만 아니라 각종 경제 지표도 함께 수집할 수 있습니다.
> 
> * [FinanceData/FinanceDataReader: Financial data reader](https://github.com/FinanceData/FinanceDataReader)
> * [FinanceDataReader 사용자 안내서 | FinanceData](https://financedata.github.io/posts/finance-data-reader-users-guide.html)
> * https://pandas-datareader.readthedocs.io/en/latest/readers/index.html

좋은 정보 감사합니다.^^
