### ISSUE TITLE
소프트웨어학과 4학년 올라가는 학생입니다.

### ISSUE THREAD

**Issue by RockMiin** [codingeverybody/codingyahac#1053]
올 해 소프트웨어학과 4학년에 올라가는 학생입니다.
학교에서 AI, 딥러닝과 같은 AI 관련 수업을 들어 기본적인 모델과 사용 방법, 어떤 것이 있는지는 어느 정도 인지한 상태입니다.
학교에서 인공지능 관련 수업이 이제 없는데 어떠한 방법으로 공부를 해 나가야 할 지 감이 안 잡혀 질문드립니다.
교내에서 한 수업들은 모두 정형화된 데이터 셋을 가지고 모델을 학습시키고 예측을 시켰는데, 앞으로 실무에서 사용해야 할 데이터는 비정형화 되있는 데이터가 대부분이며 데이터의 특성에 따라 전처리 방식이 다른 것으로 알고 있는데 이러한 방법에 대해 어떻게 공부를 해야 하며 앞으로의 진로를 어떻게 잡아야 할지 도저히 모르겠어 질문드립니다.
답변 기다리겠습니다. 감사합니다.

**Comment by storykim** [comment]
안녕하세요.

말씀하신 문제에 대한 수많은 해결책이 있겠지만, 저는 두 가지 방법을 알려드리고싶습니다.

1. 인턴십
실무에서 사용하는 테크닉들을 배우는 가장 빠른 방법 중 하나는 실제로 일을 해보는 것입니다. 관심있으신 기업의 AI 관련 부서에서 인턴십을 해보신다면 데이터는 어떻게 수집되고 가공되어 학습이 되는지, 그렇게 학습된 모델은 어떻게 사용자들에게 전달되는지, 그 과정에서 어떤 추가적인 고민들을 해야하는지를 몸소 느껴보실 수 있습니다. 물론 그 과정에서 내가 어떤 부분에 대한 지식이 부족하며 앞으로 어떤 공부를 하면 될지에 대한 계획도 자연스레 생기게 될 것 같습니다.

2. Kaggle
Kaggle은 일종의 머신러닝 대회 플랫폼입니다. 기업이나 특정 단체에서 데이터와 과제를 내걸면 전세계의 수많은 사람들이 그 과제를 푸는 플랫폼인데요, 물론 기업이 어느정도 데이터를 정형화해서 넘겨주기는하지만 여전히 전처리에 대한 많은 고민을 해야만 좋은 결과가 나오기 때문에 이 플랫폼도 다양한 방식으로 활용하실 수 있습니다.
첫 번째 활용법은 물론 직접 대회에 참여해보는 방법입니다. 전세계의 쟁쟁한 실력자들이 상금을 위해 노력하기때문에 처음부터 순위권에 드는 것은 굉장히 힘든 일이겠지만, 배움을 목적으로 참여하셔서 문제에 대한 고민을 하시다보면 원하시는 방향으로의 성장이 충분히 이루어지실 것 같습니다. 
두 번째 활용법은 각 대회의 Discussion 게시판을 활용하는 방법입니다. 지나간 대회 뿐만 아니라 현재 진행 중인 대회에도 수많은 게시글들이 Discussion 게시판에 올라와있는데요, 자신들이 어떤 식으로 데이터를 가공했는지, 어떤 모델을 사용했는지, 그래서 최종적으로 어떤 성과를 이루었는지를 잘 정리해둔 글들이 많습니다. 이런 글들을 통해서 실제 데이터를 가공하는데 어떤 테크닉이 사용되는지 배우실 수 있을 것 같습니다.

답변이 도움이 되셨기를 바래요.

**Comment by RockMiin** [comment]
> 안녕하세요.
> 
> 말씀하신 문제에 대한 수많은 해결책이 있겠지만, 저는 두 가지 방법을 알려드리고싶습니다.
> 
> 1. 인턴십
>    실무에서 사용하는 테크닉들을 배우는 가장 빠른 방법 중 하나는 실제로 일을 해보는 것입니다. 관심있으신 기업의 AI 관련 부서에서 인턴십을 해보신다면 데이터는 어떻게 수집되고 가공되어 학습이 되는지, 그렇게 학습된 모델은 어떻게 사용자들에게 전달되는지, 그 과정에서 어떤 추가적인 고민들을 해야하는지를 몸소 느껴보실 수 있습니다. 물론 그 과정에서 내가 어떤 부분에 대한 지식이 부족하며 앞으로 어떤 공부를 하면 될지에 대한 계획도 자연스레 생기게 될 것 같습니다.
> 2. Kaggle
>    Kaggle은 일종의 머신러닝 대회 플랫폼입니다. 기업이나 특정 단체에서 데이터와 과제를 내걸면 전세계의 수많은 사람들이 그 과제를 푸는 플랫폼인데요, 물론 기업이 어느정도 데이터를 정형화해서 넘겨주기는하지만 여전히 전처리에 대한 많은 고민을 해야만 좋은 결과가 나오기 때문에 이 플랫폼도 다양한 방식으로 활용하실 수 있습니다.
>    첫 번째 활용법은 물론 직접 대회에 참여해보는 방법입니다. 전세계의 쟁쟁한 실력자들이 상금을 위해 노력하기때문에 처음부터 순위권에 드는 것은 굉장히 힘든 일이겠지만, 배움을 목적으로 참여하셔서 문제에 대한 고민을 하시다보면 원하시는 방향으로의 성장이 충분히 이루어지실 것 같습니다.
>    두 번째 활용법은 각 대회의 Discussion 게시판을 활용하는 방법입니다. 지나간 대회 뿐만 아니라 현재 진행 중인 대회에도 수많은 게시글들이 Discussion 게시판에 올라와있는데요, 자신들이 어떤 식으로 데이터를 가공했는지, 어떤 모델을 사용했는지, 그래서 최종적으로 어떤 성과를 이루었는지를 잘 정리해둔 글들이 많습니다. 이런 글들을 통해서 실제 데이터를 가공하는데 어떤 테크닉이 사용되는지 배우실 수 있을 것 같습니다.
> 
> 답변이 도움이 되셨기를 바래요.

친절한 답변 감사합니다. 추가 질문이 있어 리플을 답니다.
지금 교내 학점연계 인턴십을 하고 있습니다. 하지만 어떻게 진행을 해 나가야 하는지 감이 안잡힙니다. 수고스러우시겠지만 다른 방법에는 무엇이 있는지도 궁금해서 연락드립니다. 예시 등을 추가해서 설명해 주셔도 좋을 것 같습니다.  추가적으로 어떤 기업에서 하는 어떠한 프로그램이 있는데 참여하면 좋을 것 같다는 예시도 들어주시면 감사하겠습니다. 구글링을 수차례 하며 검색을 해봐도 어떠한 루트로 공부를 해 나가야 한다는 것은 나온게 없더라구요. 공부 루트를 대략적으로나마 세우고 싶습니다.

**Comment by jeuxdeau** [comment]
> 구글링을 수차례 하며 검색을 해봐도 어떠한 루트로 공부를 해 나가야 한다는 것은 나온게 없더라구요. 공부 루트를 대략적으로나마 세우고 싶습니다.

그런 게 없기 때문이 아닐까요? (ㅠㅠ) 게임처럼 [전사의 길]: 1. 무슨 퀘스트 깨고 => 2. 다음 거 깨고 => 3. 또 다른 거 깨면  2차 전직이 되십니다 이러면 참 좋을텐데요. 설명해주신 학교 수업과 실무의 차이랑 비슷한 것 같습니다. 학교에는 정해진 교과과정이 있고 그걸 따라가기만 하면 되지만 학교 밖에는 수강편람이 없는 것처럼요.

로드맵 roadmap 이라는 키워드가 말씀하신 "루트"에 가까울 것 같기도 한데요, (i.e., "머신러닝 로드맵", "딥러닝 로드맵" 등으로 검색해 보았습니다)
- 책 마인드맵 같은 자료도 있고 https://www.mindmeister.com/812276967/_ (한국어)
- 추천하는 공부 방향이 정리되어 있기도 합니다 https://github.com/mrdbourke/machine-learning-roadmap (영어)
- 로드맵은 아니지만, github을 돌아다니다 보면 사람들이 이것저것 정리해놓은 게 있기도 하고 https://github.com/teddylee777/machine-learning (한국어)
- 정부나 기업에서는 보통 AI/데이터 경진대회 라는 이름으로 행사를 여는 것 같은데 저도 참여해본 적이 없어서 검색해서 가장 먼저 나오는 링크를 가져왔습니다... ^^;;  https://theorydb.github.io/dev/2019/06/23/dev-competition-list/ (한국어)
