### ISSUE TITLE
진로 관련 질문입니다

### ISSUE THREAD

**Issue by eric2925** [codingeverybody/codingyahac#1055]
밑에 질문했던 사람인데요... 친절한 답변 감사드립니다^^ 제가 코딩을 꼭 하고싶은건 아니고 알고리즘을 만들고싶은데.. 그래도 컴퓨터공학과를 가는게 맞을까요?

**Comment by RickyPark** [comment]
저는 컴공 출신입니다만 말씀하신 내용을 봐서는 수학과가 어울릴지도 모르겠습니다. (수학과 분들의 답변도 듣고 싶어지네요.) 다만 [아래 글의 답변](https://github.com/codingeverybody/codingyahac/issues/1049#issuecomment-753744421)에도 있듯이 머신러닝에 대해 더 알아보신 이후에 고민을 이어가시는 것을 추천드리고 싶습니다.

p.s. 아래에서 답변해주신 분들도 계시니 그 쪽에서 이야기를 이어가시는 것이 답변자분들께도 & 추후에 이 글을 읽어보시게 될 분들께도 도움이 될 것 같네요.

**Comment by eric2925** [comment]
아 감사합니다. 아래쪽에 쓰면 다시 안봐주실까봐 ㅎㅎ 알겠습니다^^

**Comment by RickyPark** [comment]
> 아 감사합니다. 아래쪽에 쓰면 다시 안봐주실까봐 ㅎㅎ 알겠습니다^^

이 질문글은 목적을 달성한 것으로 보이는데요, 이 경우에는 close해주셔도 좋을 것 같습니다. (한꺼번에 설명해드릴걸 그랬네요, 죄송합니다.)
