### ISSUE TITLE
머신러닝머신이 작동하지 않습니다

### ISSUE THREAD

**Issue by itsfrankocean** [codingeverybody/codingyahac#1056]
# 해결하고자 하는 문제
머신러닝머신을 크롬브라우저에서 작동시키려 하는데 파일 드래그 이후 카메라 사용을 허용을 했는데도 계속 허용하라는 화면이 뜨고 클릭 여러번 했더니 넘어가지긴 하는데 모든 수치가 0퍼센트로 되어있는걸 보니 작동하지 않는것 같습니다 브라우저 문제인가요 파일 문제인가요? 드래그한 파일은 teachable machines 사이트에서 tensorflow.js 로 다운로드 했습니다 teachable machines 사이트에선 정상적으로 작동 했습니다

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by egoing** [comment]
<img width="1024" alt="스크린샷 2021-01-05 오후 5 44 03" src="https://user-images.githubusercontent.com/303822/103625017-b4eefe80-4f7d-11eb-920b-52d879ba36a9.png">

샘플모델을 이용했을 때도 동작하지 않나요?

그리고 'tensorflow.js로 다운로드' 했다는 말의 의미가 이해가 되지 않습니다.
