### ISSUE TITLE
오렌지 3.  4편 기본사용법에서

### ISSUE THREAD

**Issue by lucy2020-tech** [codingeverybody/codingyahac#1059]
-->
오렌지 3 야햑중인데요. 4편 보면서 샘플을 이용해서 실습중이에요. 파일을 받아 apply까지 완료했는데 
data tabble에서 no data라고 확인되네요;;
스크린 샷 올려 보아요. 좀 다른 점이 있는데 file과 data table 라인 끝에 빨간점이 있네요.

> 
<img width="1440" alt="스크린샷 2021-01-05 오전 11 15 53" src="https://user-images.githubusercontent.com/75058620/103600198-37f66180-4f4a-11eb-8b40-abbeceacbcbf.png">

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by egoing** [comment]
File,  data, DataTable를 더블 클릭하셔서 나타나는 화면을 공유해주시면 원인을 파악하는데 도움이 될 것 같습니다.
