### ISSUE TITLE
오랜지3 기본 사용법 질문(select rows)

### ISSUE THREAD

**Issue by thdcnd1210** [codingeverybody/codingyahac#1063]
![image](https://user-images.githubusercontent.com/77034107/103720148-0941bf00-500e-11eb-9de6-26d2b8b3d3f8.png)
이미지에서 빨간색으로 표시한 조건만 지울 수 있는 방법은 없을까요?
remove all을 선택하니 전체가 지워지네요.

윈도우10 64bit

**Comment by jeuxdeau** [comment]
![image](https://user-images.githubusercontent.com/22112344/103750188-c30a5100-5049-11eb-8bb6-279ed3396137.png)
ㅋㅋ 오른쪽에 X 버튼이 숨겨져 있어요

**Comment by thdcnd1210** [comment]
이럴수가........................감사합니다
