### ISSUE TITLE
진로관련 고민

### ISSUE THREAD

**Issue by cksrb1616** [codingeverybody/codingyahac#1067]
외국에서 대학을 얼마 전에 끝낸 경제학과 학생입니다.
길게는 솔루션 아키텍쳐를 생각하고 있지만, 할 수 있는 파이썬 부터 시작하여 차근차근 밟아 올라갈 생각입니다.

운 좋게도 첫 인 턴을 보안업체의 데이터 관련 직책으로 수행할 수 있었고 개인적으로 계속 파이썬 위주의 알고리즘, 머신러닝을 공부하고 있는데요.
이번에 인턴을 했던 곳에서 머신러닝 인턴을 구하기에, github에 있는 프로젝트를 늘려간다면 타 학과 출신임을 커버하기에 좋을 것 같아 여러가지를 올려보고 있습니다. 하지만 여전히 제 github이 부실해 보이기는 하네요. 이에 방비 자료로 더 많이 경험하고 업로드 해보고자 하는데,

" **단순한 선형회귀 이외의 머신러닝 또한 경험해보고 싶은데 좋은 참고자료가 있을까요?** "

또한, **수료증을 영문으로 받을 수 있는지 궁금합니다.** 아무래도 외국에 있다보니 이를 링크드인에도 기재하고 싶어 가능하다면 정말 감사할 것 같습니다.

좋은 강의들과 빠르고 이해쉬운 답변들 감사합니다. 
다른 분들이 올리신 질문들 참고하는 것도 꽤나 공부가 되서 굉장히 좋은 것 같습니다.

**Comment by dayeongl** [comment]
안녕하세요.

" 단순한 선형회귀 이외의 머신러닝 또한 경험해보고 싶은데 좋은 참고자료가 있을까요? "와 관련해서, 개인적으로 더 심화된 2가지의 course를 추천드리고 싶습니다.

1. CS229 - Machine Learning - Stanford Engineering Everywhere(https://see.stanford.edu/Course/CS229)
기본적인 ML과 관련된 기초 배경지식과 다양한 방법론에 대해 잘 설명해주십니다.

2. 모두를 위한 머신러닝/딥러닝 강의(https://hunkim.github.io/ml/)
1번과는 다르게 한국어로 진행되고, 역시 좋은 강의라고 생각합니다.

개인적으로 추천드리는 참고자료이며, 머신러닝야학보다는 보다 심화된 강의여서 처음에 쉽게 따라가지 못하더라도 꾸준히 보시는것을 추천드립니다:)

**Comment by RayleighKim** [comment]
바로 딥러닝으로 가지 않고(장단점이 있습니다.)

공짜로, 선형회귀에 이어서 공부하기 좋은 책이 있다면 저는 항상 아래 두 책을 강력 추천합니다.
R이 붙어있지만, 이미 인터넷의 능력자들이 github에 python으로 전부 포팅해서 올려두었습니다.

1. 수식이 나름 편하다. :  ESL(https://web.stanford.edu/~hastie/ElemStatLearn/)
2. 조금 기초 책 : ISLR(https://statlearning.com/)
