### ISSUE TITLE
<meta charset="utf-8">반드시 써야하나요?

### ISSUE THREAD

**Issue by jjolbo** [codingeverybody/codingyahac#107]
제가 meta태그를 쓰지 않고 html파일을 만들고 크롬을 통해 화면을 보았을때는 
한글이 깨지지 않았습니다. 그런데 웹서버(127.0.0.1)(?)로 확인했을때는 한글이 깨져서
meta태그를 사용했더니 정상작동하였습니다. 왜 그런가요? :)

**Comment by dongheegy** [comment]
`<meta charset="utf-8">` 태그는 html 파일의 인코딩을 알려주는 태그입니다. 인코딩을 명확하게 알려주지 않으면 웹브라우저 설정 상황에 따라 자동으로 인코딩을 추정해서 처리해주는데, 처리가 정확할 경우도 있지만, 그렇지 못하는 경우도 많습니다. 다양한 경우에 한글이 깨지지 않고 잘 보이기를 기대한다면 위 태그는 꼭 적어주는 것이 좋습니다.

**Comment by davidkwak** [comment]
참고로 해당 html 파일이 utf-8이 아닌 다른 인코딩 (euc-kr 등)으로 작성되어 있는 경우 해당 인코딩으로 명시를 해줘야 합니다. 게다가, mysql 같은 DB와 연동해서 결과를 출력할 때에는 해당 DB 인코딩도 맞춰주지 않으면 DB 출력결과는 깨지는 등의 문제가 생길 수 있습니다.

요즘은 UTF-8로 대동단결되는 분위기지만 예전 레거시코드를 다룰 일이있다거나 할때는 euc-kr도 흔히 나오는 인코딩이니 주의를 하셔야 합니다.

**Comment by jjolbo** [comment]
감사합니다! 아직 인코딩에 대해 잘 몰라서 많이 혼란스러웠는데 잘 배우고 가요!
