### ISSUE TITLE
[ Orange3 ] 오렌지3 기본사용법 file URL 질문입니다

### ISSUE THREAD

**Issue by tlfzgjadyd** [codingeverybody/codingyahac#1076]
안녕하세요, 오렌지3 기본사용법 강의에서 질문을 드립니다<br/>

## 해결하고자 하는 문제 <br/>
file위젯에서 URL을 입력하고 apply까지 완료하면 그때에는 데이터가 정상적으로 뜹니다<br/>
하지만 ows파일 저장 후 오렌지를 껐다가 다시 그 파일을 열 경우 입력했던 URL은 빈칸이 되어있고<br/>
data table에도 아무런 데이터도 출력되지 않습니다 <br/>
다시 열었을 때에도 데이터가 그대로 뜨게 하려면 어떻게 해야하나요? <br/><br/><br/>

## 오류화면 <br/>

<div>

+ #### apply로 URL 반영시 정상 작동
<img src="https://user-images.githubusercontent.com/47634717/103968536-61f88f80-51a7-11eb-81b4-e43a5d273410.png"/> <br/>
<img src="https://user-images.githubusercontent.com/47634717/103968678-9cfac300-51a7-11eb-9f25-f00ed90a9dd2.png"/><br/><br/>

+ #### 저장후 다시 켜기
<img src="https://user-images.githubusercontent.com/47634717/103968819-eea34d80-51a7-11eb-83d3-89886105f9cd.png"/> <br/>
<img src="https://user-images.githubusercontent.com/47634717/103968844-fb27a600-51a7-11eb-8e1a-fb5734cdcaae.png" /><br/><br/>

+ #### URL이 사라진 상태
<img src="https://user-images.githubusercontent.com/47634717/103968891-12ff2a00-51a8-11eb-9191-33a30fd4ce57.png" /> <br/>
<img src="https://user-images.githubusercontent.com/47634717/103968906-1beffb80-51a8-11eb-91c8-1607a7b6fe58.png"/><br/><br/>

</div>

## 환경 <br/>
운영체제 : Windows10 버전20H2 <br/>
오렌지 : Orange3-3.27.1-Miniconda-x86_64.exe <br/><br/><br/>

## 시도해본 방법 <br/> 
URL방식 말고 컴퓨터에 있는 파일을 이용했을 경우 다시 키더라도 데이터가 정상적으로 남아있었습니다 <br/>

**Comment by xenosoz** [comment]
혹시 몰라 오렌지 다른 버전에서도 시험해봤는데 같은 문제가 있네요. 실습하실 때는 구글 스프레드시트의 File - Download - Tab-separated values를 이용해서 tsv 파일을 다운로드 하시는 방법도 고려해보셔요.

<img width="628" alt="Screen Shot 2021-01-08 at 7 46 52 PM" src="https://user-images.githubusercontent.com/255453/104007262-06e88c00-51eb-11eb-935b-62ba874c9266.png">

운영체제: MacOS Mojave 10.14.6 (18G5033)
오렌지:
Orange3-3.25.0-Python36.dmg
Orange3-3.27.1-Python3.7.6.dmg

**Comment by tlfzgjadyd** [comment]
네 감사합니다!!
