### ISSUE TITLE
Deploy 관련

### ISSUE THREAD

**Issue by cksrb1616** [codingeverybody/codingyahac#1083]
# 해결하고자 하는 문제
flask 와 파이썬 tensorflow를 통해 만들어낸 app의 배포를 시도해보고 싶습니다.
Heroku 를 통해 배포하려 하기에 마지막에 git push heroku master 를 입력할 시
마지막 즈음에 requirements.txt에는 포함 되어있지도 않은 pyobjc-framework-CoreAudio==7.1 때문에 오류가 납니다.
macOS에만 있다는 것과 다양한 시도들을 구글링을 통해 시도해 봤는데 피할 수 가 없더라고요.
이 항목을 다운 받지 않는 방법이 있을까요.
전체 파일을 별도로 주소를 첨부해 두겠습니다.
https://github.com/cksrb1616/Price_Prediction_Cabbage_for_Kimchi/blob/main/Heroku.zip
다른 방법도 좋으니 flask와 tensorflow 저장된 모델을 활용한 파일의 배포를 해보고 싶습니다.
다른 유튜브 들도 많이 봤지만 영 뚜렷한 답을 주지 못하네요

# 코드 혹은 오류
```
 Collecting pyobjc-framework-CoreAudio==7.1
remote:          Downloading pyobjc-framework-CoreAudio-7.1.tar.gz (83 kB)
remote:            ERROR: Command errored out with exit status 1:
remote:             command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uv18k749
remote:                 cwd: /tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/
remote:            Complete output (9 lines):
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/setup.py", line 32, in <module>
remote:                py_limited_api=True,
remote:              File "/tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/pyobjc_setup.py", line 414, in Extension
remote:                os_level = get_os_level()
remote:              File "/tmp/pip-install-7e6mpzd3/pyobjc-framework-CoreAudio/pyobjc_setup.py", line 200, in get_os_level
remote:                with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
remote:            FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
remote:            ----------------------------------------
remote:        ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to allforkimchi.
remote: 
To https://git.heroku.com/allforkimchi.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/allforkimchi.git'
```

# 환경
macOS big sur 11.1 , python3, 

# 시도해본 방법
requirements.txt를 수정.
virtual machine 에서 구동.
aws 활용
goorm ide 활용 - > gnu가 없어서 웹페이지가 표시가 되지 않는 것 같았습니다.

**Comment by progh2** [comment]
일단.. virtualenv는 사용하신거겠죠? ^^;

pyobjc-framework-CoreAudio 에 대해서 찾아보니 맥만을 위한 패키지로 되어있네요.

> Wrappers for the “CoreAudioKit” framework on macOS.

https://pypi.org/project/pyobjc-framework-CoreAudioKit/

위 내용을 보니 playsound 모듈이 맥에 의존성을 가지기 때문에 리눅스(헤로쿠 동작 환경)에서는 사용할 수 없다고 하네요.
즉 현재 있는 패키지들 중에서 맥에서만 의존성을 가지는 패키지가 있다는건데.. 
너무 많은 패키지가 연관되어있어 파악이 쉽지 않네요. ^^;;

요인이 플라스크에 있는지, 텐서플로우 모델에 있는지 파악해서 진행해야 할 것인데
소스코드를 단계적으로 새로 만들어서 붙여가며 업로드해서 언제 에러가 발생하는지 찾아보는 방법이 하나 있을 것 같고

아니면 가상머신에서 리눅스를 설치한후 그 환경에서 한번 플라스크와 텐서플로우 모델을 빌드해서
넣어서 배포해보면 어떨까 합니다. (소스를 그대로 옮기는게 아니라 리눅스 환경에서 플래스크 프로젝트를 생성,
개발해온 단계를 밟아서 가는 것이죠.)

이러면 맥 전용 라이브러리를 사용하는 문제를 피할 수 있지 않을까 합니다.

**Comment by cksrb1616** [comment]
> 일단.. virtualenv는 사용하신거겠죠? ^^;
> 
> pyobjc-framework-CoreAudio 에 대해서 찾아보니 맥만을 위한 패키지로 되어있네요.
> 
> > Wrappers for the “CoreAudioKit” framework on macOS.
> 
> https://pypi.org/project/pyobjc-framework-CoreAudioKit/
> 
> 위 내용을 보니 playsound 모듈이 맥에 의존성을 가지기 때문에 리눅스(헤로쿠 동작 환경)에서는 사용할 수 없다고 하네요.
> 즉 현재 있는 패키지들 중에서 맥에서만 의존성을 가지는 패키지가 있다는건데..
> 너무 많은 패키지가 연관되어있어 파악이 쉽지 않네요. ^^;;
> 
> 요인이 플라스크에 있는지, 텐서플로우 모델에 있는지 파악해서 진행해야 할 것인데
> 소스코드를 단계적으로 새로 만들어서 붙여가며 업로드해서 언제 에러가 발생하는지 찾아보는 방법이 하나 있을 것 같고
> 
> 아니면 가상머신에서 리눅스를 설치한후 그 환경에서 한번 플라스크와 텐서플로우 모델을 빌드해서
> 넣어서 배포해보면 어떨까 합니다. (소스를 그대로 옮기는게 아니라 리눅스 환경에서 플래스크 프로젝트를 생성,
> 개발해온 단계를 밟아서 가는 것이죠.)
> 
> 이러면 맥 전용 라이브러리를 사용하는 문제를 피할 수 있지 않을까 합니다.

Docker를 이용해서 피해보려하니 해당 문제는 피해지는데, 서버가 가동했다는 문구까지 나오는데 접속하려 하니 접속은 또 되지 않네요. CORS 문제인가 싶은데 좀 더 알아봐야 될 것 같습니다. 감사합니다!!!
