### ISSUE TITLE
제 80번 질문만 답변이 안달립니다ㅜㅜ

### ISSUE THREAD

**Issue by kwonminki** [codingeverybody/codingyahac#109]

**Comment by blackdew** [comment]
안녕하세요 :) 

mapper 이라는 도구를 처음 보내요. 아무래도 이와 관련된 지식을 가지신 분이 조력자중에 현재는 없는 것 같아요. 
해당 도구에 대한 document와 샘플 예제를 참조할 수 있게 링크를 함께 주시면 문제를 파악하는 데에 도움이 될 것 같아요. :)
