### ISSUE TITLE
코딩야학 웹호스팅에 대해 질문 드려요!

### ISSUE THREAD

**Issue by yoonsoo2002** [codingeverybody/codingyahac#1091]
이번에 갓 코딩을 시작한 초보입니다! 강의를 들으며 진도를 따라오던 중 github pages에서의 설정이 영상 속에서는 master branch라고 하여 그것을 클릭하면 웹사이트가 만들어지는 반면에 지금은 main 과 none 으로 구별되며 옆에 파일이라고 떠 root인가 docs인가를 고르는 ui로 변경되어 어떻게 사용하는지 모르고 있습니다. ㅠㅠ 이에 대해 알 수 있을까요?
![캡처SCD](https://user-images.githubusercontent.com/41609768/104336176-7b972f80-5537-11eb-81b7-777c290ee672.PNG)

**Comment by progh2** [comment]
#1092 와 같아서 닫겠습니다. :)
