### ISSUE TITLE
디자이너가 사용하기 좋은 라이브러리 Bootstrap vs Semantic ui

### ISSUE THREAD

**Issue by Choijinsol** [codingeverybody/codingyahac#110]
안녕하세요 존경하는 조력자님, 웹디자이너로 재직 중인 디자이너입니다. 이고잉님의 Semantic ui 강좌를 보고 배우고싶어서 알아봤더니 Bootstrap보다 제공하는 테마나 ui가 훨씬 많은 장점이 있는데 JavaScript를 수준급으로 이해할 수 있어야 한다고해서 Bootstrap이랑 Semantic ui중에 어떤걸 배워야할지 고민입니다. 저는 JS는 잘 다루지 못하거든요. JS를 잘 모르는 디자이너도 Semantic ui를 잘 활용 할 수 있을까요?

**Comment by egoing** [comment]
예 가능합니다. 거기서 제시하는 js를 js라고 생각하지 마시고, 그냥 마법의 주문이라고 생각하시고 copy & paste 하시면 됩니다. 원래 그렇게 경험적으로 사용자가 되었다가, 나중에 이론적으로 공부를 통해서 경험적으로 알게 된 것을 컴팩트하게 압축해나가는 것이 저는 더 좋은 공부 방향이라고 생각하거든요. 물론 시행착오를 줄이고 싶다면 너무 두려워하지 마시고 자바스크립트를 공부해보세요. @Choijinsol 님을 위해서 만든 수업을 소개해봅니다. https://opentutorials.org/course/3085

화이팅입니다 :)
