### ISSUE TITLE
파이썬 공부법 질문 있습니다 !

### ISSUE THREAD

**Issue by gmuffiness** [codingeverybody/codingyahac#111]
이고잉님 덕분에 생활코딩으로 웹 애플리케이션과 파이썬루비 수업 다 들었네요..!!
한 2주?? 조금 안 걸린것 같아요.

 파이썬 더 공부하고 싶은데 책 찾아보니 '점프 투 파이썬' 좋다고 그래서 그냥 그 책 완파하면 될까요???

아니면 파이썬에 관한 다른 더 좋은 강의나 책들 같은 수단이 있는지 궁금합니다!

**Comment by ghdalsrldi** [comment]
수업을 다 들으셨다면 무엇이든 직접 만들어 보시는 것을 추천합니다.

만들면서 부족한 부분을 인터넷이라 교재로 채워간다면 흥미를 잃지 않고 공부할 수 있을 것 같아요!

화이팅!

**Comment by progh2** [comment]
안녕하세요~ 
관련 커뮤니티 스터디에 참가 또는 만들어서 같이 공부하고 프로젝트 만들어보며 경험을 공유해보는 것도 추천드려요.

**Comment by gmuffiness** [comment]
개발 분야는 커뮤니티 쪽이 활성화 되어 있어서 네 좋다고 들은 적은 있긴 한데..
막상 어디가 저에게 괜찮은 스터디일지 결정을 못하겠네요 하하...
