### ISSUE TITLE
IT 관련 사업을 하고 싶습니다. 어디서부터 배워야 할까요?

### ISSUE THREAD

**Issue by Park-eungje** [codingeverybody/codingyahac#112]
안녕하세요, 생활코딩님.

 

평소 유튜브를 통해 JAVA를 애청하는 학습자 입니다.

 

저는 System을 통한 사업을 하고 싶기에 이렇게 메일을 보냅니다.

 

대학에서 산업공학을 전공하며, java와 c언어를 공부했지만

 

심도있는 학습은 아니었습니다. 따로, JAVA의 정석을 구매해

 

개인적으로 공부하지만 지루하고 고루한 과정들로 인해  

 

진도가 더딥니다.

 

웹 사이트와 어플, 이 두 방향에서 Platform을 개발하고 싶은데

 

어디서부터 공부해야할지 감이 안 잡히기에 문의 드립니다.

 

다소 막연한 질문이라는 점 양해바라며,

 

답변 부탁드리겠습니다. 감사합니다.

**Comment by egoing** [comment]
둘 다 동시에 하기는 어렵습니다. 우선 웹과 앱 중에 하나를 선택하시면 좋겠습니다. 소프트웨어를 판매하기에는 앱이 좋고, 서비스를 제공하기에는 접근성이 높은 웹이 더 좋을 것 같습니다. 


저는 웹개발자이기 때문에 웹 중심으로 말씀 드리면 우선 지금 진행중인 코딩야학에 http://code-night.ga/ 참여하셔서   html&internet 과정으로 시작을 해보시면 어떨까 싶습니다. 

앱을 만들고 싶으시다면 우선 자바를 '적당히' 공부하시고, 안드로이드 플랫폼에 대한 공부를 하면서 공부하면서 부족한 java에 대한 지식을 검색이나 질문을 통해서 보충하면서 나아간다 면 덜 힘들게 공부하실 수 있지 않을가 싶습니다.
