### ISSUE TITLE
웹 기반 이미지 ai를 만들어보려고 합니다!

### ISSUE THREAD

**Issue by donhaklee** [codingeverybody/codingyahac#1123]
안녕하세요! 이번 머신러닝 강좌를 수강한 대학생입니다.
텐서플로우까지 수강하면서 
그림을 사진으로 사진을 그림으로 바꿔주는
이미지 ai 프로그램을 정말 꼭 만들고 싶더군요..ㅠ

웹형태로 만들거라 자바스크립트를 이용할 예정인데
혹시 해당 프로그램을 만들기 위해서 어떤 알고리즘과 어떤 라이브러리
혹은 어떤 오픈소스를 참고하는게 좋을까요?

인공지능 공부가 정말 막막했었는데 도움 많이 되었습니다!

**Comment by visiodeibc** [comment]
안녕하세요!
아주 멋있는 목표를 가지고 계시는군요~!
해당 질문은 정확히 어떤 사진을 그림으로 혹은 그림을 사진으로 바꾸고 싶으냐에 따라 다양한 접근 방법이 있을거 같은데요.

우선 사진과 그림에 스타일을 합쳐서 결과물을 내는 [style transfer](https://www.tensorflow.org/tutorials/generative/style_transfer)라는 예시를 참고 해시는것도 좋을거 같구요.
style transfer를 간단하게 해주는 [사이트](https://deepart.io/)도 있으니 참고 해보세요!

또한 찾아보니 간단한 스케치를 사진으로 변경해주는 [논문](https://openaccess.thecvf.com/content_cvpr_2018/papers/Chen_SketchyGAN_Towards_Diverse_CVPR_2018_paper.pdf)이 있네요. 하지만 영어 원문이라 난이도가 좀 있을 것으로 예상 됩니다.
위 논문의 코드가 있어서 같이 첨부드릴게요! [여기](https://git.droidware.info/wchen342/SketchyGAN)

아 마지막으로 저도 인상깊게 보았던 예시인데 그림 ->사진으로 만들어주는 프로그램중에 NVIDIA에서 한게 있더라구요. gauGAN모델이라는 친구인데 현재는 베타중이고, 후에 api가 나오면 사용해도 좋지 않을까하는 의견입니다! [여기](http://nvidia-research-mingyuliu.com/gaugan)

그 멋진 마음 잘 가듬어서 꼭 원하는 사이트를 만드시길 바라요! 무엇보다도 그 과정을 즐기세요~!
Happy Coding! :D

**Comment by donhaklee** [comment]
답변해주셔서 감사합니다!
그림과 사진은 인물과 배경 혹은 스케치나 수채화 상관없이 누가봐도 그림, 누가봐도 사진인 느낌을 주기만 하려해서 정하진 않았습니다! 그래서 덕뿐에 걸어주신 링크와 논문을 통해 어느정도 갈피를 잡게 되었습니다.

그런데 혹시 걸어주신 링크들이 다 파이썬으로 제작해야하는 내용들이던데 자바스크립트로 하거나 해당 내용을 자바스크립트와 연동하는 방법이 있을까요?
웹사이트의 틀까지 만들긴했지만 혹시나 방법이 없다면 장고를 새롭게 배워서 시도해보도록하겠습니다!

친절한 답변 정말 감사드려요!

**Comment by visiodeibc** [comment]
자바 스크립트로 프론트를 구성한다고 해도 
트레이닝 자체는 파이썬을 사용해서 서버단에서 트레이닝을 하시고 결과 모델을 js호환 가능하게 export하여 사용하실 수 있을거 같습니다~
아래 링크를 참고해보시면 좋을거 같아요!
[링크](https://www.tensorflow.org/js/tutorials/conversion/import_keras)
[링크](https://www.tensorflow.org/js)

**Comment by donhaklee** [comment]
답변 감사합니다! 덕분에 머신러닝 프로젝트 입문에 정말 도움 됐습니다 ㅠㅠ

한번 남은 기간동안 말씀해주신 링크 하나하나 쭉 공부해보도록 할게요!

**Comment by visiodeibc** [comment]
응원합니다~~ 그럼 이 이슈는 클로즈 할게요~~
