### ISSUE TITLE
진로 고민. 어디서부터 어떻게 해야될지 모르겠습니다.

### ISSUE THREAD

**Issue by zmdals** [codingeverybody/codingyahac#1124]
미국에서 대학을 다니다 군복무를 하기위해 3학기를 남겨놓고 왔습니다. (현재 군복무 7개월정도 남았고 내년9월 복학예정입니다.)

당장 내년에 다시 돌아가야하는데 어디서부터 뭘 어떻게 해야할지 너무 막막합니다. 

사실 저는 확고한 꿈이없는채로 수능을보고 대학에 진학했는데 컴퓨터공학과를 선택한 이유도 단지 취업이 잘된다는 소리를 들어서 였습니다.

코딩에 ㅋ도 모른채로 진학하여 아무생각없이 어플리케이션 개발학과를 선택해서 2년반동안 자바를 배웠는데, 머릿속에 남은게 별로없습니다.

대학교에 있을 당시에는 정말 뭐가 뭔지 하나도 모르겠고 그냥 과제내주면 겨우겨우 의무적으로 해가는 생활을 2년반동안 하고 한국에 왔습니다.

한국에 와서 남는시간에 우연히 유튜브를 보다가 생활코딩이란것을 알게되고 html,css 같이 눈에보이는것들을 따라해보고 흥미를 많이 느꼈습니다.

특히 직접 파이썬으로 웹으로 파일을 만들고 삭제하고 그런 과정이 너무 신기하고 재미있었습니다.

그런데 딱 거기까지는 너무 재밌게하는데 그 이후에 뭘 더해야하고 어떤것을 해야 할 지 갈피를 못잡겠습니다. 

예를들어 장고, 스프링 이런것들을 더 해보고 싶은데 뭘 어떻게 해야할지 감이 오지않습니다.

대학에서도 그렇고 생활코딩을 보면서도 그렇고 따라하기만 했던 제가, 그 이후엔 누군가 뭘 이렇게 해라 딱 정해주지않으니 당장 뭘해야 내 실력이 늘고 더 성장 할 수 있는지 잘 모르겠습니다.

'내가 지금까지 해왔던것들이 정말 쓸모가 있을까?', '너무 잘못된 길로 가고있는거아닌가?' 라는 생각들이 지배적입니다.

또한, 저는 파이썬이 자바보다 더 쉽고 재미있고 이번 머신러닝 강의를 듣고 파이썬이 더 끌리게 되었는데,

그동안에 들여온 시간이나 학비같은것 때문에 언어를 바꿔야할지 고민입니다.

마지막으로 직접 멘토분들을이나 관련 종사자분들을 만나 이런 상담을 할 수 있는곳이 있을까요?

긴 글 읽어주셔서 감사합니다 :)
---------------------------------------------------------------------------------
주 질문
1. 생활코딩을 다 보고 자기개발을 위해 무엇을 어떻게 더 해야할까요?
2. 주 언어를 바꿔 처음부터 다시 시작해야 할까요?
3. 멘토분을 구할수있는곳이 있을까요?

**Comment by visiodeibc** [comment]
안녕하세요! 저도 개발자로 취직한지 얼마 안되어서 작성자 분이 나누어 주신 고민들이 정말 공감되는 거 같아요.
우선 답변하는 분마다 답변이 상이하겠지만 제 개인적인 생각을 나누어 보자고 하면

저는 프로그래밍이 어느 한 언어 혹은 프래임 워크에 종속되어 있다고 생각하지 않아요. 
프로그래밍은 단순히 '문제풀이'에 수단이고 프로그래머는 '문제를 푸는 사람' 이라고 생각합니다. 많은 소프트웨어는
재미, 업무, 효율 등을 위한 다양한 문제를 푸는 도구인 것이죠!

이 이야기를 하는 이유는 작성자님이 어떤 프래임워크 혹은 언어를 해야하는지 알고 싶기 이전에 어떤 문제에 흥미를 느끼는지, 어떤 과정이 즐거운지를 좀 더 고민해보는 것이 도움이 되지 않을까 해요. 풀고 싶은 문제 또는 흥미를 유발하는 문제를 찾았다면 그 문제를 해결하기위해 필요한 언어와 프래임워크를 찾는 것은 상대적으로 쉬운 일이 되지 않을까 합니다. 

예를 들어 데이터 관련된 일과 업무에 관심이 많다면 파이썬을 그 중에서도 웹 서비스에 관심이 있으면 django, flask, 머신러닝이라면 keras, pytorch, 분석이라면 pandas, matplotlib 등의 라이브러리를.
스케일 아웃하고 효율적인 서비스 백단을 고민하면 java spring을
인터렉티브한 프론트에 관심이 있으면 react혹은 vue js를
앱 개발에 관심이 있으면 ios,android 혹은 react native이나 flutter
등등 작성자님의 성향과 관심에 따라 언어와 프래임워크는 바람을 실천하는 '도구'일 뿐이랍니다.

개인적인 경험으로는 저는 다양한 hackthon 혹은 창업 경진 대회를 나가서, 배우는 기술과 세상과 사회에 필요한 '문제'에 연결고리를 좀 더 고민하게 되어 진로에 대한 갈피를 잡는데 도움이 많이 된거 같아요. 세상에 대해 더 알게 되고 내가 하는 프로그래밍이라는 도구로 그 세상에 있는 문제를 어떻게 풀 수 있을까?라는 고민을 하다보면 가야하는 방향이 나올 수 있지 않을까요? 뿐만 아니라 이런 대회를 통해 훌륭한 멘토 또 친구들도 만날 수도 있다고 생각해서 적극 추천 드립니다!

저도 비슷한 경험을 하며 취직 과정을 담은 글이 있는데 좀 도움이 될 수 있을까하여 링크 공유해요! [링크](https://medium.com/visiodeibc/%EC%8A%A4%ED%83%80%ED%8A%B8%EC%97%85-%EC%82%AC%ED%9A%8C%EC%A0%81-%EA%B0%80%EC%B9%98-%EA%B3%B5%EB%8F%8C%EC%9D%B4-%EC%A2%8C%EC%B6%A9%EC%9A%B0%EB%8F%8C-%EA%B0%9C%EB%B0%9C%EC%9E%90-%EC%B7%A8%EB%BD%80%EA%B8%B0-98879d45745b)
홧팅!

**Comment by zmdals** [comment]
답변 감사합니다!! 링크도 들어가서 빠져들듯이 읽었어요. 막연했던 저에게 많은 도움이 되었습니다. 정말감사합니다!

**Comment by visiodeibc** [comment]
ㅎㅎ 잘 읽어주셔서 감사합니다! 
어떤 길이 되었든 응원합니다! 아자아자!
