### ISSUE TITLE
텐서플로우에서 모델 구축 할 때 코드 별 차이가 궁금합니다!

### ISSUE THREAD

**Issue by Chromis07** [codingeverybody/codingyahac#1125]
# 해결하고자 하는 문제
이번 머신러닝 야학을 통해 tensorflow 101 수업을 잘 들었습니다!
그리고는 다른 텐서플로우 코드들을 구경하던 와중에 아주 작은(?) 차이들이 보여서 질문 드립니다.

제가 이해한 바로는
강사님은 layer들을 변수들에 담아 순서대로 쌓으신 걸로 보이고 (어떤 층을 받는지도 따로 정의도 해주고)
혹은 model을 Sequential()로 정의하고 add를 통해 쌓거나,
아예 모델을 정의하면서 한번에 쌓는 것도 보이거든요.

- 이 코드들 형태의 장단점이 있는 건지, 혹은 단순히 개인 취향에 따른 코드인지 궁금합니다!

그리고 어떤 코드들은 초반에 tensorflow 만 임포트하고 끝내는데
Sequential, Dense, Flatten 까지 디테일하게 임포트 하기도 하더라고요

- 가장 상위의 라이브러리(tensorflow)만 임포트하는 것이 아니라 세부적으로 임포트 하는 이유가 궁금합니다!

이렇게 두 가지 질문을 드립니다.
다른 분들의 질답들을 통해 많이 배워가고 있습니다. 항상 감사드립니다!

# 코드
**강사님의 모델 코드**
```
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
```
**다른 예시 1 (add)**
```
model = Sequential()
model.add(Dense(32, input_shape=(2,), activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer= SGD(), loss=mse, metrics=['acc'])
```
**다른 예시 2 (model 내에서 한번에 처리)**
```
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
```

**import 예시**
```
import tensorflow as tf # 이 친구가 다 가져와주는 것 아니었나?
from tensorflow.keras.models import Sequential # 왜 얘네들까지 불렀을까?
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse 
```

**Comment by blackdew** [comment]
텐서플로우는 Sequential 과 Functional 두가지 형태로 모델을 구성할 수 있습니다. 
코드를 처음 접하는 사람들에게는 Sequential 구조가 좀 더 편한 면이 있습니다 

좀 더 복잡한 형태로 구조를 만드는 것은 Functional에서만 가능하고, 
변수에 데이터를 저장하면서 진행하는 것이 프로그래밍 관점에 대해서도 경험을 할 수 있는 장점이 있다고 판단해서 
강의에서는 의도적으로 Functional 구조만을 사용했습니다. 

텐서플로우 내부적으로는 작성된 코드 모두가 동일한 구조라고 보시면 되겠습니다. 

import 와 관련해서는 같이 하는 팀원들이 어떤 방식을 선호하느냐에 따라 맞추면 됩니다. 
처음 학습하는 과정에서는 tensorflow library 내에서 module의 hierarchy를 이해하는 데에 
도움이 된다는 판단이 있어서 주욱 늘어놓는 방식을 사용했네요.

**Comment by Chromis07** [comment]
@blackdew 
아하!!
언젠가 Sequential 말고도 다른 형태가 있다고 얼핏 듣기만 했었는데
이번 강의 덕분에 Functional도 하나 챙겨가네요!
실제로도 변수에 담는 방식이 기존 프로그래밍 방식에 더 익숙하기도 했고요.

자세하고 친절한 답변 정말 감사드립니다!!
