### ISSUE TITLE
오렌지3에서 파일을 가져오는데 feature이라는 요상한 것들이 같이 있어요.

### ISSUE THREAD

**Issue by hanbokkorea** [codingeverybody/codingyahac#1127]
# 해결하고자 하는 문제
![1](https://user-images.githubusercontent.com/77918331/126481471-03dd1148-49a1-47b7-afbc-b2f00fdf0473.jpg)
[](url)
[Orange3 -sample example - data의 사본.xlsx](https://github.com/codingeverybody/codingyahac/files/6855229/Orange3.-sample.example.-.data.xlsx)

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법
우클릭해도 뜨는 것이 없어요.

**Comment by blackdew** [comment]
오랜지 3 수업에 있는 예제를 따라했는데 그렇게 된건가요? 
칼럼에 이상한 값이 들어있어서 칼럼으로 인지를 하게 된 것 같아요. 
불필요한 칼럼은 skip으로 설정하신 뒤에 수업을 이어서 들으시면 되겠습니다. :)
