### ISSUE TITLE
오렌지3--text 타입과 categorical의 차이, meta와 skip 뜻이 뭔가요??

### ISSUE THREAD

**Issue by hanbokkorea** [codingeverybody/codingyahac#1128]
# 해결하고자 하는 문제
text 타입과 categorical 의 차이가 뭔가요?? 카테고리컬은 범주형이라 알고 있는데 범주형도 텍스트니까 둘이 같은 거
아닌가요??? role에서 meta와 skip 은 뭘 뜻하나요?? 

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법
검색해봤는데 어려운 용어들이 잔뜩 나와서 모르겠어요..

**Comment by blackdew** [comment]
봄, 여름, 가을, 겨울 과 같이 범주를 나타내는 데이터가 categorical이고, 단순히 문자열을 적어둔 것은 text입니다. 
컴퓨터가 이 데이터를 범주로 인식해야 한다면 categorical로 지정해 주면 됩니다. 

meta와 skip 모두 데이터를 분석하는 데 있어서 사용하지 않을 것들을 의미하고요, 
다만 meta는 데이터로서의 가치는 없지만 사람이 데이터를 볼 때에 도움이 되는 것들 이라고 이해하시면 됩니다. 보충 설명이라고 보면 되요. 

예를 들어 음악 데이터를 생각해 보시면, 가수, 곡명, 앨범명 등 음악 자체는 아니지만 음악을 듣는데에 도움이 되는 부가적인 정보가 있어요. 이를 메타 데이터라고 합니다. 보충 설명이죠.
