### ISSUE TITLE
nodejs 서버운영

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#114]
nodejs로 서버를 생성하려면 서버를 생성하는 코드가있는 파일을 커맨드 라인에서실행 시켜야 하잖아요?
그 실행시킨 상태에서는 다른 작업을 못해서 ctrl+c로 작업을 중지한 다음 다른작업을 해야하던데 그럼 nodejs로 웹서버로 운영하려면 다른작업을 하고싶을 때 서버를 꺼가면서 운영을 해야하나요??

**Comment by ghdalsrldi** [comment]
여러가지 도구들이 존재합니다.
저는 pm2라는 도구를 사용하는데 nodejs의 process를 편리하게 관리할 수 있습니다

참고해 주세요! ^^
https://www.npmjs.com/package/pm2
