### ISSUE TITLE
자바스크립트 특정위치로 스크롤했을때 이벤트 작동하게 하는법

### ISSUE THREAD

**Issue by dondaoare** [codingeverybody/codingyahac#1148]
# 해결하고자 하는 문제
자바스크립트로 스크롤을 내리면 특정한 위치에 도달했을때 옆에 fixed로 달아놓은 버튼의 디자인이  바뀌는 코드를 짜고 싶은데요.
제가 짠 코드가 맞는 것같고 실제로 버튼 4 개중 첫번째(main)와 두 번째(traffic)까지는 잘 작동합니다. 그런데 3번째(safety) 4번째(travel) 부분으로 스크롤할 때는 버튼이 왜 작동을 안하는지 모르겠네요.

# 코드 혹은 오류
```
   $(document).ready(function(){
  $(window).scroll(function(){
    if ($(window).scrollTop() < 500) {
      $(".scmain").addClass("design_sc");
      $(".sctraffic").removeClass("design_sc");
    } else if (500 < $(window).scrollTop() < 1300){
      $(".sctraffic").addClass("design_sc");
      $(".scmain").removeClass("design_sc");
      $(".scsafety").removeClass("design_sc");
    } else if (1300 < $(window).scrollTop() < 2100) {
      $(".scsafety").addClass("design_sc");
      $(".sctraffic").removeClass("design_sc");
      $(".sctravel").removeClass("design_sc");
    } else if (2100 < $(window).scrollTop()) {
      $(".sctravel").addClass("design_sc");
      $(".scsafety").removeClass("design_sc");
    }
  });
});
```
스크롤을 아래로 내리며 버튼은 main - traffic - safety - travel 순으로 바뀌어야합니다. 위의 코드에 문제가 있을까요? 같은 방식으로 짠 코드인데 왜 2개는 되고 2개는 안될까요.

**Comment by Haytsir** [comment]
자바스크립트에서는 비교연산자의 연계를 지원하지 않습니다.
내부적으로 따로 계산하거든요.
```js
500 < $(window).scrollTop() < 1300
```
`500 < $(window).scrollTop()` 가 참이라면 이후
`true < 1300`, 거짓이라면 `false < 1300`을 비교합니다


파이선에서는 작성하신 코드처럼 사용하셔도 가능한데,
현재 대부분의 언어에서 지원하지 않는 문법입니다.

세 항을 한번에 비교하는 문법을 만들기 위해서는 파서를 더 복잡하게 만들어야하고, 자바스크립트같은 언어에서는 성능과도 연관이 있습니다.

조건문 안의 비교연산자를 나눠서 적용해보세요
[참조](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Operator_Precedence)
