### ISSUE TITLE
웹보안이 궁금합니다

### ISSUE THREAD

**Issue by kdw9805** [codingeverybody/codingyahac#115]
저는 정보보호학과에 재학중인 대학생입니다. 이제 대학생활의 1년이 지나간 상태네요.. 지난 1년동안 학교에서는 C와 JAVA만을 간단하게 배웠습니다. 그래서 저는 더 많은것을 배워보고싶다 생각해서 이번방학에 여러가지를 도전하려고합니다. 지난 2기때도 코딩야학을 했었지만 완주를 못하고 이번에는 HTML은 물론 CSS까지 완주하고 Java Script를 공부하고있습니다.  근데 제가 학과가 학과인지라 보안에 더 큰 관심이 있는데요. 웹보안을 어떻게 시작하고 접근해야하는지가 궁금합니다.

**Comment by babomose** [comment]
안녕하세요. 

웹을 이해하고 계신다면(간단한 웹사이트를 제작하신 경험이 있다면) 바로 웹 보안 공부를 하실 수 있습니다. 웹 보안의 역사는 꽤 길기 때문에 좋은 자료들이 많습니다. 

웹 취약점을 실습할 수 있는 가상의 사이트를 구축하고 실습하는 것을 추천드립니다.
bWAPP: http://www.mmebvba.com/sites/bwapp/download.htm
WebGoat: https://github.com/WebGoat/WebGoat


만약 실습하는 중에 막히는 부분이 있으실 경우에는 해당 취약점을 구글에 검색하시고 '동영상'을 클릭하시면 많은 정보를 얻으실 수 있습니다.
