### ISSUE TITLE
프로그래밍 관련 진로 질문드립니다

### ISSUE THREAD

**Issue by phillyham24** [codingeverybody/codingyahac#118]
안녕하세요. web1 수업을 마치며2까지 듣고 생각을 정리하던 중에 스스로 해결되지 않아 글을 올립니다.
질문이 2가지라 나눠서 드립니다.

1. 문제 상황부터 말씀드리면 왜 프로그래밍을 하는 지에 대한 스스로 답을 못내렸다는 것입니다.
현재 대학교 2학년까지 마친 상황이고 경영학에 복수전공으로 컴퓨터공학 수준까진 아니지만 프로그래밍 관련 수업을 듣는 과를 같이 진행할 예정입니다. 학교에서 파이선과 c를 배우면서 문제 해결 과정에서 논리를 짜고 코딩으로 실현화하는게 재미있었습니다. 그래서 개발자를 희망하며 어떤 서비스나 무언가를 만들고 싶다는 생각이 들었습니다.

문제는 알맹이라고 할 수 있는 '무언가' 혹은 '어떤 프로젝트의 주제'를 생각해보려고해도 떠오르지가 않는다는 것입니다. 사람들은 자신의 삶에서 불편함을 극복하거나 새로운 아이디어를 현실화하기위해 코딩을 배우고 관련된 사항에 바로 적용해보지만 저는 제가 하고 싶은 주제나 프로젝트가 없어서 지식이 늘고 새로운 툴을 배워도 '빈 깡통' 같은 느낌이 강하게 듭니다.

조력자분들 중에서 저와 같은 상황에 처해보신 분들이 계신가요? 있으시다면 어떤 방향으로 길을 나아가셨는지,  아니면 현업자로서 주실 수 있는 조언이라도 주신다면 감사하겠습니다.

2. web1을 끝내고 web2로 가면 css를 배우는데 디자인적 요소가 들어가는 걸로 알고있습니다. 당장은 아니더라도 UI나 UX와 관련된 디자인 이론을 따로 배워야 할 필요가 있나요? 관련된 글을 찾아보면 코딩과는 또 다른 분야라 어디서부터 무엇을 해야할 지 혼란스럽습니다.

**Comment by smartbos** [comment]
1번과 2번 질문이 어떤 면에서는 공통점이 있는 것 같습니다. 지극히 개인적인 의견입니다만, 무언가를 배울 때는 필요할 때 배우는게 가장 효과가 좋은 것 같습니다. 다른 말로 하면 필요할 때 까지 배움을 미루는 것이 좋다고 표현할 수 도 있습니다.

이런 관점에서 보면 1번은 두 가지 방안이 있을 수 있습니다. 1) 하고 싶은게 생길 때까지 배움을 미룬다. 2) 하고 싶은 것을 더 적극적으로 찾아본다. 2)번의 경우 직접 떠올리려고 해봤지만 마땅한게 안 떠오른다고 하셨으니 제안드리고 싶은 바는 2-1) 경험의 폭을 넓힌다. 일을 하거나 책을 읽다보면 해보고 싶은게 떠오를 가능성이 높습니다. 2-2) 내 아이디어가 아닌 다른 사람의 아이디어를 구현하는 것을 돕는다. 둘러보면 아이디어는 있는데 개발 능력이 없어서 아쉬워 하는 분들이 정말 많습니다. 스타트업위크엔드나 해커톤, 프라이머에서 진행하는 엔턴쉽 같은 것들에 참여해보세요. 재미있는 아이디어를 가진 사람을 발견할 가능성이 있습니다.

**Comment by phillyham** [comment]
자세한 답변 감사드립니다!
추가적으로 한가지만 더 질문드리면 제시하신 2-2 방안에서 해커톤이나 스타트업위켄드와 같은 행사에 참여하려면 어느 정도의 코딩 실력을 가져야 하는지 혹은 최소한 이정도는 스스로 할 줄 알아야 한다는 나름의 기준이 있나요?
