### ISSUE TITLE
퍼블리셔로 취업에 성공하였습니다. 그 이후에 어떻게 해야할지 모르겠습니다.

### ISSUE THREAD

**Issue by showme0077** [codingeverybody/codingyahac#120]
게임 프로그래밍을 전공했지만 취업이 되지 않아 다른 일을 잠시 하다가
지인 추천으로 생활코딩 사이트를 접하게 되었고 코딩에 대한 미련이 남아
하던일을 모두 내려놓고 약 6개월 간 공부한 끝에 작은 회사에 취업했습니다.
회사는 모두 개발자만 있는 데 저만 퍼블리셔로 입사를 하게 되었습니다.
사실 저는 개발자가 되고 싶었습니다. 다만, 모든걸 내려놓고 공부만 하자니 금전적 여유가 없어
기존에 알고 있는 지식과 공부를 통해 새롭게 배우게 된 것들로는 퍼블리셔밖에 안되더라고요.

유지보수 업체인데 개발자 밖에 없는 공간에서 제가 딱히 할 수 있는게 없더라고요...
jsp로 만들어진 홈페이지에서 개발자들이 마크업도 수정하시니... 저는 이미지 스케일링이나 이미지로 된 텍스트 수정뿐이라 개발도 퍼블리셔도 아닌 것 같아요

여기 있으면서 퍼블리셔로 경력을 쌓게 될텐데 개발자로 전향했을 때 이 경력을 쳐줄지 걱정이네요
나이도 30대를 바라보고 있어 어리다고 하면 어리지만 제 마음속에는 쫓기고 있는 기분이네요

자연스럽게 퍼블리셔에서 개발자로 전향하기 위해 제가 노력해야 할지 현업 분들의 도움이 필요합니다.
진로가 걱정이라 코딩관련 내용은 없어 죄송합니다

**Comment by egoing** [comment]
우선 긴 호흡으로 여유을 가지시면 좋겠습니다. 

그리고 퍼블리셔가 개발자가 아니라는 생각도 저는 동의하기 어렵습니다. 코드를 통해서 현실의 문제를 해결하고 있다는 그 사람은 다 개발자라고 생각합니다. 

아마도 개발자들이 마크업을 한다면, @showme0077 님께서는 css를 주로하고 계신 상황일 것 같습니다. css는 매우 중요한 웹의 태크닉입니다. 오히려 css에 전념해서 수련할 수 있는 좋은 기회라고 생각해보시면 어떨까요? css와 관련된 다양한 태크닉과 새로운 CSS 기법들을 꾸준히 수련하면서 우선은 CSS를 공고히 하는 것도 좋을 것입니다. 특히 CSS는 코드와 오랜시간을 보내야 잘할 수 있습니다. 쉽지 않은 영역임에 분명합니다. 

그리고 CSS가 좀 탄탄해지면 JavaScript나 JSP로 확장하면서 자신의 분야를 넓혀나가보셔요~ 주변에 도와줄 동료가 있다는 것도 정말 큰 힘이 될거에요.

퍼블리싱만큼은 확실히 하는 개발자는 좋은 경쟁력을 가질 수 있을거라 생각합니다.
