### ISSUE TITLE
3D디자인 파일을 공유하는 웹사이트를 만들고 싶은데 무엇을 공부해야 하나요?

### ISSUE THREAD

**Issue by yuseongpark95** [codingeverybody/codingyahac#121]
Webn 시리즈들을 공부하면서 꿈이 생겼습니다.
23살 난생처음으로 컴퓨터 공부를 해본 것이라
무엇을 공부해야 할 지 몰라서 많이 답답한 상황입니다.
그래서 도움을 얻을 수 있을까 이렇게 질문해봅니다!

3d프린터가 대중화 될 때를 생각해서 전세계 사람들이 3d디자인 파일들을 공유할 수 있는 웹사이트가 있다면 좋겠다고 생각했습니다. 그래서 3d디자인 파일들을 공유하는 웹사이트를 만드는 꿈이 생겼는데요, 무엇을 공부해야 할 지 모르겠습니다.

웹사이트를 만들기 위해서는 html, css, javascript가 필요하다라는 것을 이제 알았는데, 제가 원하는
웹사이트를 만들기 위해서는 무엇을 공부해야 할까요? 
3d 디자인 모델링 파일 같은 것들은 웹사이트에 사람들이 다운 받을 수 있게 업로드 할 수 있나요?
그러기 위해서는 CAD같은 소프트웨어를 자체개발 해야하나요? 

먼훗날 그러한 웹사이트를 만들고나면 스마트폰 앱으로도 만들어 3D프린터와 연동을 시켜 3D디자인 파일들을 스마트폰 안에서 손가락으로 3D프린터에 던지면 바로 프린팅하는 기술을 만들고 싶은데 그러기 위해선 무엇을 배워야하나요?

**Comment by smartbos** [comment]
우선은 제가 아는 범위 내에서 부분 적으로만 답변 드릴께요.

> 3d 디자인 모델링 파일 같은 것들은 웹사이트에 사람들이 다운 받을 수 있게 업로드 할 수 있나요?
> 그러기 위해서는 CAD같은 소프트웨어를 자체개발 해야하나요?
3D 디자인 모델링 파일 자체를 업로드하고 다운로드하는데는 별도의 프로그램이 필요하지 않습니다. 다른 형식(예를 들어 이미지 파일)의 파일을 업로드하고 다운로드 하는 것과 동일하게 처리할 수 있습니다.

단, 3D 모델링 파일을 웹상에서 렌더링해서 보여주려면 별도의 기술이 필요할 것 같네요.

**Comment by azaraks2** [comment]
어떤 걸 만들고 싶은 건지 항목 단위로 차근차근히 정리해보세요.
https://pinshape.com/ 같은 걸 만들고 싶으신 것 같긴 한데..

**Comment by ch-choi** [comment]
전문가는 아니지만 (디자이너로 불리는 일을 함) 웹 상에서 3D파일을 렌더링 툴 처럼 돌려보려면 WebGL이 필요한데 조금 구글링해보니 javascript api가 제공되네요.
그리고 html5에서 WebGL을 적용하는 방법은 html과 javascript 공부하시면서 구글링을 더 해보면 배울 수 있을것 같습니다.
그리고 참고할 3d 파일 공유 사이트 알려드립니다.
https://www.thingiverse.com/
https://3dwarehouse.sketchup.com
https://grabcad.com
사이트에서 소스코드를 전부 공개하지는 않겠지만 소스코드를 보면 어떤 api나 기술을 썼는지 알 수 있을 겁니다.
