### ISSUE TITLE
제가 생각한 어플리케이션을 구현할려면 어떤 것들을 공부해야 할까요? 

### ISSUE THREAD

**Issue by Hyogeun2** [codingeverybody/codingyahac#122]
프로그램 이름 : 내가 제일 잘 알아.

프로그램 구성
1. 자신에게 질문입력.
 2.데이터베이스에 질문에 대한 답변이 없다면 답변을 등록하는 창 호출.
3. 답변을 등록하면 나중에 같은 질문을 했을 때 저장했던 답변을 호출.
 주의사항 1.완전히 같지 않아도 입력했던 값이 적절하게 나와야 한다.
                2.나중에 생각이 바꼈을 경우를 대비하여 생각의 변화를 기록 할 수 있게 시간순으로 이전에 기록했던 답변을 저장한다. 이 기록을 보기 위해서는 우측 하단의 작은 버튼을 눌러 들어가도록 한다. 
                3. 너무 길게 쓸 경우 후에 가독성이 좋지 않아 문제가 생길 수 있으므로 사전에 글자수에 제한을 둔다.

프로그램 효과
 1.방향을 잃었을 때 과거에 내가 내 자신에게 한 질문과 그에대한 답변을 보며 잃어버렸던 자신을 찾을 수 있다.
 2. 질문과 답변을 통해 나의 내면에 더욱 깊게 접근 할 수 있다. 
 3.나의 생각의 변화를 알아 갈 수있다.

 질문을 등록해두고 나중에 비슷한 질문을 했을 때 이전에 했던 답변을 호출하는 어플리케이션입니다. 
어떤 언어들과 기술들을 공부해야 구현할 수 있을까요? 안드로이드 어플리케이션으로 만들고 싶습니다.

**Comment by ghdalsrldi** [comment]
질문에 답이 있는 것 같아요.

좀더 구체화 해서 말씀드리자면 
서버(API) , 클라이언트(안드로이드)의 기술이 필요할 것 같아요

서버 
1. 데이터베이스
> mysql, SQL Server, PostgreSQL, Oracle 등이 있구요 이와 같은 관계형 데이터베이스 중 한가지
2. 미들웨어(서버사이드)
> PHP, NodeJS(Javascript), Python, Java 등 서버에서 작동하는 프로그래밍 언어 중 1개
3. 기타
> RestFul API

이런 것 들이 있어요

클라이언트는 말씀하신대로 안드로이드에 대한 학습이 필요할 것 같아요

**Comment by haebin** [comment]
저는 Firebase 추천합니다.
컨셉트를 프로덕트화하는데 가장 빠르게 할 수 있습니다.
(후에 상용 서비스를 한다고 해도 나쁘지 않은 선택입니다.)
