### ISSUE TITLE
모의해킹분야(웹 or 시스템)로 취직하고 싶습니다. 조력자분들께 여쭤봅니다.

### ISSUE THREAD

**Issue by PassionOfStudy** [codingeverybody/codingyahac#126]
안녕하세요.  
나이 30에 첫 직장으로 OP업무를 하고 있는 열정 가득한 <strong>보안새내기</strong>입니다.
질문에 앞서서 현재의 저의 상황을 이야기해보려 합니다. 

-------------------------------------------------------------------------------------------------------------------
<p>
막연히 보안에 대한 관심만 가지다가 더 늦으면 안될 것 같아서  알아보다가 작년에 국비지원으로
정보교육학원의 정보보안엔지니어과정을 교육받았습니다.  비전공자임에도 불구하고 열심히 
교육받아서 이수는 했는데, 막상 취직을 하려고 보니, 제가 가고싶은 모의해킹 및 악성코드분석 분야는 
신입은 뽑지 않더군요... 신입을 뽑더라도 대부분 4년제 대학 학력(참고로 4학년 학사경고 누적으로 제적되었습니다. ㅠㅠ 공부의 뜻이 없었어요...)이 기본이고, 기본 영어와 자격증... 등등(개인적으로 진입 장벽
이 조금 높아보였습니다. 경력자 위주...) 나이도 있고, 쫓기고 지쳐 한계에 부딪히고, 결국 학원취업담당분께서 취업턱이 낮은 OP업무를 권유하셨고, 그래서 지금 OP업무 야간일을 하고있습니다.  
일을 하다보니 정말 배울 것이 하나 없고, 미래에 대한 전망이 없다고 느꼈습니다.(주변에 들어보니 
OP업무는 경력으로 인정해주지 않고, 길어야 1년 정도 일하고 이직해야 한다고 들었습니다.) 
하는 일이 없다보니 자연히 저만의 시간이 많았고(야간 15시간씩 일을 하는데 평균 12시간 이상의
개인시간이 있습니다.) 그래서 1년동안 준비해서 이직하자고 결심하게 되었습니다. 
</p>
-------------------------------------------------------------------------------------------------------------------

글을 쓰다보니 한 풀이가 된 것 같아 죄송합니다... ㅠ_ㅠ

<br><br>
그러면 질문 드리겠습니다.
=================================================================
<ul>
<li> <strong>이번 년도 하반기까지 준비해서 모의해킹(Web) 분야로 취직할 수 있을까요?</strong>
   <br>(현실 적인 조언 부탁드립니다! ) </li><br>

<li> <strong>모의해킹(Web) 분야로 진출하기 위해 필수적인 공부(기술)들에는 무엇이 있을까요?</strong>
   <br>(시간이 되신다면 모의해킹(System)분야도 알려주시면 감사하겠습니다.) </li><br>

<li> <strong>대부분의 기업에서 신입을 뽑지않고, 경력직을 선호하는데... 어떻게 경력을 쌓아야 할까요? ㅠ_ㅠ</strong>
</li>
</ul>
=================================================================
<p> 
<br>
지금가지 길고 서툰 저의 글을 읽어주셔서 감사합니다. <br>
바쁘신대도 불구하고 귀한 시간을 내서 지식을 공유하고 나누어주셔서 감사합니다.<br>
이런 좋은 기회를 주신 코딩야학3기의 이고잉님 및 조력자분들께 <br>
다시 한번 감사의 말을 전하고싶습니다! ^_^ <br>
늦었지만 새해 복 많이 받으시고, 무술년에 행복한 일만 가득하시길 기원합니다.<br>
</p>

**Comment by davidkwak** [comment]
안녕하세요. 여러모로 미래에 고민과 걱정이 많을 시기네요. 

4년제 학위라던지, 공인 영어 점수라던지 하는 부분들은 해당 업무 자체를 하는데 필요하다기 보다는 인사부서 쪽에서 기본적으로 요구하는 부분일 가능성이 높습니다.  이 부분은 정말 뛰어난 실력이 있다면 해당 포지션을 구인하는 부서에서 인사부서에 꼭 필요한 인재임을 어필해서 커버할 수 있겠습니다만 현재 글쓴분은 그 정도의 실력은 안되시는것 같으니 기본적으로 필요한  부분(학력, 외국어 등)을 최대한 채우시는게 좋을것 같습니다. 

다만, 스타트업, 벤쳐 규모의 회사는 갓 학원 졸업한 신입들을 뽑을 때도 있습니다. 이런 작은 회사에서 시작해서 관련 경력쌓으면서 좀 더 큰 회사로 이직하는  것도 괜찮을 것 같습니다. 

본격적으로 질문에 답변 드리자면 

1) 올 하반기에 취업 가능한가? 
질문자님 하기나름입니다. 냉정히 말해 저라면 안뽑을것 같긴합니다.  하지만, 저는 취업은 운칠기삼이라고 보기 때문에 ... 여기저기 포지션 날때마다 꾸준히 넣다보면 면접도 몇번 보게되고 그러다가 한 군데 될 수도 있습니다. (좀 무책임한 소리 같지만 현재로서는 그게 제일 현실적인것 같네요)

2)모의해킹 분야에 취업하기 위한 기술은?
 모의해킹(PT)은 사실 TO가 많은 분야는 아닙니다. SK인포섹이나 A3 같은 어느정도 규모 있는 회사가 아니면 20인 이하 소규모 업체에서 인력장사 같은 분위기로 진행되거나 앞서 말씀드린 업체에서 경력쌓은 분들이 나와서 프리랜서로 활동하면서 프로젝트 단위로 들어가는 경우가 많습니다. 모의 해킹이라는 분야도 저렇게 좁은데 web 분야라고 분리하는 의미가 없고, 모든 분야를 다 해야 합니다.  

웹 쪽으로 공부해야하는 기술을 꼽자면 OWASP Top10 리스트에 나오는 공격기법 명으로 검색해서 관련 문서들을 두루두루 보셔야 합니다.  특히 가장 많이 발생하는 취약점인 XSS, SQL injection 같은 것들은 더 유심히 보셔야 합니다. 그리고, 취업을 목적으로 하시는거라면 각종 툴 사용법들도 알아두시는게 좋습니다.  이건 kali linux라고 검색하셔서 참고자료를 찾아보세요 

시스템 쪽은 해킹과 직접적인 관련은 없지만 간단한 쉘스크립트나, 파이선 스크립트 정도는 짜서 쓸 수 있는 능력이 있으셔야하고, 각종 디버깅 기법, 후킹 기법 들도 아시면 좋겠습니다. 시간과 노력이 많이 필요한 분야니만큼 조바심 갖지말고 천천히 진행하세요 

3) 경력직만 선호하는데.. 경력이 없는 사람은 어떻게 경력을 쌓냐?
질문하신 내용중 가장 핵심적이고 중요한 부분입니다.   모의해킹 같은 인력장사 분야는 투입되는 인력의 경력에 따라 금액이 달라지기 때문에 높은 경력의 사람을 선호하는 경향이 있습니다.  꼭 인력장사를 하기 위해서가 아니더라도 뽑아서 바로 써먹을 수 있는 사람을 원하는건 인지상정이지요.  없는 경력을 만들 순 없으니 ... "내가 바로 뽑아서 써먹을만한 사람이다" 라는걸 어필하셔야 할 겁니다. 

자신의 실력을 증명 할 수 있는 다양한 외부활동 (블로그에 각종 취약점 분석 리포트를 써본다거나)을 성실히 하시고, 그냥 등록하면 누구나 갈 수 있는 학원 코스외에 좀 깊이 있는 교육 커리큘럼(BOB 등?)을 수료하거나, 정보보안기사와 같은 자격증을 취득하는 것으로 경력을 대신해 어필할 거리를 만드셔야 합니다.

실제로 보안 업무를 하고있고, 구직을 해보기도 구인을 해보기도 한 입장에서 제가 개인적으로 이력서에서 살펴보는 건  업무 경력 (수행한 프로젝트, 해당 프로젝트에서의 역할) --> 학력 --> 수상경력 --> 자격증 순인것 같습니다. 



어떻게 도움이 좀 되어 드렸는지 모르겠네요. 추가로 궁금한게 생기면 또 질문해주세요.

**Comment by davidkwak** [comment]
다른 유사한 고민을 하신 분과 거기에 대한 답변을 (저보다 훨씬 훌륭한 분께서 ^^) 달아주신 글도 있네요 

http://tigerteam.kr/main/xe/qna/9078

**Comment by PassionOfStudy** [comment]
성심성의껏 작성해 주신 davidwak님께 감사합니다!

답변 글을 읽어보니 제 머리에 속에 여러갈래의 길들이 몇개의 길로 좁혀진 것 같습니다. ^_^

어드바이스를 참고해서 2018년 이직을 목표로 열심히 달려야겠습니다.
