### ISSUE TITLE
안드로이드 : 특정 좌표값

### ISSUE THREAD

**Issue by beanbug** [codingeverybody/codingyahac#127]
어플 사용자 주변의 특정 건물들의 위치를 사용자들에게 알려주고 싶습니다.

현재 구글 places api 키를 받아서 제 주변의 500m 안의 음식점을 마커로 찍었는데

구글에서 가지고있는 음식점의 좌표들만 마커로 찍히더군요 

개발자가 나타내고싶은 음식점의 위치를 나타낼때는 서버에 db를 두어 좌표값을 넣어 어플을 개발하는게 맞는 건가요?

그렇다면 제가 원하는 음식점의 좌표는 어디서 확인할 수 있으며, 음식점, 주유소 등 특정 건물의 좌표값들을 모아놓은 곳들이 있는지 알고 싶습니다.

제가 생각한 방향이 맞는지도 알려주셧으면 좋겠고 이 문제에 도움이될 만한 글도 알려주시면 감사하겠습니다.!

해본방법 : 인터넷에서 원하는 음식점을 검색 후 html 코드에 좌표가 있나 확인해보았는데 정확한 좌표값이 아니고 이렇게 하는건 아닌 것 같다는 느낌이 들었습니다.

**Comment by blackdew** [comment]
음식점들의 주소와 전화번호를 모아놓은 데이터는 쉽게 구할 수 있을 것 같아요. 
DB에서 주소를 검색한 뒤에 주소 목록을 가지고 맵에서 위치 값을 조회하는 방식을 시도해 보고 싶네요. 
:)
