### ISSUE TITLE
(멜트다운(intel), 스펙터라)보안전문가 조력자님에게 질문드리고자 합니다

### ISSUE THREAD

**Issue by youngwon2** [codingeverybody/codingyahac#129]
CPU 제조사들의 CPU에서 멜트다운(intel), 스펙터라는 보안 버그발견 때문에 말이 많은데

일단 서버 운영하는 게임회사들이 타격이 클거같은데

개개인들은 안심하고 쓸 수 있는건지 궁금합니다

이에 대해서 사견같은게 있으면 들어보고도 싶네요^^

**Comment by davidkwak** [comment]
안녕하세요.

말씀하신 취약점들은 제 개인적인 생각으로는  heart bleed 나 shellshock 같은 대형 취약점을 모두 포함하더라도 최근 몇 년내에 발견된 버그 중 가장 파급력이 큰 취약점인것 같습니다. 

말씀하신대로 각종 서버를 운영하는 업체들이 타격이 크겠지만 일반 개인사용자들도 안심할 수는 없을것 같습니다.  악성코드에 해당 공격 기법이 이용 될 경우 CPU 캐시 메모리상의 중요 데이터를 가져갈 수 도 있고, 웹 사이트에서 자바스크립트로 공격이 가능하다는 것도 확인된 상황이기 때문에 특정 웹 사이트에 방문하는 것 만으로도 CPU 메모리 상의 정보가 유출 될 수도 있습니다. 

물론, 개인 사용자의 CPU내에 별다른 중요 정보가 저장되어 있을 타이밍에 해당 공격을 받을 가능성이 극히 적어보이긴 합니다만 적다는게 없다는건 아니니까요.

해당 취약점 패치를 하고나면 디스크I/O 성능 등이 하락한다고 하니 선택은 사용자의 몫이겠죠 ^^;

**Comment by youngwon2** [comment]
특정 웹사이트 방문만으로도 정보가 유출된다면
역시나 개인사용자도 안심할 수만은 없는 것이군요
감사합니다^ㅡ^
