### ISSUE TITLE
cordova 질문입니다!

### ISSUE THREAD

**Issue by yjh96** [codingeverybody/codingyahac#130]
cordova프로젝트로 코딩을 하면, 반드시 어플로 배포해야만 만든 웹사이트를 이용할 수 있나요?
시뮬레이터에서는 내용 표시가 되는데, 일반 웹브라우져로 접속하게되면 아무것도 뜨지가 않네요ㅜㅜ
src 폴더에 cordova.js 파일을 넣어줘도 socket.io가 작동을 안하는데,  cordova 시뮬레이터를 사용하면 socket.io가 작동을 해요 ㅠㅠ 왜그럴까요?

**Comment by progh2** [comment]
안녕하세요~ 
크롬에서 테스트 후 콘솔에 에러 메시지가 어떻게 나오나요?
cordova 작업해본지 오랜 시간이 흘러서 테스트 해볼 수는 없습니다만 ㅠㅠ 
특별히 오타나 경로 문제 등으로 인한 것이 아니라면(이런거라면 콘솔에 에러가 찍히겠죠?)
cordova가 해당 기기의 웹뷰/운영체제와 연결(의존)되어 동작하게 설계되어있어서
초기화 등에서 문제가 일어나기 때문에 일반 웹브라우져에서는 정상적으로 동작하지 못하는게 아닐까 하는 추측이 듭니다..

일반 데스크탑용 웹사이트와 같은 코드를 사용하는 것은 힘들 것으로 생각합니다.

**Comment by yjh96** [comment]
제 생각도 비슷합니다. cordova에 의존하는게 좀 많을것 같네요.
cordova 시뮬레이션에서 필요했던 js들을 똑같이 루트폴더에 정리해줬을때도 socket.io까지 못가더라구요.
http상태 OK로 통신이 끝나버려요 ㅠㅠ 
어쩔수 없이 저런 경우는 다시 코드를 짜야겠죠??
