### ISSUE TITLE
깃허브에 올린 모든파일 삭제한는법좀 알려주세요

### ISSUE THREAD

**Issue by testernewnic** [codingeverybody/codingyahac#131]
깃허브에 올린 모든파일 삭제한는법좀 알려주세요

**Comment by dongheegy** [comment]
1. 저장소 페이지 들어가면 오른쪽 위에 `Settings` 버튼이 있습니다 클릭해서 들어가시고..
![image](https://user-images.githubusercontent.com/13765815/34900395-f4d450d0-f842-11e7-9df2-e67371fec488.png)

1. 화면 맨 아래로 가시면 `Delete this repository` 항목이 있습니다. 클릭해서 저장소를 지우면 됩니다.
![image](https://user-images.githubusercontent.com/13765815/34900432-56008018-f843-11e7-84da-92966fdb1ca2.png)
