### ISSUE TITLE
github에서 지금까지 프로그래밍 해온 파일로 공식적인 웹을 만들려하는 데 잘 안되네요..

### ISSUE THREAD

**Issue by jungyun2916** [codingeverybody/codingyahac#132]
github에서 지금까지 프로그래밍 해온 파일로 공식적인 웹을 만들려하는 데 잘 안되네요..
<파일1>
<html>
<head>
<title>Variety story - story Earth science</title>
<meta charset="utf-8">
</head>
<body>
  <h1><a href="Welcome to variety story">variety story</a></h1>
<ol>
  <li><a href="story Issue">이슈</a></li>
  <li><a href="story Earth science">지구과학</a></li>
  <li><a href="story Math">수학</a></li>
</ol>
<h2>story Earth science</h2>
<p>
  지구과학은 지구를 대상으로 연구하는 학문들을 묶어 부르는 이름입니다. 일반적으로 지구과학으로 불리는 학문들은 대기에서 일어나는 현상을 대상으로
   하는 기상학, 지구 표면의 물질을 주로 대상으로 하는 지질학, 바다 현상을 대상으로 하는 해양학, 지구의 깊은 속에서 일어나는 현상을 대상으로 하는 지구물리학 등이 있습니다.
</p>
</body>
</html>

<파일2>
<html>
<head>
<title>Variety story - story Issue</title>
<meta charset="utf-8">
</head>
<body>
  <h1><a href="Welcome to variety story">variety story</a></h1>
<ol>
  <li><a href="story Issue">이슈</a></li>
  <li><a href="story Earth science">지구과학</a></li>
  <li><a href="story Math">수학</a></li>
</ol>
<h2>story Issue</h2>
<p>기업이 사회 일반 사람들의 관심이 되고 있는 사회적, 경제적, 정치적 문제를 다루고 있습니다. 흔히 다루고 있는 문제에 대하여 논쟁, 주장의 형식입니다.
</p>
</body>
</html>

<파일3>
<html>
<head>
<title>Variety story - story Math</title>
<meta charset="utf-8">
</head>
<body>
  <h1><a href="Welcome to variety story">variety story</a></h1>
<ol>
  <li><a href="story Issue">이슈</a></li>
  <li><a href="story Earth science">지구과학</a></li>
  <li><a href="story Math">수학</a></li>
</ol>
<h2>story Math</h2>
수학 양, 구조, 공간, 변화 등의 개념을 다루는 학문입니다. 현대 수학은 형식 논리를 이용해서 공리로 구성된 추상적 구조를 연구하는 학문으로 여겨지기도 한다.
수학은 그 구조와 발전 과정에서는 자연과학에 속하는 물리학을 비롯한 다른 학문들과 깊은 연관을 맺고 있으나, 여느 과학의 분야들과는 달리, 자연계에서 관측되지 않는 개념들에
대해서까지 이론을 일반화 및 추상화시킬 수 있다는 차이가 있습니다. 수학자들은 그러한 개념들에 대해서 추측을 하고, 적절하게 선택된 정의와 공리로부터의 엄밀한 연역을 통해서 추측
들의 진위를 파악합니다.
</body>
</html>

<파일4>
<html>
<head>
<title>variety story - variety story</title>
<meta charset="utf-8">
</head>
<body>
  <h1><a href="Welcome to variety story">variety story</a></h1>
<ol>
  <li><a href="story Issue">이슈</a></li>
  <li><a href="story Earth science">지구과학</a></li>
  <li><a href="story Math">수학</a></li>
</ol>
<h2>Welcome to variety story</h2>
<p><a href="http://www.kma.go.kr/index.jsp" target="_blank" title="기상청">
'variety story'에 오신 것을 환영합니다.</a>
<strong>'<u>variety</u> story'</strong>에서는 기상청의 자료를 통하여 다양한 이야기를 하는 웹입니다.</p>
<img src="카메라.jpg" width=35%>
</body>
</html>

-이렇게해서 공식적으로 웹을 만들었는데 하얀화면에 yun-story라고만 뜨네요..;;;;;

**Comment by dongheegy** [comment]
_해당 웹페이지 주소가 어떻게 되나요?_
얘기하신 저장소가 https://github.com/jungyun2916/variety-story 라면 .. index.html 파일이 없어서 README.md 파일이 기본으로 띄워진 것 같습니다. 해당 디렉토리 주소로 접근했을 때, 기본적으로 보여주고 싶은 페이지의 html 파일 이름을 index.html로 수정하시는 게 좋을 듯 합니다.
![image](https://user-images.githubusercontent.com/13765815/34900206-4879c3fc-f841-11e7-9d49-1fb2f285447e.png)
