### ISSUE TITLE
안녕하세요, 진로 관련 고민이 있습니다.

### ISSUE THREAD

**Issue by GmelaN** [codingeverybody/codingyahac#133]
안녕하세요. 저는 지방의 한 인문계 고등학교에 재학중인 (이제 고2 올라가는) 학생입니다.
 우선 저는 평소에 IT에 관심이 많습니다. 
인터넷을 떠돌다가 호기심이 가는 소식 (ex. 신제품 소식 등)이 있으면 인터넷을 통해 이를 찾아보고 이해하는데 소소한 즐거음을 느끼곤 합니다. 
어느덧 저는 진로를 결정해야 할 중요한 시기가 되었습니다.
 초등학교 때 막연하게 '과학자'를 생각했었는데, 격렬했던 사춘기(...)를 거치고, 중3이 되어서야 제 진로에 대한 갈피를 잡기 시작했습니다-바로 '<strong>프로그래머'</strong>로요.
고등학교에 입학하기 전, 저는 'JAVA 입문서'를 구매하여 지금까지 틈틈이 공부하고 있습니다. (첫 프로그래밍 언어로서 Java를 선택한 이유는 딱히 없었습니다...의식의 흐름대로 ㅠㅠ) 
 
여기서, 최근들어 고민이 생기기 시작했습니다.
고민을 말하기에 앞서, 저는 우리나라의 교육정책에 문제가 있다고 생각하는 입장입니다.
 ('수능'이라는 시험 하나가 상위권 대학을 가냐 못가냐를 결정하는... 그 시험이 합리적이면 몰라도, 원어민도 못 푸는 영어 문제를 출제하는건 좀.. 이래서 최근 수시의 비중이 높아지고는 있지만 이건 논외로 할게요) 
그래서 일까요, (물론 공부를 못하는 편은 아니지만) 요즘, 공부를 너무 하기가 싫습니다. 공부를 하려 해도 자꾸 코딩에 손이 가게 됩니다. 마음을 다잡고 하려해도 '내가 고3까지 잘 할 수 있을까?'라는 생각이 머릿속에서 떠나지를 않아요..ㅜ

...아무튼 제 질문은 2가지에요.

1. 코딩 관련 직업군은 채용시 대학 출신을 잘 가리지 않는다고 하던데, 실제로도 그러한지, 그러하지 않다면 다른 직업군들에 비해 어느정도로 출신을 가리는지 궁금해요.

2. [공부를 열심히 해서 괜찮은 대학을 졸업하고 취업에 도전한다] 와 [공부를 접고 코딩연습에 집중해서 고졸 (또는 전문대) 하고 취업에 도전한다] 중 어떤 방법을 선택하는 것이 나을까요? (다른 의견 있으시면 남겨주세요)

혹시 궁금한 점 있으시면 댓글로 남겨주시고, 기타 조언할 부분이 있으시다면 역시 댓글로 남겨주세요 :D

**Comment by davidkwak** [comment]
1)일반적으로 대학을 봅니다. 다만 어느정도 비중을두고 보느냐는 회사에 따라 다릅니다.  

2) 무조건 대학을 나오길 추천합니다.

**Comment by GmelaN** [comment]
그렇군요..조언 정말 감사드립니다.
