### ISSUE TITLE
버전관리시스템>>git이 관리할 대상으로 파일 등록 렉쳐에 관한 질문

### ISSUE THREAD

**Issue by minheeseo** [codingeverybody/codingyahac#134]
안녕허세요~ 렉쳐를 따라하다가 질문이 생겨서 여기에 적습니다. 이해도 잘 되고 저장소를 만드는 법도 알겠습니다만 영상과 제 terminal의 한가지 다른점은 제가 저장소를 만들면 영상처럼 옆에 "master"와 체크사인 부분이 뜨지않는다는 겁니다. 이런 부분은 따로 설정하신 건가요? 바쁘실텐데 먼저 감사의 말씀드립니다.

**Comment by happydeveloper** [comment]
@minheeseo 안녕하세요. 

아마도 생활코딩의 깃 강의를 보시고 말씀하신 것 같습니다. 맞나요? :)
영상안에 터미널에서는 [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) 이라는 셀프로그램이 설치되어 있어서 프롬프트에서 자동으로 브랜치가 표시가 되는 것입니다.

터미널창에서 깃이 셋팅되어 있는 디렉토리에 들어가면  셀 프롬프트에 "master" 라고 로컬저장소의 브랜치정보가 셀 프롬프트(명령창)에 뜨게 하게 위해서는  셀마다 있는 설정정보에 설정을 해주시면 됩니다.

기본셀인 bash 를 사용하시면 아래 링크를 참조하셔서 설정하시면 됩니다.
[다양한 환경에서 Git  사용하기](https://git-scm.com/book/ko/v2/Appendix-A%3A-%EB%8B%A4%EC%96%91%ED%95%9C-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-Git-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-Bash)

**Comment by minheeseo** [comment]
@happydeveloper 빠른 답변 정말 감사드립니다!
