### ISSUE TITLE
아톰 에디터를 사용할때 일괄저장 방법~

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#135]
아톰 에디터를 사용하고 있는데요 각 파일마다 수정하면 ctrl+S 를 눌러서 저장하곤 하는데요 

한번에 여러 파일을 수정한 다음에 일괄 저장하려면 어떻게 해야 하는지 궁금합니다.

**Comment by azaraks2** [comment]
맨 위 메뉴의 File tab에서 Save 밑에 Save as과 Save all이 있습니다.
전 맥이라서 윈도우 단축키는 모르겠네요.

**Comment by smartbos** [comment]
자동 저장 기능을 사용하시면 정신 건강에 도움이 됩니다. :)
http://junho85.pe.kr/m/526
