### ISSUE TITLE
github에서 공식 사이트를 만들었는데 리스트를 클릭하면 리스트가 다운로드 되네요..;;

### ISSUE THREAD

**Issue by jungyun2916** [codingeverybody/codingyahac#136]
github에서 공식 사이트를 만들었는데 리스트를 클릭하면 리스트가 다운로드 되네요..;;
https://jungyun2916.github.io/variety-story/
들어가시면 리스트를 클릭하면 다운만 되고 리스트가 열리지를 안아요..
그리고 사진도 안 보이네요...;;

**Comment by dongheegy** [comment]
- 링크된 html 파일 이름에 확장자 .html 을 입력하시면 잘 보일 듯 합니다.

- [소스코드](https://github.com/jungyun2916/variety-story/blob/efb4f905b1ae07672b921a6f9c32fecd9a7f069a/index.html#L17)에 보면 img 태그에서 "카메라.jpg" 파일을 src 속성으로 지정하고 있는데, [저장소](https://github.com/jungyun2916/variety-story)에는 해당 파일이 없습니다. 사진 파일을 같이 업로드하셔야 표시됩니다.

**Comment by dongheegy** [comment]
추가로... 링크된 html 파일 이름뿐만 아니라 각각의 a 태그에 지정된 href 속성에도 수정된 파일 이름을 적용해주어야 합니다.
