### ISSUE TITLE
javascript: textarea에서 이벤트 발생시키는 법

### ISSUE THREAD

**Issue by umu05** [codingeverybody/codingyahac#138]
안녕하세요?
저는 자바스크립트 아주 기초적인 문법만 한번 살펴본 상태이고요, 제가 만들고 싶은것은, 일단 외관상으로는 
http://speller.cs.pusan.ac.kr/PnuWebSpeller/
이런 모습인데요,

textarea안에 텍스트를 붙여넣기 해서 단어를 클릭하면 빈칸으로 만들거나, 혹은 다른 단어로 바꾸거나, 문장을 드래그 해서 선택하면 단어의 순서를 스크램블 형태로 섞는 프로그램을 만들고 싶어요. 그런데 textarea안에서 단어를 클릭하거나 드래그 선택할 경우 이벤트를 발생시키려면  (마치 onkeypress처럼) 어떻게 해야할지 혹은 어느 부분을 구글 검색해야 하거나 공부해야 할지 실마리라도 주시면 감사하겠습니다. 공부해서 만들어 보고 싶어요. 감사합니다.

**Comment by azaraks2** [comment]
HTML DOM Events부터 보세요.

**Comment by umu05** [comment]
너무 감사합니다~^^
