### ISSUE TITLE
link 태그 관련 질문입니다.

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#139]
link 태그를 적용할때 

http://localhost/html/1.html 과

http://125.140.217.115/html/1.html 를 

적용할 경우 

로컬 호스트는 코드내용을 변경 저장하면 바로 웹상으로 볼수 가 잇는데 

IP주로를 이용하면 에디터에서 코드를 변경 저장 하여도 바로 적용이 안되는 현상이 발생하는 데요 

이건 정상적인 반응 인가요 아니면 어떠한 설정이 필요한 건가요?

**Comment by Trostal** [comment]
브라우저에서 페이지 캐싱을 하는걸로 생각됩니다.

이 사실을 확인해보시려면, 크롬 기준으로
Ctrl + Shift + R[또는 F5] 버튼을 누르시면 
'강력 새로고침(Hard Reload)' 이라는 기능을 통해 새로고침을 합니다.
위 기능으로 브라우저 캐시를 무시하고 새로 정보를 불러옵니다.

어떤 서버를 사용하는지는 잘 모르겠지만
혹시 서버단에서 캐시설정이 되어있다면, 캐시설정을 한 번 확인해보시기 바랍니다.
서버에서 response할 때 캐싱하지 않도록 헤더를 설정하실 수도 있습니다.
