### ISSUE TITLE
python GUI프로그래밍에 대해 질문합니다

### ISSUE THREAD

**Issue by bernardokang** [codingeverybody/codingyahac#141]
제가 현재 바로 써먹을 수 있는 언어는 python/javascript/html/css/sql(mysql) 이렇게 있습니다. 저는 제가 어떤 일(공부 등)을 완수 하고 push버튼을 클릭하면 계산된 퍼센트가 올라가는 프로그램을 만들고 싶은데요. 그래서 python tkinter를 공부했고 제가 원하는 기능이 구현될 수 없다는 것을 알고(=gif 애니메이션이 들어간 gui) PyQt를 하기로 선택했습니다. 그리고 데이터 관리가 생각보다 많이 필요해서(30개 미션과목..)db를 쓰는게 낫겟다 싶어 MySql을 독파했습니다. 드디어 PyQt5로 간단하게 레이아웃을 짜고 배치만을 해보았고 간단히 수치는 받을 수는 있습니다.
(스크린샷)
![ex](https://user-images.githubusercontent.com/31756020/34908034-882af7e2-f8cc-11e7-886e-0acf671c2c25.png)

그런데 아직 실력이 없어서 Qt 라이브러리를 하나하나 쳐보고 직접확인하고 알아내는게 너무 시간도 오래걸리고 지칩니다(Qt4에서 Qt5로 버전 업그레이드가 있었고 Qt5에 대한 자료는 또 적어서 Doc을 보아야만 하는데 Doc은 C++위주로 되어있습니다) 지금은 C++을 공부해야겠다는 생각을 하다가 고민이 많아져서 질문합니다. 어떻게 하면 gui내공을 키울수 있을까요? 저는 GUI에 대한 이해도가 별로 없는 것 같습니다. 근데도 움직이는 효과도 넣고싶고, 제가 목표한 것은 꼭 이루고 싶은데

**Comment by blackdew** [comment]
pyQT로 gui를 제작하는 것은 doc나 reference가 부족해서 뭔가 만들어가는 데에 어려움이 많을 것 같습니다.  
차라리  python/javascript/css/html 을 이용하여 웹으로 애플리케이션을 제작한 뒤에 eletron(http://electronjs.org/) 같은 도구를 이용해서 PC용 애플리케이션으로 만드시는 것을 추천드립니다.

**Comment by azaraks2** [comment]
지금 써먹을 수 있는게 그렇다면 윗분 말씀대로 웹으로 만드는 게 나아보입니다.
qt가 멀티플랫폼으로 개발하기에는 좋습니다. qt creator가 편하다는 전제하에..
