### ISSUE TITLE
데이터베이스 mysql 실습 에러 입니다 

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#142]
# 증상

```
<?php
   $conn = mysqli_connect("localhost", "root", 111111);
   mysqli_select_db($conn,'opentutorials');
   $result = mysqli_query($conn, "SELECT * FORM topic");
   $row = mysqli_fetch_assoc($result);

echo "<br/>";
   
   echo $row('id');
   echo $row('title');
 ?>
```

위와 같이 코드를 작성했을때 아래와 같이 에러 메세지가 뜹니다.

Warning: mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 2

Warning: mysqli_select_db() expects parameter 1 to be mysqli, boolean given in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 3

Warning: mysqli_query() expects parameter 1 to be mysqli, boolean given in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 4

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, null given in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 5

Fatal error: Uncaught Error: Function name must be a string in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php:9 Stack trace: #0 {main} thrown in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 9

확인 부탁드립니다.

# 환경

윈도우10, 크롬 입니다.

**Comment by dhchoi82** [comment]
[mysqli_connect 함수에 대한 공식문서](http://php.net/manual/kr/mysqli.construct.php)를 확인해보면 password는 string (문자열) 형이어야 합니다. 입력하신 password에 따옴표를 추가하셔야 할 듯 합니다.
`$conn = mysqli_connect("localhost", "root", 111111);`
`$conn = mysqli_connect("localhost", "root", "111111");`

**Comment by chung0906** [comment]
실습영상에서는 따옴표를 붙이지 않아도 실해이 되던데요?

**Comment by dhchoi82** [comment]
`Warning: mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in C:\Bitnami\wampstack-7.1.12-0\apache2\htdocs\php\index.php on line 2`
데이터베이스 접속에서 에러가 나서 그 이후의 구문도 줄줄이 에러가 나고 있는 듯 한데, password 문제가 아니라면 root 랑 localhost 중에 잘못된 것이 있겠네요. 처음 서버 설정과 일치하는지 확인해보셔야 할 것 같네요. (참고로 localhost는 Mysql 서버가 설치된 컴퓨터와 PHP 서버가 설치된 컴퓨터가 동일한 경우에만 제대로 동작합니다.)

**Comment by progh2** [comment]
@dhchoi82 님 말씀대로 로그인 정보가 올바른지 먼저 확인이 필요할 것 같습니다. 
먼저 [cmd에서 입력하신 아이디와 암호로 mysql 접속이 가능한지](https://www.google.co.kr/search?ei=AulcWqi3OsK68QXiiZ34BA&q=cmd+mysql+%EB%A1%9C%EA%B7%B8%EC%9D%B8&oq=cmd+mysql+%EB%A1%9C%EA%B7%B8%EC%9D%B8&gs_l=psy-ab.3..0i30k1.590072.593351.0.593553.19.14.0.5.5.0.252.1464.8j4j1.14.0....0...1c.1j4.64.psy-ab..1.16.1282.0..0j0i131k1j0i131i67k1j0i67k1j0i13i30k1j0i8i13i30k1.85.ki8i-P0lPUA) 먼저 확인해보면 어떨까요?
mysql 설치할 때 입력했던 root 암호가 111111이 맞나요? 맞다면 위 cmd에서 로그인이 되어야 합니다.

**Comment by azaraks2** [comment]
비트나미는 mysql root 기본 암호 bitnami입니다. 변경한게 맞습니까?
https://docs.bitnami.com/virtual-machine/components/mysql/
