### ISSUE TITLE
데이터베이스 삭제하기

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#146]
REATE DATABASE opentutorials CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `topic` (
`id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `author` varchar(30) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

데이터베이스 강의 내용에 따라 프로토콜에서 

데이터 베이스를 만들었는데요 데이터베이스를 삭제할려면 어떻게 해야 하나요?

**Comment by dhchoi82** [comment]
https://opentutorials.org/module/98/1404
위 강의를 보면 ```DROP DATABASE `opentutorials`;```로 삭제 가능할 듯 합니다.

**Comment by ghdalsrldi** [comment]
```sql
# 데이터베이스 삭제
DROP DATABASE `opentutorials`;

# 테이블 삭제
DROP TABLE `topic`;

```

입니다
