### ISSUE TITLE
웹페이지에서 mdi 구현시요???

### ISSUE THREAD

**Issue by gmkjh74** [codingeverybody/codingyahac#147]
하나의 크롬 웹페이지 내에 mdi로 탭방식으로 페이지 열경우에 최대 5개 이상 열게 되면 부하가 많다고 하던데요...?
그럼 웹에서는 하나의 페이지에서 여러개의 탭으로 된 웹 어플리케이션 구축을 할수 없나요??

**Comment by progh2** [comment]
정확히 무엇을 하려는 것인지 구체적으로 이야기 해주실 수 있을까요? 
구글독스나 구글스프레드시트 같은 실시간 공유 작업이 가능한 것을 만들려는 것인지,
아니면 화면을 여러 탭으로 나눠서 동작하게 하는 무엇인가 만들려는 것인지 정확히 그려지지 않습니다.

어떤 목적으로 무엇을 만들기 위해 어떤걸 할려는지 구체적으로 표현해주시면 
답변하는 분들이 더 좋은 답변을 줄 수 있을 것 같습니다.

**Comment by gmkjh74** [comment]
네 음...,ERP 같은것을 보면 여러개의 메뉴가 있을수 있잖아요..
그런 여러개의 메뉴를 탭으로 처리 하려고 하는것입니다.
하나의 페이지 내에서 말이죠...

화면은 데이터 조회된 상태를 유지하고 있어야 하고요...

아 !! 엑셀 보시면 아래 여러개의 sheet가 있잖습니다...그런것을 말하는 겁니다.

![image](https://user-images.githubusercontent.com/35083092/34965149-3f051dd4-fa95-11e7-869b-b741ab2b4af3.png)

**Comment by happydeveloper** [comment]
css 와 JavaScript 기술을 이용하면 탭 UI 인터페이스를 웹에서 구현 할 수 있습니다. 
아래 페이지를 참고하시면 도움이 되실 것 같습니다.

[how to tab](https://www.w3schools.com/howto/howto_js_tabs.asp)
