### ISSUE TITLE
보안 시스템 분야 취업은 뭐부터 시작하면 좋을까요

### ISSUE THREAD

**Issue by schyyy** [codingeverybody/codingyahac#148]
안녕하세요 조력자님

보안쪽은 내공이 쌓여야 하다고 들었는데요.
그래도 10년쯤 내다보고 한다면 어느정도 비전이 있고 프리랜서로도 나갈 수도 있다고 해서 독하게 마음먹고 해보려고 합니다.
우선 웹 기초(HTML, CSS, Javascript, php, mysql), 자바는 해봤는데요. 보안은 어떤 프로그래밍 언어를 공부해야 하는지 그리고 공부방향은 어떻게 잡으면 될지 조언해주시면 정말 감사하겠습니다. 자격증 같은 것도 필요하다면 소개해주세요.

감사합니다.

**Comment by davidkwak** [comment]
안녕하세요 

보안 뿐 아니라 다른 분야도 내공이 쌓이고 능력을 인정 받으면 비전은 다 있다고 봅니다. 
그렇지만 보안쪽 분야를 위주로 설명 드리자면, 많이 쓰는 언어는 요즘은 파이썬을 많이 쓰는 추세입니다. 
C나 C++도 많이 쓰긴하지만 그렇게 본격적으로 시스템에 Deep down  해서 뭔가를 하는것보다 
파이썬 같이 빠르고 생산성 높은 언어가 더 많이 쓰입니다. (배우기도 쉽고요 ㅎㅎ)

공부 방향은... 자격증과 어느정도 통하는데 국내의 "정보보안기사"나 해외 자격증으로는 "CISA", "CISSP"  같은 자격증을 준비하시다보면 공부해야하는 화두는 어느정도 감을 잡으실 겁니다.  

질문자 뿐 아니라 다른 구직자 분들께 아주 작은 팁을 드리자면, 내가 가고자 하는 분야에서 어떤 기술, 자격증, 경력을 요구하는지는 "구인광고"에서 가장 잘 알 수 있습니다. 사람인 같은 사이트에서 보안 분야의 구인광고를 보면 
"보안기사"/"CISSP" 우대 / " ISMS" 경력자 우대 같은 내용들을 보실 수 있고, 그런 키워드로 검색해서 찾아보시면 갈 길이 조금은 보이실 겁니다.
