### ISSUE TITLE
이 길을 걷고 싶은데 조언을 구합니다!

### ISSUE THREAD

**Issue by HOONI2** [codingeverybody/codingyahac#149]
웹호스팅 업체 IDC센터에서 근무를 하다가 네트워크의 길을 걷고 있습니다

쉬는 동안 HTML 해커톤을 경험하고 틈틈히 생활코딩에서 코딩을 배우고 있습니다

나이는 이제 앞자리가 3이 되었네요ㅎㅎㅎ 뭔가 새로운 걸 만들고 싶고 개발을 하고싶네요

이론적으로는 조금씩 듣고 이리저리 공부를 하는데 프로젝트라는 걸 해야 발전이 있을거 같은데

이런저런일을 많이 경험했지만 도무지 딱 떠오르는... 첫발을 내딛기가 어렵다고(?) 느낍니다

먼저 이 분야를 접하시고 실력이 있으신 조력자님들과 이고잉님의 조언을 부탁드려봅니다!

항상 좋은 강의 감사드려요!

**Comment by progh2** [comment]
안녕하세요~
관심 있으신 프로그래밍 언어 등이 있다면 관련 커뮤니티 활동, 세미나 참가 등을 하면서
활동을 해보는 것은 어떨까 합니다. 스터디 등에 참가하거나 만들어서 작은 프로젝트 만들며
경험을 공유하기도 하면서요.. 이 과정에서 다른 학습자가 개발자들과 만나면서 이런저런
많은 책에 나와있지 않은 것도 배울 수 있고 여러 경험을 공유할 수 있다고 생각합니다. ^^
게다가 IDC센터에 있었다면 나름 그쪽에서 이루어지는 경험을 공유하실 수도 있을 것 같네요~
