### ISSUE TITLE
Node.js 다중 게시판 로직(?)이 궁금합니다.

### ISSUE THREAD

**Issue by hanlyang** [codingeverybody/codingyahac#150]
안녕하세요. 개인 프로젝트로 node.js를 이용해 게시판을 만들고 있습니다.
여러개의 게시판으로 구성된 사이트를 만들려고 하는데, 전체적인 흐름을 모르겠습니다.
(그동안은 게시판 1개짜리 예제용 게시판 등만 만들어 보았습니다.)

제가 만든 형태는
DB(mysql)에 menu1, menu2, menu3 이런식으로 테이블을 준비하고

``` javascript
// 테이블 목록을 배열로 만들어 저장하고
const menu = ['menu1' 'menu2', 'menu3'];
 
router.get('/:menu', (req, res, next) => {
    // menu 파라미터가 배열에 있으면
    // 그에 해당하는 테이블을 읽어와 목록을 보여준다. 
});

router.post('/:menu/create', (req, res, next) => {
    // 메뉴파라미터가 배열에 있으면 그 테이블에 글을 쓴다.
});

router.get('/:menu/:no', (req, res, next) => {
    // menu 파라미터가 배열에 있으면 글 번호에 해당하는 데이터를 읽어와 상세페이지에 보여준다.
});

router.post('/:menu/:no/update', (req, res, next) => {
    // 메뉴파라미터가 배열에 있고, 글 번호가 그 테이블에 있으면 글을 수정한다.
});
```

이런 식으로 짰는데요. 일단 결과는 원하는데로 나오고 돌아는 가는데 과연 이렇게 하는것이 맞는지 모르겠습니다. 한마디로 제가 짠 코드를 신뢰하지를 못하겠어요.

가령 이용자가 정해진 링크(예: domain.com/menu1)로 접근하지 않고, 자기 마음대로 주소를 입력했을때를 대비해 일일이 예외처리식으로  menu에 해당하는 파라미터가 실제 존재하는 테이블인지 아닌지 확인해주는 것이 맞는지, 불필요한 과정인지도 모르겠고, 각 게시판에 해당하는 테이블들을 저렇게 단순한 배열로 정의해도 되는것인지도 모르겠습니다.

게시판간에 게시물 이동을 원할하게 하려면 저렇게 게시판별로 테이블을 따로 만들것이 아니라 게시판은 1개로 만들고 따로 게시판 분류를 저장하는 칼럼을 만들어 운영해야 하는게 아닌가 싶기도 하고... 초보자 입장에서 실제 상용 서비스들은 어떤식으로 운영되는지 로직(?)이 너무 궁금합니다.

대략적인 흐름만이라도 좀 알려주시면 감사하겠습니다.

**Comment by progh2** [comment]
게시판 설정을 db로 관리해서 입력한 게시판이 존재하는지 확인해서 처리하는 식으로 구성하면 어떨까요?
그러기 위해서는 게시판 추가/설정/삭제 등을 할 수 있도록 관리자 메뉴가 있어야 하겠지만
같은 성격의 게시판이라면 한번에 운영이 가능할 것입니다. 

이러한 것을 해보기 위해서 한번 제로보드 등 다양한 기존 오픈소스 게시판들을
설치해서 관리자 메뉴가 어떻게 동작하는지, URL이 어떻게 접근하도록 세팅되는지를
살펴보는 것도 좋은 경험이 될꺼라 생각해서 추천드립니다. (아래는 PHP로 된 게시판입니다. 살펴보세요)

[XE](https://www.xpressengine.com/)
[그누보드](https://sir.kr/)

**Comment by hanlyang** [comment]
@progh2 안녕하세요. 답변해주셔서 감사합니다. 배열에 담은 것들을 게시판 설정 db로 관리한다는거군요.
 저도 node.js로 cms를 만들려고 하는거라 그누보드 참고해보려 했으나 소스를 봐도 (초보라서) 너무 복잡하고 뭐가뭔지 하나도 모르겠더라구요. ㅠㅠ 아무쪼록 답변 감사합니다.
