### ISSUE TITLE
깃 강의 git commit 에 대한 질문

### ISSUE THREAD

**Issue by minheeseo** [codingeverybody/codingyahac#151]
안녕하세요. 깃 강의를 듣다가 또 모르는 점이 생겼는데 인터넷을 찾아봐도 잘 모르겠어서 여기에 또 질문하게 되었습니다.
강의에서는 git commit이란 코멘드를 입력하면 그 다음에 원하는 문구를 insert하게 되어있는데요. 제 terminal에서는 git commit이라고 치면 
"error: unable to start editor 'gedit'
Please supply the message using either -m or -F option." 이런 에러가 뜹니다.
git commit -m "update new file" 이런식으로 코멘드를 입력하면 코밋이 잘 되고요.. 왜 git commit명령어는 실행되지 않는데 git commit -m "description" 이 명령어는 잘 실행이 될까요? 에러에서 gedit이랑 에디터를 설치하라는 것 같은데 찾아봐도 도통 모르겠네요. 도움 주셔서 감사합니다.

**Comment by progh2** [comment]
안녕하세요~ 반갑습니다. ^^
git commit 으로 명령을 실행하면 메시지 작성을 위한 텍스트 에디터가 실행됩니다.
이것은 git 기본 설정이 어떻게 되었냐에 따라서 어떤 에디터가 실행되는지가 다른데요,
gedit는 리눅스에서 사용하는 메모장 같은 프로그램인데 그게 설치가 되어 있지 않아서
발생하는 에러입니다. 

gedit로 하고 싶으시다면 사용하시는 리눅스에서 관리자 권한으로 gedit를 설치하세요.
우분투/민트/데비안이라면 

> apt-get install gedit 

레드햇 계열이면 
> yum install gedit

로 설치하시면 됩니다.

아니면 선호하는 에디터(예: vim 이나 nano)가 있으시다면 
[Git 편집기 변경](https://git-scm.com/book/ko/v1/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-Git-%EC%B5%9C%EC%B4%88-%EC%84%A4%EC%A0%95#%ED%8E%B8%EC%A7%91%EA%B8%B0) <-- 이 링크를 참고하셔서 변경하시면 됩니다. 
[좀 더 다양한 검색 링크](https://www.google.co.kr/search?q=git+%EC%97%90%EB%94%94%ED%84%B0+%EB%B3%80%EA%B2%BD&oq=git+%EC%97%90%EB%94%94%ED%84%B0+%EB%B3%80%EA%B2%BD&aqs=chrome..69i57j69i64.2650j0j4&sourceid=chrome&ie=UTF-8) 내용도 찾아서 봐보세요~ 

즐거운 시간 보내길 바랍니다. =D

**Comment by minheeseo** [comment]
@progh2  안녕하세요. 답변 너무 감사드립니다. follow-up question이 있는데요. 제가 리눅스가 아니라 맥을 쓰고 있거든요. 맥의 경우에도 progh2님 답변이 똑같이 적용되는 건가요? 감사합니다!

**Comment by progh2** [comment]
맥이면 서브라임텍스트나 아톰 등 다른 자주 사용하시는 에디터로 설정하시는 것이 좋겠습니다.
[맥에서 쓰는 gedit](https://www.google.co.kr/search?ei=R-NcWq_eJYn78gW97KngAQ&q=osx+gedit&oq=osx+gedit&gs_l=psy-ab.3..0j0i10i30k1l2j0i5i10i30k1l2j0i8i10i30k1l3j0i8i30k1l2.1241960.1244615.0.1244763.11.10.1.0.0.0.240.1179.6j3j1.10.0....0...1c.1j4.64.psy-ab..0.11.1179...0i131k1j0i67k1j0i10k1j0i13k1j0i13i30k1j0i30k1.0.hrexCjKMEHI)도 있지만 주로 사용하시는 에디터(atom 등)를 쓰시는게 좋겠습니다. ^^

[참고링크](https://help.github.com/articles/associating-text-editors-with-git/#platform-mac)

**Comment by minheeseo** [comment]
@progh2 그렇군요 문제가 잘 해결되었습니다. 너무 감사합니다.
