### ISSUE TITLE
1:1 메신저를 만들기 위한 기술이 궁금합니다.

### ISSUE THREAD

**Issue by hanlyang** [codingeverybody/codingyahac#152]
안녕하세요. 우선 야학이 하루밖에 남지않아 이렇게 두서없이 이질문 저질문 올리게 되어 죄송합니다.

비트윈(https://between.us/?lang=ko) 같은 1:1 커플 메신저 어플을 만들고자 하는데요. 
지금 네이티브앱을 위해 자바, 안드로이드를 따로 공부할 수 있는 상황은 못되고,
그나마 조금이라도 할줄 아는 것이 html/css/javascript + 서버쪽은 node.js입니다.
(socket.io를 이용해 간단한 예제수준의 웹채팅을 만들어보긴 했습니다.)

지금 생각한 것은 (최대한 아는 것을 활용해) 프론트쪽은 html/css/js를 사용해서 짜고
서버는 node.js의 socket.io를 쓰던지, 아니면 firebase를 배워서 쓰던지 하려고 합니다.

**질문** 

유저의 대화내용은 그냥 디비서버에 암호화해서 저장하고 채팅방에는 디비서버에서 데이터를 읽어오면 되겠다고 생각했었는데 검색을 해보니 실제 메신저 어플은 유저의 데이터가 디비서버에 저장되는 것이 아니라 유저의 기계에 저장된다고 하는것 같았습니다. 네이티브앱은 기기의 sqlite를 사용하면 되는 것으로 알고 있는데 위에 말씀드린 웹기술을 활용해 만들려면 그런 부분은 어떤식으로 처리되어야 하는지 궁금합니다.

**Comment by progh2** [comment]
안녕하세요~ 
간단히 구현하신다면 firebase를 써서 만들어도 충분할 것 같습니다.
 firebase의 리얼타임디비가 실시간으로 동기화 기능을 제공해주기 때문에 원하시는 기능을
쉽고 빠르게 구현할 수 있을 것으로 생각됩니다. ^^
데이터는 암호화해서 저장하고 기기에서 복호화해서 출력해주는 식으로 하면 될 것 같고요
암호화/복호화에 사용할 비밀키만 서로 공유해서 설정해서 쓴다든가 식으로 하면 괜찮지 않을까 싶네요.

메신저 어플이 그런 구조를 가지는 것은 이전 데이터 자료가 쌓여서 부담이 된다던가, 
데이터가 계속 남아있어서 가져갈 수 있다던가 등의 문제 때문에 그런 것이 아닌가 싶습니다.
또 페이스북 메신저나 슬랙 같은 경우도 다운로드 방식이 아니라 서버서 계속 읽어오는 구조기도 하고요.
일정 시간이 지난 글은 삭제하게 한다던가 하는 것도 방법이라 생각합니다. 

좋은 시간 보내세요~ =)

**Comment by blackdew** [comment]
클라이언트에 대화의 내용을 저장하는 것은 기본적으로 '캐싱(caching)'의 의미가 큽니다. 대화를 하면서 이전에 대화한 내용을 스크롤해서 찾아본다고 할 때에, 그 때마다 DB에서 내용을 보내주는 것은 서버에는 부하이고 네트워크에는 낭비가 되거든요. 이전의 대화내용을 클라이언트에 저장해 놓으면 서버의 부담도 줄고 네트워크 비용도 사라지게 됩니다. 

브라우저도 웹에 접속하면 페이지를 저장(캐싱)해 두었다가 서버의 변경사항이 없으면 local에 저장된 것을 다시 보여주지요. 같은 개념이라고 생각하면 됩니다. :)

**Comment by hanlyang** [comment]
@progh2 답변 감사합니다. 말씀해주신 방법으로 해도 되겠네요. 한가지만 더 여쭤보고 싶은데요. 만약 html과 firebase 조합으로 채팅을 만들게 되면 앱이 아니니 당연히 유저가 마켓에서 다운받을 필요는 없을것이고, 그냥 서비스 url로 접속해서 이용을 하게 되는 구조가 되는것이죠?

**Comment by hanlyang** [comment]
@blackdew 안녕하세요. 답변 감사합니다.  웹캐싱은 제가 어떻게 프로그램을 짜는게 아니라 브라우저에서 알아서 작동하는거 아닌가요? 대화 내용을 어떻게 클라이언트쪽에 저장해야 하는지 답변만 봐서는 이해가 잘 가지 않는데 조금만 더 알려주시면 안될까요? ㅠㅠ

**Comment by progh2** [comment]
네 맞습니다. 다만 파이어베이스 안드로이드, ios용 sdk도 존재해서 해당 sdk를 사용하면 쉽게 만들 수 있고 역시 웹에서 만든 것과 같이 연동해서 동작합니다. 이게 큰 장점이죠.

**Comment by hanlyang** [comment]
@progh2 넵. 답변 감사합니다. ^^

**Comment by blackdew** [comment]
브라우저에서 캐시가 구현이 되어있는 것이죠. 캐쉬의 개념이라는 것을 말씀드리는 것이에요. 

클라이언트에 대화내용을 저장하는 방식은 파일에 저장을 할 수도 있고요. 
sqlite 같은 클라이언트용 가벼운 db에 저장하셔도 됩니다. :) 

"how to use sqlite in [언어혹은플랫폼]"와 같은 검색어로 검색해 보시면 원하시는 자료를 찾으실 수 있을거에요.

**Comment by hanlyang** [comment]
@blackdew 넵. 답변 감사합니다. ^^
