### ISSUE TITLE
아톰 스크롤바가 끊없이 늘어나서 작성한 코드를 한 화면에 볼 수 없습니다.

### ISSUE THREAD

**Issue by hkim29** [codingeverybody/codingyahac#153]
스크롤바가 한없이 늘어나서 코드를 한 화면에 볼수가 없습니다.
어떻게 세팅을 바꿀수 있나요?

![screen shot 2018-01-15 at 12 41 12 pm](https://user-images.githubusercontent.com/6721149/34955214-72b60cc8-f9f1-11e7-93b7-99eeacbb5f7f.png)

**Comment by progh2** [comment]
안녕하세요~

구글에서 [아톰 에디터 자동줄바꿈](https://www.google.co.kr/search?q=%EC%95%84%ED%86%B0+%EC%97%90%EB%94%94%ED%84%B0+%EC%9E%90%EB%8F%99%EC%A4%84%EB%B0%94%EA%BF%88&oq=%EC%95%84%ED%86%B0+%EC%97%90%EB%94%94%ED%84%B0+%EC%9E%90%EB%8F%99%EC%A4%84%EB%B0%94%EA%BF%88&aqs=chrome..69i57.7683j0j9&sourceid=chrome&ie=UTF-8) 검색해보세요 ^^

**Comment by azaraks2** [comment]
Settings - Editor - Soft Wrap / Soft Wrap At Preffered Line Length

**Comment by hkim29** [comment]
감사합니다!
