### ISSUE TITLE
#html iframe 태그 내용 수정

### ISSUE THREAD

**Issue by ghost** [codingeverybody/codingyahac#154]
안녕하세요. 여러분의 시간을 위하여 질문만 적겠습니다. 양해바랍니다.
구글시트 웹 게시 내용의 디자인을 수정하고 싶습니다.

## 구조
1. 일일 매출을 위한 구글 시트
2. 인트라넷 게시판

## 설명
1의 정보를 2의 페이지에 대시보드 형식으로 넣었습니다.
구글 시트의 Publish(웹에 게시)기능 중, 문서에 삽입으로 연결해보았는데요,
<iframe>태그 안의 내용을 수정할 수 없더군요. 글씨 폰트와 크기, 헤더정보, 배경색상 등 디자인 요소를 수정하고 싶습니다. 

## 사진

![2018-01-16 12 41 43](https://user-images.githubusercontent.com/33408349/34971104-e56596e2-fabb-11e7-9089-4c99fd809040.JPG)

## 프레임 소스

<!DOCTYPE html><html><head><title>*** 매출보고</title><meta name="viewport" content="target-densitydpi=device-dpi,user-scalable=1,minimum-scale=1,maximum-scale=2.5,initial-scale=1,width=device-width"><link href='/static/spreadsheets2/client/css/2702751554-waffle_k_ltr.css' type='text/css' rel='stylesheet'><style type="text/css" nonce="bJfWPyRCEN8vPWwWzNdJpGwxx8U">
  | html { overflow: visible; }
  | #sheets-viewport { overflow: auto; }
  | #sheets-viewport.widget-viewport { overflow: hidden; }
  | .grid-container { overflow: visible; background: white;}
  | .grid-table-container { overflow: visible; }
  | #top-bar {
  | background: url("//ssl.gstatic.com/docs/spreadsheets/publishheader.png") repeat-x bottom;
  | margin: 0;
  | overflow: hidden;
  | }
  | #top-bar {
  | border-bottom: 1px solid #ccc;
  | padding: 6px 6px 0;
  | }
  | #doc-title { padding-bottom: 5px; }
  | #doc-title .name { font-size: 15px; }
  | #sheet-menu {
  | font-size: 13px;
  | margin: 6px 0 0;
  | padding: 0 0 5px;
  | }
  | #sheet-menu li {
  | display: inline;
  | list-style-type: none;
  | margin: 0;
  | padding: 5px 8px;
  | }
  | #sheet-menu li.active {
  | background-color: #fff;
  | font-weight: bold;
  | border: 1px solid #999;
  | }
  | #top-bar #sheet-menu li.active {
  | border-bottom: 0;
  | }
  | #sheet-menu a, #sheet-menu a:visited { color: #07c; }
  | #footer {
  | background: #f0f0f0;
  | border-top: 1px #ccc solid;
  | border-bottom: 1px #ccc solid;
  | font-size: 13;
  | padding: 10px 10px;
  | }
  | .dash {
  | padding: 0 6px;

...이후 구글 시트 정보, api 등...

##시도해본 방법
jQuery로 콘텐츠 수정할 방법을 알게 되었습니다. .content()로 내보 소스를 변경하는 것 같은데요, 구글시트가 제공하는 iframe 내 소스가 무지하게 많아(....)서 다른 방법이 있을까 질문 올립니다. 아니면 꼭 구글 시트가 아니더라도 스프레드시트를 웹페이지에 게시할 방법이 있을까요? 물론 변경사항이 실시간 반영되어야 합니다. 

귀한 시간 읽어주셔서 감사합니다.

**Comment by egoing** [comment]
이렇게 하실 수 있습니다. php와 같은 기술을 이용해서 publish 된 웹페이지를 다운로드 받습니다. 그것을 화면에 뿌리면서 디자인을 제어합니다. 

예를들면 아래와 같은 코드가 가능하겠네요. 
```php
<html>
<head>
<style>
디자인 코드
</style>
</head>
<body>
<?php
echo file_get_contents('publish된 url');
?>
</body>
</html>

**Comment by Benjamin-KIm** [comment]
iframe내부 src경로 내용을 파일겟 할수 있군요!! 헠헠!! 게시내용 디자인을 변경시킨 뒤 인트라넷웹서버에 저장하고 인트라넷 게시판에 전송하면 되겠네요. 감사합니다!
