### ISSUE TITLE
에디터 툴(IDE)을 사용하는 방법도 배우는 것이 좋을까요

### ISSUE THREAD

**Issue by bernardokang** [codingeverybody/codingyahac#155]
지금은 아는게 적어서 IDE를 그냥 주어진대로 쓰는 편인데요 
예를 들어, 유튜브에 서브라임텍스트를 검색해보면 튜토리얼로 3시간이 넘는 강의가 있는 경우도 있습니다
이런 툴을 사용하는 방법들을 배우는 데 시간을 투자하는 것이 효율적일지 궁금합니다
현재 저는 제가 어떤 기능을 원하는지도 잘 몰라서 검색하기도 어렵네요

**Comment by ghdalsrldi** [comment]
효율적입니다.

하지만 IDE는 보조적인 도구 입니다.

IDE에 대한 학습도 좋지만 코딩에 익숙 해 지신 후 IDE를 학습하시거나..
코딩을 하면서 지루하거나 집중이 안될때 짬짬히 학습하시는 방법을 추천드려요
(사실 저도 집중 잘 안될때 IDE의 메뉴얼을 살펴보며 새로운 기능들을 탐험해요...ㅎㅎ)

**Comment by azaraks2** [comment]
숏컷하고 기능 다 숙지해야지 아니면 쓸 이유가 딱히 없네요.
얼른 얼른 개발하려고 쓰는 건데..
