### ISSUE TITLE
javascript로 개발시 nosql DB를 쓰는 이유와 장점이 궁금합니다.

### ISSUE THREAD

**Issue by seongu99** [codingeverybody/codingyahac#156]
자바스크립트로 풀스택 개발하고 있습니다.

그 과정에서 인터넷상의 글들을 참고하며 mongoDB를 이용하고 있습니다.(mongoose로 schema설정해서요.)

schema가 없는 nosql임에도 schema를 설정해서 데이터를 삽입하고 조회하며 제가 느낀 RDB와의 차이점
은 
1)join과 같은 복잡한 쿼리문을 쓰지않아도 된다. 그래서 편하다?라는 것과 
2)schema 설정하면서 type같은 것을 지정해주므로 잘못된 데이터가 들어갈 오류를 어느정도? 줄일 수 있다 정도입니다.

인터넷 자료를 참고하며 개발하면서도 왜 이걸 쓰는지 생각을 곱씹으며 개발하다보니 질문드리게 되었습니다.

조력자님의 의견? 또는 조언 부탁드려요!

**Comment by azaraks2** [comment]
개발자와 DBA 둘을 자르고 개발자 한명을 고용할 수 있는 장점이 있습니다.

**Comment by ghdalsrldi** [comment]
구조가 단순한 데이터를 빠르고 쉽게 처리할 수 있습니다.
하지만 구조가 복잡한 데이터를 저장하기에는 여러가지 불편한 사항들이 존재하며
오히려 복잡도가 증가될 수 있다는 위험부담이 있습니다.
