### ISSUE TITLE
정보보안쪽으로 진로를 정하고 싶은 학생입니다.

### ISSUE THREAD

**Issue by manen0122** [codingeverybody/codingyahac#157]
#정보보안관련 직업을 택하고 싶은 학생입니다.

저는 이제 고등학교 1학년에 올라가고, 고등학교는 일반 인문계보단 성적이 좋은 쪽으로 갑니다. (그렇게 떵떵거리며 살 성적은 아닙니다...)

취미가 여러 곳에 있기도 하고, 컴퓨터를 워낙 사랑했었기에 보통 컴퓨터를 잡으면 평일 2시간 정도의 짬은 낼 수 있었습니다(물론 타이트하고 불규칙적이긴 합니다)

문득 막상 제가 하고싶은 취미들만 했다간 제 진로가 워낙 흔들릴 것 같아서, 코딩야학을 통해 배웠는데, 하면 할수록 저에게 잘 맞는 것 같아서 재밌곤 했습니다.

처음에 계획한 대로, 드리고 싶은 질문은

1) 정보보안을 직업으로 선택한다면, 회사에 보안전문가로 취직하는 것 말고 다른 활동을 통해 정보보안이라는 직업을 살릴 수 있나요?

2) 정보보안에 대해서 관심이 있고, 하루 2시간정도의 시간을 낼 수 있으며, 학생의 신분으로 그 직업을 위해서 노력할 수 있는 게  있을까요?

3) 학생이 참가해 볼 수 있는 정보보안 관련 대회는 어떤 게 있을까요?

올해 3월, 향후 전망이 어떻게 될지는 잘 모르겠지만, 이번 겨울 방학이 끝난다면 저는 기숙사행이 예정되어있습니다.

어떤 일을 해보는 게 좋을까요?

**Comment by egoing** [comment]
#148 #78 관련된 비슷한 질문들이 있어서 알려드려요. 한번 읽어보시면 도움이 될 것 같습니다.
