### ISSUE TITLE
euc-kr과 utf-8의 차이를 알고싶습니다.

### ISSUE THREAD

**Issue by sn49** [codingeverybody/codingyahac#158]
html을 코딩하다보면
meta charset이란 코드가 필요한데요.
euc-kr과 utf-8 둘다 한글이 가능하다는 공통점 때문에 구분이 잘 안됩니다.

정확히 어떤 차이가 있길래
utf-8을 더 많이 쓰는걸까요?

**Comment by azaraks2** [comment]
검색만 해도 나오는 건데..
http://d2.naver.com/helloworld/19187
유니코드 안쓰고, 브라우저 설정에서 utf-8로 보내는 걸 끄는게 보편적인 팁이었던 시절도 있었습니다.

**Comment by ghdalsrldi** [comment]
문자열 인코딩 방식의 차이입니다.

euc-kr은 영어와 한국어를 처리할 수 있습니다. 그 외의 언어(일본어 등)은 깨지게 됩니다.
utf-8은 유니코드로 저장하며 컴퓨터로 볼 수 있는 거희 모든 언어를 깨지지 않고 저장할 수 있어요

자세한 사항은 아래의 링크를 참고해 주세요

https://ko.wikipedia.org/wiki/%EB%AC%B8%EC%9E%90_%EC%9D%B8%EC%BD%94%EB%94%A9

**Comment by nohsundong** [comment]
한글 데이터 중 샾, 힣, 뷁 같은 UTF-8 로는 표현되지만 EUC-KR로는 표현 안되는 값이 포함되면 서버에서 에러가 발생
