### ISSUE TITLE
순수javascript 능력을 키우고 싶습니다

### ISSUE THREAD

**Issue by bernardokang** [codingeverybody/codingyahac#160]
인터넷에서 접하는 많은 js 튜토리얼, 강의들은 react라든지 vue.js라든지 많은 라이브러리를 설명하는데 집중되있는것 같습니다. 저는 순수하게 자바스크립트의 내공을 쌓고 싶은데요(closure, functional programming 등등의 많은 복잡미묘한 부분들) 어떤 공부를 하면 좋을까요?

**Comment by haebin** [comment]
고리타분해 보이는 답변이지만
좋은 책을 정독 하실 것을 권장드립니다.

http://www.yes24.com/24/goods/42806896?scode=032&OzSrank=3

**Comment by happydeveloper** [comment]
아래 사이트의 튜토리얼도 추천드립니다.

[http://javascript.info/](http://javascript.info/)
[JavaScript 생활코딩 강좌](https://opentutorials.org/course/743)

**Comment by CreatiCoding** [comment]
https://github.com/getify/You-Dont-Know-JS

유명한 js 원서 시리즈입니다 저도 이제 읽어보려구요!
