### ISSUE TITLE
잘만들어진 웹의 예시를 알고 싶습니다.

### ISSUE THREAD

**Issue by minlee077** [codingeverybody/codingyahac#161]
여러 검색어를 검색해봐도 잘안나오는데 키워드가 뭘까요.

전반적으로 어떤 구조를 해야 좀 더 정돈되고 안정될지 

잘 운영된 웹의 경우는 어떤 디자인을 취하는지가 궁금해서 질문올립니다.. 

혼자 골격을 구상해서 만들어보니 너무 난잡해보이는것 같아서요..

골격이나 디자인을 좀 보고 아이디어를 얻고 싶네요..

**Comment by smartbos** [comment]
말씀하시는 디자인은 시각적인 디자인을 말씀하시는 건가요?

**Comment by minlee077** [comment]
네 그렇습니다..  그리드나 레이아웃같은것들이 어떻게하면 효과적으로 보일지 궁금해서 그렇습니다.. 
웹디자인 쪽같기도 한데 제가 할수 있는 선에서만 이라도 정리를 해보고 싶어서요!

**Comment by smartbos** [comment]
제 전문 영역이 아니지만 혹시나 도움이 될 수 있을까 답변 남겨봅니다.

[](http://dribble.com) 이라는 사이트는 디자인을 공유하는 사이트인데, 이런 사이트를 둘러보면 도움이 되지 않을까 싶어요. 아래 링크는 이 사이트에서 찾아낸 디자인 중 하나 입니다.
[](https://dribbble.com/shots/978949-Responsive-Wireframe-Templates-GIF)

그리고 [](http://pinterest.com) 이라는 사이트는 이미지를 공유하는 사이트인데, 여기에서도 좋은 디자인을 찾아보실 수 있을 겁니다. 예를 들어, 아래 링크로 들어가면 website design 이라는 키워드로 검색된 이미지 모음들을 보실 수 있습니다.
[](https://www.pinterest.co.kr/search/boards/?q=website%20design)

[](http://themeforest.net) 은 디자인 템플릿을 판매하는 웹사이트인데, 여기서도 인기있거나 많이 팔린 제품을 보시면 도움이 될 것 같아요.

그 외에는 인기있는 웹사이트들도 좋은 참고가 되지 않을까 싶습니다.

**Comment by minlee077** [comment]
와... 정말 감사합니다.. 이런자료를 너무 찾고싶었는데 고맙습니다 :)
