### ISSUE TITLE
아톰 Tab누를시에 자동완성

### ISSUE THREAD

**Issue by hkim29** [codingeverybody/codingyahac#165]
맥에서 사용중입니다. 저는 Tab을 눌러도 자동완성이 되지 않아요. 그래서 일일히 하나하나 적어야 하는 불편함이 있습니다. 
어떻게 설정할수 있나요?

**Comment by ghdalsrldi** [comment]
HTML 태그 자동완성은 emmet 플러그인을 설치해 주시면 될거에요!
