### ISSUE TITLE
업무용 Webapplication 개발사 추천해주실수 있나요?

### ISSUE THREAD

**Issue by gmkjh74** [codingeverybody/codingyahac#166]
회사에서 각종 업무용 프로그램을 Web으로 개발 하려고 하는데 개발 업체 찾기가 힘드네요...
혹시 아시는 업체 추천좀 해주시면 안되나요?

인터넷에서 검색하면 다 홈페이지 어플 개발만 있네요...

가능하면 경기 남부권이면 좋고요...^^

혹 글이 문제 되면 삭제 하겠습니다.

**Comment by haebin** [comment]
구글 및 기타 검색에서 'it 외주'라고 검색해 보시면 업체들이 많이 뜹니다.
요즘에는 관련 스타트업들도 많네요.

참고하세요.
