### ISSUE TITLE
egoing님 css 책 추천좀요

### ISSUE THREAD

**Issue by kimmanyoung** [codingeverybody/codingyahac#167]
CSS에 관련된 책을 사고 싶은데 추천해주세요!

**Comment by haebin** [comment]
이고잉님은 아니지만,
구글 검색: 'css 책 추천'으로 좋은 결과가 많이 나오네요.

https://hashcode.co.kr/questions/2364/css-%EC%B1%85-%EC%B6%94%EC%B2%9C-%EB%B6%80%ED%83%81%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4
