### ISSUE TITLE
div 크기와 다른 border 만들고 싶을 때

### ISSUE THREAD

**Issue by ninking** [codingeverybody/codingyahac#168]
작거나 크게 만들려고 하고싶은데 어떻게 해야할까요?

**Comment by dhchoi82** [comment]
구체적으로 어떤 것을 작거나 크게 하고 싶으신 건지 질문만으로는 알기 어렵습니다. box 모델의 width, height, margin, border, padding 중 어느것을 얘기하시는 것인지 확인하고 구체적으로 얘기하시는 것이 좋을 듯 합니다.
https://opentutorials.org/course/2418/13404
