### ISSUE TITLE
Javascript 익명함수 호출 문법의 가장 바깥쪽 괄호()에 대해..

### ISSUE THREAD

**Issue by dhchoi82** [codingeverybody/codingyahac#169]
안녕하세요?
생활코딩 Javascript 강의 중 유효범위에 대한 부분( https://opentutorials.org/course/743/6495 )을 보다가 질문 드립니다. 위 페이지 3/5 영상을 보면 익명함수를 사용할 때에는 `function(){}()` 전체를 괄호()로 감싸야 한다고 나오는데요. 크롬개발자도구에서 괄호()로 감싸지 않으면 에러가 나는 것을 확인할 수 있었습니다.
![image](https://user-images.githubusercontent.com/13765815/35180342-a55b4f4a-fdf1-11e7-8843-30aa0cb2bf64.png)
하지만 이벤트리스너를 추가할 때에는 괄호로 감싸지 않고, 실행을 위한 마지막부분의 괄호를 뗀 `function(){}` 형태를 사용해야 제대로 동작하는데요...
![image](https://user-images.githubusercontent.com/13765815/35180385-afac0d3a-fdf2-11e7-9c3e-b28aecf42e5f.png)
문법적으로 어떤 차이가 있는지 궁금합니다.

**Comment by azaraks2** [comment]
이름없는 function expression은 있지만 이름없는 function declaration은 없습니다.

**Comment by dhchoi82** [comment]
@azaraks 님, 답변 감사합니다. 근데 잘 이해가 안되네요. 무얼 모르는 건지 몰라 제가 질문을 잘못한 것 같습니다. 일단 활용에는 큰 지장이 없으니 다음에 기회가 있으면 차차 알아가는 게 나을 것 같네요.
