### ISSUE TITLE
벽돌쌓기 정렬 masonry

### ISSUE THREAD

**Issue by dynlee** [codingeverybody/codingyahac#171]
안녕하세요~
홈페이지에서 세로 길이가 다른 이미지를 예쁘게 정렬하고 싶어서 찾아보다가
벽돌쌓기 정렬이란 걸 알게 되었는데요. masonry라는 jquery를 알게 되어서 해보았는데
어떻게 정렬까지는 됐는데 responsive가 특정 브라우저가 아니면 적용이 되질 않네요.
제가 아직 jquery(javasacript)지식이 부족해서 그냥 붙여넣기로 하려고 해서 그렇긴 한데
responsive까지 가능한 다른 방법이나 jquery소스를 제공하는 곳이 있을까요?

참고 했던 사이트

> https://masonry.desandro.com/

 중에 가로 폭은 같고 세로 길이가 다를 때 정렬을 하고 싶어서

> https://masonry.desandro.com/layout.html#imagesloaded

 으로 해보았습니다.

**Comment by haebin** [comment]
예시 사이트 코드를 그대로 하셔도 안된다는 것인가요?
https://masonry.desandro.com/v2/docs/intro.html#getting_started
https://masonry.desandro.com/v2/demos/basic-single-column.html

통상 jQuery(및 기타 컴포넌트)를 쓸때는 여러 브라우저 관련 이슈를 해결해 주기 때문에 사용합니다.
위 모듈도 기본적으로는 브라우저에 상관 없이 동작해야하는 것이 맞을것 같습니다.

**Comment by dynlee** [comment]
감사합니다! 말씀하신대로 테스트로 한페이지에서 다시 해봤을 때는 되는 것을 확인했는데요, 그 방법말고 
b.php에서 사용할 js, css파일을 a.php파일에서 부르고 a.php 컨텐츠로 b.php를 부를 경우 제대로 작동되지 않는 걸까요?

**Comment by haebin** [comment]
순수 HTML, JS, CSS로 상기가 정상적으로 동작한다면 php는 해당 요소들을 적절히 출력하면 똑같이 동작해야겠죠? 아마 php코드가 출력한 요소들에 오류가 있을것 같습니다. HTML 소스코드 보기에서 예시와 어떻게 디른지 디버깅해보세요.
