### ISSUE TITLE
Django 시작과 공부법

### ISSUE THREAD

**Issue by Evan-JH-Kim** [codingeverybody/codingyahac#172]
안녕하세요, 방금 WEB1 HTML과 WEB2 CSS 강좌를 수료했습니다.
이제 웹 프레임워크를 공부해서 본격적인 웹 페이지를 만들어보고 싶은데,
바로 Django 공부에 들어가면 될까요? (Python은 어느 정도 할 줄 압니다.)
아니면 JavaScript와 react, vue 등의 라이브러리를 다루어 보는 것이 좋을까요?

**Comment by ghdalsrldi** [comment]
Python 경험이 있으시다면
Django를 먼저 공부하시는 것을 추천 드립니다.
React나 Vue는 좋은 기술이지만 이와 같은 기술 없이도 웹사이트를 만들 수 있습니다.

Django를 이용해서 웹 사이트를 만들어 보신 다음 React나 Vue와 같은 기술을 공부하시는 방법을 추천 드려요!
