### ISSUE TITLE
github 페이지에 대해 질문있습니다!

### ISSUE THREAD

**Issue by younga94** [codingeverybody/codingyahac#173]
![20180122_211212](https://user-images.githubusercontent.com/35579642/35220383-1999ce90-ff6e-11e7-82e4-2646b5490631.jpg)
다른컴퓨터로 할때는 이상이 없는데 제 컴퓨터로 하면 매번  크롬이나 엣지로 해도 매번 이렇개 떠요 ㅜ

**Comment by davidkwak** [comment]
CSS같은게 로드되지 않은것 같은데 윈도우 시라면 ctrl + shift  + r 로 강한 새로고침 한번 해보시고, 안되면 브라우저 캐시와 쿠키를 싹 지우신후에 다시 시도해보세요

**Comment by younga94** [comment]
그래도 안되네요ㅜㅜ 도대체 왜이러는지 알수가없어요 ㅠ.ㅠ

**Comment by leapa** [comment]
개발자 도구의 네트워크 탭에 CSS 가 로딩되는지 확인하세요. 로딩이 않된다면...
저도 모르겠네요..
