### ISSUE TITLE
깃허브 웹사이트

### ISSUE THREAD

**Issue by soucestory** [codingeverybody/codingyahac#174]
깃허브에서 new repository에서 Repository name이름을 ex2라고 입력해서 html코드를 입력했는데 세팅에 들어가서 받은 주소를  들어가니 ex2라고만 써져있어서 어떻게 해결해야될지 모르겟어요
html코드는 깃허브에 올리기 전에 웹페이지에 ctrl+o눌러서 연결해서 확인까지 다 했는데 왜 Repository name이름이 계속 나오는지 모르겠어요
정리해서 말씀드리면 제가 쓴 코드가 안나오고 Repository name이름이 나오는지 모르겠어요

**Comment by azaraks2** [comment]
커밋 푸시 하셨어요?

**Comment by soucestory** [comment]
??어떻게 하는줄 모르겟어요

**Comment by dhchoi82** [comment]
https://github.com/soucestory/ex2?files=1
기본으로 띄울 파일 이름은 index.html 로 바꾸세요. (대소문자도 구분되니 주의하세요.)

**Comment by soucestory** [comment]
https://github.com/soucestory/ex2/index.html
https://github.com/soucestory/ex2?files/index.html
https://github.com/soucestory/ex2?files=1/index.html
https://github.com/soucestory/ex2?files=1.index.html
다 해봤는데도 나오지 않아요

**Comment by dhchoi82** [comment]
https://www.inmotionhosting.com/support/website/htaccess/htaccess-change-index-page
기본으로 불러오는 웹페이지 파일의 이름은 서버 설정에 따라 다릅니다.

**Comment by dhchoi82** [comment]
저장된 home.html 파일의 이름을 index.html로 수정하시고, 깃허브 페이지 설정 후 기본 url은 https://soucestory.github.io/ex2/ 일 것으로 생각합니다만...
https://opentutorials.org/course/3084/18891
위 강의를 참고하세요.

**Comment by dhchoi82** [comment]
https://github.com/soucestory/ex2?files=1
이 주소는 깃허브 페이지 접속 URL이 아닌, 올려두신 ex2 저장소 URL입니다.

**Comment by azaraks2** [comment]
https://soucestory.github.io/web/home.html
잘 보입니다.

https://help.github.com/categories/github-pages-basics/
이걸 먼저 다 읽어보길 권합니다..

파일이름에 되도록이면 공백이나 멀티바이트 문자는 사용하지 않는 것이 좋습니다.
