### ISSUE TITLE
phpWarning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /home/cabox/workspace/writing/login.php on line 5 에러

### ISSUE THREAD

**Issue by noamboy2006** [codingeverybody/codingyahac#175]
```  <?php
    $conn = mysqli_connect("localhost", "root", '비밀번호가 무엇일까요?');
    mysqli_select_db($conn, "lol");
    $result = mysqli_query($conn, 'SELECT * FROM login where id='.$_GET["id"]);
    $row=mysqli_fetch_assoc($result);
?>
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8"/>
        <?php
        if($_GET["id"] == $row["id"] && $_GET["password"]=$row["password"]){
        echo("<a href='realindex.php'>로그인 성공<a/>");  
        }else{
        echo("아이디 또는 패스워드 잘못 입력");
        }
        echo ($row['id']);
        ?>
      </head>
      <body> 
      </body>
    </html>
```
지금 php로 로그인 기능을 만들려고 하는데요.
Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /home/cabox/workspace/writing/login.php on line 5이런 에러가 뜹니다. stack에도 질문했는데 mysqli_error로 에러가 어디서 났는지 알아보라고 해서 보았더니 $result가 false더군요. 이것을 어떻게 해결해야할까요?

**Comment by dhchoi82** [comment]
PHP 공식문서를 찾아보니 mysqli_query가 false를 반환하는 건 해당 쿼리문 실행이 실패한 경우라고 합니다.
http://php.net/manual/en/mysqli.query.php#refsect1-mysqli.query-returnvalues
위 코드에서는 GET으로 넘어온 id 값이 없으면 정상적인 SQL이 완성되지 않는 것 같은데, 혹시 id를 넣더라도 문제가 계속된다면 DB, Table, user 이름, password, DB권한이 맞게 설정되었는지 확인해보는게 좋을 것 같습니다.
.
덧붙여서... 위와 같은 SQL 생성은 SQL Injection 공격에 취약하니 다른 방식으로 추후에 개선하시길 권장합니다.

**Comment by noamboy2006** [comment]
에러 해결했습니다. 
```$result = mysqli_query($conn,'SELECT * FROM login where id=\''.$_GET["id"].'\'');
```
이렇게 고치니 수정 되네요.

**Comment by azaraks2** [comment]
오 쿼리를 잘못 치셨는 줄은 몰랐네요! 찾으셔서 다행입니다. 😄
