### ISSUE TITLE
[C언어, 윈도우] 쉘을 직접 만들어야 하는데요, 개념이 너무 헷갈립니다. ㅠㅠ

### ISSUE THREAD

**Issue by leochoo** [codingeverybody/codingyahac#176]
뭔가 쉘에 관해서 쉽게 설명해놓은 자료가 없어서 힘듭니다...

지금 C언어 수업에서 쉘을 직접 만들어서, 다른 쉘로 이동, 즉 쉘 프롬프트를 바꿔주는 과제를 하는 중인데요,
배운 범위를 초과하는 과제라 자료조사를 하는데 조금 애들 먹고 있습니다.
저는 윈도우를 써서, 윈도우에서 쉘을 만드는 법을 알고 싶은데 거의 대부분의 자료는 '리눅스 쉘'  '리눅스에서 쉘 만들기'이라고 나와있는데... 이걸 참고해야 하는 건가요...??

도대체 리눅스 쉘과 윈도우 쉘은 뭐가 다른건가요?  윈도우에서도 쉘은 리눅스로 돌아가는 건가요?
쉘 스크립트는 쉘과는 또 다른 걸 지칭하는 건가요?
쉘프롬프트를 바꾸려면 쉘을 처음부터 다시 만들어야하는 것 같은데... 어느 자료나 개념을 참고해야 좋을 지 모르겠습니다. https://brennan.io/2015/01/16/write-a-shell-in-c/ 이 자료를 봐도 쉘프롬프트를 바꾸는 부분도 안나와있고 글이 딱히 깔끔하지도 않아서 너무 헷갈리기만 하네요 ㅠㅠ

**Comment by azaraks2** [comment]
shell이 뭔지 잘 모르시는 것 같은데.. 정확히 뭘 만드시려는 건가요?

**Comment by leochoo** [comment]
네 수업에서 쉘에대한 개념을 배운적이 없어서 혼자 찾아봐서 이해하는 중인데 아직 완벽히 이해가 가질 않아요.
유저가 입력하는 인라인 커맨드를 기록해주는 쉘을 만드는 게 목표입니다. 기본 쉘 위에서 동작하면서 유저인풋을 기록하는 동시에 기본 쉘에게 넘겨서 커맨드가 유저인풋대로 작동해야하구요, 쉘 프롬프트는  C:¥user>> 이런 기본형태에서 recsh>> 의 형태로 바뀌어야합니다.

현재까지 생각하는 솔루션은,
페런트프로세스에서 execv로 차일드프로세스로 recsh를 실행하고 recsh 안에서 recsh>>를 출력하는 것인데... 그럼 resch은 프로그램인데 그걸 왜 쉘이라고 지칭하는 건지 모르겠습니다.

그래서 위에 개념들이 너무 헷갈리네요.

**Comment by azaraks2** [comment]
찾아가서 모든 요구사항을 제대로 확인하고 그것들만 만족시키세요. 
필요한지 아닌지 모르는 요구사항을 마음대로 상상하는 것은 좋지 않습니다.

윈도기준으로 cmd는 console이지 shell 아닙니다.

**Comment by leochoo** [comment]
네. 이고잉님 말대로 뭐가 모르는지 모르는 상태에서 도움이 필요해서 질문을 드린거라 질문이 애매할 수 밖에 없어 힘드네요.

**Comment by dhchoi82** [comment]
CMD 콘솔 응용프로그램은 표준입출력만으로도 충분히 구현할 수 있습니다만... 쉘의 의미가 애매한 것 같네요.

**Comment by leochoo** [comment]
@dhchoi82  그러게요 문제자체에서도 쉘이라고만 언급하고 구체적으로 나오진 않아서...
 구체적인 질문 새 포스트에서 올릴게요
