### ISSUE TITLE
이고잉님께 질문 합니다~!~!

### ISSUE THREAD

**Issue by jungyun2916** [codingeverybody/codingyahac#177]
저번 WEB1때 처럼 WEB2-PHP도 따로 신청을 해야한다거나 특정 시간 동안 방송을 봐야하나요?

**Comment by egoing** [comment]
아니요~ PHP 수업은 야학과 같은 캠페인으로 진행되지 않습니다. 그냥 편하실 때 공부하시는 방식으로 진행하시면 됩니다.

**Comment by jungyun2916** [comment]
네 감사합니다~!
