### ISSUE TITLE
[C언어] execv 가 실행이 생각대로 안되는 이유를 모르겠습니다.

### ISSUE THREAD

**Issue by leochoo** [codingeverybody/codingyahac#178]
custom shell 을 만드는 과제를 하고 있습니다.
main을 실행해서 resch>> 를 보여주는 쉘 안으로 들어간 다음에, 
유저인풋을 커맨드 입력으로 인식해 execv로 실행하려 합니다. (사실은 유저인풋을 input.log라는 파일에 출력하는 동시에 커맨드입력까지 실행하는 게 목적입니다).

그런데 20행 execv가 생각대로 작동하질 않습니다.

fork()해서 child까지 진입하는 것 까지 성공했구요, 
21행에서 확인한 결과 path와 user_input 값이  제대로 입력되고 있는 것을 확인했습니다.

그런데 커맨드를 실행하려고 pwd 같은 인풋을 입력해도, 아무런 반응이 없이 다시 인풋을 넣으라고 반복 될 뿐입니다.
왜 이러는 걸까요? 제가 execv 활용법을 오해한 걸까요?
3시간정도 웹을 헤멨는데도 이해할 수 있는 자료를 찾기가 힘드네요... 잘못된 예제도 너무 많고.

도움 부탁드립니다.

```

1. #include <time.h>
2. #include <stdio.h>
3. #include <unistd.h>
4. #include <sys/wait.h>
5. #include <string.h>
6. #include <stdlib.h>
7. 
8. void execute(char *user_input)
9. {
10.     printf("Entered execute successfully\n");
11.     pid_t pid;
12.     int state_loc;
13.     if( (pid = fork()) == -1){
14.       printf("fork failed\n");
15.       exit(1);
16.     }
17.     else if(pid == 0){
18.       printf("In Child\n");
19.       printf("User input is %s\n", user_input);
20.       char *argv[] = {"커맨드를 실행하고 싶은 경로", user_input};
21.       printf("argv[0]: %s\n",argv[0]);
22.       execv(argv[0],argv);
23.     }
24.     else{
25.       wait(&state_loc);
26.       printf("the child process terminated with %d\n", state_loc);
27.     }
28. }
29. 
30. int main ()
31. {
32.   char user_input[1024];
33.   while(1)
34.   {
35.             //the_file = argv[1];
36.             printf("recsh>> ");
37.             scanf("%s", user_input);
38.             if(strcmp(user_input, "exit") == 0){
39.               printf("Exiting\n");
40.               exit(0);
41.             }
42.             printf("Okay. Execute command: \n");
43.             execute(user_input);
44.   }
45.   return 0;
46. }

```

**Comment by leochoo** [comment]
@dhchoi82 주소로 넣고 실행하니 이런저런 포인터 에러가 뜨는 데 해결할 시간이 없어서 일단 저렇게 했습니다.. 지금보니 execv 의 두번째 parameter 에 argv[]가 어레이 형식이 아니라 string 으로 들어가서 안되나 싶네요...

**Comment by leochoo** [comment]
```
char* user_input = ls la
char* separator = " ";
            char* argv[64];
            int argc = 0;
            char* tmp;
            argv[argc] = strtok_r(user_input, separator, &tmp);
            while( argv[argc] != NULL){
              argv[argc+1] = strtok_r(NULL, separator, &tmp);
              argc++;
            }

      // char *argv[] = {"/home/t16561sc/public_html/SysProg", user_input};
      // printf("argv[0]: %s\n",argv[0]);
      printf("argv[1]:%s\n", argv[1]);
char* separator = " ";
            char* argv[64];
            int argc = 0;
            char* tmp;
            argv[argc] = strtok_r(user_input, separator, &tmp);
            while( argv[argc] != NULL){
              argv[argc+1] = strtok_r(NULL, separator, &tmp);
              argc++;
            }

   
      printf("argv[1]:%s\n", argv[1]);
```
이 결과값이 
`argv[1]:(null)`
로 출력이 되는데 왜 일까요?? 
char *argv[] 의 인덱스 하나당 단어를 토큰시켜서 넣었다고 생각했는데 안들어가있네요...

**Comment by dhchoi82** [comment]
아무래도 제가 같이 고민하기엔 바쁘신 것 같네요.
https://youtu.be/KkE5FKd0xGo
이 유투브 강의가 도움이 될 것 같아 주소 적어둡니다.
https://www.youtube.com/playlist?list=PL52K_8WQO5oXIATx2vcTvqwxXxoGxxsIz
이건 전체 재생목록입니다.
.
제가 보기엔 저 강의 안에 필요한 기술적인 부분은 거의 다 설명되어 있을 것 같습니다.

**Comment by leochoo** [comment]
@dhchoi82 좋은 피드백 주셔서 너무나 감사합니다. 
프로그램이 완벽하진 않지만 어찌저찌 돌아가게 되었습니다.
지금까지 제가 해결한 점 업데이트 드리고 마무리 지을게요.

네 , scanf 가 저부분은 문제가 없지만, scanf가 space를 맞닥뜨리면 인풋을 잘라버리는 문제가 발생하는 걸 알았습니다. 그래서 밑과 같은 신택스로 극복했습니다.
`scanf("%[^\n]", user_input);`

프로그램안에서 커맨드를 실행하는 법은 execvp 를 사용했는데요, 사실 아직 이 점은 이해가 안가는 점이 많습니다만, 먼저 execvp 함수 안에 두번째 매개변수인 char** argv를 만들었습니다. 어레이 마지막에 NULL 값이 들어가는 게 포인트더라구요. 그리고 나서 execvp(argv[0], argv) 를 실행하니 커맨드명령이 실행이 되었습니다.  
```
char* separator = " ";
            char* argv[64];
            int argc = 0;
            char* tmp;
            argv[argc] = strtok_r(user_input, separator, &tmp);
            while( argv[argc] != NULL){
              argc+=1;
              argv[argc] = strtok_r(NULL, separator, &tmp);
              // printf("argc: %d\n",argc);
            }
            argv[argc] = NULL; // null termination array
  execvp(argv[0],argv);
```

참을성있게 친절하게 답변해주셔서 감사합니다.

**Comment by azaraks2** [comment]
유튜브 링크는 별 관련이 없는 것 같습니다.
exec이 argument array가 몇개의 원소를 지녔는지 알 수 없으므로 마지막 요소가 null pointer여야 합니다.
최종 소스는 어떻게 되었나요?

**Comment by leochoo** [comment]
@dhchoi82 @azaraks2  

최종 소스 올립니다. 맨 위에 #include는 아마 다는 필요 없을 텐데 개발하던 도중에 남은 걸 그냥 놔뒀습니다. 사실은 없어도 되는 게 몇 개 있을거에요. 도움 주셔서 감사드립니다.

- scanf
75행에서 scanf("%[^\n]", user_input);   를 이용해  \n 을 제외한 모든 character을 받았습니다.
그리고 85행에서 while( getchar() != '\n'); 를 이용해버퍼를 클리어 해줬습니다. 이게 없으면 코드가 execvp이후로 알아서 인풋을 받아버려서 scanf에 자동으로 인풋이 입력되어 버리더군요.  

- exec 
이 문제는 62행에 execvp(argv[0], argv) 라는 코드로 해결했는데요, 아직 잘 이해가 안갑니다.
execvp(파일이름, char** argv)  - 첫번째 매개변수로 파일이름을 기대하는데요, 실제 예제에서는 커맨드 "ls" 같은 걸 넣어라구요. 근데 커맨드는 유저가 입력한 가장 첫번째 커맨드인데, 이게 왜 첫번째 '파일이름' 으로
 인식이 되어서 매개변수에 들어가는 지 이해가 안갑니다. (참조: http://forum.falinux.com/zbxe/?mid=C_LIB&page=3&document_srl=408566)

- 

```

1. #include <time.h>
2. #include <stdio.h>
3. #include <unistd.h>
4. #include <sys/wait.h>
5. #include <string.h>
6. #include <stdlib.h>
7. #include  <sys/types.h>
8. #include <wordexp.h>
9. 
10. /*
11. Creating custom shell command that records and executes user input command line.
12. 
13. 유저인풋을 tmp.log에 기록하고 커맨드를 실행해 주는 커스텀 쉘 만들기
14.
15. */
16. 
17. // function concat        source: https://goo.gl/HJ6w5c
18. char* concat(const char *s1, const char *s2)
19. {
20.     char *result = malloc(strlen(s1)+strlen(s2)+1);//+1 for the null-terminator
21.     //in real code you would check for errors in malloc here
22.     strcpy(result, s1);
23.     strcat(result, s2);
24.     return result;
25. }
26. 
27. void execute(char *user_input)
28. {
29.     pid_t pid;
30.     int state_loc;
31.     if( (pid = fork()) == -1){
32.       printf("fork failed\n");
33.       exit(1);
34.     }
35.     else if(pid == 0){
36.             FILE *f;
37.             f = fopen("tmp.log", "a+"); // Append, but create if not there.
38.             if (f == NULL) { printf("Something is wrong");}
39. 
40.             struct tm *p;
41.             struct tm buf;
42.             char timestring[100];
43.             time_t ltime = time(NULL);
44.             if (NULL != (p=localtime_r(&ltime, &buf))){
45.               strftime(timestring, sizeof(timestring),"** %c: ", p);
46.               char* result = concat(user_input,"\n");
47.               fprintf(f, "%s", concat(timestring,result));
48.             }
49.             fclose(f);
50. 
51.             char* separator = " ";
52.             char* argv[64];
53.             int argc = 0;
54.             char* tmp;
55.             argv[argc] = strtok_r(user_input, separator, &tmp);
56.             while( argv[argc] != NULL){
57.               argc+=1;
58.               argv[argc] = strtok_r(NULL, separator, &tmp);
59.             }
60.             argv[argc] = NULL; // null termination array
61. 
62.       execvp(argv[0],argv); // I'm still quite unsure about this part. I'll study further
63.     }
64.     else{
65.       wait(&state_loc);
66.     }
67. }
68. 
69. int main ()
70. {
71.   while(1)
72.   {
73.             char user_input[1024];
74.             printf("recsh>> ");
75.             scanf("%[^\n]", user_input);
76.             if(strcmp(user_input, "exit") == 0){
77.               printf("Exiting\n");
78.               exit(0);
79.               break;
80.             }
81.             execute(user_input);
82.             while( getchar() != '\n');
83.   }
84.   return 0;
85. }

```

**Comment by azaraks2** [comment]
바로 저 코드를 제출하실 것이라고는 생각하지 않지만 혹시나 하는 마음에 잠깐 리뷰 해보겠습니다.

indent가 들쭉날쭉한 것은 좋지 않습니다. 같은 depth면 같은 indent depth를 갖는 것이 코드를 파악하기 편합니다.
L73 입력이 1023자를 초과할 일이 없는지 확인하는 것이 좋습니다. 더 긴 입력이 가능한 스펙이라면 초과할 경우 수행 안한다고 하거나 동적으로 할당하도록 하는 것이 좋습니다.
L78 exit(0)은 L81에 else를 추가하면 break로 충분해 필요하지 않습니다. 더 나은 코드 흐름을 위해 없는 것이 나아 보입니다.
L82 버퍼 더 쓸 일이 없다면 scanf 이후에 바로 비우는 것이 좋습니다. 그리고 보통 EOF가 올 경우도 생각합니다.
L38 파일 포인터 NULL check 하는 것은 좋은데, NULL이면 fprintf를 하지 않아야 합니다.
L20 malloc한 메모리를 free하고 있지 않습니다. 그리고 동적 할당을 위해 다른 곳의 코드도 쓰셨는데 다음과 같이 하는 것에 비해 어떤 장점이 있어 보이지 않습니다.
```c
fprintf(f, "%s %s \n", timestring, user_input);
```
L52 입력이 1000자면 argument가 100개일 수도 있습니다. argv[64]로 충분한지 확인하는 것이 좋습니다.
L60 while 안에서 수행된 마지막 strtok_r이 이미 NULL을 대입했으므로 불필요합니다.
L62 첫번째 인수는 이미지를 교체할 바이너리이고, 두번째 인수는 그 바이너리에 넘겨줄 argv[]입니다. 자기 파일 이름이 실행하는데 필요하지 않다면 두번째 인수의 첫 요소는 다른 단어나 문장이어도 실행에 관련이 없습니다.

각 줄에 번호를 붙이는 것 보다 \`\`\`로 감싼채 그냥 붙이거나 gist로 공유하는게 더 좋습니다.
> \`\`\`c
> for(int i=0;i<m;i++)
> {
>   // stuff
> }
> \`\`\`

하면
```c
for(int i=0;i<m;i++)
{
  // stuff
}
```
로 하이라이트되어 읽기 좋습니다.
깃헙 리포지터리를 생성하고 리포지터리에 커밋 푸시를 하시면 라인 코멘트를 받을 수도 있습니다.
교수님께 말씀 드리고 같은 과제 하시는 분들 몇분 모여서 서로 코드 리뷰 하시면 좋습니다. (학생은 깃헙 유료 혜택을 무료로 받을 수 있어 비공개 리포지터리에서 서로 코드 리뷰 할 수도 있습니다.)

**Comment by leochoo** [comment]
@azaraks 님, 아주 많은 공부가 되었습니다. 진짜 고수들만 아시는 노하우 너무 감사드려요!!!
저번에는 마감시간이 다 되어 저 코드를 제출했습니다만, 이해가 안가는 점이 많아 다시 공부를 하러 돌아왔습니다. 답변을 읽고 다시 공부를 하여 답변을 거의다 이해했는데요, 아무리 해도 납득이 안가는 부분이 있어 질문 드립니다.

```
execvp(argv[0],argv);
``` 
-> 이 부분이 이해는 가지만, 납득이 안갑니다. 공식 documentation에도 "첫번째 매개변수에는 실행할 파일의 이름이 들어가야한다" 또는 PATH 변수의 경로에 있는 파일명이 들어가야 한다고 나와있습니다.. (http://man7.org/linux/man-pages/man3/exec.3.html)
그런데 제 프로그램 execvp(argv[0],argv);  에서 보듯 첫번째 매개 변수는 유저가 입력한 명령어 잖습니까?
예를들어 pwd 라던가 ls 라던가.  
어째서 파일 이름이 들어가야 하는 곳에 명령어가 들어가는 걸까요.???
설마 우리가 흔히 **"명령어" 라고 부르는 게 사실은 실행가능한 파일이라는 말인가요**?? 
이런건 아무도 알려주지 않았고 찾아도 아무것도 나오질 않아 답을 모르겠습니다.

그리고... 이렇게 알기 힘든 걸 다들 어떻게 배워서 아는 걸까요..?  당장 구글에 execvp parameter를 검색해서
 공식 documentation 을 봐도 첫번째에 명령어가 들어간다는 아무리 찾아봐도 없었는데...

친구의 코드를 보고나서야 여기에 명령어가 들어간다는 사실을 알고 한국어 블로그를 딱 하나 찾았는데요, 도대체 어떤 자료를 봐야지 종합적인 설명을 받을 수 있는걸까요? 컴퓨터 공부를 할 때 이런 점이 가장 답답하고 화가납니다 :(

끝까지 도움 주셔서 진심으로 감사드립니다.

**Comment by azaraks** [comment]
일단 exec은 명령어를 인수로 받지 않습니다. 파일을 받는 것이 맞습니다.

- 내부 명령어는 쉘에 포함되어 있어 별도의 파일이 존재하지 않습니다.
- 외부 명령어는 별도의 파일로 존재해 그 파일이 없으면 실행할 수 없습니다.

예를 들어 cd는 사용하신 방법대로 실행시킬 수가 없습니다. 쉘에 명령을 전달하거나 직접 기능을 구현해야 합니다. 내부 명령어에 대한 자세한 사항은 internal commands / built-in commands로 검색하시면 알 수 있습니다. 왜 내부 명령어, 외부 명령어가 따로 있는지 잘 생각해보시면 좋습니다.
어느 명령이 내부 명령어인지 알 필요가 있는 경우 bash에서는 type으로 확인합니다. 도스/윈도는 그냥 전부 외웁니다.

**Comment by leochoo** [comment]
@azaraks 

말씀해주신 내용은 잘 이해했습니다.
그렇다면 첫번째 parameter인 argv[0] 가 지칭하는 건 도대체 무엇일까요?
프로그램 이름을 지칭한다고 배웠는 데 도대체 어떤 프로그램을 지칭하는 걸까요?
설마 현재 돌아가고 있는 shell을 프로그램으로 인식하는 건가요?

**Comment by azaraks** [comment]
```c
int main ( int argc, char **argv )
{
  printf("%s", argv[0]);
  return 0;
}
```
를 해보시고 생각해보셨으면 합니다.

**Comment by chimd715** [comment]
다른 분들이 답을 하지 않아서 답을 드립니다. 공식 documentation에도 "첫번째 매개변수에는 실행할 파일의 이름이 들어가야한다" 또는 PATH 변수의 경로에 있는 파일명이 들어가야 한다고 나와있습니다..  라고 하신 부분에 대한 답변입니다. 9달이나 지난 답변이지만 도움이 됐으면 하네요. 유닉스/리눅스 기반에서 모든 명령어라 하는 것은 파일입니다. cd /bin 을 해서 bin 폴더 안의 내용을 보면 무슨 말인지 알 것 같네요
유닉스/리눅스 기반의 모든 것은 파일입니다. 소켓, i/o들, 우리가 아는 파일, 혹은 directory 모두 파일로 이루어져있습니다.
명령어로 실행하는 것은 이 파일들을 이미 시스템 환경변수에 있는 것을 부르는 것이라 이해하면 편할 것 같습니다.
제 설명은 이해하기 편하게 간추리고 자세히 설명 안 한 것이 있기에 틀린 부분이 있을 가능성도 있습니다. 그러므로 자세한 부분을 알고 싶다면 리눅스의 파일 시스템을 확인하시면 될 것입니다.
