### ISSUE TITLE
제가 objective-c와 centos를 이용해서 채팅프로그램을 만들려고합니다 조언즘 해주세요ㅠㅠ

### ISSUE THREAD

**Issue by xkawjd121000** [codingeverybody/codingyahac#179]
제목처럼 만들고 싶어서 프로그램을 만들어 보고 싶은데 어디서 물어볼데가 없어서 이렇게 질문을 합니다. 그런데 다른 프로그래밍 언어끼리 소켓통신이나 아니면 서버 통신을 해서  채팅앱을 만드려고 하는데 아이폰 기반입니다.  검색을 해도 잘 안나옵니다. 스위프트로(오브젝트 c)앱을 만들고 centos에서는 c언어 아니면 오브젝트c로해서 채팅 프로그렘을 만들려고 합니다.  조언 부탁드립니다.ㅠㅠ

**Comment by haebin** [comment]
Firebase 입문하시죠.
https://firebase.google.com/docs/samples/
예시 코드들입니다.
실제 채팅 프로젝트도 있고,
iOS 클라이언트 예제는 Instragram 유사류인 FriendlyPix 참고하시면 될 것 같습니다.
