### ISSUE TITLE
이숙번님 : java, R, Hadoop프로그램 관련 진로문의

### ISSUE THREAD

**Issue by SeonwooJeong** [codingeverybody/codingyahac#18]
안녕하세요? 

직종변경으로 취업교육을 수강하고있는 정선우라고합니다.

제 현재상황을 간략히 소개하겠습니다.
기존전공 및 경력 : 전자물리학(복수전공 : 기계시스템공학) / 맡은 업무 : 중소기업 기계설계 1년6개월
현재 : 커넥티드카를 위한 IoT 전문가교육 수강중(국비지원) /교육과목 java, javaScript, SQL, R, Hadoop

희망하는 직종 : 자동차산업 관련 S/W분야. 커넥티드카 V2X...

제가 직업에 관련해서 조사한 내용은 
1. 자율주행분야(ADAS)  필요역량 : 영상처리로 인해서 C++,CUDA, 임베디드시스템...
2. 커넥티드카(스마트카), 차량정보 클라우드  필요역량 : java, golang, tensorFlow...

하지만 취업사이트의 채용정보에서는 현재 대부분 경력직 또는 석사,박사 채용하고있습니다.

java, R, Hadoop을 통해서는 SI업체에서 많이 선호한다고 알고 있지만 
저는 자동차산업관련 S/W로 취직을 희망합니다. 

질문1
SI업체 또는 타분야 S/W개발자로 경력을 쌓고 이직하는게 좋을까요?
아니면 신입을 뽑는데를 계속 찾아서 들어가는게 좋을까요?

질문2
기업에서 원하는 프로그래밍 언어의 수준이 궁금합니다.

질문3
영어성적은 얼마나 필요한가요?
현재 OPIc은 IM1 토익600점

질문4
정보처리기사 자격증은 취득이 좋은가요?
아니면 프로그래밍언어나 알고리즘을 더 공부하는게 좋을까요?

바쁜시간에 읽어주셔서 감사합니다.

**Comment by blackdew** [comment]
안녕하세요. 코딩야학 조력자 이숙번입니다. 

주신 질문들이 기술적인 질문이 아니고, 구직에 대한 내용이네요. 
제가 답변드려도 그것은 지극히 개인적이고 주관적인 의견으로 참고사항일 뿐입니다. 
결국 주신 질문에 대한 답은 장선우님께서 직접 만들어가야 하는 것이라는 생각이 드네요. 

답변 1. 
각 개인에 따라 다르고, 가려는 SI업체가 어떤 업체인가에 따라 다르고, 또 그 가게되는 업체에서 함께 일할 사람들이 어떤 사람들인가에 따라 답이 달라질 것 같습니다. 본인의 실력을 향상시키는 데에 어느 쪽이 더 도움이 될지 충분히 고민하시는 게 좋을 것 같고요. 무엇보다 둘 중 어느 쪽을 택하더라도 그 선택과 상관없이 본인의 실력을 향상시킬 수 있는 방식을 마련하는 것이 더욱 중요한 일이라는 생각이 듭니다. 

답변 2. 
기업에서는 프로그래밍 언어의 수준은 의외로 높지 않습니다. 
다만, 과제가 주어졌을 때에 현재 자신이 가진 지식과 사용가능한 자원을 가지고 얼마나 지혜롭게 과제를 해결해 나갈 수 있는지를 중요하게 생각한다고 생각합니다. 
다만, 어느 언어든 상관없이 하나쯤은 능숙하게 다룰 수 있으면 좋겠지요. 

답변 3. 
영어성적은 회사마다 다를 것 같습니다만, 국내의 회사 보통의 경우라면 기술문서를 큰 무리없이 읽고 지식을 습득할 수 있는 수준이면 충분할 거라 생각합니다. 

답변 4. 
둘 중에 하나를 선택하는 것이라면 후자가 중요합니다.

도움이 되면 좋겠네요. :)
