### ISSUE TITLE
[Github Pages] 깃허브 페이지 브랜치 질문

### ISSUE THREAD

**Issue by jj-pa** [codingeverybody/codingyahac#181]
깃헙 페이지에서 master 브랜치만 실제 적용이 되는 건가요?
다른 브랜치를 적용할 수는 없나요..?

**Comment by azaraks** [comment]
master나 gh-pages 중 하나를 선택하게 되어있습니다.
preview를 봐가면서 편집하다가 완성한 뒤에 적용되었으면 좋겠다는 생각이시면 로컬에 지킬을 설치하시는 방안을 추천드립니다.

**Comment by jj-pa** [comment]
로컬 환경에서 지킬을 설치하였는데, 테마가 적용이 안되네요...
혹시 해결 방법 아시나요?
Ubuntu on Windows 10 으로 설치했습니다.
