### ISSUE TITLE
웹호스팅

### ISSUE THREAD

**Issue by noamboy2006** [codingeverybody/codingyahac#182]
저는 2기때 알게된 codeanywhere서비스를 사용하여 웹호스팅을 받고 있었습니다. 그런데 새로운 서비스가 필요해서 여기에 질문해 봅니다.
반드시 '꼭' 필요한 조건
```php,mysql 호스팅```
```꺼지지 않음: 깃헙처럼 언제나 접속이 가능한 것입니다.코드에니웨어는 코드에니웨어 사이트에 제 아이디로 로그인을 해 콘테이너를 켜놓을 때만 접속이 돼고 다른때는 되지 않습니다.```
```무료```
있으면 좋지만 없어도 상관 없는 조건
```웹에디터 기능:코드에니웨어는 웹에디터 형식입니다. 제가 컴퓨터에서 프로그래밍 한 페이지를 호스팅하는곳에 올리는 형식이 아니라 사이트에서 프로그래밍이 가능합니다.이런 기능도 있으면 무척 좋겠습니다.(없어도 돼요^^)```

**Comment by egoing** [comment]
아쉽게도 말씀하신 기능을 갖춘 서비스는 대체로 유료랍니다. 제가 아는 범위에서는요. ^^;

2018-02-04 20:57 GMT+09:00 noamboy2006 <notifications@github.com>:

**Comment by azaraks** [comment]
돈을 내고 쓰지 않으면 서비스를 보장받을 수 없습니다.
당장은 쓸 수 있을지 몰라도 서비스가 중단되거나 내껄 뻇어가도 아무 말도 못하는건 기본입니다.
