### ISSUE TITLE
[Jekyll] 로컬 환경에서 테마 적용 문제

### ISSUE THREAD

**Issue by jj-pa** [codingeverybody/codingyahac#183]
깃헙 페이지에서는 인터넷으로 받은 테마가 잘 적용되는데, 로컬 환경에서는 테마만 적용이 안되네요.
페이지가 올라오는 것 까지는 확인이 됩니다.
혹시 해결 방법 아시는 분 계신가요...?

**Comment by devyohan** [comment]
_config.yml 에 baseurl 부분을 "" 또는 "/" 등으로 수정해보시면서 테스트 해보셔요. 확실한건 구글 크롬 등에 있는 개발자 도구에서 css, js, 이미지 파일들의 경로 (예: http://localhost:4000/asset/js/asdf.js ) 가 어떻게 되어 있느냐에 따라 설정을 바꿔주면 잘 작동할겁니다.
