### ISSUE TITLE
웹으로 엑셀 연동하기

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#184]
웹의 자바스크립트의 기능의 이용해서 

엑셀 파일을 열때 아이디와 비번을 입력 받아서 

웹상으로 아이디와 비번이 맞아서 로그인이 되면 엑셀 파일이 열리도록 하고 싶습니다.

이것이 이론적으로 실질적으로 가능한지 궁금합니다.

프로세스 

엑셀파일을 연다 - 엑셀에 VBA를 통해서 웹 으로 넘어간다 - 웹으로 넘어가며 사이트상에 아이디와 비번을 입력하는 창이 뜬다 - 아이디와 비번이 일치하면 - 엑셀 파일이 열린다.

**Comment by azaraks** [comment]
<i>이론적으로 실질적으로</i> 가능하다는건 무슨 말인지 모르겠습니다.
두 말이 상반됩니다.
