### ISSUE TITLE
도메인을 구했는데 연결이 안되요

### ISSUE THREAD

**Issue by kkkssa** [codingeverybody/codingyahac#185]
https://www.youtube.com/watch?v=DqKGoixwI74&t=426s
이 영상보고 그대로 따라했는데 연결이 안되요
https://soucestory.github.io/web/home.html
seongwonpc.cf
이 아이디가 아니라 다른건데 사정이 있어서 이 아이디로 올립니다.
인터넷 찾아보니깐 기다려보면 된다고 하던데 freedom에 입력하는 ip주소에 오류가 있다고 하는데 그대로 붙여서 넣어놨거든요 
왜 안될까요?
지금 20시간정도 지났어요

**Comment by dhchoi82** [comment]
http://seongwonpc.cf/web/home.html
여기는 잘 열리는데, 여기가 맞나요? 다른 문제가 있나요?

**Comment by kkkssa** [comment]
뒤에 home.html 없이는 안되나요?
아니면 없애는방법이 있나요?

2018. 2. 15. 오전 3:07에 "Choi, Donghui" <notifications@github.com>님이 작성:

http://seongwonpc.cf/web/home.html
여기는 잘 열리는데, 여기가 맞나요? 다른 문제가 있나요?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codingeverybody/codingyahac/issues/185#issuecomment-365694435>,
or mute the thread

**Comment by dhchoi82** [comment]
Github Pages에서는 기본으로 열리는 파일이 README.md, index.html 등으로 고정되어 있습니다. 개인서버에서는 서버 설정에서 기본 파일을 바꿀 수 있습니다.

**Comment by kkkssa** [comment]
깃허브에 올려져있는 이상 바꿀수가 없다는거죠?

2018. 2. 15. 오전 3:11에 "Choi, Donghui" <notifications@github.com>님이 작성:

**Comment by dhchoi82** [comment]
깃허브 서버 설정을 바꾸는 게 가능한지는 모르겠네요.
(제가 아는 한) home.html 이라는 파일 이름을 index.html로 바꾸지 않는 한 주소창에서는 계속 보일 거고요,

꼭 home.html 이라는 이름을 유지하면서 이동하게 하고 싶다면
index.html 파일을 따로 만들어서
redirection을 설정해야 합니다.
https://developer.mozilla.org/ko/docs/Web/HTTP/Redirections#리다이렉션을_명시하는_대체_방법

**Comment by azaraks** [comment]
> 깃허브에 올려져있는 이상 바꿀수가 없다는거죠?
네
