### ISSUE TITLE
개인 포트폴리오 웹페이지 만들기

### ISSUE THREAD

**Issue by Evan-JH-Kim** [codingeverybody/codingyahac#186]
타임라인과 연대기 형식으로 저의 개인 포트폴리오 웹 페이지를 만드려 하는데,
이 경우에는 웹사이트를 어떻게 구성하면 될까요?
또는 추천할 만한 참고용 사이트가 있을까요?
감사합니다.

**Comment by Nullgom** [comment]
https://www.hongkiat.com/blog/timeline-in-web-design/
