### ISSUE TITLE
로그인 회원가입 페이지 코드

### ISSUE THREAD

**Issue by chung0906** [codingeverybody/codingyahac#187]
회원가입과 로그인이 가능한 웹페이지를 만들고 싶습니다.

간단하게 회원가입 과 로그인 기능만 구현되면 됩니다.

코드를 어떻게 작성해야 하는지 부탁드립니다.

또는 참고할수 있는 생활코딩 강좌를 부탁드립니다.

**Comment by dhchoi82** [comment]
기본적인 아이디어는 아래의 강의를 참고하시면 될 듯 합니다만...
https://opentutorials.org/course/1688/9372
보안상 문제가 있습니다.
https://opentutorials.org/course/1688/9471
생활코딩에서 검색해보면 여러 강의가 나오는데 어느것이 적절할지는 스스로 판단하셔야 할 것 같고요...
https://www.google.co.kr/search?safe=off&rlz=1C1NHXL_koKR717KR717&ei=exWKWtvhJoOJ8wWUrr3oCA&q=%EB%A1%9C%EA%B7%B8%EC%9D%B8+site%3Ahttps%3A%2F%2Fopentutorials.org&oq=%EB%A1%9C%EA%B7%B8%EC%9D%B8+site%3Ahttps%3A%2F%2Fopentutorials.org&gs_l=psy-ab.3...0.0.0.15337.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.mzOn5qYgLSo
생활코딩을 벗어나서 `sign in sign up (사용언어)`로 검색해도 많은 결과를 볼 수 있으니 참고하시고요...
https://www.google.co.kr/search?q=sign+in+sign+up+php&rlz=1C1NHXL_koKR717KR717&oq=sign+in+sign+up+php&aqs=chrome..69i57.623j0j7&sourceid=chrome&ie=UTF-8

OAuth를 이용하는 방법도 참고하시길 권합니다.
https://opentutorials.org/course/2473/16571

**Comment by azaraks** [comment]
정말로 회원가입과 로그인만 할 수 있다면 회원 가입의 의미가 없을 겁니다.
무엇을 하려는지 명확히 하시는 것이 좋습니다.

**Comment by dhchoi82** [comment]
코드와는 별개로, 회원가입을 받는 것은 회원 개인의 정보를 수집, 보관하는 작업이 필요하게 되니
[개인정보보호법](http://www.law.go.kr/lsSc.do?query=개인정보%20보호법)을 준수할 의무가 있습니다.
