### ISSUE TITLE
 자바스크립트로 어떠한 물체가 다른 물체에 닿을 시에 이벤트를 일어나게 할 수 있나요?

### ISSUE THREAD

**Issue by noamboy2006** [codingeverybody/codingyahac#189]
자바스크립트로 어떠한 물체가 다른 물체에 닿을 시에 이벤트를 일어나게 할 수 있나요?

**Comment by davidkwak** [comment]
일단 드는 생각은 HTML  게임같은거 만들때 쓰는  collision detection을 쓰면 구현 가능할것 같습니다.
각 오브젝트의 좌표랑 크기를 구해서 겹치는지 여부를 확인해서 처리해도 될것 같고요 .
(기존에 구현된 라이브러리를 쓰시는게 좀더 용이할것 같긴합니다)

참고 : https://www.youtube.com/watch?v=_Ov-ghI_frc
