### ISSUE TITLE
html : 웹페이지 안에 c언어 코드를 보여주고 싶어요

### ISSUE THREAD

**Issue by seongwonpc** [codingeverybody/codingyahac#19]
html을 이용하여 웹페이지를 제작중인데 c언어로 만든 코드를 웹페이지에 올리고 싶습니다. 
프리뷰를 누르면 나오는 모양처럼요
사진처럼 코드가 무언가에 둘러싸이게 하고 싶어요

![screenshot_2017-12-25-01-01-29](https://user-images.githubusercontent.com/35033598/34485677-2d438972-f00f-11e7-80e7-6baa83a2680c.png)

```
#include<stdio.h>
int main(void)
{
printf("hello world\n")
return 0;
}
```

**Comment by egoing** [comment]
코드를 문법에 따라서 하이라이트해서 보여주고 싶으신건가요?

우선 검색어를 추천해드릴께요. 
syntax highlight javascript library 

혹시 자바스크립트가 학습이 안되어 있으시다면 web2 javascript 수업까지 공부하시면 쉽게 라이브러리를 이용해서 해결할 수 있을 것 같습니다. 

검색해보시고 해결되지 않으시면 이슈를 다시 열어주시고 후속 질문을 해주셔요~
