### ISSUE TITLE
PHP의 file_get_contents 관련 궁금한 점

### ISSUE THREAD

**Issue by hangyun2** [codingeverybody/codingyahac#190]
PHP의 file_get_contents를 사용해 PHP 코드를 작동시켜보니 작동이 되지않고 HTML의 주석으로 처리되었습니다...
인터넷에 검색해보니 PHP 코드가 HTML의 주석으로 처리되면 서버에서 PHP 엔진이 작동하지 않아서라고 들었는데 아무리봐도 PHP에 문제는 아닌 것 같다는 생각을 하게 되었습니다.
그렇다가 문득 "혹시, file_get_contents가 PHP의 코드를 작동시키지 못하는 것이 아닐까?"라는 생각에 도달하게 되었습니다.

**혹시 PHP의 file_get_contents는 PHP의 코드를 사용할 수 없는 건가요?**

(제가 많이 초보자라 많이 답답하시더라도 이해해주셨으면 좋겠습니다... ㅠㅠ)

**Comment by azaraks** [comment]
file_get_contents는 잠시 잊으시고, php 강의를 처음부터 천천히 들어보시기를 권합니다.

**Comment by dhchoi82** [comment]
http://php.net/manual/kr/function.file-get-contents.php
file_get_contents 함수의 반환값은 string이니 문자열이 반환될 뿐, 입력된 PHP 파일의 코드가 실행되지는 않습니다.
```php
<?php echo "<?php echo 'Hello world'; ?>"; ?>
```
위 구문의 실행 결과를 생각해보시는 게 어떨까 합니다.

**Comment by hangyun2** [comment]
@azaraks 답변 감사합니다! 다시한번 PHP를 처음부터 다잡아봐야겠네요!
@dhchoi82 이해하기 쉬운 예시로 설명과 답변해주셔서 감사합니다! 당연한 것을 잘못된 생각으로 오히려 퇴행하는 길로 가고 있었네요... 다시 복습하면서 무심코 지나친 부분을 다시 살펴봐야겠네요!

다시 한 번, 답변해주신 두 분의 전문가분들께 감사드립니다!
