### ISSUE TITLE
페이지를 찾을 수 없습니다

### ISSUE THREAD

**Issue by Hanhye** [codingeverybody/codingyahac#192]
이번에 html 과정을 듣고 간단하게 싸이트를 만들어봤는데, 
계속해서 
The site configured at this address does not contain the requested file. 

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
라는 문구만 반복해서 뜹니다. 혹시 코딩 과정에서 실수가 있어서 안되는건지, 아니면 무언가 다른 문제가
있는것인지 알아내기가 너무 어렵네요. 도움 주신다면 정말 감사하겠습니다.

제 사이트는 https://github.com/Hanhye/food 입니다.

**Comment by Fhwang0926** [comment]
`https://github.com/Hanhye/food`

먼저 확인 부탁드립니다

URL  을 명확하게  작성하지 않아서 그런 것 같습니다

http://127.0.0.1/
http://localhost/

형식인지 확인 바랍니다

만약 test.html 이라면

http://localhost/test.html 이 됩니다

윈도우라면 hosts 파일설정을 해야 한다는 것은 참고입니다

good luck
