### ISSUE TITLE
Linux Tomcat에서 여러개의 홈페이지 (Webapplication)운영 방법

### ISSUE THREAD

**Issue by gmkjh74** [codingeverybody/codingyahac#193]
Linux, Apache, Tomcat 사용 경험이 없습니다.
Windows + IIS운영 경험이 조금 있는데요..

Linux에서 Tomcat (필요에 따라서는 Apache 추가)에 여러개의 도메인을 운영하려 합니다.
제가 조사한 방법중 어떤게 효율적인지 장/단점을 정확히 몰라서요..

정확한 개념이 없어 질문 자체가 너무 엉성할수 있습니다.

하나의 물리적 Linux 서버에 여러개의 도메인 서비스를 운영 하려고 합니다.
도메인은 a.com, b.com, c.com 이렇게 사용 하려고 가정 하고, Tomcat를 사용한다는 가정 입니다.. (Apache를 써야 하는 케이스도 있네요...)

Q1. NIC가 1개 있어서 가상 IP 3개(공인IP)를 세팅 하고  DNS서버에 도메인별 공인 아이피를 등록 하면 된다고 하는데, 그럼 Tomcat 어디에  도메인별 IP 셋팅을 해야 하는지요?

Q2. 어떤 분은 앞단에 아파치 서버를 두고  아파치 서버에서 a.com, b.com, c.com으로 포워딩(?)하면 된다고 하는데...이건 어떻게 하는지요? 그리고 이 용어가 포워딩은 아닌것 같은데 정확한 명칭은 무엇인지요?

Q3. 보통 root 계정으로 Apache를 설치하고 a,b,c 각각의 계정으로  tomcat을 설치후에 서비스를 올린다고 하는데 맞는지요? (Q2처럼요...)

질문이 맞는지 모르겠는데요...최종 목적은 한개의 물리적 서버에 여러개의 도메인을 운영할수 있는 방법들과 각각의 장단점이 궁금합니다.

혹시 위 개념을 잡기  위한 인강이나 책 추천도 해주시면 감사 하겠습니다.

**Comment by progh2** [comment]
Q1, Q2, Q3
IP 또는 도메인에 기반한 사이트 연결 설정은 apache2의 site-enabled 디렉토리 안에 있는 VirtualHost 설정에서 지정할 수 있습니다. apache2 가상호스트(VirtualHost) 설정을 찾아보셔야 할 것 같습니다. 
그리고 그 VirtualHost 설정 안에 apache2의 jk 모듈을 써서 Tomcat 연동을 해주면 됩니다.
Tomcat도 하나만 설치해서 운영해도 될 것 같습니다.(물론 각각 포트 번호를 달리해서 할 수도 있긴 합니다만) 대신 어플리케이션 별로 server.xml 에서 각기 포트 및 연결 webapps 디렉토리를 설정하셔서
할 수 있습니다. 

일단 아파치2 서버의 다양한 도메인에 대응하는 가상호스트 설정법을 찾아보셔서 구축한 후
그 다음에 톰캣을 jk 모듈 같은 것을 써서 연동하게 하는 식으로 작업을 해보시면 어떨까 합니다.

**Comment by progh2** [comment]
참고해보시면 좋을 URL 남겨드립니다. 

- https://m.blog.naver.com/PostView.nhn?blogId=ameeam&logNo=220936435078&proxyReferer=https%3A%2F%2Fwww.google.co.th%2F
- http://blog.naver.com/PostView.nhn?blogId=blue_0227&logNo=130094766610&redirect=Dlog&widgetTypeCall=true
- https://www.manualfactory.net/10167
- https://www.google.co.th/search?biw=1251&bih=702&ei=vP9TW4-vE8HHrQHuoq_oBQ&q=apace2+멀티도메인+톰캣&oq=apace2+멀티도메인+톰캣&gs_l=psy-ab.3...14140.15125.0.15271.7.7.0.0.0.0.95.525.7.7.0....0...1c.1j4.64.psy-ab..0.0.0....0.ozmiMAFTlX0
- http://queserasera.tistory.com/11
- http://thereclub.tistory.com/11
