### ISSUE TITLE
aws에 관한 질문입니다

### ISSUE THREAD

**Issue by kkkssa** [codingeverybody/codingyahac#194]
aws에 관한 수업을 듣고 질문올립니다.
사용법도 알고 서버를 비용을 내고 대여한다는 것은 알겠는데요 
개인 포트폴리오를 웹페이지로 작성하려고하는데요   
이름.com    이런식으로요 
그런데 여기 깃허브에 올리면 github가 url에 표시가되어 보기 좀 그러고, free domain hosting을 검색해서 나오는 무료 호스팅사이트도 깃허브라는 이름이 빠지긴 하지만 제가 올린 소스코드의 제목 같은게 나와서요
비용이 당연히 들어간다고 생각하고 있는데 이름.com이런식으로 하고싶어요 
비용은 얼마나 드는지/ 어떻게 하는지 알려주시면 감사하겠습니다.

**Comment by azaraks** [comment]
> aws에 관한 수업을 듣고 질문올립니다.

AWS 수업을 들은 것과 질문 내용은 무관해 보입니다. 무슨 관련이 있는지 알 수 없는데, 있다면 더 설명해보시는 것이 좋겠습니다.

> 사용법도 알고 서버를 비용을 내고 대여한다는 것은 알겠는데요

그렇게 말하시면 모르시는 겁니다.

> 개인 포트폴리오를 웹페이지로 작성하려고하는데요
이름.com 이런식으로요

도메인과 호스팅은 별도입니다. 도메인만 사서 깃헙에 연결시킬 수도 있습니다.

> 그런데 여기 깃허브에 올리면 github가 url에 표시가되어 보기 좀 그러고

포트폴리오 url에 github 들어간 채로 많은 분들이 그냥 쓰십니다.

> free domain hosting을 검색해서 나오는 무료 호스팅사이트도 깃허브라는 이름이 빠지긴 하지만 제가 올린 소스코드의 제목 같은게 나와서요

무슨 말인지 모르겠습니다.

어떤 포트 폴리오를 어떻게 만드셨는지믄 모르겠으나, https://opentutorials.org/course/3276
위 링크의 강의를 모두 보고 완전히 이해한 뒤에 시도하시는 것이 좋을 것 같습니다.

**Comment by progh2** [comment]
깃허브에 페이지 기능으로 포트폴리오 사이트를
만들고 여기에 도메인 연결을 하고 싶다는 
이야기시죠?

아래 링크의 글들을 참고하시면 도움이 될껍니다. ^^
https://www.google.co.kr/search?q=%EA%B9%83%ED%97%88%EB%B8%8C+%EB%8F%84%EB%A9%94%EC%9D%B8+%EC%97%B0%EA%B2%B0&rlz=1CDGOYI_enKR761KR761&oq=%EA%B9%83%ED%97%88%EB%B8%8C+%EB%8F%84%EB%A9%94%EC%9D%B8+%EC%97%B0%EA%B2%B0&aqs=chrome..69i57.4800j0j9&hl=ko&sourceid=chrome-mobile&ie=UTF-8

깃허브 계정으로 운영 시에는 도메인 비용 외에는
특별한 비용이 들지는 않습니다.
