### ISSUE TITLE
자바스크립트 공부중에 이해가 되질 않는게 있어서  질문해봅니다!!

### ISSUE THREAD

**Issue by Led001** [codingeverybody/codingyahac#199]
안녕하세요!! 저는 생활코딩 보면서 열심히 공부하고 있습니다  

이렇게 하고 싶었던 공부를 하게 해주셔서 너무 감사합니다.

공부하는 도중에 너무 개념이 안잡히고 이해가 안가는게 너무 많습니다 ㅠ.ㅠ 

아래 코드를 보면 node.appendchild(textnode)부분에서  매개변수로 creatTextNode 값이 담겨진 

textnode 변수를 를 왜 집어넣었는지 이해가 잘 가지 않습니다. 

그리고 createtextnode() 와 innerHTML 다른점이 궁금합니다 

솔직히 createtextnode() 이 메소드의 용도가 이해가 되질 않습니다 ㅠ.ㅠ

마지막으로 한가지 더 document.getElementById("myList").appendChild(node); 이 코드 를 

document.getElementByTagName("ul") 로 바꿔봤는데요 왜 적용이 안되는지 궁금합니다. 

byTagName이 안되는 이유가 무엇인가요?

프로그래밍을 도전을 하는데  이해가  안되고 개념이 잡히지 않는부분이 많아서 

답답해서 이렇게 질문을 해봅니다  저에겐 프로그래밍이 너무 어렵네요 ㅠ.ㅠ

--- 코드 내용 입니다  -----------------
```
<!DOCTYPE html>
<html>
<body>

<ul id="myList">
  <li>Coffee</li>
  <li>Tea</li>
</ul>

<p>Click the button to append an item to the end of the list.</p>

<button onclick="myFunction()">Try it</button>

<script>
function myFunction() {
    var node = document.createElement("LI");
    var textnode = document.createTextNode("Water");
    node.appendChild(textnode);
    document.getElementById("myList").appendChild(node);
}
</script>

<p><strong>Note:</strong><br>First create an LI node,<br> then create a Text node,<br> then append the Text node to the LI node.<br>Finally append the LI node to the list.</p>

</body>
</html>
```

**Comment by hojin-kr** [comment]
createTextNode 메소드는 이름 그대로 새로운 텍스트 노드를 생성하는 메소드입니다. 
그리고 appendChild 메소드는 해당 노드 자식 노드 리스트의 맨 마지막에 추가하는 기능을 합니다. 
그리고 질문하신 내용에 대해서 위 코드에서 Note: 에 설명이 나와있길래 한글로 인용해봅니다.

1. 먼저 li 노드를 생성합니다. (createElement메소드로 생성해서 node에 저장합니다)
2. 그리고 텍스트 노드를 생성합니다. (createTextNode메소드로 Warter를 생성해서 textnode에 저장합니다)
3. li 노드가 생성되어 있는 node에 텍스트 노드 textnode를 추가합니다.
4. 마지막으로 node를 리스트에 추가합니다.  

getElementByTagName메소드로 동작하지 않는 이유는 알아봤는데, 이 메소드의 리턴값이 NodeList가 반환되기 때문에 그렇다고 하는군요. 사용할 수 있게 하는 방법은 있는데 심플하게 id를 사용하는 방법을 추천한다고 합니다. 이부분은 링크를 걸어두겠습니다. 
https://stackoverflow.com/questions/8407487/appendchild-not-working

**Comment by Led001** [comment]
우와 답변 너무 감사합니다! 많은 도움됐습니다! 감사합니다!
