### ISSUE TITLE
공부방향에 대한 질문...

### ISSUE THREAD

**Issue by Mordiumaco** [codingeverybody/codingyahac#204]
안녕하세요.  
요리를 하다가 뒤늦게 웹개발자가 되기로 마음을 먹은 그리고 
구글과 같은 곳에서 일하고  싶은 27세 학생(?) 입니다. 
 
몇 년간요리를 하면서 지내오다가  재능은 고사하고 그저 노동자로서의 가치 밖에  발휘를 못하는 현실을
바라보며, 이대로는 안되겠다 마음을 먹고 진로를 탐색하던 중.. 
저에게 그나마 친숙한 컴퓨터와 관련된 직업을 가져보기로 했습니다. 
단순히 아 할게없으니까 프로그래밍이나 해야지가 아니라.. 

잿빛인생이 아닌 제 안의 날개를 펼치기 위한 탈출구로서 이 길을 택하게 되었습니다.
쉬운 길이 아니라는 걸 알고  
어쩌면 어린 나이에 프로그래밍을 배우는 친구들보다 늦은 나이이고 배움이 더딜 수도 있지만..
천천히  천천히 앞으로 나아가는 중입니다. 

현재 대전에서 국비지원을 받으며 웹프로그래밍을 공부 중에 있고, 
JAVA 수업 중 , 현재 Collection Framework 이라는 곳을 공부 진행 중에 있습니다. 

이제 2개월차에 들어가지만, 현재 만들어진 사이트들을 보면서 내가 과연 만들 수 있을까 라는 생각이 들더군요.. 
다른 친구들에 비해 부족하기도 하구요.. 

서론(넋두리)이 길어진 듯합니다..

많이 부족한 초보자 입니다... 어떠한 공부를 어떠한 순서대로 하면 좋은지 알고 싶습니다. 
java를 공부하는데 jdbc를 연결하는 것조차도 허덕이고 있습니다.. 
(egoing 강사님께서 제공해주신 java강의 다 본 상태입니다)

솔직히 말해서 어떤식으로 프로그래밍 공부를 진행해야할지를 모르겠더군요.. 
어떠한 식으로 공부를 해야할지 자세히 부탁드립니다... 
정말 잘하고 싶어요.
훌륭한 강의들이 외국사이트에 많은 것 같지만 언어의 장벽에서 많이 막히는 편입니다.. 

그리고 국비 지원을 받고 다니는 늦깍이 개발자들도 훌륭한 개발자가 될 수 있을까요..

[요약]

1.  웹 백엔드 초보 개발자가 해야할 공부 및 공부 순서. 
(웹사이트 및 책 추천해주시면 감사하겠습니다.)
[프로그래머스와 생활코딩은 자주 들려 보고 있습니다.]

2. 늦깍이 개발자도 훌륭한 개발자가 될 수 있을까요..

p.s
잘 부탁드립니다...
그리고 부족한 면이 많지만 염치불구하고.. 
저의 멘토가 되어주실 분을 찾습니다.
희망하는 곳은 저 높은 곳에 있지만 그 희망하는 곳에 도달하기 위해 
그 길이 험난하더라고 저에게 그 방향을 알려주실 분을 찾습니다.
열심히 노력하겠습니다.

**Comment by egoing** [comment]
안녕하세요. 제가 쓴 글을 하나 옮겨와봅니다.

경험하고 계신 고통과 불안은 모든 사람들에게 공통적으로 있는 것들이랍니다.
힘내시고, 나중에 뒤 돌아보면 좋았던 시간으로 기억 될 것이 틀림없습니다.

-------------------------

제목 : 적정수준의 공부

오늘 안타까운 메일을 한통 받았습니다. 프로그래밍을 오랫동안 공부했고 알고리즘, 데이터스트럭쳐, 컴퓨터 구조와 같은 것을 정말 열심히
공부했는데 프로그래밍을 할 줄 모른다고요. 프로그래밍적 사고를 못하기 때문이라며 이 공부를 그만두는 것을 심각하게 고민하고 있다고
하셨습니다. 이런 고민에 대해서 저도 정답을 알고 있는 것은 아닙니다. 저 역시도 제가 프로그래밍을 잘한다고 생각하지는 않거든요.
조심스럽게 저의 생각을 적어봅니다.

공부라는 것은 적정수준이 중요한 것 같습니다. 언어에 비유를 해볼께요. 아이들은 언어를 배울 때 힘들어하지 않습니다. 왜냐하면 아이들은
사고 체계 자체가 아직은 고차원적이지 않기 때문에 언어를 복잡한 형태로 사용할 필요가 없거든요. 그래서 명사나 동사와 같은 단어들로
말을 하다가 어느시점에서 명사와 동사를 조합해서 좀 더 많은 의미들을 만들어내기 시작합니다. 이런 과정을 반복하면서 좀 더 복잡한
언어의 체계를 자연스럽게 받아들입니다.

우리가 영어를 배울 때를 생각해봐도 좋을 것 같습니다. 문장을 사용하는 이유는 무엇일까요? 단어들을 조합해서 훨씬 더 많은 의미를 만들
수 있기 때문이겠죠. 명사 10개 동사 10개를 주어+동사의 구조에 따라서 조합하면 100개의 의미를 만들 수 있습니다. 이것을
주어+동사+목적어의 틀에 따라서 조합한다면 20개의 단어로 1000개의 의미를 만들 수 있습니다. 주어+동사+목적어+전치사+명사의
구조를 사용한다면 만들어 낼 수 있는 의미의 가능성은 가히 폭발적이라고 할 수 있습니다. 우리가 1000개의 단어를 조합해서
주어+동사+목적어의 구조로 말을 한다면 우리가 하는 대부분의 말들이 인류 역사상 누구도 해본적이 없는 말일 가능성이 큼니다. 즉
주어+동사+목적어로도 우리는 충분히 많은 의미를 만들어 낼 수 있습니다. 하지만, 제가 학교 때는 이 기본적인 도구의 잠재력을 충분히
사용하기도 전에 관계대명사, 동명사와 같은 것을 배우죠. 이것은 우리 머리를 너무 복잡하게 하는 것 같습니다. 즉 간단한 표현을 할
때도 너무 많은 결합방법들이 떠오르기 때문에 아무것도 할 수 없게 됩니다.

프로그래밍도 사정은 비슷한 것 같아요. 데이터스트럭쳐, 알고리즘, 디자인 패턴... 이런 것들은 정말 소중한 선배 개발자들의
성취입니다. 그런데 이러한 학문적인 성취들은 아래와 같은 상황들을 해결하기 위해서 고안된 것들이 아닙니다.

100건 정도 되는 데이터의 처리
20줄 짜리 규모의 코드
혼자서하는 개발
한달짜리 프로젝트
​
롯데월드타워 같은 초고층 빌딩을 짓는 것과 1층짜리 단독주택을 짓는 것은 본질적으로는 같은 일입니다. 하지만 현실적으로는 완전히 다른
공학적인 고려가 들어가게 됩니다. 규모가 달라지면 그 규모를 지탱하기 위해서 막대한 체계들이 필요해집니다. 1층 건물도 지어본 적이
없는데 초고층 빌딩을 지을 수는 없는 것이겠죠. 동시에 1층 건물을 짓는데 초고층 건물을 짓는데 필요한 체계들을 사용하는 것은 과한
것이겠죠.

특히나 좋은 코드에 대한 이해가 높아질수록 자신이 만든 코드에 대한 만족도는 떨어지게 됩니다. 그래서 더 많은 공부를 하지만 자기
코드에 대한 만족도는 오히려 더 떨어지는 악순환에 빠지게 되죠. 이것이 반복되면 아는 것은 많은데 할 수 있는 것은 별로 없다는
자괴감을 갖게 됩니다. 적당한 자괴감은 자기 발전의 약이 됩니다. 하지만 과한 자괴감은 자신감을 괴사시킵니다.

이런 이유로 제가 주장하는 것은 적정수준의 공부입니다. 장기적으로는 초고층 건물도 지어낼 수 있는 역량을 키워야 합니다. 동시에
단기적으로는 1층 건물을 짓는 것부터 시작하는 것이 어떨까 싶습니다. 제가 생각하는 구체적인 공부 방법으로 글을 마무리하겠습니다.

프로그램을 만드는데 필요한 최소한의 도구를 익힌다. (문자, 숫자, 변수, 비교, 조건문, 반복문, 함수)
최소한의 도구로 다양한 문제를 해결해 본다.
가지고 있는 도구로 문제를 해결하는 것이 점점 어려운 일이 되었을 때 선배 개발자들의 성취를 찾아본다. 이 또한 최소한으로.
2번과 3번 반복

원문 : https://opentutorials.org/course/1189/10015

------------------------------------

그리고 아래 영상도 한번 보시면 좋겠습니다.
https://opentutorials.org/course/3084/18896
https://opentutorials.org/course/3084/18897
https://opentutorials.org/course/3084/18898

**Comment by Mordiumaco** [comment]
감사합니다. 
해주시는 말씀에 대해서 좀더 생각해보겠습니다. 기초를 다시 되돌아볼 필요가 많이 느껴지네요..
포기하지 않고 나아가서 훌륭한 개발자가 되도록 노력하겠습니다.
해주신 조언에 진심으로 감사드립니다.
그리고 더불어 지금 제공해주시는 egoing님의 흘륭한 강의에도 정말 감사드립니다.
