### ISSUE TITLE
HTML bitnami wamp stack 7.2.7-1  Go to application 오류

### ISSUE THREAD

**Issue by rlaantjd641** [codingeverybody/codingyahac#208]
bitnami wamp stack 7.2.7-1에서 Go to application을 클릭했는데 오류가 뜨네요 어떻게 해야하나요??

![image](https://user-images.githubusercontent.com/37789177/43038864-7f69b38a-8d5c-11e8-9c25-2ecd6feee74e.png)

![image](https://user-images.githubusercontent.com/37789177/43038843-1a4e0ee2-8d5c-11e8-8009-7b0b735e31e8.png)

**Comment by progh2** [comment]
음.. 브라우져가 링크를 못열어주는 것으로 추측됩니다.
그냥 크롬 등 브라우져 열어서 http://localhost:80 으로 들어가시면 될 것 같습니다. ^^;

**Comment by rlaantjd641** [comment]
넵 감사합니다
