### ISSUE TITLE
리눅스에서 gcc -o를통한 c언어 컴파일오류

### ISSUE THREAD

**Issue by nooblunux** [codingeverybody/codingyahac#213]
vim으로 c언어를 작성한후 그 파일을 gcc로 컴파일하려고하는데 다음과같은 오류가뜹니다.

hello.c:2:19: fatal error: iostream: 그런 파일이나 디렉터리가 없습니다
compilation terminated.

include<iostream>부분에서 오류가 난것같은데
using namespace std; 도 적었는데
무엇이 문제일까요?

**Comment by fermat39** [comment]
안녕하세요

컴파일러를 잘못 사용하신 것 같습니다

소스코드는 C++ 같습니다

g++ 컴파일러를 사용해보세요

리눅스에 따라 패키지명이 좀 다릅니다
-----Original Message-----

**Comment by nooblunux** [comment]
flsnrtmdptj gksrmfdldksTjwutj...
g++dlfksmsrp dLTeksmsrjf cjdmadkfdkTspdy rkatkgkqslek^^

**Comment by SDRLurker** [comment]
리눅스에서 한글이 안써져서...
g++이라는게 있다는걸 처음알았네요 감사합니다^^
