### ISSUE TITLE
코딩야학 프로젝트에 관해서 질문합니다.

### ISSUE THREAD

**Issue by songpang** [codingeverybody/codingyahac#214]
안녕하세요, 이번 코딩야학을 신청하고 싶은.. 꿈꾸는 학생입니다..

이번 코딩야학 프로젝트 부문에 신청을 하고 싶은데
혹시 제가 진행 하고있는 프로젝트를 신청해도 되나요 ?
제가 하고있는 프로젝트를 진행하면서 모르는 부분이 많아서 이에따른 도움을 위해서 신청하려고해요.
공모전에 내기 위한 프로젝트인데
어떠한 제약사항이 있을까 궁금하여 질문을 남깁니다 ㅠㅠ
프로젝트 주제는 블록체인 + 안드로이드 ( + WEB ( 코딩야학을 통한 )) 입니다.

**Comment by egoing2** [comment]
안녕하세요. 코딩야학 프로젝트 섹션에는 누구나 참여할 수 있습니다.
다만, 조력자들은 보다 많은 분들에게 도움을 주기 위해서
질문 당 10분 정도를 사용해서 도움을 드리는 것을 기본적인 기조로 하고 있습니다.
이 점에 대해서는 미리 양해를 부탁드립니다. :)

2018년 7월 25일 (수) 오후 5:14, songpang <notifications@github.com>님이 작성:

**Comment by egoing** [comment]
궁금하신 점이 또 생기시면 이슈을 열어주세요 :)

**Comment by songpang** [comment]
정보의 투명성을 위해 블록체인을 이용하는 프로젝트를 진행하려고 합니다.
저희 프로젝트의 주된내용은 이렇습니다.
기존 폐쇄적인 기부시스템의 비신뢰성을 탈피하기 위해 블록체인을 도입하여 신뢰성 향상 도모가 
주 목적이며 이를 안드로이드 어플리케이션으로 구현하여 그안에서 블록체인이 동작하는 식(?)으로 
개발을 진행하려고 합니다. 이를 위해 간단한 안드로이드의 XML제작은 스케치해놓은 상태이고 
기초적인 solidity랑 geth, truffle 공부를 진행해왔는데요.
이제 개발 초기의 방향성을 어떻게 잡아야 할 지 모르겠어서 질문드립니다. 
일단 공부하다가 궁금한점을 여쭤보자면

1. 오픈제플린의 ERC20이라는 프로토콜(?)을 수정하여 코인을 개발하는 것인지?
    (오픈제플린 폴더를 뜯어보니 ERC20 폴더 내에 다수의 sol파일이 있더라구요)

2. 간단한 metacoin 예제를 찾아보니 되게 코드가 간단하고 짧던데 이렇게 구현해도 되는지 ?
