### ISSUE TITLE
help java download in ubuntu

### ISSUE THREAD

**Issue by nooblunux** [codingeverybody/codingyahac#215]
sudo apt-get install oracle-jdk7-installer;

--->패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다       
상태 정보를 읽는 중입니다... 완료
oracle-jdk7-installer 패키지를 사용할 수 없습니다.  하지만 다른 패키지가 참조하고 있습니다.
해당 패키지가 누락되었거나 지워졌다는 뜻입니다. 아니면 또 다른 곳에서
패키지를 받아와야 하는 경우일 수도 있습니다.
하지만 다음 패키지가 대체합니다:
  oracle-java8-installer

E: 'oracle-jdk7-installer' 패키지는 설치할 수 있는 후보가 없습니다

help me TT

**Comment by fermat39** [comment]
안녕하세요...
현재 jdk8이 설치되어있습니다.
 
굳이 jdk7을 설치하려는 이유가 있는 것인지요?
 
현재 상황으로 볼 때는 리눅스 배포판으로 jdk8이 설치되어 있는 상태이며, 
jdk7을 설치하려면 수동설치 파일을 다운받은 후 원하는 위치에 압축을 해제한 후
그 위치를 PATH변수에 설정해주면 됩니다.
 
약간의 OS 지식과 귀찮은 과정이 필요합니다. ^^
 
필요하신 목적이 무엇이신지 궁금하군요...
 
감사합니다. ㅎㅎ
 
 
 
-----Original Message-----

**Comment by nooblunux** [comment]
i can't korean in ubuntu
so i speak english.

thanks. your answer is useful ^^

**Comment by w3bn00b** [comment]
우분투에서도 ibus-hangul 설치하시면 한글 타이핑 할수 있어요
