### ISSUE TITLE
도메인 연결에 대하여

### ISSUE THREAD

**Issue by amplet7** [codingeverybody/codingyahac#217]
### 문제점

현재 '우비' 라는 곳에서 가상서버호스팅(ip주소로 접속)과 유료도메인 한개를 신청했습니다.
검색해보면 ip주소와 도메인을 도메인 제공업체에서 연결을 해줘야하는거 같은데..
업체에 문의해보면 서버에서 설정만하면 된다고하네요.

1. 업체에서 따로 도메인과 제 가상서버를 연결하질 않았는데.. 왜 이게 되는걸까요?

2. 서버 도메인 관련 설정해보려고 계속 검색 및 시도해봤는데 너무 복잡하고 방향을 못잡겠습니다.
- 어디를 어떻게 공부해야 될까요?
리눅스 우분투 14버전이고, nodejs+express로 서버 돌리고있습니다. 
- 혹시 [링크](http://jinbroing.tistory.com/186) 이 를 따라하면 될까요?;;

### 해본 것

이 [사이트 ](http://abc1211.tistory.com/283)  따라해봤는데 에러가 수도없이 발생하고, 너무 복잡합니다 ㅠㅠ

**Comment by fermat39** [comment]
안녕하세요... 
일반적으로 도메인을 구입한 곳에서 기본적으로 정보 연결 서비스를 해주고 있습니다.
 
보통은 가성서버호스팅의 관리자 화면에 가면 DNS (도메인 네임 서버) 설정 화면이 있습니다. 
이 곳에서 ip와 도메인을 연결할 수 있습니다.
 
 
-----Original Message-----

**Comment by amplet7** [comment]
@fermat39 그럼 아파치나 Node 스크립트나 서버 설정파일에서  따로 손댈건 없나요?

**Comment by fermat39** [comment]
안녕하세요

일단 ssh 방식으로 접속하실 때 도메인으로
서버에 접근하실 수 있으면 연결되었다고
할 수 있고

웹서버 및 WAS마다
설정부분이 있기는 합니다
메뉴얼을 읽어보세야 합니다
-----Original Message-----

**Comment by egoing** [comment]
사용하시는 환경이 어떻게 되어 있는지 알기가 어려워서 직접적인 도움을 드리기는 어렵지만, 
아래 순서로 학습을 해보시면 문제 해결 방법이 보일지도 모르겠어서 링크를 드려봅니다. 

https://opentutorials.org/course/3265
https://opentutorials.org/course/3276

원리가 현상 보다 생각보다 쉬울 때 가 많더라구요. 
힘내세요!

**Comment by hephaex** [comment]
도메인을 구입하셨거나 사용하실 수 있게 되면 접속할 수 있는 IP와 도메인을 연결하는 DNS (Domain Name Service)를 설정해서 사용할 수 있습니다. 

 AWS 클라우드를 사용하시면 Route 53을 기존 도메인에 대한 DNS 서비스로 설정해서 가상 서버와 도메인을 연결하실 수 있습니다.
