### ISSUE TITLE
내부 아이피 외부 아이피 + 도메인사용

### ISSUE THREAD

**Issue by nooblunux** [codingeverybody/codingyahac#221]
원래 외부아이피가 명령어에따라서 다른건가요?

curl http://ipinfo.io/ip 로입력해서 확인한 ip와 포트포워딩하려고 들어간 창에서 시스템요약정보에 들어가서 본 외부ip 주소가 다른데 정상인가요??

그리고 도메인을 구입하고 curl로확인한 외부아이피를 도메인에 등록하고 apache2를 실행한후
웹브라우저에서 도메인으로 접속해봤는데  MERCURY Corporation에서 로그인하는게뜨네요
여기 아이디비번이 뭔지도 모르는데 어떡하죠?

**Comment by egoing** [comment]
질문이 다소 모호해서 답변 대신 참고하실만한 수업을 드려봅니다. 

아래는 집에 있는 컴퓨터를 웹서버로 구동하는 방법에 대한 수업입니다. 
이중 포트포워딩 부분을 중심으로 보시면 도움이 될지도 모르겠습니다. 
https://opentutorials.org/course/3265

아래에는 도메인은 서버에 장착하는 방법에 대한 수업이 나와있습니다. 
https://opentutorials.org/course/3276

때로는 원리가 현상 보다 단순한 경우가 있거든요. 

조금 더 자세히 질문해주시면 답변하는데 도움이 될 것 같습니다.

**Comment by egoing** [comment]
추가 질문이 생기면 질문을 다시 열어주세요 :)
