### ISSUE TITLE
사진인식기술을 통한 약인식 앱을 만드는 중인데 잘하고 있는건지 모르겠어요?

### ISSUE THREAD

**Issue by rlaalstn0107** [codingeverybody/codingyahac#222]
제가 지금 3명의 친구와 함께 사진인식기술을 통한 약인식 앱 프로젝트를 진행중입니다.
제목 그대로 약이 있으면 사진만으로 그게 무슨 약인지 알려주는 앱입니다.(부가 기능으로 텍스트로도 검색이 가능하게 하려고 합니다.)
프로젝트 진행을 위해 전체적인 계획으로 우선 앱을 Firebase에 연결해서 만들고 앱에서 이미지를 서버에 보냅니다 그리고
파이썬 OpenCV로 사진을 인식해서 장고서버를 통해 웹에서 검색결과가 뭐가 나왔는지 앱에 다시보내는 형식으로 만들려고 합니다.
이렇게 만드는게 가능할까요?    
아니면 다른 더 쉬운방법이 있나요? 
참고로 csv파일로 이미지와 상세 정보들은 거의다 있고 자바는 꽤 많이 알고 있지만 앱은 배운적이 없어서 인터넷으로 하나씩 찾아가며 만들고 있습니다.   사진인식기술은 친구가 맡았는데 사진인식기술관련해서는 전혀 모릅니다.   앱 배울때 참고할만 한 사이트나 팁도 있으면 알려주시면 감사하겠습니다.
제대로 된 프로젝트가 처음이라 막막하네요.

**질문**

1. 제 프로젝트는 어떤 것들을 이용해서 만들어야 가장 쉽게 만들까요?
2. 안드로이드를 배울때 참고 할만한 좋은 것이 있을까요?(지금 인프런과 youtube를 통해 배우고 있습니다.)

**Comment by blackdew** [comment]
1. 주어진 이미지를 분류하는 것
2. 이미지를 서버로 보내는 것
3. 앱과 firebase를 연결하는 것
4. 장고서버의 구축 - 웹 검색결과 출력 

각각을 별개의 프로젝트로 개발을 해보시면서 개별로 확인해보세요.  
그렇게 서로 독립적으로 만들어서 완성해보면 하나로 연결할 수 있는 연결점이 보일 겁니다. :)

**Comment by rlaalstn0107** [comment]
감사합니다
