### ISSUE TITLE
프로젝트 도움이 필요해서 연락드립니다.

### ISSUE THREAD

**Issue by myevertime** [codingeverybody/codingyahac#223]
텍스트 마이닝 관련 프로젝트를 진행중인데 야학 4기를 신청하면 도움을 받을 수 있다고 해서 질문을 남기겠습니다. 텍스트마이닝을 통해서 마켓팅 쪽으로 분석을 하고 싶은데 혹시 관련해서 실무 경험이 있으시거나 전문가 분들이 계시는건가요? 있다면 어떻게 도움을 받을 수 있는지 궁급합니다. 이미 이번 야학 기수는 신청을 완료한 상태입니다.

**Comment by fermat39** [comment]
안녕하세요... 김영하 입니다.
 
질문이 너무 막연하네요... 어떤 연구를 하시려는 것인지와 어떤 언어를 사용하시려는지요??
 
 
-----Original Message-----

**Comment by myevertime** [comment]
비타민제 관련한 SNS크롤링된 데이터를 바탕으로 마켓팅 주제는 이미 몇가지 잡혀있는 상태입니다. R이나 파이썬을 사용해서 한국어 형태소 분석(KoNLPy)로 감성분석, 연관어 분석 진행하려고합니다.

**Comment by egoing** [comment]
코딩야학에서는 수천명의 참여자들을 20명이 안되는 조력자들이 돕고 있기 때문에 멘토링 수준의 도움을 드리기는 어렵답니다. 하나의 질문당 10분을 사용하는 룰을 내부적으로 가지고 있습니다. 

진행하시면서 맥락적으로 궁금한 부분을 최대한 좁게 질문해주시면 도움을 받으실 수 있을꺼에요. 

추후에 구체적으로 궁금하신 사항이 생기시면 질문을 올려주세요  :)

**Comment by fermat39** [comment]
안녕하세요... 김영하 입니다.
 
자세한 방법을 찾으시려는 경우, 제 메일로 따로 연락주셔도 됩니다.
 
감사합니다.
 
-----Original Message-----
