### ISSUE TITLE
c언어 소스코드좀 봐주실수있나요??

### ISSUE THREAD

**Issue by nooblunux** [codingeverybody/codingyahac#224]
10미만의 자연수에서 3과 5의 배수를 구하면 3,5,6,9이다. 이들의 총합은 23이다.

1000미만의 자연수에서 3,5의 배수의 총합을 구하라.

#include<stdio.h>
int main(){
	int be_3 = 0;
	int be_5 = 0;
	int je = 1;
	int pe = 1;
	for(int i =3; i <1000; i*je){
		be_3 = be_3 + i;
		je++;
	}
	for(int a = 5; a<1000; a*pe){
		be_5 = be_5 + a;
		pe++;	
	}
	return be_3 + be_5;
}

이문제를 푼건데 dev c++에서 컴파일하니 오류는없는데 컴파일이안되고 그냥검은화면에정지만돼서요..
이렇게푼게 맞는건가요??

그리고 가끔 dev c++ 이번과같이 컴파일하면 검은화면에 정지된상태로 있는 현상 해결하는방법이있나요 ㅠㅠㅠ

**Comment by nooblunux** [comment]
for문 조건부분에 ije 가아니고 i 곱하기je, ape가아니고 a곱하기pe입니다
글올리니 곱하기가 수정되네요..

**

**Comment by hojin-kr** [comment]
알고리즘에 대한 답 이전에 C언어에서 for문의 문법은 
for (초기식; 조건식; 증감식) { 실행문 } 
이렇게 되어있습니다.  조건식을 만족하는 동안 반복을 하게 되고요. 
 작성하신 코드에서 조건식에 사용되는 변수 i와 a 의 값의 변화를 살펴보시면 두 변수의 값의 변화가 없기 때문에 조건식을 계속해서 만족하게 되고 프로그램은 무한히 반복하게됩니다. 사용하신 컴파일러의 경우도 이 무한루프로 인해서 검은화면으로 중지된게 아닌가하고 생각해봅니다.

**Comment by JunhoYeo** [comment]
잠깐 팁이지만, 깃허브 이슈에는 마크다운 문법이 적용되기 때문에 코드를 ```로 감싸지 않은 채 * 등의 기호를 사용하면 의도와 다르게 표시될 수 있어요! 그럴 땐 `/*`처럼 슬래시를 앞에 붙여주는 것으로 escape 해줘서 글을 작성하면 정상적으로 표시된답니다 :)

**Comment by nooblunux** [comment]
아 바로이거였군요 ㅋㅋ 정말감사합니다!! 문법을 정확하게 이해했다고 생각 했는데 알고리즘문제풀다보니
아직부족하다는걸 느끼네요 ㅎㅎㅠㅠ

준호님이 알려주신 팁도 많은도움 됐네요 감사합니다^^
