### ISSUE TITLE
웹 디자이너.. 웹 퍼블리셔..가 되고 싶은 고1 학생인데요

### ISSUE THREAD

**Issue by HYUNSTARK** [codingeverybody/codingyahac#226]
언어의 범위는 어디까지 배우면 좋은지 궁금해요!

**Comment by hojin-kr** [comment]
생활코딩에 WEBn 이라는 이름으로 새로운 과정이 개설되었습니다.  그 과정의 n 에 속해있는 언어들이 지금  시기에 생각할 수 있는 웹 퍼블리셔의 기본이 되는 언어의 범위라고 생각해도 무리가 없을 것 같습니다.  (HTML, CSS, JavaScript, PHP, MySQL, Python)
https://opentutorials.org/course/3083

**Comment by HYUNSTARK** [comment]
답변 정말 감사합니다!

**Comment by egoing** [comment]
![webdesign](https://user-images.githubusercontent.com/303822/43402077-bfe7bca8-944c-11e8-8c31-441b8a95b957.png)

웹디자인을 지망하신다면 첨부한 이미지의 코스로 공부를 해보시면 좋을 것 같습니다. 자바스크립트는 필수는 아니지만, 알게 되면 할 수 있는 일이 훨씬 넓어진답니다. 

무엇보다 중요한 것은 무엇인가를 만들어보는 것이에요. ^^

**Comment by HYUNSTARK** [comment]
정말 도움 많이 됬습니다ㅠㅠ 감사합니다!
