### ISSUE TITLE
MySQL의 파일 저장 방법(BLOB)에 관한 질문을 드리고 싶습니다!

### ISSUE THREAD

**Issue by thisisjungeun** [codingeverybody/codingyahac#227]
저는 현재 nodejs를 이용해서 웹 사이트를 만들고 있는데, 사진을 저장하는 방법에 대한 고민이 있습니다. 원래 저는 BLOB type을 이용해서 MySQL에 이미지도 같이 저장하려는 계획을 세웠습니다. 그런데 계획을 조금 구체적으로 세우면서 Database에는 파일명만 저장하고 이미지 파일은 파일 시스템에 저장하는 방법이 프로그램의 속도 등의 문제에는 더 좋은 방법일까하는 고민을 하게 되었습니다. 이미지 파일을 Database에 insert 하는게 더 좋은 방법일까요 아니면 file system에 따로 저장하는게 더 좋을까요?

**Comment by egoing** [comment]
데이터베이스에서는 이미지를 저장하는 것이 권장되지 않는 답니다. 파일에 저장하실 것을 권해요. 
그리고 아래와 같은 서비스를 이용하면 업로드를 정말 쉽게 구현할 수 있어요. 
https://www.youtube.com/watch?v=1iViYMeEqq0

추가 질문이 필요하시면 질문을 다시 열어주세요~
