### ISSUE TITLE
웹사이트 코드에서 이렇게 나타나는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by oovuuv** [codingeverybody/codingyahac#229]
안녕하세요.
생활코딩으로 강의를 듣고 있는 완전 초보자입니다.

어떤 웹사이트를 들어가서 코드를 살펴보게 되잖아요?
그런데 거기 써있는 코드들의 방식은 선생님들이 초보자들에게 가르쳐주는 작성 방식과는 많이 다른 것 같아서 이유가 궁금합니다.
예를들어 맨아래 코드의 경우입니다. (아래 부분에 처박아 놨습니다.)
drupal이라는 사이트 내에 한 css 파일 중 발췌해왔습니다. 이걸 해석해달라는 의미는 아닙니다! ^^;;
도저히 사람이 작성했다고 믿기지 않는 가독성 제로의 상태입니다.
보통 에디터를 써서 사람이 코드를 작성했다면 
`div.messages { `
`background-position: 8px 8px;`
`background-repeat: no-repeat;`
`.....`
`}`
이런 식으로 가독성을 염두에 두고 작성을 하지 않나요?
공부하는 입장이라 사이트의 css 코드가 궁금해서 하나하나 열어보는데
이 사이트는 죄다 이런식으로 작성돼 있어서 알아 볼수가 없어서 그냥 덮어버리다가
왜 이런 현상(?)이 일어나는지 궁금해서 여쭤봅니다.

읽어주셔서 감사합니다.

* 여기서부터 그 문제의 코드입니다.
--------------------------------------------------------------------------
`div.messages{background-position:8px 8px;background-repeat:no-repeat;border:1px solid;margin:6px 0;padding:10px 10px 10px 50px;}div.status{background-image:url(/misc/message-24-ok.png);border-color:#be7;}div.status,.ok{color:#234600;}div.status,table tr.ok{background-color:#f8fff0;}div.warning{background-image:url(/misc/message-24-warning.png);border-color:#ed5;}div.warning,.warning{color:#840;}div.warning,table tr.warning{background-color:#fffce5;}div.error{background-image:url(/misc/message-24-error.png);border-color:#ed541d;}div.error,.error{color:#8c2e0b;}div.error,table tr.error{background-color:#fef5f1;}div.error p.error{color:#333;}div.messages ul{margin:0 0 0 1em;padding:0;}div.messages ul li{list-style-image:none;}
/*})'"*/
fieldset{margin-bottom:1em;padding:0.5em;}form{margin:0;padding:0;}hr{border:1px solid gray;height:1px;}img{border:0;}table{border-collapse:collapse;}th{border-bottom:3px solid #ccc;padding-right:1em;text-align:left;}tbody{border-top:1px solid #ccc;}tr.even,tr.odd{background-color:#eee;border-bottom:1px solid #ccc;padding:0.1em 0.6em;}th.active img{display:inline;}td.active{background-color:#ddd;}.item-list .title{font-weight:bold;}.item-list ul{margin:0 0 0.75em 0;padding:0;}.item-list ul li{margin:0 0 0.25em 1.5em;padding:0;}.form-item,.form-actions{margin-top:1em;margin-bottom:1em;}tr.odd .form-item,tr.even .form-item{margin-top:0;margin-bottom:0;white-space:nowrap;}.form-item .description{font-size:0.85em;}label{display:block;font-weight:bold;}label.option{display:inline;font-weight:normal;}.form-checkboxes .form-item,.form-radios .form-item{margin-top:0.4em;margin-bottom:0.4em;}.form-type-radio .description,.form-type-checkbox .description{margin-left:2.4em;}input.form-checkbox,input.form-radio{vertical-align:middle;}.marker,.form-required{color:#f00;}.form-item input.error,.form-item textarea.error,.form-item select.error{border:2px solid red;}.container-inline .form-actions,.container-inline.form-actions{margin-top:0;margin-bottom:0;}.more-link{text-align:right;}.more-help-link{text-align:right;}.more-help-link a{background:url(/misc/help.png) 0 50% no-repeat;padding:1px 0 1px 20px;}.item-list .pager{clear:both;text-align:center;}.item-list .pager li{background-image:none;display:inline;list-style-type:none;padding:0.5em;}.pager-current{font-weight:bold;}#autocomplete li.selected{background:#0072b9;color:#fff;}html.js fieldset.collapsible .fieldset-legend{background:url(/misc/menu-expanded.png) 5px 65% no-repeat;padding-left:15px;}html.js fieldset.collapsed .fieldset-legend{background-image:url(/misc/menu-collapsed.png);background-position:5px 50%;}.fieldset-legend span.summary{color:#999;font-size:0.9em;margin-left:0.5em;}tr.drag{background-color:#fffff0;}tr.drag-previous{background-color:#ffd;}.tabledrag-toggle-weight{font-size:0.9em;}body div.tabledrag-changed-warning{margin-bottom:0.5em;}tr.selected td{background:#ffc;}td.checkbox,th.checkbox{text-align:center;}.progress{font-weight:bold;}.progress .bar{background:#ccc;border-color:#666;margin:0 0.2em;-moz-border-radius:3px;-webkit-border-radius:3px;border-radius:3px;}.progress .filled{background:#0072b9 url(/misc/progress.gif);}
/*})'"*/`

**Comment by fermat39** [comment]
안녕하세요... 김영하입니다.
 
보통 자바스크립트의 경우 굳이 나누자면 개발자 버전, 운영 버전 2개로 제공합니다.
유명한 jQuery의 경우 compress버전이라고 해서 일반적인 이름에 min이 붙은 것을 제공합니다.
uncompresssed버전은 보통 개발용으로 사용합니다. compress 버전의 경우 문의를 주셨던 방식으로 제공합니다.
즉, 공백 및 탭, 개행 문자를 제외한 것입니다. 이는 자바스크립트 파일의 용량을 줄이기 위해서 입니다.
아래 그림은 보시면 2개 버전 용량의 차이에서 2.5배 정도 차이가 있다는 것을 알 수 있습니다.
 
이는 빠르고 쾌적한 서핑환경을 제공하고자 하기 때문입니다. 웹사이트를 처음 방문하게 되면 사용자가 인지하지 못할 정도의
빠른 시간에 해당 사이트에서 사용하는 자바스크립트 내용이 사용자 브라우저에 전송이 됩니다. 브라우저의 개발자 환경을 켜놓고 
해당 페이지에 접근하면 진행사항을 볼 수 있습니다.
 
이 때, 아무래도 용량이 작은 자바스크립트가 전송되는 것이 더 유리하겠지요? 개발 환경에서 개발을 할 때는 가독성을 위해 보통 
uncompresssed버전을 사용하지만, 실제 운영환경에서는 compress를 사용합니다. 개발환경과 운영환경을 서로 독립적인 서버이기 
때문입니다.
 
가끔 개발하신 때 자바스크립트 수정을 했는데 반영이 안 된 것 같이 느낄 때가 있습니다. 이는 수정된 자바스크립트를 다시 브라우저가
받지 않았기 때문입니다. 브라우저 리프레시를 하시면 수정된 자바스크립트가 반영됩니다.
 
 
 
 
 
 
-----Original Message-----
