### ISSUE TITLE
다른 사이트의 회원정보를 연동?

### ISSUE THREAD

**Issue by dwagwa** [codingeverybody/codingyahac#23]
안녕하세요 제가 하고 싶은 것은
제가 만들 웹사이트에 학교 홈페이지의 아이디로 로그인 가능하게 하는 것 입니다.
어떤식으로 해야할까요?

**Comment by egoing** [comment]
우선 질문 드릴 것은 학교 측에서 그것을 허용할지 궁금합니다.
