### ISSUE TITLE
문자열 이미지를 텍스트로 변환하는 서비스 만들기

### ISSUE THREAD

**Issue by jangjichang** [codingeverybody/codingyahac#230]
안녕하세요 우선 질문 읽어주셔서 감사합니다.

제가 만들고자하는 서비스에 대한 설명은 다음과 같습니다.

1. 웹에서 사용자로부터 문자열을 찍은 이미지를 입력받습니다.
2. 이미지를 인식하여 문자열을 추출해냅니다.
3. 같은 화면에 변환된 텍스트를 보여줍니다.

이 웹 서비스를 만들고 싶은데요

현재 저는 django 1.10.4. 버전을 이용해서 프로젝트를 진행중입니다.

사용자로부터 문자열을 찍은 이미지를 입력받아서 제 컴퓨터의 폴더에 저장하는 것 까지는 완료헀습니다.

이제 이 이미지를 2번 처리를 해줘야하는데 그 방법을 잘 모르겠습니다. 자바스크립트로 가능하다는 분도 있고 ajax로 하라는 분도있고 많은데... 좀 더 자세히 알고 싶습니다.

**Comment by fermat39** [comment]
안녕하세요... 김영하입니다.
 
이미지에서 글자를 찾으실 때 숫자의 경우 MNIST라고 치시면 
텐서플로를 사용한 유사한 사례를 많이 찾을 수 있습니다.
MNIST의 경우 딥러닝으로 숫자를 인식하는 유명한 데이터셋입니다.
아마도 글자의 경우도 찾을 수 있지 않을까 합니다.
tensorflow.js를 사용할 수도 있을 것입니다.
 
감사합니다. 
 
 
 
-----Original Message-----

**Comment by jangjichang** [comment]
@fermat39 
김영하님 답변감사합니다.

다시보니 제가 질문을 잘못했습니다.

2번을하는 프로그램은 만들었습니다. 예를들어서 Imagetotext.py라는 파일을 만들었습니다.

이 파일에 사진을 입력으로 주면 사진에 있는 문자열을 텍스트로 바꿔서 출력합니다.

문제는 이걸 **어떻게 웹 서비스로 사용자들에게 제공하는가** 입니다.

사용자에게 이미지 입력도 받았고, 사진에 있는 문자열을 텍스트로 바꾸는 것 까지는 할 수 있는데요,

이 프로그램을 이용해 전체적인 웹 사이틀 구성을 모르겠습니다.

request로 파일을 받고, 서버쪽에서 그파일을 입력으로 넣고 Imagetotext.py라는 파일을 실행해서 나온 결괏값을 response로 반환해 주면 되는데 이것을 어떻게 해야하는지 알고싶습니다.

**Comment by blackdew** [comment]
아래 명령어로 코드상에서 bash 명령을 실행시키는 방법이 있습니다. 
import subprocess
result = subprocess.check_output('ls', shell=True)

---

위의 방법이 안되면 다음의 방법이 있겠네요. 

1. 파일이 업로드 되는 폴더를 지정
2. 파일이 업로드 될 때 DB에 기록하고,
3. crontab에 schedule을 걸어서 일정 시간마다 폴더 내의 모든 파일을 처리합니다. 
4. 이미지에서 텍스트를 추출하여 DB의 해당 데이터의 text 데이터를 업데이트 합니다. 
5. 위의 작업이 끝날 때까지 기다렸다가 사용자는 자신의 이미지에서 추출된 텍스트를 확인하게 됩니다.

**Comment by jangjichang** [comment]
@blackdew 친절한 답변 감사합니다.
근데 제가 1번은 했는데 2번부터는 잘 모르겠습니다. 어떤것을 공부(?) 해야할지 잘 모르겠습니다.
django로 웹사이트를 만들고 있는데요, html css를 이용해서 화면을 꾸미고 회원가입까지는 했는데요
2. 파일이 업로드 될 때 DB에 기록하는 방법을 모르겠습니다.

**Comment by blackdew** [comment]
1번이 되셨으면 'ls' 대신에 
Imagetotext.py를 가지고 유저가 업로드한 파일을 처리하는 명령어를 넣으시면 될 것 같은데요. 
한 번 시도해 보시겠어요? :) 

DB를 사용하는 것은 생활코딩에 database를 다루는 수업을 들으시면 도움이 되실 거에요! 
https://opentutorials.org/course/3160

**Comment by jangjichang** [comment]
@blackdew 친절한 답변 감사합니다.

> 'ls' 대신에 Imagetotext.py를 가지고 유저가 업로드한 파일을 처리하는 명령어를 넣으시면 될 것 같은데요.

라는게 무슨말씀이신지 잘 이해가 안갑니다. 예를 들어 Imagetotext.py 파일을 실행하는 명령어가

python Imagetotext.py [파일명] 이라고 했을 때 이 명령어를 어디에 넣으라는 말씀이신가요? 그리고 'ls' 대신에 라고 말씀하신 것도 이해가 안갑니다. 

database수업 추천해주셔서 감사합니다.

**Comment by blackdew** [comment]
에고, 재질문이 올라온 줄 몰랐네요 ㅠㅠ 
아래 코드로 진행해 보시겠어요? 

```
import subprocess
result = subprocess.check_output('python Imagetotext.py', shell=True)
```
