### ISSUE TITLE
블록체인으로 분산스토리지 프로젝트를 하기위해 필요지식이 어떤게 있을까요?

### ISSUE THREAD

**Issue by ToKimSeoYeon** [codingeverybody/codingyahac#231]
블록체인 분산스토리지 프로젝트를 멋지게는 아니더라도 간단하게 web으로 라도 만들고 싶은데, 이에 관한 자료나 정보가 있을만한 곳이 없을까요?
대부분 자료를 찾아보면 다 영어로 되있고 막상 해석하더라도 내가 해석한게 맞나 의구심이 듭니다.
어떻게 속시원하게 알려줄만한 곳이 없을런지 여쭤봅니다

**Comment by fermat39** [comment]
안녕하셔요 김영하입니다

일단 블록체인이 시작된 논문부터 읽으보시는 것은
어떠신지요?

한국어로 잘 번역된 것이 있습니다
https://encodent.com/bitcoin

이후에 하시고 싶으신 것에 대해서 구체적으로
그려보시면 괜찮을 것 같습니다

감사합니다
-----Original Message-----

**Comment by ToKimSeoYeon** [comment]
블록체인 논문으로 된것은 이미 한국어로 된것들을 많이 봐왔습니다.
저는 분산스토리지 관련해서 자료가 없어서 여쭈어 봤습니다.
분산스토리지 관련한 자료는 없는지요?
예를 들면 분산스토리지라는 것은 클라우드 스토리지 + 블록체인으로 구성되있는게 맞는지? 그게 아니라면 개념이 어떻게 되고, 만약
그렇다면 클라우드 스토리지를 알만한 간단한 코드 예제가 있는지 궁금합니자.

2018년 7월 31일 (화) 오후 4:45, fermat39 <notifications@github.com>님이 작성:

**Comment by blackdew** [comment]
검색해보니 다음과 같은 자료들이 보이네요. 
https://www.eiric.or.kr/community/post2.php?m=view&gubun=201607&num=4725&pg=1&seGubun=13&seGubun1=&SnxGubun=%C6%F7%BD%BA%C5%CD&searchBy=&searchWord=
https://steemit.com/kr/@areyoucrazy/storj-about-storj-coin

**Comment by studroid** [comment]
현재 블록체인에서 분산 스토리지로 유명한 프로젝트는 IPFS가 있습니다 :)

공식 홈페이지: https://ipfs.io/
한글로 된 설명글: https://steemit.com/kr/@kblock/8-ipfs-interplanetary-file-system-1-http-web-ipfs-web

Implementation에 대해서도 오픈 소스로 공개되어 있으니, 한번 검토해보시면 도움이 되실 듯합니다!

https://github.com/ipfs/ipfs#protocol-implementations

**Comment by studroid** [comment]
추가 질문이 있으면 다시 열어주세요! :)

우선 Close 하겠습니다
