### ISSUE TITLE
안드로이드 앱을 이용하여 아두이노 LED 켜기!

### ISSUE THREAD

**Issue by Mugglim** [codingeverybody/codingyahac#232]
안녕하세요.
대학교를 잠시 휴학하고 원하는 공부를 하고 있는 대학생입니다.
제가 학업하고 싶은 방향은 어플 or 웹 어플리케이션을 이용하여 아두이노를 제어하는거입니다.
현재 아두이노는 많이 다뤄봐서 제어할 수 있고 어플은 앱 인벤터로도 할 수 있지만
안드로이드를 이번에 공부해보려고 합니다. 안드로이드를 공부하기 위해 지금
생활코딩님의 JAVA강의를 70%정도 진행하였고 이제 안드로이드 이론공부와 병행하려고 합니다.
안드로이드 어플을 이용하여 아두이노 LED를 키게하려는게 제가 이번 코딩야학의 목표입니다.
학습 조언이나 안드로이드를 사용하여 아두이노를 제어하는 원리를 댓글 부탁드립니다.!

**Comment by yoobato** [comment]
안드로이드 앱과 아두이노와의 통신을 어떻게 할 것인지 정하는 것부터 시작하시면 될 것 같습니다.
가장 쉬운 방법은 블루투스를 이용하는 것입니다.

아래 링크 한 번 참고해보시면 좋을 것 같습니다.
https://kocoafab.cc/tutorial/view/444

**Comment by Mugglim** [comment]
답변 감사합니다!
