### ISSUE TITLE
자바 웹 개발에 앞서서 전체적인 지도에 대해서 궁금합니다!

### ISSUE THREAD

**Issue by WHITEPAEK** [codingeverybody/codingyahac#235]
프로젝트를 만들고 싶은데, 앞서서 필요한 언어와 개념들이 맞는 것일까요?
더 필요한 개념이나 혹은 필요 없는 개념에 대해서 궁금합니다!

✓ 프론트엔드 : HTML, CSS, JavaScript, jQuery
✓ 백엔드 : Java, JSP, Servlet - MVC2
✓ 서버 : Apache Tomcat
✓ 데이터베이스 : MySql

**Comment by egoing** [comment]
기술을 잘 구분하고 계신 것 같습니다. ^^
그리고 관련해서 일전에 제가 답변을 했던 관련 내용이 있어서 링크 걸어봅니다. 
https://github.com/codingeverybody/codingyahac/issues/216#issuecomment-408394917

**Comment by WHITEPAEK** [comment]
egoing님, 댓글 감사합니다~^^
생각한 구현 방법으로 열심히 공부하고 진행 해봐야겠네요~^^
