### ISSUE TITLE
블록체인 질문

### ISSUE THREAD

**Issue by songpang** [codingeverybody/codingyahac#236]
정보의 투명성을 위해 블록체인을 이용하는 프로젝트를 진행하려고 합니다.
저희 프로젝트의 주된내용은 이렇습니다.
기존 폐쇄적인 기부시스템의 비신뢰성을 탈피하기 위해 블록체인을 도입하여 신뢰성 향상 도모가
주 목적이며 이를 안드로이드 어플리케이션으로 구현하여 그안에서 블록체인이 동작하는 식(?)으로
개발을 진행하려고 합니다. 이를 위해 간단한 안드로이드의 XML제작은 스케치해놓은 상태이고
기초적인 solidity랑 geth, truffle 공부를 진행해왔는데요.
이제 개발 초기의 방향성을 어떻게 잡아야 할 지 모르겠어서 질문드립니다.
일단 공부하다가 궁금한점을 여쭤보자면

1. 오픈제플린의 ERC20이라는 프로토콜(?)을 수정하여 코인을 개발하는 것인지?
(오픈제플린 폴더를 뜯어보니 ERC20 폴더 내에 다수의 sol파일이 있더라구요)

2. 간단한 metacoin 예제를 찾아보니 되게 코드가 간단하고 짧던데 이렇게 구현해도 되는지 ?

**Comment by studroid** [comment]
안녕하세요, 첫 블록체인 질문이네요! :)

1. 맞습니다. ERC20은 일종의 표준이라고 보시면 되구요, ERC20 내에 다수의 sol 파일은 다양한 토큰의 특성을 정의하는, 상속할 수 있는 컨트랙트들입니다.

다만 일반적으로 StandardToken으로 처음 개발해보시는 게 좋고, 나머지는 구글링을 통해 특성을 파악하셔야 합니다 :)

발행 방법은 아래 두 사이트 참고해보시면 될 듯합니다.

https://steemkr.com/jjangjjangman/@dimens/1-erc20

https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6


2. 맞습니다. 토큰 컨트랙트는 굉장히 간단하고 짧아요. 심지어 ICO를 위한 Crowdsale 컨트랙트도 OpenZeppelin에서 제공하는 예제를 기반으로 하면 굉장히 쉽게 만들 수 있습니다.

실제로 OpenZeppelin의 예제를 사용하여 토큰을 많이들 발행합니다. 다른 프로젝트의 구조를 참고해보시는 것도 도움이 되실 듯한데, 제가 커뮤니티 매니징을 하고 있는 Loom Network의 토큰은 아래 URL의 Code 부분을 보시면 확인하실 수 있듯이, StandardToken을 쓰며 발행량 10억 개로 정해져 있습니다. :)

https://etherscan.io/address/0xa4e8c3ec456107ea67d3075bf9e3df3a75823db0#code

**Comment by songpang** [comment]
감사합니다 ㅠㅠ 블록체인을 처음 공부하는 학생이라 어려운것이 많네요. 
궁금한점이 생겼을때 다시 오겠습니당.
