### ISSUE TITLE
계획 세우기: 계획을 세우기가 너무 어려워요

### ISSUE THREAD

**Issue by beginner29** [codingeverybody/codingyahac#246]
해보고 싶은 프로젝트가 나이 드신분들을 위한 웹용 단어 퀴즈를 제작 해보고 싶은데 어떻게 계획을 짜야 할 지 잘 모르겠어요. 

어떤 코딩 기술이 필요한지, 어느걸 통해 어느 순서로 해야 할지 감이 잘 잡히지 않습니다.

꼭 좀 도와주세요

**Comment by o2-basta** [comment]
우선적으로 필요한것은 만들고 싶은것을 구체화하는것입니다. 

코딩이나 개발을 떠나서 머릿속에 있는내용을 종이에 그려보세요.
더좋은것은 그려놓은 내용이 서로 연결되는 것입니다. 
그림을 그려놓고 나면 어떤 내용이 필요한지, 어떤식으로 화면이 연결되는지 구체화 될 수 있습니다. 
코딩이라는게 간단히 보면 컴퓨터에게 우리가 원하는것을 차분하고도 자세하게 알려주는 일입니다. 
따라서 원하는 것이 무엇인지 자세하게 설명할 수 있으면 됩니다. 
중간에 변경되어서 그림을 다시그려도 좋습니다. 코딩을 다시하는것보다는 빠르고 수월하게 바꿀수 있으니까요.
그렇게 구체적으로 머리속이 정리되면 적절한 언어/플랫폼/기반기술을 골라서 작업하면 됩니다. 
우선 맘속에 있는걸 꺼내보세요. 
그러고 다시 질문해 주세요
