### ISSUE TITLE
적지않은 나이에 기본도 없이 프로그래머를 준비하려합니다.

### ISSUE THREAD

**Issue by lived1024** [codingeverybody/codingyahac#249]
안녕하세요. 만 31살의 취준생입니다.
이리저리 공무원공부한다고 시간낭비가 많다보니 이 나이에 국가기간전략산업으로 개발자 직업훈련을 할 예정인데... IT계열에 관심은 많았지만 아는 부분이 없던차에 이 사이트를 알게 되었습니다.
주변에도 IT계열에 종사하는 사람이 없다보니 너무 막막하던차에 코딩야학을 알게되어 코딩 공부할 예정이라 덜컥 신청하고 듣기 시작했네요. 제 미래가 걸린 선택이다보니 어떻게 준비를 해야 될지 막막해서 질문을 드려봅니다.

1.개발자 쪽은 컴퓨터 언어를 여러가지 알수록 좋다고 하는데 국가기간전략산업으로 직업훈련 하는 곳에서는 자바만 배운다고 들었습니다. 주로 웹개발, 안드로이드 앱 개발 쪽으로 교육을 진행한다 하는데 자바 1개만 전문으로'만' 했을시 장래성이 있나요? 
 1-1, 아니면 약 4개월을 늦춰서라도 기본적인 파이썬, C++, 자바, JSP 등의 단과교육이라도 듣고 직업교육을 받는 것이 나을까요?
 1-2. 눈여겨본 강의가 9월개강이라 생활코딩 페이지에서 강의들을 보고 바로 들을지, 1-1 질문처럼 단과라도 각 언어를 조금씩이라도 공부해야할지 고민이 많습니다.

2. 주로 프로그래머에 관한 편견이 일명 '코딩노예'를 의미한다는 것을 인터넷에서 알게 되었습니다. 실제로 프로그래머의 근무환경이나 조건은 많이 개선되어 좋아졌다고 알고있구요.. 다만 개발자가 경력 3년 이후부터는 대우가 좋아진다고 들었는데 이 '코딩노예'는 신입에서 약 3년차까지를 일컫는지 궁금합니다. 신입에서 약 3년차까지가 아니라면 어떤 능력이 부족했을 경우에 코딩노예로 전락하는지 알고 싶습니다.

3. 직업훈련 이후 웹 개발, 응용SW개발 등등 개발분야쪽으로 나갈수 있다는 것을 알기는 하지만 프로그래머도 워낙 많은 종류가 존재하다보니 어떻게 목표를 잡아야될지도 조금 난감한 부분이 있네요....

4. 훌륭한 프로그래머가 되기 위한 기본조건이 무엇이라고 생각하시는지도 궁금하네요

개발자분들께서 보시기에 답이없다고 생각하실 수도 있는 상황이지만 뒤늦게나마 개발자쪽을으로 진로를 잡았지만 어떤 능력을 갖춰야 훌륭한 프로그래머가 될 수 있는지 많이 궁금합니다. 주변에 조언을 구하려해도 인맥도 없고, 학원관계자들이다보니 객관적이지 못하여 더 답답함을 느끼기도 하네요..

**Comment by o2-basta** [comment]
1. 컴퓨터 언어를 배우는것은  외국어를 배우는것과도 비슷합니다. 배우는것과 병행해서 자주 사용할 수 있으면 아주 좋습니다. 그러니까 배운다고 생각하시기 보다는 익숙해진다고 보시면 좋겠습니다. 
눈여겨 봐두신 강의가 어떤것인지 궁금하네요 ㅎㅎ 
제생각에는 이것저것 준비하기보다는 바로 원하는곳으로 가시고, 필요한것들은 그때그때 검색을 하시거나 생코강의등을 찾아보시면 될거같습니다. 다른것들을 먼저 접하고 준비하다보면 변죽만 울리다가 흥미없어 질 수 있어요. 

2. 제가 생각하는 코딩노예는 다른사람이 생각한것을 만들어 주는것이라고 생각합니다. 아마도 질문에서 개발자 3년차까지를 코딩노예라고 하는것을 생각해보면, 주어진 업무에서 자기가 의도한대로 개발내용을 가져갈 수 있느냐 하는것에서 판가름 난다고 보여집니다. 쉽게 말해서 코딩에서 벗어나 개발적으로 무리없이 진행되도록 개발설계를 할 수 있을지가 관건일거 같습니다. 이부분은 경험이 우선적으로 중요하고, 새로나오는 신기술들을 계속적으로 배워나가는게 도움이 될 수 있을거 같습니다. 무엇보다도 회사업무적으로 같은일을 반복한다면,  개인적인 프로젝트나 해커톤등을 많이 해보는게 좋을거 같습니다.

3. 일단 직업훈련을 하고나면, 원하는 분야가 생기실 거 같아요. 일단 접해봤는데, 가슴뛰는 부분이 없다면 코딩보다 더 잼있는일이 기다리고 있는거 같아요. 개인적으로 뒤돌아보면 관심사는 계속적으로 이곳저곳으로 부유하는거 같아요.

4. 훌륭한 프로그래머가 되기위해서 가장 중요한것은 타인에 대한 이해인거 같습니다. 뚱단지 같은 이야기인데요 ㅎㅎ 
코딩을 한다는것은 남이 짜놓은 코드위에서 코딩을 하게 마련입니다. 그렇지 않다면 모든개발자가 각각 다른 언어를 만들어서 쓰고 있겠죠 ㅎㅎ 그래서 남이 만든 코드를 보고 이해하는게 중요한데, 이부분에서 필요한것이 남을 이해하는 능력입니다. 타인의 코드에서는 타인의 맥락들이 존재하는데, 그런것들을 놓치게 되면 효율적인 코딩이 어려워집니다. 간혹 번역서보다 원서로 읽는게 이해가 잘되는게 다 이런 이유입니다.ㅎㅎ

**Comment by lived1024** [comment]
친절한 답변 감사합니다. 다만 2번의 질문중에서 일명 '코딩노예'라고 불리는 사람들이 신입에서 3년차 인가? 아니면 말씀하신 것처럼 개발설계를 못하는 사람들을 지칭하는 것인지 그것도 조금 궁금하긴 하네요^^;;

제가 눈여겨봐뒀다는 강의는 총 2가지인데 하나는 9월에 시작하는 웹 크롤링을 활용한 자바프레임워크개발 이라는 프로그램과 자바기반 웹 개발자 양성 과정   이렇게 2개입니다

마음같아선 링크를 달아드리고 어떤지 의견좀 들어보고싶은데 그게 가능할지 모르겠네요... ㅎㅎ;;

**Comment by yoobato** [comment]
@lived1024 
코딩노예라는 말이 나온 배경(?)에 대해서는 크게 두 가지로 설명드릴 수 있을 것 같아요.

1. 저도 간혹 개발 프로젝트를 하다보면 많이 느끼는 것들인데, 개발자가 아닌 사람들이 개발자와 같이 일 할 때, 업무를 존중해주지 않는다는 점입니다. 요즘도 가끔 듣는 이야기지만, 어떤 웹페이지를 만들자고 했을 때, 이게 한 달이 걸린다고 생각되어, 한 달이 걸린다고 하면, '이게 뭐가 어렵다고 한 달이나 걸려...' 라는 말을 들을 때가 있습니다. 이런 맥락에서 나온 의미일 수도 있다고 생각합니다. 의사, 변호사 등의 전문직이 하는 말은 맞다고 믿으면서, 개발의 전문성은 존중해주지 않는 분위기가 있는 곳이 있기 때문입니다.

2. 어떤 프로그램 내지는 웹사이트를 만드는 방법은 여러가지가 있습니다. 예를 들어, ```안녕하세요```라는 문장을 100개 출력해야하는 프로그램을 만들어야된다고 할 때, 이걸 출력하는 문장을 정말 100번 직접 코딩하여 쓸 수도 있지만, 100번 반복하라는 반복문을 쓸 수도 있습니다. 즉, 코드에도 퀄리티라는게 있고, 어떻게 하면 더 깔끔하고 좋은 코드를 짤 수 있는가에 대한 논의들이 계속 이어지고 있습니다. 이런 고민을 스스로 계속하여, 본인이 만든 프로그램의 퀄리티를 지속적으로 높여나갈 수 있다면, 우려하시는 코딩노예에 대한 생각은 하지 않으셔도 훌륭한 개발자로 성장하실 수 있을 것입니다!

**Comment by lived1024** [comment]
@yoobato 상세한 설명 감사합니다! 결론은 코딩을 하는 방법에 있어서 저 스스로 세련(?)되고 간소화(?) 시키면서 제 코딩의 퀄리티를 상승시킨다면 일반적으로 생각하는 코딩노예에서는 벗어날수 있다고 하시는 것 같네요. 이제 입문을 하게 됐지만 최대한 노력을 해야겠습니다. 감사합니다!
