### ISSUE TITLE
자동다운로드 리워드 어플을 만들고 싶습니다.

### ISSUE THREAD

**Issue by chamchiking** [codingeverybody/codingyahac#25]
저는 학과에서 배우는 c++코딩만 하다가 어플 개발을 시작한 전기정보공학부 3학년에 재학중인 학생입니다.
오토링과 오토캐시와 같은 리워드 어플을 만드려고 하는데 자동 다운로드를 어떻게 구현해야하는지에서 막혀서 진행이 되지 않고 있습니다.
다음은 제가 지금까지 시도해보면서 관련 자료를 정리하고 시도해본 자료입니다.
혹시 어떻게 하는지 알려주실 수 있으시다면 정말 감사하겠습니다!!!
[자동설치 분석내용 정리.zip](https://github.com/codingeverybody/codingyahac/files/1599859/default.zip)

**Comment by blackdew** [comment]
1.1 '내 서버에서 접속하는 방법'은 법적으로도 문제가 있는 것 같아요. 일단, 이런 방식은 하지 않는 걸 권장드려요. 
2.1 'webview로 접속' 에서는 oauth에서 재로그인 없이도 받아온 token을 갱신할 수 있는 방법을 제공하는 걸로 알고 있어요. 그걸 이용하면 되지 않을까 싶습니다. 
2.2 '웹 페이지에서 구글 로그인을 실행 시킨 후 설치' - 2.1과 동일한 방식이라는 생각이 들고요. 아마 같은 문제가 발생할 겁니다.

**Comment by progh2** [comment]
왜 앱을 자동 다운로드해서 설치해야하는 것이 필요한지부터 설명을 해주시면 어떨까 합니다. 
이러한 기능이 허용된다면 여러 악성코드 등도 똑같은 방식으로 설치될 수 있는 길을 만들어주는 것과 같아서
사용자 동의 없이 앱을 설치할 수 있을뿐더러 법적인 문제도 될 수 있을 것으로 생각됩니다. 
앱 안의 내용의 갱신이 필요하던가 하면 그에 해당하는 데이터 파일만 앱에서 서버에 요청해서 받아오면 되며
그건 안드로이드 "서비스" 등 다양한 방법을 사용해서 구현하실 수 있을 것입니다.

**Comment by chamchiking** [comment]
앱의 내용을 갱신하는 것이 아니라 자동으로 설치를 시킨 후에 Nas나 TNK에서 광고하는 어플들에 대한 리워드를 지급해주는 어플을 만드려고 합니다.
실제 구글 플레이에 올라와있는 어플들로는 오토링, 오토캐시 같은 것이 있고요.
그냥 얼핏 듣기로는 pc 구글 플레이에서 핸드폰에 어플을 설치하는 방식을 핸드폰 webview로 실행을 시킨다고 들었습니다. 그런데 그것을 어떻게 자동으로 wifi가 되는 환경 내에서 실행이되도록 하는지 그 부분이 막혀서 질문을 드립니다. 알려주실 수 있으시다면 정말 감사하겠습니다.

**Comment by jungyoungsoo** [comment]
chamchiking 안녕하세요 이거 메일을 어떻게 보내는지 모르겠네요 ㅠㅠ 관련해서 저도 좀 조사중인데 같이 정보좀 공유하고 싶어서요 그런데 일반적으로 tnk, nas등 리워드앱 광고주 회사들은 광고목록이 생서되고 자체링크를 통하지 않고 다운받으면 보상을 못받게 되어있습니다. 물론 방법이야 있겠지만 혹시 정보좀 서로 공유하고 이부분에 대해서 연구하고 싶은데 메일좀 ㅁ주실수 있나요? michu88888@gmail.com
