### ISSUE TITLE
개인 회사를 차릴려고 합니다.

### ISSUE THREAD

**Issue by OHOHAOHO** [codingeverybody/codingyahac#251]
안녕하세요
개인 회사를 차릴려고하고, 지금 앱을 준비하고 있지만,
개발자가 아니기 때문에 코딩을 짜도 시원치가 않아 개발을 의뢰 하려고 하는데요,

개발자들이 처음에 대화를 하다 말고 계속해서 지분 이야기를 하는 개발자들이 간혹 있더라구요
또 금액을 너무 낮춰서 불러서 의심이 가기도 하고요...

B2B 웹을 개발하려고 하는데,

개발 업체에서 개발을 하고 제가 나중에 서버 관리를 하고 싶은데,
워낙 프로그래밍을 몰라서요..

제가 의뢰한 제 웹을 향후에 제가 직접 관리를 하려고자 한다면,
어느정도의 지식을 갖춰야 하는지 또한 알고 있어야 하는 프로그램이 무엇인지 좀 알고 싶어서요..

제가 개발하려는 웹의 concept를 알려드리자면, 잡플래닛하고 배달의 민족 같은 겁니다.
그리고 개발자들이 개발하다가 웹에 가입하는 회원들의 목록이나 이런걸 가져갈까 무지 두렵습니다..ㅠㅠ

또한 그들이 거기다가 백도어나 정보를 빼가는 기술을 심어 놓을지 않을지..ㅠ

그런거 발견하는 방법도 있는지 좀 알려주세요

죄송합니다 너무 서두없이 적어서요...ㅠ 제가 혼자서 다 하려고 하니 어렵네요. 주변 개발자들은 도와줄
생각도 안하고..(지들 필요할 땐 찾으면서...)

읽어주셔서 감사합니다.

**Comment by o2-basta** [comment]
여기서 질문하시는 분들은 자신의 프로젝트를 스스로 진행하면서 풀리지 않는 부분을 질문하곤 합니다. 
일단 전체적인 내용을 간단하게나마 시작해보시는건 어떨까합니다. 
개발자들이 무엇을 하고 있는지 알아야 한다면 개발자의 언어로 개발자와 얘기하거나 개발자의 언어로 씌여진 코드를 볼수 있으면 됩니다. 
물론 직접 코딩하는게 좋겠지만, 그렇지 않다면 읽고 이해할 수 있으면 좋을거 같습니다.

**Comment by blackdew** [comment]
생활코딩에서 약간의 코딩을 공부하신 후에 직접 간단한 버전을 만들어 보시면 좋을 것 같아요.
'프로토타입'을 만든다고 하는데요. 어떤 것이든지 html만 공부하셔도 충분히 만들 수 있습니다. 

프로토타입 버전을 만들어서 개발자에게 보여주면 
개발자들에게 무얼 만들어야 하는지 더 명확하게 알려줄 수 있고, 
프로토타입을 정도는 개발할 역량이 있는 분이라는 걸 알면, 
걱정하시는 그런 행동에 대해 억제하는 역할을 할 것 같아요. 

그리고 제가 아는 한 스스로 인생을 망칠 수 있는 그런 선택을 하는 경우는 잘 없거든요. :) 
직원을 두고 개발을 해도 혹은 외주 개발자와 개발을 하더라도 크게 걱정은 안하셔도 될 것 같아요. 
의심하기 보다는 상호간의 신뢰 속에 원하시는 프로젝트를 잘 완성하시길 바랍니다~

**Comment by OHOHAOHO** [comment]
감사합니다. 많은 도움 되었네요.. 저 역시 계속 공부하고 있는데, 실력 쌓기 보다는 왤케 걱정이 앞서는지 무서워서요.. 감사합니다.
