### ISSUE TITLE
리액트 질문입니다

### ISSUE THREAD

**Issue by hamwol** [codingeverybody/codingyahac#255]
안녕하세요.
리액트를 이용해 간단한 CRUD 페이지를 만들고 있습니다.
input나 select 태그에 값을 넣거나 사용자 입력 값을 가져올 때 document.getElementById.value를 많이 사용하고 있는데, 잘 되긴 하지만 안 좋은 방법인 것 같습니다. 더 좋은 방법이 있을까요?

**Comment by ghdalsrldi** [comment]
input이나 select 등의 태그의 value를 Props, State 등으로 관리하면 될 것 같아요
답변으로 달기에는 어려움이 있으니 해당 키워드로 검색해 주시면 도움이 될 것 같아요

**Comment by hamwol** [comment]
태그의 value를 State에 연결하고, 태그의 onChange에 함수를 달아 이벤트를 받아서 [event].target.value로 바뀐 값을 꺼내 해당 State를 변경하니까 되는군요.
감사합니다.
