### ISSUE TITLE
Day1 : 웹 페이지 제작 질문이요!

### ISSUE THREAD

**Issue by MoonSupport** [codingeverybody/codingyahac#258]
저는 코딩이 처음인 학생입니다.
내일, 그리고 앞으로 어떤 식으로 배워나가면 좋을지 배우고 싶습니다.

최근에 코딩에 관심이 생겨서 
일주인 전부터 이고잉님의 WEB1,2,3를 정주행하고 오늘부터 무턱대고 만들기 시작했습니다.
아직 저한테는 해결 해야 할 문제가 없어서
쇼핑을 즐겨하기에 쇼핑몰을 만들어 볼까 합니다.

WEB1,2,3 동안 엄청나게 많은 것을 배운거 같은데, 막상 만들고 보니 엉망진창이 되버렸네요.
스스로 해결해보려고 하다, 생전 처음 접한 생소하고 어려운 용어에 결국 SOS를 청합니다.

주소입니다.
https://clockmoon.github.io/FirstProject/index.html
https://github.com/ClockMoon/FirstProject

내일은 무엇을 공부해서 어떻게 만들어 고쳐 나가면 좋을까요?
최소한 찾아라도 볼 수 있게 무엇을 검색 하면 좋을지라도 배우고 싶습니다.
//그리고 책을 빌려서 정독하는게 도움이 될까요?//

**Comment by o2-basta** [comment]
오 멋져요!!

처음만든다면 막막하고 어떤걸 어떻게 해야할지 모르는게 당연합니다. 
사이트를 만들고 보면서 익숙하게 쇼핑하던걸 생각하면서 조금씩 고쳐나가면 될거 같아요. 
물론 첨음부터 잘할수 없지만 하다보면 자연스러워질거 같아요. 
그리고 더중요한것은 만들어 본내용을 다시 또 만들어 보는게 의외로 도움이 되는 경우가 많습니다. 개인적으로는 위키를 통해서 지식을 관리하는데, 각종버전의 위키페이지를 만들어보면서 코딩에 도움이 되었어요 ㅎㅎ

**Comment by blackdew** [comment]
차근차근 하나씩 배워가시면 좋을 것 같아요. 

쇼핑몰이 제법 난이도가 있는 애플리케이션이에요. 
꽤 먼 길이 될거에요. 마음의 준비를 먼저 좀 하시는게 좋을 것 같아요 :) 

먼저 메인페이지, 상품리스트 페이지, 그리고 상품페이지에 집중해 보세요. 
위의 세 종류의 페이지만를 구성하면서  
자바스크립트와 CSS, 서버 프로그래밍 언어(php, python, nodejs), 데이터베이스를 배우고 숙련하는 데에 집중하면 좋겠습니다. 

충분히 연습이 되신 후에 로그인, 구매, 장바구니 등등의 기능을 실력을 쌓아가면서 하나씩 더해가시면 
원하시는 쇼핑몰 사이트에 가까이 다가갈 수 있을 거에요. 

화이팅입니다. :)

**Comment by ClockMoon** [comment]
한 번 해볼께요! 감사합니다!
