### ISSUE TITLE
웹 프로그램(PHP+Javascript) 개발(또는 디버깅) 환경 등

### ISSUE THREAD

**Issue by attorneyatlaw** [codingeverybody/codingyahac#26]
안녕하세요, 웹 프로그램 개발(디버깅) 환경 등 관련하여 2가지 정도 문의하고 싶어 글을 올립니다.

개인적으로 웹 프로그래밍 관련해서는 생활코딩 강의를 통해 전체적인 구조 및 개념 정도만 파악하고 있는 상태입니다.

워드프레스(wordpress)의 plug-in 을 customization 하려 하는데, 그 전에 먼저 개발 환경을 셋업하고 싶습니다.

# 1.

웹 프로그래밍 개발할 때는 어떠한 개발 환경을 갖추어야 하는 지(갖출 수 있는 지) 알고 싶습니다.

예를 들어, (웹 프로그래밍이 아닌) C 또는 C++의 경우, 

과거에 개인적으로 Visual Studio IDE에서 디버깅을 하며 프로그램을 개발하였습니다.

Run to Cursor, Step Into 같은 디버거 모드의 기능을 PHP + Javascript 개발 환경에서 사용할 수 있는 지, 사용할 수 있다면 어떠한 환경을 어떻게 갖추어야 하는 지 알고 싶습니다.

혹시 PHP, Javascript는 C나 C++ 같은 컴파일러에 의한 언어가 아니어서 위와 같은 형태의 디버깅이
안 되는지요?

Customization 하려 하는 워드프레스의 특정 plug-in이 있는데 수십 개의 PHP와 Javascript 파일로 이루어져 있어 눈으로는 코드 분석하는데 한계가 있더군요.

Visual Studio 에서 C++ 디버거 사용하듯이 위 plug-in을 런타임에서 하나하나 뒤져가며 개발하고 싶습니다.

# 2.

위와 같은 웹 프로그래밍 디버깅 환경을 클라이언트와 서버 각각에 구축해야 하는 건지 알고 싶습니다.

조금 검색해보니, 웹 프로그래밍의 경우

local PC에 서버를 설치하여 그 환경에서 먼저 개발하고 그 다음에 remote server에 올리는 것이 일반적인 듯 합니다.

그런데 이렇게 하지 않고, 바로 클라이언트 - 서버(remote server) 환경에서 디버깅 환경을 구축하고 싶은데 가능한 지 알고 싶습니다.

현재 호스팅 서버를 임대하여 운영하고 있는 비즈니스 웹페이지가 이미 있습니다.

가르침 부탁드립니다.

**Comment by blackdew** [comment]
요즘에는 c9.io 같은 웹IDE 서비스에서 말씀하신 수준의 디버깅 모드를 제공하합니다. 
아래 동영상을 참고하시면 도움이 될 것 같네요. 
https://www.youtube.com/watch?v=l5HxwCMTMz8

**Comment by ghdalsrldi** [comment]
php디버깅은 xdebug라는 도구를 많이 사용하며
IDE와 연결하여 사용할 수 있습니다.
