### ISSUE TITLE
개발자가 되신계기가 궁금합니다.

### ISSUE THREAD

**Issue by Sixmonth6** [codingeverybody/codingyahac#260]
안녕하세요, 오늘 처음 수업들은 학생입니다. 너무 친절한 강의 감사합니다.
수업중에 채팅창에 질문을 하였으나, 운영자 분께서 깃험? 에 질문을 올리시면 좋을 것 같다고 하여 사용방법은 잘 모르겟지만 여기에 조심스럽게 글 올려 봅니다.

국문과 졸업하셔서 어떻게 개발자가 되신건지 그 부분이 궁금합니다. 저도 영문과&회계학 전공을 하여 회사를 다니고 있지만, 미래를 위해, 또 하고싶은 것을 하기 위해 코딩을 공부하려고 합니다. 
이것 저것 알아보다가, 정보를 쉽게 찾을 수 없던 중에 코딩야학을 알게 되어서 이렇게 수업을 듣게 되었습니다.
일단 코딩의 기초를 배우고 직업적으로 코딩을 하는 곳으로 이직을 해야 빠른 시간안에 실력이 많이 늘 것 같은데 이부분에 대한 조언 부탁드립니다.

**Comment by egoing** [comment]
제가 프로그래머가 된 계기는 학과에서 교수님이 학과 홈페이지를 만들어보라고 하신게 결정적인 계기가 되었습니다. 학과 홈페이지가 학우들에게 관심을 받기 시작하고, 저 또한 애착이 커지면서, 더 좋은 홈페이지를 만들기 위해서 

문제에 부딛히고
공부하고, 
해결하고, 
기분 좋고, 
반복 

하면서 코딩에 익숙해진 것 같습니다. 

제 개인적인 생각에 직장은 학원이 아니기 때문에 직장에서 배운다는 것은 코딩처럼 고도로 복잡한 작업에는 좋은 생각은 아니라고 생각합니다. 

아래 글처럼 적정수준의 공부를 하면서 나의 프로젝트를 키워나가신다면 네이티브처럼 코딩이 편하게 느껴지는 순간이 올 것 같습니다. 
https://opentutorials.org/course/1189/10015

여러 걱정이 있으시겠지만, 일단 코딩야학과 함께 하면서 완주하시면 다음 도약지점이 스스로 보일거에요. 

함께 하시죠 :)

**Comment by egoing** [comment]
더 궁금하신게 있으면 이슈를 열어주세요~
일단 닫겠습니다.
