### ISSUE TITLE
25살 취업준비생입니다.

### ISSUE THREAD

**Issue by parkseongjin2** [codingeverybody/codingyahac#263]
대학교는 따로 안가고 국기과정을 끝난 상태에서 개인포토폴리오 사이트를 만들면서 지내고 있습니다.
개인소개사이트를 제외한 사이트를 만들어야하는데 어떻게 시작할지가 막막해서 적어봅니다.
1. 고졸취업이라서 더욱 불안한것이 있습니다. 
고졸이라 취업이 더 힘든가요?
2. 취업을 위한 포토폴리오 제작을 위해 코딩을 해야하는데 제가 직접 디자인을 하지않고 코딩만하기 위한 무료 템플릿으로 만들어도 될까요?? 
3. 된다면 템플릿 사이트 추천해주실수 있나요??
PS. 디자인을 하지않고라는 말을 사용한 이유는 제가 디자인 전공이 아닐뿐더라 너무나도 자신이 없어서 입니다. 건방져 보일까봐 남깁니다.

**Comment by blackdew** [comment]
1. 경험상 더 힘들거이라 짐작합니다. 아마 대기업, 중견기업의 경우는 고졸 신입 취업은 거의 불가능할 것 같아요. 대한민국의 현실이니까요. 어쩔 수 없는 것 같습니다. 하지만, 다른 분야나 다른 직군와 비교했을 때에 개발자 직군은 그래도 학력에 덜 민감한 건 사실입니다. 노력하셔서 실력을 쌓으시면 충분히 원하는 곳에 취업할 수 있을 거에요. 

2. 프로그래머를 뽑을 때에 '디자인 능력 여부'는 플러스 알파는 되지만 마이너스 요인은 아닙니다. 무료 템플릿 디자인으로 하셔도 괜찮습니다. 완성한 다음에 어떤 기술을 사용해서 어떻게 구현을 했는지 잘 설명할 수 있으면 충분할 것 같습니다. 다만,  디자인을 직접 하지는 않아도 디자인을 고르는 안목은 높은 것이 도움이 많이 될거에요. :) 

3. 검색하니 꽤 나오는 것 같아요. "무료 디자인 템플릿" 키워드로 구글링해서 찾은 페이지 입니다. 
http://www.webjangi.com/design/freetemplate

**Comment by parkseongjin2** [comment]
감사합니다ㅠㅠ 
최근에 개인포토폴리오를 준비하면서 많이 고민하고 좌절하고 있었습니다.
다시한번 마음을 잡고 좋은 프로그래머가 될수 있도록 노력하겠습니다 ㅠㅠ
