### ISSUE TITLE
안드로이드 SDK와 Firebase로 앱을 만들고 있습니다. 개인정보보안 관련하여 질문 드립니다. 

### ISSUE THREAD

**Issue by beaucnl** [codingeverybody/codingyahac#264]
안녕하세요. 코딩을 시작한지 얼마 되지 않은 초보 개발자입니다. 

제목처럼 SDK와 Firebase를 이용하여 데이팅앱을 만들고 있습니다. 

회원 가입할 때, 본인인증 서비스 업체(드림시큐리티 등)를 이용하여 본인인증을 할 예정입니다. 
이 과정에서 입력된 이메일주소, 로그인비밀번호, 회원이름, 전화번호, 생년월일, 성별 등을 Firebase에 저장했습니다. 
Firebase에 저장된 이미지는 아래와 같습니다. 
<img width="522" alt="2018-08-01 11 47 06" src="https://user-images.githubusercontent.com/42003080/43529137-92ef7a84-95e5-11e8-9e2b-b1e4ad591330.png">

궁금한 점은, 

   1. 위의 이미지처럼 개인정보를 암호화 하지 않고 Firebase에 저장해도 되는지,
   2. 1번이 안된다면, 이메일주소, 로그인비밀번호, 전화번호, 성별 4가지만 저장해도 개인정보 관련된 법에 위반되는지,
   3. 2번도 안된다면, Firebase를 이용해서 개인정보를 암호화 하는 방법이 있는지
   4. 방법이 있다면 어떤 방식으로 해결해야 하는지 (또는 Firebase를 이용해서는 구현이 불가능한건지)

입니다. 검색을 했는데도 이해할 수 없는 답변이 있고, 해결할 수 있는 접근방식을 찾지 못하고 있습니다. 

도움을 요청 드립니다. 그리고 이런 좋은 기회를 주셔서 감사드립니다.

**Comment by blackdew** [comment]
회원가입을 받으실 때에 이용약관과 개인정보보호 규정에 대해서 
회원으로 부터 동의를 받는 절차를 거쳐야 하고요. 
그 규정에 따라 정보를 보관하고 이용하시면 문제는 없습니다. 

회원가입을 받는 여러 사이트들의 약관과 규정을 보시고 참고하시면 도움이 될거에요 :) 

그리고, 패스워드 이외의 정보는 그대로 저장하셔도 괜찮아요. 
로그인 패스워드는 sha256이상의 암호화 해쉬 알고리즘을 이용하여 암호화를 하셔야 합니다. 
암호화 하실 때에, timestamp를 salt값으로 이용하는 방식을 함께 이용하시는 것이 좋습니다. 

암호화 참고 링크: https://ppss.kr/archives/16823
(현재는 sha1 보다 높음 수준을 이용하는 것이 좋습니다. sha256이상을 이요하세요.)

salt를 이용한 암호화 해쉬 참고 링크: https://d2.naver.com/helloworld/318732

**Comment by beaucnl** [comment]
blackdew님 방향을 몰라서 답답했는데  답변 감사 드립니다.
