### ISSUE TITLE
Firebase를 안드로이드 앱개발에 이용하고싶습니다.

### ISSUE THREAD

**Issue by lavinedb** [codingeverybody/codingyahac#27]
제가 서버나 데이터베이스쪽을 깊게 다뤄본적이 없는데 간단하게나마 firebase는 이용해 본적이 있습니다
그래서 이번에 포트폴리오를 만드는데에 이용하고 싶은데, 
Nosql 환경에서 데이터 베이스 구조를 짜는 과정이 너무막막해서 조언을 얻고자 질문드리게 되었습니다

**Comment by egoing** [comment]
막막하죠. 정말 공감됩니다. 저도 nosql을 처음 접했을 때, 또 처음 무엇인가를 만들려고 했을 때 막막했던 기억이 생생해요. 

한편, 제가 생각하는 막막함의 실체 중의 하나는 공부가 부족해서가 아니라, 너무 많은 것을 공부해서 머리속이 너무 복잡해져 있어서 일 수 있습니다. 아마 프로젝트를 시작하시려고 한다면, 공부는 충분히 많이 하신 상태라고 짐작되는데요. 이제 머리속을 비우고, 단순하고 가벼운 것부터 포트폴리오를 만들어보시면 어떨까요? 

아래는 제가 만든 수업 중에 보편적이지 않은 코딩이라는 수업입니다. 한번 보시고 개인적이고, 작은 프로젝트들의 사례들을 한번 살펴보셔도 좋을 것 같습니다. 
https://opentutorials.org/course/2897

좀 더 좁혀서 질문해주시면 보다 구체적인 답변을 얻으실수도 있을 것 같아요.
