### ISSUE TITLE
자바스크립트 - 모듈을 어떤 형태로 만들어야 할지 고민입니다 ( 클래스 static vs 클래스 인스턴스  vs  해쉬맵)

### ISSUE THREAD

**Issue by swon223** [codingeverybody/codingyahac#272]
코딩야학 멘토님 안녕하세요!
우선 이렇게 좋은 기회를 마련해주셔서 감사드립니다.

현재 공부 목적으로 웹앱을 하나 만들고 있고, 사용하는 기술 스택은 HTML/CSS/Javascript/React/Node/MongoDB입니다.

지금 반복되는 코드가 나와서 모듈로 분리해보는 작업을 하고 있는데요, 모듈을 만들 때 위 세 가지 형태 중에 언제 어떤 형태를 쓰는 게 적합한지 판단하기가 어려워 글을 남기게 되었습니다ㅜ 아래는 제가 써본 모듈 코드인데 방식이 맞는지 여쭤보고 싶습니다

1. 로컬스토리지 값 저장/출력
로컬스토리지에 값을 저장할 때가 많고, 메소드 식별자에 좀더 의미를 담으려고 로컬스토리지 메소드를 아래와 같이 한 클래스에 모아봤습니다
```
// 모듈
const StorageHelper = class {
     constructor(){}
     public getIcon(){
          return localStorage.getItem('character');
     }
     // ...
}

const storageFinder = new StorageHelper();
export default storageFinder;
```
이렇게 쓰고 있었는데 문득 1) 그냥 해쉬맵처럼 전역 식별자 객체 안에 프로퍼티로 선언하면 안 되는지?
```
const StorageHelper = {
     getIcon : ( ) => {},
}
```
2) 인스터스를 export하지 말고,  그냥 클래스 메소드를 static으로 만들어서 클래스 자체를 쓰면 안 되는지?  같은 생각이 들었는데.. 일단 위와 같은 방식으로 만들었습니다.

2. API 요청 객체 ( 라이브러리 Axios 사용 )

CRUD 작업에 필요한 객체가 많이 나와서 따로 분리해봤습니다
```
POST 요청에 필요한 라이브러리 기본 코드

axios.post('/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })

```

```
// 모듈

const AxiosHelper = class {
     constructor(url: string , payload : {}) {
     super()
          this._url = url;
          this._payload = payload;
     }

     private requestLogin(){
          return Axios.post(`${this._url}`, this._payload)
          .then( docs => {
               // 생략
           }

}

export default AxiosHelper;

```
```
// home.tsx
componentMethod( ){
        const payload = { x : y }
     const EmailLoginAxios = new AxiosHelper(‘url’, ‘payload')
     EmailLoginAxios.requestLogin().then( res => {
      // 생략
     }
}
```
2번에서 객체 인스턴스를 만든 이유는 엔드포인트, 페이로드 스트링 값이 인스턴스 별로 다르다는 데 있었는데..사실 정확한 판단인지 모르겠습니다. 메소드를 한 클래스에 넣다보니  각 인스턴스에서 불필요한 메소드까지 가지게 되고, 사실상 코드를 모듈 파일에 똑같이 적고 있으니 모듈을 만든 이유가 없어진 것 같다는 생각이 드네요

 - 1번과 2번의 경우에 빌트인이나 라이브러리로 주어진 어떤 한 객체를 좀 편하게 쓰려는 작업인데 이럴 땐 어떤 형태로 모듈을 만드는 게 좋을지

- 위 경우를 제외하고 모듈를 만들 때 어떤 기준으로 접근하시는지 간략하게 여쭤보고 싶습니다. 감사합니다!

**Comment by blackdew** [comment]
위와 같이 'StorageHelper', 'AxiosHelper의 이름으로 method들을 묶어주게 되는 케이스는 
그 안의 메소드들을 여러곳에서 공유해서 사용하는 경우에 활용하면 좋습니다. 
OS의 공유 자원을 관리해주는 pool과 같은 개념인 거죠. 

만일. 각 method들이 대부분 특정 instance나 특정 함수 내에서만 각각 개별적으로 불리는 형태라면
해당 동작을 기준을 module을 분리하는 게 더 좋다고 생각이 됩니다. 

정답이 있는 것은 아니고 경험해 가면서 각자가 판단해야 하는 부분인 것 같네요 :) 
제 제안도 참고 정도로만 해주시면 될 것 같아요. 

질문의 내용을 볼 때 이미 질문자께서 충분히 고민하신 것 같아요. 본인의 판단을 믿고 가시면 될 것 같습니다. 
잘못된 선택이었음을 알게 되면 그 때 또 바꾸면 되지 않겠어요? ^__^

**Comment by swon223** [comment]
감사합니다! 많이 고민해보고 고쳐나가겠습니다 감사합니다~!
