### ISSUE TITLE
page를 만들고 있는데,  <details></details> 태그 질문이 있습니다.

### ISSUE THREAD

**Issue by gitsunmin** [codingeverybody/codingyahac#274]
<details></details> 태그로 접기 펼치기를 만들었는데, 화살표가 있습니다.

이 화살표를 없애는 방법이 있을까요...?

**Comment by swon223** [comment]
https://stackoverflow.com/questions/10813581/replace-the-expand-icon-of-html5-details-tag
참고하시면 될 것 같습니다~

**Comment by gitsunmin** [comment]
감사합니다!
