### ISSUE TITLE
메뉴바 가로 가운데 정렬 도움좀 부탁드립니다.

### ISSUE THREAD

**Issue by oovuuv** [codingeverybody/codingyahac#275]
안녕하세요
코딩야학 프로젝트로 웹페이지를 만들고 있습니다.
이 페이지에서 메뉴바를 div 사이즈 내에서 가로 가운데 정렬 시키고 싶습니다.
이를테면 생활코딩 사이트의 메뉴바와 같은 구성입니다.

ul, li로 메뉴를 짜고 css로 li 속성에 float: left를 통해 가로 정렬은 구성하였는데, 
전체를 감싼 div 내에서 **가로 가운데 정렬**이 되질 않고 그냥 왼쪽정렬만 되는 상태입니다.
인터넷 검색을 해서 여러가지를 찾아보았지만 거기 나오는 속성들을 적용해봐도 원하는대로 되질 않아요.
검색으로 css파일 내에서 li 요소에 width 값의 단위를 px이 아닌 em으로 했더니 
각각의 li 요소들의 너비가 em단위로 지정되면서 전체 div 내에서 자리를 잡아 가운데 정렬처럼 보이긴 하더라구요.
이 방법은 전체 div의 가로 사이즈를 변경하면 완전 망합니다. 
결국 근본적인 해결책은 아니라서 도움을 요청드립니다.
그냥 왼쪽 정렬이 되는 메뉴 구성으로 할까 하다가 -_-;;;; 꼭 처음 계획했던 대로 가로 구성으로 하고 싶습니다.
간단한 것 같은데 되질 않아서 답답합니다.

현재 index.html파일의 body 태그 내의 태그 상태는 아래와 같습니다.

```
  <div class="wrapper">
      <h1 class="subject"><a href="index.html">page subject</a></h1>
      <div class="nav">
        <ul>
          <li>
            <a href="service.html" title="서비스를 알아보세요">서비스</a>
          </li>
          <li>
            <a href="form.html" title="책 제작을 신청해보세요">제작 신청</a>
          </li>
          <li>
            <a href="calculator.html" title="책 제작 견적을 알아보세요">견적 계산</a>
          </li>
          <li>
            <a href="notice.html" title="신청 전 꼭 읽어주세요">주의 사항</a>
          </li>
          <li>
            <a href="epilogue.html" title="ㅇ">제작 후기</a>
          </li>
        </ul>
      </div>
      <p class="index">
        description
      </p>
  </div>


그리고 css파일의 상태는 아래와 같습니다.

.wrapper {
  width: 960px;
  margin: 0 auto;
  overflow: hidden;
  /* background-color: #9bc65e; */
}

h1 {
  margin: 20px;
  text-align: center;
}

h1 a {
  text-decoration: none;
}

.nav {
  display: inline-block;
  /* background-color: #fcac32; */
}

ul {
  margin: 20px auto;
}

li {
  padding: 7px 15px;
  margin-bottom: 20px;
  float: left;
  text-align: center;
  width: 10.12em;
}

**Comment by swon223** [comment]
html파일이 없어서 문서구조를 잘 모르겠는데 
지금 ul 태그에 너비가 적용이 안 되서 그런 것 같아요
ul태그에 ```width : 100%```한번 적용해보는 것도 괜찮을 것 같습니다
list옆에 뜨는 점은 ```list-style:none```으로 없앨 수 있습니다

**Comment by swon223** [comment]
백틱(`) 세번 처리하면 코드가 적힐 텐데 html코드 다시 한번 부탁드려두 될까용?

**Comment by oovuuv** [comment]
@swon223 님
방법 찾아서 다시 올려놨어요!

질문의 요점: 
li의 width: 10.12em;를 쓰지 않고 메뉴들을 wrapper 내에서 가운데 정렬을 시키고 싶습니다.
그리고 메뉴가 현재는 5가지지만 더 늘어나거나 줄어들어도 자동으로 정렬되면 가장 이상적일 것 같습니다!

**Comment by swon223** [comment]
혹시 선택자 wrapper는 문서 어디에 쓰이는 건가용?? html코드에서 안 보여서요

**Comment by oovuuv** [comment]
@swon223 님
저도 방금 그 실수를 발견하고 또다시 수정해두었습니다!
자꾸 번거롭게 해드려서 정말로 죄송합니다.ㅠㅠ 그리고 봐주셔서 정말 감사합니다...!

**Comment by swon223** [comment]
이렇게 하면 되는 걸까용?
http://jsbin.com/howokesese/edit?html,css,output

**Comment by oovuuv** [comment]
@swon223 님
처음에 가르쳐주신 ul에 width 100% 적용하는 방법을 자세하게 알려주셔서 정말 감사합니다!!
그리고 display도 어디에 적용해야 하는건지 개념이 명확지 않아 여기저기 다 써봤는데도 이모양이라..
결국 가로로 배치할 구간에만 display를 써야한다는 것을 알게 됐습니다!
바쁘신 시간 내주시고 도와주셔서 정말로 감사합니다..!!!

**Comment by swon223** [comment]
float을 `dispaly : inline-block`으로 대체했고, (inline-block이 가진 단점이 있는데 이건 따로 검색을..저도 정확히 모르겠네요)
중앙정렬을 하려고 li 부모 요소인 ul에 text-align: center를 적용했습니다. 인라인 요소는 text-align으로 중앙정렬이 된다고 알고 있어서 위와 같이 처리해봤습니다
