### ISSUE TITLE
현업에서는 어떤 과정으로 개발프로젝트를 진행하는지 궁금합니다.

### ISSUE THREAD

**Issue by PassionOfStudy** [codingeverybody/codingyahac#277]
안녕하세요~ 이번에 프로그래밍 개발 프로젝트를 진행해보려는 코딩새내기입니다.
다름이 아니라 프로그래밍 개발 프로젝트를 진행하는데 있어서 계획수립이 중요하다고 생각하는데요.
주제를 선정하고 계획서를 만드려는데, 프로그래밍 개발 계획서에는 어떠한 것들이 들어가는지 궁금합니다.
너무 질문이 길어진 것 같아 요약하자면
<br/>
<h2>Q1) 현업에서 프로그래밍 개발 계획수립은 어떻게 진행되나요?</h2>
<h2>Q2) 프로그래밍 개발은 어떤 절차에 맞춰서 이뤄지는가요?</h2>
<h2>Q3) 참고할 만한 자료나 서적이 있다면 추천부탁드립니다.</h2>
<br/>

이상입니다. 
마지막으로 이렇게 질문할 수 있는 좋은 공간을 제공해 주신 생활코딩 조력자분들께 감사합니다!

**Comment by o2-basta** [comment]
코딩을 배우면서 자연스럽게 프록젝트를 하게되는데요, 현업에서 진행되는 프로젝트는 많은 방법으로 진행합니다. 
개발자가 몇명이나 같이 참여하는지 아니면 온라인으로 참여하는지 등에 따라서 많이 달라 질 수 있어요. 
일반적으로 현업에서 개발계획은 기획단계에서 해야할것들을 구분하고 먼저 할것과 나중에 할것을 하나하나 해나가는 과정입니다. 
코딩이 각 단계별로 진행되는 것처럼 프로젝트도 단계별로 진행될 수 있어요. 가장중요한것은 각자 코딩가능하도록 해야할 일을 쪼개서 일을 나누고 협업하는 것입니다. 
2. 프로그램 개발은 기획하고 구현하고, 테스트 하고 서버에 올리거나 앱을 출시하는것입니다. 
3. 책이나 자료를 검색해보시면 될거 같아요."프로그램 개발 방법론" 같은 단어를 넣어서 검색하시면 원하는 결과를 얻으실 수 있을 것으로 생각됩니다. 

위의 내용은 이상적인 현업개발 방법이고, 현실의 현업은 기획한 내용이 하루아침에 바뀌고, 기획한내용을 서로 다르게 이해하고 있는경우도 있고, 테스트를 하기 어려운 경우도 있으며, 별거아닌일로 예상보다 많은 시간이 걸리기도 합니다. 리얼 현업얘기가 궁금하시면 메일주세요 ㅎㅎ
