### ISSUE TITLE
Atom에서 긴 문장을 줄바꿔서 볼 수 없나요.

### ISSUE THREAD

**Issue by Yoon-1** [codingeverybody/codingyahac#278]
Atom에서 긴 문장을 줄바꿔서 볼 수 없나요. 강사님 설명대로 HTTP에 대한 설명을 copy해와 붙여넣으니 
한줄이 너무 길어서 내용 찾기도 어렵고 편집도 어렵네요.
한 화면에서 볼 수 있도록 줄 바꿔서 보이는 방법 좀 부탁드립니다.

**Comment by metallsk** [comment]
아톰에서 File >> Settings를 클릭하고 Editor 탭에 Soft Wrap을 체크! 하시면 된다고 합니다!!

**Comment by Yoon-1** [comment]
정말 빠르고 확실한 답변 감사합니다.
