### ISSUE TITLE
django, db: 모델(DB?) 설계 관련 입니다

### ISSUE THREAD

**Issue by flavono123** [codingeverybody/codingyahac#28]
![image](https://user-images.githubusercontent.com/20619567/34520002-26a58974-f0ca-11e7-8fba-a64646997937.png)

이런 웹앱을 만들어 보려 합니다.
근데 제 설계/아이디어에서 바로 구현해도 괜찮을지 질문드립니다.

우선 YAGNI 원칙으로 최소 스펙을 구현 후 확장하려 합니다.

설계:
모델(`django.db.models.Model`)을 요리, 레시피(한 줄 단위 요리법 설명), 재료 이렇게 세 개만 만들려는데 
레시피와 재료에 요리를 외래키로 써야지 

이게 다입니다.

근데 막상 실제(?) 프로젝트라고 생각하니 상속할 슈퍼클래스 같은것도 생각해야 되나 싶고(YAGNI한다면서..)
너무 간단한거 아닌가 싶기도 하고요..

사실 제가 데이터베이스 지식이 부족한데 무지에서 오는 공포 같습니다.

데이터베이스 관련 mooc나 강의 추천해주셔도 감사하겠습니다!

**Comment by blackdew** [comment]
YAGNI "You aren't gonna need it" 이런 뜻인거죠? :) 

핵심 테이블은 말씀하신 세 개면 충분할 것 같아요. 
'요리'와 '레시피'의 관계(relation) 설정을 어떻게 하실지 
'레시피'와 '재료'의 관계(relation) 설정을 어떻게 하실지 고민을 하시면 될 것 같아요. 
상황에 따라 relation table을 추가해 주어야 할 수도 있습니다. 

간단한 E-R Diagram을 그려보시는 것을 추천해 드립니다. 
참고하실 만한 샘플 ER diagram 검색 결과를 링크했습니다. :) 
https://goo.gl/YquYhV

**Comment by flavono123** [comment]
@blackdew 
> *YAGNI "You aren't gonna need it" 이런 뜻인거죠? :)*
네 맞습니다! 🙌  제가 읽던 책에 나온 표현인데, 설명이 좀 부족했네요 😅

일단 깃허브 레포 만들고, ER 다이어그램도 필요한만큼만 공부해서 만들어 봐야겠어요.

정말 고맙습니다!

**Comment by flavono123** [comment]
말씀해주신 링크 참고해서 아래 그림 참고하기로 했는데요:
https://goo.gl/mdNeFe

몇 가지 질문 드립니다.

1. 그림에서 아래 부분이 이해안갑니다:
![image](https://user-images.githubusercontent.com/20619567/34532755-9ec01016-f0fa-11e7-8989-5d65890f907b.png)
(ㅁ-+o---ㅁ)

검색해본 결과 관계가 하나 또는 없음(?) 같은데,
그럼 재료(Ingredients)와 레시피(Recipe)의 관계는 어떻게 되는건가요..? (1 또는 0:1 ?)
ERM에서 개체끼리 1:1, 1:N, N:N의 표현은 이해가 가는데 중간에 관계(Ingredients used)가 있는 것은 또 이해가 잘 안갑니다.

제가 생각한 재료와 레시피의 관계는 N:N이었습니다!
그리고 재료에 관계 되는 레시피가 없을 수도 있겠다고 생각했습니다.

2. 제가 이전에 적은 요리, 레시피는 둘 다 개체로서 생각했습니다.
그런데 이것을 각각 (그림처럼) 레시피;개체, 요리법(instructions);속성으로 하면 될 것 같습니다.

그러면 요리법을 django.models.TextField 로 하고 내부적으로 한 줄 요리법이라는(줄 바꿈) 표시를 하면 될까요?

```
instruction = '물을 붓는다%끓인다%먹는다'

## 페이지에선 % 구분하여 한 줄 씩 보이게 함
# 물을 붓는다
# 끓인다
# 먹는다
```

P.S: 사실 이렇게 장황하게 설명 안하고 ERD로 그리고 싶었는데, [이걸](https://github.com/BurntSushi/erd)로 그리려다 하스켈 설치 실패해서 시간 허비 했습니다.. 😅😅😅😅😅 
혹시 [이 질문](https://stackoverflow.com/questions/48082595/install-haskell-through-ghc-in-fish)에 대한 답도 들을 수 있었으면 좋겠네요 .. 😢

**Comment by blackdew** [comment]
제 생각에도 재료-레시피의 관계는 N:N이 맞는 것 같아요. 
1:1, 1:N의 관계에서는 한쪽에 키 필드를 만들어 주어서, relation table을 만들지 않아도 데이터 간의 relation을 만들어 줄수 있는데요. 
N:N 관계를 설정하기 위해서는 중간에 relation table이 필요합니다.

링크 걸어주신 er-diagram에서는 그 relation table의 이름을 'ingredients used'로 결정한 것 같아요. "레시피에서 사용되고 있는 재료"라는 의미인 것 같습니다. 그런데 레시피만 만들어 두고 재료를 연결하지 않는 경우도 있나봐요. 재료가 선택되지 않는 경우도 허용을 하는 것 같네요. (이해가 안간다는 그림의 의미입니다.)

요리법은 text로 처리하셔도 전혀 문제가 없을거라고 생각합니다. 
다만, list field가 있으면 가장 좋을 것 같은데요. 검색해보니 이런 글이 있네요 참고하셔도 좋을 것 같아요. :) 
https://stackoverflow.com/questions/22340258/django-list-field-in-model

**Comment by flavono123** [comment]
@blackdew  고맙습니다~ 아직 Django ManyToMany까진 써보지 못해서.. 🙌 
오늘은 데이터베이스와 Django 공부를 더하고 진행 해야겠습니다.
