### ISSUE TITLE
[python3] javascript 크롤링 질문

### ISSUE THREAD

**Issue by KimBongNam** [codingeverybody/codingyahac#283]
beautifulsoup 를 이용해 가온차트를 크롤링하려고 합니다.
selenium으로 웹 페이지를 로드하는 것 까지는 완료했습니다.
페이지의 소스코드를 변수에 할당했는데 차트의 내용이 없어 확인해보니 웹사이트에서 차트를 javascript를 통해 불러오는 과정에서 이를 기다리지 않은 것이 문제인 것 같습니다.

알아보니 implicitly wait과 explicitly wait이라는 것이 있다고 하는데, 원하는 요소가 로드될 때까지 기다릴 때는 explicitly wait을 이용하는 것 같긴 한데 이를 코드로 구현하는 것이 어려워 도움을 청합니다.
`from selenium import webdriver
from bs4 import BeautifulSoup

path = "C:\chromedriver.exe"

driver = webdriver.Chrome(path)
driver.get('http://www.gaonchart.co.kr/main/section/search/list.gaon?serviceGbn=S1020&nationGbn=&yyyy=2018&condition=2&search_str=%EC%95%84%EC%9D%B4%EC%9C%A0')
html = driver.page_source
soup = BeautifulSoup(html,'html')
`

어떻게 대기하는 코드를 작성해야 할까요?

**Comment by blackdew** [comment]
`
from selenium import webdriver
from bs4 import BeautifulSoup

path = "C:\chromedriver.exe"

driver = webdriver.Chrome(path)
driver.get('http://www.gaonchart.co.kr/main/section/search/list.gaon?serviceGbn=S1020&nationGbn=&yyyy=2018&condition=2&search_str=%EC%95%84%EC%9D%B4%EC%9C%A0')

// 이 정도로도 html을 가져오는 것 같습니다. :) 
import time
time.sleep(3)

html = driver.page_source
soup = BeautifulSoup(html,'html5lib')

`

**Comment by KimBongNam** [comment]
혹시 왜 html5lib를 이용하는지 알려주실 수 있을까요?

**Comment by blackdew** [comment]
그 부분에는 Beautifulsoap으로 파싱할 문자열의 파서알고리즘을 명시하는 것입니다. 
제가 드린 소스에서는 html5lib이라는 파서를 이용하도록 명시한 것이고요. 
요즘에는 'html.parser'라는 파서를 주로 씁니다. 
만약 xml이나 json 문자열을 파싱한다고 하면 그와 관련된 파서를 명시해 주시면 되요. 

html5lib은 그냥 html을 파싱하는 여러가지 파서들 중에 하나의 알고리즘인데요. 
검색해서 들고 온 것이어서 딱히 여러 html 파서들 중에 어떤 장점이 있는지는 찾아보지 않았네요. 
궁금하시면 파서들을 검색해서 각각의 특징들을 확인해보세요! 

:)

**Comment by KimBongNam** [comment]
감사합니다!
