### ISSUE TITLE
(워드프레스) 풀스크린 스크롤 구현관련 질문입니다.

### ISSUE THREAD

**Issue by kingston31** [codingeverybody/codingyahac#284]
http://project191.kr

이 페이지를 보시는 편이 이해가 제일 빠르실 것 같습니다.

원하는 스타일은

http://awaker.co.kr
http://jungangdakgangjeong.com

위 페이지들과 같은 페이지를 구현하려고 했는데요,
상단에 margin인지 padding인지가 생겨서 없어지지 않습니다;
메뉴 투명한 부분까지 배경 이미지를 채워주고 싶은데 잘 안되네요 ㅠㅠ

avada 스킨에서는 멀쩡하게 구현이 되었는데, the7 스킨으로 바꾸고 나서 이런 현상이 발생하고있습니다.
아래에 아바다 스킨에서 구현했던 형태입니다.
https://imgur.com/a/0E3W0Ce

그리고 아래는 css와 js 파일을 올려두겠습니다.

http://project191.kr/custom/fullpage.css
http://project191.kr/custom/fullpage.js

**Comment by blackdew** [comment]
구글 개발자도구로 확인해보니 

아래와 같은 스타일 코드가 보이네요. 
```
#main {
  padding: 70px 0 70px 0;
}
```

이렇게 수정하시면, bottom padding이 사라집니다. 
```
#main {
  padding: 70px 0 0 0;
}
```

**Comment by kingston31** [comment]
답변 감사합니다!
일단 말씀해주신대로 main.css에서 해당 항목 찾아서 교체했는데요, 그래도 아무 변화가 없네요 ㅜㅜ
