### ISSUE TITLE
맥북에서 터미널로 자바 컴파일 오류..

### ISSUE THREAD

**Issue by WHITEPAEK** [codingeverybody/codingyahac#285]
<img width="682" alt="2018-08-02 9 43 07" src="https://user-images.githubusercontent.com/41967243/43586095-abbb7d62-96a1-11e8-8d65-bb14f87c1da7.png"><br>
<img width="682" alt="2018-08-02 9 43 23" src="https://user-images.githubusercontent.com/41967243/43586131-c21eef80-96a1-11e8-9b39-f61e4d79df1e.png">
<br>
[질문]
정상적으로 class파일까지도 생성을 했으나, 그 다음이 실행이 안되네요..ㅠ
해당 오류를 해결할라면 어떻게 해야하나요?

**Comment by blackdew** [comment]
저는 자바 코드를 작성해 본지가 15년쯤 된 것 같네요. ㅎㅎㅎ 

검색해 보니 같은 오류를 겪은 분이 올리신 글 같아서 참고하시라고 가져왔습니다. :) 
http://zeddios.tistory.com/41

**Comment by WHITEPAEK** [comment]
blackdew님, 댓글 감사합니다~^^
자바 공부를 하면서 검색 실력이 부족한 탓인지, 해당 문제 해결 방법에 대해서 못찾고 답답하기만 했었는데 한번에 해결됬습니다!
