### ISSUE TITLE
node js 에서

### ISSUE THREAD

**Issue by hynazomba** [codingeverybody/codingyahac#29]
로그인 코드 와  html 코드와 어떻게 배치 해야 되는지 알려주세요?

**Comment by egoing** [comment]
어디까지 학습하셨는지 또 어디까지 시도해보셨는지 좀 더 상세한 정보를 주시면 조력자들이 답변하기 좋을 것 같습니다 :)

**Comment by hynazomba** [comment]
passport 까지  해 보았는데 계속 연계 되니까  딱 잘라서  로그인  서버  연결 할려니 게속  연결이 안되네요?    로그인
한세트가 필요 해요 저는   감사해요  답장 주셔서... 아 그리고  반응형 웹 다 만들었는데  회원 가입하고  채팅창 만들고 게시판
을 제 반응형 웹에 올리고 싶어요.  게속 공부하고 시도 하고 있어요... 도와 주시면  감사 하겠습니다.

2018-01-04 0:45 GMT+09:00 egoing <notifications@github.com>:

**Comment by hynazomba** [comment]
오늘 강의 안해요?

2018년 1월 5일 오후 7:06, 김현식 <hynazomba@gmail.com>님이 작성:
