### ISSUE TITLE
Atom PHP 설정 질문

### ISSUE THREAD

**Issue by KimPinot** [codingeverybody/codingyahac#291]
### 문제점

1. atom 시작시마다 **'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.** 라는 알림이 뜸.
2. atom beauty php 를 사용하려고 하면 **Could not find 'php-cs-fixer'. The program may not be installed**라는 문구가 뜨며 사용을 할 수 없음.

### 시도해본 것
1. php 경로 연결
2. php-cs-fixer 설치 완료

이상하게 다 잘 되다가 php만 들어가면 이런 문제가 발생하네요...
해결 할 수 있는 방법이 있을까요?

**Comment by notkimwol** [comment]
안녕하세요. autocomplete-php 패키지 비활성화 이후 아무런 알림이 뜨지 않는 것을 확인했습니다. 감사합니다. 하지만 **_Could not find 'php-cs-fixer'. The program may not be installed_** 라는 문구가 뜨며 PHP 정렬이 되지 않네요...
