### ISSUE TITLE
데이터분석 사이트를 만들기 위해서는 뭘 공부하는게 가장 좋을까요?

### ISSUE THREAD

**Issue by nanhiei** [codingeverybody/codingyahac#294]
안녕하세요.
저는 프로젝트 팀으로 지원한 김형석입니다. 
어제와 오늘 라이브수업을 들었고 따로 여러가지 알아보면서 어느정도 감을 잡아 이번 코딩야학 기간동안은 PHP와 Mysql을 공부하는 방향으로 가야될 것 같다고 판단했습니다만 python이 제가 만들고자 하는 사이트를 만드는데 더 적합할 것 같아 제 지식으로는 애매한 부분이 있어 조력자님들에게 질문올립니다.  

질문에 앞서 프로젝트의 방향에 대해 간단히 소개하면 제가 만들려는 사이트는 약 반년간 회귀분석, 상관분석, 데이터마이닝 등이 가능한 형태로 데이터를 축적해놓았고 이를 토대로 정보공유사이트를 제작할 예정입니다. 초기에는 정보공유 목적으로 제공될 예정이지만 후에는 쌓아 놓은 데이터와 쌓이는 유저데이터를 토대로 데이터 분석을 하여 좀더 정교한 서비스로 발전시켜나갈 예정입니다.

느낌적으로는 PHP를 학습하고 Python을 배우는게 더 나을 것 같다는 생각이 들지만 seomal.org에 보면 Python은 Web1옆에 붙어있기에 후에 통계분석 할것을 고려하면 곧바로 Python을 하는게 나을 것 같긴합니다. (mysql에서도 통계분석이 가능한지는 잘 모르겠어서 pyhon에 더 후한 점수를 주고 있는 것은 사실입니다.) 

넉두리가 길어졌네요. 
PHP, MySql, Python 무엇부터 배우기 시작하면 제가 만들어내고 싶은 프로젝트의 기반을 만드는데 좋을까요? 또는 우선순위가 아닌 어떤것 하나만 집중적으로 해야한다면 무엇을 해야할까요? 만약 Python을 한다면 PHP나 MySql을 몰라도 상관이 없는지 궁금합니다. (당연히 개념은 이해합니다.)

답변부탁드립니다. 감사합니다.

**Comment by egoing** [comment]
안녕하세요.

제가 생각하기에는 웹사이트 만들기에 집중을 한다면 PHP가 더 시작하기 쉬운 선택일 것 같구요.

데이터 분석과 같은 분야까지 나아간다면 좀 더 범용적인 용도로도 사용할 수 있는 pyhton, javascript, java와 같은
언어가 더 좋은 선택이 될 것 같습니다.

Python으로 웹을 구현하는 것도 물론 가능합니다.

물론 개인적인 생각인거 아시죠? ^^

**Comment by blackdew** [comment]
이미 python을 할 줄 아신다면, flask library를 이용하여 웹사이트를 구축하셔도 좋을 것 같아요. 
데이터 분석을 python으로 하실 생각이라면 더욱 권해 드립니다. :) 
python과 flask만 배워도 사이트 구축은 어렵지 않게 하실 수 있으실 거에요. 

다만, 웹 기술의 기본에 대해 더 다지는 것을 목적으로 한다면 
php로 진행하는 생활코딩의 웹수업을 꼭 진행해 보셨으면 좋겠어요.

**Comment by nanhiei** [comment]
답변 감사합니다. 머리속 그림이 좀 더 명확해졌습니다. ^^

웹사이트를 잘 만드는 것이 우선순위이고 기본을 알아둬야지 나중에 훌륭한 친구와 함께 일하더라도 소통에 문제가 없을 것 같아 이번 코딩야학기간에는 PHP에 집중해봐야겠습니다. 파이썬과 플라스크는 후에 누군가가 될지 모르는 훌륭한 친구와 함께 만들어가도 좋을 것 같네요. ^^
