### ISSUE TITLE
다했는데 데이터 베이스에 저장이,...ㅠㅠ 

### ISSUE THREAD

**Issue by SemiAuto777** [codingeverybody/codingyahac#295]
**dbc.php** 

<?php
    include './dbc.php';
    
 $name=$_POST['voter_name'];

   mysqli_query ($conn, "
     INSERT INTO vote (
       voter_name
       )
       VALUES (
       '$name'
         )
   ");

 ?>

 <script>
 windows.alert('DB로 전송 완료 !');
 location.href='./main.php'
 </script>

**main.php**

<!DOCTYPE html>
<html>

<head>
 <meta charset="utf-8">
 <meta name="keywords" content="전자투표, 웹">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <meta http-equiv="refresh" content="30">
 <meta property="og:title" content=" 선거웹"/>
 <meta property="og:image" content="기표도장_him9114.jpg"/>
 <meta property="description" content="전자투표 웹"/>
 <title>학교 전자투표웹</title>

  <style>

 #title {
  padding: 30px;
  background-color: #373a3c;
  color: #f8f9fa;
  text-align: center;
  margin: 0;
}

body {
  margin: 0;
  margin-top: 0;
}

#b1 {
  border-width: 1px;
  border-color: #E6E6E6;
  text-align: center;
  border-style: solid;
  margin-right: 300px;
  margin-left: 300px;
  padding: 25px;
}

.b2 {
  border-width: 1px;
  border-color: #E6E6E6;
  text-align: center;
  border-style: solid;
  margin-right: 300px;
  margin-left: 300px;
  padding: 300px;
  margin-top: 50px;
}

@media(max-width:1218px) {

  #b1 {
    border-width: 1px;
    border-color: #E6E6E6;
    text-align: center;
    border-style: solid;
    margin-right: 20px;
    margin-left: 20px;
    padding: 25px;
  }

  .b2 {
    border-width: 1px;
    border-color: #E6E6E6;
    text-align: center;
    border-style: solid;
    margin-right: 20px;
    margin-left: 20px;
    padding: 25px;
    margin-top: 50px;
  }

}

  </style>

<script>

</script>

</head>

<body>

**result.php** 

<?
include("./dbconnection.php");
      $connect=dbconn();
      ?>

<h3 id="title"></h3>

<h4 id="b1"></h4>

<form action="./result.php" name='review_table' method="post" class="b2">
  <p><input type="text" name="voter_name" placeholder="Name"></p>
  <p><input type="submit"></p>

</body>

</html>

<?php
    include './dbc.php';
    
 $name=$_POST['voter_name'];

   mysqli_query ($conn, "
     INSERT INTO vote (
       voter_name
       )
       VALUES (
       '$name'
         )
   ");

 ?>

 <script>
 windows.alert('DB로 전송 완료 !');
 location.href='./main.php'
 </script>

mysql에는 db이름 : vote 테이블이름: votetable 컬럼: voter_name

이렇게 했는데 데이터 베이스에는 저장이 안되네요. ,....

**Comment by egoing** [comment]
에러 메시지는 확인해보셨나요? 
보내주신 정보만으로는 파악하기가 어렵답니다. 

또는 아래와 같은 방법으로 쿼리 로그가 어떻게 데이터베이스 서버에 전달되는지를 확인해볼 수 있다면 문제에 더 가까이 갈 수 있습니다. 
http://blog.plura.io/?p=4493

**Comment by SemiAuto777** [comment]
해결했습니다! 단순 코드작성 미숙이였네요,, ㅠㅠ
