### ISSUE TITLE
안드로이드 notificationListenserService API... 

### ISSUE THREAD

**Issue by ParkHongUK** [codingeverybody/codingyahac#296]
안녕하세요..

현재 제 디바이스는 안드로이드 8.0 (오레오) 갤럭시 s8+ 사용중입니다.

안드로이드 스튜디오에서 emulator 로 돌리면, notification post가 잘 들어오고.. 이것도 잘 처리하게 구현해놨는데요.

( 전화 수,발신 시 전화가 연결중.. 통화중.. 이런 메시지를 받고 처리하기 위해서 사용중입니다.)

근데 제 디바이스에서 앱 설치후 실행해보니, 들어오는 notification 이 제대로 처리가 안되는 현상을 겪었습니다.

오레오 특성상 백그라운드에서 막아놨나..했더니 방금 로그를 찍어보니 한글로 노티가 찍히더라구요.

현재 통화 , 전화 연결 중 << 이런식으로요.
혹시 이거에 관련해서 답변해주실 수 있으신가요.

핵심 문제는 에뮬레이터에서 돌려본대로 돌아가지 않는다는 것입니다.

**Comment by InyoungAum** [comment]
혹시 
https://cheonjoosung.github.io/android/2017/07/09/it_android_permission.html
여기있는 퍼미션 처리를 하셨는데도 폰에서 해당 기능이 작동하지 않으시나요?

**Comment by ParkHongUK** [comment]
네 이미 권한은 모두 정상적으로 허용한 상태입니다..

**Comment by InyoungAum** [comment]
https://stackoverflow.com/questions/17911883/cannot-get-the-notificationlistenerservice-class-to-work

http://goodtogreate.tistory.com/entry/NotificationListenerService-%EC%9D%B4%EC%83%81-%EC%A2%85%EB%A3%8C-%EB%AC%B8%EC%A0%9C-%EB%B0%8F-%EB%94%94%EB%B2%84%EA%B9%85-%EB%B0%A9%EB%B2%95

두 링크가 도움이 될 수 있을 것 같은데요 저도 비슷하게 해봤는데 재현이 되지않아 추측으로만 답변을 달아드리는 점 양해 부탁드립니다. 
두 링크의 내용을 보면 이미 한번 잡고있어서 업데이트가 안되거나 혹은 코어쪽 문제이니 서비스를 껐다가 다시 연결하거나  아예 리부트 하는 방법등을 제시하고 있네요.
