### ISSUE TITLE
오래 기억하는 프로그램 만들려고 합니다. [과제]

### ISSUE THREAD

**Issue by yong9795** [codingeverybody/codingyahac#299]
코딩야학에 참여하기 전에는 프로그램을 개발한다는 것이 너무나 어렵게만 느껴졌었습니다.
코딩야학 4기에 참여하고 있는데 WEB1 과정이 궁금하여 미리 내용을 끝까지 보았습니다.
WEB1 과정을 마치고나니 무엇인가 개발해보고 싶은 욕심이 생기네요.

제가 자꾸 까먹는 것이 많아져서....기억을 오래하는 방법의 프로그램을 개발해보고 싶습니다.
예를 들어서 단어 또는 문장 암기 프로그램을 컴퓨터(웹)에서 구현하려고 합니다.
우선 WEB1 과정은 끝냈는데... 무엇을 더 공부해야 이런 프로그램을 개발할 수 있는지 알려주세요.
그리고 핸드폰에서도 구동되도록 개발하는 것이 가능할까요?
고맙습니다.

**Comment by laftworld** [comment]
python이나 java, javascript같은 프로그래밍 언어를 배워보세요. 
html로는 말씀하신것 같은 동적인 로직을 구현하기 어렵습니다. 

핸드폰으로 개발을 하려면, 기종에 따라(안드로이드 / iOS) 프로그래밍 언어가 다릅니다.
웹 공부를 더 하셔서 웹앱으로 구현하셔도 좋을듯 합니다. 안드로이드/iOS는 최소로 배우고, 웹브라우저를 핸드폰에 띄우는 식으로 동작합니다.

**Comment by yong9795** [comment]
고맙습니다.
