### ISSUE TITLE
Github에서 웹페이지 제작

### ISSUE THREAD

**Issue by pch0789** [codingeverybody/codingyahac#30]
처음에 강의들을때 만든 web1 은 잘 만들었어요 그런데 이제 제가 다시 만들려고 만들었는데 똑같은 방식으로 그런데 계속 안만들어지네요.... 삭제하고 다시만들고 해봤는데도 안되요 ㅠ
원래 맨 아래화면처럼 나와야되는건데.... ㅠㅠ 왜 첫번째 사진처럼 뜨는 걸까요 소스코드는 2번째 것 입니다....

![default](https://user-images.githubusercontent.com/35018497/34520905-4e1ca1b4-f0ce-11e7-960d-9a43e54a2e1b.PNG)
![default](https://user-images.githubusercontent.com/35018497/34520906-4e49cbc6-f0ce-11e7-88c9-0ace70d9a089.PNG)
![default](https://user-images.githubusercontent.com/35018497/34520907-4e7a5f52-f0ce-11e7-96b5-e136e5281f35.PNG)

**Comment by Choi-Jae-Young** [comment]
웹브라우저에서 받은 소스와 업로드하신 소스가 다른데 혹시 설정을 잘못하닌게 없나요?
![screenshot from 2018-01-03 22-31-25](https://user-images.githubusercontent.com/32431032/34522501-42c1b22a-f0d6-11e7-93a0-f3102d8a9d00.png)

**Comment by azaraks2** [comment]
ReadMe.md에 기록한 내용은 바뀐게 없는데요.
TWICE.html에 저장한 내용으로 보입니다.
https://pch0789.github.io/TWICE1/TWICE.html

**Comment by pch0789** [comment]
![default](https://user-images.githubusercontent.com/35018497/34548949-60263864-f148-11e7-83a6-eb7deb65e1d5.PNG)
azaraks2 님 감사합니다!! 그게 맞긴하네요!! 근데 저장경로를 ..마스터브랜치로 바꾸는 것 밖에 모르겠는데 ....어떻게 저장경로를 바꿀 수 있을까요? 너무 궁금하네요...

**Comment by azaraks2** [comment]
경로에서 처음 보여질 내용은 파일명 index.html에 남기세요.

**Comment by pch0789** [comment]
azaraks2님 감사합니다!!! :)
