### ISSUE TITLE
php 코드 오류

### ISSUE THREAD

**Issue by dlgockssla** [codingeverybody/codingyahac#306]
1.
![2018-08-03 3 17 09](https://user-images.githubusercontent.com/39184753/43627386-2400789c-9731-11e8-8856-3dcd709a21b9.jpg)
2.
![2018-08-03 3 22 09](https://user-images.githubusercontent.com/39184753/43627391-2db8f6e8-9731-11e8-9a39-2c983349917e.jpg)

1번의 코드로 2번과 같이 li안에 li항목을 짜고싶습니다.
19번째줄부터 28번재줄까지 주석처리하면 정상작동되는데 그러지 않을 시, HTTP ERROR 500란 오류가 뜹니다.
무엇이 문제인지 몇 시간 고민해도 답이 나오질 않아 문의 드립니다.

날도 더우신데 정말 고생이 많으십니다.. 정말 감사하고 존경합니다.

ps)지금 제가 apache를 깔아서 사용중인데 php.ini에서 display_errors를 off에서 on으로 수정했는데 왜 오류의 자세한 내용을 보여주지않는건가요??

**Comment by fermat39** [comment]
안녕하세요

phpinfo()
?>

를 test.php에 저장하고 호출하면 결과가 잘 나오나요?
-----Original Message-----

**Comment by dlgockssla** [comment]
서버에 문제가없는가를 묻고싶은건가요??? 
<php phpinfo(); ?>는 잘 작동될겁니다 지금 밖에있는 상황이라서 해보지는 못했는데 위에 언급한 바와 같이 19번째부터 28번째까지의 코드를 삭제한 후 호출하면 잘 됩니다....
혹시 다른의미에서 말씀하신거면 가능할 때 다시 해보고 말씀드리겠습니다 감사합니다!
