### ISSUE TITLE
프로그래머의 기본기가 궁금합니다.

### ISSUE THREAD

**Issue by lived1024** [codingeverybody/codingyahac#309]
만 31살에 국비지원 훈련받고 프로그래머로 나아가려는 취준생입니다.
평소에 프로그래머에 관심은 많았으나 기본 지식은 하나도 없었고, 현재 코딩야학에서 web1-html&internet 수업만 완강했습니다.
현재 제가 진행하려는 과정은 

 1. 9월에 시작하는 http://www.busanit.ac.kr/lesson/class_view.aspx?id=AD180056  이 강의는 다른 선수학습은 없어도 된다고 말했던 곳이고,
 2. 12월에 시작하는 http://www.kgitbank.co.kr/jobtraining/sub.php?cate_name=%EA%B5%AD%EA%B0%80%EA%B8%B0%EA%B0%84%EC%A0%84%EB%9E%B5%EC%82%B0%EC%97%85%EC%A7%81%EC%A2%85&cate_name_sub=%EB%B6%80%EC%82%B0%EC%A0%90  카테고리중 자바기반 웹 개발자 과정

이렇게 2가지를 보고 있습니다. 이 계열에 관련직종이 너무 많다보니 현재 생각중인 것은 웹 개발자나 앱 개발자를 보고 있구요.

다만 2번의 경우에는 상담중 파이썬, C, JAVA, JSP  각 1달씩 수강후 국비지원 교육에 들어가는 것을 추천해주시더군요.

1번 과정은 프로그래밍 언어는 순수 자바만 진행한다는 특이점이 있구요...

**주위에 IT직종 종사자가 없다보니 학원관계자만의 상담만으로 4달을 수강후 진행할지, 또는 9월에 시작하는 과정을 바로 시작할지 고민이 많네요... 아무래도 제 미래를 결정하는 포인트라 생각되서 이렇게 여쭤봅니다.**

연장선상에 있는 질문이지만 프로그래머라면 기본적으로 갖춰야되는 능력이 있다면 그 능력을 갖춰야 제가 프로그래머로서 제 몫을 다할수 있을것이라 생각되기에 질문하게 되었습니다.

이전의 질문에서 타인에 대한 이해를 대답해주신 감사한 분이 계신데  이번에는 필요한 능력이 궁금합니다. (이전의 글에는 답변이 다시 달리지 않으셔서 ㅎㅎ;;)

**Comment by laftworld** [comment]
지나가다가 글을 남겨봅니다ㅎㅎ... 저도 만 31살에 방황하는 영혼입니다. 
프로그래머라면 기본적으로 갖춰야 하는 능력...
코딩하는걸 좋아하는것 이라고 생각합니다.

기술도 언어도 너무 빨리 바뀌고요. C든 Java든 Python이든, 한두가지만 잘 다루면 나머지는 금방 배워서 쓸 수 있다고 생각합니다. 무엇을 배울 것인가는 별 문제가 되지 않을 듯 하고..

그런데 일은 해도해도 야근에 끝이 없고
좋아해서 시작해도 질려버리도록 일을 하니... 
야근폭탄에도 코딩이 싫어지지 않도록 (좋아하면 더 좋고) 멘탈관리를 하는 능력이 가장 중요하다고 생각해요.

**Comment by lived1024** [comment]
조언 감사합니다. 현재 나이가 나이다보니... 이왕 할꺼 책임감을 가지고 꾸준히 하려고 하는중이죠...
다만 멘탈관리나 다른분이 말씀해주신 타인의 의도를 파악하는 그런 부분은 뭐랄까... 정신적인 부분에 관해서 말씀하신것인데, 전 아예 노베이스로 시작을 하게 되니 기술적인 부분에서 기본기가 특히나 더 궁금합니다. 그래야 저도 어느정도 기본기를 준비하고 국비지원 교육을 받으며 그 내용을 최대한 흡수할 수 있을것 같기에 이렇게 여쭤보네요...

**Comment by fermat39** [comment]
31살이시면 아직 젋습니다! 전 33살부터 IT바닥에서 시작했고 현재 9년차로 
일하고 있습니다.

현재 나이도 있고 가정도 꾸리고 싶고 답답하실거예요... 힘드시겠지만,
할 수 있다, 그리고 기회는 분명히 온다고 꼭!!! 마인드 컨트롤 하셨으면 좋겠어요...

어느 순간에 분명 기회가 올거예요... 저도 우연히 기회가 왔었고... 
계속 공부했고, 또다른 기회가 이어졌었습니다. 지금도 공부하고 있고요... 

무엇보다 열린 마음으로 배운다는 자세를 가지셨으면 합니다!!!
네트워크 활동도 하셨으면 좋겠습니다. 인연이 곧 좋은 기회가 될 수 있습니다!

**Comment by lived1024** [comment]
@fermat39 댓글 감사합니다. 다만, 혹시 코딩에 대해서 노베이스로 시작하게 되셨던 건가요? 만으로 31살이라 33살이라 보시면 되고... 쌩초보? 라고 볼수 있는 상황에서 할수 있는한 최대한의 노력을 하려고 생각중입니다. 다만 늦은 시작인데 제로베이스라 어느정도 기본기를 갖추지 않으면 안될것 같다는 압박감이 있어서 계속 우왕좌왕하게 되네요...

**Comment by yoobato** [comment]
@lived1024 제가 개인적으로 되게 좋아하는 분인데, 이 분 글 한 번 읽어보시면 조금 도움이 되지 않을까 싶어요.

https://brunch.co.kr/@imagineer#magazines

**Comment by blackdew** [comment]
비슷한 질문을 올려주신 다른 분들의 글에 조력자 분들이 달아두신 답변이 많이 있습니다. :)
참고하시면 좋을 것 같아요.

https://github.com/codingeverybody/codingyahac/issues?utf8=%E2%9C%93&q=label%3A%22%EC%A7%84%EB%A1%9C+%EC%83%81%EB%8B%B4%22+
