### ISSUE TITLE
웹 관련 질문 있습니다.

### ISSUE THREAD

**Issue by happycs0203** [codingeverybody/codingyahac#31]
1. 웹 서버를 리눅스를 많이 사용하는 이유가 궁금합니다.(window와 의 차이점 )
    보안적으로 장점도 같이 알려주셨으면 좋겠습니다.
2. 톰켓을 사용하면서 많은 사람들 20명이상이 들어왔을때 어떻게 해야되는지 궁금합니다.
3. 회사에서 Restful API를 많이 사용하는 이유가 무엇인가요? ( 현업에서의 장점을 알려주셧으면 좋겠습니다. )
4.  게시판 페이징 할 때 MySQL과 Oracle의 차이점이 있다고하는데 어떤 차이점이 있는지 궁금합니다.

**Comment by blackdew** [comment]
1. 여러가지 이유들이 있을 수 있지만, 그 장점들을 한줄로 압축 할 수 있을 것 같습니다. 
 - 오픈소스입니다. 
2. "tomcat 동시 접속자 설정" 정도의 키워드로 검색해 보시면 원하시는 답을 찾을 수 있을 것 같습니다. 
3. REST의 장점을 통해 협업을 위한 상호간의 협의의 내용과 주고 받아야할 정보의 양을 확 줄여주는 것이 핵심 이유입니다. 
    REST의 장점 - https://goo.gl/SmoEkc
4. mysql과 오라클의 차이는 무료와 유료인 것이 가장 큰 것 같아요. :) 물론 대용량 데이터를 처리하는 데에 있어서의 성능과 안정성 등은 오라클이 비교 우위에 있습니다. 게시판 페이징을 할 때 차이가 나는 것이 아니고, 어떤 형태로 데이터를 구성하느냐, 구성된 데이터가 어떤 방식으로 빈번하게 사용되느냐에 따라 쿼리 튜닝이 조금 달라질 것입니다. 이건 같은 제품 내에서도 버전에 따라서 달라지는 부분이어서요. 어떤 차이가 있다고 특정 지어서 답변 드리기는 어려울 것 같아요.

**Comment by egoing** [comment]
이후에 질문하실 때는 질문 하나에 하나의 토픽을 해주시면 더 좋을 것 같다고 건의 드려봅니다. ^^

**Comment by ghdalsrldi** [comment]
4번 내용에 대하여 추가적인 답변을 드리자면
게시판의 페이징일 구현할 때 
**SQL문이 조금 다릅니다.**
mysql은 limit이라는 키워드로 페이지 범위를 정하게 되지만
오라클은 다른 기법을 사용하여 페이지의 범위를 지정하게 됩니다.

**Comment by egoing** [comment]
4번에 대해한 추천 검색어를 드립니다~  
paging oracle vs mysql 

궁금증이 해소가 안된 부분이 있으시면 이슈를 다시 오픈해주셔요 :)
