### ISSUE TITLE
Vmware에서 라즈비안환경 설치가 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by PassionOfStudy** [codingeverybody/codingyahac#310]
안녕하세요~ 

라즈베리파이는 우리가 일반적으로 사용하는 컴퓨터 x86과는 달리 라즈베리파이는 저전력을 목표로한 
ARM아키텍처 기반이라고 하는데요. 아키텍쳐가 다르면 프로그램이 호환이 안된다고합니다.
가상환경으로 잘 알려진 VMware에서 라즈비안 운영체제 설치를 통한 개발환경을 구축하려고하는데요,
Vmware에서 라즈베리파이에 적합한 O.S인 라즈비안환경 설치가 가능한지 궁금합니다.

**Comment by o2-basta** [comment]
x86용 라스비안을 구해서 설치하면 됩니다 ㅎㅎ
https://www.raspberrypi.org/forums/viewtopic.php?t=193734 여기를 참고해 보세요
