### ISSUE TITLE
<img src="사진.jpg">

### ISSUE THREAD

**Issue by SmartKDH3238** [codingeverybody/codingyahac#312]
'''<img src=''BlackArch.jpg">'''

이걸 웹 문서로 만들어서 실행시키니깐 에러가 떠요ㅠㅠ

**Comment by o2-basta** [comment]
이미지 경로가 맞는지 확인해 보세요. 
에러 메세지를 자세히보시면 어떤부분에서 문제가 생겼는지 힌트를 얻으실 수 있어요 ㅎㅎ

**Comment by SmartKDH3238** [comment]
경로는 맞고요, 에러메시지가 아니라.. 캡처해서 보려드리고 싶은데 이미지를 못올려서 뭐라 설명을 못드리겠어요;;

**Comment by SmartKDH3238** [comment]
그 웹페이지를 열면 좌측 상단에 x표시만 떠요ㅠㅠ

**Comment by o2-basta** [comment]
크롬 개발자도구에서 보시면 이미지가 왜 안보이는지 좀더 많은 정보를 알 수 있어요!

**Comment by SmartKDH3238** [comment]
아 넵! 한번 해볼게요

**Comment by SmartKDH3238** [comment]
근데 이건 에러라기 보다는 가끔 사이트 들어가면 이미지 오는 자리가 비어있고 좌측 위에 x자 뜨는 것처럼 되있어서 크롬으로 봐도 안나올거 같아요.. 지금 크롬도 없고요;;

**Comment by SmartKDH3238** [comment]
오늘이 처음이라 너무 서둘렀더니 오타난걸 몰랐어요;; 죄송해요
