### ISSUE TITLE
공부하는 것에 대한 상담을 부탁드리고 싶어요!

### ISSUE THREAD

**Issue by ruripian** [codingeverybody/codingyahac#314]
지금 대학생 2학년으로 재학중인 컴퓨터 공학과 학생입니다!

중학생때부터 컴퓨터에 대해서 관심을 가지고 있었고, 성격이랑 잘 맞을것 같다고 생각되어서 오게 되었는데요, 공부를 하면서 너무나도 재미있고 행복해요. 그런데 최근 고민하는 부분이 생기게 되었고 이를 매일같이 고민해도 명확한 답이 나오지 않고 있어요. 그리고 이 고민에 대해서 물어볼 곳이 없는 상황이라서 이 곳에 오게 되었어요!

제 고민은 무엇을 공부해야 해야할지 잘 모르겠다는 것이에요.
막연하게 가상현실에 관심이 있고 뭔가 만들어보고 싶다는 생각은 있지만 막상 할 수 있는것이 별로 없다는 생각이 들어요.
학교에서 공부하는  c언어나 c++같은 언어는 꾸준히 복습은 하고 있어도 이런 언어로 무엇을 할 수 있는지도 모르겠고요..
프로젝트를 만들어보라는 다른 교수님의 조언을 받고 만들려고 했었는데 명확한 주제 없이 잠깐잠깐 만들다보니 제가 만족할만한 결과가 나오지 않는것 같아요. ㅠㅠ
뭔가 이것저것 해보고 싶은 욕심이 많아서 시선을 자꾸 옮기는 바람에 집중해서 무언가 하지 못하는것 같아요.
음음 아! 그리고 컴퓨터 코딩에는 많은 흥미와 재미를 느끼는데, 하드웨어와 관련된 부분은 영 흥미가 가질 않아요.. 그런데 이 하드웨어에  관한 지식이 저에게 필요한지 잘 모르겠어요 저는 소프트웨어를 다루고 싶은데 하드웨어에 관한 지식이 필요할까요?

뭔가 길게 끄적인것 같네요 헤헷 
좋은 하루 보내세요!

**Comment by o2-basta** [comment]
음... 뭔가 약간 공감이 가기도 하네요.
일단 하드웨어가 흥미가 없으면 필요없다고 보는게 맞아요. 요새는 클라우드서비스도 좋아요. 
일단 고민하시는 부분은 다른사람들은 소프트웨어만 하지 않고 하드웨어도 하고, 다른사람은 코딩만 하지 않고 프로젝트도 하는데, 나는 흥미가 없다는 그런거 같아요. 
그런것이라면 아주 정상적인거 같아요. 왜냐면 사람들은 모두 상대적이기때문이에요. 우리가 보기에 하드웨어프로그래밍을 하는사람이라고 해도, 직접 PCB를 제작하는 사람보단 덜 하드웨어 적이고, 그사람도 칩을 설계하는 사람보단 덜 하드웨어 적이에요. 칩보다는 전자공학을 하는 사람들이 하드웨어적이고, 그보다는 물리학을 하는사람이 더 비교될수 있을거 같아요. 
이런것들은 그저 그렇다고 이해하는게 중요할거 같아요. 그렇다고 생각하건 안하건 그런것들은 그렇습니다. 
프로젝트를 하는 사람들도 있어요. 뚝딱뚝딱 무언가를 만들어 내지요. 하지만 어떤사람들은 그안에 있는 내용중에 한부분만 만드는데도 잼있고, 시간을 다 쓰게 됩니다. 무슨 차이일까요? 
바로 맥락적으로 다른 영역에 있다고 보시면 될거 같아요. 
의사들은 환자들을 치료하지만, 환자를 돌보는것은 간호사들이 더 잘해요. 환자는 둘다 필요하죠. 
개발에서 소프트웨어도 필요하고 하드웨어도 필요하죠. 개발자들은 맥락적으로 다른 영역에서 자기의 할일을 하는거죠. 재미없는 일이 있다는것은 잼있는 부분이 도드라지게 나올 수 있다는것이죠. 그게 어떤건지 안다는게 가장 중요할거 같아요. 
평생 남들의 코딩을 위해서 프로그램언어를 만드는 사람이 있어요. 그런사람은 코딩을 하게끔하는 코딩을 하죠. 개발언어에 대한 프로그램을 한다고 할수 있지만, 어떻게 보면 성과없어보이기도 하죠. 이런게 맥락적인 부분이에요. 
불교에서 말하는 화엄처럼 각자 자신의 재미난영역에서 열심히 할때 잘 맞물려 돌아가리라 믿어요. 
남들이 하는것이나 관심1도 없는것에 신경쓰지 마세요. 그런것들이 관심생길때까지 지금 재미난것들에 더 시간을 보내보는게 중요할거 같아요 ㅎㅎ
