### ISSUE TITLE
생활코딩web1 강의 수강 후 학우분들의 결과물을 보고싶어요~!

### ISSUE THREAD

**Issue by leehaobit** [codingeverybody/codingyahac#315]
프로젝트 하시는 분들 결과물 보고싶은데, 볼수있는 방법이 있을까요? 
아니면 생활코딩 수업 완료후 웹사이트 만드신 분들 거 보고싶은데 볼수없을까요?

web1을 수강 후 내가 뭘 만들 수 있을지 감이 안잡혀서
다른 분들이 어떤식으로 만드시는 지 보고싶어요~!

**Comment by o2-basta** [comment]
각자 나름의 결과물을 만드시는거 같아요. 
프로젝트를 하시는 분들을 살펴보시면 힌드를 얻으실수 있을거 같아요. 
코딩야학을 같이 한다고 해서 모두 처음 코딩을 하시는 분들은 아니어서 난이도는 제각각일거 같아요. 
그리고 프로젝트 내용을  따로 모아두진 않은거 같은데, 그리 중요하지 않다고 생각합니다. 남들이 한것이라서요 ㅎㅎ
남들이 한것을 보면 남들처럼 할 수 있지만 내가 만들어낸것은 아니에요. 내걸 만들어야 내가 할 수 있게 됩니다. 이상한말처럼 들리지만, 사실이에요.

**Comment by leehaobit** [comment]
ㅎ넵! 나 나름대로의 내것을 만들자! 알겠습니다! 일단 더 배워야겠어요ㅎㅎ

**Comment by egoing** [comment]
@leehaobit 님 아래 페이지 하단에 가보시면 학우들이 만든 웹사이트가 등록 되어 있답니다. 
https://opentutorials.org/course/3084/18891

^^

**Comment by leehaobit** [comment]
@egoing 오홋!! 감사합니다!! 이고잉님 짜응~!!
