### ISSUE TITLE
이런 문의도 답변이 가능한지요?

### ISSUE THREAD

**Issue by JunCheol** [codingeverybody/codingyahac#32]
생활코딩을 공부하면서 정보처리사 자격을 취득하고자 고민하고 있는데요? 당연 이제 시작인데 쓸데없는 꿈인것 같기도 하고 조언을 구하고자.

- 학점은행제를 통해 열심히하면 내년에 자격조건을 갖출수 있음.
- 저는 개인적인 프로젝트가 있습니다. 이꿈을 이루기위해서 
- 공부한 내용을 실제 개발자가 되어서 배우는 과정이 필요할듯함.
- 엔지니어로 취업할려면 자격이 필요한지요?

불필요한 질문이면 삭제하도록 하겠습니다.
감사합니다.

**Comment by egoing** [comment]
불필요하지 않습니다. 아주 좋은 질문이예요. 

자격증은 어떤 일을 하시나냐에 따라서 중요할수도 있고, 아닐수도 있습니다. 예를들어 정부 프로젝트에 참여하는 회사라면 구성원들의 자격증을 중요하게 봅니다. 하지만 자체적인 서비스를 만드는 회사라고 한다면 자격증은 참고를 많이 하지 않습니다. 오히려 자기 혼자서 진행한 프로젝트가 있는가? 또 github이나 stackoverflow와 같은 커뮤니티에서 얼마나 활동하고 있나? 이런 부분들을 더 중요하게 볼 수 있습니다. 저는 자격증을 위해서 공부를 하는 것 보다, 공부를하고 실무를 하다보니 자격증에도 도전해서 어렵지 않게 자격을 따는 것이 더 좋은 방향이라는 사견입니다. 자격증을 목표로 공부하면 공부만 너무 많이하고, 사용하지 않아서 머리속이 너무 복잡해서 아무것도 할 수 없을지도 몰라요.

**Comment by JunCheol** [comment]
답변 감사합니다.
제가 Atom 상단 메뉴바를 없애고 나서 원복이 안되네요. 방법좀 가르쳐주세요 ㅎㅎ 넘 감사합니다.

2018. 1. 4. 오전 12:42에 "egoing" <notifications@github.com>님이 작성:

**Comment by egoing** [comment]
추천 검색어 : atom menu show
해결책 : 제 기억으로는 alt 키를 누르면 나오는 것으로 기억해요.
건의 사항 : 하나의 질문에는 하나의 주제로 해주시면 더 좋을 것 같아요. :)

2018-01-04 0:52 GMT+09:00 JunCheol <notifications@github.com>:
