### ISSUE TITLE
코드이그나이터에서 view 페이지내의 php 소스 분리시키는 방법

### ISSUE THREAD

**Issue by DeuklyoungKo** [codingeverybody/codingyahac#321]
안녕하세요.

저는 php개발자로 근무하다가 휴식기를 가지면서
이고잉님 코드이크나이터 수업 다 듣고 실습하고 있는데요.

강의하실 때 보면  view 페이지 단에 php 소스를 중간중간에 섞어서 사용하시는데요. 보통 실무에서도 그렇게 사용하시는지 궁금합니다.

저같은 경우에는 일반적인 경우 php값으로 제어해야하는 view 부분을 
별도로 javascript파일을 만들어서 해당 javascript파일에 php값을 전달해서 
javascript로 view단을 제어하거든요.

그러면 나중에 디자인이 수정되서 퍼블리셔가 해당 페이지를 수정해도 php소스를 건들일 일이 없어서 문제가 되는 경우가 적었습니다.

그러니까 html소스와 php부분 소스를 분리해서 사용하는 일반적인 방법이나 많이 사용하고 있는 방법이 있는지 문의드립니다.

방법은 여러가지가 있을 것 같은데요. 가장 바람직한 방법이 어떤 것인지 궁금해서요.
관련 글 있다면 단순히 링크만 알려주셔도 감사하겠습니다.

**Comment by smartbos** [comment]
'HTML을 시작하기 전에 모든 데이터 처리를 끝낸다' 라고 생각하시면 쉬우실 것 같아요.

제가 쓴 글 중에 [PHP 예제로 알아보는 MVC 패턴](https://medium.com/@smartbosslee/php-%EC%98%88%EC%A0%9C%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-mvc-%ED%8C%A8%ED%84%B4-1628b47b1b04) 라는 글이 있는데, 도움이 될 수 있을 것 같아요.

**Comment by DeuklyoungKo** [comment]
답변 감사 드립니다.

이전에 봤던 글이네요.
그 때는 그냥 그런가 보다 하고 한번 읽고 말았는데
코드이그나이터를 익히고 나니 설명하시는 MVC모델이 좀 더 쉽게 이해되네요.

제가 문의한 질문에는 해답이 안되었지만
view단에서 이 정도 php코딩( if문이나 foreach문 정도)과 html 코딩을 섞어 쓴는 것은 무난하다고 이해하도록 하겠습니다.

감사합니다.
