### ISSUE TITLE
띄어쓰기, 페이지 구분 등

### ISSUE THREAD

**Issue by Yoon-1** [codingeverybody/codingyahac#330]
1. 아톰으로 파이썬 프로그램할 땐 명령어 입력 후 적당하게 "Tap"이 들어가서 예쁘게 구성되던데
  HTTP에는 그런 기능 적용안되나요?
2. 홈페이지는 만들었는데 화면이 하나라 영 보기 안좋네요. 그림으로 그린 것 처럼 Web칸, list칸, 내용칸 따로 구분하려면 어떻게 해야하죠?
3. index를 home으로 만들어서 집그림을 누르면 돌아가도록 하고 싶은데 그림 넣는 법, 링크 거는 법 좀 부탁합니다.

**Comment by o2-basta** [comment]
1. HTTP는 규약이라서 web contents보낼때 두줄 빈칸으로 보내는등의 엄격한 룰이 있어요. 말씀하시는 부분은 HTML인거 같은데, HTML의 내용은 띄어쓰기와는 상관없어도 됩니다. 그렇지만 HTML태그에 따라서 보기좋게 페이지의 내용을 정리해주는 툴이 있으니 찾아서 사용해 보세요
2. 따로 구분하려면 구분해서 나눠주어야 합니다. 구조적으로 나눈다고 해도 보기좋게 하려면 CSS를 다뤄서 내용을 적당하게 배치하는게 좋을거 같습니다. 
3. 링크를 걸고 그림을 넣는것은 코딩야학을 보시면 됩니다 ㅎㅎ

**Comment by Yoon-1** [comment]
감사합니다.
