### ISSUE TITLE
Github에 올린 파일을 여는데 사진이 뜨지 않아요~

### ISSUE THREAD

**Issue by leehaobit** [codingeverybody/codingyahac#333]
<h1><깃텁에서 열어본 파일></h1><br>

![default](https://user-images.githubusercontent.com/42068379/43676646-ed2bf968-982f-11e8-80aa-5bf4e4efb4ba.PNG)

<h1><직접 폴더에서 열어본 파일></h1><br>

![default](https://user-images.githubusercontent.com/42068379/43676647-ed62a878-982f-11e8-9c06-0d3fd9522bcc.PNG)

<br>
<br>

Q. 왜 사진이 안뜨는 건가요? 뭘 빼먹은 건지 알려주세요;ㅁ;
<br>
<br>

**Comment by chul526** [comment]
안녕하세요...  원인은 모르겠구요... 일단 임시 해결 책은 찾았어요
Issue 에 사진을 붙여넣기 (Ctrl+C, Ctril+V)하셔서 우클릭 하시고 링크를 사용하시면 
바로 뜨네요.... ㅠㅠ 
원인 알고 계신분 있으시면 언제든지 알려주세요....

**Comment by leehaobit** [comment]
@chul526 님 감사합니다ㅜ아직 해결못했어요! 게다가 github로 웹페이지 여는 방법도 까먹었어요...어디서 열었는지...이런..흑

**Comment by blackdew** [comment]
png 확장자 명이 대문자로 되어있네요. 
https://leehaobit.github.io/web1/coding.PNG

코드상에서 소문자로 되어있는데요. 
대문자로 고쳐주시면 동작할 거에요 :)
```
<img src="coding.png" width="30%" align="middle">
<img src="coding.PNG" width="30%" align="middle">
```

**Comment by leehaobit** [comment]
@blackdew 감사합니다! 확인해보겠습니다^_^!
