### ISSUE TITLE
코드이그나이터 Form Helper 사용에 관한 문의 외 기타

### ISSUE THREAD

**Issue by DeuklyoungKo** [codingeverybody/codingyahac#336]
안녕하세요.

전 주로 클래식 ASP나 PHP 프로그래머로 일했던 프로그램머 입니다. 프레임웤이나 MVC모델 같은 것은 사용을 안했었습니다.
휴식기를 가지고 이고잉님 코드이그나이터 동영상 강의 실습 중인데요.
password_hash 함수 알아보다가 Form Helper 라는 것이 있는 것을 알게 되었습니다.

인터넷을 찾아보니 형식은 다르지만 다른 웹서버 언어들도 다들 지원하고 있는 것으로 파악이 되서요.

1. Form Helper 사용을 권장하는지 문의드립니다.

2. Form Helper 를 사용하는 것을 권장하신다면 우려되는 부분이 퍼블리셔(프런트앤드 개발자)도 이 부분을 어느정도 이해 해야 할 것 같은데 보통 퍼블리셔 들도 Form Helper 부분을 알고 있나요? 아니면 이부분은 온전히 서버개발자의 몫인가요?

3. 실작업시 최대한 html코드와 php소스를 안섞으려고 최대한 노력해서 작업을 해 왔는데, 요즘 전반적인 추세가 html 코드와 php소스를 섞어쓰는 것을 안꺼리는 추세인가요?

일반적인 추세가 궁금해서 드리는 질문입니다.

회사에서 웹개발 작업 시 프레임웤이나 MVC 모델 같은 것 사용 안해도 별다른 지장이 없어 사용을 안하고 있었습니다. 확실히 파악이 안된 소스를 편리하다는 이유만으로 가져다 사용하기에는 오류가 발생했을 때 재빠르게 대처를 해야 하는데 부담이 많이 되서요. 요즘에는 그런 부분들이 제가 잘못한 것은 아닌가 하는 후회가 됩니다.

혹시 관련해서 읽어볼만한 글이 있을 까요?
책이나 블로그나, 웹개발 방식에 대한 변화를 파악해 볼 수 있을 만한 것이요.

그리고
이고잉님 코드이그나이터 강의 학습 끝나면 제 개인 사이트 하나 만들어보고,
라라벨 공부를 해 볼지 아니면 코드이그나이터를 더 심화 학습할지 고민 중인데
어떤 것이 더 좋을지 문의드립니다.

**Comment by smartbos** [comment]
1. 권장하지 않습니다. 크게 편리한 것도 아니고, 협업에도 별 도움이 안된다고 생각합니다.
2. 코드이그나이터 폼 헬퍼는 코드이그나이터에만 있는 기능이므로, 퍼블리셔가 알고 있을 가능성은 매우 낮습니다.
3. 실 작업시 HTML과 PHP는 최대한 안섞는게 추세입니다. 화면 출력에 필요한 조건문, 반복문 정도 외엔 안섞는 것을 권장합니다.

아래 자료들을 참고하시면 도움이 되실 겁니다.
[(웹) PHP The Right Way](https://modernpug.github.io/php-the-right-way/)
[(도서) Modern PHP](http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=68414290)
[(도서) 바쁜 팀장님 대신 알려주는 신입 PHP 개발자 안내서](https://ridibooks.com/v2/Detail?id=3166000001&_s=search&_q=%EB%B0%94%EC%81%9C%20%ED%8C%80%EC%9E%A5%EB%8B%98)

**Comment by DeuklyoungKo** [comment]
답변 감사합니다.

Form Helper 사용을 권장안하다는 말을 들으니 안심이 되네요. ㅎㅎ.

참고자료 챙겨 보도록 하겠습니다.
