### ISSUE TITLE
Database : 맴버관리 및 이벤트 운영을 위한 DB를 구축하고 싶은데요

### ISSUE THREAD

**Issue by dodut** [codingeverybody/codingyahac#34]
맴버관련 정보는 지금 구글시트로 약 일만건이 있습니다. 
행사할때마다 100여명이 신청해주시는데, 신청인원 및 참가인원을 모두 db를 통해서 관리하고 싶어요.!
온라인 상으로 구축할 수 있는 DB가 있을까 궁금합니다. 
ㅠㅠ

**Comment by smartbos** [comment]
기획이 필요한 시점이군요~ 
'관리하고 싶다'를 조금 더 구체적으로 표현해주실 수 있을까요? 원하는 것이 더 명확해질 수록 도구를 찾거나 만들기 수월해집니다. 예를 들어 아래와 같이 '누가' '어떤 행위를' 할 수 있다 식으로 표현하면 필요한 기능을 찾아내기 수월해집니다.
- 관리자로서 웹브라우저로 행사를 입력할 수 있다
- 관리자로서 웹브라우저로 행사 목록을 조회할 수 있다
- 관리자로서 웹브라우저로 행사 신청인원를 입력하고 조회할 수 있다
