### ISSUE TITLE
[JAVA/C#]접근제어자에 대해 질문 있습니다.

### ISSUE THREAD

**Issue by andole87** [codingeverybody/codingyahac#340]
public 클래스를 인스턴스화 한 뒤에도 private 멤버에는 접근할 수 없는 건가요? 그렇다면 private와 public 작동 원리가 궁금합니다.
`public class Example{`
`public string A  `
`private string B  `
`}`  

`public void Main(string[] args){  `
`Example exp  = new Example();  `
`exp1.A = "Hello";  `
`exp1.B = "World!"; //컴파일 에러  `
`}`

제 생각으로는 클래스를 인스턴스화 했다면 현재 바이너리 영역(Main)에 들어올 것 같은데 에러가 나는 걸 보니 아닌 것 같아요. 
private클래스는 외부에서 인스턴스화 할 수 없고, private 멤버들은 Main영역에서 get;set;할 수 없다면.. 왜 필요한지 잘 모르겠어요.
OOP에서는 private를 권장하던데 막상 public만 쓰고 있어서요..
private한정자와 public한정자의 쓰임새에 대해 간략히 예를 들어 주시면 감사하겠습니다.

**Comment by yoobato** [comment]
여러 이유가 있겠지만, 가장 이해가 빠른 세가지 이유에 대해 설명해 드리겠습니다.

우선, 말씀하신 것처럼 ```public```은 외부에서 자유롭게 접근할 수 있고, ```private```은 클래스 내부에서만 사용할 수 있는 접근제어자입니다.

1. 혼자서 코딩을 할 때는 크게 의미를 느끼시지 않을 수도 있지만, 여러 개발자가 협업하는 상황에서는 ```private```이 필요합니다. 만약, 내가 만든 어떤 클래스의 멤버 변수가 외부에서 함부로 변경하면 안되는 변수인데, 이를 ```public```으로 선언하면, 다른 개발자가 이 클래스를 객체로 인스턴스화해서 사용할 때, 이 변수의 값을 마음대로 바꿀 수도 있겠지요? 이 때, ```private```으로 선언하면, 이런 실수를 미연에 방지할 수 있습니다.

2. 변수를 읽기 전용 (Readonly) 변수로 만들 때도 유용합니다.  멤버 변수를 ```private```으로 선언한 다음, ```getter```만 ```public```으로 선언하면, 이 변수의 값을 읽을 수만 있고 변경할 수는 없도록 만들 수 있습니다.

아래의 코드를 보시면 이해하는데 도움이 될 것입니다.
```
public class Example {
    private string A;  // A의 값은 Example 클래스 내부에서만 변경 가능

    public string getA() {  // exp.getA() 형태로 사용. (읽기 전용)
        return this.A;
    }
}
```

3. 2번이 ```getter``` 예시라면, 반대로 ```setter```의 경우에도 도움이 됩니다. 예를 들어, 화면 밝기가 0~1 사이라고 합시다. 이 때, 이 밝기 설정을 0~100%로 받고 싶을 수도 있습니다. 즉, 실제로 밝기 값은 0~1 사이의 소수(float, double)로 저장되지만, 입력은 0~100 사이의 퍼센트 값으로 받고 싶은 경우입니다.

마찬가지로 아래의 코드를 보시면 이해하는데 도움이 될 것입니다.
```
public class Example {
    private double brightness;

    // 입력은 정수(%)로 받고, 실제 값은 소수(0~1) 로 가지고 있음
    public void setBrightness(int brightnessPercentage) {
        this.brightness = brightnessPercentage / 100.0;
    }

    // 값은 0~1 사이의 소수지만, 사용자는 정수로 사용할 수 있게 하고 싶음
    public int getBrightness() {
        return (int) this.brightness * 100;
    } 
}
```

**Comment by andole87** [comment]
설명 감사드립니다. 혼자 코딩해서 그랬던 거군요..
