### ISSUE TITLE
CSS 가상클래스 :hover 질문드립니다.

### ISSUE THREAD

**Issue by oovuuv** [codingeverybody/codingyahac#342]
안녕하세요
html 마크업을 하였고 h3 폰트에 :hover 효과를 주고 싶어서 css에 아래와 같이 코드를 작성하였습니다
h3폰트에 마우스오버를 하면 border-bottom이 생기는 효과인데요 
문제는 밑줄이 글자 크기만큼이 아니라 전체 div width 크기만큼 생깁니다
'글자 크기'만큼으로 설정을 하려면 어디를 어떻게 고쳐줘야 할까요
그리고 이런 경우 검색을 해보려면 어떤식으로 검색을 해야할지 추천해주시면 더욱 감사하겠습니다.
만약 이고잉님 같으면 css hover 하고 다음에 뭐라고 검색을 하실지 생각이 떠오르질 않아요..

```
* html 코드
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title></title>
</head>
<body>
<h3 class="theme">표지</h3>
  <h4 class="topic">컬러 여부</h4>
      <input type="radio" name="second" /> 흑백 &nbsp&nbsp
      <input type="radio" name="second" /> 컬러 &nbsp&nbsp
</body>
</html>


* css 코드
.theme h3:hover {
  border-bottom: 3px solid #7bff5b;
}

**Comment by yoobato** [comment]
Heading을 의미하는 ```h3``` 태그가 ```block``` 속성(한 줄을 차지)을 가지고 있기 때문입니다. 이를 ```inline``` 속성(자기가 차지하는 만큼만 차지)으로 바꾸어주시면 됩니다.

즉, CSS 코드에서
```
.theme {
    display: inline;
}
```
을 해주시면 됩니다.

Block과 Inline 속성에 관해서는 http://www.beautifulcss.com/archives/1179 이 글을 참고해보시면 좋을 것 같습니다.

**Comment by oovuuv** [comment]
@yoobato 사정이 있어서 확인이 늦었습니다ㅠㅠ
늦었지만 좋은 답변 감사합니다~
