### ISSUE TITLE
자바스크립트 정규 표현식 질문입니다. 

### ISSUE THREAD

**Issue by bohyeon-n** [codingeverybody/codingyahac#347]
안녕하세요.  
블로그를 생성해주는 프로그램을 만들고 있는데요! 
마크다운 파일을 받아서 html파일로 변환해주고 있습니다 
제가 마크다운 파일을 html파일로 변환 할 때 제목이나 날짜를 마크다운 파일 안에  `+++ <여기!> +++ `여기에 넣어서 받고 있는데요 

```md 
+++ 
title = 'coding every body'
date= '20180805'
category ='issue'
+++
```
이런식으로요 ! 
그런데 이 +++ <>+++ 안에 있는 것들만 빼내고 싶어서 

```js
let string = md.match(/\n*(\+\+\+)\n*([\s\S]+)\n*(\+\+\+)/);
 
```
이런식으로  이 string  변수 안에 저 값들이 들어갈 수 있도록 하였고 
```js
string[2] // 이 안에 저 값들이 들어가도록 하였습니다. 
```
만약에 

```md 
+++ 
title = 'coding every body'
date= '20180805'
category ='issue'
+++

## 안녕하세요 

+++ 
여기서 또 이렇게 +++ 를 써주게 되면 제가 원하는 결과를 얻지 못합니다. 
+++ 
```

**질문**
맨 처음 +++ <> +++ 값만 얻고 싶다면 정규 표현식을 어떤 식으로 고쳐야 할까요? 정규 표현식을 아직 잘 모르는데 그냥 막 쓰고 있습니다 ㅠㅠ 
그럼 답변 부탁드리겠습니다. 감사합니다!

**Comment by yoobato** [comment]
```[\s\S]+``` 이 부분을 정규식에서는 탐욕스럽다(가능한 많이 대응시킨다)고 말합니다.
모든 문자열을 포함시킬 수 있기 때문입니다.

만약 수량을 나타내는 수량자 *, +, ?, {} 등의 뒤에 ```?```를 사용하면, 기본적으로 탐욕스러운 수량자를 탐욕스럽지 않게(가능한 적은 문자들을 대응시킴) 만들 수 있습니다.

따라서, 정규식을 ```let string = md.match(/\n*(\+\+\+)\n*([\s\S]+?)\n*(\+\+\+)/);``` 와 같이 만들면, 첫 번째 부분에만 대응시킬 수 있게 됩니다.

추가적으로, 제가 조금 더 정규식을 다듬어 본다면,
```let string = md.match(/(\+{3})([\s|\S]+?)\1/g);```
이렇게 만들어볼 수 있을 것 같습니다.
