### ISSUE TITLE
이고잉님의 페이스북 이벤트 랜덤추천 사이트와 비슷한것을 만들고싶습니다.

### ISSUE THREAD

**Issue by hw6544** [codingeverybody/codingyahac#35]
어제 라이브방송을 보며 이고잉님의 페이스북 이벤트 랜덤추천사이트를 보고 만들어보고 싶은것이 생겻습니다.

우선 저는 도서사이트 (서점사이트) 에서 어떤 카테고리를 클릭하면 쭉 나오는 도서 정보를 긁어와 정리해서 보여주는 것을 만들고 싶어요.

어제 보니 페이스북 주소를 가지고 파싱해서 원하는것만 끌어오는것 같아서 질문드립니다.

아직 시작도 못한 프로젝트이지만 개인이 해보는 첫 프로젝트라 막막한대
필요해보이는 기술과 강의가 있다면 추천 부탁드립니다!
 
아 그리고 저는 정리된 내용을 엑셀파일로 빼보고 싶은대 가능할까요?

**Comment by cyppi** [comment]
서점사이트(혹은 다른 웹페이지등)에서 정보를 주르륵 가져오는것은 보통 크롤링이라고 합니다. 
카테고리에서 나오는 도서정보를 가지고 온다면, 아마도 카테고리별로 나오는 책들의 목록과 각각의 책에 대한 정보를 가지고 오는 두부분으로 나누어 작업하면 될거 같아요.
만약 사이트에서 로그인정보 없이 가져올수 있다면 wget, curl 등의 명령어로 가져오거나, 프로그래밍으로 가져올수 있어요. 로그인을 해야하거나 하는경우라면 웹브라우저를 흉내내서 일괄적으로 가져오도록 하는 프로그램(셀레니움 같은것들)을 쓰면 될거 같아요같아요. 
그렇게 가져온 정보들은 보통 데이터베이스에 넣게 됩니다. 

그러고 나면 저장된 정보를 입맛에 맞게 조합해서 보여줄 수 있어요. 

물론 엑셀로 정리해서 출력할수도 있구요 ㅎㅎ

멋진출발보다는 일단 해보고 알아가는 그런 프로젝트가 되길 바래요

**Comment by smartbos** [comment]
알라딘이나 네이버 책 같은 서비스들은 도서 정보를 외부에서 가져다 쓸 수 있도록 제공해주기도 합니다.
https://www.apistore.co.kr/generalApi/generalApiView.do?general_service_seq=72
https://developers.naver.com/docs/search/book/

**Comment by hw6544** [comment]
안녕하세요 고마운 답변 감사합니다.
조금더 여쭙고 싶은것이 있어서 연락드립니다 ㅎ
크롤링이란것이 파이썬으로만 가능한 것인가요?
 
 
-----Original Message-----

**Comment by azaraks2** [comment]
뭘로 하시려는 건가요? 메이저 언어는 크롤러 모듈이 한두개씩은 다 있습니다.

**Comment by hw6544** [comment]
저는 자바입니다!

**Comment by azaraks2** [comment]
https://github.com/search?l=Java&o=desc&q=web+crawler&s=stars&type=Repositories
별 많은 애들 문서 읽어보시고 쓸지 말지 결정하시면 될 것 같습니다.

**Comment by hw6544** [comment]
감사합니다 !
