### ISSUE TITLE
Node.js - Socket.io 관련 질문

### ISSUE THREAD

**Issue by ParkHongUK** [codingeverybody/codingyahac#352]
안녕하세요.

socket.io emit method 관련해서 질문드립니다.

서버와 클라이언트가 웹소켓으로 연결된 상태에서,

서버에서 '특정' 클라이언트에만 메시지를 보내고 싶은데, 어떻게 구현하면 될까요?

현재는 브로드캐스트 때문에, 전체적으로 다 퍼져나가게 해놨습니다... 도움 부탁드립니다.

**Comment by egoing** [comment]
socket.io는 제가 사용해보진 못했습니다만,
firebase realtime database와 같은 기술을 이용하시면 접속한 사용자에게 데이터를 푸쉬할 수 있고,
https://onesignal.com/ 과 같은 서비스를 이용하면 특정사용자에게 노티를 푸쉬할수도 있습니다.

**Comment by swon223** [comment]
여러 방법이 있는데요
소켓 주소를 활용해서 이 주소에 접속한 소켓끼리만 통신이 가능할 수 있고(namespace), 룸이란 개념이 있어서 스트링 이름으로 된 룸에 접속한 소켓만 통신할 수도 있습니다~

소켓IO공식문서입니다
https://socket.io/docs/rooms-and-namespaces/
