### ISSUE TITLE
[안드로이드] 원격 서버에 데이터 저장하고 불러오기

### ISSUE THREAD

**Issue by Diocto** [codingeverybody/codingyahac#353]
안녕하세요. 간단한 단어장 앱을 만들고 있습니다.

지금 현재 SQLite를 이용해서 단어를 저장하고 불러오는 기능을 개발했는데요.  저는 다음과 같은 기능을 위해 외부 서버와 연동시키고 싶습니다.

1. 사용자가 저장한 단어들을 종합해서 망각 패턴 분석 등의 데이터 분석
2. 클라이언트가 단어장 사진을 찍으면 이미지를 분석해서 [단어:뜻]으로 파싱해서 저장해주는 기능
3. 사용자가 저장한 단어들을 백업

찾아보니 보안상 이유때문에 DB와의 연동을 막았다고 들었는데요. 그럼 안드로이드 - PHP - JSON - 서버 형태로 통신을 하는 방법이 일반적인 방법이라고 들었는데 이 방법이 통상적이고 상용 어플리케이션을 개발할 때도 주로 사용되는 방법인가요?

**Comment by yoobato** [comment]
말씀하신 구조를 보통 ```서버 - 클라이언트``` 구조라고 부릅니다.

클라이언트는 서버에 ```요청(Request)```을 하는 주체이고, 서버는 클라이언트의 ```요청```을 받아 처리하고, ```응답(Response)```하는 역할을 하게 됩니다.

질문을 이 구조에 맞춰 조금 바꾸어 보면, ```클라이언트```는 ```안드로이드 앱```이고, ```서버```는  ```PHP```로 개발되었으며, ```JSON``` 포맷을 사용하여 통신하는 구조라고 할 수 있습니다.

말씀주신것처럼, 이러한 방법은 상용 어플리케이션을 개발할 때 주로 사용되는 방법입니다. 물론, 클라이언트는 안드로으이드앱 뿐만 아니라 iOS 앱, PC 프로그램 등등 다른 것일 수도 있고, 서버 또한 꼭 PHP가 아니라 Python, JSP 등 개발할 수 있는 방법이 다양하지요. 데이터를 주고받는 형식 또한, JSON 외에도 XML 등을 사용할 수도 있습니다.

**Comment by yoobato** [comment]
1. 사용자가 저장한 단어들을 종합해서 망각 패턴 분석 등의 데이터 분석
2. 클라이언트가 단어장 사진을 찍으면 이미지를 분석해서 [단어:뜻]으로 파싱해서 저장해주는 기능
3. 사용자가 저장한 단어들을 백업

위에서 1~2번은 안드로이드 앱 내에서도 처리할 수 있지만, 3번은 서버를 이용해야겠네요 😄

**Comment by Diocto** [comment]
@yoobato 
친절한 답변 감사합니다! 이번 기회에 서버 사이드 스크립트 언어를 배워서 적용해 보겠습니다.
