### ISSUE TITLE
[블록체인/안드로이드] 블록체인 기반 안드로이드 앱을 개발하려고 합니다.

### ISSUE THREAD

**Issue by s2ungja2** [codingeverybody/codingyahac#357]
어떤 앱이나 서비스를 배포해보는것이 처음이라, 구조부터 많이 막히네요 ..
DB라는것도 학부생시절이나 정보처리기사 취득시에 다뤄본 DML DDL DCL정도가 전부입니다 ㅠㅠ
구조를 어떤식으로 해야 할지 여쭤보고싶은데,
현재 안드로이드를 클라이언트로, 클라우드 서버에 DB와 프라이빗 넷 geth를 같이 올려서 작업을 하려고 합니다.
이렇게 작업하는게 효율적인 서버/클라이언트 구조일까요 ?

DB의 데이터를 JSON으로 PHP서버에 보내서, 안드로이드에서 읽어올 수 있도록 하는 연동과정은 해결이 되었고, geth의 지갑정보/지갑비밀번호등을 DB에 저장하고싶습니다.
DB는 Mysql을 사용중인데, geth와 Mysql간의 연동은 어떤식으로 해야할지 참고할만한 문서나 자료같은게 있을까요 ?

**Comment by studroid** [comment]
우선 전체적인 DApp의 구조와 개발 환경을 이해하기 위해, [CryptoZombies](https://cryptozombies.io/)를 통해 학습을 먼저 진행해보시면 좋을 듯합니다.

일반적으로 DB에 개인키나 지갑에 관한 정보를 저장하는 것은 바람직한 방법은 아닙니다.
블록체인 기반 서비스를 사용할 때 Mysql과 같은 중앙화 DB는 검색 등을 빠르게 하기 위한 인덱싱 용도로 사용하고, 실제 데이터는 블록체인에 기록하는 방식을 많이 씁니다.

아래 글을 한번 살짝 읽어보시고 감을 잡아보시면 좋을 듯합니다 :)
https://medium.com/loom-network-korean/개발자를-위한-loom-sdk-번개처럼-빠른-dapp-성능을-위한-인덱싱-계층의-사용-92cec91e1667
