### ISSUE TITLE
django : 모임 홈페이지 제작 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by pibrizo** [codingeverybody/codingyahac#36]
안녕하세요 

웹 애플리케이션 만들기 수업이랑 파이썬 수업을 듣고 간단하게 제가 참여하는 독서모임에서 사용할 수 있도록 홈페이지를 제작하려고 이번 야학을 신청했습니다. 책 별로 게시판(혹은 댓글을 달 수 있도록)이 있고(Board), 구성원이 누가누가 있다(Team), 모임의 목적은 무엇이다(About)로 구성된 홈페이지를 만들고 싶습니다. 그래서 메인페이지 상단에는 About, Team, Board 로 메뉴를 만들어 들어갈 수 있게끔 만들어진 기본적인 홈페이지를 구상하고 있습니다.

장고가 편하다고 해서 장고를 통해 페이지를 제작하려고 하고 장고 튜토리얼, 인스타그램 클론 등을 해보면서 대충 장고가 어떤 식으로 돌아가는지만 아는 상태인데요,

드리고 싶었던 질문은 일반적으로 장고로 홈페이지를 제작할 때 초기 화면(메인 페이지? 홈?)을 위해서 따로 장고 앱을 생성해서 하는지 입니다. 제가 인터넷에서 찾아본 초보를 위한 홈페이지 제작은 대부분 블로그를 만드는 걸 예시로 들고 있고 들어가자마자 바로 포스트가 보이는 형태인데, 저는 메인페이지가 따로 있었으면 합니다. 예를 들면 제가 방금 djangosites.com에서 찾은

https://www.presscleaners.com/ 나 https://wearecnxion.com/,

더 간단하게는 https://www.cloudstormllc.com/

같은 사이트를 들 수 있을 것 같습니다.  제가 만들고자 하는 사이트는 About, Team, Books 이 정도의 메뉴만 필요하기 때문에 세 번째 사이트처럼 아주 간단하게 만들어도 좋을 것 같습니다.

이런 사이트들이 정말 많은 것 같은데... 아니면 이 메인 부분은 HTML의 영역인가요? 질문을 쓰고 보니 제가 장고를 제대로 이해를 못하고 있어서 중언부언하고 질문이 이상하다는 생각이 드네요.. 어쨌든 핵심적인 질문은 보통 따로 프로젝트 속에 장고 앱을 만들어서 메인페이지를 만드는지입니다ㅎㅎ;;

감사합니다!

**Comment by smartbos** [comment]
https://tutorial.djangogirls.org/ko/django_views/

위 링크를 참고하시면 도움이 될 것 같습니다.
직접 읽으실것으로 예상되지만 요약하면 장고로 html 파일을 불러들여서 출력하는 개념이에요.

**Comment by ghdalsrldi** [comment]
규모에 따라서 달라질 수 있을 것 같아요
규모가 큰 웹사이트라면 각각 앱을 생성하는 방법을 추천드립니다.
하지만 그렇지 않다면 하나의 앱에서 만들어도 충분할 것이라 생각됩니다.

**Comment by cyppi** [comment]
앱을 따로 나누기도 하고 그렇지 않기도 할거 같아요.
메인부분에서는 보통 커다란 이미지들을 걸어놓아서 그닥 의미 없을수도 있지만, 프로그램적으로 가장많은 공을 들어야 하는 전체를 포괄하는 정보를 보여주는 경우도 있어서 코딩이 필요할수도 있어요.
특히나 로그인이 필요한 사이트인데, 권한설정이 다르다거나 하면 제일 첫페이지가 HTML만으로는 어림없어 질수도 있답니다. ㅎㅎㅎㅎ

**Comment by pibrizo** [comment]
모두 감사합니다!
