### ISSUE TITLE
코딩야학 4일차 메일을 읽고 궁금한것이 생겼습니다!

### ISSUE THREAD

**Issue by soheemon** [codingeverybody/codingyahac#360]
안녕하세요
최근 저는 제가 새로 알게된 기술이나 개념을 블로그에 기록하고 있습니다.

자료를 찾느라 고생한 과거의 저를 떠올리며
다른사람에게 도움이 될수있는 글을 쓰고싶었고

자연스럽게 아래와 같은 고민을 하게 되었습니다.

- 다른사람에게 설명하기 위해서
나는 그 개념을 얼마나 잘 이해하고 있어야 할까
- 반드시 설명해야 할 중요한 개념은 무엇이고 그것을 정하는 기준은 무엇일까
- 그 개념들에 대해 설명은 어느정도로 자세히 해야할까

그러다 코딩야학4일차 메일에서 이고잉님의 공부법에 대해 읽게되었고
제 고민에 조언을 얻을수 있을것 같아서 이렇게 질문을 남깁니다!

**Comment by o2-basta** [comment]
이부분은 고잉님이 답변을 달면 좋겠지만, 일단 제가 먼저 답을 달아 보겠습니다 ㅎㅎ

1. 나는 얼마나 잘 알고 있어야 하나? 이건 정답이 없는거 같아요. 물론 많이 알고 있고 관련된 지식도 잘 알고 있으면 좋겠지만, 일단 알고 있는거라도 공유하고, 알려주는게 좋은거 같아요. 사실 지식을 완벽하게 알 수 있는 방법은 없다고 생각하고 있어요. 
2. 반드시 설명해야할 중요개념과 정하는기준은 사람마다 다른거 같아요. 사람마다 중요하다고 여기는 부분이 다르니까요. 이것은 가르쳐 주는사람의 기준에서도 그렇고 배우는 사람에서도 그렇습니다. 그리고, 배우는사람을 특정할 수 없는 상황임을 고려하면 가르쳐주는 사람기준으로 중요하다고 생각하는것을 강조하면 될거 같아요. 그렇게 지식의 주파수가 맞는 사람들에게 지식이 전파될 수 있을거 같아요
3. 어느정도로 자세히설명할지는 학습하는 사람에 따라 달려있는데, 일대일로 알려주는 내용이 아니니까 그저 자세하다고 생각하는 만큼 설명하면 될거 같아요. 그리고 그보다 자세한 내용은 관련 링크를 달아주거나 하는정도면 되지 않을까요? ㅎㅎ

그리고, 고잉님이 강의에 대한 내용을 강의하는 "강의강의"를 하실거 같아요. 그때 한번 고잉님의 강의 방식을 접해보시길 바래요

**Comment by soheemon** [comment]
이슈 클로즈가 늦었네요.. ;-;
답변 감사합니다..!
