### ISSUE TITLE
ATOM 설치 후, 경로 설정 오류 문제

### ISSUE THREAD

**Issue by overexertion** [codingeverybody/codingyahac#362]
![image](https://user-images.githubusercontent.com/42131908/43699242-f828861a-9988-11e8-882d-45947a8ebc59.png)

ENOENT : no such file or directory, 오류가 뜨는데, 경로 설정에 문제 없는데 파일생성이 안됩니다. ㅠㅠ

**Comment by egoing** [comment]
HTML이라는 이름의 디렉토리가 실제로 존재하나요?
