### ISSUE TITLE
jQuery를 이용한 애니메이션을 실행 할때 이미지가 한쪽으로만 커지는 문제점

### ISSUE THREAD

**Issue by FKgk** [codingeverybody/codingyahac#363]
![kakaotalk_20180806_150421615](https://user-images.githubusercontent.com/40608930/43699627-7ffd96ce-998a-11e8-8e91-6ac2f3607613.jpg)
사라지고 있는 별박스 모양이 왼쪽 위쪽을 기준으로 아래와 오른쪽으로만 커지고 있습니다.
원래 크기는 밑에 있는 화살표 모양이구요
('').animate({width:100,height:100}) - 이런식으로 이미지를 커지게 했습니다. 
이미지 가운데를 기준으로 이미지의 크기를 키우고 싶습니다. 어떻게 해야 하나요?

**Comment by yoobato** [comment]
```top```과 ```left``` 속성도 같이 주시면 됩니다.

아래 예제 참고해보세요!

http://jsfiddle.net/Nalum/46pHK/
