### ISSUE TITLE
MySQL 데이터 입력 질문

### ISSUE THREAD

**Issue by Kimeunbok** [codingeverybody/codingyahac#365]
MySQL문에 입력을 하나씩 입력하게 되는데 한꺼번에 받아들이는 방법은 없는지요?

**Comment by ghdalsrldi** [comment]
"bulk insert"을 참고하시면 될 것 같아요

```sql
insert into 테이블명 (컬럼1, 컬럼2) values (값1, 값2), (값3, 값4), (값5, 값6);
```
위와 같은 방법으로 3개의 데이터를 한번에 insert 할 수 있습니다.

**Comment by Kimeunbok** [comment]
감사합니다. 적용해보겠습니다. ^^ 잘 되어야 할텐데....
