### ISSUE TITLE
모바일 카메라 촬영한 사진의 EXIF 정보 가져오기

### ISSUE THREAD

**Issue by yjaquinas** [codingeverybody/codingyahac#367]
모바일에서 촬영한 사진의 EXIF 정보를 받아오려 하는데요,
(https://github.com/exif-js/exif-js/blob/master/exif.js 이 라이브러리를 사용합니다)
아이폰에서 수차례 테스트 해 보면 읽혀 오다가 가끔씩 undefined라고 안 읽히네요.
안드로이드는 아예 못 읽어오구요.

```
.html
<input type="file" accept="image/*" capture="camera" onchange="NewPhotoCaptured(this)">
```
```

.js
function NewPhotoCaptured(captured)
{
  var camera_input = captured.files[0];                         // 카메라가 찍은 사진
  var reader = new FileReader();          // 사진 리더
  reader.onload = function(e)
  {
...
    EXIF.getData(camera_input, function(){camera_orientation = this.exifdata.Orientation;});

    alert('촬영 방향 인덱스: '+camera_orientation);
...
```

아이폰에서 사진 파일 정보가 다 읽혀 들어오기전에 exif정보를 읽으려고 하는걸까요?
안드로이드에서는 아예 안 되던데, 이 github라는 커뮤니티 이용법을 잘 몰라서 라이브버리 제작자분꼐서 따로 안드로이드 아이폰에 관한 메세지를 남기셨는지 잘 모르겠네요. 어디가 문제일까요?

검색해봐도 잘 모르겠어서 질문 남깁니다... 도와주세요!
(질문을 제대로 했는지도 모르겠네요.)

**Comment by ghdalsrldi** [comment]
비동기 처리 문제가 아닐까 의심됩니다.

camera_orientation 라는 변수를 미리 선언한 후 
```javascript
EXIF.getData(camera_input, function(){camera_orientation = this.exifdata.Orientation;});
```
에서 camera_orientation 변수에 데이터를 할당하는것으로 보이는데요
```javascript
```

**Comment by yjaquinas** [comment]
스크랩트 랭귀지는 처음이라, 동기화에 대해 헷갈리는 점이 많네요. function내의 call back function이라 하나요? 이것도 아직 이해하기 전이고...

갤럭시에 기본으로 설치되어있는 인터넷 어플리케이션에서는 안되고, 크롬 어플을 받아서 해보니 되더라구요. 뭐가 문젠지 ㅠ

**Comment by ghdalsrldi** [comment]
>  스크랩트 랭귀지는 처음이라, 동기화에 대해 헷갈리는 점이 많네요. function내의 call back function이라 하나요? 이것도 아직 이해하기 전이고...

callback function(콜백함수) 맞습니다.

> 갤럭시에 기본으로 설치되어있는 인터넷 어플리케이션에서는 안되고, 크롬 어플을 받아서 해보니 되더라구요. 뭐가 문젠지 ㅠ

자바스크립트는 비동기로 처리되기 때문에 브라우저, 상황에 따라 코드가 처리완료되는 순서가 다를 수 있습니다.
