### ISSUE TITLE
php코드를 아래와 같이 작성했는데 ,파일출력이 안됩니다.

### ISSUE THREAD

**Issue by TAEKnical** [codingeverybody/codingyahac#369]
![image](https://user-images.githubusercontent.com/37683734/43718888-0cf3a47e-99c7-11e8-80a3-9132c137109e.png)

동영상대로라면 atom의 왼쪽 목록에 result.txt가 보여야 하는데 실제로 생성되지도 않고, 보이지도 않습니다.  무언가 설정이 필요한가요??

**Comment by yoobato** [comment]
```file_put_content``` 가 아니라 ```file_put_contents``` 입니다. s를 빼먹으셨어요!

http://php.net/manual/en/function.file-put-contents.php
