### ISSUE TITLE
코딩야학은 어느정도까지 알려주시는 건가요?

### ISSUE THREAD

**Issue by kkoma2** [codingeverybody/codingyahac#37]
안녕하세요 저는 이런 분야는 완전 처음 이라서요.  답변해주시면 감사하겠습니다.  
코딩야학에서  어느정도까지  가르쳐 주시려는지 궁금합니다. 코딩야학을 이수하고 나면 관련직종일을 할수있을까요? 아니라면 코딩야학 이후에 어떻게 공부해야할까요?
교육을 이수하면 관련(css,자바스크립트)자격증을 따는일에 도움을 많이 줄까요?
관련자격증은 꼭따야 할까요?

**Comment by cyppi** [comment]
어떤 분야이건 완전 처음이라면, 뭔가 진도를 확인하면서 성과를 확인하는게 도움이될거 같은데, 이때필요한 것이 자격증인거 같아요.
코딩야학에서는 자격증은 없어요. 다만 수료증을 드릴수는 있어요. 
자격증은 남이 자신을 인정해주는것이지만, 그보다 중요한것이 코딩에 대한 감을 얻으면서 자신이 할수 있다고 생각하는 위치에 가는게 좋을거 같아요. 
관련자격증보다는 관련 프로젝트를 많이 경험하시길 추천드립니다 ㅎㅎ

**Comment by kkoma2** [comment]
답변 감사합니다.
