### ISSUE TITLE
Unity 게임과 Facebook과의 연동

### ISSUE THREAD

**Issue by hni1124** [codingeverybody/codingyahac#370]
안녕하세요. 게임 개발을 해서 실제로 런칭을 꿈꾸는 학생입니다.

제 목적은 시중에 나오는 모든 게임들이 그러하듯이 다른 유저와의 점수 비교도 할 수있으며
그에따른 순위가 나오는 리더보드를 만들어서 사용자들에게 보여주고, 제가 그 데이터들을 다룰 수 있도록하는 것 입니다.

리더보드는 요즘 나오는 게임에서 매우 중요한 요소라고 생각하지만 게임을 만드는 법만 알았지 이런 부분에 대해서는 아예 무지한지라 도움을 얻고자 이렇게 요청드립니다...

게임을 FaceBook과 같은 SNS와 연동하는 방법을 인터넷을 통해 찾아보아봐도
로그인 API를 C#과 연동해서 한다. 이정도의 설명이 나와있는 것은 찾아보았지만 제가 원하는 디테일은 없었습니다.

-문제상황
로그인 후 점수 Table을 구성해야하는데, 그 때 로그인한 사용자의 점수를 저장한다고 한다면 로그인 한 A라는 사람에 대한 user_ID의 해쉬값을 제 DB내부의 table에 저장한다고 하더라도, 그 A라는 사람의 정보를 담는 '행'안에 그 사람의 친구들의 점수데이터까지 전부 저장하고,
B라는 사람도 마찬가지로 B의 친구들의 점수데이터를 전부 저장하고 만약에 이렇게 된다면 

너무나 방대한 데이터를 다루게 될 것이고 누가 서로에게 'FB친구'인지도 제 DB를 가지고 계산을 해서 해야 하는 방법밖에 생각이 나질 않습니다. 

그렇지만 현업에서는 이렇게 비효율적으로 일을 처리할 것 같지는 않아서 질문드립니다. 실제 게임 산업에서는 어떻게 이런 데이터를 저장하고 다루는지 궁금합니다. 

1. FB과 같은 SNS와 UNITY를 통한 연동을 할 때 어느 Facebook API를 사용해야 하는지 알고싶습니다.

2. 질문과 답변의 한계로 인해 설명이 길어질 것 같으시다면 연동에 대한 지식이 아예 없는 사람이
어떤 자료를 참고로 해야 SNS와 연동이 가능할지 링크를 첨부해주시면 공부하도록 하겠습니다.

감사합니다.

**Comment by yoobato** [comment]
원래 페이스북 게임을 만들 때, 게임의 점수를 페이스북에 저장(publish)하는 구조였는데, 방금 확인해보니 Scores API가 deprecated 되었네요 ㅠ...

혹시 모르니, 아래 링크들 참고해보시겠어요!?
페이스북 모바일 게임: https://developers.facebook.com/docs/games/mobile
Unity + Facebook: https://developers.facebook.com/docs/unity/gettingstarted
Facebook 연동한 Unity 샘플 게임: https://github.com/facebookarchive/friendsmash-unity (이건 archive 되었네요 ㅠ)

**Comment by studroid** [comment]
간단히 검색해보니, SNS에서 친구 DB를 구현하는 방법은 오래 전 아래 사이트에서 토론이 있었네요 :) 하나의 방법으로 참고하시면 좋을 듯합니다.
http://www.gurubee.net/article/53587

**Comment by hni1124** [comment]
모두 답변 감사드립니다
