### ISSUE TITLE
안드로이드 requestPermissions() 관련 질문입니다.

### ISSUE THREAD

**Issue by ChoMk** [codingeverybody/codingyahac#372]
메인엑티비티에서 requestPermissions()를  호출하는 함수를 만들고 자식 프래그먼트에서 메인엑티비티에 있는 requestPermissions()호출하는 함수를 호출하여 권한을 얻으려고 할 때 구동 단말기에서 권한 요청 팝업 창이 뜨지 않고 바로 onRequestPermissionsResult()(메인 엑티비티에 있는)로 넘어갑니다... 
뭐가 문제일까요.?

public void checkPermissionRead(){
        int readStorageCheck = ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE);
        if(readStorageCheck != PackageManager.PERMISSION_GRANTED){
            if(ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.READ_EXTERNAL_STORAGE)){
                Toast.makeText(this,"외부 메모리 읽기 권한", Toast.LENGTH_LONG).show();
            }else{
                ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.READ_EXTERNAL_STORAGE},READ_CODE);
            }

        }else{

            permissionState[READ_CODE] = true;
        }

    }//읽기 권한
    public void checkPermissionWrite(){
        int writeStorageCheck = ContextCompat.checkSelfPermission(this,Manifest.permission.WRITE_EXTERNAL_STORAGE);
        if(writeStorageCheck != PackageManager.PERMISSION_GRANTED){
            if(ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
                Toast.makeText(this, "외부 메모리 쓰기 권한", Toast.LENGTH_LONG).show();

            }else{
                ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.WRITE_EXTERNAL_STORAGE},WRITE_CODE);

            }
        }else{

            permissionState[WRITE_CODE] = true;
        }
    }//쓰기권한
    public void checkPermissionCamera(){
        int readStorageCheck = ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA);
        if(readStorageCheck != PackageManager.PERMISSION_GRANTED){
            if(ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.CAMERA)){
                Toast.makeText(this,"카메라 권한", Toast.LENGTH_LONG).show();
            }else{
                ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.CAMERA},CAMERA_CODE);

            }
        }else{

            permissionState[CAMERA_CODE] = true;
        }

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if(requestCode == WRITE_CODE){
            if(grantResults.length>0){
                if(grantResults[0] == PackageManager.PERMISSION_GRANTED){
                    //진행
                    permissionState[WRITE_CODE] = true;
                }
            }

        }else if(requestCode == READ_CODE) {
            if (grantResults.length > 0) {
                if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    //진행
                    permissionState[READ_CODE] = true;
                }
            }
        }else if(requestCode == CAMERA_CODE) {
            if (grantResults.length > 0) {
                if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                    permissionState[CAMERA_CODE] = true;

                }
            }
        }
    }

**Comment by yoobato** [comment]
```onRequestPermissionsResult```에서 ```grantResults[0]```이 어떻게 나오는지 알 수 있을까요?

**Comment by ChoMk** [comment]
-1이 나옵니다.

**Comment by yoobato** [comment]
```
시스템이 사용자에게 권한을 허용하도록 요청하면 사용자에게는 시스템에게 해당 권한을 다시 요청하지 말라고 지시할 선택권이 있습니다. 그런 경우, 앱이 해당 권한을 요청하기 위해 requestPermissions()를 사용할 때마다 시스템이 즉시 이 요청을 거부합니다. 시스템은 사용자가 명시적으로 여러분의 요청을 다시 거절했을 때와 동일한 방식으로 onRequestPermissionsResult() 콜백 메서드를 호출하고 PERMISSION_DENIED를 전달합니다. 즉, 여러분이 requestPermissions()를 호출하는 경우, 사용자와의 어떠한 직접적 상호작용이 발생했다고 가정할 수 없습니다.
```

https://developer.android.com/training/permissions/requesting?hl=ko

위 링크 참고해보시면 좋을 것 같아요!

**Comment by yoobato** [comment]
https://gist.github.com/lopspower/01aa324dae5875f27cf9 이것도 도움이 될 것 같아요!

**Comment by yoobato** [comment]
아래는 제가 예전에 만든 앱에서 사용한 권한 관련 코드에요.
권한을 얻을 때까지 계속 체크하는건데, 혹시 필요하실까봐 첨부해드립니다.

```android
private void checkPermissionsIfNeeded() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        Set<String> allPermissions = new HashSet<>();
        allPermissions.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
        allPermissions.add(Manifest.permission.READ_EXTERNAL_STORAGE);
        allPermissions.add(Manifest.permission.CAMERA);
        allPermissions.add(Manifest.permission.RECORD_AUDIO);

        // 필요한 권한
        requiredPermissions.clear();
        for (String permission : allPermissions) {
            if (checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED) {
                requiredPermissions.add(permission);
            }
        }

        if (requiredPermissions.isEmpty()) {
            // 필요한 권한이 없다
            postProcess();
        } else {
            // 권한 요청
            requestPermissions(requiredPermissions.toArray(new String[requiredPermissions.size()]), PERMISSION_REQUEST_CODE);
        }
    } else {
        postProcess();
    }
}

@TargetApi(Build.VERSION_CODES.M)
@Override
public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
    if (requestCode == PERMISSION_REQUEST_CODE) {
        Set<String> grantedPermissions = new HashSet<>();
        final Set<String> shouldReRequestPermissions = new HashSet<>();
        final Set<String> permanentDeniedPermissions = new HashSet<>();

        for (int i = 0; i < grantResults.length; i++) {
            if (grantResults[i] == PackageManager.PERMISSION_GRANTED) {
                // 획득한 권한
                grantedPermissions.add(permissions[i]);
            } else {
                if (shouldShowRequestPermissionRationale(permissions[i])) {
                    // 다시 물어볼 권한
                    shouldReRequestPermissions.add(permissions[i]);
                } else {
                    // '다시 묻지 않음'에 체크하고 거부한 권한 (설정 들어가서 유저가 직접 허용해줘야함)
                    permanentDeniedPermissions.add(permissions[i]);
                }
            }
        }

        if (grantedPermissions.containsAll(requiredPermissions) && requiredPermissions.containsAll(grantedPermissions)) {
            // 모든 권한을 획득함
            postProcess();
        } else if (!shouldReRequestPermissions.isEmpty()) {
            // 다시 물어볼 권한이 있는 경우 => 다시 물어본다.
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    checkPermissionsIfNeeded();
                }
            }, CloudDialog.LENGTH_SHORT);
            new CloudDialog(LogoActivity.this, getString(R.string.dialog_notice_title), getString(R.string.logo_permission_required)).show();
        } else if (!permanentDeniedPermissions.isEmpty()) {
            // 다시 물어볼 권한이 있지만, Never ask again에 체크한 경우 => 앱 설정 Intent를 연다.
            new CloudDialog(LogoActivity.this, getString(R.string.dialog_notice_title), getString(R.string.logo_permission_setting_required), new CloudDialog.SingleButtonClickListener() {
                @Override
                public void onClick(CloudDialog dialog) {
                    Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,
                            Uri.fromParts("package", getPackageName(), null));
                    startActivityForResult(intent, PERMISSION_SETTING_REQUEST_CODE);

                    dialog.dismiss();
                }
            }).show();
        }
    }
}

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == PERMISSION_SETTING_REQUEST_CODE) {
        // 다시 권한 체크
        checkPermissionsIfNeeded();
    } else {
        super.onActivityResult(requestCode, resultCode, data);
    }
}
```

**Comment by ChoMk** [comment]
감사합니다/.! 참고하여 문제 해결하였습니다.!!!!  딱 필요한 부분을 편집하여 첨부해 주셨네요 !!
