### ISSUE TITLE
ck에디터를 실제 서비스에 넣게되면 비용발생이 되나요? 

### ISSUE THREAD

**Issue by tuntunkimpo** [codingeverybody/codingyahac#374]
안녕하세요 ^ ^ 생활코딩 보면서 떠듬떠듬 공부해나가고 있는데요 
ck에디터를 사용해 보면서 실제 서비스에 넣어도 되겠다 하는생각이 들더라구요
실제 서비스로 사용해보려고 생각하다보니 비용을 고려해야 하겠더라구요
https://ckeditor.com/ckeditor-4/pricing/

한달에 260$ 정도인데 엄청 비싸다는 느낌을 받았어요 ㅠ ㅠ 

그래서 질문의 요지는... 
혹시 회사에서 실제 ck에디터를 적용하고 이 비용을 지불하시는 분이 있나요? 

서비스를 외부에 배포하지 않으면 무료로 사용해도 된다고 하는데 이 기준이 참 모호해 보여서요
ck에디터 라이센스 정책에 대해 이야기 해주실분이 있으실까요? 

더불어 ck에디터를 네이티브앱에 붙일수 있는지도 궁금합니다 

날씨도 더운데 시원하게 다들 코딩공부 즐겁게 하시구요~ ㅎㅎ ^ ^

**Comment by egoing** [comment]
제 생각에는 여러 옵션을 붙였을 때 그 비용이고, 그냥 다운로드 받아서 사용하는 것은 무료인 것 같습니다. 
네이티브 앱에 웹뷰로 붙이면 될 것 같지만, 제가 안드로이드는 아니라서 이 부분은 잘 모르겠습니다.

**Comment by tuntunkimpo** [comment]
비용이 더 추가 될수있는 여러 옵션이라는게 
CKEditor Cloud Services  (https://ckeditor.com/ckeditor-cloud-services/) 같은 걸 이야기 하시는거죠? 

단순 플러그인
https://ckeditor.com/cke4/addons/plugins/all

들을 붙여서 서비스에 넣는것은 비용이 안들겠죠? ^ ^


이고잉님
답변주셔서 감사 드립니다 
벌써 몇년째 생활코딩 강좌에 큰 도움을 받고 있습니다
덕분에 이제는 세상에 도움될 만한 조그마한 서비스를 하나 만들어 볼까합니다
어느정도 만들어지면 소개하겠습니다 
^ ^ 더운데 고생하셔요 ~ ㅎ
