### ISSUE TITLE
안드로이드 Tab Activity에 대해서..

### ISSUE THREAD

**Issue by ParkHongUK** [codingeverybody/codingyahac#377]
안녕하세요.

어플리케이션을 만드는 도중 탭을 사용하여, 기능을 구성하려고 하는데요.

깃에 돌아다니는 이쁘고 적용하기 좋은 tab UI 들이 많아서 적용하려 했더니,

이러한 탭들은 다  fragment 를 적용하기 때문에 저한테는 사용할 수 없는 것이었습니다.

왜냐하면, 제가 원하는 기능을 일종의 activity  ( 탭을 클릭했을 때 나오는) 들이 다른 API 를 상속받기 때문에,

fragment형식으로 띄울 수가 없었습니다.

일반적으로 Tabhost 를 사용하면 activity 를 탭마다 띄울 수 있던데, 탭 아이콘이 변하지 않는다던가, 이쁜 애니메이션을 적용하기 힘든 경우가 많더라구요.

여기까지.. 제 상황 설명이었고, 정확히 질문드리겠습니다~ 선임 개발자분들 도와주시면 정말 감사하겠습니다.

1. 다른 API를 상속받는 activity 를 프래그먼트 형식으로 inflate 할 수 있을까요?

2. 1번 질문에서 불가능하다면, tabhost 를 통해 Acitivity 를 보내줘야하는데, 탭의 모양이나 아이콘을 변경할 방법이 있을까요?

- Tabhost.setIndicator("title", 아이콘 ) << 이런식으로 설정해봤지만, 작동하지 않았습니다.
찾아보니 안드로이드 버전 업그레이드 이후 안되는 이슈인 것 같더라구요..

**Comment by InyoungAum** [comment]
1. inflate를 한다고 해도 xml 가져와서 그리는 것이니 결국 상위 액티비티만 존재하는 것과 같은 결과 일 것입니다.  `fragment`로도 해결이 가능할 것 같은데 혹시 어떤 상황인지 다른 질문으로 올려주시면 감사하겠습니다!

2. title을 지우면 아이콘이 보이는 군요 둘다 있는 경우엔 title이 우선순위를 가지구요 
https://stackoverflow.com/questions/10745092/icon-in-tab-is-not-showing-up/11379708
위의 링크가 도움이 될 것 같습니다! 결국 둘다 표시하려면 커스텀뷰를 사용해야하는군요

**Comment by yoobato** [comment]
이 라이브러리 한 번 참고해보세요.

https://github.com/H07000223/FlycoTabLayout

**Comment by ParkHongUK** [comment]
감사합니다. 많은 도움이 되었습니다.

결국에는 TabHost 를 사용하였고, 커스텀뷰를 사용해 둘다 띄우게 구현했습니다!
