### ISSUE TITLE
진로, 학습방법에 대해서 조금 긴 질문을 드립니다.

### ISSUE THREAD

**Issue by gitsunmin** [codingeverybody/codingyahac#381]
안녕하세요. 저는 현재 물리학과에 다니고 있는 4학년 학생입니다. 예전에는 컴퓨터나 코딩에 대해서 관심이 전혀 없었지만, 최근에 전산물리라는 과목을 준비하면서 python을 알게 되었고, 점점 흥미를 느꼈고, 생활코딩님도 알게 되었습니다. 그래서 코딩공부를 취업준비보다 열심히 하고 있는데, 걱정거리가 몇 개 생기기 시작했습니다.
 진로를 바꾼 만큼 더 열심히 취업을 준비해야 한다고 생각을 하는데, 막상 자격증 공부를 할려고 보니, 컴퓨터에 관련한 지식이 너무 부족하다는 생각이 들었습니다. 물론 문제는 전부 외워서 시험을 보면 합격을 할 수도 있을 것 같지만, 그 외우는 시간이 조금 아까울 것 같습니다. 그래서 <코딩을 지탱하는 기술
URL: https://book.naver.com/bookdb/book_detail.nhn?bid=7317474 >과 같은 컴퓨터 관련 교양서적을 더 읽고, 전문서적도 조금씩 접하는 것이 우선이라는 생각이 문득 들고있습니다. 현실적으로 정보처리기사를 먼저 취득하는 것이 옳은 길일까요? 아니면, 지식을 먼저 쌓고 천천히 정보처리기사를 취득하는 것이 옳은 길일까요? 
그리고 컴퓨터 관련 전공이 필수 요소인가요? 필수라면 학점은행제를 통해서라도 얻으려고 합니다....

그리고... (질문이 많아서 죄송합니다.)
 제가 1월부터 국가기간전략산업으로 빅데이터 관련 수업을 듣기로 하였는데, 전공자도 아니고, 정보처리기사 자격증 없이도 취직이 가능할까요...?

p.s 이런 질문을 드려도 되는지 모르겠지만, 답답한 마음에 써봤습니다. 읽어주셔서 감사합니다.

**Comment by blackdew** [comment]
진로에 대해 고민하시는 분들이 참 많은 것 같아요. 
다른 분들이 질문과 그에 답변들을 읽어보시는 것이 도움이 많이 될 거라 생각합니다. 

먼저 링크의 글들을 확인해보세요 :) 
https://github.com/codingeverybody/codingyahac/issues?utf8=%E2%9C%93&q=label%3A%22%EC%A7%84%EB%A1%9C+%EC%83%81%EB%8B%B4%22+

정보처리기사를 먼저 취득하는 것도 좋은 방법이고요. 
지식을 먼저 쌓고 나중에 취득하는 것도 좋은 방법입니다. 
컴퓨터 관련 전공이 필수는 아닙니다. 하지만, 컴퓨터 관련 전공 지식은 언제가 되었든 습득을 하셔야 하겠죠. :) 

언제나 비슷한 답을 드릴 수 밖에 없네요. 이런 선택은 정답이 없습니다. 
각자의 길 위에서 각자가 처한 상황에서 스스로 가장 알맞은 해답을 찾아갈 수 밖에 없습니다. 
자신의 상황에 대해서 가장 많이 알고 자신의 길 위에서 가장 많이 고민한 사람은 각자 자신일 수밖에 없습니다. 
스스로가 최고의 전문가인 것이죠. :) 

스스로의 선택을 믿고 가시면 될 것 같습니다. 

**맨 마지막 질문에 대한 현실적인 답변은 드릴 수 있습니다. 참고 정도로 읽어주세요.** 

현재는 빅데이터 관련 수업을 듣더라도 해당 분야로 취업이 쉽지는 않을거에요. 
해당 분야의 전공자(박사, 석사)들과 경험자들이 우선이 됩니다. 
꽤 오랫동안 실제 데이터를 다뤄보면서 경험을 축적하지 않으면 필드에서 역할을 하기가 어렵거든요. 

그렇지만, 이도 현재의 얘기일 뿐 미래에 어떻게 될지는 알 수 없습니다. 
만약에 수업을 완료하시고 계속 빅데이터에 필드에 계시면서 일하기 원하신다면, 
개인 프로젝트를 진행하시면서 데이터에 대한 경험을 지속적으로 축척해보세요. 
빅데이터 분야는 앞으로 더 성장할 분야이기 때문에 
그렇게 개인적으로 1년, 2년 계속 경험을 쌓고 계시다 보면 길이 열릴 거라고 생각해요.

**Comment by gitsunmin** [comment]
답변 정말 감사합니다 현실적인 답변도 참고하겠습니다. 스스로가 최고의 전문가라는 말을 보니 좀 더 천천히 생각을 해봐야겠다는 생각이 들어요. 감사합니다.
