### ISSUE TITLE
텔레그램 봇 실행시 주의점에 관한 질문입니다.

### ISSUE THREAD

**Issue by kim00425** [codingeverybody/codingyahac#383]
안녕하세요?
저는 현재 취업카페의 새로 생성되는 글들을 감지하여 텔레그램봇으로 알람설정하는 기능을 구현하고 있습니다.
그래서 네이버의 한 취업카페의 로그인이 필요한 특정게시판에 들어가기위해 webdriver로 접속하여 bs4를 통해 새로 갱신되는 글을 텔레그램봇으로 알람설정하려고합니다. 크롬 webdriver를 통해 카페에 특정게시판의 글들을 긁어오는 것은 성공했습니다.
그런데 제가 어느 강의에서 네이버나 다음 같은 포털사이트의 글들을 긁어오려고 계속적인 실시간 크롤링 시도는 IP차단이나 처벌의 대상이 될수 있으니 주의하라고 들었습니다. 하지만 저는 pythonwhere에서 저의 파이썬 스크립트를 단순한 while 문을 통해 매초 단위로 실행하여 실시간으로 게시판을 체크하고 생성되는 글들을  감지하여 텔레그램을 통해 알람설정하려고합니다. 만약 이 방법이 문제가 된다면 다른 실시간 감지방법을 알고 싶습니다.

**Comment by blackdew** [comment]
과도한 크롤링은 언제든지 문제가 될 수 있습니다. 
상황에 따라 크롤링 자체가 문제가 되는 케이스가 있을 수도 있어요. 

올리신 것처럼 알람 기능 구현을 위해 업데이트를 체크하기 위하여 크롤링을 하는 것이라면 크게 문제는 안될 것입니다. 
크롤링한 정보를 어딘가에 저장을 하고 그것을 다른 용도로 사용을 하게 되면 문제가 될 수 있어요. 
어떤 경우에는 저장을 하는 것만으로도 문제를 삼을 수 있습니다. 

만약에 알람이 목적이시라면 글 리스트 전체를 저장하지 마시고, 
최종적인 글의 번호나 글의 제목 정도를 저장하셨다가 
그것이 갱신되는 시점에 알람을 남기는 방식으로 처리하시면 좋을 것 같아요. 

**다른 실시간 감지방법**
해당 사이트에서 글 리스트를 제공하는 API를 확인하시면 좋을 것 같고요. 
API가 있다면, 그 규약에 맞게 사용하시면 전혀 문제가 없을 것입니다. 
API를 따로 제공하지 않는 웹사이트라면 크롤링 외에 다른 방법은 없어요 :)
