### ISSUE TITLE
[HTML]github에서 받은 주소로 사이트연결 불가

### ISSUE THREAD

**Issue by sujin0326** [codingeverybody/codingyahac#386]
본 양식은 질문의 막연함을 도와주기 위한 도움을 드리기 위한 것입니다. 양식을 참고해서 자유롭게 적어주세요. 

# 해결하고자 하는 문제
gitub에서 받은 주소로 html연결하려고 하는데 페이지가 나타나질 않습니다

# 코드 혹은 오류
"<a href="https://sujin0326.github.io/sujin/index.html/" target="_blank">html 제작 사이트</a>

이렇게 보여지는데 무엇이 문제일까요ㅠㅠ

```


# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.


# 시도해본 방법

**Comment by yoobato** [comment]
```Repository```의 설정(Settings)에 들어가셔서, 아래로 스크롤 내리시면 ```GitHub Pages``` 라는게 있는데, 여기에서 ```Source```가 ```master branch```로 설정되어 있는지 확인해주시겠어요?

**Comment by sujin0326** [comment]
답변 감사합니다.
master brach로 체크되어 있는데... 왜그럴까요ㅠㅠ
<img width="625" alt="default" src="https://user-images.githubusercontent.com/42107095/43837588-f4269512-9b53-11e8-9a61-3ef7e894a3a0.PNG">

**Comment by blackdew** [comment]
파일명 확장자를 대문자로 하셨네요. 
잘 동작하고 있는 걸로 보입니다. :) 

https://sujin0326.github.io/sujin/index.HTML

**Comment by sujin0326** [comment]
@blackdew 아 확장자명!! 너무 감사합니다 :)
