### ISSUE TITLE
웹 크롤링 프로그램을 만드는 것은 어렵나요?

### ISSUE THREAD

**Issue by unqest** [codingeverybody/codingyahac#387]
HTML만 살짝 아는 비기너입니다. 네이버쇼핑에서 특정상품(여기서는 노트북이라고 하죠) 이름으로 검색하면 그 결과가 쭉 뜨는데, 그 내용(가격, 상품의 이미지, 판매채널 등등)을 자동으로 엑셀로 옮기는 프로그램을 만들고 싶습니다. (그게 웹 크롤링인지는 잘 모르겠어요...)

제 주변에도 개발자가 없다보니 엑셀과 VBA만 잘 해도 가능하다, 파이썬을 알아야 가능하다, 2~3가지 언어는 알아야 가능하다...등 근거가 없는 지인의 말만 듣고 있습니다. --; 웹에 나온 정보를 긁어오는 프로그램은 어떻게 만드는지 알고 싶습니다.

**Comment by egoing** [comment]
php를 할 줄 아신다면 
아래 코드를 php에서 입력해보세요. 

```
$content = file_get_contents('https://naver.com');
```

위의 코드는 naver.com의 홈페이지에서 html을 다운로드 받는 코드입니다. 
이제 $content라는 변수의 값은 네이버 홈페이지의 코드가 되죠. 

그걸 분석한 후에 (어떻게든 하겠죠? 했다고 상상해주세요)
그 결과를 excel의 파일 포멧에 따라서 저장하면 됩니다. 

php, python, java 등 하나의 언어만 사용할 수 있으면 됩니다~

**Comment by egoing** [comment]
잘하기는 어렵지만 
그냥 하기는 어렵지 않답니다.

**Comment by blackdew** [comment]
파이썬을 조금 익히신 후에 아래 튜토리얼을 따라해보세요. :) 
크롤링에 대한 기본 개념을 익힐 수 있을거에요. 
https://beomi.github.io/gb-crawling/

**Comment by unqest** [comment]
답변 감사드립니다. 뭘 모르는지 조차 모른다...는 말... 제가 자주 쓰던 말인데 생활코딩에서 이고잉님 강의에 이런 말이 나와서 놀라기도 했습니다. 그게 벌써 2년전이네요 ㅎㅎ. 이제 저만의 플젝을 시도해보려고 하는데 많은 도움 얻고 있습니다. 다시 한 번 감사드려요.
