### ISSUE TITLE
저는 영상보단 책으로 공부하고 싶습니다.. 

### ISSUE THREAD

**Issue by jjunyjjuny** [codingeverybody/codingyahac#391]
제가 공부 성향?이 영상이나 인터넷에서 보는 것보다 책 한권을 파는 걸 선호합니다..
그래서 어떤 책을 잡고 공부할까 찾아보고 있는데 지식이 전혀 없어서요 ..
일단 생활코딩 web1~2 부분은 계속 보고 있지만 책으로 공부하는걸 목표?로 하고 있습니다

HTML, CSS, JavaScript, Java, 혹은 스코틀까지도 염두해 두고 있지만 일단 html, css 등 기초적인 것 부터 공부하고 싶습니다. 제 목표는 웹사이트나 앱을 만드는 것입니다. 굳이 예를 들면 페이스북이나, 인스타그램, 혹은 어떤 커뮤니티, 플랫폼 같은 형태로요 . 

책좀 추천해주시면 감사하겠습니다.. 
Head First HTML and CSS 라는 책을 눈여겨 보고 있는데 2013년도 책이더군요 개정판이 ..
최신 책이 아니더라도 상관 없을까요?

**Comment by egoing** [comment]
CSS라면 최신 판을 보실 것을 강하게 권해드립니다. 왜냐면 웹브라우저 환경이 격변하고 있기 때문에 브라우저의 발전이 더뎠을 때의 온갓 트릭들을 공부할 필요가 없는 시대에 지금 살고 있거든요.
