### ISSUE TITLE
[블록체인] 메인넷 / 테스트넷 / 프라이빗넷의 명확한 차이가 궁금합니다!

### ISSUE THREAD

**Issue by s2ungja2** [codingeverybody/codingyahac#393]
메인넷은 실제 통용되고있는 이더와 가스를 사용하는 곳,
테스트넷은 무료로 발급되는 이더와 가스로 테스트를 진행할 수 있는 곳,
프라이빗 넷은 자신이 직접 이더와 가스를 만들고 테스트를 할 수 있는 곳이 맞나요 ?

위의 말이 맞다면, 개발을 할 때, 테스트넷 / 프라이빗 넷 중에 어떤 환경에서의 개발이 더 좋을까요 ?
혹시 위의 말이 다르다면, 설명좀 부탁드립니다 !

**Comment by s2ungja2** [comment]
@studroid 

Studroid님 !! 추가로 질문드리고 싶은게 있는데 혹시 Loom Network 토큰에서
Openzepplin의 DetailedToken을 상속받지 않고 심볼, 이름, 발행량을 선언한 특별한 이유가 있는건가요?

**Comment by studroid** [comment]
메인넷, 테스트넷, 프라이빗넷에 대한 설명은 이해하고 계신 바가 대략 맞습니다만, 일반적으로 스마트 컨트랙트를 개발할 떄의 프로세스는 
가상 환경(Ganache 등) -> 테스트넷 -> 메인넷 순서가 됩니다.
처음엔 메인넷과는 실행 환경이 다를 수 있지만 빠른 처리가 가능한 가상 환경에서 테스트를 진행하고, 점차 메인넷과 비슷한 환경으로 옮겨가는 과정이지요 :)

이에 대해서는 아래 글을 참고해보시면 도움이 되실 듯합니다.
[Teckle 스터디 글](https://medium.com/@weekly.teckle/초보자들을-위한-이더리움-dapp-만들기-c6ddb0c6651d)

추가로 질문하신 LOOM 토큰의 경우, OpenZepplin의 ERC20, 그중에서도 StandardToken을 상속받아 구현했습니다. 소스 코드는 아래 Etherscan 사이트에서 확인하실 수 있습니다.
[LOOM 토큰 소스](https://etherscan.io/address/0xa4e8c3ec456107ea67d3075bf9e3df3a75823db0#code)

토큰 컨트랙트 상속 이후에, 자신만의 속성을 정의해야 하므로 보통 심볼, 이름, 발행량은 따로 지정해야 합니다. 아마 컨트랙트 코드를 보시면 이해하실 수 있을 듯합니다 :)

**Comment by s2ungja2** [comment]
감사합니다 :) 추가질문은 OpenZepplin에서 이름, 심볼, 발행량을 정해주는 DetailedToken이라는 컨트랙트가 있더라구요 ㅎㅎ 혹시 안쓰신 특별한 이유가 있나 해서 여쭤봤습니다.
[DetailedToken](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/DetailedERC20.sol)

**Comment by s2ungja2** [comment]
아하 ㅎㅎ 감사합니다 :)
