### ISSUE TITLE
쇼핑몰을 만들어 보고 싶습니다. 무엇을 공부해야 하나요?

### ISSUE THREAD

**Issue by moon-alien** [codingeverybody/codingyahac#394]
web1을 대략 공부하고 나서 쇼핑몰을 만들어 보려고 하는데 
공부 방향을 어떻게 잡아야 하는지 모르겠습니다.
워드프레스를 이용해서 만든다면 
코딩야학에서 어떤 것을 배워야 할지 모르겠습니다.

**Comment by yoobato** [comment]
Wordpress를 이용하신다면, [Woocommerce](https://woocommerce.com/) 한 번 보시고, 직접 적용해보시는게 도움이 될 것 같아요.

HTML, CSS, JavaScript, PHP 대략 이 네 가지 공부를 하시면 될 것 같습니다 😄
