### ISSUE TITLE
웹개발자로 커리어 전환 시 진로 및 방향 고민

### ISSUE THREAD

**Issue by ChanwheKim** [codingeverybody/codingyahac#399]
안녕하세요!

저는 기존에 한 중견기업 제조업의 해외영업직에 근무를 했었고 지금은 무직 상태입니다. 영어 전공자이고 나이도 34살이지만, 현재 웹개발자로 직업을 변경하고 싶어, 이리저리 알아보고 있는 가운데 고민이 생겨 질문을 남겨요.

저의 질문은 커리어 전환 시 학원을 다니는 것이 유리할까요? 아니면 혼자서 인강을 듣고 지원을 해봐도 될까요?

저는 javascript와 아직 접해보지는 않았지만 react 같은 프레임워크,(가능하다면 node.js와 express?) 이것을 배워보고 커리어 전환을 도전해 보고 싶습니다. 국비지원 학원을 여러 곳 상담 받았는데 모두 java언어로 강의가 진행되더라고요. 그래서 학원에 맞추어 아무래도 java쪽으로 웹개발을 배워야 좋은지, 아니면 하고 싶었던 javascript로 혼자 강의를 듣고 도전을 해봐도 괜찮을 지 고민입니다. 

아무래도 독학을 하게 되면 회사측에서 저의 학습에 대한 신뢰도가 떨어질까봐도 걱정입니다..; 비싸긴 하지만, 필요하다면 udacity의 react과정을 듣고 포트폴리오를 만들어 볼까 생각중입니다.

개인적으로 저에 대해 간략히 소개 드리면, 저는 여행을 좋아해서 퇴사 후 이직 전까지 기존에 하던 여행블로그를 어느정도 만들어 놓으려 했습니다. 워드프레스로 만들어 보다가 html, css를 조금 학습하게 되었고, 흥미를 느껴 javascript도 조금 학습을 했습니다. 제게 위의 내용들이 매우 어려웠습니다. 하지만, 해외영업보다 흥미를 느끼게 되어, 직업으로 하면 일하는 시간이 즐거울 것 같다고 생각했습니다. 그리고 현재는 웹개발자로 커리어 전환을 꿈꾸게 되었습니다.

위의 글 읽어 주셔서 감사합니다. 저는 주변에 물어볼 곳이 없는데,  이러한 상담 코너 만들어 주셔서 너무 감사합니다!!

**Comment by blackdew** [comment]
비슷한 질문을 올려주신 다른 분들의 글에 조력자 분들이 달아두신 답변이 많이 있습니다. :) 
참고하시면 좋을 것 같아요. 

https://github.com/codingeverybody/codingyahac/issues?utf8=%E2%9C%93&q=label%3A%22%EC%A7%84%EB%A1%9C+%EC%83%81%EB%8B%B4%22+

node.js와 reactjs 혹은 vuejs로의 흐름이 있는 것은 맞습니다. 이 부분을 중심으로 준비하시면 아마 도움이 될 거에요. 그치만, 너무 취업 중심으로만 공부를 하시지는 않으셨으면 해요. 
간단한 것부터 본인이 주도하며 재미있게 지속할 수 있는 프로젝트를 찾으시고,  그 프로젝트를 중심으로 프로그래밍 지식을 쌓아가시다 보면 좋은 결과가 있을 거라고 생각합니다.

**Comment by ChanwheKim** [comment]
아 다른분들 관련 답변도 전달 주셔서 감사합니다~!

저는 웹으로 여행 관련이나 어떠한 서비스 제공하는 것을 해보고 싶었는데, 답변 주신대로 이 방향으로 간단한 프로젝트부터 시작해서 재미도 느끼며 차근히 지식을 쌓아가야겠어요! 

답변 정말 감사합니다~~~! :)
