### ISSUE TITLE
빅데이터 관련 진로에 관한 질문 드립니다.

### ISSUE THREAD

**Issue by Bottlecoffin** [codingeverybody/codingyahac#40]
빅데이터에 관심이 많은 27살 비전공자 학생입니다.

꼭 이쪽으로 일해보고 싶다는 생각이 들어 여러 학원들 상담도 받아보고 인터넷도 찾아봤지만 사람들 마다
 
말도 다르고 어떤 공부를 하고 어떻게 해 나가야하는지 관련 정보가 너무 적어 힘드네요..

그와중에 코딩야학을 알게되고 빅데이터 관련 엔지니어 분들도 계신거 같아 질문드립니다.

### 3. 현재는 자바, 파이썬, html, css 등 기초가 되는 언어들을 공부하고 있는데 빅데이터 관련 일을 하기 위해선 어떤 공부가 필요하고 어떤 준비가 필요한지 궁금합니다.

목표를 정했는데 어떤 방식으로 나아가야 하는지 너무 막연하고 막막해서 이렇게 질문 드리게 되었습니다.

실무에서 일하시는 분들께 조언을 받을 수 있는 좋은 기회인 것 같아 주저리주저리 말이 길어졌는데 저에게

는 정말 간절한 일이라서 혹시 답변내용이 아니더라도 조언해 주실 게 있다면 정말 감사히 새겨듣겠습니다!

**Comment by blackdew** [comment]
1. 27살은 그게 무엇이든 시작하기에 늦은 나이가 결코 아닌 것 같아요. :) 

2. 빅데이터와 머신러닝&데이터분석 분야가 집중적으로 주목을 받기 시작한 게 얼마 되지 않습니다. 그래서 이 분야를 어떻게 접근하고 어떻게 방향을 잡고 가야할 지 참고할 만한 텍스트를 찾기가 어렵지요. 특히, 국내에서는 더욱 그렇습니다. 이 얘기는 바꿔말하면 아직 어떤 것이 더 좋다라고 얘기할 만한 충분한 케이스가 쌓은 미개척 분야라는 뜻이고 그래서 사람들마다 말도 다르고 관련정보를 찾기가 어려운 것이지요. 그만큼 이것저것 시행착오를 직접 겪으면서 경험해가야 한다는 의미이기도 합니다. 하지만, 이 분야에 있는 모두가 동일한 조건인거죠. 그래서 더욱 지금부터 시작하더라도 결코 늦지 않았다고 말씀드리고 싶습니다. 
때문에, 저는 어느 쪽이 더 나을지 고민을 하실 필요가 없고, 지금 본인의 상황에 맞다고 판단되는 쪽을 선택하고 가시면 된다고 말씀드리고 싶어요. 데이터 분석 공부를 계속 하시면서 바로 데이터 분석 일을 찾아보셔도 좋을 것 같고요. 빅데이터 개발자로 일할 기회가 있다면 그곳에 가서 일을 하면서 배워가는 것도 좋을 것 같습니다. 

3. 빅데이터 기술은 Hadoop 기술을 배우는 것은 필수입니다. 기술이 쏟아져 나오고 있기 때문에 혼란스러울 수 있는데요. 일단 Hadoop - map reduce, yarn, hdfs 이 키워드를 가지고 공부를 하시면 됩니다. 나머지 기술들은 여기에 기초를 두고 있다고 보시면 됩니다. 그리고 데이터 분석일을 하시려면 '통계학'과 '선형대수' 수학 공부를 해두시는 게 최고입니다. :) 언어와 관련해서는 R, python, scala 등 어떤 언어든 데이터를 다룰 수 있는 언어를 하나를 배우셔서 그걸 가지고 데이터를 가지고 놀아보시면 될 것 같아요.
