### ISSUE TITLE
안드로이드 - 프레그먼트가 바로 호출되지 않는 문제

### ISSUE THREAD

**Issue by beaucnl** [codingeverybody/codingyahac#400]
# 해결하고자 하는 문제

MainActivity.Java에서 BottomNavigationView 를 이용해서 Fragment를 만들었습니다. 
그리고 setOnNavigationItemSelectedListener 에서 onNavigationItemSelected 에서 각 프레그먼트에 대해
                        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, serviceFragment).commit();

위와같이 코딩했습니다. 

그리고 MainActivity.jave - onCreate 에 마지막에 기본으로 보일 뷰를, 

        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, onLiveFragment).commit();

위처럼 코딩했습니다. 

문제는 onLiveFragment가 보이기는 하는데, rootView.findViewById 로 찾은 view들만 보이고, 
      
  nickNameTextView.setText(nick); 
위 코드처럼 setter로 띄운 것은 바로 보이지 않습니다. 

다른 프레그먼트 클릭해서 돌아오고 나서야 보입니다. 

처음부터 보이게 할 방법이 없는지 질문 드립니다. 

# 코드 혹은 오류

public class MainActivity extends AppCompatActivity {

    private BottomNavigationView bottomNavigationView;

    private Fragment onLiveFragment;
    private Fragment serviceFragment;
    private Fragment profileFragment;
    private Fragment settingFragment;

    private FirebaseFirestore firestore;
    private FirebaseAuth auth;
    private FirebaseUser user;
    private String uid;

    private String url1;
    private String url2;
    private String url3;
    private String nick;

    private TextView nickNameTextView;

    String color_string_base = "#607D8B";
    String color_string_selected = "#03A9F4";

    private final long FINISH_INTERVAL_TIME = 2000; 
    private long backPressedTime = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        auth = FirebaseAuth.getInstance();

        uid = auth.getCurrentUser().getUid();

        nickNameTextView = (TextView)findViewById(R.id.onlive_fragment_textview_mynickname);

        bottomNavigationView = (BottomNavigationView) findViewById(R.id.mainactivity_bottomnavigationview);
        BottomNavigationViewHelper.disableShiftMode(bottomNavigationView);

        firestore = FirebaseFirestore.getInstance();

        firestore.collection("user").document(uid).addSnapshotListener(new EventListener<DocumentSnapshot>() {
            @Override
            public void onEvent(@Nullable DocumentSnapshot documentSnapshot, @Nullable FirebaseFirestoreException e) {
                UserDTO userDTO = documentSnapshot.toObject(UserDTO.class);
                if (userDTO != null) {
                    if (userDTO.imageUrl1 != null) {
                        url1 = userDTO.imageUrl1;
                    }
                    if (userDTO.imageUrl2 != null) {
                        url2 = userDTO.imageUrl2;
                    }
                    if (userDTO.imageUrl3 != null) {
                        url3 = userDTO.imageUrl3;
                    }

                    if (userDTO.nickname != null) {
                        nick = userDTO.nickname;
                    }
                }

            }
        });

        int[] colors = new int[]{
                Color.parseColor(color_string_base),
                Color.parseColor(color_string_selected)
        };

        int[][] states = new int[][]{
                new int[]{android.R.attr.state_enabled, -android.R.attr.state_checked},
                new int[]{android.R.attr.state_enabled, android.R.attr.state_checked}
        };

        bottomNavigationView.setItemTextColor(new ColorStateList(states, colors));
        bottomNavigationView.setItemIconTintList(new ColorStateList(states, colors));

        onLiveFragment = new OnLiveFragment();
        serviceFragment = new ServiceFragment();
        profileFragment = new ProfileFragment();
        settingFragment = new SettingFragment();

        Menu menu = bottomNavigationView.getMenu();

        bottomNavigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                switch (item.getItemId()) {

                    case R.id.action_onlive:
                        Bundle onliveBundle = new Bundle();
                        onliveBundle.putString("url1", url1);
                        onliveBundle.putString("url2", url2);
                        onliveBundle.putString("url3", url3);
                        onliveBundle.putString("nick", nick);
                        onLiveFragment.setArguments(onliveBundle);
                        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, onLiveFragment).commit();
                        return true; 

                    case R.id.action_service:
                        Bundle bundle = new Bundle();
                        bundle.putString("edttext", "ㅈㅔ발 돼라아아아아");
                        serviceFragment.setArguments(bundle);

                        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, serviceFragment).commit();
                        return true; 

                    case R.id.action_profile:
                        Bundle profileBundle = new Bundle();
                        profileBundle.putString("url1", url1);
                        profileBundle.putString("url2", url2);
                        profileBundle.putString("url3", url3);
                        profileFragment.setArguments(profileBundle);
                        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, profileFragment).commit();
                        return true;

                    case R.id.action_account:
                        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, settingFragment).commit();
                        return true;

                }

                return false;
            }
        });

        Bundle onliveBundle = new Bundle();
        onliveBundle.putString("url1", url1);
        onliveBundle.putString("url2", url2);
        onliveBundle.putString("url3", url3);
        onliveBundle.putString("nick", nick);
        onLiveFragment.setArguments(onliveBundle);
        getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, onLiveFragment).commit();

    }

public class OnLiveFragment extends Fragment {

    private TextView nickNameTextView;
    private ImageView myImageView;
    private TextView descriptionTextView;

    private Button requestBtn;

    private TextView nextTimeTextView;
    private TextView nextTimeTextViewCount;

    private String url1;
    private String url2;
    private String url3;
    private String nick;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_onlive, container, false);

        nickNameTextView = (TextView) rootView.findViewById(R.id.onlive_fragment_textview_mynickname);
        myImageView = (ImageView) rootView.findViewById(R.id.onlive_fragment_imageview_myimageview);
        descriptionTextView = (TextView) rootView.findViewById(R.id.onlive_fragment_textview_mydescription);

        requestBtn = (Button) rootView.findViewById(R.id.onlive_fragment_button_request);

        nextTimeTextView = (TextView) rootView.findViewById(R.id.onlive_fragment_textview_nexttime);
        nextTimeTextViewCount = (TextView) rootView.findViewById(R.id.onlive_fragment_textview_nexttime_count);

        url1 = getArguments().getString("url1");
        url2 = getArguments().getString("url2");
        url3 = getArguments().getString("url3");
        nick = getArguments().getString("nick");

        nickNameTextView.setText(nick);

        return rootView;
    }

}

# 환경
MacOs , 안드로이드 SDK

# 시도해본 방법
프레그먼트의 onAttach, onViewCreated 등에서 해보려고 시도했으나, 실행되지 않았습니다. 

구글 검색해보니, 액티비티와 프레그먼트의 리스너를 통해서 인자를 전달하라고 설명은 되어 있는데 정확히 어떻게 해야할지 모르겠습니다.

**Comment by InyoungAum** [comment]
추측해 본 문제는 
`firestore.collection("user").document(uid).addSnapshotListener`의 `onEvent`에서  url들과 nick을 받아오는데 이 값들을 받아오는 시점이 
액티비티 코드 하단의 

```
Bundle onliveBundle = new Bundle();
onliveBundle.putString("url1", url1);
onliveBundle.putString("url2", url2);
onliveBundle.putString("url3", url3);
onliveBundle.putString("nick", nick);
onLiveFragment.setArguments(onliveBundle);
getSupportFragmentManager().beginTransaction().replace(R.id.mainactivity_framelayout, onLiveFragment).commit();
```
여기서 fragment를 띄워주는 시점보다 느려서 그렇습니다. 프래그먼트가 뜨고 값이 받아와졌으니 다른 프래그먼트에 갔다오면 값이 있어서 되는 것처럼 보이는 것입니다. 

위의 프래그먼트가 뜨게 하는 코드를 `onEvent`의 값들이 다 넣어진 후로 시점을 바꿔보시겠어요?

**Comment by beaucnl** [comment]
ㅜㅜ 감사합니다. 

해결했습니다. 머리 숙여 감사드립니다.
