### ISSUE TITLE
DB : Oracle Timestamp형 update 쿼리문 질문입니다

### ISSUE THREAD

**Issue by j2k63** [codingeverybody/codingyahac#402]
# 해결하고자 하는 문제
CGV 홈페이지를 벤치마킹하여
영화 예매 스케쥴을 저장해 놨는데
갱신을 위해 현재 저장되어 있는 월 +1을 하려고 합니다.
Oracle Timestamp update

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Window
oracle DB 11g express, oracle SQL Developer

# 시도해본 방법

UPDATE TIMESCHEDULE SET THEATERDATE = TO_DATE(TO_CHAR(TO_DATE('201807'), 'YYYYMM') || TO_CHAR(TIMESTAMP, 'HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
WHERE TO_CHAR(TIMESTAMP, 'YYYYMM') = '201808';

**Comment by blackdew** [comment]
oracle을 써본적은 없는데요. 검색해보니 ADD_MONTHS() 라는 함수가 있네요. :) 
https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions004.htm#SQLRF00603

**Comment by j2k63** [comment]
알려주신 ADD_MONTH() 함수로 사이트 구동은 원활하게 돌아갑니다 .ㅎㅎ
다만 밀리 세컨드 까지 변환시킬수 있는 방법이 있을까요?

**Comment by blackdew** [comment]
Timestamp를 date로 converting 하는 과정에서 milisecond가 사라지는 걸로 보이는데 맞나요? 

아래 링크들이 참고가 될지 모르겠네요. 
https://stackoverflow.com/questions/9180014/using-oracle-to-date-function-for-date-string-with-milliseconds
https://okky.kr/article/55301

**Comment by j2k63** [comment]
update TIMESCHEDULE 
set THEATERTIME = ADD_MONTHS(THEATERTIME, 1),
THEATERDATE = ADD_MONTHS(THEATERDATE, 1)
where theaterdate <= TO_DATE('2018082623','YYYYMMDDhh24');
쿼리문은 이걸 사용했었습니다.
위 링크 보고 해결할 수 있을 것 같습니다.
정말로 감사합니다!!!
