### ISSUE TITLE
대학교 강의정보를 가져오는 방법에 대해서 질문합니다.

### ISSUE THREAD

**Issue by lee95292** [codingeverybody/codingyahac#404]
현재 JSP/Servlet을 공부한 상태에서, DB 연결 후, 대학 강의정보를 불러오고싶습니다.

이때 제가 알아본 결과 가능성있는 방법 두가지를 찾아봤는데요, 

1. 대학교 수강신청사이트를 크롤링한다.(저같은경우, JAVA 크롤러 작성)

2. 대학 강의정보를 제공하는 API 또는 공공데이터를 찾는다.

보통의 경우, 두가지 방법중 어떤 방법을 사용하는지, 이 두가지 외에 다른 방법이 있는지,  궁금합니다!

**Comment by blackdew** [comment]
두가지 경우가 보통입니다. 
2번을 제공하고 있는 경우라면 그것을 사용하는 것은 공식적인 것이 됩니다. 이를 사용하기를 권장드립니다. 
2번을 제공하고 있지 않는 경우에 1번 크롤링을 시도할 수 있고요. 크롤링 시에는 데이터를 가져가는 것에 불법적인 측면이 없는지 고려를 하셔야 합니다. 대학 강의정보라면 크게 문제가 없어보이네요. :)

**Comment by yoobato** [comment]
저도 예전에 학교 앱을 개발한 적이 있는데, 거의 대부분의 대학교가 ```OpenAPI```를 제공하지 않기 때문에
직접 크롤링하는 1번의 방법을 사용하셔야할 가능성이 큽니다 😢

**Comment by lee95292** [comment]
@blackdew  @yoobato 
답변 정말정말 감사드립니다!  DB설계 관련해서 막힐것같은데 또 질문하러 오겠습니다. ( _ _)
