### ISSUE TITLE
php 와 db연동 문제

### ISSUE THREAD

**Issue by limyongkwan** [codingeverybody/codingyahac#407]
# 해결하고자 하는 문제

php로 db와 연동을 하는데
가상윈도우인 리눅스에서는 아무런 문제가 없는데
윈도우에서 실행을 하면 mysql에서 ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '}' at line 1
이런 오류가 발생하면서 연결이 안됩니다.
코드자체에 문제가 있는것 같진 않고 환경설정의 문제 같은데 뭐가 문제인지 모르겠습니다...ㅠㅠㅠ

# 코드 혹은 오류
```

$connect = mysqli_connect("localhost","root","1234","haksa","80","");

if($connect->connect_error){
    echo '[연결실패] : '.$connect->connect_error.'<br>';
} else {
    echo '[연결성공]<br>';
}

   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
window10 , php7.2 ,mysql 5.x

# 시도해본 방법
아파치를 안깔아서 문제가 발생한건가 싶어서 아파치를 깔아보고 환경변수에서 문제가 발생한건가 싶어서 환경변수도 약간 만져봤는데 반응이 없었습니다.
포트번호의 문제인가 싶었는데 가상윈도우인 리눅스에서는 포트번호나 db의 문제가 있다고 말은 나와도 db자체하고는 연결이 되었다고연결성공이 나왔습니다.

**Comment by blackdew** [comment]
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '}

해당 버그는 query 문이 잘못되었을 때에 나타나는 에러 구문이에요. '}'문자열을 가진 쿼리문이 만들어져 있고 이 쿼리문을 실행하면서 에러가 난 것이죠. 

만일 실제 코드상에서 쿼리문이 적절히 잘 되어있는지 확인해 보시고요. 
만일 쿼리문이 잘못되지 않은 것 같다면, 코드를 복사해 오는 가운데 
1. 보이지 않는 유니코드 문자열이 포함되거나 
2. ', ", 줄바꿈 등등의 특수 문자가 비슷한 모양의 전혀 다른 유니코드 문자열로 바뀌어서 복사되었거나 
하는 경우에 발생하는 경우도 있습니다. 

쿼리문 문자열이 제대로 닫히지 않게 되고, 
쿼리문에 그 뒤에 나타나는 코드상의 문자열 '}'를 포함하는 상태가 발생하는 것이지요.

**Comment by smartbos** [comment]
연결은 됐는데 다른 코드에서 문법 오류가 있는거 같아요.
적어주신 코드 말고 다른 곳에 있는 쿼리문에 } 가 잘못 포함된 경우가 있는지 확인해보세요.

**Comment by limyongkwan** [comment]
넵 해결되었습니다. 감사합니다ㅎㅎ
