### ISSUE TITLE
코드의 가독성과 오픈소스에 대한 질문입니다.

### ISSUE THREAD

**Issue by G-ONL** [codingeverybody/codingyahac#408]
안녕하세요. 화학과에서 코딩을 하고 있는 학생입니다. 진로를 어플리케이션 개발자로 생각을하고 열심히 공부 하고 있습니다.

1. 코드를 작성하다보면 내가 작성하는 코드가 과연 잘 작성한 코드일까라는 생각을 많이 합니다.
과연 현업에서 개발자분들은 어떻게 작성할까라는 생각도 들고요.

그래서 혹시 현업에서 개발하시는 분들의 코드를 볼 수 있는곳이 있을까요??

2. 깃허브에 있는 오픈소스를 활용을 하고 싶은데 어플리케이션을 개발할때 어떤 라이브러리가 좋은지 찾아봐야 하는걸로 알고 있습니다. 그런데 그냥 구글링으로 찾아봐야하는건지 아니면 깃허브에서 찾을 수가 있는것인지가 궁금합니다. 

좋은것은 star의 수로 구분을 할 수 있다고 생각을 하는데 자기 서비스에 맞는 라이브러리를 발굴해 내는것이 어렵네요.

긴 글 읽어주셔서 감사합니다.

**Comment by InyoungAum** [comment]
1. 그 회사의 기술블로그나 오픈소스가 있다면 깃헙등을 가보면 볼 수 있습니다. 
예시로 우아한 형제들의 한 오픈소스 링크를 첨부합니다.
https://github.com/woowabros/WoowahanJS

2. 저는 구글링도하고 그냥 깃헙에 검색 하기도하고 그때 그때 다른것 같습니다. 딱히 언제 이걸 써야한다 이런건 없구요 라이브러리는 스타많은것부터 들어가보고 readme나 위키가 있다면 읽어보고 적용합니다. 하다가 안되면 소스를 뜯어보거나 정안되면 다른 라이브러리를 적용해보고 다시 또 반복하고 합니다. 도움이 되셨을지 모르겠네요 :)

**Comment by G-ONL** [comment]
소중한 답변 너무 감사드립니다!!
혹시 추가로 궁금한것이 깃헙에 검색을 할때는 어떤식으로 키워드를 검색하시나요??
라이브러리를 딱 정해서 검색을 한다면 바로 그에 따른 라이브러리를 볼 수가 있는데
어떤 기능을 원하지만 라이브러리 이름과 기능의 이름이 동일시 되는 패키지는 거의 본적이 없어서요!!

**Comment by yoobato** [comment]
GIthub 검색이 단순히 라이브러리 이름만으로 매칭시키는 것이 아니기 때문에, 기능으로 검색하셔도 됩니다.
더불어, Github에서 검색을 하면 좌측 하단에 ```Langauge```가 나오는데, 이걸로 필터링해서 보시면 더 도움이 됩니다.

예를 들어, 안드로이드의 라이브러리 같은 경우에는 ```Java``` 혹은 ```Kotlin``` language를 사용하겠지요?

추가로, 저는 개인적으로 Github 검색보다 구글 검색을 선호하는 편입니다.
구글에 ```android tab inurl:github``` 이런식으로 검색하시면, github이 URL에 포함된 검색 결과만
나오게 되서, github에서 검색하는 것과 큰 차이가 없습니다 😄

**Comment by G-ONL** [comment]
와우 너무 감사합니다!!
역시 구글신님의 검색방법은 다양하면서 신기하고 유용하네요!!
알려주신 만큼 열심히 공부해보겠습니다^^
