### ISSUE TITLE
파이썬 + bs4 를 이용한 다른 프로젝트가 있을까요?

### ISSUE THREAD

**Issue by kim00425** [codingeverybody/codingyahac#409]
안녕하세요?
파이썬 + bs4 + 셀레니움을 이번에 배우고 간단한 텔레그램 봇을 만들어 보면서  파이썬의 장점과 매력에 빠지게 되었습니다.

이제 저만의 포트폴리오를 만들어 보려고합니다. 백엔드 서버 진로를 생각 중인데 파이썬을 이용한 프로젝트 있을까요?

DB는 MySQL을 배워본 적 있습니다.

**Comment by blackdew** [comment]
생활코딩 멤버분들을 위해 생활코딩 페북페이지 글을 크롤링해서 
텔레그램 봇을 만들어 해보시면 어떠신가요? :)

**Comment by blackdew** [comment]
어떻게 데이터를 추출하면 사람들에게 편리하고 유익한 정보를 전달할 수 있게 될지 직접 고민을 해보시길 권해드려요 
그런 고민을 하는 것이 프로그래밍과 문제해결 능력을 배우는 과정입니다. :)
