### ISSUE TITLE
Nodejs 공부중에 질문이 있습니다! - nodejs로 실시간 1:1랜덤매칭 채팅 서버를 구축할 수 있을까요??

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#41]
안녕하세요! 현재 aws프리웨어 서비스를 이용해서 1:1랜덤 채팅사이트를 만들어 보고싶은 사람이에요.
원래는 APM으로 서버를 셋팅후에 구현해보고 싶었는데, nodejs라는 흥미로운 언어를 발견해서 그것을 통해 제 채팅사이트를 구축하고자 합니다. 자바스크립트는 어느정도 알고있었으나 nodejs는 완전 처음 접해보았고 현재도 이고잉님의 강의를 보면서 학습중입니다. 학습중에 궁금한 사항이 생겨서 이렇게 질문합니다!

질문1. nodejs로 실시간 1:1랜덤매칭 채팅 서버를 구축할 수 있을까요??

질문2. nodejs로 서버를 생성하던데, 그럼 nodejs로 아파치의 역할까지 수행할 수 있는건가요??

질문3. npm으로 모듈들을 설치하다보면 No repository field라는 경고문구가 자꾸 나오는데, 아마 저장소를 등록안해서 나오는 문구같습니다. 이 경고문구를 무시하고 진행해도 될까요?

질문4. npm으로 express 모듈 설치후에 생성되는 폴더인 mine의 cli.js 파일에 #!/usr/bin/env node가 첫줄에 코드인데 이부분이 기본적으로 에러가 뜹니다. 문법상의 오류인지 왜 오류가 뜨는지 잘 모르겠어서 우선 주석처리를 해놨는데, 중요한 부분일까요??

너무 디테일한 부분을 질문해서 답변을 받을 수 있을지 모르겠지만, 구글링으로 해당 내용을 찾을 수 없어서 이렇게 질문드립니다!

**Comment by blackdew** [comment]
nodejs 실시간 채팅 서버는 이미 샘플 코드들이 많이 있어서 쉽게 자료를 찾을 수 있을거에요. :)
채팅을 쉽게 만들 수 있다면, 랜덤 매칭을 해주는 것만 구현을 하면 되는 것이니 어렵지 않을 것 같습니다. 
https://goo.gl/pPmzXx

socket.io를 이용해서 구현하는 예제들이 좋아보이네요 :) 


-----

하나의 이슈에 하나의 질문만 올려주시는 것이 다른 사람에게도 도움이 되고 답변을 잘 받을 수 있는 방법이 되어서 그렇게 가이드를 드리고 있습니다. 
각각의 질문들을 하나 하나 분리해서 질문을 올려주시면 좋을 것 같아요. :)
