### ISSUE TITLE
flex 디자인 관련 반응형 이미지 질문드립니다.

### ISSUE THREAD

**Issue by integerblue** [codingeverybody/codingyahac#412]
# 해결하고자 하는 문제
웹사이트를 flex를 이용하여 디자인중입니다.
백그라운드 이미지 위에 가운데에 로고가 있고 아래에 세 개의 버튼이 있는 구조로 만들었습니다.
요는 FHD해상도인 제 노트북에서는 잘 출력되지만 HD 해상도의 모니터에서는 비율이 맞지 않아 화면크기에 따라 자동으로 로고와 버튼의 크기가 조절되는 웹사이트를 만들고 싶습니다. 

제가 생각했던 바로는 이미지를 담고 있는 컨테이너의 크기를 화면 크기에 비례하여 %로 설정하였을 경우 컨테이너가 이미지의 크기보다 작아지면 이미지도 자동으로 컨테이너의 크기에 맞춰서 작아지게 하는 방법이 제일 깔끔할 것 같았는데 이를 적용할 방법을 찾지 못했습니다. 도와주시면 정말정말 감사드리겠습니다!

# 코드 혹은 오류
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Audiro</title>
    <style>
        html{
            height:100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        body{
            background-image:url(./img/background_home.png)
        }
        .container{
            display:flex;
            flex-direction:column;
            align-items:center;
            justify-content: center;

        }
        .index_logo, .content{
            display:flex;
            justify-content:center;
        }
        .index_logo{
              margin-bottom:50px;
        }
        .index_img{
            margin : 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="index_logo">
            <a href="http://naver.com"><img src="./img/Logo_rosegold.png" alt="에이전시""/></a>
        </div>
        <div class="content">
            <a href="http://naver.com"><img class="index_img" src="./img/Agency.png" alt="에이전시""/></a>
            <a href="http://naver.com"><img class="index_img" src="./img/Model.png" alt="모델"/></a>
            <a href="http://naver.com"><img class="index_img" src="./img/Fan.png" alt="팬"/></a>
        </div>
    </div>
</body>
</html>

```
# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Windows, Chrome을 사용하고 있습니다.

**Comment by swon223** [comment]
생활코딩 페북 페이지에도 올라왔는데요
뷰포트를 기준으로 자신의 크기를 조절하는 `vw, vh`를 참고해보시면 좋을 것 같아용
https://webdesign.tutsplus.com/ko/articles/7-css-units-you-might-not-know-about--cms-22573

아니면 전체 브라우저 창 크기에 따라서 외부 css 파일을 가져다 쓰는 방법도 있을 것 같습니다~
https://developers.google.com/web/fundamentals/design-and-ux/responsive/?hl=ko

**Comment by integerblue** [comment]
아 정말 감사합니다! Vw, vh는 모르고 있었네요.
다만 div태그 안의 flex 이미지가 div의 크기가 줄어들었을 때 이미지의 크기도 그에 맞춰 줄어들게 하려면 어떻게 해야 할까요?

**Comment by swon223** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax
flex를 활용해서 반응형 이미지 엘리먼트를 만드려고 하려면, 일단  
1) 이미지 상위 엘리먼트가 flex 성격을 가지고 있고 
2) 빈 공간이 있어야 하고
3) 이미지 엘리먼트들이 `flex-grow`나  `flex-shrink`를 써서 서로 이 공간을 차지하는 방식으로 움직여야하는데..여러 조건을 파악해야하는 것 같아요. flex-direction에 따라 엘리먼트가 자동으로 차지하는 방향도 달라지고,  `flex-basis`로 기본적인 너비를 지정해줘야 세밀한 이미지 사이즈 조정이 되는 것 같습니다. 그리고 이미지 엘리먼트가 하나의 a태그를 부모로 공유하고 있는 형태가 아니라 각각 부모가 있어서 위와 같은 행동이 이뤄지게 하려면 음..제 실력으로 잘 모르겠습니다ㅜ

어떤 이벤트로 컨테이너 사이즈가 달라질지  모르겠지만,  이미지 엘리먼트에 직접 vw,vh를 활용하는 게 효율적일 것 같아요

http://jsbin.com/dagawerotu/edit?html,output
많이 허접한데 a태그 안에 있는 img에 vh,vw를 적용해본 거예요

**Comment by integerblue** [comment]
vw, vh, vmin을 활용해서 원하는대로 구현하였습니다!
감사합니다 ㅎㅎ
