### ISSUE TITLE
깃텁에서 내가 만든 웹사이트 여는 방법?

### ISSUE THREAD

**Issue by leehaobit** [codingeverybody/codingyahac#413]
# 해결하고자 하는 문제
전에는 이것저것 누르다가 알았었는데,
깃텁에서 제가만든 페이지를 어떻게 열어볼 수 있는지 까먹었어요ㅠㅠ 답답해서 질문합니다!
코드말고 직접 페이지를 열어보고싶어요! 잘 작동되는지!
![default](https://user-images.githubusercontent.com/42068379/43887119-c74eddba-9bf8-11e8-8227-fc93f3578073.PNG)

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by hyunki** [comment]
위의 페이지에서 오른쪽 상단에 setting 버튼 누르시면
![image](https://user-images.githubusercontent.com/25163778/43889768-01aa3886-9c00-11e8-8681-48e0db5ef9bc.png)

**Comment by yoobato** [comment]
```[Github계정명].github.io/[프로젝트명]``` 형태로 주소창에 치시면 됩니다 😄 

스크린샷으로 올려주신 사이트의 경우에는 https://leehaobit.github.io/web1/ 네요!

**Comment by leehaobit** [comment]
@hyunki 님 @yoobato 님 감사합니다!! ㅎ_ㅎ 확인했습니다!! 좋은 하루 보내세요~^_^
