### ISSUE TITLE
aws 질문입니다. - public ip와 private ip는 1:1로 매칭시켜놓은 것인가요?

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#42]
지식인에 올렸던 내용인데 원하는 답변을 받지못해서 이곳에도 올려봅니다.. ㅎㅎ

저는 현재 aws의 ec2서비스를 프리웨어로 1년간 이용중입니다.
ec2서비스를 이용하면서 한가지 의문점이 생겨서 질문드립니다.
먼저 인스턴스를 생성하고 elastic ip를 할당받으면 public ip와 private ip가 부여 되는걸로 알고있습니다.
제가 일반적으로 아는 공인ip와 사설ip의 개념인것같은데요. 
제 aws 서버에 아파치를 설치해놔서 public ip로 접속시 제 index페이지로 접속이 됩니다. 
putty로 제 서버 접속시에는 ifconfig시 private 아이피가 조회되구요, 여기서 의문인것은 private ip가 부여된다는것은 저 말고도 저와 동일한 public ip를 가지고있는 사람이 있다는 뜻 아닌가요?? 
제가 생각하기론 그런것같은데, 아니면 public ip와 private ip를 1:1로 매칭시켜놓은 것일까요?? 
어떻게 public ip로 접속시 포트번호를 붙여서 포워딩 해주거나 한것도 아닌데 
제 웹사이트로 접속이 될까요?? 
일반적으로 제가 아는 네트워크 개념과 다른개념을 사용하는건지 이해가 잘 안되서 질문합니다!! 
또 public, private 아이피가 제가아는 공인,사설 아이피에 대응되는 개념이 맞나요??
  
아 이건 추가적인 질문인데, ec2프리웨어를 이용하면 기본적으로 t2.micro로 인스턴스가 생성되는데, cpu credit이라는 항목이 잘 이해가 되지않습니다. 이 부분이 트래픽에 대응되는 부분인가요??

생활코딩 운영진분들~ 항상 좋은 강의 무료로 제공해주셔서 정말 감사합니다!! ^^

**Comment by blackdew** [comment]
한번 public ip가 정해지면 동일한 ip가 다른 곳에 배정이 되지는 않을거에요. public ip와 private ip를 1:1로 매칭이 되는 거죠. 그리고, 이후에 누군가 배정을 받았다가 사용을 하지 않게되어 시스템에 반환을 하게 되면, 그 때 그 public ip를 요청한 다른 사람에게 배정을 하게 되겠죠. 

public ip를 유연하게 붙였다가 뗄 수 있도록 하기 위해 이러한 방식을 사용하는 것 같습니다. 
(이건 개인적인 추측입니다.)

-------

1개의 이슈에 1개의 질문만 담는 것이 좋은 것 같아서요. 
추가적인 질문은 새로 이슈를 만들어서 올려주시면 좋을 것 같아요. :) 
질문을 새로 올려주시면 그 곳에 답을 달도록 할게요!
