### ISSUE TITLE
css를 수정했는데 예전걸로만 인식이 돼요

### ISSUE THREAD

**Issue by Duhoon** [codingeverybody/codingyahac#422]
# 해결하고자 하는 문제
html을 웹브라우저로 보면 css가 자꾸 예전걸로 인식이 되네요...

# 코드 혹은 오류
<head>
    <title>환영합니다</title>
    <link rel="stylesheet" href="stylesheet.css"/>
</head>
    <body>
        <header>
            <div class="header">
                <h2><a href="index.html">AFAC</a></h2>
            </div>
        </header>
        <nav>
            <a href="index.html" class="nonehref"><div>STYLE</div></a>
            <a href="index.html" class="nonehref"><div>LIFE</div></a>
            <a href="index.html" class="nonehref"><div>PLAY</div></a>
        </nav>
        <section>
            <div class="cotton">
                <img src="images/cotton.jpg" id="cotton_img" />
            </div>
        </section>
        <section>
            <div class="postcard"></div>
        </section>
        <footer>
            <address><a href="mailto:eclip6@naver.com" class="nonehref" id="footer_address">helf@example.com</a></address><br />
            <small>Copyright &cap; copy; 2018 JejuAlrock</small>
        </footer>
    </body>

`/*default css*/
* {
    -webkit-margin-before: 0em;
    -webkit-margin-after: 0em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 0px;
    -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
           boxsizing: border-box;
}

body{
    margin:0px;
}
.wrapper{
    display:grid;

}
.postcard {
    margin: 30px auto;
    height: 400px;
    width: 600px;
    border-bottom: 1px solid black;
}
/*header css*/
.nonehref {
    text-decoration: none;
    color: black;
}
header{
    background-color:black;
    width:100%;
    height:150px;
    width:auto;
}
header>div>h2>a{
    color:white;
    font-size:80px;
    text-decoration:none;
    margin-top:30px
}
/*nav css*/
nav {
    width: 80%;
    margin: 0 auto;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-column-start: 1;
    grid-column-end: 3;
    height: 75px;
    text-align: center;
}
nav > a > div {
        font-size:50px
    }
nav > a > div:hover{
    border-bottom:3px solid black;
}
/*content css*/
.cotton img{
    max-width:100%;
    max-height:100%;
}
.cotton{
    width:100%;
    height:400px;
    background-color:aquamarine;
    margin-bottom:10px;
}
#real{
    margin: 20px auto;
    height: 400px;
    width: 600px;
    border-bottom: 1px solid gray;
}
/*footer css*/
footer {
    display:block;
    background-color:black;
    color:white;
    bottom:0px;
    width:100%;
}
#footer_address{
    color:white;
}
#footer_address:hover{
    text-decoration:solid;
    text-decoration-color:white;
}
`

# 시도해본 방법
지금 여기에서 postcard 부분이 문제의 코드에요. 예전에 썼었던 코드입니다.
`.postcard{
    margin: 30px auto;
    height: 400px;
    width: 600px;
    border-bottom: 5px solid gray;
}`
html을 웹브라우저로 보면 매번 예전 css로 인식이 돼요. 어떻게 해결해야돼나요??

**Comment by cyppi** [comment]
웹브라우저 캐시를 없애고 다시 시도해 보세요. 
크롬브라우저라면 개발자도구에서 캐시를 없애는 설정을 할 수 있어요.
