### ISSUE TITLE
atom에서 1줄을 2줄로 보이게끔 만드는 법

### ISSUE THREAD

**Issue by oseongwon** [codingeverybody/codingyahac#423]
atom editor 에서 강의를 보면서 진행하기 때문에 화면의 반은 강의를 띄우고 반은 에디터를 띄우는데요,
반이된 에디터에서 1줄이 옆으로 쭉 이어져서 보기가 불편한데 강의에서 고잉님은 1번인데도 2번째 줄에 코드가 이어서 적히드라구요. 번호는 여전히 1번이고 밑에는 ''인데 말이죠. 어떻게 하는 건가요?

**Comment by qxbpwqdxp** [comment]
Soft Wrap 설정을 활성화하시면 됩니다.

> File > Settings > Editor > Soft Wrap 체크

**Comment by oseongwon** [comment]
감사합니다!!
