### ISSUE TITLE
코딩야학4기 8월9일(목) 방송 WEB1 나만의 도메인만들기에서 막혔습니다.

### ISSUE THREAD

**Issue by Blancware** [codingeverybody/codingyahac#425]
# 해결하고자 하는 문제
freenom.com에서 무료 도메인을 구입하여 github에 등록했습니다.
주소는 blancware.ml로 받았는데요, 이대로는 제가 만든 웹사이트로 안 넘어갑니다. (무료도메인을 생성하는 절차에서는 문제가 없었습니다.)

그래서, 도메인 뒤에 제가 만든 html파일을 기입해 봤더니 작동을 하더라구요. 

여기서 그냥 순수히 blancware.ml로 도메인을 연결시킬 방법은 없나요?

cf) blancware.ml(작동X)
     blancware.ml/Tokyo.html(작동O)

**Comment by yoobato** [comment]
```index.html``` 이라는 이름을 가진 파일을 추가하시면,
```blancware.ml``` 이 ```blancware.ml/index.html``` 을 자동으로 가리키게 됩니다 😄 

즉, ```index.html``` 파일을 추가하시면 됩니다!

**Comment by Blancware** [comment]
어디에다가 추가하면 되죠? 
추가하는 장소를 몰라서, 대표 파일인 Tokyo.html의 이름을 index.html로 바꿔 봤는데 여전히 작동을 안 해요...

**Comment by Blancware** [comment]
github에서README파일을 삭제하고 구동시켜봤더니 blancware.ml로 바로 연결됐습니다! README파일 지우는 거 괜찮은 건가요?

**Comment by yoobato** [comment]
아마 ```index.html``` 로 바꾸고 바로 시도해보셔서 그런 것 같습니다. ```index.html```로 바꾸시고 5~10분 정도 후에 시도해보시면 잘 될거에요 😄 

그리고, ```README``` 파일은 지워도 괜찮습니다.

잘 해결되셨다니 다행이에요!
