### ISSUE TITLE
IT 국내취업/해외취업

### ISSUE THREAD

**Issue by Blancware** [codingeverybody/codingyahac#426]
국내취업과 해외취업에 대해서 여쭙고 싶습니다.

비전공자 30대초입니다. 
최근 코딩야학을 통해서 코딩세계에 입문했습니다. 공부할 수록 적성에 맞아서 IT분야로 진로를 바꾸려고 취업현황(국내/해외)에 대해서 이것저것 알아보고 있습니다!

여기서 궁금한 것이 생겼는데요,
해외취업에 있어서는 '정보처리기사(자격증)'를 취득해야 한다고 하더라구요. 
그런데 이 곳 여러분들이 말씀하시길 자격증은 현장에서 의미가 없는 것이라는 하십니다만..
*'정보처리기사 자격증 취득 유무'가 비자발급을 위한 수단으로서만 쓰이는 것 인지요? 

정보가 없는 제가 보기에는 무엇을 공부하고 준비해야하는 지 판단이 서질 않아서요..

앞으로 공부할 것들이 많아서 가장 필요한 것들만 추리고 싶습니다.

국내취업과 해외취업에 있어서 가장 기본적으로 갖춰야 할 스킬(언어, 자격증?)이 무엇인지 알려주시면 감사하겠습니다!

관심있는 분야는 빅데이터분야 입니다.

잘 부탁드립니다!

**Comment by cyppi** [comment]
개인적으로는 외국에 직장을 구해본적이 없어서 국내 기업위주(그것도 스타트업위주로)로 설명을 드리면, 취업하려고 하는회사가 국가기관이나 SI등을 많이 하는 곳이라면 자격증이 중요할 수 있습니다. 
그렇지 않다면 자격증보다는 그간의 경험이나 다루는 언어에 따라서 많이 달라질 수 있습니다. 
그렇다고 특정언어가 개발자 직군에서 아주 유리하다고 할 수 없습니다. 

아마도 취업을 준비하는 입장에서는 마음편하게 한가지에 집중하기는 어려울거 같습니다. 특히나 외국으로 가는경우라면 기술적인 내용을 준비하면서 언어적인 부분도 신경써야 할거 같기 때문입니다.

**Comment by Blancware** [comment]
해외취업은 일본취업을 생각하고 있습니다.  감사합니다.^^
