### ISSUE TITLE
카카오톡 대화명 같은...!

### ISSUE THREAD

**Issue by LeescNote** [codingeverybody/codingyahac#429]
예를 들어 카카오 대화명 같은것?

자신의 상태 메세지 같은 걸 남기는 것은 어떻게 하나요?  == (네이트온 시절 우측 상태 메세지)

유저들이 각자 로그인을 해서 자신의 상태메세지를 쓴다면 그게 저장이 되고 올라와 있는것인데 

nodejs로 되는 건가요? ? ? ?  그것들은 뭘로 만들어지는 건지 궁금하네요.. 

// 사용자가 자신의 상태 (글) 을 올렸을 때 저장이 되서 
글이 그대로 올라와 있는 거는 어떻게 해야 하는거죠? ? ?

**Comment by cyppi** [comment]
어렵게 생각할거 없이 사용자의 아이디를 저장하면서 데이터베이스에서 상태메세지 한줄더 저장하면 될거 같아요. 
그래서 아이디 아래에 약간 작고 흐릿하게 보여주면 될듯 합니다.
그런것들은 어떤 언어나 프레임웍을 쓴다기보다는 데이터베이스에 저장됩니다. 물론 nodejs로 연결해서 보여줄 수도 있어요 ㅎㅎ

**Comment by LeescNote** [comment]
답변 감사합니다!
