### ISSUE TITLE
웹사이트 설계 단계나 절차에 대해서 여쭤보고 싶습니다.

### ISSUE THREAD

**Issue by PassionOfStudy** [codingeverybody/codingyahac#43]
안녕하세요. 
공유경제라는 컨텐츠를 가지고 웹사이트를 구현해보려고하는 햇 병아리입니다! ^_^
(3일 시작인데... 이틀 늦은 5일 새볔에 시작하게 되었습니다. 늦은만큼 열심히 해보려고요 ㅠㅠ)

질문드리겠습니다.
이왕 웹사이트를 제작하는거  실제 설계단계나 절차에 따라서 진행해보고싶은데요,
현업에서는 웹사이트를 설계하고 제작할 때 어떠한 모델을 참고하여 구축하시는지 궁금합니다.

인터넷을 검색해 보니 웹사이트 설계단계는 크게 6단계로 나눠볼 수 있다고하는데
1단계) 정보수집과 확인
2단계) 기획
3단계) 디자인
4단계) 개발
5단계) 테스트, 인도 및 론칭
6단계) 유지보수

제가 검색한 정보가 맞는지  궁금하고, 
혹시 이와 관련한 도서나 자료있으시면 추천 부탁드립니다.
바쁘신데 시간 내주셔서 감사합니다! ^^

**Comment by egoing** [comment]
보통 3,4번을 순차적으로 하기도 하고요. 

3번과 4번의 백엔드 작업을 동시에 진행하고, 
3번이 끝나면 4번의 프론트 엔드 작업이 진행되는 경우도 많습니다. 

그런데 중요한 것은 저런 순서는 협력 작업 때문에 존재하는 것이라고 생각해요. 사실 이상적인 것은 순서와 필요에 따라서 일을 처리해가는 것이죠. 개인 프로젝트라면 저런 순서는 중요하지 않은 것 같다는 저의 사견입니다~

**Comment by PassionOfStudy** [comment]
아하 협력작업에 필요한 것이었군요. ^^ 너무 거창하게 시작하려고 했던 것 같네요.
첫 개인프로젝트인 만큼 뭔가 완벽하게 해내게 싶은 마음이 컸던 것 같습니다. 
좋은 답변 감사드립니다! ^_^
