### ISSUE TITLE
iot / arduino / 임베디드

### ISSUE THREAD

**Issue by rakaill** [codingeverybody/codingyahac#430]
코딩야학 프로젝트중 아두이노를 이용해서 iot를 구현해 보았는데요. 작동에는 전혀 문제없이 예전에 만들어놓은 코드들을 불러와서 만들었습니다. 프로그래밍에 대해서도 아직 모자란 부분이 많아 앞서간다고도 느끼긴 하지만 예전부터 하고싶었던게 직접 회로를 설계하고 코드를 작성하여 나만에 무언가를 만들어 보는것이라  어셈블리어와c,java=>전자회로 와 회로이론 => 커널,아키텍쳐 와 부트로더 이순서대로 공부하려고 하는데 모자라거나 바꿔야할 부분이 있을까요?

**Comment by cyppi** [comment]
말씀하신내용을 다하면 모자람이 없을거 같아요. ㅎㅎ 
다만 IOT관련 내용은 하드웨어적인 부분과도 연동되는만큼 LED를 연결하거나 스위치를 달고, 배터리를 연결하는등의 작업과 기구를 만드는 것같은 일들을 무리없이 섞어서 진행할 수 있으면 될거 같아요.

**Comment by studroid** [comment]
물론 말씀하신 것들을 알고 있으면 굉장히 도움이 되겠습니다만, 학자가 되거나 당장 제품을 양산할 수준을 목표로 하시는 게 아니라면 아래 사이트의 커리큘럼을 따라가보셔도 좋을 듯합니다.

https://kocoafab.cc/product/studyguide

저도 제품 개발 시작할 때 참고하곤 했던 곳인데, 정리가 정말 잘 되어 있습니다. :)
회로 들어가는 부품들은 어떤 종류가 있으며 어떤 역할을 하는지를 잘 이해하고, 이를 제어하는 방법을 이해한 상태로 간단한 알고리즘 지식을 더한다면 생활에 필요한 대부분의 제품들은 만드실 수 있습니다.

여기에 더 필요한 건 문제를 발견하는 능력과 창의적인 해결 방법이겠죠! ㅎㅎ

**Comment by egoing** [comment]
@studroid 오 저도 그걸로 공부해봐야겠네요. ㅎㅎ

**Comment by studroid** [comment]
더 질문이 있으시거나 얘기해보고 싶은 게 있으시면 다시 열어주세요! :)
