### ISSUE TITLE
w3 사이트에 있는 템플릿을 그대로 써도 저작권위반과 같은 문제가 생기지 않나요?

### ISSUE THREAD

**Issue by YangHyojeong** [codingeverybody/codingyahac#431]
제 주제를 가지고 웹사이트를 만드는 중입니다 
그러다 w3에 있는 예시템플릿을 보고 맘에 들어
그 템플릿을 주로 하여 웹사이트를 만들었는데요.
혹시 저작권 쪽...? 과 같은 문제가 있나요?

기술 방향의 문제는 딱히 아닌 것 같아서 이쪽에다 질문 드립니다.
수고하세요 감사합니다 :)

**Comment by cyppi** [comment]
w3 는 https://www.w3schools.com/ 여기를 의미하는것인가요?

**Comment by YangHyojeong** [comment]
넵 죄송해요 w3school 저 사이트 맞습니다ㅠㅎㅎ

2018년 8월 10일 (금) 오후 8:47, cyppi <notifications@github.com>님이 작성:
