### ISSUE TITLE
이고잉님께서 여기로 오면 대답해 주신다고 해서 질문합니다

### ISSUE THREAD

**Issue by pshoon922** [codingeverybody/codingyahac#432]
# 해결하고자 하는 문제
제가 만든 깃허브 웹페이지를 수정 또는 삭제하려면 어디로 가야하죠?

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법
설정을 들어가보고 계속 새로운 웹을 만들다 지쳐서 수정하는 법을 질문합니다ㅠ

**Comment by cyppi** [comment]
제가 고잉님은 아니지만, 답변을 드리면, 
두가지 방법이 있어요. 
우선적으로는 git으로 만드신 내용을 컴퓨터에 받아서 코드를 고치고, 다시 커밋/푸시 하는 방법입니다. 이방법은 git을 알아야하지만, 보통의 개발자들이 소스코드를 수정해서 공유하는 방식입니다. 
두번째 방법은 깃헙이라서 가능한 방법인데, 깃헙의 해당 프로젝트로 가셔서 html 파일을 직접 수정하는 방법입니다.(옆에 연필아이콘을 클릭하시면 파일을 수정해서 저장할 수 있습니다.
더궁금한 내용은 아래 다시 질문해 주세요 ㅎㅎ

**Comment by pshoon922** [comment]
연필 아이콘을 클릭했는데 1번에 제가 쓴 웹의 제목 만 나옵니다. 파일 삭제는 어디서 하나요?

**Comment by pshoon922** [comment]
죄송하지만 휴지통 아이콘을 못 찾겠습니다..
Your Repsitories에 들어가서 찾는 것이 맞죠?

**Comment by pshoon922** [comment]
아 아닙니다
휴지통 아이콘을 찾은 것 같네요ㅎㅎ 
늦은 시간까지 답변해주셔서 갑사합니다.
