### ISSUE TITLE
seomal.org 사이트 만드는 방법 질문

### ISSUE THREAD

**Issue by donghwan2** [codingeverybody/codingyahac#433]
# 해결하고자 하는 문제
seomal.org 사이트처럼 포트폴리오를 만들고 싶습니다.
어떻게 만들어야 하는지, 관련된 강의가 있는지 궁금합니다!

항상 감사합니다 :)

**Comment by yoobato** [comment]
소스를 확인해보니, @egoing 님께서 만드실 때, ```Cytoscape.js```라는 라이브러리를 사용하신 것 같아요.

아래 주소 들어가셔서 한 번 확인해보시면 좋을 것 같습니다 😄 
http://js.cytoscape.org/

**Comment by egoing** [comment]
곧 수업으로 만들께요! 그래프 이론도 준비하고 있습니다.
