### ISSUE TITLE
웹사이트 도메인을 사는 것과, 코드의 저장 위치 에 대해 궁금합니다.

### ISSUE THREAD

**Issue by hanbin7011** [codingeverybody/codingyahac#44]
Html,css,javascript를 통해 코딩을 한후, 그 웹페이지를 런칭하려고 하는 부분에대해 궁금합니다.

보통 내가 코딩한 코드들은 어디에 저장을 하고 

도메인과 어떻게 연결을 해서 웹사이트를 상업화 하나요/??

감사합니다.

**Comment by smartbos** [comment]
생활코딩 강좌 중 인터넷에 관한 내용을 들어보시면 도움이 되실 것 같아요.
https://opentutorials.org/course/1688/9483
