### ISSUE TITLE
javascript, nodejs 코드 실행 순서

### ISSUE THREAD

**Issue by goldentrash** [codingeverybody/codingyahac#447]
# 궁금한 내용
코드의 실행 순서가 자연스럽게 윗줄에서 차례대로 아랫줄이라고 생각해 왔습니다. 그런데 코드를 실행시켜보니 그렇지 않은 것 같아요. 혹시 제가 오해를 하고 있는건지, 아니면 이게 당연한 것인지 궁금합니다. 그리고 만약 실행 순서가 윗줄에서 아랫줄이 아닌 특정한 규칙을 따른다면 그 규칙이 궁금합니다.
 (제가 그 규칙을 활용할 수 있도록이요)

# 코드 혹은 오류
```
const fs = require('fs');
var num = 'he';
console.log(num)
function start(){
    fs.readFile('./list.text', 'utf8', function(err, data){
        num = 'she';
        console.log(num)
    })
    fs.readFile('./diary/0810.text', 'utf8', function(err, data){
        num = 'they';
        console.log(num)
    })
    num = 'we';
    console.log(num)
}
start();
num ='?';
console.log(num)
```

# 결과
```
he
we
?
she
they
```
# 제가 의도한 결과
he
she
they
we
?

# 환경
nodejs코드입니다. (8.11.3 버전)
본문 내용을 2개 이상의 외부파일에서 가져오는 코드를 작성해 보다가 계속해서 원치 않는 결과가 나와서 즉시 테스트용으로 수정한 코드라 변수나 함수 등이 매끄럽지 못한 점 죄송합니다.

**Comment by goldentrash** [comment]
정말 신기한 개념이네요! fs.readFile의 경우에는 (제가 코딩하진 않았지만) '파일을 읽는다'라고 하는 오래 걸리는 일이 처리되고, 그 시간동안 제 코드의 다른 부분이 실행되다가, '파일을 읽는다'라고 하는 일이 마무리되면 3번째 인자인 콜백이 실행되는거네요. (readFile함수의 마지막 줄이 콜백 호출부분인가 보네요)

그런데 그러면, nodejs에서는 '동시에, 여러 줄의 코드를 실행'시키고 있는 것인지요? 만약 그렇다면 어떤 코드들을 한 번에(동시에) 처리하는 건가요? 제가 너무 깊게 파고드는 걸까요? 이 내용을 공부하려면 어떤 키워드로 검색을 해야 할까요?

**Comment by blackdew** [comment]
nodejs 내부구조를 알려주는 블로그 링크에요. :) 
http://bcho.tistory.com/881

**Comment by goldentrash** [comment]
많은 도움 되었습니다. 감사합니다!
