### ISSUE TITLE
솔리디티 컨트랙트

### ISSUE THREAD

**Issue by songpang** [codingeverybody/codingyahac#449]
# 해결하고자 하는 문제
솔리디티에서 컨트랙트를 작성하고 나서 그 컨트랙트를 토큰에 적용하고 싶을때 어떻게 해야하나요 ??
예를들어서 A라는 기능의 스마트 계약을 위한 컨트랙트를 만들고 토큰이 교환될때 마다 적용하고 싶은것
(토큰이 교환될때마다 무슨 기능이 작동하는 컨트랙트)이 있다고 할때 
이 컨트랙트를 사용하려면 그냥 token에 상속만 하면 되는건가요?? 어떻게 해야하는지 도저히 모르겠어요 ㅠㅠ

++) 그리고 기본 openzeppelin에 들어있는 컨트랙트들의 함수들이 있는데 이 함수들 이름을 바꾸면
예를들어 transfer을 transferone이라고 바꾸면 사용하지 못하는것인가요? (호환이 안되서?)
(transfer같이 무조건적으로 있어야하는 함수 말고라도 다른함수들도??)

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
솔리디티

# 시도해본 방법
X

**Comment by studroid** [comment]
먼저 토큰을 사용하는 대표적인 예시인 Crowdsale 컨트랙트(ICO용)를 보시면 도움이 될 듯합니다.
링크: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/examples/SampleCrowdsale.sol

위 예시에서 보실 수 있듯이, 일반적으로 많이 사용되는 방식은 토큰은 토큰 자체를 컨트랙트로 만들고, 이를 다른 컨트랙트에서 포함하여 특정한 함수가 불릴 때 토큰을 주고 받는 로직을 사용하는 것입니다.

물론 토큰 컨트랙트의 함수에 특정한 로직을 추가해 넣을 수도 있겠지만(교환이 될 때마다 어딘가에 기록하거나 이벤트를 발생시키는 등), 대부분 토큰 자체에서 필요한 것들은 OpenZeppelin에서 제공하는 컨트랙트들이 안전하게 제공하므로 그저 이를 상속하여 쓰는 경우가 많습니다.

크라우드세일 또는 ICO 컨트랙트로 검색하셔서 나오는 것들을 위주로 한번 따라서 만들어보시고, 이후 원하시는 로직을 구현해보시면 좋을 듯하네요 :)


++ 답변) ERC20은 확정된 토큰 표준이라, 함수명을 마음대로 바꾸시면 다른 곳에서 이를 쉽게 활용하지 못합니다. 즉, ERC20 표준을 지키면 거래소 등에서 내 토큰 컨트랙트가 어떻게 생겼는지 몰라도 쉽게 상장을 시킬 수 있고, 다른 사람들도 이를 활용하는 또 다른 컨트랙트를 쉽게 개발할 수 있습니다. 표준을 지키지 않으면 다른 사람들이 내 토큰을 쉽게 쓰기 힘들 것이고, 그럼 엄청난 가치를 처음부터 가지지 않는 한 잘 안 쓰일 확률이 높겠죠 ㅎㅎㅎ

또 질문이 있으시면 새로운 글을 등록해주세요! :)
