### ISSUE TITLE
Firebase Vs mysql

### ISSUE THREAD

**Issue by hanbin7011** [codingeverybody/codingyahac#45]
안녕하세요 firebase와 mysql의 차이를 알고 싶습니다.

현재 앱을 firebase통해 만들고 있는데,

firebase는 mysql보다 많은 사용자의 데이터를 사용하기 부적합하다는 말을 들어서요.

firebase의 앞으로의 전망과 장단점을 비교해서 알수 있을까요:??

**Comment by egoing** [comment]
두가지 기술을 모두 사용해본 입장에서 경험한 가장 큰 차이는
mysql은 관계형 데이터베이스이고, firebase는 아닙니다. 

관계형 디비는 서로 다른 분류(테이블)로 묶인 데이터를 join을 통해서 매우 쉽게 재생산을 할 수 있습니다만, firebase는 key->value 기반이고, join을 지원하지 않습니다. 

이런 차이로 관계형 디비는 데이터의 성격에 따라서 분류해서 저장을 하는데, firebase는 데이터를 어떻게 사용할 것인가에 따라서 저장을 하게 됩니다. 즉 firebase는 애플리케이션의 형태에 매우 의존적인 정보구조를 갖게 된다는 것이죠. 

저는 이런 점에서 firebase와 같은 nosql에 대해서 아쉬움이 컸습니다. join을 너무 하고 싶어요. ㅠㅠ 

https://yah.ac이 firebase로 만들어진 서비스이고요. 

반면에 firebase는 실시간 데이터베이스가 된다는 mysql은 따라올 수 없는 비대칭 경쟁력을 가지고 있죠. 

이 정도로 답변 드려봅니다. close를 해드릴께요. 혹 추가로 궁금하신 점이 있으시면 open해주세요~

**Comment by hanbin7011** [comment]
실시간 데이터베이스가 된다는 말의 의미는 무엇인가요?

**Comment by egoing** [comment]
db의 내용이 변경되면 웹페이지의 내용이 동시에 변경됩니다. 마법처럼요. 
이걸로 구글 스프레드쉬트나 채팅 같은 것을 아주 쉽게 만들 수 있답니다.

**Comment by Patrick386** [comment]
검색기능이 한 페이지라도 있다면 firebase 는 절대 사용하지 마세요. 
full text search 를 지원하지 않습니다. 이 작은 차이가 만들고자 하는 앱 전체에 영향을 끼치게 됩니다.
업무용, 쇼핑몰 등등 일반적인 사업용 앱 절대 만들 수 없답니다.
특히 구글이라는 점이 가장 취약합니다. 코어 기술자가 없습니다. 
MS 솔루션으로 가고, 시간낭비 하지 마세요.
