### ISSUE TITLE
python을 이용한 웹파싱에 어려움이 있습니다.

### ISSUE THREAD

**Issue by walangland** [codingeverybody/codingyahac#451]
# 해결하고자 하는 문제

특정 웹사이트에서 웹파싱을 하려고 하는데, 크롬의 개발자도구를 통해서는 보이는 HTML 소스들이 파이썬을 이용해 파싱을 하면 보이지 않습니다.

url : http://www.r114.com/?_c=lots&_s=lotsSchedule&_m=lotsSchedule

위 사이트에 접속하면 뜨는 '2018년,8월'에 포함된 코드가 아래와 같음을 확인할수 있습니다. 
```
<span class="ui-selectmenu-text">2018\</span>

<span class="ui-selectmenu-text">8\</span>
```
하지만 파이썬을 통해 파싱한 결과에서는 찾을수 없습니다.

또한 파싱 결과로 나오는 HTML 소스에서는
```
<tbody id="lotsInfoList">
</tbody>
```
라고만 나오는데, 개발자 도구를 이용하여 확인한 소스코드에서는 \<tbody> 태그아래로  child인 \<tr> 태그가 굉장히 많이 있는데, 다 생략되어 나오네요..
혹시 해당 태그들을 포함하여 결과로 출력할 수 있을까요?

# 코드 혹은 오류
```
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup

url = 'http://www.r114.com/?_c=lots&_s=lotsSchedule&_m=lotsSchedule'
html = urllib.request.urlopen(url).read()
soup = BeautifulSoup(html, 'html.parser')
print(soup) 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
OS : windows10 
언어 : Python3.6
라이브러리 : urllib, BeautifulSoup4

**Comment by blackdew** [comment]
웹페이지를 브라우저 입장에서 구분을 해보자면 
"정적인 페이지", "동적인 페이지"로 구분을 할 수 있는데요. 

"정적인 페이지"는 서버에서 완성된 html을 만들어서 보내줍니다. 
때문에 서버에서 보내주는 시점에서 완성된 html 태그들을 확인할 수 있죠. 

반면에, "동적인 페이지"는 서버에서 아직 완성되지 않은 html과 javascript코드를 보내줍니다. 
브라우저는 javascript 코드에 적혀진 대로 실행을 시켜서 html코드를 "동적"으로 완성시키죠. 
때문에 서버에서 보내주는 시점의  html 코드를 아무리 확인을 해도 "동적"으로 완성해야 하는 부분의 html 코드를 볼 수가 없는 겁니다. 

위에 적어두신 코드에서 해당하는 부분을 완성하려면, javascript 코드를 실행히켜서 html 코드를 완성하는 작업을 해야 하는 것이죠. 그런데 javascript 코드를 직접 실행하는 코드를 만들기란 너무 어려운 일이에요. 그래서 이를 쉽게 해주는 selenium이라는 라이브러리가 있어요. 

아래는 selenium 공식 페이지에요. 
http://selenium-python.readthedocs.io/
아래는 튜토리얼을 쉽게 알려주는 블로그입니다. 
https://beomi.github.io/2017/02/27/HowToMakeWebCrawler-With-Selenium/

참고하셔서 완성하시면 되겠습니다. :)
