### ISSUE TITLE
라즈베리파이에 비트나미 관련된 질문입니다.

### ISSUE THREAD

**Issue by Loooooader** [codingeverybody/codingyahac#453]
# 해결하고자 하는 문제
라즈베리파이에 비트나미와같은 소프트웨어를 한번에 설치 할 수 있는 방법이 있나요?

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
라즈비안 4.14

# 시도해본 방법
sudo apt-get install apache2
sudo apt-get install php5
sudo apt-get install mysql-server php5-mysql

**Comment by cyppi** [comment]
위에서 실행하신 방법이 비트나미와 같은 내용입닙다. 
물론 비트나미는 한번에 쉽게 설치해 주긴 하지만, 라스베리에서 설치하는것과 내용이 다르진 않습니다. 
위의 명령어를 실행하셨다면 아마도 php, mysql, apache2가 설치되어 있을것입니다. 
비트나미와는 다른 파일구조라서 쉽게 익숙해지지는 않겠지만, 라스베리에서 시도한다면 각각의 서버를 위의 명령어를 사용하여 설치해야합니다. 
이후에 설정파일은 /etc 디렉토리 밑에서 살펴보고, service 명령어를 사용해서 각각의 서버를 시동시키거나 정지시키면 될거 같습니다. 
그럼 매력적인 라스베리에서 재미나게 즐기시길 바래요

**Comment by Loooooader** [comment]
친절한 답변 감사드립니다!
