### ISSUE TITLE
Git structure - 클라이언트/서버 소스를 하나의 repository로 관리하는 것과 분리하는 것 어느 쪽이 좋은가요? 

### ISSUE THREAD

**Issue by jdragonbae** [codingeverybody/codingyahac#46]
안녕하세요! 코딩야학 3기를 통해 정말 많은 것을 배우고 있습니다.

Happy new project로 진행하는 ios/android/server에 대해 형상관리로 git을 사용하려고 합니다.

보통 각각의 클라이언트/서버를 github프로젝트로 만들어서 관리하는지 혹은 하나의 github프로젝트에서 디렉토리 형식으로 진행하는지 궁금합니다.

답은 없겠지만 조언부탁드립니다!!

감사합니다.

**Comment by blackdew** [comment]
개인이나 소규모 인원이 작업하는 것이라면 굳이 분리할 필요는 없는 것 같아요. 
폴더로 구분해서 한꺼번에 관리해도 크게 불편한 점이 없을 거에요!

**Comment by progh2** [comment]
저라면 git이라면 브랜치로 나누어 관리하는 것도 방법일 것 같습니다. =)
이슈는 흐름은 공유하면서 커밋은 브랜치별로 나타나니까요. 

하나의 프로젝트에 디렉토리로 모두 몰아서 관리할 경우 이슈와 커밋이 같이 올라와서 거대 프로젝트면 복잡해질 수 있을 것 같습니다. 반면 프로젝트를 분리해서 하면 각 상황을 보기 힘든 면도 없지 않고요. 물론 프로젝트가 커지면 분리하는게 맞겠습니다.

**Comment by jdragonbae** [comment]
답변 감사합니다 ^^
