### ISSUE TITLE
자바스크립트에서 줄바꿈 어떻게 하나요?

### ISSUE THREAD

**Issue by Jiyong-Jung** [codingeverybody/codingyahac#467]
# 해결하고자 하는 문제
자바스크립트를 실행하기 위해 <script> 태그를 사용해서
그 안에서 document.write 엘리먼트로 여러 값들을 출력을 하는데
줄바꿈이 안 되고 그냥 한 줄에 붙어서 출력이 되더라고요...

자바스크립트에서 줄바꿈을 하려면 어떻게 해야 하나요?

p.s) 인터넷을 좀 찾아보니
document.createElement("br");
이런 식으로 엘리먼트를 먼저 새로 만들라고 하던데,
이렇게 만든다고 해도 저 엘리먼트를 실행하는 방법은 또 어떻게 되는지 못 찾겠어서 막혀 있네요...

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by ghdalsrldi** [comment]
```javascript
document.createElement("br"); 
```
는 엘리먼트를 생성하는 메소드입니다.
생성 후 다른 엘리먼트 안에 넣어야 하는데요
```javascript
// 엘리먼트 생성
var br = document.createElement("br");
// 생성된 엘리먼트 추가
document.body.appendChild(br);
```

이런식으로 사용해 주시면 됩니다.

혹은 
```javascript
document.write('내용을넣어주세요<br>여기는 다음줄 입니다.');
```
이렇게 내용안에 br태그를 넣어서 줄바꿈을 해 주셔도 됩니다.
