### ISSUE TITLE
web3 phpmysql 활용-글 읽기 부분에서 이해가 안된부분이 있어서 질문드립니다

### ISSUE THREAD

**Issue by Led001** [codingeverybody/codingyahac#473]
궁금한게 있습니다!!
```
$conn = mysqli_connect(
  'localhost',
  'root',
  '111111',
  'opentutorials');
 $sql = "SELECT * FROM topic";
$result = mysqli_query($conn, $sql);
$list = ' ';
while($row = mysqli_fetch_array($result)) {
  $list = $list."<li><a href=\"index.php?id={$row['id']}\">{$row['title']}</a></li>";
}
```
 이 코드에서 
```
$list = '';
while($row = mysqli_fetch_array($result)) {
  $list = $list."<li><a href=\"index.php?id={$row['id']}\">{$row['title']}</a></li>";
} 
```
이부분에 대해서 이해가 안가서 그러는데요 
왜 변수 값에 $list=' '; 이렇게 하는건지 궁금합니다 특별한 기능이 있는건가요?

그리고 $list=' ' ; 이걸 빼고 

그냥 
```
while($row = mysqli_fetch_array($result)) {
  $list = "<li><a href=\"index.php?id={$row['id']}\">{$row['title']}</a></li>";
}
``` 
이렇게 해보니깐 출력이 한 줄만 나오던데   왜 그러는건지 궁금합니다! 
```$list =$list. "<li>~~~</li>"```
왜 이렇게 $list=' '; 를 결합 해야지 데이터들이 다 출력이 되는거죠??

**Comment by yorez** [comment]
while문 안에서 list변수를 공란으로 선언하시면 반복될 때 마다 list변수가 공란으로 시작하지 않을까요?!! :-)

**Comment by Led001** [comment]
글쎄요 아직도 의문이네요! 
왜 공란을 해야지만  배열에 담긴 전체 갯수가 다 출력되는건지 모르겠습니다 ㅠㅠ 
공란을 빼고 그냥 해보니깐 전체 갯수중에 한개만 나오공 왜 이러는 거죵?!

**Comment by yorez** [comment]
while($row = mysqli_fetch_array($result)) {
  $list = "<li><a href=\"index.php?id={$row['id']}\">{$row['title']}</a></li>";
}
말씀하신 위 방식은 매번 $list변수에 새로운 값을 넣고 있는 거에요! 
$list=$list+"<li><a href=\"index.php?id={$row['id']}\">{$row['title']}</a></li>"와 같은 형태로 처리해야하지요.

. 기호는 변수가 중복적으로 등장하지 않게 하기 위한 용도로 사용합니다. :-)
$list=$list+1과 $list.=1은 동일한 의미 입니다.

**Comment by Led001** [comment]
오홍!!! 답변주셔서 감사합니다!!! 많은 도움이 되었습니다!!!!! 
그럼요 var a = ' ' ;    이런 경우는  a 변수에 공백 문자열 데이터 타입이 대입 됐다는 뜻 인가요? 아님 어떤 특별한 기능이 있는건가요?  다름이아니라 ``` var a='1';   a+='1';   a+='1'; ``` 이경우에는 몇번을 출력해도 '111' 만 출력되는데  반면  ``` var a;   a+='1';   a+='1'; ```  이 경우에는 출력 할때마다 값이 증가 됩니다  
'111'  --> '1111'  ->'11111'  이렇게 됩니다 !  이게 개념이 잘 안잡힙니다 ! ㅠ.ㅠ

**Comment by Led001** [comment]
오홍!!! 답변주셔서 감사합니다!!! 많은 도움이 되었습니다!!!!!
그럼요 $ a = ' ' ; 이게 데이터 타입이 문자열인 공백이란 값이 들어있다는 건가요
아님 그냥 $a=null 이란 뜻 인가요? 아님 $a 의 데이터 타입은 문자열이라고 선언 해주는 건가요?

**Comment by yoobato** [comment]
@Led001 

말씀하신 것처럼, `$a = '';` 은 공백 문자열(empty string)이라는 뜻입니다. 이는 `NULL`과는 다릅니다.

아래 링크 참고해보세요!

https://stackoverflow.com/questions/5615747/what-is-the-difference-between-null-and-empty

**Comment by Led001** [comment]
링크 들어가보니 질문자가 저랑 비슷한 혼돈을 겪었네요!!  
emty 와 null 에 대해서  개념이 잡히도록 더 공부해야겠습니다!  
위에 두분 제 질문에 답변 주셔서 너무 감사합니다 정말 많은 도움 됐습니다!  
감사합니다! 담에도 부탁드리겠습니다!

**Comment by Led001** [comment]
제가 더 많이 부탁을 헤헤 .. 프로그래밍이 너무 어렵네요  이해도 잘 안되고 

그나저나 c언어를 건너 뛰고 자바를 먼저 배워도 될련지 고민이네요 다들 물어보니까 

c언어를 공부하고  기초를 다지고 넘어가야된다고 하길래 고민이네용!! 어떻게 해야될련지! 

정작 지금 php 도 다 모르는데요 헤헤

**Comment by yoobato** [comment]
@Led001 

저는 지금 회사 일을 하기는 하지만, 대학에 재학중입니다.

저희 학교가 원래는, `컴퓨터프로그래밍(C) -> 객체지향프로그래밍(C++)` 이였는데,
최근에 다시 확인해보니까, `컴퓨터프로그래밍(Python) -> 객체지향프로그래밍(Java)`로 바뀌었더라구요.

참고하시면 좋을 것 같습니다 😄

**Comment by Led001** [comment]
오오 그렇군요!! 파이썬부터 해봐야겠네요!  일단 php 부터 자유롭게 구사 할 정도로 익힌다음 도전 해보겠습니다! 위에 두분 제가 팔로우좀 했어요!! 헤헤  
아 그리공  회원가입 로그인 페이지 만들고 있는데   메인 페이지인 index.html 화면에서 로그인이나 회원가입 버튼을 누르면 php 화면으로 넘어가서  완료한 다음  다시  메인 페이지 index.html 으로 보내서  로그인 회원가입 버튼이  누구누구님 환영합니다로 바꾸고 싶은데  이거 어떻게 구현 해야되나요?

**Comment by Led001** [comment]
오오 그렇군요!! 파이썬부터 해봐야겠네요!  일단 php 부터 자유롭게 구사 할 정도로 익힌다음 도전 해보겠습니다! 위에 두분 제가 팔로우좀 했어요!! 헤헤  
아 그리공  회원가입 로그인 페이지 만들고 있는데   메인 페이지인 index.html 화면에서 로그인이나 회원가입 버튼을 누르면 php 화면으로 넘어가서  완료한 다음  다시  메인 페이지 index.html 으로 보내서  로그인 회원가입 버튼이  누구누구님 환영합니다로 바꾸고 싶은데  이거 어떻게 구현 해야되나요? 
네이버 회원가입 로그인처럼 말이죠

**Comment by yoobato** [comment]
@Led001 

`HTML` 파일로는 해당 기능을 구현하기 어렵습니다. `PHP`를 사용하셔야 합니다.

`index.php`에,
```php
<?php
  if ($logged_in) {
?>
    <div><?php echo $name; ?>님 환영합니다.</div>
<?php
  } else {
?>
    <form method="POST" action="login.php">
      아이디: <input type="text" name="user_id" /><br />
      비밀번호: <input type="text" name="user_password" /><br />
      <input type="submit" value="로그인" />
    </form>
<?php
  }
?>
```
이런식으로 구현을 해놓고,

`login.php`에,
```php
<?php
  $user_id = $_POST['user_id'];
  $user_password = $_POST['user_password'];

  if ($user_id == OOO && $user_password == OOO) {
    echo "<script>location.href='index.php?logged_in=1&name=OOO';</script>";
  } else {
    echo "<script>alert('로그인 실패'); location.href='index.php';</script>";
  }
?>
```
이렇게 하는 방법이 있습니다. (회원가입 또한 유사합니다)

물론 이건 정말 간단한 예제이며, 실제로는 `session` 등을 활용하여 로그인을 구현합니다.
네이버의 경우에는 더 복잡하겠지요 😄

**Comment by Led001** [comment]
그렇군요! 바토님이 적어주신 코드로 응용해봐야겠습니다 감사합니다!
그럼요 네이버에서 로그인 하면  메인페이지에서 로그인 정보 이메일 등등 우측에 표시가 되는데이거는 ajax 아님 자바스크립트로 쿠키를 읽어 들여서 표시하는건가요? 
 url은 naver.com 달랑 이것만 있어서 메인페이지는 html 인가 라는 생각이 들어서요

**Comment by yoobato** [comment]
@Led001 
답장이 늦어 죄송합니다.

말씀해주신 두 가지 방법 모두 가능합니다.

1. Ajax를 사용하여, 동적으로 계정 정보를 불러와 보여주는 방법. (로그인 여부를 클라이언트에서 구분)
2. 처음부터 html 을 만들 때부터, 계정 정보를 넣는 방법. (로그인 여부를 서버에서 구분)

1번의 경우, 클라이언트에서 access token과 같이 로그인된 사용자를 구분할 수 있는 정보를 가지고 있을 때 사용할 수 있습니다. 우선 화면을 먼저 만들어 뿌려주고, 그 다음 서버에 계정 정보를 요청해서 불러와 보여주는거지요. (React라고 하는 것이 이러한 방식으로 동작하는 것으로 알고 있습니다.)

2번의 경우, 보통 로그인 인증으로 세션을 사용할 때 많이 사용하는 방법인데요. 사용자가 로그인했는지 안했는지에 대한 구분을 클라이언트가 아니라 서버가 하게 됩니다. 따라서, 로그인한 사용자한테는 로그인/회원가입 버튼이 있는 html이 아니라, 계정 정보가 담겨져 있는 html을 뿌려주는 것이지요!

**Comment by Led001** [comment]
아닙니다 답변 신경 써주셔서 너무나 감사할뿐입니다!!ajax 로 로그인 기능 계속 풀어 나갈려고 하다가 잘 되지 않아서 일단은  접어두고  php만으로 풀어나갈려고 합니다 그런데 답변을 보고 다시 한번 도전 해봐야겠네요!! 어렵네요!! 자바스크립트 mysql php java 이렇게 동시에 공부하고있는데 잘하고 있는건지 모르겠네요그냥 한가지씩 어느정도 다 끝내놓고 공부를 진행할까 생각중입니다. 아 그리고 php 로그인 기능을 코딩하고있는데 이게 왜 이러는지 모르겠네용!/*session_start();require_once('../lib/conn.php');$join=connect();$id = trim(htmlspecialchars(($_POST['id'])));$pwd = trim(htmlspecialchars(($_POST['pwd'])));$query="select id,pwd from user where id=? and pwd =?";$smt=$join->prepare($query);$smt->bind_param('ss', $id, $pwd);$smt->execute();$smt->bind_result($gm,$fg);$smt->fetch();if($gm != $id){echo 'not id';if($fg != $id)echo 'not pwd';}$smt->free_result();*/이렇게 로그인 코드를 짜봤습니다... 아이디가 틀릴경우 아이디를 입력해주세요 패스워드가 틀리면 패스워드를 입력 해주세요 라는 코딩을 하고 있는데 어찌된일인지 아이디나 패스워드가 하나만 틀려도 if문의 echo 두개가 출력 됩니다 그러니깐 not id not pwd 이렇게 두문장이 출력 됩니다 원인을 찾을수가 없네용 fetch() 말고 fetch_array() 함수를 써야되는건지 알수가 없네요 한가지 더는 bind_result()  와 store_result() 이 둘의 함수가 어떤기능을 하는건지 모르겠습니다 메뉴얼을 봐도 무슨 기능인지 모르겠네요 아니 이해를 못하겠네요 num_row() 함수와 관련이 있는거 같은데..자꾸 질문만 하네요!!! 좀 죄송스럽습니다 그리고시간내서 답변해주신점 정말 감사하고 많은게 도움되었습니다 잊지 않고 있습니다!  감사합니다!!!!

**Comment by Led001** [comment]
아닙니다 답변 신경 써주셔서 너무나 감사할뿐입니다!!

ajax 로 로그인 기능 계속 풀어 나갈려고 하다가 잘 되지 않아서 일단은  접어두고  

php만으로 풀어나갈려고 합니다 그런데 답변을 보고 다시 한번 도전 해봐야겠네요!! 

어렵네요!! 자바스크립트 mysql php java 이렇게 동시에 공부하고있는데 잘하고 있는건지 모르겠네요

그냥 한가지씩 어느정도 다 끝내놓고 공부를 진행할까 생각중입니다. 

아 그리고 php 로그인 기능을 코딩하고있는데 이게 왜 이러는지 모르겠네용!

/-
session_start();
require_once('../lib/conn.php');
$join=connect();
$id = trim(htmlspecialchars(($_POST['id'])));
$pwd = trim(htmlspecialchars(($_POST['pwd'])));

$query="select id,pwd from user where id=? and pwd =?";
$smt=$join->prepare($query);
$smt->bind_param('ss', $id, $pwd);
$smt->execute();
$smt->bind_result($gm,$fg);
$smt->fetch();
if($gm != $id){
echo 'not id';
if($fg != $id)
echo 'not pwd';
}
$smt->free_result();

*-

이렇게 로그인 코드를 짜봤습니다... 

아이디가 틀릴경우 아이디를 입력해주세요 

패스워드가 틀리면 패스워드를 입력 해주세요 라는 

코딩을 하고 있는데 

어찌된일인지 아이디나 패스워드가 하나만 틀려도 

if문의 echo 두개가 출력 됩니다 

그러니깐 not id not pwd 이렇게 두문장이 출력 됩니다 

원인을 찾을수가 없네용 

fetch() 말고 fetch_array() 함수를 써야되는건지 알수가 없네요 

한가지 더는 

bind_result()  와 store_result() 이 둘의 함수가 어떤기능을 하는건지 

모르겠습니다 메뉴얼을 봐도 무슨 기능인지 모르겠네요 아니 이해를 못하겠네요 

num_row() 함수와 관련이 있는거 같은데..

자꾸 질문만 하네요!!! 좀 죄송스럽습니다 그리고

시간내서 답변해주신점 정말 감사하고 많은게 도움되었습니다 

잊지 않고 있습니다!  감사합니다!!!!

**Comment by yoobato** [comment]
@Led001 

올려주신 소스에서,
```
if($fg != $id)
echo 'not pwd';
}
```
여기도 `$fg != $id`로 비교하는데, 이걸 `$fg != $pwd`로 바꾸시면 될 것 같습니다.

`fetch()`는 `mysqli_stmt`에 속해있는 것이고 (`bind_result()`와 함께 사용),
`fetch_array()`는 `mysqli_result`안에 속해있는 함수 같네요.
자세한 것은 사실 중요하지 않습니다 😄 

제 이메일 주소는 `dy@yoobato.com`입니다!
