### ISSUE TITLE
딤처리 레이어팝업 반응형

### ISSUE THREAD

**Issue by notkimwol** [codingeverybody/codingyahac#475]
# 해결하고자 하는 문제
기존에 있던 JS 코드를 레퍼런스하여 반응형 딤처리 레이어 팝업을 만들려 합니다.
하지만 어째서인지 딤처리 레이어가 열렸을때의 브라우져 크기를 기준으로 잡혀서 브라우저의 크기를 줄이거나 늘리면 유격이 일어나는 문제가 발생합니다.

# 코드 혹은 오류
`JS
$('.btn-example').click(function(){
        var $href = $(this).attr('href');
        layer_popup($href);
    });
    function layer_popup(el){

        var $el = $(el);		//레이어의 id를 $el 변수에 저장
        var isDim = $el.prev().hasClass('dimBg');	//dimmed 레이어를 감지하기 위한 boolean 변수

        isDim ? $('.dim-layer').fadeIn() : $el.fadeIn();

        var $elWidth = ~~($el.outerWidth()),
            $elHeight = ~~($el.outerHeight()),
            docWidth = $(document).width(),
            docHeight = $(document).height();

        // 화면의 중앙에 레이어를 띄운다.
        if ($elHeight < docHeight || $elWidth < docWidth) {
            $el.css({
                marginTop: -$elHeight /2,
                marginLeft: -$elWidth/2
            })
        } else {
            $el.css({top: 0, left: 0});
        }

        $el.find('a.btn-layerClose').click(function(){
            isDim ? $('.dim-layer').fadeOut() : $el.fadeOut(); // 닫기 버튼을 클릭하면 레이어가 닫힌다.
            return false;
        });

        $('.layer .dimBg').click(function(){
            $('.dim-layer').fadeOut();
            return false;
        });`

css 코드도 있는데 길어서 그런지 평문으로 나오게 되네요. 필요하시면 보내드리겠습니다.

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도우 10, 한국어, atom 사용중

# 시도해본 방법
제가 아는 모든 방법 margin left, right 수정 말고도 여러 할수 있는건 다했읍니다

**Comment by notkimwol** [comment]
`* {
  margin: 0;
  padding: 0;
}

body {
  margin: 100px;
}

.pop-layer img {
  width: 100%;
  margin-bottom: 20px;
}

.pop-layer .pop-container {
  padding: 20px 25px;
}

.pop-layer p.ctxt {
  line-height: 25px;
  color: #666;
}

.pop-layer .btn-r {
  width: 100%;
  margin: 10px 0 20px;
  padding-top: 10px;
  text-align: right;
  border-top: 1px solid #ddd;
}

.pop-layer {
  position: absolute;
  z-index: 10;
  top: 50%;
  left: 50%;
  display: none;
  width: 85%;
  /* 세로 넓이 지정 */
  height: auto;
  /* 가로 넓이 지정 */
  border: 5px solid #3571b5;
  /* 배경화면 외곽선 */
  background-color: #fff;
  margin-left: auto;
  margin-right: auto;
}

.dim-layer {
  position: fixed;
  z-index: 100;
  top: 0;
  left: 0;
  display: none;
  width: 100%;
  height: 100%;
  _position: absolute;
}

.dim-layer .dimBg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0.5;
  background: #000;
  filter: alpha(opacity=50);
}

.dim-layer .pop-layer {
  display: block;
}

a.btn-layerClose {
  font-size: 13px;
  line-height: 25px;
  display: inline-block;
  height: 25px;
  padding: 0 14px;
  color: #fff;
  border: 1px solid #304a8a;
  background-color: #3f5a9d;
}

a.btn-layerClose:hover {
  color: #fff;
  border: 1px solid #091940;
  background-color: #1f326a;
}

.pop-layer input[type=button] {
  align-items: center;
  border: none;
  padding: 5px 10px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  margin-bottom: 20px;
}

#SM-N930 .black {
  color: #fff;
  background-color: #090B12;
}

#SM-N930 .silver {
  background-color: #CACDD4;
}

#SM-N930 .blue {
  background-color: #6E93B0;
}

#SM-N930 .gold {
  background-color: #DEDACA;
}

@media (min-width: 590px) {
  .pop-layer {
    position: absolute;
    z-index: 10;
    top: 50%;
    left: 50%;
    display: none;
    width: 500px;
    /* 세로 넓이 지정 */
    height: auto;
    /* 가로 넓이 지정 */
    border: 5px solid #3571b5;
    /* 배경화면 vor */
    background-color: #fff;
    margin-left: auto;
    margin-right: auto;
  }
}`

**Comment by yoobato** [comment]
`$('.dim-layer')`가 Dim처리된 레이아웃이지요?

`CSS`에서
```
position: absolute;
width: 100vh;
height: 100vh;
top: 0;
left:0;
z-index: 999;
```
으로 줘보시겠어요?

`Javascript`에서는 뷰의 크기나 위치에 대한 동작을 따로 해주지 않으셔도 됩니다.

**Comment by yoobato** [comment]
@notkimwol 

덮어씌워져서 나타나는 것은, 제가 작성한 CSS 코드의 `z-index` 속성 때문입니다.
저 값을 더 **작게** 주시면 됩니다.

추가적으로 `z-index`로 레이어간의 순서(?)를 조정할 수 있습니다. 어떤 레이어를 앞에 둘 것이고, 어떤
레이어를 뒤에 둘 것인지요.

**Comment by notkimwol** [comment]
@yoobato https://codepen.io/kimwol/pen/LJWVbJ 말씀하신대로 코드 적용해보았습니다. 이번에는 아예 오류가 나네요.

**Comment by yoobato** [comment]
@notkimwol 

https://codepen.io/anon/pen/dqvNJG
제가 한 번 수정해보았습니다.

`device-layer`가 팝업 밑에 어둡게(dim 되어) 깔리는 레이어이고,
`layer-popup`이 실제 팝업 레이어인가봐요.

그럼, `device-layer`가 다른 것들보다는 위에 깔려야 하지만, `layer-popup` 보다는 밑에 깔려야 합니다.

따라서, `device-layer`의 `z-index`를 다른 것들보다 높게 두고 (저는 50으로 했습니다)
`layer-popup`의 `z-index`는 `device-layer` 보다만 높게 두면 됩니다. (저는 51로 했습니다)

이 외에도, `layer-popup`의 위치나 크기 관련해서도 수정을 좀 해두었습니다. 확인해보세요!

**Comment by yoobato** [comment]
@notkimwol 

`Javascript` 코드가 남아있어서 그랬던 것 같네요. 수정했으니, 다시 확인해보세요.
https://codepen.io/anon/pen/dqvNJG

`CSS` 코드로만 스타일을 정의하고, `Javascript(jQuery)`는 단순히 모달을 띄우거나 없애는 역할만
하도록 했습니다.

더불어, Modal과 관련해서는 아래 링크도 참고해보세요 😄 
https://www.w3schools.com/howto/howto_css_modals.asp

**Comment by notkimwol** [comment]
확인했습니다. 정말 감사합니다!
