### ISSUE TITLE
라디오 박스 버튼을 이용하여 내용 표시하기

### ISSUE THREAD

**Issue by notkimwol** [codingeverybody/codingyahac#478]
# 해결하고자 하는 문제

A와 B라는 라디오 버튼과

C와 D라는 텍스트 입력 필드가 있습니다. 라디오 버튼을 클릭하지 않았을 경우에는 숨김 상태가 됩니다.

여기서 A를 누르면 C가 나타나고, B를 누르면 D가 나타나게 하려고 한다면 코드를 어떻게 작성해야 할까요?

# 코드 혹은 오류
```<form>
 <input type="radio" name="Choice" value="A" required>  <br>
 <input type="radio" name="Choice" value="B" required>  <br>

 <input type="text" name="C" required> <br>
 <input type="text" name="D" required> <br>

 <input type="submit" name="submit" value="입력">
</form>```


# 환경



# 시도해본 방법

**Comment by progh2** [comment]
안녕하세요~ 
해답은 아니지만 참고할만한 내용만 적어봅니다. ^^;

문제를 나눠보면, 
1. 라디오 버튼이 클릭되었을 때 처리
2. 눌렸다는 이벤트가 발생했을 때 C, D가 출력되게 하기

로 나눠볼 것 같습니다. 
일단 각 input 요소마다 id를 지정해서 getElementById로 접근해서 할 수 있도록 할 필요가 있을 것 같습니다. 

1. 은 아래와 같이 검색하셔서 onClick 이벤트 구현을 참고해보세요. 
https://www.google.co.kr/search?q=%EB%9D%BC%EB%94%94%EC%98%A4+%EB%B2%84%ED%8A%BC+%ED%81%B4%EB%A6%AD+%EC%9D%B4%EB%B2%A4%ED%8A%B8&oq=%EB%9D%BC%EB%94%94%EC%98%A4+%EB%B2%84%ED%8A%BC+%ED%81%B4%EB%A6%AD+%EC%9D%B4%EB%B2%A4%ED%8A%B8+&aqs=chrome..69i57.4999j0j4&sourceid=chrome&ie=UTF-8

2.는 아래 링크처럼 자바스크립트로 dom 요소(element) 추가하기를 참고하시면 될 것 같습니다. 

https://www.google.co.kr/search?ei=CDTIW82ZHIT08AWX861g&q=%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8+dom+element+%EC%B6%94%EA%B0%80&oq=%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8+dom+element+%EC%B6%94%EA%B0%80&gs_l=psy-ab.3...25778.33291.0.33458.39.35.4.0.0.0.132.3176.0j28.28.0....0...1.1j4.64.psy-ab..8.26.2730...0j0i30k1j33i160k1j33i21k1j33i10i42k1.0.Wlr84FPEG3k

**Comment by notkimwol** [comment]
이제야 확인했습니다 ㅠㅠㅠㅠ 정말 감사합니다!
