### ISSUE TITLE
휴대폰과 웹서버 연결문제 관련해서 질문드립니다

### ISSUE THREAD

**Issue by vhok74** [codingeverybody/codingyahac#48]
휴대폰과 노트북을 같은 와이파이로 연결시킨후 
와이파이의 해당 ip주소를 통해 휴대폰으로 접속을 하는데 사이트에 연결할 수 없음 이라고 뜹니다.
영상을 쭉 따라 했는데 어느 부분이 잘못된지 모르겠습니다.

**Comment by progh2** [comment]
일단 노트북에서 127.0.0.1로 접속해서 접속 되는지 여부를 확인하신 후 접속이 된다면
노트북에 있는 V3 같은 방화벽이 해당 포트를 막고 있는지 확인해보세요.
방화벽 프로그램을 일시 끄거나 예외로 해당 포트를 추가해주는 식으로 해결할 수 있습니다. 
구글에서 "방화벽 특정포트 열기"로 검색하면 많은 글들을 보실 수 있을꺼에요~
