### ISSUE TITLE
두뇌 훈련용 간단한 앱을 개발하고 싶습니다.

### ISSUE THREAD

**Issue by globalkim** [codingeverybody/codingyahac#483]
# 해결하고자 하는 문제
제가 모바일앱을 개발하려고 합니다.
앱의 주제는 두뇌훈련용 앱입니다.
숫자 더하기 빼기
초성으로 낱말 맞추기
초성으로 속담 맞추기
이런 간단한 앱을 개발하려고합니다.
어떻게 시작해야하는지 궁금합니다.

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법
 안드로이드 스튜디어로를 공부하고 있는데 너무 분량이 방대하고 
제가 개발하려는 앱하고 조금 별개로 많이 배워야 해서
속도가 느려지니 의욕이 자꾸 떨어집니다. 

감사합니다.^^

**Comment by canfas** [comment]
만드려고 하는 프로그램에서 불필요 부분(카메라 제어..)까지 일일이 다 훑어보고 배울 필요는 없다고 생각합니다. 다 배우고 시작하려면, 필요한것들만 선택해서 간단하게 익히고 넘어가거나, 아니면 만들면서 배우는 식으로 1. 화면부터 구성하고 2. 기능을 구현하면서 하나하나 배워나가는 것이 좋겠습니다. 화면 디자인같은 경우는 혼자 만드려면 퀄리티가 떨어지고 예쁘지 않아 힘들수도 있습니다. 돈이 좀 들겠지만 디자인만 외주로 맡기고 개발은 직접하는것도 좋은 방법입니다.

**Comment by yoobato** [comment]
현재 어느정도 수준에 계신지 몰라 자세하게 답변을 드리기는 어렵지만,
@canfas 님께서 말씀해주신대로 굳이 안드로이드의 모든 것을 배울 필요는 없다고 생각합니다.
그때그때 필요한 부분들을 배워서 적용하는 것이 중요한 것 같아요.
(실제로 안드로이드 개발자 분들이 안드로이드의 모든 기능에 대해 모두 알고 계신 것은 아니에요 :)

적어주신 기능 중에서, 하나만 일단 만들어보는게 어떨지요?
예를 들어, '숫자 더하기 빼기'라면,

Java의 random 함수로 랜덤하게 숫자를 2개를 고른 다음,
random 함수로 0 혹은 1을 고르게 하고, (0인 경우 덧셈 / 1인 경우 뺄셈)

Activity에 TextView와 EditText를 사용해서,
[고른숫자1] (+ 혹은 -) [고른숫자2] = [EditText]

이렇게 나오게 한 다음...
사용자가 입력한 답안과, 코드 상에서 계산된 답안이 같은지 비교하는거부터
시작해보시면 어떨지요?

이게 다 되면, 하나씩 진행하는게 좋아보입니다 😄

**Comment by globalkim** [comment]
p{margin-top:0;margin-bottom:0}
    


    좋은 아침입니다. 
답변 주셔서 진심으로 감사합니다.^^

힘이 되네요.
제가 일단 만들어 보고 
다 만들고 나면 알려드리겠습니다.^^

감사합니다.
새 해 복 많이 받으세요^^



운명을 스스로 창조 합니다.
모든 것에 끊임없이 감사하라.
삶은 마인드에 달려 있다.
마인드 크리에이터





--------- 원본 메일 ---------

    
        보낸사람: Daeyeol Ryu <notifications@github.com>
        받는사람: codingeverybody/codingyahac <codingyahac@noreply.github.com>
        
            참조: globalkim <k889@daum.net>, Author <author@noreply.github.com>
        
        날짜: 18.12.31 00:33 GMT +0900
        제목: Re: [codingeverybody/codingyahac] 두뇌 훈련용 간단한 앱을 개발하고 싶습니다. (#483)
        
        
    
    
        현재 어느정도 수준에 계신지 몰라 자세하게 답변을 드리기는 어렵지만,
@canfas 님께서 말씀해주신대로 굳이 안드로이드의 모든 것을 배울 필요는 없다고 생각합니다.
그때그때 필요한 부분들을 배워서 적용하는 것이 중요한 것 같아요.
(실제로 안드로이드 개발자 분들이 안드로이드의 모든 기능에 대해 모두 알고 계신 것은 아니에요 :)
적어주신 기능 중에서, 하나만 일단 만들어보는게 어떨지요?
예를 들어, '숫자 더하기 빼기'라면,
Java의 random 함수로 랜덤하게 숫자를 2개를 고른 다음,
random 함수로 0 혹은 1을 고르게 하고, (0인 경우 덧셈 / 1인 경우 뺄셈)
Activity에 TextView와 EditText를 사용해서,
[고른숫자1] (+ 혹은 -) [고른숫자2] = [EditText]
이렇게 나오게 한 다음...
사용자가 입력한 답안과, 코드 상에서 계산된 답안이 같은지 비교하는거부터
시작해보시면 어떨지요?
이게 다 되면, 하나씩 진행하는게 좋아보입니다 😄
