### ISSUE TITLE
자바스크립트와 html을 이용해서 이상형 월드컵을 만드려 하는데 변수 저장에 있어 어려움을 겪고 있습니다 ㅜㅜ 

### ISSUE THREAD

**Issue by 2yeseul** [codingeverybody/codingyahac#484]
# 해결하고자 하는 문제

제가 만들고자 하는 웹은 이상형 월드컵을 간단하게 구현하는 것 입니다..
페이지 별로 두 개의 사진이 있고, 사진을 클릭 시 onClick 이벤트를 사용하여 js 내의 배열에 값을 저장한 뒤 또 다른 html에서도 값들을 사용하고자 했습니다ㅜㅜ 하지만 사진을 클릭해도 배열에 값이 저장이 되지 않는 듯 해서 문의드려요

# 코드 혹은 오류

```
<!--index.html-->
<a href="index2.html" target="_self" id="choice01" onclick="savePhotoName(0,1);">
						<span class="image fit primary">
							<img id = "img01">
								<script>
									document.getElementById('img01').src=photo[0];
								</script>
							</a>
		</span>
```

```
// script.js

function savePhotoName(i,j){
	choicePhoto[i]=photo[j];
}
```

html에서 js로 값을 넘기는 부분이 잘못된 것인지, 값을 받질 못합니다 ㅜㅜ 클릭하는 동시에 index2.html로 페이지가 바뀌고, onclick 이벤트를 실행하여 savePhotoName을 실행하고 싶습니다 ㅜㅜ 다음 페이지에서도 쭉 js내에 값을 저장하는게 가능할까요? 

# 환경

사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

window, html+js

# 시도해본 방법

form, input으로도 해봤는데 넘기는 값이 사진명이라 어떻게 값을 넘겨야할지 모르겠습니다 ㅜㅜ github블로그를 통해 구현하는 웹이라 php도 소용이 없는것 같구요

**Comment by canfas** [comment]
savePhotoName 에서 photo 배열과 choicePhoto 배열은 선언이 되어있는지? 우선 배열을 선언하고, savePhotoName 함수 안에서 getElementById('img01').src 를 사용해야... 위 코드만 봐서는, 이미지 태그 안에 스크립트에서, 포토배열[0]을 img src 로 가져온것 ? 대입? 문법이 안맞는듯 보입니다.

**Comment by 2yeseul** [comment]
ㄴ 앗 네 ㅜㅜ 선언은 윗 부분에 해놨는데 제가 펑션 부분만 가져와서요 링크 첨부 감사합니다!

**Comment by yoobato** [comment]
```
<a target="_self" id="choice01" onclick="savePhotoName(0,1);">
```
a 태그 안에서, href 속성을 빼버리고,

```
function savePhotoName(i,j) {
    choicePhoto[i]=photo[j];
    location.href = 'index2.html';
}
```
이렇게 하면 어떨까요?

**Comment by yoobato** [comment]
다음 페이지에서 js 내 값을 저장하는 것은 불가능하지만,

Cookie나 HTML5의 LocalStorage를 사용하는 방법도 있을 것 같구요.

이동시킬 때, `location.href = 'index.html2?foo=bar&abc=123';` 이런식으로,
GET 파라미터를 넘긴다음에, 다음 페이지의 js에서 파싱해서 사용하는 방법이 있을 것 같습니다. (https://www.google.com/search?q=javascript+parse+url+get+parameter&ie=utf-8&oe=utf-8&aq=t)
