### ISSUE TITLE
파싱? 스크래핑? 에 관한 질문입니다. - 자동가입방지 문자를 인식할려면 어떤 프로그램을 배워야되는지요?

### ISSUE THREAD

**Issue by aitppj** [codingeverybody/codingyahac#49]
제가 업무에 사용할 작은 프로젝트를 시작했습니다.
몇년전부터 관련 프로그램이  있었으면 좋겠다 싶었는데 이번 기회에 용기를 내어 시작해보고 있습니다.
전반적인건 이고잉님의 생활코딩강좌를 보면서 많이 배워가면서 진행하고 있는데 막히는 부분이 있어서 질문드립니다.

아래 화면은 현제 저의 프로젝트 진행상태 입니다.
상황은  mysql 디비에서 정보를 읽어와 데이타베이스테이블에 정보를 표현하는 정도까지는 구현을 했습니다. 
![13](https://user-images.githubusercontent.com/34802420/34603063-ae9a1378-f245-11e7-8f73-83d3633ac22f.png)
.
.
앞으로 구현해야될 내용은 
아래의 화면의  대법원 홈페이지의 입력부분에 위의 정보를 자동으로 입력해야되는 상황입니다.
![11](https://user-images.githubusercontent.com/34802420/34602438-13c0b1f6-f243-11e7-92f3-3fa9d99e67e9.png)

제가 만들고 있는 웹페이지에 연동되어 있는 mysql 디비에 있는 자료를 읽어와서  위의 입력창에 자동으로 등록해서 검색버튼까지 자동으로 눌러지게 하고 싶습니다. 

그러면 아래와 같은 정보가 나옵니다..

![12](https://user-images.githubusercontent.com/34802420/34602593-ad7f9a0a-f243-11e7-9981-4556d9662fe7.png)

이런 정보중에 내가 원하는 내용을 자동으로 mysql 디비에 저장이 되어서 활용하고자 하는게 최종 목표입니다. 

이런 진행과정은 백드라운드 작업으로 해야될거 같은데?  자바로 하면 되는지요 ?, 아님 자바스크립트? 

이런 걸 할려면 뭘 배워야될지 부터  막혀있습니다.  ㅡ./ㅡ
직장을 다니면서 틉틉히  배워서 써먹을려고 하니 시간적인 한게때문에 모든걸 배우기는 벅찬 상태입니다.

이고잉님의 말씁대로  필요한 기술을 배워서 써먹다 보면 실력은 어느덧 늘거 같고 덜 지칠거 같은데 뭘 배워야 알토랑같이 써먹을수 있을까요 ? ^_^~~~
너무 꽁으로 먹을려고 하는건 아니겠죠 ? ㅎㅎ ~~~~

해결할문제 ...
1. 자동가입방지 문자를 인식할려면 어떤 프로그램을 배워야되는지요 ?
(파이썬의 딥러닝 기술을? 이건 너무 어려울거 같고 좀 쉽게 해결할수 있는 방법은 없는지요 ?)

2. 필요한 정보를 읽어올려면 파싱? 스크래핑? 관련 기술을 배워야될거 같은데 어떤 프로그램을 배워야되는지요 ? (자바스크립트?  json?  아님 자바?) 중에서도 어느부분을 직중 공략하면 시간을 절약할수 있을까요 ?

관련 자료나 참고 사이트를 알려주시면 열심히 배워서 엄무에 활용해보고 싶습니다.
많은 도움 부탁드립니다. 감사합니다.

**Comment by davidkwak** [comment]
안녕하세요. 위에 progh2님께서 좋은 답변주지만 추가로 조금 더 붙이자면 

1. 캡챠 이미지는 현재로써는 질문자님께서 말씀하신 머신러닝 기반외에는 별다른 방법이 없어보입니다. 
다만, progh2님 말씀대로 자동화를 방지하기 위한 것이니만큼 설령 인식 할 수 있다 하더라도, 자동 크롤링을 시도하실 경우 IP 차단 등 조치가 취해질 가능성도 염두에 두셔야 할 것 같습니다. 
    참고 자료: https://medium.com/@ageitgey/how-to-break-a-captcha-system-in-15-minutes-with-machine-learning-dbebb035a710
