### ISSUE TITLE
진도표 문의

### ISSUE THREAD

**Issue by yoolern10** [codingeverybody/codingyahac#490]
오른쪽 하단 "참가하기" 버튼을 클릭해서 뜬 화면입니다. GOOGLE 버튼을 클릭하면 왜 팝업이 뜨다가 사라지고 아무 일도 안 일어날까요?ㅠ
![screen shot 2018-12-27 at 1 17 18 am](https://user-images.githubusercontent.com/46165502/50451297-8db8cc00-0976-11e9-90a9-656c58553ef6.png)

**Comment by egoing** [comment]
그러시면 브라우저 종류를 다른 것으로 바꿔보시겠어요? 종종 이런 일이 일어나고 있더라구여.

2018년 12월 27일 (목) 오전 1:27, yoolern10 <notifications@github.com>님이 작성:

**Comment by progh2** [comment]
혹시 크롬 브라우져인데도 그러면 시크릿 모드로 들어가셔서 해보세요~
브라우져 우측 상단 x버튼 밑에 보면  쩜쩜쩜 버튼(옵션 버튼) 눌러서 [새 시크릿창 열기] 클릭하면 해볼 수 있습니다. 

![image](https://user-images.githubusercontent.com/1307187/50578612-823a3900-0e7f-11e9-9ad4-209ee897f7cf.png)

**Comment by egoing** [comment]
진도표를 만든 사람으로서 불편함을 드려서 죄송합니다. ㅠㅠ 
다른 브라우저로 시도해보시고요. 
혹 안된다면 진도표가 필수는 아니니 진도표의 진도를 참고해서 진행해주시면 될 것 같습니다. 
개선 하도록 하겠습니다!

**Comment by yoolern10** [comment]
> 혹시 크롬 브라우져인데도 그러면 시크릿 모드로 들어가셔서 해보세요~
> 브라우져 우측 상단 x버튼 밑에 보면 쩜쩜쩜 버튼(옵션 버튼) 눌러서 [새 시크릿창 열기] 클릭하면 해볼 수 있습니다.
> 
> ![image](https://user-images.githubusercontent.com/1307187/50578612-823a3900-0e7f-11e9-9ad4-209ee897f7cf.png)

이렇게 하니까 되네요! 감사합니다!
