### ISSUE TITLE
검색하는 법? (사실 제가 github 처음 써서 하나도 모르겠네요...)

### ISSUE THREAD

**Issue by yoolern10** [codingeverybody/codingyahac#491]
> 보편적인 질문의 기술
질문 전에 검색을 먼저 해보세요. 사람 사는게 다 비슷하다는 것을 알게 됩니다.

issues 게시판에서 검색하려고 다음 사진과 같이 하니까 왠지 잘못하고 있는 것 같네요. 구글에 "github how to search"와 "github 검색하는 법"이라고 쳐도 왠지 관련 없는 내용만 뜨고... 어떻게 검색하나요?
![screen shot 2018-12-27 at 1 24 03 am](https://user-images.githubusercontent.com/46165502/50451399-16376c80-0977-11e9-95e1-c3a3d16b8cdd.png)

**Comment by humit0** [comment]
먼저 상단에 있는 위쪽 검색창에 검색하고 싶으신 검색어를 입력합니다.

![image](https://user-images.githubusercontent.com/8676247/50532471-037e8c80-0b5d-11e9-96dd-8e8f92f414a5.png)

그러면 상단의 사진과 같이 'In this repository'로 선택을 합니다.
다음은 왼쪽에 있는 서브 메뉴에서 Issues를 클릭합니다.

![image](https://user-images.githubusercontent.com/8676247/50532487-417bb080-0b5d-11e9-81af-5a1b0ea46d23.png)

이렇게 하면 이 저장소에 있는 Issues에 올라온 관련된 내용을 보실 수 있습니다.

**Comment by yoolern10** [comment]
감사합니다!!
