### ISSUE TITLE
안녕하세요. &nbsp;에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by badack** [codingeverybody/codingyahac#492]
# 해결하고자 하는 문제
안녕하세요. 코딩야학 수업으로 html을 처음 접하게 된 직장인입니다.
WEB2 CSS까지 수강한 이후, 여러 페이지를 구경하면서 html에 대해 알아가고 있는 중인데
&nbsp;에 대해 궁굼한 것이 있어서 글을 남겨봅니다.

검색해보니 &nbsp;는 우리가 아는 '띄어쓰기'의 기능을 하며
html상에서의 중복되는 띄어쓰기나 줄바꿈을 강제로 방지하기 위해 사용한다고 배웠습니다. 
헌데 몇몇 페이지에서 &nbsp;가 남용(?) 되고 있는 모습이 보여서 의문이 들었습니다.
그래서 저 나름대로의 가설을 세워봤습니다.

**가설 1. 한 칸 이상의 여백을 만들기 위해서 사용한 것이다.**
만일 그런 용도로 사용한다면 &nbsp;가 복수로 들어갔을것이라 생각됩니다. 하나만 필요하다면 &nbsp;가 아닌 그냥 스페이스바를 한번 치면 더 간단한 일이니깐요. 
하지만 딱히 그런 용도로 보이진 않았습니다. 그저 띄어쓰기의 대용품으로 사용이 되고 있는 모습이였거든요.  본문 내용은 아래의 (예시1)과 유사한 형태로 진행되었습니다.

**가설 2. 줄 바꿈을 방지하기 위해서이다.**
만일 그렇다면 줄 바꿈을 방지할만한, 그러니깐 학명이라던가 고유명사 등 납득갈만한 이유가 있는 단어 사이에 위치해야 한다고 생각했습니다. 아니면 읽기 적당한 단위로 &nbsp;가 존재할것이라 생각했습니다.
역시나 그런 용도로 보이진 않았습니다. 줄 바꿈이 있을만한 길이도 아닐뿐더러 만약 &nbsp;을 줄바꿈에 사용했다면 단어당 한 줄을 차지하는 실험적인 운문과 같은 형태를 띄게 되겠죠.

제가 스스로 내렸던 결론은 아마도 웹페이지상에서 스페이스를 &nbsp;로 자동 인식하게 되는 시스템이 있지 않을까 싶었습니다. html 작성을 하는데 있어서 &nbsp; 하나하나를 사람이 직접 입력했을것이라고 보기에는 무척이나 비효율적인 업무로 보이기 때문이죠.

이제 막 배워가고 있는 입장에서는 어떠한 과정이 있었기에 이런 형태의 html이 작성되었는지 잘 이해가 안됩니다. 왜 이렇게 작성되었는지 알고계신 분이 있길 바라며 질문을 올려봅니다!

# 코드 혹은 오류
```
(예시1)
안녕하세요.&nbsp;저는&nbsp;코딩을&nbsp;처음&nbsp;배우는&nbsp;직장인입니다. <br />
만나서&nbsp;반갑습니다.
``'

**Comment by egoing** [comment]
제 생각에도 저 코드는 저렇게 nbsp를 사용할 이유가 없어보이네요. 
말씀하신 것처럼 위지윅 에디터 등의 도구를 이용했기 때문에 발생한 문제가 아닐까 싶습니다.

**Comment by badack** [comment]
그렇다면 이젠 위지윅 에디터에 대해서 공부해봐야겠네요!

답변 감사드립니다 :)
