### ISSUE TITLE
aws cpu credit이 뭔가요??

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#50]
아 이건 추가적인 질문인데, ec2프리웨어를 이용하면 기본적으로 t2.micro로 인스턴스가 생성되는데, cpu credit이라는 항목이 잘 이해가 되지않습니다. 이 부분이 트래픽에 대응되는 부분인가요??

**Comment by haebin** [comment]
관련해서 아래 키워드로 구글 검색해보시면 바로 나옵니다.
'cpu credit amazon'

https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/t2-credits-baseline-concepts.html
