### ISSUE TITLE
html에서 img태그의 src를 변경할 떄 화면상에서 약간의 딜레이가 생기는 현상입니다.

### ISSUE THREAD

**Issue by FKgk** [codingeverybody/codingyahac#500]
안녕하세요 
특정 조건에서 특정 img의 src를 변경 할 때 딜레이가 생겨서 질문드립니다. 
# 해결하고자 하는 문제
javascript에서 html의 img태그의 src를 변경할 때 화면에서 약간의 딜레이가 생깁니다.

# 환경
HTML , JAVASCRIPT

# 시도해본 방법
제 생각에는 src를 변경할 때마다 img를 불러와서 트래픽 증가로 인해 발생하는 것 같습니다.
그래서 img들을 합쳐서 하나의 이미지 파일로 만들고 파일에서 특정 이미지만 가져오는 방식으로 변경하고 싶습니다.
하지만 그렇게 하는 방법을 잘 모르겠습니다.
방법이나 참고할만한 사이트를 알려주시면 감사하겠습니다.

**Comment by blackdew** [comment]
아래 샘플 코드가 도움이 될 것 같네요. :) 
https://blog.teamtreehouse.com/learn-asynchronous-image-loading-javascript

`
var image = document.images[0];
var downloadingImage = new Image();
downloadingImage.onload = function(){
    image.src = this.src;   
};
downloadingImage.src = "http://an.image/to/aynchrounously/download.jpg";
`

["img src change after loaded"](https://www.google.com/search?ei=NA4uXJbwLI6noAT9o4uwAQ&q=img+src+change+after+loaded+&oq=img+src+change+after+loaded+&gs_l=psy-ab.3...4334.7094..7306...0.0..0.134.738.0j6......0....1..gws-wiz.OpnMEG1dkv8) 이렇게 검색을 했어요. 참고해서 다른 검색어로도 검색을 해보시고 여러 다른 해결책도 찾아보시면 공부가 될 거에요~

**Comment by davidkwak** [comment]
문제 ) 여러개의 이미지를 보여주고 싶은데 그중에 몇몇 이미지는 불러올때 딜레이가 걸린다, 
원하는 바) 많은 이미지를 하나로 만들어서 한번에 로드하고, 그때 그때 필요한 이미지만 가져와서 보여주고 싶다. 

위 내용으로 이해했는데 제가 질문하신바를 제대로 이해한건지 모르겠네요. 

일단, 이미지를 하나로 만들어서 (.zip 같은 형태의?) 한번에 로드해서 골라서 쓰는건 제가 아는 바로는 좀 어려울것 같습니다. 대신, 기존에 미리 이미지 작업을 통해서 하나의 큰~~ 이미지 파일로 만들어놓고 
각 이미지의 좌표값을 알고 계시다면 페이지 첫 로딩 시에 큰 이미지 하나를 불러오고 좌표값을 바꿔가면서 출력하는 방법이 가능할것 같습니다 (옛날 도트시절 게임 그래픽에 쓰던 방법... ) 
(참고: https://stackoverflow.com/questions/57725/how-can-i-display-just-a-portion-of-an-image-in-html-css) 

좀더 스마트한 방법이라면 html5의 web storage 기능을 이용하는 방법이 있을것 같네요. 
(참고: https://stackoverflow.com/questions/19183180/how-to-save-an-image-to-localstorage-and-display-it-on-the-next-page)
