### ISSUE TITLE
컨텍스트 스위칭관련 궁금증이 있습니다

### ISSUE THREAD

**Issue by zarate02** [codingeverybody/codingyahac#501]
프로세스가 실행되고 있는중에 다른 프로세스에서 인터럽트가 발생하면 컨텍스트 스위칭이 일어난다고 알고있는데

그러면 운영체제에 하나의 프로세스에서만 인터럽트가 계속 난다면 컨텍스트 스위칭은 일어나지 않는건가요?

**Comment by studroid** [comment]
우선[ Linux Information Project에서 Context Switch에 관한 정의](http://www.linfo.org/context_switch.html)를 보시면, 다음과 같은 말이 첫 줄에 있습니다.

> A context switch (also sometimes referred to as a process switch or a task switch) is the switching of the CPU (central processing unit) **from one process or thread** to another.

즉, 컨텍스트 스위칭은 프로세스 간에 일어나느 것 외에도 한 프로세스 내 여러 스레드가 있을 경우 일어날 수 있는 것이지요.

또 컨텍스트 스위칭이 발생하는 때에 관해 [위키피디아](https://en.wikipedia.org/wiki/Context_switch)에도 잘 정리돼 있는데,

아래와 같은 세 경우가 나열돼 있습니다.

* Multitasking - 스케쥴러에 의해 CPU 시간 분배
* Interrupt Handling - 하드웨어, 소프트웨어 인터럽트 다 있겠죠?
* User and kernel mode switching - OS에서 유저 레벨과 커널 레벨 모드 스위칭이 발생할 때, 컨텍스트 스위칭이 일어날 수 있습니다.

더 상세한 내용은 Coursera 등 온라인 대학 강의에서 OS 관련 강의를 보시면 나올 것 같습니다! :)
