### ISSUE TITLE
대화방 초대 불가 메시지가 뜨네요!

### ISSUE THREAD

**Issue by fromSummer** [codingeverybody/codingyahac#502]
안녕하세요, 오늘 처음 야학을 시작하였습니다.
오픈 대화방에 참여하고 싶어 디스코드 설치 후 가입까지 완료하였는데,
방에 입장이 되지 않네요!

디스코드의 부가 설명 링크를 따라가니, 초대불가능한 링크라고 명시가 되어 있네요 ;)
기간 만료, 유효하지 않은 코드, 차단, 100개 서버 제한
-을 확인하라고 안내받았습니다.
혹시 해당 초대 링크의 기간이 만료된 것이 아닐지 추측을 해보고 있어요.
해결 방법을 알고 계시는 분이 계시다면, 알려주시면 감사하겠습니다 :))
함께 모여 이야기를 나누고 싶어요.

감사합니다.
새해복 많이 받으세요, 학우분들!! :))

**Comment by egoing** [comment]
https://discord.gg/wCsKG6

위의 링크를 한번 이용해보셔요~
