### ISSUE TITLE
웹 서비스의 개념과 구현(JSON-RPC 서버)에 대해서 포괄적인 질문좀 드리고 싶습니다.

### ISSUE THREAD

**Issue by jinsu421** [codingeverybody/codingyahac#505]
# 해결하고자 하는 문제

제가 응용프로그램 C#을 이용해서 DB와 연결을 해서 정보를 가져오고 수정하는 프로젝트를 진행해왔습니다.

그런데 단순 로컬(설치형식)이 아니라 원격에서도 이런 기능을 제공해야되서 
이제서야 유투브 강의를 활용해서 Html,Jquery 등 웹 프로그래밍을 처음 접해봤습니다.
강의만 따라하다보니 완벽한 이해 없이 프로토타입만 작성해보려는 안타까운 상황입니다.

' C#(ASP.Net) + Web API를 이용한 웹 서비스' 형식으로 구현을 해야하는데 제대로 진행하는지, 
강의 개념 등이 확실하게 이해가 안되서 질문좀 드리겠습니다.

1.비쥬얼 스튜디오(visual studio)에서 ASP.Net 웹 응용 프로그램 프로젝트 생성
2.HTML, CSS, JQuery를 이용하여 웹 페이지 구성
3.C#과 DB를 통한 Model과 Data 연동
4.JQuery 및 Ajax를 이용하여 UI와 View의 연동 및 Data 갱신

위와 같은 방식이 될것같은데. 강의 진행 중에

1.Server 에서 제공할 페이지만 구현하면은 되는것인지

2.Html 파일에서 Get,Post등과 같은 Http Verb를 활용하는 경우가 있고, 
controller.cs에서 Http Verb를 활용하는 방식의 차이점

3. .asmx 파일을 통해서 웹페이지 생성하는 경우와 .aspx 파일을 통해서 웹페이지 생성하는 경우의 차이점

4.보안(Authentication)을 위해 필요한 기술은 어떤 식으로 구현이 되야하는지

5.프로젝트 배포방식은 어떻게 되는지

와 같은 궁금증이 생겼습니다.

# 환경
C#(ASP.Net), Web Browser, Mysql, Mssql, JQuery, Web API

# 시도해본 방법

DB를 가져와서 Json 형식으로 출력하는 방법과
Html과 JQuery를 이용한 웹페이지 구성 방법은 어느정도(40~60%정도) 이해한것 같습니다.

**Comment by jinsu421** [comment]
조금 자료를 찾아보니 'JSON-RPC 서버 구현' 방식이 적절한 것 같습니다.

**Comment by jinsu421** [comment]
> ajax라는 기술이 도입이 되면서 javascript 상에서 특정 url을 호출하고,
> 서버로 부터 응답을 받은 내용을 가지고 html에 추가적으로 반영되는 것이 가능해 졌습니다.
> 이후에 서버는 html과 상관없이 데이터만 응답하는 방식이 의미가 있게 사용되기 시작한거죠.
> 이것이 web api의 등장이고, 이로써 http method가 더 적극적으로 활용되게 된 것입니다.
> 
> 처음에는 ajax의 결과로 서버가 완성된 html코드를 반환하고, 받은 html 코드를 사용하는 형태로 사용되었고요.
> 지금은 json의 형태로 받아, js 내에서 태그를 만드는 형태가 주를 이룹니다.
> json의 형태로 주고받는 것이 거의 표준이 된 것 같습니다.

글 쓰신 내용은 이해가 가는데, 프로젝트 진행 중에 이해가 안가는 부분이 있어서 추가질문 여쭤보고 싶습니다.
C#에서 web api 프로젝트 생성해서 진행중인데, 항상 url에 http(혹은 https) ://localhost:PortNumber 
형식으로 빌드,컴파일 되는데 이 자체로 서버 웹사이트가 되어서 다른 end point (User)가 해당 사이트를 접속 할 수있는것인가요?
(배포시에는 localhost가 아닌 웹 호스팅을 해야겠지만요.)

**Comment by blackdew** [comment]
C#으로 프로젝트 진행을 해보지는 않아서 세밀한 설정에 대해 답변을 드리기는 어려울 것 같아요. 
언어나 프레임워크에서 직접 서버를 올리는 경우에는 지원하는 경우에 port를 직접 지정할 수 있는 옵션이 있습니다. 옵션을 조정하여 80포트를 이용하셔도 되고요. 

port forwading이나 redirection을 이용해서 여러 개의 서비스를 한 서버내에  띄워서 운영할 수 있습니다. 
아파치나 nginx같은 웹서버를 따로 띄우는 경우에는 해당 웹서버에서 port fowarding을 지원해요.

**Comment by jinsu421** [comment]
빠른 답변감사합니다.

https://www.c-sharpcorner.com/UploadFile/3d39b4/publish-and-host-Asp-Net-web-api/

해당 예시대로 하게될때 8번그림에서 호스트 받은 이름을 hostname칸에만 맵핑해주
publishing 가능하게 되는거겠죠?

**Comment by blackdew** [comment]
네. 맞는 것 같아요. 성공하시길 바랍니다~ :)
