### ISSUE TITLE
github.io로 구축한 홈페이지에 게시판을 연동하고 싶습니다.

### ISSUE THREAD

**Issue by BY1994** [codingeverybody/codingyahac#506]
생활코딩 강의를 보고 github.io 로 쉽게 개인 홈페이지 구축을 하는 방법을 따라해보았습니다.
질문과 댓글을 쓸 수 있는 게시판을 구현하고 싶은데, 그것을 만들 수 있을까요? 안된다면 잘 된 서비스에서 연동을 시킬 수 있을까요?

**Comment by studroid** [comment]
github.io에 개인 홈페이지를 구축하는 것은, 개발자가 미리 정해놓은 내용들만 보여줄 수 있는 형태입니다 :)

즉, 다른 사람들이 내 홈페이지에 들어와서 새로운 질문과 새로운 댓글을 쓰고, 내용을 수정하고, 댓글을 지우는 등 미리 정해지지 않은 행동들을 할 수 있게 만드는 것은 **서버**라는 개념이 더 필요한 일이지요.

이번 코딩야학 10일 기간 동안, 이고잉님이 진행하시는 라이브 방송과 생활코딩의 [WebN](https://opentutorials.org/course/3083) 강의를 통해 이에 대해 감을 잡으실 수 있을 듯합니다.

알아야 할 내용이 적지는 않지만, 함께 공부하다 보면 분명히 다 이해할 수 있는 것들이니 너무 급하게 생각하지 마시고, 같이 즐겨보시지요!

**Comment by smartbos** [comment]
Disqus 라는 서비스를 한 번 확인해보세요.
https://disqus.com

**Comment by egoing** [comment]
아래 수업을 한번 참고해보셔요~

https://opentutorials.org/course/3084/18594

**Comment by blackdew** [comment]
게시판을 직접 구현해 보는 것은 굉장히 도움이 되는 프로젝트에요. 
게시판을 변주한 많은 형태가 있는데요. 
직접 해보시면 보이지 않았던 여러가지 디테일한 내용들을 만나볼 수 있어요. 

한번 도전해 보시기를 권해드립니다. :) 
https://www.google.com/search?ei=JK80XP7bCNOK8gXo451g&q=php%2C+mysql+%EA%B2%8C%EC%8B%9C%ED%8C%90+%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EA%B8%B0&oq=php%2C+mysql+%EA%B2%8C%EC%8B%9C%ED%8C%90+%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EA%B8%B0&gs_l=psy-ab.3...2373.6989..7191...0.0..0.195.1499.0j9......0....1..gws-wiz.......35i39.vlOp0_VQwo8
