### ISSUE TITLE
제 상황에선 Webn 과 기존 웹애플리케이션 만들기 중 무엇을 듣는게 좋을까요

### ISSUE THREAD

**Issue by hxxmxx** [codingeverybody/codingyahac#507]
Base: 저는 컴퓨터공학과를 재학중이며 파이썬과 C를 배웠습니다.

상황: 올해 상반기 안에 동업자와 전자상거래 플랫폼 스타트업을 런칭을 하는 것을 목표로 하고 있고, 웹사이트를 (특히 모바일 버전에 특화한) 제가 직접 만들고 싶어서 며칠전부터 생활코딩 강의를 듣기 시작했습니다. 지금까지 이틀에 걸쳐 Web1 html과 Web2 CSS를 듣고 연습했어요. 목표가 있다보니 이제부터는 하루에 반나절은 코딩을 배우는데 쓰려고 합니다.

질문1: 웹 애플리케이션 만들기 코스를 훑어보니 제가 Webn 코스를 통해 배운 html과 CSS 내용보다 더 많은 것들을 가르쳐주는 것 같더라구요.

Webn은 어떤 특정 부분이 필요한 사람들을 위해 앞 파트들을 최대한 효율적으로 구성하신거라고 하셨잖아요. 그럼 제 상황같이 특정 무엇이 필요한 게 아니라 웹사이트를 전체적으로 구현하는 것을 목표로 하는 경우는 Webn보다는 아예 웹애플리케이션 만들기를 듣는게 더 나을까요?

질문2: 생활코딩 강좌들로 제가 원하는 전자상거래 플랫폼 웹사이트를 만들 수 있는 단계에 도달하는 것이 가능할까요? 아직 html과 CSS에 갓 발을 담근 상태라 그런지 전자상거래 웹사이트를 만든다는 것이 너무나 굉장하고 거대하고 저 혼자서는 이룰 수 없는 큰일같아보입니다ㅠ

강좌로 부족하다면 학원이나 책 중에 어떤 것을 병행 혹은 추가하는 것이 더 나을까요? 저희 아빠도 프로그래머이셔서 코딩 중 생기는 사소한 문제들에 대한 답을 쉽게 얻을 수 있기는 합니다.

+이렇게 배움을 얻고, 질문을 공유할 수 있는 장을 만들어주신 모든 관계자분들과 답변해주시는 모든 분들께 너무 감사하다는 말씀을 전합니다!♥

**Comment by o2-basta** [comment]
이고잉님이 강의하시는 동안 조력자로 참여하기도 했었던 사람으로서 WEBn이 좀더 최신내용이면서 먼저 접하시면 좋을거 같습니다. 그렇다고 웹애플리케이션 만들기가 최신이 아니라는것은 아니지만, 좀더 핵심적인 사항에대해서 이해를 하시고, 이후에 웹애플리케이션을 만들어보시는게 좋을거 같습니다. 
아마도 중복되는 내용은 자연스럽게 지나가면서 새로이 배우시는 부분만 더 또렷하게 보실 수 있을거 같아요

**Comment by egoing** [comment]
webn이 웹앱수업 보다 더 많은 내용을 다루고 있답니다. 그러니 webn을 추천 드려요.

전자상거래를 직접적으로 다루진 않지만 핵심적인 개념은 webn에 포함 되어 있어요. 진도 나가다보면 다음 도약 지점이 보일 것 같습니다.

화이팅

**Comment by egoing** [comment]
추가로 궁금하신 점이 있으시면 다시 오픈해주세요~
