### ISSUE TITLE
MySQL Client에서 .db 파일을 실행방법/ 행삭제 이후 새로운 값의 id를 결번 없이 연속생성하는 방법

### ISSUE THREAD

**Issue by 4visuals** [codingeverybody/codingyahac#508]
다른 언어로 만들어져 있는 웹어플리케이션을 한국어로 구현해보려고 코딩을 기초부터 공부하고 있는 직장인입니다. 
HTML과 CSS, JavaScript, Python, MySQL을 한 번 훑었고 Node.js는 반 정도 듣다가 일단 보류하였습니다.

1. 구현하고자 하는 웹어플리케이션에서 사용할 데이터베이스 파일을 Db Browser라는 프로그램을 이용해서 짬짬이 한글로 변환시켜 놓았는데요, 
  MySQL 수업을 듣고 HeidiSQL이라는 MySQL client에서 이 파일을 실행시켜보려고 하니 제가 작업해 놓은 파일은 확장자가 .db인지라 이 파일을 MySQL에서 어떻게 사용할 수 있는지 여쭤봅니다.
  열심히 찾아봐도 .db파일과 .sql파일은 파일 기반 프로그램에서 생성된 파일이고 MySQL은 서버 기반이다 ' 정도 밖에 이해를 못하고 있습니다. 

2. MySQL 수업에서 질문입니다.
 행 삭제 후에 다시 데이터를 테이블에 입력하니 삭제된 id 다음 번호부터 새 id가 생성되어 나오던데,  연결해서 id가 작성되는 방법은 어떤 것이 있는지요?

**Comment by jinsu421** [comment]
.db 형식을 지원하는 sql이 sqlite입니다. 아마 그 두개를 연동하는 방식으로 odbc를 지원하는지는 모르겠네요. 아시는바와 같이 mysql은 서버 기반이고, sqlite는 로컬 기반 db입니다.
2번째 항목은 이해가 안되서 다른분에게 넘겨보겠습니다.

**Comment by davidkwak** [comment]
1) sqlite에서 sql로 export 하는 기능이 있을것입니다. 
  (참고 : https://stackoverflow.com/questions/163079/exporting-from-sqlite-to-sql-server)

2) 아마 ai (auto increment)기능을 이용해서 id를 붙이고 계신것 같은데 그 상황에서 빠진 이빨을 채우고 싶으시다면 ai를 사용하시면 안됩니다. 매 insert 때마다 기존 id를 보고 +1 하는 로직을 따로 짜셔야 합니다. 

(참고 : https://stackoverflow.com/questions/12969161/make-auto-increment-fill-previously-deleted-number)

**Comment by fermat39** [comment]
1번 사항에 대해서 말씀드리면 DBMS에 대한 개념을 일단 알고 가셔야 할 것 같습니다.

DBMS는 DataBase Managment System 의 약자입니다. 전산 관련 학과를 다니셨으면 아마도
학부때 DBMS에 대해서 배우셨을 것입니다. 이 시스템의 경우 물리적인 서버에 Database를 운영 및 
관리할 수 있는 애플리케이션이 설치됩니다. 이 애플리케이션이 유명한, 오라클, MS-SQL, MySQL 등등이
있습니다.  이 애플리케이션의 경우 기본적으로 설치를 하면 서버 역할 을 하며 이 서버에 접속해서
데이터를 입력, 수정, 삭제, 검색 (CRUD)를 하게 됩니다. 

최근에는 로컬 즉, 내가 가지고 있는 PC에서 사용할 수 있는 단독적인 DBMS를 원하게 되었습니다.
특히, 스마트폰이 발전하면서 그런 측면이 더욱 강조되었고, 최근에는 브라우저의 기능이 강력해 지면서
브라우저의 기능을 살려 브라우저에 DBMS 기능을 살린 PouchDB라고도 있습니다.

SQLite의 경우 파일 단위 DBMS로 보시면 됩니다. 사실 위에서 이야기한 DBMS의 경우도 어떻게 보면
파일 단위 DBMS로 이야기할 수도 있겠지만, SQLite의 경우는 실제 특정 파일 1개에 CRUD에 대한 데이터를 가지고 있습니다.

**Comment by 4visuals** [comment]
> .db 형식을 지원하는 sql이 sqlite입니다. 아마 그 두개를 연동하는 방식으로 odbc를 지원하는지는 모르겠네요. 아시는바와 같이 mysql은 서버 기반이고, sqlite는 로컬 기반 db입니다.
> 2번째 항목은 이해가 안되서 다른분에게 넘겨보겠습니다.

네, 답글 달아주셔서 고맙습니다. 열심히 공부해봐야겠네요.^^

**Comment by 4visuals** [comment]
> 1. sqlite에서 sql로 export 하는 기능이 있을것입니다.
>    (참고 : https://stackoverflow.com/questions/163079/exporting-from-sqlite-to-sql-server)
> 2. 아마 ai (auto increment)기능을 이용해서 id를 붙이고 계신것 같은데 그 상황에서 빠진 이빨을 채우고 싶으시다면 ai를 사용하시면 안됩니다. 매 insert 때마다 기존 id를 보고 +1 하는 로직을 따로 짜셔야 합니다.
> 
> (참고 : https://stackoverflow.com/questions/12969161/make-auto-increment-fill-previously-deleted-number)

 .db 파일을 sql로 export는 했고 MySQL에서 그 sql을 실행시켜보았는데 첫 문장에서 error가 발생했다고 하네요... 좀 더 공부해보고 또 질문드리겠습니다.   답글 감사합니다~~

**Comment by 4visuals** [comment]
> 1번 사항에 대해서 말씀드리면 DBMS에 대한 개념을 일단 알고 가셔야 할 것 같습니다.
> 
> DBMS는 DataBase Managment System 의 약자입니다. 전산 관련 학과를 다니셨으면 아마도
> 학부때 DBMS에 대해서 배우셨을 것입니다. 이 시스템의 경우 물리적인 서버에 Database를 운영 및
> 관리할 수 있는 애플리케이션이 설치됩니다. 이 애플리케이션이 유명한, 오라클, MS-SQL, MySQL 등등이
> 있습니다. 이 애플리케이션의 경우 기본적으로 설치를 하면 서버 역할 을 하며 이 서버에 접속해서
> 데이터를 입력, 수정, 삭제, 검색 (CRUD)를 하게 됩니다.
> 
> 최근에는 로컬 즉, 내가 가지고 있는 PC에서 사용할 수 있는 단독적인 DBMS를 원하게 되었습니다.
> 특히, 스마트폰이 발전하면서 그런 측면이 더욱 강조되었고, 최근에는 브라우저의 기능이 강력해 지면서
> 브라우저의 기능을 살려 브라우저에 DBMS 기능을 살린 PouchDB라고도 있습니다.
> 
> SQLite의 경우 파일 단위 DBMS로 보시면 됩니다. 사실 위에서 이야기한 DBMS의 경우도 어떻게 보면
> 파일 단위 DBMS로 이야기할 수도 있겠지만, SQLite의 경우는 실제 특정 파일 1개에 CRUD에 대한 데이터를 가지고 있습니다.

제가 30여년 전에 교양으로 전산기초인가 C언어인가를 들은 게  전부인지라 이런 자세한 설명  너무 감사하네요^^  고맙습니다~
