### ISSUE TITLE
랜덤으로 편지를 매칭해주는 앱을 개발하고있는데 조언부탁드립니다!

### ISSUE THREAD

**Issue by inyoungW** [codingeverybody/codingyahac#509]
작성한 편지를 랜덤하게 상대방에게 전달하는 앱을 개발하려고 합니다.
하나의 편지를 1:1 로 매칭해주는 것을 목표로 하고 있는데

현재 수준에서는
사용자를 랜덤함수를 이용해서 선택하는 것으로 생각하고 있습니다.

그런데,
만약 자신의 관심사에 따라서 예를 들어서 연애나 가족, 등의 문제 연관성이 더 높은
사람에게 매칭해주거나 할 때는 어떻게 해주는 것이 좋을까요?

조언부탁드립니다..!

**Comment by o2-basta** [comment]
빅데이터 분석같은 분야로 점점 나아가고 계시군요 ㅎㅎ
질문주신내용에서는 아마도 편지를 쓰시는 분들과 받으시는 분들사이의 연관성 분석을 할 필요가 있을거 같아요.
구체적으로는 두가지 방법이 있을거 같은데, 
첫번째는 모든 분들의 관심사와 취향, 선호하는 내용을 받아서 세분화하고 같은 그룹으로 묶어서 그 그룹 안에서만 보내는 방법입니다. 
두번쨰는 편지의 내용에서 나오는 단어를 분리해서 단어의 내용과 가장 관련있는 선호도와 매칭되는 사람들 혹은 그룹에 있는 사람들중에서 한분에게 보내는 방법도 있을거 같습니다. 

사람들의 내용을 파악하는조사를  할수도 있지만, SNS등의 데이터를 (사용자의 동의하에) 받아서 같이 분석하는게 도움이 될 수도 있을거 같아요 

잼난거 만드시길 바래요~~

**Comment by fermat39** [comment]
랜덤이라는 것이 의외로 굉장히 어렵습니다.
나중에 공부하시면서 아시겠지만 랜덤이 의외로 편향이 생길 수가 있습니다.

관심사에 대한 데이터를 어떻게 구하실지 고민이 필요하실 것 같습니다.
한국에서는 의외로 데이터 수집에 대해서 법률적인 제한이 많습니다.
그리고 그 데이터를 어떻게 저장해서 활용할지도 고민이 필요합니다. 

제가 너무 부정적인 말씀을 드린 것인지 모르겠네요...
하지만, 아무리 좋은 아이디어라도 한국에서는 개인보호측면에서 데이터
수집 및 저장에서 제한이 좀 있습니다. 이 부분에 대해서 고민하시면서
만들어 나가시면 좋을 듯합니다.

감사합니다. 화이팅입니다!!!
