### ISSUE TITLE
nodejs가 아파치의 역할을 할 수있나요??

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#51]
nodejs로 서버를 생성하던데, 그럼 nodejs로 아파치의 역할까지 수행할 수 있는건가요??
아파치 없이 웹서비스가 가능한건가요??

**Comment by haebin** [comment]
네, 가능합니다.
아래 참고하세요.
- 원문: https://www.w3schools.com/nodejs/nodejs_http.asp
- 번역: https://translate.google.co.kr/translate?hl=ko&sl=en&tl=ko&u=https://www.w3schools.com/nodejs/nodejs_http.asp

실 서비스에서는 주로
아래와 유사한 형태로 서비스가 됩니다.
- 번역: https://translate.google.co.kr/translate?hl=ko&sl=en&tl=ko&u=https://blog.carbonfive.com/2014/06/02/node-js-in-production/
- 원문: https://blog.carbonfive.com/2014/06/02/node-js-in-production/
