### ISSUE TITLE
C# 공부하면서 oop관련해서 제 생각이 맞는지 궁금합니다.

### ISSUE THREAD

**Issue by minseoi** [codingeverybody/codingyahac#511]
아래는 제가 정리한 내용입니다.

클래스는 오브젝트의 설계도와 같은겁니다.
클래스로 생성한 객체 = Instance 입니다.

이 객체에 참조변수를 추가하여 객체에 접근을 할 수 있습니다.
 
Human Joe = new Human;
여기서 Joe가 새로생긴 Human객체의 참조변수인 것이고요.

참조변수가 없는 객체는 GC 대상이 됩니다.

제가 잘 이해 한 것인가요?

**Comment by fermat39** [comment]
네 잘 이해하셨습니다. 
이제 이 오브젝트의 메소드들을 잘 사용하실 준비가 되셨네요.. ㅎㅎ
