### ISSUE TITLE
javascript에서 한글 자음과 모음 string을 한 문자로 만들고 싶어요.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#517]
# 해결하고자 하는 문제
 안녕하세요?
한글 자/모음을 1개의 한글로 만들고 싶어서 concat을 사용하여 시도해 봤습니다.
예를 들어 "ㄱ" 과 "ㅗ"를 concat 하면 "ㄱㅗ" 이런 식으로 string이 합쳐지는데
이 것을 "고"로 만드는 방법이 있을까요?

# 코드 혹은 오류
```
let consonant = "ㄱ";
let vowel = "ㅗ";
let ass = consonant.concat(vowel);
console.log(ass);

```

# 환경
javascript

**Comment by InyoungAum** [comment]
유니코드 한글 조합원리를 통해 해결 가능합니다. 
다음 링크가 도움이 될 것 같네요!
https://zetawiki.com/wiki/%EC%9C%A0%EB%8B%88%EC%BD%94%EB%93%9C_%ED%95%9C%EA%B8%80_%EC%B4%88%EC%84%B1,_%EC%A4%91%EC%84%B1,_%EC%A2%85%EC%84%B1_%EC%A1%B0%ED%95%A9_%EC%9B%90%EB%A6%AC

**Comment by kammaii** [comment]
> 유니코드 한글 조합원리를 통해 해결 가능합니다.
> 다음 링크가 도움이 될 것 같네요!
> https://zetawiki.com/wiki/%EC%9C%A0%EB%8B%88%EC%BD%94%EB%93%9C_%ED%95%9C%EA%B8%80_%EC%B4%88%EC%84%B1,_%EC%A4%91%EC%84%B1,_%EC%A2%85%EC%84%B1_%EC%A1%B0%ED%95%A9_%EC%9B%90%EB%A6%AC

빠른 답변 감사합니다!!
