### ISSUE TITLE
vscode로 파이썬 작업중 디버깅 오류 질문드립니다.

### ISSUE THREAD

**Issue by mahns1201** [codingeverybody/codingyahac#519]
# 해결하고자 하는 문제
 코드를 작성하고 디버깅을 시작하면,
Debug adapter process has terminated unexpectedly (Cannot read property 'style' of undefined 
라는 문구와 함께 멈춰버리는데 어떻게 해야 할지 모르겠습니다. 도와주세요

**Comment by blackdew** [comment]
debug를 위한 interpreter 설정이 잘못되어 있을수도 있고, 사용하는 extention이 충돌을 일으킬 수도 있을 것 같아요. 
환경이 아예 꼬여서 손댈수 없다면, vscode를 삭제한 뒤에 재설치해서 환경을 처음부터 다시 잡는 것도 좋은 방법입니다. :)

**Comment by mahns1201** [comment]
> 안녕하세요.
> 올려주신 에러코드는 다양한 원인이 있어 확실한 원인을 찾기는 조금 힘들어 보입니다.
> 혹시 에러난 부분 캡쳐나 코드쪽을 캡쳐해서 올려주실 수 있나요??

분명히 질문을 한 날에는 오류가 f5키 한번당 한번씩 나서 질문을 올렸는데 오류를 캡처하려니까 나타나지가 않습니다. 그런데 몇번 실행하다 보면 안되서 terminal을 지우고 다시 하기를 반복했는데 아랫분 말씀처럼 지우고 다시 환경을 설정해보려고 합니다! 프로그램에 처음 입문해서 수준 낮은 질문인데 답변해 주셔서 감사합니다.

**Comment by mahns1201** [comment]
> debug를 위한 interpreter 설정이 잘못되어 있을수도 있고, 사용하는 extention이 충돌을 일으킬 수도 있을 것 같아요.
> 환경이 아예 꼬여서 손댈수 없다면, vscode를 삭제한 뒤에 재설치해서 환경을 처음부터 다시 잡는 것도 좋은 방법입니다. :)

네 한번 아예 지우고 다시 해보겠습니다. 감사합니다!
