### ISSUE TITLE
nodejs 경고문구 질문입니다!

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#52]
npm으로 모듈들을 설치하다보면 No repository field라는 경고문구가 자꾸 나오는데, 아마 저장소를 등록안해서 나오는 문구같습니다. 이 경고문구를 무시하고 진행해도 될까요?

**Comment by haebin** [comment]
구글 검색: "npm no repository field"

아래 참고하세요.
https://stackoverflow.com/questions/16827858/npm-warn-package-json-no-repository-field
