### ISSUE TITLE
모바일 및 프로그래머 관련 질문드립니다.

### ISSUE THREAD

**Issue by dasd412** [codingeverybody/codingyahac#520]
안녕하세요. 이번년도에 컴퓨터공학과 복수전공을 앞두고 있는 학생입니다.  언어는 java를 사용하고 있습니다. 해본 프로젝트는 아직 없습니다. ㅠㅠ 아직 기능 구현밖에 한게 없네요....
제가 궁금한 것은 네 가지입니다. (특히 네 번째꺼!!)
1.대학교 모바일 어플을 만들어보고 싶은데 필요한 사항들, 예를 들면 공부해야 할 것들이 뭐뭐있나요?
(최대한 심플하게 만들려고합니다. )
2.모바일 프로그래머가 되고 싶은데 학부 생활 중에 어떤 것을 공부해야 할까요?  그냥 학교 공부만 충실히 한다음 졸업해서 추가적으로 모바일 공부하면 될까요? 아니면 학부 생활 중에 틈틈히 (방학등을 이용해서) 공부해야 할까요?
3.대학원 석사 과정까지 필요한 프로그래머 관련 진로는 어떤 것들이 있나요?
4.지금 제 실력은  알고리즘이나 트리 정도의 자료구조를 구현할 정도인데요......즉 ,기능 구현이랑 참조 정도는 할 줄 아는데요.ㅠ  그런데 저는 객체들끼리 상호작용하면서 시스템을 구성하는... 진짜 '프로그램'을 만들어보고 싶어요... 이 단계로 나아가려면 어떻게 해야하나요? 선배님들은 어떤 방식으로 이 단계로 나아가셨고 어떻게 공부하셨는지 여쭙고 싶습니다. (간단한 게임이라도 만들어보고 싶어요!!)

**Comment by fermat39** [comment]
안녕하세요... 
저도 수학을 주전공으로 하고 CS를 복수전공한 사람입니다. ㅎㅎ
아직 3학년을 앞두신 것으로 생각이 됩니다. 아마도 막막하고 답답하시리라 생각이 됩니다.

질문 내용을 보면 의욕이 앞서서 너무 걱정이 많이 생기신 것 같습니다. 
너무 크게 시작하시마시고 작게 시작하시기 바랍니다. 
특히, 네트워크 활동을 통해 사람들과 만나고 그를 통해 기회가 생기기도 합니다.

아니면 직접 Toy 프로젝트를 시작해 가시면서 좋은 기회가 생기기도 합니다.
제 지인도 필요에 의해 작제 시작했지만 2018년 오픈소스  경연대회에서 금상을 타시기도 했고요...

분명 주변에 멘토가 되어주실 분이나 좋은 기회가 있을거예요... 
질문을 하셨기에 좋은 기회가 있을 것이라고 생각이 됩니다. 

정~~말 답답하시면 연락주세요... ㅎㅎ

화이팅입니다.

**Comment by blackdew** [comment]
1. 모바일을 개발 언어가 여러가지가 있지요. 아직 개발해 본것이 없으시다면 가장 심플하게 접근해 보시는게 어떨까 싶어요. 모바일 어플을 완성해 보는 것을 목표로 두고 html+javascript+css를 이용한 webapp 쪽으로 접근하는 것을 드립니다. 

2. 모바일이라면 언어공부는 사실상 답이 몇가지 정해진것 같아요. native 앱이라면 swift, kotlin 을 보시면 되고요. 모바일 웹과 웹앱 쪽에 관심이 많으시다면 reactjs, vuejs, angularjs 중에서 선택하시면 됩니다. 
제 개인적으로는 모바일쪽으로 가시더라도 '데이터 구조', '알고리즘', '리팩토링/클린코드' 등과 같은 기본기에 대해 더 공부를 하시는 걸 더 추천드립니다. web, internet, http, 암호화 hash 등 현재 프로그램 생태계의 근간이 되는 기술에 대한 공부도 하시면 좋겠습니다. 

3. 대학원 석사 과정은 아주 많아서 일일이 나열하기는 어려운 것 같습니다. 현재는 빅데이터와 머신러닝 분야가 관심을 많이 받고 있지 않나 싶어요. 

4. '만들어보고 싶은 무언가'를 찾는 것은 쉬운 일은 아닌 것 같아요. 본인의 프로젝트를 생각해 내면 최고이긴 한데요. 그것도 어렵다면 남들이 만들어 놓은 작은 무언가를 찾아서 그것을 그대로 구현을 해보는 것도 좋은 경험이 될거에요. 예전에 재미있게 했었던 게임 이나 유용하게 사용했던 프로그램 중에 가장 작은 것을 하나 정하셔서 그대로 구현해 보시는 건 어떨까요? :)

**Comment by dasd412** [comment]
자세한 답변들 감사합니다!!
