### ISSUE TITLE
Javascript에서 첫 번째 오디오가 종료된 후에 조건을 따져서 두 번째 오디오를 재생하고 싶어요.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#521]
# 해결하고자 하는 문제
안녕하세요?
제목과 같이 어떤 오디오가 다 재생된 후에 조건을 따져서 다음 오디오를 재생하고 싶습니다.
지금의 코드로는 첫 번째 오디오의 재생이 끝나기도 전에 다음 오디오가 재생이 되어버립니다.

# 코드 혹은 오류
```
     // 첫 번째 오디오 
  function audioPlay(content) {
    if(currentSound) {
      currentSound.pause();
      currentSound.currentTime = 0;
    }
    if(vowel_array.indexOf(content) == -1) {
      currentSound = new Audio('audio/consonant/'+content+'.mp3');
      consonant = content;
    } else if(consonant_array.indexOf(content) == -1) {
      currentSound = new Audio('audio/vowel/'+content+'.mp3');
      vowel = content;
    }
    currentSound.play()

  // 두 번째 오디오
    let ass = consonant.concat(vowel);
    if(ass.indexOf("null") == -1) {
      currentSound = new Audio('audio/ass1/'+ass+'.mp3');
      currentSound.play()
    }
  }
```

# 환경
Javascript

# 시도해본 방법

Promise를 사용해야 하는 문제인 것 같아서 이리저리 노력해 봤는데 잘 작동하지 않습니다.

**Comment by blackdew** [comment]
아래 코드가 도움이 될 것 같네요 :)

```
var aud = document.getElementById("myAudio");
aud.onended = function() {
    alert("The audio has ended");
};
```
https://www.w3schools.com/tags/av_event_ended.asp

**Comment by kammaii** [comment]
> 아래 코드가 도움이 될 것 같네요 :)
> 
> ```
> var aud = document.getElementById("myAudio");
> aud.onended = function() {
>     alert("The audio has ended");
> };
> ```
> https://www.w3schools.com/tags/av_event_ended.asp

답변 감사합니다.
그런데 도움 주신 코드는 HTML에서 audio 태그를 사용하는 것 같은데 
제 코드는 터치 드래그 앤 드롭을 하면 첫 번째 오디오가 시작하는 방식이어서 작동을 하지 않는 것 같습니다.
다른 방법이 있을까요?

**Comment by blackdew** [comment]
드래그앤드롭은 사용방법에 대한 내용으로 오브젝트의 이벤트 처리하는 것과는 별개의 내용이에요. 
new audio로 객체를 생성하셨으면 객체의 이벤트를 사용할 수 있습니다. 

직접 audio 객체를 이용하는 것이라면 아래의 코드를 참고하시면 되겠네요. :) 

```
audio = new Audio();
audio.addEventListener("ended", function(){ 
    alert("The audio has ended");
});
```

audio 객체 이벤트에 대해서 참고하시면 해결점을 찾으실 수 있을 거에요. 
http://www.developphp.com/video/JavaScript#Audio-Programming
http://www.developphp.com/video/JavaScript/Audio-Playlist-Array-Tutorial

**Comment by kammaii** [comment]
> 드래그앤드롭은 사용방법에 대한 내용으로 오브젝트의 이벤트 처리하는 것과는 별개의 내용이에요.
> new audio로 객체를 생성하셨으면 객체의 이벤트를 사용할 수 있습니다.
> 
> 직접 audio 객체를 이용하는 것이라면 아래의 코드를 참고하시면 되겠네요. :)
> 
> ```
> audio = new Audio();
> audio.addEventListener("ended", function(){ 
>     alert("The audio has ended");
> });
> ```
> audio 객체 이벤트에 대해서 참고하시면 해결점을 찾으실 수 있을 거에요.
> http://www.developphp.com/video/JavaScript#Audio-Programming
> http://www.developphp.com/video/JavaScript/Audio-Playlist-Array-Tutorial

와!! 잘 작동하네요! 감사합니다!! :)
