### ISSUE TITLE
user agent stylesheet 은 어떻게 해결하나요??

### ISSUE THREAD

**Issue by seakgba** [codingeverybody/codingyahac#523]
# 해결하고자 하는 문제

user agent stylesheet 가 생기면서 태그에 클래스 아이디속성을 달아도 css가 적용되지 않습니다
vue.js라 <!doctype html> 속성을 적는것도 아닌거 같은데..ㅠ

# 환경
vue.js

# 시도해본 방법
css  !important 적용해도 반영이 안됩니다ㅠ

**Comment by blackdew** [comment]
vue.js가 동적으로 html을 생성합니다 
브라우저 상에서 개발자도구를 사용해서 style을 주기 위한 tag와 class, id를 일일이 확인해 보시면 
적용이 안되는 이유를 찾으실 수 있을 거에요.
