### ISSUE TITLE
블로그를 만들고 싶습니다.

### ISSUE THREAD

**Issue by sdYoo** [codingeverybody/codingyahac#526]
웹 프로그래밍을 이용해서 블로그을 만들려고 합니다. 

화면은 react js, 개발언어는 java-springboot, database는 mysql로 구성할 생각입니다.
추후에는 python 및 다른 언어로 개발한 프로그램과 연동도 해볼 생각입니다. 
오래 전에 잠시동안 jsp로만 웹 개발을 해본게 전부여서 개념이 잘 잡히지 않아 몇가지 질문을 드립니다.

1) react js와 springboot 연동을 많이 사용하나요? react js가  jsp 역활을 하는 것이라고 봐도 되는건가요?

2) 메인화면을 react js로 구성한다고 하면 tiles 와 같이 메인화면을 나누는 구성도 가능한가요? 

3) 메인화면에서 A 메뉴(ex.회원정보관리)는 springboot로 개발하고 B 메뉴(ex.자산등록관리)는 python-flask를 이용해서 개발을 하고 싶은데 이러한 구성도 가능한가요? 

4) react js는 화면을 구성하는 프레임 워크라고 본다면 react js 로 구성한 화면에서 조회버튼을 눌렀을때 뒷단의 컨트롤러 역활은 springboot+mysql 또는 python-flask+mariadb 같은 구조로 개발이 가능한가요?

5) 메인화면에서 세부 화면 마다 다른 프로그래밍언어로 개발한 화면을 호출하려고 할때에 
가장 좋은 구성은 어떻게 해야하는게 좋은지 알고 싶습니다. 

제가 하려고 하는 것은 하나의 블로그에서 각각의 메뉴를 호출하면 각각 다른언어및DBMS로 개발한 페이지를 호출하도록 하고 싶습니다.

test.com으로 접속하면 메인페이지가 뜨고 메뉴바에 성적조회|사원조회|연봉조회 이렇게 메뉴가 있고 
성적조회를 클릭하면 sprinngboot+mysql로 개발한 화면이 뜨며, 연봉조회를 누르면 python-flask+postgres로 개발한 화면이 뜨는 것을 구현하고 싶은 것입니다. 
이걸 msa라고 봐도 되는 건가요?

**Comment by studroid** [comment]
1. 말씀하신 환경에서 React는 클라이언트단 처리를 하기 위해 쓰입니다. 즉, 사용자의 화면에 뭔가 보여주고, 데이터에 따라 동적으로 화면 구성을 바꿀 때 쓰일 수 있겠지요. 정확히는 JSP를 대체하기보다는, 자바스크립트를 구조적으로 쓸 수 있게 도와주는 것이라 보면 될 듯합니다.

2. 메인화면을 타일로 나누는 구성은 리액트를 쓰지 않더라도 가능하고 쓰더라도 가능합니다 :)

3. 가능합니다. 다만 이를 위해서는 네트워크와 서버의 개념을 정확히 이해하고 계셔야 합니다. 물론 실제 서비스용이라면 이렇게 구성할 요인이 거의 없습니다만, 학습을 위해 시도해보실 수는 있겠죠? 다만, 이렇게 해보기 전에 각 언어 및 개발환경별로 따로따로 만들어보고 배우신 뒤에 시도해보시는 게 좋겠습니다.

4. 가능합니다. AJAX 등으로 서버로 데이터 송신 요청을 보낼 때, 클라이언트는 API 호출을 통해 서버 환경이 어떤 것인지 몰라도 내가 원하는 데이터를 요청할 수 있습니다. 어떤 웹사이트가 어떤 환경으로 구성되어 있는지 몰라도 우리는 웹브라우저로 접속해서 원하는 화면을 볼 수 있죠. 이것과 동일한 원리라고 보시면 됩니다.

5. 프레임(frame), 아이프레임(iframe)에 대해서 찾아보시면 좋을 듯합니다. 생활코딩에도 다음 링크에 관련 자료가 있으니 확인해보세요! https://opentutorials.org/course/2039/10951

이렇게 다 구성하시면 그 형태로 볼 때 일종의 MSA라고 볼 순 있겠지만, 이 경우에는 MSA를 써서 얻을 수 있는 실질적인 이득은 없다고 봐야겠지요? ^^
