### ISSUE TITLE
javascript array에서 일치하는 String의 array number를 얻고 싶습니다.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#528]
# 해결하고자 하는 문제

안녕하세요?
검색을 하면 string array에서 일치하는 string을 찾는 기능은 나오는데 
저는 그 string의 array number를 가져오고 싶습니다.
지금 문득 떠오르는 생각은 for문을 돌려서 string이 일치할 때의 i 값을 가져올 수 있을 것 같은데
혹시 좀 더 간단한 방법이 있나요? 

# 환경
javascript

**Comment by yoobato** [comment]
Javascript의 Array에 IndexOf 라는 메소드가 있습니다.

아래 링크 참고해보세요!
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by kammaii** [comment]
> Javascript의 Array에 IndexOf 라는 메소드가 있습니다.
> 
> 아래 링크 참고해보세요!
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

아! 이걸 잊고있었네요! 감사합니다! :)
