### ISSUE TITLE
nodejs express 모듈 설치시 에러

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#53]
npm으로 express 모듈 설치후에 생성되는 폴더인 mine의 cli.js 파일에 #!/usr/bin/env node가 첫줄에 코드인데 이부분이 기본적으로 에러가 뜹니다. 문법상의 오류인지 왜 오류가 뜨는지 잘 모르겠어서 우선 주석처리를 해놨는데, 중요한 부분일까요??

**Comment by ghdalsrldi** [comment]
어떤 오류 메세지가 뜨는지 알려 주신다면 오류 내용을 파악할 수 있을 것 같아요
