### ISSUE TITLE
javascript의 touch drag and drop에 대해 질문이 있습니다. (jquery 아님)

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#530]
# 해결하고자 하는 문제
jquery를 사용하니 문제가 좀 있어서 pure javascript로 touch drag and drop을 만들었습니다.
touch drag 한 박스의 글자를 drop한 박스 안에 넣는 기능인데
잘 작동은 되는데 touch drag 중에 해당 박스가 손가락을 따라 움직이는 기능을 추가하고 싶습니다.

# 코드 혹은 오류
```
   newElement.addEventListener("touchstart", touchDrag, false);
   newElement.addEventListener("touchend", touchDrop, false);
   newElement.addEventListener("touchmove", touchMove, false);

    var lastTouchId = null;

    function touchDrag(ev) {
      ev.preventDefault();
      lastTouchId = ev.target.id;
    }

    function touchDrop(ev) {
      ev.preventDefault();
      let content = document.getElementById(lastTouchId).textContent;
      var changedTouch = ev.changedTouches[0];
      var elem = document.elementFromPoint(changedTouch.clientX, changedTouch.clientY);
           
      document.getElementById("assembly").innerHTML = content;
    }

    function touchMove(ev) {
      ev.preventDefault();
      let x = ev.touches[0].clientX;
      let y = ev.touches[0].clientY;
     }

```

# 환경
javascript

# 시도해본 방법
touchMove 함수에서 touch 부위의 x와 y 좌표를 구할 수 있었습니다. 
touch drag 중인 박스가 이 좌표를 따라다니게 하면 될 것 같은데 어떻게 해야 할 지 모르겠습니다.

**Comment by jinsu421** [comment]
해당하는 box를 찾아서 box 좌표에 touch 부의 x,y 좌표를 넣으면 기능이 유사하게 가능하지않을까요?

**Comment by kammaii** [comment]
> 해당하는 box를 찾아서 box 좌표에 touch 부의 x,y 좌표를 넣으면 기능이 유사하게 구현되지않을까요?

빠른 답변 감사합니다. :)
다른 박스들의 배치를 방해하지 않기 위해 같은 모양의 박스(#movingBox)를 display:none 으로 만들어 놓고 touch가 발생했을 때 display:initial 로 바꾸어 position: absolute의 top과 left에 각각 x,y 좌표를 넣어줬습니다. 
이렇게 하면 박스가 touch를 따라 움직일 것 같았는데 꼼짝도 안해요 ㅜ.ㅜ
position: absolute를 사용하기 위해 상위 div에 position: relative도 했습니다.
```
    function touchMove(ev) {
      ev.preventDefault();
      let x = ev.touches[0].clientX;
      let y = ev.touches[0].clientY;
      
      document.getElementById("movingBox").style.display = "initial";
      document.getElementById("movingBox").style.top = x;
      document.getElementById("movingBox").style.left = y;
    }
```
