### ISSUE TITLE
[PHP] 'Internal Server Error' 가 났습니다 ㅠㅠ

### ISSUE THREAD

**Issue by woong9149** [codingeverybody/codingyahac#534]
PHP로 게시판 만들기를 하다가
'Internal Server Error' 가 났습니다 ㅠㅠ
파일 다운로드와 업로드 부분은 구현하다가 났던것같은데...(에러 이후로 작업을 멈춘지 한달됐습니다.)
다른 질문채널을 통해 시간이 지나면 알아서 해결이 된다는 말을 믿고 기다려본 결과 계속 그대로네요...
어떻게 해결해야 할까요?

**Comment by yoobato** [comment]
말씀해주신 내용만으로는 도와드리기 어려울 것 같아요.

구체적인 오류 내용과, 오류가 발생하는 소스를 첨부해주시면 좋을 것 같습니다!

**Comment by fermat39** [comment]
안녕하세요... 
PHP를 운영하시는 환경이 궁금합니다. 버전은 무엇이고,
PHP와 연결된 서버는 무엇이고, 운영체제는 무엇인지....

아마도 해당 사항과 관련된 에러로그도 당연히 있을 것이라고 생각됩니다!

좀더 자세한 내용 부탁드립니다!!!

**Comment by woong9149** [comment]
잘 정리해서 질문했어야되는데 생각없이 급하게 질문드려서 죄송합니다.
<img width="960" alt="default" src="https://user-images.githubusercontent.com/42554237/50969585-57f11700-1522-11e9-8b5d-08ac383ee863.png">
우선 에러가 뜬 화면이구요,
해당페이지의 소스코드입니다.
`<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
include('dbconn.php');
$id=$_GET['id'];
//글 번호에 해당되는 첨부파일의 이름
$result = mysqli_query($conn," SELECT filename FROM board WHERE id=$id");
$row= mysqli_fetch_array($result);
$filename= $row['filename'];
if($filename){
  $path = "C:\Bitnami\wampstack-7.1.22-0\apache2\htdocs\pds\uploads\\$filename";
//파일이름에 한글, 특수문자 있을때 => urldecode
$real_filename=urldecode('filename');//url decode
header('Content-Type: application/x-octetstream');
header('Content-Dispositon: attachment; filename='.$real_filename);
header('Content=Length:'.filesize($path));
header('Content-Transfer-Encoding: binary');
header('Pragma: no-cache');
header('Expires:0');
flush();//출력 버퍼 비우기
$fp = fopen($path,"r");//파일을 읽기 모드로 오픈
fpassthru($fp);//파일 내용을 곧바로 출력
fclose($fp);//파일 닫기
}//다운로드 횟수 증가 처리
mysqli_query($conn,"UPDATE board SET down=down+1 WHERE id=$id");
mysqli_close($conn);
 ?>
`
현재 windows 10 사용중이며, 에디터는 ATOM, 그리고 서버는  bitnami 쓰고있습니다.
php 버전은 PHP Version 7.1.22입니다. 코딩 초짜라 충분하게 정보를 드렸는지 모르겠습니다 ㅠㅠ

**Comment by yoobato** [comment]
@woong9149 혹시, https://opentutorials.org/course/62/1803 이거 참고하셔서, 에러 로그 내용 복사해서 올려주실 수 있으세요!?

**Comment by woong9149** [comment]
C:\Bitnami\wampstack-7.1.22-0\apache2\logs에 있는 error파일에서
오늘 날짜로 되있는것만 찾았습니다. 전체 내용을 복사해드려야되나요?

> [Thu Jan 10 02:14:43.275742 2019] [mpm_winnt:notice] [pid 4040:tid 620] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Thu Jan 10 02:14:45.309700 2019] [mpm_winnt:notice] [pid 6968:tid 592] AH00364: Child: All worker threads have exited.
[Thu Jan 10 02:14:45.450239 2019] [mpm_winnt:notice] [pid 4040:tid 620] AH00430: Parent: Child process 6968 exited successfully.
[Thu Jan 10 02:15:17.755733 2019] [ssl:warn] [pid 3700:tid 612] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 10 02:15:18.184755 2019] [ssl:warn] [pid 3700:tid 612] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 10 02:15:18.500929 2019] [mpm_winnt:notice] [pid 3700:tid 612] AH00455: Apache/2.4.34 (Win64) OpenSSL/1.0.2o PHP/7.1.22 configured -- resuming normal operations
[Thu Jan 10 02:15:18.500929 2019] [mpm_winnt:notice] [pid 3700:tid 612] AH00456: Apache Lounge VC14 Server built: Jul 15 2018 11:48:32
[Thu Jan 10 02:15:18.500929 2019] [core:notice] [pid 3700:tid 612] AH00094: Command line: 'C:\\Bitnami\\WAMPST~1.22-\\apache2\\bin\\httpd.exe -d C:/Bitnami/wampstack-7.1.22-0/apache2 -f C:\\Bitnami\\WAMPST~1.22-\\apache2\\conf\\httpd.conf'
[Thu Jan 10 02:15:18.521465 2019] [mpm_winnt:notice] [pid 3700:tid 612] AH00418: Parent: Created child process 5836
[Thu Jan 10 02:15:20.970280 2019] [ssl:warn] [pid 5836:tid 536] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 10 02:15:21.350952 2019] [ssl:warn] [pid 5836:tid 536] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jan 10 02:15:21.454050 2019] [mpm_winnt:notice] [pid 5836:tid 536] AH00354: Child: Starting 64 worker threads.
[Thu Jan 10 21:36:31.367101 2019] [http:error] [pid 5836:tid 1256] [client ::1:5584] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request, referer: http://localhost/pds/list.php
[Thu Jan 10 21:38:24.686644 2019] [php7:notice] [pid 5836:tid 1252] [client ::1:5644] PHP Notice:  Undefined index: filename in C:\\Bitnami\\wampstack-7.1.22-0\\apache2\\htdocs\\pds\\download.php on line 3
[Thu Jan 10 21:38:24.687642 2019] [http:error] [pid 5836:tid 1252] [client ::1:5644] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request
[Thu Jan 10 21:38:30.825495 2019] [php7:notice] [pid 5836:tid 1256] [client ::1:5645] PHP Notice:  Undefined index: filename in C:\\Bitnami\\wampstack-7.1.22-0\\apache2\\htdocs\\pds\\download.php on line 3
[Thu Jan 10 21:38:30.825495 2019] [http:error] [pid 5836:tid 1256] [client ::1:5645] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request
[Thu Jan 10 21:38:49.661573 2019] [php7:notice] [pid 5836:tid 1256] [client ::1:5656] PHP Notice:  Undefined index: filename in C:\\Bitnami\\wampstack-7.1.22-0\\apache2\\htdocs\\pds\\download.php on line 3
[Thu Jan 10 21:38:49.663055 2019] [http:error] [pid 5836:tid 1256] [client ::1:5656] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request
[Thu Jan 10 21:49:42.872211 2019] [http:error] [pid 5836:tid 1252] [client ::1:5808] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request, referer: http://localhost/pds/read.php?id=116&no=
[Thu Jan 10 21:53:49.822192 2019] [http:error] [pid 5836:tid 1256] [client ::1:5907] AH02429: Response header name 'Content=Length' contains invalid characters, aborting request, referer: http://localhost/pds/list.php

**Comment by yoobato** [comment]
오류 로그를 보니,
```
Response header name 'Content=Length' contains invalid characters, aborting request
```
이라는 내용이 반복적으로 확인되네요.

HTTP 헤더를 설정하는 부분에,
Content=Length 라고 오타난 부분이 있는지 확인해보시면 될 것 같습니다.

[Content-Length](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Content-Length)라고 쓰셔야 합니다!

**Comment by woong9149** [comment]
와... 됩니다...
아까도 설명에 빠뜨린부분이,
원하는데로 구현이 안되서 제가 틀렸다고 생각하는부분을 계속 고치다가  에러가 났거든요.
엉뚱한데만 고치고, 틀린부분을 그대로 둔채로 계속 리로드를해서 그런 오류가 났던것같습니다. 감사합니다 ! 새해복 많이 받으세요 !

**Comment by yoobato** [comment]
@woong9149 오류가 날 때는, 위에 올려주신 것처럼 오류 로그를 확인해보는게 좋습니다 :)

팁을 드리면! 오류 로그가 무슨 말인지 잘 모르겠는 때에는, 로그 내용을 복사해서 구글에 검색하면, 관련된 내용이 많이 나올 것입니다!

이 issue는 close 하겠습니다. 화이팅하시고, 새해 복 많이 받으세요 😄
