### ISSUE TITLE
background: linear-gradient 가 제대로 작동되지 않습니다.

### ISSUE THREAD

**Issue by Hellobonjour101** [codingeverybody/codingyahac#538]
# 해결하고자 하는 문제
background: linear-gradient 부분이 chrome에서는 동작하는데 IE에서 작동하지 않아서
cross browsing을 어떻게 해야 하는지 여쭤보고 싶습니다. 

mac컴퓨터로 작업해서 chrome에서는 아래와 같이 잘 작동을 합니다만, 
<img width="741" alt="screen shot 2019-01-09 at 10 56 10 pm" src="https://user-images.githubusercontent.com/43777600/50903759-f6697380-1461-11e9-8ab6-29b4d5dee9af.png">

윈도우에서 열어보면, 다음과 같습니다
![img_4765](https://user-images.githubusercontent.com/43777600/50903952-7263bb80-1462-11e9-9bbe-63576af690e8.jpg)
. 

# 코드 혹은 오류
``` 
이 코드가 작동을 안합니다. 
 background: linear-gradient(to right, #1A9BF1 0%, #0017AE 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    -ms-background-clip: text;
    -ms-text-fill-color: transparent;
    -moz-background-clip: text;
    -moz-text-fill-color: transparent;
    -o-background-clip: text;
    -o-text-fill-color: transparent;
```

# 환경
HTML/ CSS만 사용하고 있습니다. 

# 시도해본 방법

아래와 같이 li 태그 배경에 linear-gradient를 넣는것은 cross browsing을 하는 법을 찾았습니다.
<img width="200" alt="screen shot 2019-01-09 at 10 56 54 pm" src="https://user-images.githubusercontent.com/43777600/50904038-9cb57900-1462-11e9-8152-79bc5081c7f5.png">

```
이것은 작동을 합니다. 
  background-image: -webkit-linear-gradient(left, #1A9BF1 0%, #0017AE 90%);
  background-image: -moz-linear-gradient(left, #1A9BF1 0%, #0017AE 90%);
  background-image: -ms-linear-gradient(left, #1A9BF1 0%, #0017AE 90%);
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1A9BF1', endColorstr='#0017AE',GradientType=1 );
  background-image: -o-linear-gradient(left, #1A9BF1 0%, #0017AE 90%);
  background-image: linear-gradient(left, #1A9BF1 0%, #0017AE 90%);
```
구글링을 해봤는데, 잘 안찾아져서 질문 드립니다!! ㅠㅠ

**Comment by studroid** [comment]
전체 코드를 알 수 없어서 정확히 어떻게 적용될지는 모르겠지만, 아래와 같이 두 가지 방법이 있는 것 같습니다.

https://stackoverflow.com/a/48263230

https://codepen.io/noah2233/pen/LGZPPL

아마 위 두 링크의 CSS를 참고하시면 해결하실 수 있을 듯합니다 :)

위 자료로 해결이 어려우시면 해당 코드 부분을 같이 올려주세요!
