### ISSUE TITLE
<php> Web에 표시가 지연되며, 특정함수를 썼을 때 먹통

### ISSUE THREAD

**Issue by sonice21c** [codingeverybody/codingyahac#539]
# 해결하고자 하는 문제
문제를 연이어 올려서 마음이 불편하지만, 
제 상황에서 문제 파악이 되지 않아서 도움을 구합니다. 

최근에 올렸던 문의인데,

1) Php를 사용하면 Web에서 확인하면 1분정도 지연되어 반영되는 '딜레이'증상이 있습니다. 
2) 이번엔 조건문 if 를 써서 본문의 내용을 표기하려고 하니, 웹페이지가 아무것도 출력이 안되는 '먹통'증상이 있습니다.

<h2>
<?php
if(isset($_GET['id'])){
echo $_GET['id'];
} else {
  echo "welcome";
}
  ?>
</h2>
<p>
  <?php
if(isset($_GET['id')){
echo file_get_contents("data/".$_GET['id']);
} else {
  echo "Hello";
}
?>
</p>

이 코드 중 

<?php
if(isset($_GET['id')){
echo file_get_contents("data/".$_GET['id']);
} else {
  echo "Hello";
}
?>

이 부분을 지우면, 출력은 되지만, 지연문제는 해결되지 않고 있습니다. 
이 부분을 추가하면 아무것도 출력이 되지 않는 먹통증상이 반복되며 그마저도 지연되어 반영됩니다.

# 코드 혹은 오류
index.php 파일에 담긴 코드

```

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <h1><a href="index.php">Barceloven</a></h1>
    <ol>
        <li><a href="index.php?id=Devotion">Devotion</a></li>
        <li><a href="index.php?id=Music">Music</a></li>
        <li><a href="index.php?id=Orchestration">Orchestration</a></li>
        <li><a href="index.php?id=Church">Church</a></li>
      </ol>
<h2>
<?php
if(isset($_GET['id'])){
echo $_GET['id'];
} else {
  echo "welcome";
}
  ?>
</h2>
<p>
  <?php
if(isset($_GET['id')){
echo file_get_contents("data/".$_GET['id']);
} else {
  echo "Hello";
}
?>
</p>
  </body>
</html>
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Mac OS High Sierra 10.13.6, PHP 

# 시도해본 방법

컴퓨터 재부팅, 서버 재부팅, 아톰 재부팅, 웹 재부팅.

**Comment by yoobato** [comment]
PHP의 [file_get_contents()](http://php.net/manual/en/function.file-get-contents.php)는 파일의 내용을 읽어들이는 함수입니다.

올려주신 코드대로라면, Devotion을 클릭했을 때,
`echo file_get_contents("data/devotion");` 이렇게 될텐데,
이때, `data/devotion` 이 경로에 해당하는 파일이 존재하는지 확인을 먼저 해보셔야할 것 같습니다.

**Comment by yoobato** [comment]
PHP 가 느린 것에 대해서는, https://github.com/codingeverybody/codingyahac/issues/531#issuecomment-452749581 이곳에 답글을 달아놓았습니다!

**Comment by fermat39** [comment]
안녕하세요....
일단, 왜 굳이 이런 방식으로 웹페이지를 만드시는지 궁금합니다.

**Comment by sonice21c** [comment]
답변 감사합니다.
3개의 답변을 따로 주셔서 개별적으로 답하겠습니다.

확인해봤더니 Data/Devotion 파일은 존재합니다.
그런데 다른 파일들은 확장자가 Html이나 php 인데,
Data 폴더에 들어있는 파일들만 확장자가 없습니다.
실행시켜보면 텍스트 편집기로 열립니다.

눈에 띄는 점은 일단 이부분입니다.

2019년 1월 10일 (목) 오전 12:57, Daeyeol Ryu <notifications@github.com>님이 작성:

**Comment by sonice21c** [comment]
안녕하세요!
먼저는 저는 코딩을 전혀 할 줄 모릅니다.
이번에 코딩야학 5기로 처음 시작하게 되었고,
흥미를 느껴 CSS 와 php 까지 진도를 나가면서
웹페이지를 만들던 중이었습니다.

진도대로 하다보니 제가 의도한 바는 거의 없다고 보셔도 무방합니다.
따라했을 뿐이거든요^^;



2019년 1월 10일 (목) 오전 1:13, fermat39 <notifications@github.com>님이 작성:

**Comment by sonice21c** [comment]
느려지는 문제는 아직 건드려보지 못했습니다만, 

if 조건문 문제는 해결된 것 같습니다.

식을 쓸 때 괄호의 열고 닫음의 갯수가 완전하지 못해서 그런 에러가 났던 것으로 보입니다. 
코딩야학을 통해 코딩을 배워가고 있으며, 또한 문제가 생겼을 때 도움을 받을 수 있다는 것이 굉장히 큰 힘이 됩니다. 
비록 저의 작은 실수였지만, 여러분들이 같이 고민해주시니 코딩을 배워가는데 용기를 낼 수 있어서 감사하게 생각하고 있습니다. 

늦었지만 다시 한번 감사의 말씀 드립니다.

**Comment by yoobato** [comment]
@sonice21c

Data/Devotion 파일 내용 좀 올려주시겠어요?

아 그리고!
파일의 확장자는 이 파일이 '어떤 파일'인지를 운영체제한테 알려줘서, 적절한 프로그램으로 열리게 유도하는
힌트에 불과해요! 따라서, 파일의 확장자가 없는 경우도 있습니다 😄

**Comment by sonice21c** [comment]
선생님, 안녕하세요!

Devotion 파일 안에는 
--
묵상을 위한 공간.
--

7글자와 . 점하나가 찍혀있습니다.

태그는 전혀 없습니다.

이고잉님 강의를 보면서 그렇게 하시는 것을 보고 요령껏 따라했습니다.

그런데 지금은 그 문제가 잘 해결되었습니다. 

제가 괄호를 닫고 여는 것의 갯수를 잘 파악하지 못해서 
완전하지 않은 코드로 인색했었던 것 같습니다. 


현재 가장 큰 문제라면, 코드를 변경하고 웹 상에서 확인할 때 
지연되어 반영되는 문제가 제게는 가장 큰 불편함 입니다. 

알려주신 링크로 들어가보았는데 결과적으로는 제 상황과 유사해보이지만, 

그것을 조절하는 과정이 제 상황과 차이가 있는 것 같아서 적용을 못 시키고 있습니다.

도움을 구하고 싶지만, 여기서 더 어떻게 도움을 구해야하는지 모르겠는 것이 가장 큰 문제일지도 모르겠네요^^;

코딩을 배워가는 중 어떤 번거로움도 감수할 각오가 되어있어서 원하시는대로 해볼 마음도 있습니다.

그리고 바쁘신 중에도 마음 써주셔서 정말 감사합니다. 

일단은 이렇게 답변을 마칩니다. 



* 확장자가 힌트라는 것이 재밌는 관점으로 배우게 되는 말씀 같습니다. 감사합니다^^

**Comment by sonice21c** [comment]
선생님, 추가로 드릴 말씀은, 

알려주신 링크의 사이트를 보니, 

초보자인 제가 이해하기에는 다소 어려움이 있습니다. 

그리고 이전 답변에 적었던 내용이지만, 제가 사용하는 환경과 차이가 있어서 
적용하는 것이 제한되는 것 같습니다. 

예를 들어, MAMP의 OP Cache 를 변경하라는데 제가 사용하는 MAMP프로그램은 

어디서 그런 설정을 만지는 것인지 모르겠습니다. 

CMD+, 속성을 눌러보아도 속성이 뜨지 않고,
뭔가를 조절하는 설정하는 옵션이 없는 것 같습니다.

**Comment by yoobato** [comment]
@sonice21c 

혹시 index.php 에 접속하실 때, 어떤 주소를 사용하시나요?
다시 말해서, 주소창에 어떤 주소를 입력하셔서 index.php 파일을 여시는지요?

**Comment by sonice21c** [comment]
http://127.0.0.1:8080/index.php

위의 주소를 사용합니다.

**Comment by yoobato** [comment]
@sonice21c 

흠... 이럴 땐, 참 옆에서 같이 도와드리면 좋을텐데, 글로 설명하려니 한계가 느껴지네요 ㅠ.
혹시 크롬을 쓰시면, 개발자 도구의 Network 탭을 확인해보시겠어요?

<img width="814" alt="screen shot 2019-01-10 at 9 37 13 pm" src="https://user-images.githubusercontent.com/1592319/50968899-f465ea00-151f-11e9-97f9-51a0f6a8d4b7.png">

위 스크린샷 참고하셔서 개발자 도구를 선택하시면, (제 맥이 영어 버전이라 ㅠ... 한국어로는 어떻게 되어있는지 잘 모르겠네요.) 창이 하나 뜨게 됩니다.

위 쪽에 보면, Network 라는 탭이 있는데, 이걸 클릭하시고 한 번 사이트를 새로고침해보세요.
그럼, 사이트에 사용된 리소스 별로, 로드하는데 얼마의 시간이 걸리는지 볼 수 있고, 문제를 확인할 수도 있을 것 같습니다!

**Comment by sonice21c** [comment]
제가 볼 줄 몰라서 일단 캡처해서 선생님께 보내드립니다.

**Comment by sonice21c** [comment]
아 증상을 못 적었군요. ㅎㅎ 

Php 안에서 문구를 바꾸면, 

반영이 30초에서 1분 정도 후에 반영되는 증상입니다. 


그리고 바뀌고 나서의 상황을 캡쳐해서 보내드렸습니다.

팀뷰어나 전화 등 저는 지원받을 수 있다면 정말 큰 도움이 될 것 같습니다.

이게 뭘 하나 테스트 하려고 해도 시간을 많이 소비하게 되어서요 ㅠㅠ

**Comment by yoobato** [comment]
아!!! 웹 페이지 로딩이 1분 걸리는게 아니라, 변경된 내용이 반영되는데 1분이 걸린다는 의미셨군요 ㅠ.
질문을 이제야 이해한 것 같습니다 😭 

이 경우에는, 캐시(Cache) 문제일 확률이 높습니다.
`php.ini` 라는 파일을 찾으셔서, OPCache에 해당하는 부분을 모두 주석처리 하시면 됩니다.
(참고: https://stackoverflow.com/questions/19079089/mamp-time-between-seeing-live-changes/19268769#19268769)

혹은, 한 번 웹브라우저 새로고침하실 때, `cmd + r` 말고, `cmd + shift + r` 해보시겠어요? (브라우저 캐시를 사용하지 않는 새로고침입니다.)

**Comment by sonice21c** [comment]
와.. 드디어 빛을 보기 전인것 같네요 

일단 PHP.ini 파일에서 OPcache 부분을 찾았는데요 

열자마자 모든 글자가 색이 전부 회색으로 되어있는데 이게 주석처리 된 것이 아닌가 싶네요. 

그리고 길이가 매우 긴데요, 

제가 붙여넣기 한 부분이 OPcache 영역일까요? 

주석 처리는 어떻게 하는걸까요? 

제가 알기로는 CMD + / 인걸로 알고 있는데요..

바쁘시고 피곤하실텐데 답장 해주셔서 고맙습니다. ^^


--------
[opcache]
zend_extension=opcache.so
; Determines if Zend OPCache is enabled
opcache.enable=1

; Determines if Zend OPCache is enabled for the CLI version of PHP
opcache.enable_cli=0

; The OPcache shared memory storage size.
opcache.memory_consumption=128

; The amount of memory for interned strings in Mbytes.
opcache.interned_strings_buffer=8

; The maximum number of keys (scripts) in the OPcache hash table.
; Only numbers between 200 and 1000000 are allowed.
opcache.max_accelerated_files=10000

; The maximum percentage of "wasted" memory until a restart is scheduled.
;opcache.max_wasted_percentage=5

; When this directive is enabled, the OPcache appends the current working
; directory to the script key, thus eliminating possible collisions between
; files with the same name (basename). Disabling the directive improves
; performance, but may break existing applications.
;opcache.use_cwd=1

; When disabled, you must reset the OPcache manually or restart the
; webserver for changes to the filesystem to take effect.
;opcache.validate_timestamps=1

; How often (in seconds) to check file timestamps for changes to the shared
; memory storage allocation. ("1" means validate once per second, but only
; once per request. "0" means always validate)
opcache.revalidate_freq=60

; Enables or disables file search in include_path optimization
;opcache.revalidate_path=0

; If disabled, all PHPDoc comments are dropped from the code to reduce the
; size of the optimized code.
;opcache.save_comments=1

; If enabled, a fast shutdown sequence is used for the accelerated code
; Depending on the used Memory Manager this may cause some incompatibilities.
opcache.fast_shutdown=1

; Allow file existence override (file_exists, etc.) performance feature.
;opcache.enable_file_override=0

; A bitmask, where each bit enables or disables the appropriate OPcache
; passes
;opcache.optimization_level=0xffffffff

;opcache.inherited_hack=1
;opcache.dups_fix=0

; The location of the OPcache blacklist file (wildcards allowed).
; Each OPcache blacklist file is a text file that holds the names of files
; that should not be accelerated. The file format is to add each filename
; to a new line. The filename may be a full path or just a file prefix
; (i.e., /var/www/x  blacklists all the files and directories in /var/www
; that start with 'x'). Line starting with a ; are ignored (comments).
;opcache.blacklist_filename=

; Allows exclusion of large files from being cached. By default all files
; are cached.
;opcache.max_file_size=0

; Check the cache checksum each N requests.
; The default value of "0" means that the checks are disabled.
;opcache.consistency_checks=0

; How long to wait (in seconds) for a scheduled restart to begin if the cache
; is not being accessed.
;opcache.force_restart_timeout=180

; OPcache error_log file name. Empty string assumes "stderr".
;opcache.error_log=

; All OPcache errors go to the Web server log.
; By default, only fatal errors (level 0) or errors (level 1) are logged.
; You can also enable warnings (level 2), info messages (level 3) or
; debug messages (level 4).
;opcache.log_verbosity_level=1

; Preferred Shared Memory back-end. Leave empty and let the system decide.
;opcache.preferred_memory_model=

; Protect the shared memory from unexpected writing during script execution.
; Useful for internal debugging only.
;opcache.protect_memory=0

; Allows calling OPcache API functions only from PHP scripts which path is
; started from specified string. The default "" means no restriction
;opcache.restrict_api=

; Mapping base of shared memory segments (for Windows only). All the PHP
; processes have to map shared memory into the same address space. This
; directive allows to manually fix the "Unable to reattach to base address"
; errors.
;opcache.mmap_base=

; Enables and sets the second level cache directory.
; It should improve performance when SHM memory is full, at server restart or
; SHM reset. The default "" disables file based caching.
;opcache.file_cache=

; Enables or disables opcode caching in shared memory.
;opcache.file_cache_only=0

; Enables or disables checksum validation when script loaded from file cache.
;opcache.file_cache_consistency_checks=1

; Implies opcache.file_cache_only=1 for a certain process that failed to
; reattach to the shared memory (for Windows only). Explicitly enabled file
; cache is required.
;opcache.file_cache_fallback=1

; Enables or disables copying of PHP code (text segment) into HUGE PAGES.
; This should improve performance, but requires appropriate OS configuration.
;;opcache.huge_code_pages=1

; Validate cached file permissions.
;opcache.validate_permission=0

; Prevent name collisions in chroot'ed environment.
;opcache.validate_root=0

; If specified, it produces opcode dumps for debugging different stages of
; optimizations.
;opcache.opt_debug_level=0

————여기까지인가요?-------

[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =

[openssl]

**Comment by yoobato** [comment]
@sonice21c 주석처리는 줄의 맨 앞에 # 혹은 ; 를 붙이시면 됩니다.
```
예)
[OPcache]
; zend_extension="/Applications/MAMP/bin/php/php5.5.3/lib/php/extensions/no-debug-non-zts-20121212/opcache.so"
; opcache.memory_consumption=128
; opcache.interned_strings_buffer=8
; opcache.max_accelerated_files=4000
; opcache.revalidate_freq=60
; opcache.fast_shutdown=1
; opcache.enable_cli=1
```

**Comment by sonice21c** [comment]
말씀해주신대로 처리해서 테스트 해봤지만, 동일하네요 

CMD + SHIFT + R 도 그렇고요. 

제가 사용하는 환경의 문제일까요?

Mac OS 10.13.6

MAMP Stack 7.1.25-O

ATOM 1.33.0 x64

**Comment by sonice21c** [comment]
검색어를 달리 해서 검색해봤더니 

저 말고 윈도우 사용하시는 분들 중에서도 이런 문제를 겪으시는 분들이 있으시네요.

http://hack.pe.kr/373 <http://hack.pe.kr/373>

http://blog.naver.com/PostView.nhn?blogId=nostresss12&logNo=221027748454&parentCategoryNo=&categoryNo=24&viewDate=&isShowPopularPosts=false&from=postView

두 분은 해결 되신 것으로 보이는데 저는 아직 해결책을 찾는 중입니다. 

비교하던 중에 사파리와 크롬에 나타나는 글씨체의 차이가 있는 것은 왜 그런건지 궁금하네요..

**Comment by yoobato** [comment]
@sonice21c 

위에 적혀있는 것처럼, opcache.enabled = 0 으로 설정하여도, 오류가 지속되나요?
위의 값을 바꾸신 후에는 서버를 재시작해주셔야 합니다!
(php.ini의 내용을 변경하신 후에는, apache를 재시작해주셔야 합니다. 즉, MAMP를 재시작해주셔야 변경한 설정이 적용됩니다!)

크롬과 사파리의 글씨체에 차이가 나는 경우는, 크롬과 사파리에서 사용하는 기본 폰트가 다르기 때문입니다.
따라서, 보통 웹사이트를 개발할 때, 어느 브라우저에서나 같은 글씨체를 보이게 하고 싶다면, 웹폰트를 사용하곤 합니다 :)

한 번 구글에, `웹폰트` 라고 검색해보시고, 나중에 기회되시면 적용도 해보세요!

**Comment by sonice21c** [comment]
아하, 재부팅해보니 드디어 즉시 적용됩니다 ^^ !

이야... 벽을 만나고 나니 이렇게 당연하게 생각하는 절차들이 감사하고 기쁘네요 ! 

선생님 덕분입니다.

웹 폰트에 대해 알려주셔서 감사합니다. 

다른 분들에게도 이 내용이 도움이 되었으면 좋겠네요 ! ^^

이틀동안 문제해결을 위해 도움주셔서 진심으로 감사합니다. 

편안한 밤 되시길 바라며, 전 다시 코딩모드로 ...^^
