### ISSUE TITLE
nodejs 폴더 및 파일 경로지정 질문!!

### ISSUE THREAD

**Issue by mosball** [codingeverybody/codingyahac#54]
생활코딩 nodejs 강좌중 정적파일을 서비스하는법 부분을 보고있습니다.

app.use(express.static('public')); 
이러한 코드를 작성하는 부분에서 public폴더의 경로는 app.js파일이 위치하는 /(루트) 경로가 기준이 되나요?? (app.js파일이 위치한곳이 /(root) 경로가 맞죠?)
혹시 npm init 으로 설정한 폴더가 위에 코드에서 지정하는 폴더의 경로를 지정하는 기준인가요?? 
저는 저런식으로 경로를 쓰면 오류가뜨고, 상위에 경로인 Back/server_side_javascript/public 이렇게 써줘야 제대로된 결과가 나오네용.. 원래 상대경로라면 해당파일이 위치한 곳이 기준으로 아는데 이전강의인 동기/비동기 프로그래밍 강좌에서 txt파일 읽어올때도 경로지정을 상위폴더인 Back부터 지정을 해야 잘 먹혔습니다. 이고잉님은 app.js가 위치한 파일을 기준으로 경로를 입력하신거같은데 저는 왜 Back이라는 상위폴더부터 경로를 지정해야 되는것일까요..?
 
생각나는대로 막써서 이해가 잘 되실지 모르겠네요.. 감사합니다!

**Comment by haebin** [comment]
상황이 어떤 상황인지 모르겠으나,
모르실때는 공식 문서 참고하세요.
https://nodejs.org/api/path.html

https://stackoverflow.com/questions/3133243/how-do-i-get-the-path-to-the-current-script-with-node-js
