### ISSUE TITLE
코딩야학 2일차. 태그 표현이 안됩니다.

### ISSUE THREAD

**Issue by todrlee87** [codingeverybody/codingyahac#541]
# 해결하고자 하는 문제
태그를 입력해도 웹페이지에서 태그 적용이 아닌 명령어 그대로 보여집니다.

# 코드 혹은 오류
```
Hypertext Markup Language (HTML) is the standard markup language for <strong>creating <u>web</u> pages</strong> and web applications.
```
![image](https://user-images.githubusercontent.com/46530332/50906178-e0f74800-1467-11e9-9b7f-54ea19673c64.png)

# 환경
OS : 맥북에어 부트캠프로 윈도우 사용 중
editor : atom

# 시도해본 방법
크롬, 인터넷익스플로러 모두에서 html 파일을 열어보았으나 태그 그대로 보여집니다.

**Comment by fermat39** [comment]
안녕하세요....
일단.... 파일을 저장하실 때 확장명을 주시기 바랍니다.

파일명.확장명 ex) index.html

웹페이지라면 질문하신 분께서 생각하신 파일명 뒤에 .html을 붙여주시고 
브라우저에서 불러오기 하시기 바랍니다
