### ISSUE TITLE
데이터 과학(데이터분석, 빅데이터)에서 공부해야하는 것 들은 무엇인가요?공부 순서는 어떻게 될까요?(독학)

### ISSUE THREAD

**Issue by SammyLee2** [codingeverybody/codingyahac#542]
안녕하세요!!
아직 대학도 가지 않은 20살이고 데이터 과학을 공부하고있습니다. 
우선 데이터 과학에서 공부해야하는 영역들이 궁금합니다. 대학에서 데이터 사이언스를 배울 수 있으면 좋겠지만 
사정 상 대학에서 데이터 사이언스나 스탯, 컴퓨터 공학을 배우기는 힘든 상황입니다.

코딩을 한 지는 1년정도 열심히 했고, 자바, 안드로이드 , 파이썬, SQL 등 을 다룰 줄 알고 요즘에는
파이썬을 이용한 라이브러리들을 공부하고 있습니다. Pandas, numpy, matplotlib 이런 류.

1. 그런데 확실히 이 정도의 지식으로는 너무 부족하다고 생각이 들어 선형대수학과 통계학을 배우고자하는데 
수학이나 통계학에서 데이터 과학에 활용하고자 한다면 요구되는 수준은 어느정도일까요?
대학교 수준의 통계가 필요할까요? 경제나 통계학부들이 사용하는 수준의 통계가 필요할까요?

2. 수학은 대부분 선형대수학 정도면 괜찮다고들 하시는 것 같은데 이 역시 더 필요할까요?

3. 그리고 알고리즘에 대해서 공부할 필요가 있을까요?

4. 추후 R을 학습할 필요가 있을까요? 

5. 머신러닝이나 딥러닝 같은 것들은 어디서 어떻게 배워야 할까요?
(영어에 능숙하니 해외 강의나 자료도 괜찮습니다. Coursera의 강의들이 몇가지 보이던데 어느정도 배운 후에 도전해야할지 감이 잘 잡히지 않네요. 그리고 2년 3년 지난 한 두 가지 강의밖에 없어서 이 역시 부족하다는 생각이 듭니다. 혹시 잘 설명된 강좌/강의, 책이 있을까요? 영어나 한국어로 번역된 책이면 좋을 것 같습니다.)

6. 마지막으로 실제로 하둡이나 맵리듀스?(맞게 기억하는지 모르겠습니다) 이러한 것들도 학습할 필요가 있을까요?

혹시 더 추천해주실만한 학습해야하는 것들이 있다면 추천해주시면 감사하겠습니다.

7. 그리고 제가 독학으로 배우다보니 무엇을 배워야할지는 대략 감이 잡힌다고 해도 그 순서를 잘 모르겠습니다. 
무엇부터 배우고 무엇으로 확장해 나가며 배움을 지속해야하는지 감을 잡기가 힘드네요. 어떤 순서로 공부하는게 좋을까요? 통계부터 시작하는게 좋을까요?

**Comment by RayleighKim** [comment]
안녕하세요 SammyLee2 님.

  데이터 과학이라는 것이 어느 분야들에 쓰이고 있는지, 어떤 사례가 재미있는지 취향이 먼저 생겼으면 합니다. 데이터 과학은 너무나 포괄적인 단어이기 때문에 더욱 그렇습니다.
  자기가 전문적으로 공부하지 않은 부분도 어느정도는 알아야 겠지만, 취향인 부분 재미있는 부분을 잡아서 주욱 공부하시면서 곁가지들을 보충하는 것이 오래 공부할 수 있는 방법 입니다.

-------------------------------
Q1. 그런데 확실히 이 정도의 지식으로는 너무 부족하다고 생각이 들어 선형대수학과 통계학을 배우고자하는데
수학이나 통계학에서 데이터 과학에 활용하고자 한다면 요구되는 수준은 어느정도일까요?
대학교 수준의 통계가 필요할까요? 경제나 통계학부들이 사용하는 수준의 통계가 필요할까요?

A. 어느정도 수준이느냐에 따라 다르겠습니다. 머신러닝 알고리즘들을 깊게 이해하고 새롭게 모델링하고 튜닝하는 것이 취향이라면, 대학교 학부 수준에서 편성된 교과들 정도로는 살짝 부족할 수도 있습니다.
 시작을 해야한다는 의미에서는 [통계학 개론]정도를 우선 추천합니다만, 테크닉보다 사고방식이 더 중요합니다.
----------------------------------
Q2. 수학은 대부분 선형대수학 정도면 괜찮다고들 하시는 것 같은데 이 역시 더 필요할까요?

A. 위와 답변이 같습니다. 어느정도 수준이느냐에 따라 다릅니다만, 잘 다듬어진 툴보다 코드를 이용할 경우가 더 많아질 것 같다면, 선형대수는 최소조건이 될 것 입니다. 그리고 어느 분야가 취향이신지에 따라 다를겁니다.
 Machine Learning을 공부하는데 '전혀 막힘없이' 공부하고 싶다면,  [미적분학, 선형대수, 수치해석, 통계학개론, 확률론, 베이지안 통계, 일반화 선형 모델, 확률과정, 최적화] 등등을 다 공부하고 오면 정말 편안하게 시작하실 수는 있는데, 보편적으로 추천하는 방법은 아닙니다.
 광고를 최적화 한다고 하면, 비지니스 상황에 맞추어 실험을 설계하고 결과를 해석해서 의사소통할 수 있는 사람이 더욱 중요할 수도 있습니다. 이런 상황에서는 [실험계획법]정도의 내용만 알아도 기술적으로는 충분합니다.
-----------------------------
Q3. 그리고 알고리즘에 대해서 공부할 필요가 있을까요?
A. 네. 혹시, 조금 더 구체적으로 질문 가능하실까요?
-------------------------------
Q4. 추후 R을 학습할 필요가 있을까요?
A. 통계를 공부하신다고 하면 필요할 겁니다. 다른 분들과 제 관점이 다를 수 있는데요,
저는 다음과 같은 관점으로 R을 바라봅니다.  [ R을 잘 다룬다 ] = [ 통계를 잘한다 ]
사실 통계가 본질이고, R은 도구일 뿐이라 필요한 상황은 수시로 생깁니다.
항상 모든 상황을 R로 해결하는 것은 비추천하지만요.
----------------------------------
Q5. 머신러닝이나 딥러닝 같은 것들은 어디서 어떻게 배워야 할까요?
(영어에 능숙하니 해외 강의나 자료도 괜찮습니다. Coursera의 강의들이 몇가지 보이던데 어느정도 배운 후에 도전해야할지 감이 잘 잡히지 않네요. 그리고 2년 3년 지난 한 두 가지 강의밖에 없어서 이 역시 부족하다는 생각이 듭니다. 혹시 잘 설명된 강좌/강의, 책이 있을까요? 영어나 한국어로 번역된 책이면 좋을 것 같습니다.)

A.
개인적으로는 강의나 책을 하나 정해두고 따라가면서, 내용들을 인터넷에서 더 찾아보고 보완하며 공부하는 것을 추천드립니다.

아래 강의의 실습을 Python으로 진행한 자료를 인터넷에 검색하면 바로 나옵니다.
아래 강의를 듣고 Python으로 실습해보시기를 권장합니다.
Andrew ng ML : https://www.coursera.org/learn/machine-learning 

딥러닝은 
개론 - Udacity DL : https://in.udacity.com/course/deep-learning--ud730 (free course 가능)
Andrew ng DL : https://www.coursera.org/specializations/deep-learning
CS231n : http://cs231n.stanford.edu/
CS224n : http://web.stanford.edu/class/cs224n/

책으로는
비숍책 : http://jpub.tistory.com/835
이안책 : http://www.deeplearningbook.org/
 -----------------------------------------------------
Q6. 마지막으로 실제로 하둡이나 맵리듀스?(맞게 기억하는지 모르겠습니다) 이러한 것들도 학습할 필요가 있을까요?

A. 네, 저는 데이터 엔지니어는 아니기 때문에 제 답변은 참고만 하셨으면 좋겠습니다.
데이터 사이즈가 커지고, 개인용 로컬 머신으로는 데이터가 정말 감당이 안되기 시작 할 때, 
자연스럽게 분산처리든, 병렬처리든, 클라우드든 공부하게 됩니다.
그래서, 먼저 공부하는것은 추천드리지 않습니다.
하지만, DB에 익숙하시다면 하둡이나 스파크를 일단 간단하게 공부해보시는 것도 좋을 수 있습니다.
-----------------------------------------------------
Q7. 그리고 제가 독학으로 배우다보니 무엇을 배워야할지는 대략 감이 잡힌다고 해도 그 순서를 잘 모르겠습니다.
무엇부터 배우고 무엇으로 확장해 나가며 배움을 지속해야하는지 감을 잡기가 힘드네요. 어떤 순서로 공부하는게 좋을까요? 통계부터 시작하는게 좋을까요?

A. 뼈대가 될 줄기를 하나 잡고 가시면 좋겠습니다. 가능하면 재미를 느끼는 것이었으면 좋겠습니다.
공부가 어떤 과목 끝나면 다음 과목으로 넘어가고 하는 방식보다,
흥미가 되는 관심 분야를 하나 잡고, 그 분야를 충분히 익히기 위해 필요한 내용들을 검색하고 익혀가시는 것이 좋을 거에요.
단, 질문자께서 생각하시기에 너무 기본이 없는것 같다(?)고 느끼신다면, 통계학 개론 정도는 가볍게 훑어 보고서 시작하셔도 좋겠습니다. 테크닉 보다 사고 방식 위주로요. 이미 코딩을 공부하셨으니, 통계학 개론을 보시면서, 데이터 분석이라는게 도대체 무슨 일을 하는건가 여러 사례들을 찾아 헤매시는 것도 좋을 듯 합니다.

**Comment by SammyLee2** [comment]
정성스러운 답변 정말 감사드려요!! 사실 어디서부터 무엇을 시작할지, 어떻게 학습해야할지 생각할수록 막막했는데 큰 도움이 되었습니다. 정말 감사드립니다!!
