### ISSUE TITLE
WEB1 - website완성 강의 동영상 중 질문

### ISSUE THREAD

**Issue by saseyo078** [codingeverybody/codingyahac#543]
# 해결하고자 하는 문제
atom에서 '3.html'을 duplicate 해서 메인 homepage를 만들었는데, homepage만 파일속성이  ProCore Class라고 뜨면서, 창을 열면 계속 페이지소스만 나오고, 코드값이 제대로 출력되지 않습니다.  원래 다른 파일들 속성은 Chrome HTML Document(.html) 였습니다. 

# 코드 혹은 오류
<!doctype html>
<html>
<head>
  <title>SR-ITS_homepage</title>
  <meta charset="utf-8">
</head>
<body>
  <h1><a href="homepage">WELCOM <br> to <br> SR-ITS</a></h1>
  <ol>
    <li><a href="1.html">연구개요</a></li>
    <li><a href="2.html">연구방법 및 내용</a></li>
    <li><a href="3.html">활용방안 및 기대효과</a></li>
  </ol>
  <h2> 저자: 차은주 </h2>
  <p> 2018.11.30
  </p>
</body>
</html>

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
> 윈도우를 사용합니다. (다른건 뭔지 잘 모르겠어요)

# 시도해본 방법
atom에서 코드를 다시 입력해보기도 하고, 다시 복사해보기도 했는데 안돼요..
일부로 homepage를 구글크롬으로도 열어봤는데, 안되고 explorer도 안됐습니다.

**Comment by znffl** [comment]
안녕하세요.
혹시 homepage 파일의 확장자를 html로 주셨나요? 
homepage.html로 파일을 생성하고 사용하신 코드 그대로 붙여넣기를 한 결과 입니다.

case 1)
```
<!doctype html>
<html>
<head>
  <title>SR-ITS_homepage</title>
  <meta charset="utf-8">
</head>
<body>
  <h1><a href="homepage">WELCOM <br> to <br> SR-ITS</a></h1>
  <ol>
    <li><a href="1.html">연구개요</a></li>
    <li><a href="2.html">연구방법 및 내용</a></li>
    <li><a href="3.html">활용방안 및 기대효과</a></li>
  </ol>
  <h2> 저자: 차은주 </h2>
  <p> 2018.11.30
  </p>
</body>
</html>

```

case 1 결과)
![2](https://user-images.githubusercontent.com/17618779/50956405-eb185580-14fe-11e9-8aed-f9017d52e59a.PNG)

**Comment by saseyo078** [comment]
선생님, 그러면 확장자는 어디서 바꾸나요?

저는 확장자를 바꿨는지도 잘 모르겠습니다..

**Comment by yoobato** [comment]
@saseyo078 

파일 이름 바꾸실 때, 그냥 맨 끝에 .html 을 붙이시면 됩니다!

혹은, 윈도우 설정에 따라 파일 확장자가 숨김처리 되어 안 보이는 경우도 있는데,
이때는 아래 링크 참고하셔서, 확장자를 보이게 한 다음, 바꿔주시면 됩니다!
http://mainia.tistory.com/5104

**Comment by saseyo078** [comment]
아!!!! 
됐어요!!! ㅠㅠ 
감사합니다..  일주일 동안 너무 답답했는데ㅠㅠ 드디어!!!! 
감사합니다아~!!!
