### ISSUE TITLE
https://www.opentutorials.org/course/62/5155 수업의 input.php 가 localhost/input.php 로 했는데 안열립니다

### ISSUE THREAD

**Issue by OHOHAOHO** [codingeverybody/codingyahac#545]
# 해결하고자 하는 문제
php 코드를 창으로 열려고 하는데 안된다고 나옵니다

# 코드 혹은 오류
```
사이트에 연결할 수 없음 localhost에서 연결을 거부했습니다.
Google에서 localhost input 검색
ERR_CONNECTION_REFUSED
```
# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
window10, php 입니다
# 시도해본 방법
edge 와 다른 internet 창에서 열어 보았는데 안됩니다ㅠㅠ

**Comment by o2-basta** [comment]
아마도 80번포트에 대해서 제한이 걸려있어서 열리지 않는거 같아요~

TCP포트는 컴퓨터에서 포트번호별로 관리하는데, 1번에서 1024번까지는 중요하게 다뤄지고 있고, 시스템적으로 허가를 받아야 쓸수 있어요. 
제가 윈도우를 잘 몰라서 리눅스처럼 root권한을 허용하는것은 모르겠어요. 하지만, 1000번대 이상의 포트 (예를들어 3000번 같은) 를 사용하면 에러가 없어지고 웹페이지가 보일거 같아요. 

결론: 포트번호를 3000번 같은걸로 바꿔보세요 ㅎㅎ

**Comment by o2-basta** [comment]
APM같은걸로 운영중이시라면 아파치서버에서 포트를 설정할 수 있어요
웹서버 설정부분을 잘 살펴보시면 있어요 
안될때의 당혹스런느낌은 어쩔수 없지만, 그렇다고 금방작동하거나 망가지거나 하지 않아요. 
그냥 차분하게 다시 살펴보면 될거 같아요. 

그래도 문제라면 스샷이나 개발환경정보를 자세히 알려주세요~

화이팅!!

**Comment by OHOHAOHO** [comment]
죄송해요.. 많이 여쭤봐서...ㅠ
어떤 스샷을 올려야 할지 알려주시면 올리도록 하겠습니다.
감사합니다.

**Comment by OHOHAOHO** [comment]
그리고 database 수업에서
C:\Bitnami\wampstack-7.1.23-0\php\bin
에 있는 디렉토리를 복사해서 
![1](https://user-images.githubusercontent.com/24949174/50969591-5de6f800-1522-11e9-8d80-578e344c3572.PNG)
그림에 나와 있는 대로 directory를 복사해서 bin에닥 설정하려고 하는데, 
이렇게 설정하면은 mysql에 손쉽게 접속할 수 있다고 수업해서 그러셔서
똑같이 했는데... 안되더라구요...
이거는 어떻게 해야 하나요??

**Comment by OHOHAOHO** [comment]
대략적으로 이걸 설정하고 안되가지고
계속해서 mysql을 처음부터 typing 하고 들어가고 있는데 그 후로부터 localhost/로 들어가 지지 않는거 같습니다.

**Comment by o2-basta** [comment]
bitnami를 쓰고 계시군요.

아파치서버에서 포트를 바꿀수 있어요. 
httpd.conf파일안에 포트 설정이 있어요 

https://docs.bitnami.com/aws/apps/processmakerenterprise/administration/configure-port/ 이게 영어로 되어있긴 한데, 구글링하면 더 좋은 정보를 찾을 수 있을거에요. 
중요한거는 낙담하지 않고 다시 시도해보는겁니다!!

**Comment by OHOHAOHO** [comment]
음... 원인을 찾게 되었고 수정을 하였습니다ㅎㅎ
http://yuilovestomato.tistory.com/2
이걸 보시면, 여기에 나와 있어요
단, 제가 아직도 이고잉 선생님의 가르침에 따라 MySQL을 cmd에서 간편하게 들어갈 순 없을거 같습니다.
왜냐하면 거기에는 path에 ;을 입력하고 나서 directory 를 입력하라고 수업에서 그러셨는데,
또 따라하니깐 안되더라구요...
혹시 o2-basta 선생님께서 이 부분을 어떻게 수정하면 되는지 좀 알려주셨으면 합니다.
여기까지는 됐는데 더 이상 제가 할 수 있는 부분이 아닌거 같아요
아직 server를 구동해 보진 않았지만,
기존에 Manage Servers에서는 stop이 걸렸었는데, 드디어 Running으로 바뀌었네요...
일단 이것 저것 알아가게 되는거 같아서 좋네요..ㅎㅎ
감사합니다.
만약에 서버가 안된다면 또 리플로 달아야 할거 같습니다.ㅎㅎ
혹시 o2-basta 선생님의 이메일을 여쭤봐도 될까요?ㅎㅎ

**Comment by OHOHAOHO** [comment]
아~ 또 하나 더 알려드릴거 있습니다.
하두 해서 안되가지고 다시 reinstall 했거든요...
그래도 안되더라구요
즉, 서버가 한 번 문제가 생기면, 특히 port에 문제가 생기면,
다시 설치해도 안되는건 마찬가지더라구요
그리고 재설치 하다가 처음으로 이런 그림을 발견 했습니다.
![default](https://user-images.githubusercontent.com/24949174/50978609-23885580-1538-11e9-840c-0fd92cfd7a82.PNG)
이 사진의 뜻은.. 앞서 질문으로 남긴 port와 연관된 창이구요..
저 문제를 해결하니 이것도 해결되고 서버도 해결되고 다시 파일도 제대로 열리게 되네요
아무튼 선생님의 노고로 잘 되었습니다.
진심으로 감사합니다ㅎㅎㅎ
