### ISSUE TITLE
html 기본속성 부여의미 질문

### ISSUE THREAD

**Issue by hpik3049** [codingeverybody/codingyahac#547]
안녕하십니까 요즘 코딩야학으로 코딩에 대해 흥미를 느끼고 있는 학도입니다.
다름아니라 코딩중에 질문이 생겨서 포스팅 올립니다.

수업중에 <p style="margin-top:40px;">

이런 css 기술을 잠깐 배운적이 있는데 예를 들어

<style> h1 {color: #F18FE6 } </style> 처럼 h1처럼 전체에 속성을 부여하는 방법과 위의

태그 속에 따로 style을 등호와 따옴표로 정의 하는 방법을 적용할 때 차이가 뭔가요? 보통 다른 태그들은 

예를들어 <li><a> 같은 태그들은 연속적으로 쓰면 웹 화면 내에서 중복적으로 적용이되기는 하는데

<style>은 연속적으로 정의가 되지 않는건가요?

결론적으로 태그 속에서 띄어쓰기로 다시 새로운 문법을 정의하고 등호와 따옴표 (=" ")로 정의하는 경우는 그 언어 자체로써 암기해야 하는건가요?
이 부분이 너무 헷갈립니다.

**Comment by yoobato** [comment]
```
<style>
    h1 {
        color: #F18FE6;
    }
</style>
```
이렇게 하시게 되면, HTML 파일 내의 모든 h1 태그에 이 스타일이 적용됩니다.

```
<h1 style="color: #F18FE6;">Hello World</h1>
```
이렇게 하시게 되면, 이 h1 태그에만 스타일이 적용됩니다.

즉, 적용되는 범위가 다르지요~!

개발을 하시다 보면, 특정 h1 태그들은 글씨 색을 빨강색으로 하고, 다른 h1 태그들은 파랑색으로 하고 싶은 경우가 생길 때가 있는데, 이때는 참 애매하지요. h1 태그 전체에 색상을 입힐 수도 없고, 그렇다고 모든 h1 태그에다가 style=""을 쓰기도 귀찮고 (관리도 안되고)... 이럴 때는, CSS의 class 기능을 이용하면 됩니다 😄
(CSS Class: https://www.w3schools.com/cssref/sel_class.asp)
