### ISSUE TITLE
html의 속성 부여 의미 질문

### ISSUE THREAD

**Issue by hpik3049** [codingeverybody/codingyahac#548]
안녕하십니까 요즘 코딩야학으로 코딩에 대해 흥미를 느끼고 있는 학도입니다.
다름아니라 코딩중에 질문이 생겨서 포스팅 올립니다.

수업중에 p style="margin-top:40px;"  ##꺽새 표시 입력하면 자꾸 적용이 되는 것 같아서 그냥 올립니다.

이런 css 기술을 잠깐 배운적이 있는데 

예를 들어 

<style> h1 {color: #F18FE6 } </style> 처럼 h1처럼 전체에 속성을 부여하는 방법과 위의
태그 속에 따로 style을 등호와 따옴표로 정의 하는 방법을 적용할 때 차이가 뭔가요? 보통 다른 태그들은 

예를들어 <li 엘아이><a 에이>    ##자꾸 포스팅에 코딩이 적용되서 글자를 입력했습니다

태그를 연속적으로 쓰면 중복적으로 적용이되기는 하는데
<style>은 연속적으로 정의가 되지 않는건가요?

결론적으로 태그 속에서 띄어쓰기로 다시 새로운 문법을 정의하고 등호와 따옴표 (=" ")로 정의하는 경우는 그 언어 자체로써 암기해야 하는건가요?
이 부분이 너무 헷갈립니다.

**Comment by o2-basta** [comment]
스타일태그를 쓰는경우와 태그안에 스타일을 정의하는것의 차이에 대한 질문이군요 ㅎㅎ

스타일은 기본적으로 태그와 클래스, 아이디에대해서 적용할 수 있어요. 우리가 보통 접하는 사이트들에대한 코드를 살펴보면 많은 태그들에 클래스와 아이디가 붙어있지요. 그런 클래스, 아이디 태그에 대해서 스타일을 한꺼번에 정의한다고 할때는 스타일 태그를 씁니다. 

그런데, 일부 태그들에 대해서는 그냥 스타일을 적용하기도 합니다. 혹은 동적으로 (자바스크립등을 사용해서) 스타일을 적용할때는 태그안에 바로 스타일을 입히기도 합니다. 

각각의 장단점에 대해서는 구글링해보시면 알 수 있을거 같아요 ㅎㅎㅎ

**Comment by yoobato** [comment]
헛... 질문을 새로 올리셨군요 ㅠ. 이전꺼에 답변을 달아놓았습니다.

https://github.com/codingeverybody/codingyahac/issues/547#issuecomment-453087283 이거 참고해주세요!

**Comment by hpik3049** [comment]
친절한 답변 모두 감사합니다!!!
