### ISSUE TITLE
CSS 미디어쿼리 list 줄바꿈이 안됩니다( white-space:nowrap; )

### ISSUE THREAD

**Issue by kmu0219** [codingeverybody/codingyahac#549]
# 해결하고자 하는 문제

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```    
<style>
    h1 {
      border-bottom:1px solid gray;
      padding: 10px;
      margin: 0px;
       }
    h2 {
       list-style-type: none;
       }
    ul {
      width:100px;
      border-right:1px gray solid;
      padding:10px;
      margin:0px;
       }
    a {
       text-decoration:none;
      }
    #grid {
            display :grid;
            grid-template-columns: 150px 1fr;
          }
    @media(max-width:700px) {
            ul {
              border-right:none;
            }
            #grid {
              display:block;
            }
            .list {
              white-space:nowrap;
              color:red;
            }

    }
    </style>

<ul>
     <h2>
       <div class ="list">
        <li><a href="1.html">코딩</a></li>
        <li><a href="2.html">회화공부</a></li>
        <li><a href="3.html">운동</a></li>
        <li><a href="4.html">교정</a></li>
       </div>
     </h2>
    </ul>

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Window10 HTML 

# 시도해본 방법
CSS 미디어쿼리 시행시 List를 한줄로 나오게 하고싶은데 h2,ul,li로 style을 변형해봐도 줄바꿈이 시행이 안됩니다 ㅠㅠㅠ 어떻게 해야하나요

**Comment by yoobato** [comment]
@media 쿼리 안에다가,
```
ul li {
  display: inline;
}
```
를 추가하시면 됩니다!

아래 링크 참고해보세요!
https://codepen.io/yoobato/pen/REexbP

**Comment by kmu0219** [comment]
ㅎㅎㅎㅎㅎㅎㅎ됩니다 아하 block 을 inline으로 변환해야 하는군여 감사합니다!!!!
