### ISSUE TITLE
기본적인 홈페이지 샘플들을 얻고 싶습니다.

### ISSUE THREAD

**Issue by SangYunLeee** [codingeverybody/codingyahac#55]
다른 사람들은 어떻게 짯을지 배우고 싶은데 혹시 샘플들이 많은 좋은 사이트가 있을까요?

제 노력하에선 잘 찾아지지 않네요 ㅠㅠ.

**Comment by progh2** [comment]
음~ 어려운 질문이네요. ^^;
개인 홈페이지나 개인 사이트 검색해도 홍보 사이트가 주로 나오니..
 
부트스트랩 같은 사이트에 가시면 갤러리라고 해서 해당 기술로 구축된 사이트 예가
나옵니다. 이러한 것들을 참고해보면 어떨까 하네요.
showcase 를 찾아보시면 어떨까 합니다. 
아래는 예시입니다. ^^; 

https://startbootstrap.com/template-categories/full-websites/
https://startbootstrap.com/template-categories/all/
https://getmdl.io/showcase/index.html
https://www.xpressengine.com/showcase

**Comment by SangYunLeee** [comment]
감사합니다!
