### ISSUE TITLE
AWS 서비스 구축 및 운용을 위한 공부방향

### ISSUE THREAD

**Issue by kmu0219** [codingeverybody/codingyahac#552]
HTML로 처음 WEB 공부를 시작하게된 학생입니다.

제가 지원하고 싶고 정말로 취업하고 싶은 회사가 있습니다.

그 회사의 직무에 대한 요구사항은 아래와 같습니다.

-OS/Network/DB 대한 관련 지식
-리눅스 기반의 OS 사용경험 / 직접 WEB/WAS/DB 서버 구축 또는 운용해본 경험필요
-AWS등 가상화서버를 활용한 고객 대상의 서비스를 구축 및 운용해본 경험
-APM/DB tunning tool 등의 open-source를 활용해본 경험

이를 위해 현재 아래와 같은 공부 방법을 잡았습니다 (생활 코딩 강의 기본)
<기초 공부>
WEB : HTML - CSS - Javascript 
DATABASE : DATABASE1 - DATABASE2
서버관련 생활코딩 강의
그후 Python 공부 진행

이렇게 기초 공부를 진행해도 되는지와
이후 공부를 어떻게 진행해야 하는지 상담부탁드립니다!
감사합니다!

**Comment by egoing** [comment]
잘 잡으신 것 같고요. 참고로 제 aws 수업도 있습니다. 
https://opentutorials.org/module/3814

seomal.org에 있는 지식 지도상에서 위의 회사가 요구하는 수업들을 표시해봤습니다. 

![default](https://user-images.githubusercontent.com/303822/51023280-e66ca380-15c9-11e9-8b21-0af09337e4f4.jpg)
