### ISSUE TITLE
페이지가 열리면 자동으로 오디오를 재생하고 싶은데 에러가 발생합니다.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#554]
# 해결하고자 하는 문제
안녕하세요?
페이지가 열리면 자동으로 특정 오디오를 재생하고 싶어서 아래와 같이 코드를 만들었는데 
'Uncaught (in promise) DOMException'이라는 에러가 발생합니다.
에러를 검색해보니 Chrome의 에러라는 말도 보이는데 정확히 어떤 에러인가요?
그리고 해결 방법은 무엇인지 궁금합니다.

# 코드 혹은 오류
```
     window.onload = function() {
    currentSound = new Audio('audio/ass/a.mp3');
    currentSound.play();
  }
 
```

# 환경
Javascript

**Comment by yoobato** [comment]
Chrome에서 Autoplay를 막은 것 같아요.
(참고: https://developers.google.com/web/updates/2016/03/play-returns-promise)

Safari 브라우저에서 실행하니까 정상적으로 동작합니다 😄

**Comment by yoobato** [comment]
해결책이라기 보다는 이를 우회하는 방법들이 있는 것 같은데요.

아래 링크보니까, `iframe`을 이용한 방법이 있는 것 같습니다.
https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome

**Comment by kammaii** [comment]
> 해결책이라기 보다는 이를 우회하는 방법들이 있는 것 같은데요.
> 
> 아래 링크보니까, `iframe`을 이용한 방법이 있는 것 같습니다.
> https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome

답변 감사합니다! :)
