### ISSUE TITLE
안드로이드 플랫폼에서 서버와 통신하기

### ISSUE THREAD

**Issue by five-senses** [codingeverybody/codingyahac#555]
# 해결하고자 하는 문제
지금까지 PC 기반 으로만 개발하다!
익숙하지 않은 안드로이드 플랫폼에서 임베디드 검사장비를 만들려 합니다!
문제는 검사 결과를 각각의 원격지에서 리눅스 서버로 보내고 받아야 하는데
통신을 할 수 있는 최적의 방법을 고민하고 있습니다!

더불어 검사자료는 개인정보를 포함하여 누출되면 안 되는 자료인지라
보안에도 신경을 써야 하는데....

# 환경
안드로이드스튜디오 

# 시도해본 방법
찾아보니 서버/클라이언트 소켓으로 개발한다고 하는데 이것이 최선인지
확신이 안 가서 질문드립니다!

**Comment by o2-basta** [comment]
안드로이드 단말에서 검사한 내용을 원격으로 서버에 보낸다면 우선적으로 지원해야 하는부분은 암호화입니다. 
서버와의 데이터 교환은 패킷이라는 단위로 주고 받을 수 있을거 같은데, 여기서 데이터가 중간에 제3자에게 보여지더라도 어떤내용인지 모르도록 감추어서 보내는게 중요할거 같아요. 
일단 안드로이드안에서 검사결과를 저장하고, 이후에 서버로 보내는게 좋을거 같아요. 안드로이드에도 내부적으로 데이터베이스가 있으니, 거기 저장하면 될거 같고, 암호화가 필요하다면 데이터를 암호화 해서 저장해도 좋을거 같아요.
그러고 나서 서버로 암호화해서 보내면 좋을거 같아요. 보통 HTML을 보내는 HTTP 프로토콜 기반의로 restful하게 보내면 좋을거 같고, 암호화해서 HTTPS형식으로 데이터 전송 API를 마련하고 수집하는 정보를 보내면 될거 같아요. ㅎㅎㅎ

**Comment by five-senses** [comment]
감사합니다!
역시 전송전 암호화 한 후 보내는 것이 중요 하다는 것을 느꼈습니다!
1. 암호화 한다.
2. 안드로이드 내부적인 데이터베이스 이용 저장 한다.
3. HTTPS 형식으로 데이터 전송 한다.
