### ISSUE TITLE
숫자를 입력하면 단을 9단까지 출력해주는 걸 만들고 있다가 짬뽕이 되서 질문합니다

### ISSUE THREAD

**Issue by jacksora** [codingeverybody/codingyahac#557]
# 해결하고자 하는 문제
하다보니 막 섞여서 머가 문젠지도 모르겟네요...
html과 js 섞어서 만드는 건 성공했습니다
오직 js가지고 만드는 것도 좋다고 생각해서
그 코드들 좀만 손보면 되지 않을까 해서 막 찾아서 해보니 저러케 되었네요..

입력창에서 숫자를 입력받아 그 숫자의 9단까지를 알려주는 프로그램니다.
잘부탁드립니다

# 코드 혹은 오류
```
var 바디 = document.body;

var 단어 = document.createElement('div');
단어.textContent = '구구단입니다.출력할 단을 입력하세요';
바디.append(단어);
var 입력창 = document.createElement('input');
바디.append(입력창);
var 버튼 = document.createElement('button');
버튼.textContent = '숫자입력!';
바디.append(버튼);
document.querySelector('버튼').id = btn;

document.getElementById("btn").onclick = function() {
  var 출력단= 입력창.value;
  document.write(출력단,'단 구구단','<br>')
  for(var i = 1; i<=9; i++){
  document.write(출력단,'*',i,'=',i*출력단,'<br>')
       }
   };
```

# 환경

# 시도해본 방법
구글로 찾아봐도 구구단 테이블 만드는 것만 나오네요..

**Comment by studroid** [comment]
전반적으로 굉장히 잘 작성하셨네요!

다만 querySelector를 쓰시는 부분에서 하나 오류가 있었네요 :)

#으로 id를 선택하거나 .으로 클래스를 선택하는 등, querySelector의 사용에 대해선 이 링크에서 예시를 확인해보시고,

동작하는 코드는 다음과 같습니다 :)


var 바디 = document.body;

var 단어 = document.createElement('div');
단어.textContent = '구구단입니다.출력할 단을 입력하세요';
바디.append(단어);
var 입력창 = document.createElement('input');
바디.append(입력창);
var 버튼 = document.createElement('button');
버튼.textContent = '숫자입력!';
바디.append(버튼);
// document.querySelector('버튼').id = "button"; - 주석 처리

버튼.onclick = function() {
  var 출력단= 입력창.value;
  document.write(출력단,'단 구구단','<br>')
  for(var i = 1; i<=9; i++){
	  document.write(출력단,'*',i,'=',i*출력단,'<br>');
  }
};

**Comment by jacksora** [comment]
위에코드를 아톰으로 붙여넣기 헤서 실행해보니 작동이 안되길래 저가 약간 고쳤습니다..
여전히 안되네요..
var 출력단 쪽이 문제인거 같습니다...

var 바디 = document.body;

var 단어 = document.createElement('div');
단어.textContent = '구구단입니다.출력할 단을 입력하세요';
바디.append(단어);
var 입력창 = document.createElement('input');
바디.append(입력창);
var 버튼 = document.createElement('button');
버튼.textContent = '숫자입력!';
바디.append(버튼);


버튼.onclick = function() {
var 출력단= 입력창.value;
document.write(출력단,'단 구구단','<br>') //br이 없으면 한줄로 출력됨..
for(var i = 1; i<=9; i++){
document.write(출력단,'*',i,'=',i*출력단,'<br>');//마찬가지 br 없애면 한줄로 출력
}
};


실행결과:
단 구구단
*1=0
*2=0
*3=0
*4=0
*5=0
*6=0
*7=0
*8=0
*9=0

원하는 결과 :예 2입력시

2단 구구단
2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18

**Comment by yoobato** [comment]
@jacksora 

올려주신 코드 기반으로 제가 수정을 조금 해보았는데, 한 번 비교해보시면 좋을 것 같아요.

```html
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript">
		window.onload = function () {
			var 바디 = document.body;

			var 단어 = document.createElement('div');
			단어.textContent = '구구단입니다.출력할 단을 입력하세요';
			바디.append(단어);

			var 입력창 = document.createElement('input');
			바디.append(입력창);

			var 버튼 = document.createElement('button');
			버튼.textContent = '숫자입력!';
			바디.append(버튼);

			버튼.onclick = function() {
	  			var 출력단 = 입력창.value;
	  			document.write(출력단, '단 구구단', '<br>')

	  			for(var i = 1; i <= 9; i++) {
	  				document.write(출력단, '*', i, '=', i * 출력단, '<br>')
	       		        }
	   		}
		}
   </script>
</head>
<body>
</body>
</html>
```

**Comment by studroid** [comment]
> 위에코드를 아톰으로 붙여넣기 헤서 실행해보니 작동이 안되길래 저가 약간 고쳤습니다..
> 여전히 안되네요..
> var 출력단 쪽이 문제인거 같습니다...
> 
> var 바디 = document.body;
> 
> var 단어 = document.createElement('div');
> 단어.textContent = '구구단입니다.출력할 단을 입력하세요';
> 바디.append(단어);
> var 입력창 = document.createElement('input');
> 바디.append(입력창);
> var 버튼 = document.createElement('button');
> 버튼.textContent = '숫자입력!';
> 바디.append(버튼);
> 
> 버튼.onclick = function() {
> var 출력단= 입력창.value;
> document.write(출력단,'단 구구단','
> ') //br이 없으면 한줄로 출력됨..
> for(var i = 1; i<=9; i++){
> document.write(출력단,'_',i,'=',i_출력단,'
> ');//마찬가지 br 없애면 한줄로 출력
> }
> };
> 
> 실행결과:
> 단 구구단
> *1=0
> *2=0
> *3=0
> *4=0
> *5=0
> *6=0
> *7=0
> *8=0
> *9=0
> 
> 원하는 결과 :예 2입력시
> 
> 2단 구구단
> 2_1=2 2_2=4
> 2_3=6 2_4=8
> 2_5=10 2_6=12
> 2_7=14 2_8=16
> 2*9=18

아 제 코드를 Insert code 형태로 안 했더니, 답글 란에서 뭔가 잘못 해석이 된 것 같습니다 ^^;
코드 영역으로 다시 업데이트하니 제대로 보이네요. 위에 yoobato님이 전체를 잘 정리해주셨으니 확인해보시면 되겠습니다!
