### ISSUE TITLE
window 운영체제 에서 Mac Os 사용 가능한지?

### ISSUE THREAD

**Issue by Felixes** [codingeverybody/codingyahac#56]
제목 그대로 입니다.
window 운영체제 에서 Mac Os 운영체제 사용 가능한가요?

**Comment by egoing** [comment]
가상머신, 혹은 클라우드라는 기술을 이용하면 가능합니다.

**Comment by progh2** [comment]
"윈도우에서 맥 설치" 라고 구글 검색 해보세요.. 
그런데 왜 설치하려는건가요?

**Comment by davidkwak** [comment]
Windows에서 Mac을 사용하고싶으시다는 말씀이 APPLE 제품이 아닌 일반 PC에서 Mac을 쓰고싶다는 의미시라면 "해킨토시"를 검색해서 따라하시면 될것 같습니다.

만일, Windows가 host로 깔려 있는 상태에서 그 안에 가상 머신등을 이용해서 Mac을 사용하고 싶으신 거라면 "mac os VM" 이라고 검색하시면 관련 정보를 찾으실 수 있습니다.

 참고자료 :
https://lifehacker.com/5938332/how-to-run-mac-os-x-on-any-windows-pc-using-virtualbox
https://www.pcsteps.com/2157-mac-os-x-virtual-machine-vmware-player/ 

다만, 맥 OS에 대한 저작권 등이 문제될 수 있으니 이점 염두에 두셔아 합니다.

**Comment by azaraks2** [comment]
맥이 아닌 곳에 OSX를 설치하는건, 어지간해서는 제 성능 안나와서 결국 맥을 사게 됩니다.
설치방법도 쉽지 않구요.

**Comment by ch-choi** [comment]
가능하지만 귀찮고 불편합니다.
간단하게 사용하시기에는 VMWare나 VirtualBox 같은 가상머신(Virtual Machine)으로 윈도우 상에서도 가능합니다.
그러나 그래픽이나 하드웨어 리소스라 많이 필요한 경우 위에 davidkwak님이 이야기하신 해킨토시 혹은 커스텀 맥으로 검색하시면 여러 사이트가 나옵니다.
따라 하시기 전에 개념과 용어를 잘 보셔야 중간에 막혀도 질문을 할 수 있습니다.
커널패닉에 빠지면 원인을 찾아서 해결하기 쉽지 않습니다.
해킨은 하드웨어 관련된 kext를 일일이 설치해야 하는데 다른 분들이 설치 성공한 하드웨어로 컴퓨터를 맞추거나 노트북을 사서 설치하면 조금 편합니다.
저도 해킨 쓰다가 리얼 맥으로 넘어 왔는데 매번 업데이트 때마다 새로 설치하고 kext를 잡고 최적화하는데 삽질을 많이 해야 합니다.

**Comment by Felixes** [comment]
os를 사용해보고싶은 단순한 호기심떄문에

2018년 8월 9일 (목) 오후 5:36, sookbun <notifications@github.com>님이 작성:
