### ISSUE TITLE
Node.js 모듈 기초 질문 있습니다.

### ISSUE THREAD

**Issue by joyoon729** [codingeverybody/codingyahac#563]
# 해결하고자 하는 문제
egoing 님의 **_Node.js-44.Node.js 모듈의형식_** 강의를 들고 질문합니다!
https://www.youtube.com/watch?time_continue=327&v=ti7n2ZXO2XE

이 강의에서 'module' 은 객체를 정리정돈 할 수 있는 더 큰 정리정돈 도구라고 표현하셨는데요.
강의에서는 mpart.js 에서 객체 'M' 을 정의하시고 `module.exports = M;` 을 이용해 다른 js 파일에서 불러올 수 있도록 하신거 같습니다.

여기서 떠오른 제 의문은, module 으로 객체를 정리정돈 한다기보다 그저 다른 파일로 빼놓는거에 불과하다고 생각이 들었습니다. 객체는 여러가지 변수와 함수들을 한데 모아 정리하는데에 비해 모듈은 객체 하나를 빼놓기만 한 것 아닌가요?
만약 10억개의 객체들을 정리하기 위해선 10억개의 모듈이 필요한것 아닌가요?..

**혹시 모듈안에 여러가지 객체들을 포함시켜놓고 사용할 수 있는 방법이 있는지 궁금합니다.**

아래 코드는 모듈안에 여러가지 객체들을 넣어보고 시도해봤는데 실패한 코드입니다..

# 코드 혹은 오류
main.js
```js
var a = require('./module.js');

a.f();
// a.sample2.f(); --> 이 부분을 제가 나름대로 해본것인데 오류가 뜨고 마네요..
```

module.js
```js
var sample = {
	f: function(){console.log("module sample1")}
}

var sample2 = {
	f: function(){console.log("module sample2")}
}

module.exports = sample;
module.exports = sample2;
```

# 환경
MacOS, js&nodejs / nodejs v11.6.0

**Comment by egoing** [comment]
좋은 질문입니다!

슬쩍 찾아봤는데요. 아래와 같은 게시글이 있네요. 
https://stackoverflow.com/a/20123716
하나의 모듈에는 여러개의 객체가 위치할수도 있답니다. 
추가로 궁금하신 것이 있으면 말씀해주세요.
