### ISSUE TITLE
이론공부할수있는 책과 프로그램 추천부탁드립니다!

### ISSUE THREAD

**Issue by joymean** [codingeverybody/codingyahac#564]
안녕하세요! 비전공자늦깍이로 배우고 있는 사람입니다! 저는 나중에 빅데이터나 웹개발자로 일하고싶어서 지금 코딩을 배우고있는데요.
 이론이 너무 부족하다보니까 책으로도 공부를 하고싶은데, 어떤프로그램부터 어떤책을 봐야할지 찾는중인데 너무 어렵네요ㅠㅠ비전공자가 이론공부해야하는 커리큘럼이나 책을 추천해주실수 있을까요?! 프로그램도 추천해주시면 감사하겠습니당😊
바쁘시더라도 답변부탁드려용🙇🏻‍♀️

**Comment by smartbos** [comment]
특정 책을 콕 찝어드리지 못하는 점 우선 양해 부탁드립니다.

소프트웨어 개발 관련 서적은 계속 업데이트되는 소프트웨어의 특성상 최신 서적이 가장 유용합니다. (버전이 안맞으면 설치하는 단계부터 난관에 봉착할 수도 있어요!) 관심있는 분야의 최신 서적들 위주로 찾아보시길 권해드립니다.
 
커리큘럼은 [WEBn](https://opentutorials.org/course/3083)을 참고해보세요. 

고급 개발자가 되기 위해서는 최신성에 영향을 받지 않는, 시간이 흘러도 소프트웨어를 작성하는데 도움이 되는 영감을 주는 책을 봐야합니다. 하지만 시작하는 단계에서는 여기까지는 신경쓰지 않으시는 것이 오히려 개발자로 성장하는데 도움이 됩니다. 더 잘하는건 일단 할 줄 알게 된 후에 나중에 고민하셔도 됩니다. (단, 더 잘하고자 하는 마음은 계속 가지고 계셔야해요 ^^)

**Comment by joymean** [comment]
커리큘럼까지 찾아주시다니ㅠㅠ좋은 답변 감사합니다!
