### ISSUE TITLE
진로관련인진 모르겠는데.., 회원가입한 멤버들이 동영상업로드 할 수 있는 웹의 제작에 대해

### ISSUE THREAD

**Issue by DoctorSSun** [codingeverybody/codingyahac#565]
고민중입니다. 저는 개발자가 아니고 직장생활 하면서 퇴근 후 밤에 생활코딩을 보고 코딩야학을 들으면서 혼자 공부하고 있습니다. 이런 공부를 하는 이유는 저는 어떤 웹을 만들어야하는 긴급하고 해결해야할 목적이 있기 때문입니다. 도와주세요.

웹이 필요한 기능은,
1. 회원가입기능
2. 회원들이 동영상을 업로드 할 수 있는 기능 (1단계로 약 100명의 회원이 10분짜리 영상 2개씩을 올린다고 가정. 이후 회원과 영상이 늘어가면 2단계로 하드와 트레픽 증가에 대응 고려)
3. 너무 고화질영상은 용량이 크므로 업로드 시 자동으로 줄일 수 있는 기능
4. 각 영상에 대한 좋아요 기능
5. 각 영상에 대한 댓글 기능
6. 영상 제목과 간략한 설명 
7. 조회수 표시
8. 부적절한 영상 신고
9. PC와 모바일 버전 모두 필요
10. 서버구축은 어떻게? 호스팅?//         ... 아주 아주 단순화된 미니 유튜브 같습니다.. 

제가 이 웹을 만들 수 있을까요? 이 개발을 해결하기 위해서 어떤 공부 혹은 툴이 필요할까요? 이 웹을 우선 간단하고 매우 저렴하게 개발 의뢰 할 수 있는 곳이 있을까요? 그럼 그 개발된 코딩을 보면서 다시 혼자 공부해 보고 싶습니다. 

웹빌더 (Wix 등)도 검토해 보았는데 게시판 템플릿의 경우 동영상업로드는 모두 유튭 비메오 등의 링크로 올리게 되어 있어 난관에 봉착했습니다. 일반 블로그 템플릿은 직접 영상업로드는 되지만 회원들은 영상을 올릴 수가 없는 문제가 있었습니다. 유튭에 회원들이 일단 영상 올리고 비공개영상으로 설정하고 링크만 가져올 수 있음 유튭을 일종의 영상업로드서버로 이용할 수 있겠는데 현재 유튭은 그 기능을 허용하지 않고 있는 듯 합니다. 온갖 연구를 다 해봤는데 결국 웹을 별도 구축하는 방법 뿐인 것 같아요ㅠ

**Comment by smartbos** [comment]
말씀하신 기능은 아직 개발을 모르는 사람이라도 시간을 충분히 들이면 만들 수 있습니다. 

말씀하신 것을 만들기 위해서는 웹 개발 지식이 두루 필요합니다.
1. HTML, CSS로 화면을 보여줄 수 있어야 하고
2. 서버프로그래밍 언어(PHP, Java, Python, Ruby 등)와 데이터베이스(MySQL 등)를 이용해 기능을 구현하실 수 있어야하고
3. 만드신 기능을 다른 사람들이 이용할 수 있게 서버를 운용하실 수 있어야합니다. 이를 위해 리눅스를 조금 아셔야 합니다.

풀어써놔서 공부할게 너무 많다 생각하실 수도 있는데, 웹 개발을 공부한다 하면 다 거치는 기본 과정이니 너무 겁내지 않으셨으면 합니다. 생활코딩에 웹 개발 관련 강좌가 잘 준비되어 있으니, 차근차근 학습하다보면 전반적으로 어떻게 돌아가는지, 어떤 부분을 더 공부해야하는지 알 수 있게 될 겁니다.

**Comment by egoing** [comment]
동영상 플랫폼을 직접 운영하는 것은 정말 어려운 일이랍니다. 비용도 많이 들고요. 
생활코딩 같은 경우 youtube로 업로드를 하고 있기 때문에 비용을 절감 할 수 있었습니다. 
또 비메오(https://vimeo.com/ko/business) 와 같은 서비스를 이용하면 작은 금액으로 운영하시는 서비스에서만 재생되는 동영상 서비스를 운영할 수 있었던 것으로 기억하고 있습니다. 

그리고 기술 관련된 창업에서 창업자가 기술을 전혀 모르면 정말 많은 어려움이 있습니다. 공부를 하시다보면 자연스럽게 스스로 개발자가 될 수도 있고, 개발자에게 업무를 요청하는 기획자가 될 수도 있습니다. 어떤 포지션에 서게 되더라도 기술 공부는 꾸준히 하시면 좋을 것 같습니다. 하다보면 고민도 보다 구체화 될 것이고요.

**Comment by DoctorSSun** [comment]
두 분 선생님 조언 너무 감사합니다! 퇴근하고 힘겹고 졸린 눈으로 열심히 해보려고는 하는데 선생님들의 조언이 없다면 전 못할 것 같습니다!
