### ISSUE TITLE
무료 폰트에 글자를 추가할 수 있나요?

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#567]
# 해결하고자 하는 문제
안녕하세요?
마음에 드는 무료 폰트를 찾아서 프로젝트에 적용하고 있는데 몇몇 글자가 폰트 안에 없는 것 같습니다.
예를 들어 '얶'이라는 글자를 쓰고 싶은데 해당 폰트로는 '어ㄲ' 이렇게 표현이 됩니다.
혹시 제가 다운 받은 폰트에 글자를 추가할 수도 있나요?
추가가 안 된다면 다른 아이디어는 없는지 궁금합니다.

# 환경
HTML, CSS javascript

**Comment by kammaii** [comment]
> 이 문제에 대해서 자신은 없습니다만, 제가 아는 범위에서는 쉽지는 않을 것 같네요. (안되는 것은 없겠습니다만 ^^)
> 
> 저도 더 좋은 방법이 있는지 궁금합니다. 더 좋은 방법을 아시는 분 같이 기다려봅니다~

역시 쉽지 않은 문제였군요 ㅜ.ㅜ
사실 이 폰트도 100% 마음에 드는 것은 아니라서
지금 문득 '폰트를 내가 만들어버릴까?'라는 생각이 드는데... 이 또한 쉽지 않겠지요?^^;
다른 폰트도 찾아보면서 저도 계속 방법을 연구해 봐야겠습니다.
답글 감사합니다!

**Comment by fermat39** [comment]
폰트에도 라이선스(license)가 있습니다.
해당 폰트에 대한 라이선스를 한번 확인해보시기 바랍니다.
라이선스들이 매우 다양하고 가능한 것이들 서로 다릅니다.

잘 모르겠으면, 직접 해당 폰트 제작자에게 문의하실 수도 있습니다.
폰트도 굉장히 민감한 부분이라 잘 확인해보시기 바랍니다.
