### ISSUE TITLE
오디오를 연속으로 재생하는 코드를 만들고 있습니다.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#568]
# 해결하고자 하는 문제

안녕하세요?
버튼을 클릭하면 10개의 오디오가 연속으로 재생되는 코드를 만들었는데 2가지 문제점이 발생하였습니다.

1. 오디오를 재생하는 버튼을 클릭하면 'btn_play()'가 실행되는데, 오디오가 재생되는 중에 버튼을 한 번 더 클릭하면 오디오가 다시 처음부터 재생되게 하고 싶습니다. 현재 코드로 이 기능이 작동되야 할 것 같은데 클릭하면 다음 오디오로 넘어가 버립니다.

2. 10개의 오디오의 재생이 모두 끝나고나면 
'Uncaught TypeError: Cannot read property 'addEventListener' of undefined' 라는 에러가 뜨면서
더 이상 버튼이 작동하지 않습니다.
왜 이런 건가요?

# 코드 혹은 오류
```
  let audioArray = [];
  let j=-1;

  function btn_play() {
    if(currentSound) {
      currentSound.pause();
      currentSound.currentTime = 0;
    }
    for(let i=0; i<10; i++) {
      audioArray[i] = new Audio('audio/reading/' + audioTitle[i] + '.mp3');
    }
    audioPlay();
  }

  function audioPlay() {
    j++;
    if(j == audioArray.length) return;
    currentSound = audioArray[j];
    currentSound.addEventListener('ended', audioPlay);
    currentSound.play();
  }
```

# 환경
javascript

**Comment by o2-basta** [comment]
아마도 전체내용을 다 같이 살펴보면 더 자세히 알 수 있지만, 일단 보이는 코드로 확인해보면, 
1. 다음 오디오로 넘어가는 이유는 audioPlay() 안에서 현재플레이하는 트랙의 번호를 일단 한개뒤로 보내고 나서 실행되는거 같아요. 그래서 현재 트랙을 다시 실행하려고 해도 다음트랙으로 이동해서 그트랙의 처음으로 가는거 같아요. 

2. addEventListener of undefined 에러는 아마도 준비된 10개의 파일이름과 관련있을거 같아요.  for문에서 준비하는 audio는 0번에서 9번까지인데, 실제파일은 1번에서 10번까지이거나해서 번호가 다르게 매치되는건 아닌지 다시한번 확인해 보시면 좋을거 같아요. 그래서 실제적으로 파일이 없는 객체가 만들어져서 (그래서 undefined 객체가 되는거 같아요 ) 이벤트리스너를 달 수 없는것이 아닌지 모르겠어요. 

제가 적어놓은 내용이 문제해결에 도움이 되었는지 모르겠어요. 
확인하시고, 더 자세한 내용은 더 자세한 코드를 통해서 알아볼 수 있을거 같아요 ㅎㅎㅎ

**Comment by kammaii** [comment]
> 아마도 전체내용을 다 같이 살펴보면 더 자세히 알 수 있지만, 일단 보이는 코드로 확인해보면,
> 
> 1. 다음 오디오로 넘어가는 이유는 audioPlay() 안에서 현재플레이하는 트랙의 번호를 일단 한개뒤로 보내고 나서 실행되는거 같아요. 그래서 현재 트랙을 다시 실행하려고 해도 다음트랙으로 이동해서 그트랙의 처음으로 가는거 같아요.
> 2. addEventListener of undefined 에러는 아마도 준비된 10개의 파일이름과 관련있을거 같아요.  for문에서 준비하는 audio는 0번에서 9번까지인데, 실제파일은 1번에서 10번까지이거나해서 번호가 다르게 매치되는건 아닌지 다시한번 확인해 보시면 좋을거 같아요. 그래서 실제적으로 파일이 없는 객체가 만들어져서 (그래서 undefined 객체가 되는거 같아요 ) 이벤트리스너를 달 수 없는것이 아닌지 모르겠어요.
> 
> 제가 적어놓은 내용이 문제해결에 도움이 되었는지 모르겠어요.
> 확인하시고, 더 자세한 내용은 더 자세한 코드를 통해서 알아볼 수 있을거 같아요 ㅎㅎㅎ

답변 감사합니다! 
1번 내용 참고해서 수정했더니 2번까지 해결이 되었어요! :)
그런데 다른 문제가 또 생긴 것 같아요 ㅋㅋㅋ
좀 더 연구해보고 안 되면 다시 질문 드릴게요~
