### ISSUE TITLE
html 세로줄 긋는법 알려주세요!

### ISSUE THREAD

**Issue by ghanuul** [codingeverybody/codingyahac#57]
코딩 html 세로줄을 긋는법을 모르겠어요. 알려주세요!!!!!!!!

**Comment by wlals31** [comment]
세로줄을 만드는 방법에는 여러 가지가 있는데 두 가지를 소개해드리자면

1. 빈 div 를 만들어서 border-left를 설정하는 방법 (border-left 가 곧 긋고자 하는 세로줄이 됩니다.)
https://www.w3schools.com/howto/howto_css_vertical_line.asp

2. div 자체를 하나의 선 처럼 보이게 하는 법
(top과 bottom을 0으로, width를 선의 굵기로 설정)
http://jsfiddle.net/rlemon/RJ5ax/1/

가 있습니다. 

다른 방법이 궁금하시면 google에 "how to draw vertical line in html" 라고 검색하시면
좀 더 다양한 답변을 얻으실 수 있을거예요. :)

**Comment by ghanuul** [comment]
감사합니다.
