### ISSUE TITLE
파이썬 코딩 문의드립니다.

### ISSUE THREAD

**Issue by hoannara** [codingeverybody/codingyahac#570]
파이썬 코딩 초보인데 수학문제 퀴즈 프로그램을 하나 만들려고 합니다.
 
1. 문제와 답을 한쌍으로 여러 문제를 만들고, 
2. 문제들 중에서 랜덤하게 뽑아서 문제를 프린트하고,
3. 입력된 답이 정답이면 점수를 더하고 싶은데..
랜덤으로 뽑힌 문제와 그에 맞는 정답을 입력된 답과 비교하고 싶은데 이를 어떻게 코딩해야 되는지 문의드립니다.
  
초보적인 질문이어서 죄송합니다. 아는게 없어서 이런 기초적인 것도 코딩하기가 어렵습니다.

감사합니다.

**Comment by RayleighKim** [comment]
생각하신 바를, 억지로라도 어느정도 코딩을 해보시고, 코드를 올려주시기를 부탁드립니다.
코드에 당장 구현하다가 막힌 부분과, 질문자의 의도를 같이 올려주시면 구체적으로 답변을 해주실 분들이 많아질거에요.

일단은 우선, (문제, 답) 쌍을 4~5개 정도 간단하게만 만드시고.
샘플링 방법도 찾아서 고민해보시고, if문으로 입력된 답과 실제 답 비교도 구현해보시기를 권장드립니다.

리스트, 샘플링, input, 제어문 의 내용을 이해하고 계시다면 시작하시는데 무리 없을거에요.

**Comment by o2-basta** [comment]
일단 수학문제라서 수식을 어떻게 표현하실지 궁금하긴하네요. 
문제가 모두 문자열로 가능하다고 할때에는 문제와 보기, 그리고 정답을 딕셔너리(해시)로 구성해서 문제들을 배열에 넣어서 준비 하면 될거 같아요. 
그러고 나서 랜덤함수를 사용해서 선택하면 될거 같아요. 
 import random
random.choice(list_of_quiz) 
이런식으로 구성하면 문제를 랜덤으로 낼 수 있는데, 여기서 문제의 답과 사용자의 답이 일치하면 점수를 올려주게 하면 될거 같아요. 

여기서 주의할점은 random.choice() 를 사용하면 문제가 중복출제 될수 있어서 
리스트를 섞어주고 나서 pop을 사용해야 할 수 있을거 같아요. 

만약 웹페이지에 표현한다면 수식이 포함된 질문은 아마도 그림이나 latex으로 처리될 수 도 있을거 같아요

**Comment by hoannara** [comment]
네, 답변 감사합니다. 
답변 주신대로 코딩해 보도록 하겠습니다.
많은 도움이 되었습니다.
