### ISSUE TITLE
WEB2 Python 기술적 질문 이고잉님께 질문드립니다~!

### ISSUE THREAD

**Issue by betelgeuse06** [codingeverybody/codingyahac#571]
# 해결하고자 하는 문제

WEB2 PYTHON 에서의 오류

> # 해결하고자 하는 문제
> WEB2 PYTHON 에서의 오류
> 아 그리고 Error log 에도 log가 않찍히는데 오류가 떠요

> # 코드 혹은 오류
> 여기에 코드를 적어주세요.
> ![image](https://user-images.githubusercontent.com/32902105/51106653-bc1c1f80-182f-11e9-998d-b98a8286968b.png)
> 
> ![image](https://user-images.githubusercontent.com/32902105/51106634-ad356d00-182f-11e9-8c94-9ca29659643e.png)
> 
> # 환경
> 사용중인 운영체제: Windows 10
> 
> # 시도해본 방법
> 다운로드를 또하기도 했고, 예제를 보면서 똑같이 다시 따라해보기 했고, 철자 하나하나 보면서 보기도 했고 했습니다

**Comment by egoing** [comment]
안녕하세요. 지금 주신 것만으로는 조금 어렵네요. 
오류 메시지와 같은 부분을 좀 알려주실 수 있을까요? 
(저도 오래전에 만든 수업이고, 주력 기술은 아니라서 자신은 없지만 다른 고수 분들이 도움을 드릴 수 있거든요)

**Comment by betelgeuse06** [comment]
> # 해결하고자 하는 문제
> WEB2 PYTHON 에서의 오류
> 
> # 코드 혹은 오류
> 여기에 코드를 적어주세요.
> ![image](https://user-images.githubusercontent.com/32902105/51106653-bc1c1f80-182f-11e9-998d-b98a8286968b.png)
> 
> ![image](https://user-images.githubusercontent.com/32902105/51106634-ad356d00-182f-11e9-8c94-9ca29659643e.png)
> 
> # 환경
> 사용중인 운영체제: Windows 10
> 
> # 시도해본 방법
> 다운로드를 또하기도 했고, 정말 방법 이란 방법을 거의 하 해본듯 합니다

**Comment by yoobato** [comment]
@betelgeuse06 

올리신 내용을 그대로 다시 올려주신 것 같아요! 확인 부탁드릴게요 😄
