### ISSUE TITLE
특정 array의 글자 크기가 달라집니다.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#578]
# 해결하고자 하는 문제
안녕하세요?
버튼을 클릭하면 array에 있는 메시지 내용이 차례로 전환되는 코드를 만들었습니다.
그런데 특정 array들에서 font-size가 달라집니다.
css에 font-size도 입력하였는데 변하는 이유를 모르겠습니다.
혹시 첨부 코드로 확인이 어려우실수도 있을 듯 하여 아래에 전체 코드 링크 주소 첨부했습니다.
https://github.com/kammaii/akorean/blob/master/r1/std_con.html

# 코드 혹은 오류
```
<body>
      <a href="" id="btn" ontouchstart="btn()"><img src="img/right.svg"></a>
      <div id="content_message">I'm message.</div>
</body>

<style>
#content_message {
  border-top: 1px solid;
  text-align: center;
  font-size: 2.5em;
  padding: 50px;
  margin-bottom: 10px;
  color: #8FB299;
  overflow: scroll;
}
</style>

<script>
    let countClick = 0;
    let currentMsg = document.getElementById('content_message')

    let teachingMsg = [
    "Message 1",
    "Message 2",
    ...
    "Message 10" ];

    function btn() {
        countClick = countClick + 1;
        currentMsg.innerHTML = teachingMsg[countClick];
    }
</script>
```

# 환경
html, css, javascript

**Comment by yoobato** [comment]
올려주신 Repository 받아서 확인해봤는데, 별 다른 문제는 발견하지 못하였습니다.

제 생각에, 모든 글자(자음)의 크기가 다르기 때문에, 글자 크기가 달라진다고 말씀하신 것 같은데,
이는 폰트에 따라 다릅니다.

폰트는 고정폭 폰트와 가변폭 폰트로 나뉘는데, 글자 그대로 고정폭은 모든 글자가 같은 너비(width)를 가지는 것을
의미하고, 가변폭 폰트는 글자마다 너비가 달라질 수 있다는 것을 의미합니다.

사용하고 계신 폰트(godomaum)는 가변폭 폰트인 것 같습니다. 따라서, 글자 별로 너비가 달라 폰트 크기가 다르게 보일 수 있습니다.

아래 링크 참고해보세요!
http://www.font.co.kr/customer/faq_view.asp?idx=25

아! 참고로, 코딩 폰트라고 일컫는 '나눔고딕코딩' 같은 폰트는 고정폭 폰트입니다 😄
고정폭 폰트가 필요하신 경우, `monospace font` 혹은 `fixed-width font` 를 찾아보시면 됩니다!

**Comment by kammaii** [comment]
> 올려주신 Repository 받아서 확인해봤는데, 별 다른 문제는 발견하지 못하였습니다.
> 
> 제 생각에, 모든 글자(자음)의 크기가 다르기 때문에, 글자 크기가 달라진다고 말씀하신 것 같은데,
> 이는 폰트에 따라 다릅니다.
> 
> 폰트는 고정폭 폰트와 가변폭 폰트로 나뉘는데, 글자 그대로 고정폭은 모든 글자가 같은 너비(width)를 가지는 것을
> 의미하고, 가변폭 폰트는 글자마다 너비가 달라질 수 있다는 것을 의미합니다.
> 
> 사용하고 계신 폰트(godomaum)는 가변폭 폰트인 것 같습니다. 따라서, 글자 별로 너비가 달라 폰트 크기가 다르게 보일 수 있습니다.
> 
> 아래 링크 참고해보세요!
> http://www.font.co.kr/customer/faq_view.asp?idx=25
> 
> 아! 참고로, 코딩 폰트라고 일컫는 '나눔고딕코딩' 같은 폰트는 고정폭 폰트입니다 😄
> 고정폭 폰트가 필요하신 경우, `monospace font` 혹은 `fixed-width font` 를 찾아보시면 됩니다!

폭 뿐만 아니라 높이까지 아예 글자의 크기가 달라집니다. ㅠㅠ
크기가 변하는 부분은 한글부분(font-family: godomaum)이 아니고 영어부분(id="content_message)이며 이 부분에는 font-family를 지정하지 않았습니다.
혹시 font-size의 단위를 em으로 해서 그런 것 같아서 px로 바꿔서 해봤는데 똑같습니다.
Chrome에서 뿐만 아니라 서버를 작동하여 휴대폰으로 실행시켰을 때도 사이즈가 변합니다.
글자 크기가 변하는 부분은 항상 일정한데 예를 들면,
teachingMsg[0], [1], [4], [9],... 이런 식입니다.

**Comment by kammaii** [comment]
> ![qwer](https://user-images.githubusercontent.com/1592319/51170839-c2270480-18f2-11e9-9797-6924060c4556.png)
> 
> 이 부분을 말씀하시는게 맞나요?
> 코드를 확인해보니, 영어는 없고 한글밖에 없는 것 같아서요! (자음의 이름)
> 
> 그리고, 제가 봤을 때는 크기가 변하지 않는 것 같아요.
> 크기가 다른 경우를 스크린샷으로 찍어서 각각(2장 이상) 올려주시면 좋을 것 같습니다!

아!! 정말 죄송합니다!! 링크를 잘못 올렸어요 ㅠㅠ
https://github.com/kammaii/akorean/blob/master/r1/std_lastcon.html
![1](https://user-images.githubusercontent.com/43202563/51174093-92bfca00-18e9-11e9-9f20-315b1b4e749e.png)
![2](https://user-images.githubusercontent.com/43202563/51174097-94898d80-18e9-11e9-9a89-b469dc9fd527.png)

**Comment by yoobato** [comment]
문제의 원인을 찾았습니다 😄 

몇몇 웹 브라우저에서는 Viewport의 크기에 따라, 자동으로 폰트의 크기를 조절합니다.
이를 방지하기 위해서는, `text-size-adjust` 속성을 `none`으로 설정해야합니다.

```css
html {
  text-size-adjust: none;
}
```
`html`의 스타일 속성에, 위 속성을 추가해주시면 모두 균일한 폰트 사이즈로 나오게 될 것입니다!

**Comment by kammaii** [comment]
> 문제의 원인을 찾았습니다 😄
> 
> 몇몇 웹 브라우저에서는 Viewport의 크기에 따라, 자동으로 폰트의 크기를 조절합니다.
> 이를 방지하기 위해서는, `text-size-adjust` 속성을 `none`으로 설정해야합니다.
> 
> ```css
> html {
>   text-size-adjust: none;
> }
> ```
> 
> `html`의 스타일 속성에, 위 속성을 추가해주시면 모두 균일한 폰트 사이즈로 나오게 될 것입니다!
> 
> 참고: https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

와!!! 이렇게 쉽게 해결되는 문제였군요!!
에러가 뜨는 문제도 아니라서 갈피도 못잡고 있었는데 정말 감사합니다!! :)
