### ISSUE TITLE
앞으로 공부할 것에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by Evan-JH-Kim** [codingeverybody/codingyahac#58]
안녕하세요, 저는 web1 강좌를 3일만에 수강 완료했고,
추가적인 공부를 한 뒤 웹페이지를 만들어 보려 합니다.
Framework의 경우 제가 Python에 가장 익숙해서 Django를 이용해 보려 생각 중인데요.
궁금한 점이 몇 가지 있어 질문 드립니다.

1. 공부 순서는 HTML - CSS  - Javascript - Django 순으로 가면 될까요?
2. 생활코딩 WEBn 강좌는 어느 정도 수준까지 다룬다고 생각하면 될까요?
웹 페이지를 만드려면 강좌와 함께 관련 도서를 구매해서 공부하는 것이 좋을까요?
3. 미래에 데이터 분석 관련 직업을 생각하고 있는데(현재는 학부생입니다),
이 경우에도 Web 관련 지식은 필수적이라고 할 수 있을까요?

**Comment by davidkwak** [comment]
안녕하세요.  질문하신 내용들은 정해진 답이 있다기보다는 개인 취향차이라서.. 일단 제 의견을 말씀드리면

1. 아주 기본적인 문법이나 틀은 하나씩  훑어볼 수는 있겠습니다만 "순서를 정해서 하나씩 정복해나가자!" 보다는 구현하고자 하는 기능에 따라 그때그때 찾아가면서 알아가는걸 좋아합니다.  안그러면 HTML 만 하다가 질리실 수도 .... 

2. 이것도 취향입니다만 저는 책보다는 동영상 강의나 웹 포스팅 같이 바로바로 search 해서 접할 수 있는 매체를 좋아하는 편입니다. 온라인에서 볼 수 없는 자료는 책으로도 없으니까요 

3. 이건 명확히 YES라고 말씀드릴 수 있습니다.  데이터를 얻어오는 출처도 WEB 인 경우가 많고,  분석한 데이터를 보여주는 view도 web으로 visualization 하는 경우가 많습니다. 

별것 아닌 답변입니다만 도움이 되셨길 바랍니다. 

참고로, 1개 이상의 질문은 쪼개서 하나씩 해주시는게 답변 달기도 편하고, 나중에 다른 분들이 참고하시기에도 좋을것 같습니다.
