### ISSUE TITLE
web1 - 웹호스팅 -  오류

### ISSUE THREAD

**Issue by saseyo078** [codingeverybody/codingyahac#581]
# 해결하고자 하는 문제
강의대로 따라서했는데, 다른 학우분들처럼 404라고 오류가 뜨지는 않는데, 내용이 아무것도 안나옵니다..

# 코드 혹은 오류
코드 오류는 아닌 것 같습니다. 왜냐하면, github로 올리기 전에는 제대로 나왔습니다.

그리고 github에 올릴 때는 영상대로 똑같이 따라했고, 오류 났던 분들 조언대로, 
1) readme를 소문자로 바꿔보고, 
2) HTML 대문자로 바꿔보고,
3) 1.html.HTML 뒤에 HTML도 붙여 봤는데, 안됩니다..

사이트에서는 그냥 Repository name 만 덩그러니 떠있습니다.

뭐가 문제인지 모르겠습니다.. 도와주세요..ㅠㅠ

**Comment by yoobato** [comment]
@saseyo078 님 개인 페이지 들어가서, Repository 살펴보았는데요.
가장 최근에 만드신 SR-ITSSS Repository 기준으로 설명해드리겠습니다.

Github의 Pages 기능(호스팅 기능)을 사용하실 때는,

```
https://[Github username].github.io/[Repository name]/[Filename]
```
의 포맷으로, URL이 구성되게 됩니다.

따라서, `https://saseyo078.github.io/SR-ITSSS/homepage.HTML` 이 주소로 접속하시면 잘 보이실거에요!

**Comment by saseyo078** [comment]
아!!! 네!! 이제 잘되네요!! 감사합니다 ㅠㅠ 
아는게 하나도 없는 상태에서 시작해서 그런지 부족한게 너무 많습니다..
감사합니다~ :D
