### ISSUE TITLE
github에서 사이트 수정후 재배포

### ISSUE THREAD

**Issue by Whynitz** [codingeverybody/codingyahac#585]
github 에 제가 수업 들으며 만든 웹사이트를 올렸고, 수업에서 알려준 대로 settings 에서 master branch로 변경하여 save 해서 사이트 주소를 얻었습니다! 이후 github에 올린 코드를 수정했고 사이트를 재배포하려는데 이때는 어떤 방법을 사용해야 하나요?

**Comment by yoobato** [comment]
Github의 master branch에 파일을 정상적으로 업로드하셨다면, 따로 배포하실 필요 없이 자동으로 반영되어 있을 것입니다 😄 

[web1 repository](https://github.com/Whynitz/web1)를 가장 최근에 수정하신 것 같은데,
https://whynitz.github.io/web1/index.html 이 링크에 들어가셔서, 수정사항이 반영되어 있는지 확인해보시면 될 것 같습니다!
