### ISSUE TITLE
eventListener를 취소하고 싶어요.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#588]
# 해결하고자 하는 문제
안녕하세요? studroid 님께서 해결해주신 코드인데 다른 문제가 또 생겨서 다시 질문드립니다.
코드 내용을 다시 설명드리면, 
총 10개의 문장이 있고 버튼을 누르면 1번 문장부터 순서대로 오디오가 재생되며 
재생 중인 문장에는 배경색이 나타납니다.
그리고 여기에 각 문장을 터치할 수 있는 기능을 추가했는데,
터치를 하면 해당 문장의 오디오를 바로 재생할 수 있고,
다시 버튼을 누르면 1번 문장부터 차례로 재생이 됩니다.

문제가 무엇인지는 파악이 되었습니다.
버튼을 눌러서 오디오가 재생이 되면 audioPlay() 함수 안의 
currentSound.addEventListener('ended', audioPlay); 가 차례로 각 문장에 추가가 됩니다.
이 때, 이미 오디오가 재생이 되었던 문장에 터치를 하게 되면
touchSentence() 함수가 작동해서 해당 문장의 오디오가 재생이 됩니다.
터치한 문장의 오디오가 재생이 끝나면 동작을 멈춰야 하는데
해당 문장에는 이미 EventListener가 입력되어 있기 때문에 
자동으로 audioPlay() 함수를 불러와서 기존에 재생되던 부분을 이어서 진행하게 됩니다.

터치를 실행했을 때 기존에 입력된 EventListener를 초기화 하려면 어떻게 해야 할까요?

# 코드 혹은 오류
```
<body>
 <button type="button" class="button" onclick="btn_play()">Play</button>
</body>

<script>
    let j=-1;

    function btn_play() {
      if(currentSound) {
      currentSound.pause();
      currentSound.currentTime = 0;
      document.getElementById("sentence"+j).style.backgroundColor = "";
      j = -1;
      audioPlay();
    } else {
      audioPlay();
    }
  }

  function audioPlay() {
    j++;
    if(j == audioArray.length) return;
    currentSound = audioArray[j];

    background();
    currentSound.addEventListener('ended', audioPlay);
    currentSound.play();
  }

  function background() {
    for(let i=0; i<10; i++) {
         document.getElementById("sentence"+i).style.backgroundColor = "";
    }
    document.getElementById("sentence"+j).style.backgroundColor = "#e6e9ef";
  }

  function touchSentence(ev) {
    ev.preventDefault();
    let lastTouchId = ev.target.id;
    let lastTouchNo = lastTouchId.match(/\d/);
    if(currentSound) {
      currentSound.pause();
      currentSound.currentTime = 0;
    }
    currentSound = audioArray[lastTouchNo[0]];
    currentSound.play();
    background(lastTouchNo[0]);
    currentSound = null;
    console.log(j);
    j = -1;
  }

</script> 
```

# 환경
javascript

# 시도해본 방법
touchSentence() 함수에 for 문을 이용하여 현재의 j값까지 audioArray[j]에
addEventListener('ended', function(ev) {
    ev.preventDefault();
}
를 입력해 봤는데 에러만 발생했습니다.

**Comment by yoobato** [comment]
touchSentence() 함수에서,

```javascript
if (currentSound) {
  currentSound.pause();
  currentSound.currentTime = 0;
}
```
이 부분에,

```javascript
current.removeEventListener('ended', audioPlay);
```
를 넣으셔서, 추가한 EventListener를 제거하시면 됩니다.

RemoveEventListener와 관련하여 더 자세한 내용은 아래 링크를 참고하시면 됩니다.
https://www.w3schools.com/jsref/met_element_removeeventlistener.asp
https://developer.mozilla.org/ko/docs/Web/API/EventTarget/removeEventListener
