### ISSUE TITLE
안드로이드 : volley 라이브러리 사용법

### ISSUE THREAD

**Issue by beanbug** [codingeverybody/codingyahac#59]
# 문제
웹 서버로(php) 라이브러리 volley를 사용해 id 값을 string 형식으로 보내고 싶습니다. 

JsonObjectRequest는 url을 매개변수로 넘겨주고난 다음 칸에 보내고 싶은 jsonobject를 적어주면 되던데

StringRequest로 Requset를 만들어서 보낼때는 제가 보내고 싶은 값을 어떻게 넘겨주는지 궁금합니다.

그리고 웹 서버의 php에서 $userID = $_POST["userID"]; 로 id값을 post로 넘겨준 값을 받을때는 string 형식이나 json 형식에 상관없이 다 받을 수 있나요?

**Comment by progh2** [comment]
음.. 저는 주로 레트로핏 라이브러리를 사용해서 써서 volley는 안써보았지만 
volly 프로젝트의 기본 설명에 나오는 내용이 물어보신 내용인 것 같습니다. 

https://developer.android.com/training/volley/simple.html

보내실 때 get요청을 하신다면 url 뒤에 쿼리스트링으로 값을 추가로 넣어서 요청하시면 될듯합니다. 
~board.php?id=a1234  식으로 요청하면 $_GET['id']로 서버쪽에서 받아올 수 있습니다. 
(retrofit 라이브러리에서는 get, post 등등 좀 더 세세하게 지정이 가능하니 참고하세요.)

 velloy에 대한 강좌 및 튜터리얼을 찾아보시는 것도 도움이 될 것 같습니다.
검색해보니 다음 같은 강좌가 나오네요.
https://www.androidtutorialpoint.com/networking/android-volley-tutorial/

두번째 질문은 분리해서 다시 올려주시면 감사하겠습니다. ^^;

**Comment by beanbug** [comment]
Leave a comment
