### ISSUE TITLE
web2 반응형 디자인 관련 질문

### ISSUE THREAD

**Issue by Whynitz** [codingeverybody/codingyahac#590]
# 해결하고자 하는 문제

안녕하세요! web2 css 반응형 디자인 공부를 따라가면서 @media(max-width:800px) 코드를 이용해 화면 넓이에 따라 반응하는 웹페이지 구현을 공부했습니다! 다만 저는 이게 스마트폰에도 적용될 거라고 생각하고, 스마트폰은 화면 넓이가 적어도 800px보다는 작을 거라고 생각해서 스마트폰에서는 작은 화면용 사이트가 나올줄 알았는데 작은화면용 사이트 안나오고 그냥 원래 사이트가 나와요ㅠㅠ 왜 이런 걸까요?

**Comment by yoobato** [comment]
지금 하고 계신게, https://github.com/Whynitz/web2 이거지요?
혹시, 여기에 소스 다 업로드해주시거나

아니면, html 이랑 css 모두 여기에 올려주시겠어요?
(올려주신 것만으로는 판단하기가 어렵네요 ㅠ)

**Comment by Whynitz** [comment]
네. 배포된 사이트 링크는 https://whynitz.github.io/web2/ 이거고요!
컴퓨터로 확인했을 때는 화면크기가 800px 이하가 되면 디자인이 변형되는데, 스마트폰으로 보면 작은 화면용 디자인으로 안나와서 왜그런지 궁금합니다.

**Comment by yoobato** [comment]
Viewport 설정을 해주셔야 하는데, 해주지 않으셔서 그렇습니다 😄 

`<head></head>` 사이에,
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
를 넣어주시면 됩니다.

뷰포트(viewport)와 관련된 설명은 아래 링크를 참고해보시면 좋을 것 같습니다.
https://developers.google.com/web/fundamentals/design-and-ux/responsive/?hl=ko
