### ISSUE TITLE
프로젝트 진행 방향에 관련된 질문

### ISSUE THREAD

**Issue by yeah2055** [codingeverybody/codingyahac#592]
안녕하세요 이번에 처음 코딩을 배우기 시작해서 제가 만들고싶은 서비스가 있는데, 어느쪽으로 공부를 해야 가능한지 궁금해 질문을 드립니다.
구글의 이미지 검색처럼 이미지 추적에 관해 어느쪽으로 공부를해야되는지 궁금해 이렇게 질문을 드립니다.
또, 이미지 추적에 관련된 서비스를 만들고 싶은데, 이미지 추적은 이미지자체를 추적을 하는것인지 아님 이미지 안에 있는 코드로 추적이 가능한지 궁금합니다.

**Comment by yoobato** [comment]
말씀해주신 부분은 정확히는 `Computer vision`에 해당하는 영역이고, 구글이나 네이버에 `영상처리`라고 검색하시면, 원하시는 자료들을 많이 얻으실 수 있으실 것입니다.

기본적인 원리는 아래와 같습니다.

이미지의 기본 단위는 픽셀(px)입니다. 픽셀은 하나의 점이라고 생각하시면 좋을 것 같습니다.
예를 들어, 모니터의 해상도가 1920 * 1080px 이라면, 총 1920 * 1080 개의 점을 표현할 수 있는 것이지요.

따라서, 100 * 100px의 이미지가 있다고 할 때, 이것은 10,000개의 점으로 이루어진 이미지입니다.
각각의 점은, 색을 표현할 수 있는데, 색을 표현하는 방법은 다양하지만, 일단은 쉽게 검은색과 흰색으로만 이루어진
흑백의 이미지라고 가정한다면, 점은 0(흰색) 혹은 1(검은색)을 나타내게 됩니다. 이를 데이터의 단위로는 비트(bit)라고 합니다. 즉, 1개의 점은 1bit의 데이터(검은색 혹은 흰색)를 표현할 수 있는 것이지요. 만약, 흑백이 아니라고 한다면, 하나의 점이 표현하는 데이터의 크기가 커집니다.

다시, 흑백으로 돌아와서... 각각의 점이 0, 1을 표현한다고 했고, 10,000개의 점이 있으니 총 10,000개의 검은색/흰색 정보가 있는 것입니다. 이것을 2차원 배열로 나타낼 수 있을 것이고, 이를 이용해서 이미지 검색 혹은 처리를 하는 것입니다.

제가 말씀드린 것은 정말 기초적인 내용이고, 이 세상에는 수 많은 영상처리 알고리즘이 있습니다. 위에서 설명해드렸듯이, 검은색과 흰색으로만 표현해도 100 * 100px의 이미지가 10,000개의 정보를 가진다는 것을 알 수 있지요? 근데, 이게 흑백이 아니라 RGB의 색상을 가진다면, 처리해야할 데이터의 크기가 더 커질 것이고, 우리가 흔히 사용하는 1920 * 1080px의 이미지라면 데이터의 크기가 어마어마하겠지요? 따라서, 이미지를 단순화하고, 표본을 뽑고, 패턴 매칭을 이용하는 등의 작업을 거치게 되는데, 이것은 각 알고리즘마다 구현이 다릅니다.

저도 영상처리 쪽을 잘 알지는 못하지만, 흥미로운 분야라고 생각합니다. 예전에, 이미지 위에 워터마크를 새겨주는 프로그램을 만든적이 있는데, 이미지가 어두운 이미지면 흰색 워터마크를, 밝은 이미지면 검은색 워터마크를 추가하는 프로그램이었습니다. 무지하여 무식하게, 모든 픽셀의 색상 정보를 이중 for 문을 돌면서, 평균낸 다음 '어둡다', '밝다'로 나타냈었는데, 저는 이런 것이 영상처리 공부의 시작이라고 생각합니다 😄 

화이팅하세요!

**Comment by yeah2055** [comment]
안녕하세요 592번 질문을 한 사람입니다. 질문이 삭제되었다고 해서 왜 삭제가 되었는지 이유가 궁금하여 메일드립니다.늦은 밤 메일드려 죄송합니다. 좋은 밤되시길
-------- 원본 이메일 --------발신: Daeyeol Ryu <notifications@github.com> 날짜: 19/1/18  오전 10:49  (GMT+09:00) 받은 사람: codingeverybody/codingyahac <codingyahac@noreply.github.com> 참조: yeah2055 <yeah2055@gmail.com>, Author <author@noreply.github.com> 제목: Re: [codingeverybody/codingyahac] 프로젝트 진행 방향에 관련된 질문 (#592) 
Closed #592.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codingeverybody/codingyahac","title":"codingeverybody/codingyahac","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/codingeverybody/codingyahac"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #592."}],"action":{"name":"View Issue","url":"https://github.com/codingeverybody/codingyahac/issues/592#event-2081838385"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/codingeverybody/codingyahac/issues/592#event-2081838385",
"url": "https://github.com/codingeverybody/codingyahac/issues/592#event-2081838385",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yoobato** [comment]
@yeah2055 

질문이 삭제된 것이 아니라, 해당 질문에 대한 답이 끝났기 때문에, 제가 이 질문을 닫은(Closed) 것입니다.

Github 에서는 어떤 문제가 있을 때, 질문자님께서 질문을 올리신 것처럼 Issue라는 것을 올리게 되어 있는데,
Issue는 Open / Closed 두 개의 상태로 나뉩니다. Open은 말그대로, 답변 혹은 처리를 기다리고 있는 상태이고,
Closed는 답변 혹은 처리가 끝난 상태입니다.
만약, Closed 되었는데, 아직 끝나지 않았다고 생각이 드시면, Reopen을 하시면 됩니다!
재미있는 시스템이지요?

이 페이지 하단에 보시면, `Reopen and comment` 버튼이 있습니다.
올려주신 질문과 관련되어, 추가 질문이 있으신 경우, 이 버튼을 누르시고 추가 질문을 작성해주시면 됩니다!

**Comment by yeah2055** [comment]
안녕하세요, 질문삭제건으로 연락드렸던 수강생입니다.
답변 감사드립니다. 추가질문할것이 있어 정리 후 추가질문드리겠습니다.

2019년 1월 20일 (일) 오후 8:07, Daeyeol Ryu <notifications@github.com>님이 작성:

**Comment by yeah2055** [comment]
추가 질문 으로 다시 작성합니다.
위에 쓰여있듯이 저는 이제 막 WEB1강의를 들은 사람입니다. 최종목표는 https://tineye.com/ 틴아이 같은 서비스를 만드는것입니다. 
그런데 저는 이제 막 시작을 했는데 어려운 수순부터 시작하면 흥미와 열정을 잃을까봐 무섭습니다. 현직자께서 올린 유투브를 보니
1. HTML  CSS
2.자바스크립트JS(바닐라자바스크립트 ->HTML을 자바스크립트으로 수정하는것이 편할시점, HTML을 자바스크립트로 인터랙티브까지의 수준 ※라이브러리 도움없이)
3.바닐라 자바스크립트로 작은 프로젝트를 한다(인터랙션작고 심플한것)
4.라이브러리를 이용
5.백엔드 Node js  express 웹사이트 구현(프론드엔드-백엔드 구동원리)
순으로 하라고 하던데 제가 하려는 서비스가 이에 맞는지 궁금합니다.(공부해야할 순서가 궁금합니다.) 그리고 틴아이에서 https://services.tineye.com/docs
이 것들을 배워서 구현한다는 것인지를 알고싶습니다...마지막 졸업식에 이렇게 긴 질문 남겨서 죄송합니다.
