### ISSUE TITLE
URL에 index.html이 있고 없고 차이가 납니다.

### ISSUE THREAD

**Issue by mypark7867** [codingeverybody/codingyahac#594]
# 해결하고자 하는 문제
깃에서 제공하고는 깃 페이지를 이용하여 웹호스팅하였구요.
WEB1강의에서 배운대로 디스커스를 임베드했습니다.

문제는 URL주소에 index.html을 넣고 접속한 페이지와 넣지 않고 접속한 사이트가 서로 다릅니다.
그래서 디스커스 댓글이 따로 저장됩니다.
https://mypark7867.github.io/web/index.html
https://mypark7867.github.io/web

지금은 맨 아래쪽 댓글을 보면 쉽게 문제를 확인할 수 있는데 서로 다른 게시판이에요. ㅜㅜ
두 주소에서 같은 DISQUS의 댓글 게시판이 보이기를 원합니다.

# 코드 혹은 오류
```
   https://github.com/mypark7867/web
위 주소가 깃허브에 만든 저장소입니다.
```

# 환경
windows 10(64비트)

# 시도해본 방법
원인을 알고 싶습니다. 현재 뭘 시도해봐야 할지 모르겠어요.

**Comment by yoobato** [comment]
Page identifier 기능을 사용하시면 됩니다.
(https://help.disqus.com/developer/javascript-configuration-variables 이거 참고해보세요!)

올려주신 repository 들어가보니, 위에 config가 주석처리되어 있더라구요.
주석 풀고, 아래와 같이 page identifier 값을 넣어주시면 됩니다.
```javascript
var disqus_config = function () {
  this.page.identifier = 'a unique identifier for each page where Disqus is present';
};
```

Disqus에 page identifier를 설정하지 않으면, site url을 구분자로 사용하는데,
말씀해주신 문제도 있고, 나중에 페이지 URL이 바뀌면 연결이 끊긴다는 문제가 있어서,
page identifier를 수동으로 설정해주시는 것이 좋습니다.

**Comment by mypark7867** [comment]
감사합니다. 
덕분에 링크로 주신 동영상 강의 참고하여 해결했습니다. ^^
PAGE_URL과 PAGE_IDENTIFIER 변수를 선언하는 것은 몰라서 그냥 문자열로 넣어서 해결해 보았습니다.
변수 선언하는 것은 자바스크립트 배워야 하는 것 같네요.
