### ISSUE TITLE
전자공학과와 소프트웨어 진로

### ISSUE THREAD

**Issue by bigfootboy24** [codingeverybody/codingyahac#598]
23살의 전자공학과 학부생 이며 현재 반도체 회사 인턴을 하고 있습니다.
  현재는 전공기초에서 들은 파이썬에 빠져 관련 공부중입니다. 적성에 맞아 관련 진로를 찾는 데  주변에 현업에 계신 분들꼐 물어봐도 전자공학과의 진로를 간다 했을 때 software를 심도있게 공부하는 것이 미래에 도움이 될지 잘 모르겠다고 하십니다. 주변에 전자공학과이면서 소프트웨어 공부하는 친구도 50명중 3명으로 굉장희 적습니다. 전자공학과와 소프트웨어 두 가지가 동시에 필요한 직군이 있을까요? 단기적인 목표로는 ROS를 보고있습니다. 관련 정보를 얻기가 너무 힘드네요. 아는 직업군이 없으니 언어를 배운 후에도 어디에 적용할지 다음엔 어떤 공부를 할지 방향을 잡기가 힘듭니다. 현재로선 라즈베리 파이로 간단한 RC를 만들어보려 합니다. 
읽어주셔서 감사합니다. 좋은 하루보내시길 바랍니다.

#진로상담

**Comment by studroid** [comment]
고등학생 때까진 소프트웨어를 공부하다가, 대학교 때는 전기전자공학과로 진학 후 로봇 동아리 활동을 했으며, 산업기능요원으로 군대를 다녀온 후 2학년 2학기부터 컴퓨터과학과로 전과를 하고, 웹 & 앱 개발을 하다가 IoT 제품을 만들게 되어 주로 임베디드 & 펌웨어 개발을 계속 해오고 있는 제 입장에서 말씀드리자면,

전기전자와 컴퓨터공학과를 모두 공부하신다면 개발자로서 굉장한 경쟁력을 가지실 수 있습니다.
ROS 뿐만 아니라, 그보다 더 로우 레벨에서 돌아가는 드라이버 코드, 임베디드 소프트웨어를 개발하기 위한 학습과 실제 개발이 용이해지죠. 실제로 각종 IoT 제품 개발사에서 하드웨어부터 응용 계층까지 전반적인 이해를 하고 있는 임베디드 or 펌웨어 개발자를 많이 찾습니다.

제 기준에서 판단해보자면, 스마트폰의 등장과 함께 응용 레벨의 개발자 수요가 급증했었고, 특수한 개발 환경이 필요치 않은 응용 계층의 특성 덕에 많은 분들이 응용 계층 개발을 상대적으로 쉽게 접하고 배울 수 있었습니다. 그에 따라 개발자 양성도 많이 됐죠 :)

하지만 조금 더 낮은 계층에서 주로 개발을 하게 되는 임베디드 영역에서는, 스마트폰과의 연결을 통해 무언가 만들고자 하는 제품 개발사는 늘어난 반면, 임베디드 관련 개발을 해봤거나 제품을 다뤄본 경험이 있는 개발자의 수는 그리 늘어나지 않았습니다.

게다가 응용 계층의 복잡도가 올라가며 응용 레벨의 개발자들이 쓰는, 생산성을 위한 이런 저런 도구들이 많이 생겼음에도 임베디드 영역에서는 그런 도구들의 활용이 아직까지 잘 이뤄지지 않는 경우가 많습니다. 극단적인 예를 들면, 몇십 년 경력을 가진 임베디드 개발자 분들도 Git과 같은 분산 버전 관리 시스템을 아직까지 써보지 않았거나, SVN조차 쓰지 않는 경우도 많습니다.

한마디로 말하면 개발자 입장에서는 기회의 땅이라는 거죠 :) 임베디드 영역에서 크리티컬한 포인트들을 배우고 경험하면서 전문성으로 계속 키워나가고, 응용 계층에서 쓰이는 다양한 기법들을 함께 적용할 수 있다면 군계일학이 되실 수 있다고 확신합니다.

어떤 점 때문에 전기전자와 소프트웨어를 동시에 공부하길 원하시는지 명확히 생각해보시면, 앞으로의 진로를 선택하는 데에 도움이 되지 않을까 싶습니다.

더 와닿는 경험을 빨리 해보고 싶으시다면, 각종 해커톤(메이커톤)이나 경진대회에 참가해보시는 것도 좋을 것 같습니다.

다음 링크들에 있는 것처럼 각종 대회가 자주 열린답니다 :)

http://eswcontest.com/htm/about_01.php
https://festa.io/events/68
http://fablab-seoul.org/incheonmakeathon18-2/

**Comment by bigfootboy24** [comment]
답변 정말 감사드립니다. 아직 모르겠는 단어들이 많이 있지만 제가 공부를 해가면서 오래 읽어볼 소중한 조언같습니다. 시간 내주셔서
조언해주셔서 진심으로 감사드립니다.

2019년 1월 17일 (목) 오후 4:18, studroid <notifications@github.com>님이 작성:
