### ISSUE TITLE
아톰 에디터 쓰시는분들 외부 파일 복사해서 붙여넣기 되시나요?

### ISSUE THREAD

**Issue by sskim91** [codingeverybody/codingyahac#60]
안녕하세요. 텍스터 에디터로  아톰을 사용하고 있는데

외부 이미지 파일이나 소스파일 등을 복사해서 아톰에 직접 붙여넣기가 안됩니다.

그래서 직접 프로젝트 폴더가 있는 곳을 파인더로 열어서 붙여넣고 있습니다.

저만 이런건가요..?

아톰 파일 트리 뷰에 복사해서 붙여넣으면 키가 먹지를 않네요

혹시 저와 같은 증상이거나 해결하신분 도움좀 주시면 감사하겠습니다.

아톰 버전은 최신버전으로 업데이트 해놓은 상태이고

사용 OS는 맥 하이시에라 10.13.2버전입니다.

**Comment by kkoma2** [comment]
저도 그랬는데 원인은저도잘...

**Comment by progh2** [comment]
똑같은 질문으로 아톰 깃허브 프로젝트의 이슈에서 
여러 사람들이 지원해달라고 호소한 글에 개발자분이 못한다고 답글단 기록을 찾았습니다. ^^;

https://github.com/atom/tree-view/issues/569

atom 은 electron 이라는 프레임워크 기반으로 만들어졌는데요, 
이 프레임워크가 아직 해당 기능을 지원 못한다네요.

**Comment by sskim91** [comment]
@kkoma2 감사합니다!!
@progh2  감사합니다!!
