### ISSUE TITLE
PHP MySQL 문법 관련 질문이 있습니다

### ISSUE THREAD

**Issue by lopbur** [codingeverybody/codingyahac#602]
# 해결하고자 하는 문제

안녕하세요

php 문법 중 큰 따옴표와 따옴표를 사용하는 규칙이 있는지 궁금해서 질문을 올립니다.

```
<?php 
$conn = @mysqli_connect("localhost", "root", "11111111", "data");
if(!$conn){
    die ("Connection Error: ". mysqli_connect_errno());
}

function requestServer($query){
    $result = mysqli_query($GLOBALS['conn'], $query);
    return $result;
}

function printTitle(){
    $sql = requestServer("SELECT * FROM contents WHERE id={$_GET['id']}");
    $row = mysqli_fetch_array($sql);
    echo "{$row['title']}";
}
?>
```

위 코드에서 

`
    $sql = requestServer("SELECT * FROM contents WHERE id={$_GET['id']}");
`

이 부분의 큰 따옴표와 따옴표의 자리를 서로 바꾸어 아래 코드가 되면 $result 값이 false 가 되어
데이터베이스 테이블에서 값을 가져오지 못합니다
 
`
    $sql = requestServer('SELECT * FROM contents WHERE id={$_GET["id"]}');
`

> Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in D:\Bitnami\apache2\htdocs\index.php on line 22

이게 문법 문제인지 아니면 다른 문제가 있는지 궁금한 점이 생겨 질문 올립니다.
도움 부탁드리겠습니다.

# 코드 혹은 오류

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

Window10, kor, 

# 시도해본 방법

**Comment by znffl** [comment]
안녕하세요. 
php에서 작은따옴표, 큰따옴표는 일반적인 경우 동일한 출력을 하지만 특정조건에서는 다른 결과를 출력하게 됩니다. 

아래 url 을 보시면 왜 차이가 나는 지 확인 하실 수 있습니다.
http://friday.fun25.co.kr/blog/?p=147

**Comment by lopbur** [comment]
답변 정말 감사드립니다
