### ISSUE TITLE
머신러닝

### ISSUE THREAD

**Issue by CarryKim** [codingeverybody/codingyahac#603]
안녕하세요.  Java 웹개발자로 주로 front단부터 server단까지 웹페이지 만드는 작업을 했었는데
요즘들어 AI관련 머신러닝에 관심이 갑니다. 앞으로 그쪽이 시대흐름에 따라 알아야할 분야인거 같은데요.
개발자로서 이런부분을 어떻게 접근해야될지 잘 모르겠습니다.
선형대수와 같은 수학지식도 필요할거 같은데 오래전에 수학을 손에 놔서 공부가 많이 필요합니다.
개발자로서 로직을 이해하고 그냥 파이썬 같은 언어로 개발할 수 있나요? 
웹과는 다르게 많이 복잡하다는 생각이 듭니다..

**Comment by yoobato** [comment]
질문자님의 공부 스타일에 따라 다를 것 같습니다.

실습(경험)을 먼저 한 다음, 이론을 익히는 타입이라면, 일단 머신러닝 예제를 아무거나 따라 만들어보시는게 좋을 것 같습니다. (실습 과정에서 내가 기존에 가지고 있는 지식들과 연결되는 점이 분명히 있을거에요.

이론을 먼저 익히고, 실습을 하는 타입이라면, 요즘 제가 읽고 있는 책이기는 한데, [신경망 첫걸음](http://www.hanbit.co.kr/store/books/look.php?p_code=B1910379076) 이라는 책을 추천해드립니다!

참고로, 파이썬은 머신러닝 분야에서 많이 사용되는 언어이지, 머신러닝은 무조건 파이썬으로 해야돼!는 아닙니다.
제 경험을 말씀해 드리자면, 작년에 대학에서 컴퓨터 시스템이라는 강의를 듣는데, 어셈블리어로 에어컨의 자동 온도 기능을 개발하는 머신러닝 과제를 수행해야 했던 적이 있습니다. 단순한, [선형회귀분석](https://ko.wikipedia.org/wiki/%EC%84%A0%ED%98%95_%ED%9A%8C%EA%B7%80) 을 이용하는 것이었고, 사용자가 외부 온도가 섭씨 n도 일 때, 보통 m도를 희망 온도로 해놓더라는 것을 매번 학습해서, '자동 온도'를 몇 도로 설정할 것인지에 대한 답을 내놓는 과제였습니다.

저 또한, 머신러닝 = 파이썬 사용 이라는 생각을 가지고 있다가, 생각의 틀이 깨지는 순간이었습니다 😄

**Comment by CarryKim** [comment]
> 질문자님의 공부 스타일에 따라 다를 것 같습니다.
> 
> 실습(경험)을 먼저 한 다음, 이론을 익히는 타입이라면, 일단 머신러닝 예제를 아무거나 따라 만들어보시는게 좋을 것 같습니다. (실습 과정에서 내가 기존에 가지고 있는 지식들과 연결되는 점이 분명히 있을거에요.
> 
> 이론을 먼저 익히고, 실습을 하는 타입이라면, 요즘 제가 읽고 있는 책이기는 한데, [신경망 첫걸음](http://www.hanbit.co.kr/store/books/look.php?p_code=B1910379076) 이라는 책을 추천해드립니다!
> 
> 참고로, 파이썬은 머신러닝 분야에서 많이 사용되는 언어이지, 머신러닝은 무조건 파이썬으로 해야돼!는 아닙니다.
> 제 경험을 말씀해 드리자면, 작년에 대학에서 컴퓨터 시스템이라는 강의를 듣는데, 어셈블리어로 에어컨의 자동 온도 기능을 개발하는 머신러닝 과제를 수행해야 했던 적이 있습니다. 단순한, [선형회귀분석](https://ko.wikipedia.org/wiki/%EC%84%A0%ED%98%95_%ED%9A%8C%EA%B7%80) 을 이용하는 것이었고, 사용자가 외부 온도가 섭씨 n도 일 때, 보통 m도를 희망 온도로 해놓더라는 것을 매번 학습해서, '자동 온도'를 몇 도로 설정할 것인지에 대한 답을 내놓는 과제였습니다.
> 
> 저 또한, 머신러닝 = 파이썬 사용 이라는 생각을 가지고 있다가, 생각의 틀이 깨지는 순간이었습니다 😄

답변 감사합니다^^
저는 인제야 딥러닝, 머신러닝 관심이 가서 완전 초초초급이에요 ㅎㅎ 
세미나를 통해서 조금씩 알아가고 있는데 실습할 생각은 막막하더라구요. 그래도 실습하면서 이론을 익히는 방법도 나쁘지 않겠다는 생각이 드네요. 모든 손으로 따라해봐야 오래 남으니깐~

**Comment by yoobato** [comment]
사실, 머신러닝이라는게 되게 어렵게 느껴져서 그렇지, 실제로 하시다 보면 질문자님께 별게 아니라는 생각이 들거라고 확신합니다 😄 

화이팅하세요!

**Comment by CarryKim** [comment]
> 사실, 머신러닝이라는게 되게 어렵게 느껴져서 그렇지, 실제로 하시다 보면 질문자님께 별게 아니라는 생각이 들거라고 확신합니다 😄
> 
> 화이팅하세요!

화이팅입니다~! ^^
