### ISSUE TITLE
프로젝트에 관련된 공부방향

### ISSUE THREAD

**Issue by yeah2055** [codingeverybody/codingyahac#604]
추가 질문 으로 다시 작성합니다. 닫힌 질문 592를 이어서 추가질문입니다 질문 오픈버튼을 도져히 못찾아 다시 올립니다.
저는 이제 막 WEB1강의를 들은 사람입니다. 최종목표는 https://tineye.com/ 틴아이 같은 서비스를 만드는것입니다. 
그런데 저는 이제 막 시작을 했는데 어려운 수순부터 시작하면 흥미와 열정을 잃을까봐 무섭습니다. 현직자께서 올린 유투브를 보니
1. HTML  CSS
2.자바스크립트JS(바닐라자바스크립트 ->HTML을 자바스크립트으로 수정하는것이 편할시점, HTML을 자바스크립트로 인터랙티브까지의 수준 ※라이브러리 도움없이)
3.바닐라 자바스크립트로 작은 프로젝트를 한다(인터랙션작고 심플한것)
4.라이브러리를 이용
5.백엔드 Node js  express 웹사이트 구현(프론드엔드-백엔드 구동원리)
순으로 하라고 하던데 제가 하려는 서비스가 이에 맞는지 궁금합니다.(공부해야할 순서가 궁금합니다.) 그리고 틴아이에서 https://services.tineye.com/docs
이 것들을 배워서 구현한다는 것인지를 알고싶습니다...마지막 졸업식에 이렇게 긴 질문 남겨서 죄송합니다.

**Comment by yoobato** [comment]
이전질문: https://github.com/codingeverybody/codingyahac/issues/592

**Comment by yoobato** [comment]
지난 번에 여쭤보신 것은, 영상 처리(Computer Vision)에 관련된 것이었는데,
웹 사이트 제작을 여쭤보시는건가요? 아니면, 영상 처리 기술을 여쭤보시는건가요?

**Comment by yeah2055** [comment]
제가 잘 몰라, 질문을 이상하게 한것같습니다. 처리 기술을 가지고 웹사이트와 앱을 만들어 서비스 지원을 생각하고 있습니다.

**Comment by yoobato** [comment]
일단 영상 처리와 웹 사이트 제작은 서로 분리해서 생각하시는게 좋을 것 같습니다.

1. 영상 처리 자체는 웹(Front-end)에서 해결하기 어려우실 것입니다. Javascript 만으로는 개발이 어려우실 것이며,
C, C++ 등의 다른 프로그래밍 언어을 사용하여 이미지를 분석하는 모듈을 만드셔야 할 것입니다.
또한, 이것은 현재 생활코딩에 올라와 있는 강의만으로는 학습이 어려우실 것입니다. 꽤 전문적인 분야라서요. 이 부분은 책을 사셔서 따로 공부를 하시는 것을 추천해드립니다.

2. 웹사이트 개발은 말씀해주신 과정대로 진행하시는게 좋을 것 같습니다. 

3. 앱 개발은 또 다른 영역이지요. iOS 앱의 경우 Objective-C와 Swift 언어를 사용하여 개발하고, Android 앱의 경우 Java와 Kotlin 언어를 사용하여 개발합니다. 물론 이건 Native app의 경우이고, Hybrid app을 만드신다면, React-native 같은 Javascript 언어를 사용하는 것도 이용하실 수 있습니다. (Javascript를 공부하시는 것 같으니, React-Native를 추천해드립니다!) 또는, 모바일 웹을 개발하신 다음 iOS, Android SDK 에서 제공하는 WebView(웹페이지를 보여주는 컴포넌트) 위에 단지 보여주기만 하는, Web app 을 개발하실 수도 있습니다.
각각이 장, 단점이 있으니 어느것을 선택할지는 모두 천천히 살펴보시고 결정하시는게 좋을 것 같습니다. 참고로, Native app을 개발하는 것은 학습해야할 양이 상당하니, Hybrid app이나 Web app을 먼저 개발해보시는 것을 추천해드립니다.

4. https://tineye.com 같은 사이트를 직접 만들고자 하시는게 아니라, 이 사이트에서 제공하는 영상 처리 기술을 이용하시는 것이면, 올려주신 https://services.tineye.com/docs 사이트에 있는 Tineye의 API를 활용하는 방법도 있습니다. 당장, 영상 처리 모듈을 개발하시는 것은 어려울테니, 이곳에서 제공하는 API를 연동하여 개발하는 것이 더 좋을 것 같네요 😄. 이것은, Tineye의 영상 처리 모듈을 이용한다는 것을 의미합니다. Tineye에서 제공하는 REST API를 이용하시면, Tineye 쪽에 이미지를 보내는 것만으로 분석 결과(?)를 얻을 수 있는 것 같습니다.

**Comment by yoobato** [comment]
참고로, Reopen 버튼은 스크롤을 내리시면, 하단에 위치하고 있습니다.
아래 스크린샷 참고해보세요!

![qwer](https://user-images.githubusercontent.com/1592319/51487247-2f9cce80-1de6-11e9-9773-9b70cfed5f99.png)

**Comment by yeah2055** [comment]
세상에나, 마지막날에 이렇게나 친절하게 답변을 해주셔서 저는 죄송하고 감사합니다.
제가 정말 입문자 쌩초보로 라서 두가지가 따로 생각을 해야된다는 것을 알게 되었고, 정말 궁금하고 가려웠던 부분을 너무나도 시원하게 긁어주셔서 지금 행복합니다. 앞으로 해야할 것이 많아진것 같아 막막하긴하지만... 정말 알려주시고 도와주셔서 감사드립니다. 열심히 해서 언젠간 결과물을 내어서 보여드리고 싶네요! 마지막으로 한번 더 감사합니다!!
