### ISSUE TITLE
강의 순서에 대해 질문하고 싶습니다

### ISSUE THREAD

**Issue by joeuni** [codingeverybody/codingyahac#606]
안녕하세요! 지금 강의 web1 다 수강하고 나니 다음강의 그 후의 강의를 어떤 순서로 들어야 할지 감이 안잡히네요. 

우선 저는 css -> java script -> node.js 순으로 생활코딩 목차에 있는 그대로 들으려 했는데 중간중간 ajax등 다른 강의들이 있어서 고민입니다. 
정답은 없겠지만 아무것도 모르는 상태여서 추천하시는 순서가 있다면 알려주시면 감사하겠습니다ㅠㅠ

**Comment by yoobato** [comment]
어떤 것을 하시고 싶으신 것인지, 무엇을 만들고 싶으신 것인지에 따라서 순서가 달라질 수 있을 것 같습니다.

https://seomal.org/
위 사이트 참고해보시면, 어느 순서로 공부하는게 좋을지 감이 잡히실 것이라 생각됩니다.

각 원에 마우스를 올려보시면,
**빨간선** : 이것을 공부하기 위해 어떤 공부가 필요하고,
**파란선** : 이것을 공부하면 무엇을 더 할 수 있는지 알 수 있습니다.

**Comment by joeuni** [comment]
사이트를 보니까 어떤 순서로 공부해야 할지 정리가 되네요!! 정말 감사합니다!!!
