### ISSUE TITLE
(nodejs javaScript) 함수부분을 실행시키면 페이지에 수정상태를 계속 유지시키고 싶습니다.

### ISSUE THREAD

**Issue by mokaim** [codingeverybody/codingyahac#608]
# 해결하고자 하는 문제
    
      node.js를 공부하면서 실제 테스트 페이지를 만들고있습니다.. 하지만 문제가 되는게..
      해당 자바 스크립트 코드에 넣은 스타일시트 수정부분을 페이지에 계속해서 남기고싶습니다.
      스크립트 코드안에 있는 reaction() 이라는 함수입니다.
      저 함수를 실행시키면 일단 스타일시트가 수정이 되는것 까지는 확인하였습니다.
      문제는 잠깐 실행되다가 다시 원상태로 원복된다는 겁니다...

      원래 함수라는 것이 한번 실행되서 끝나게 되면 전역변수에 저장하지 않는한 대부분의 함수데이터
      는 메모리상에서 사라지게 되는걸로 알고는 있지만.. 저 reaction 함수는 분명 스타일시트
      를 바꾸기로 설정이 되어있는데 왜 지역변수 같이 한번 실행되다가 바로 사라지는지 모르겠습니다..

      현재의 description 본문 부분에는 제가 따로만든 data라는 폴더의 test라는 임의의 텍스트파일
      을 읽어오는 방식의 테스트 웹 어플리케이션 입니다.(이고잉님의 수업소스를 살짝 응용했습니다 ㅎ)

      예를 들어 test 링크를 클릭하면 display 부분이 block이 되면서 ${description} 부분의 텍스트가 계속 
     보여져야 하는데 현재는 test링크를 클릭하면 텍스트가 잠깐 보여졌다가 다시 사라집니다..

      즉 잠깐동안 block 이 되었다가 다시 none 으로 바뀌는 것 같아요 ㅠㅠ
      test 링크를 클릭하면 계속 block인 상태로 유지하게 하고 싶은데.. 구글에 영문으로
      검색을 해봐도 뭔가 원하는 검색방향을 못잡고있는것 같고.. 이것가지고 3시간 가량을 헤맨거
      같네요..;; ㅎㅎ

# 코드 혹은 오류
```
var http = require('http');
var fs = require('fs');
var url = require('url');

var app = http.createServer(function(request,response){
    var _url = request.url;
    var queryData = url.parse(_url, true).query;
    var title = queryData.id;
    if(_url == '/'){
      title = 'Trip';
    }
    if(_url == '/favicon.ico'){
      return response.writeHead(404);
    }
    console.log(_url);
    console.log(title);
    response.writeHead(200);
    fs.readFile(`data/${queryData.id}`, 'utf8', function(err, description){
      var template = `
      <!doctype html>
      <html lang="kr">
      	<head>
      	<meta charset="UTF-8">
      	<title>Trip</title>

        <style>
        body {
          background-color: #000000;
          position: relative;
          min-height: 100vh;
          margin: 0;
          font-family: 'Droid Sans', sans-serif;
          color: #fff;
        }
        body:before {
          content: '';
          position: fixed;
          top: 0px;
          left: 20%;
          bottom: 0px;
          -webkit-transform: translateX(-50%);
                  transform: translateX(-50%);
          width: 4px;
          background-color: #fff;
        }

        body .entries .entry {
          word-wrap: break-word;
          width: 220px;
          float: left;
          padding: 20px;
          clear: both;
          text-align: left;
        }

      	body .entries .entry:not(:first-child) {
      	  margin-top: -40px;
      	}
      	body .entries .entry .title {
      	  font-size: 32px;
      	  margin-bottom: 12px;
      	  position: relative;
      	}

      	#body01 {
      		display: none;
          position: absolute;
      		left: 25%


      	}

      	a { color: inherit; }

        </style>

        </head>
        <body>


        <script>

        function reaction(clickOk){
          var x = document.getElementById("body"+clickOk);
          x.style.display="block";
        }
        </script>

        <div class="timeline">
          <div class="entries">
            <div class="entry">
      				<a href='/?id=test' >
              <div class="title" align="left" style="font-size:180%" onclick="reaction(this.id)" id="01">test</div>
      			  </a>
              <div class="body" id="body01">
                <p>${description}</p>
              </div>
            </div>


          </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript">
        </script>
        </body>
      </html>
      `;
      response.end(template);
    })


});
app.listen(3000);
```

# 환경
Windows10사용
NodeJs를 이용한 JavaScript
node.js 의 버젼 : 10. 15. 0

# 시도해본 방법
구글링을 하면서 어떻게 해서든 html 내의 자바스크립트 코드에서 스타일시트 수정방법까지는
찾아내었지만 현재 질문한 사항에 대해서는 전혀 감이안잡히네요 ㅠㅠ

**Comment by blackdew** [comment]
처음 서버와 클라이언트를 동시에 개발할 때에 누구나 겪는 상황이에요. :) 

`reaction` 함수는 브라우저에서 실행이 되는 클라이언트 사이드의 코드입니다. 
즉, 서버가 전송해 준 js가 포함된 html 파일을 브라우저가 들고 있는 상황에서만 유의미합니다. 

서버로 새 페이지 전송을 요청하여 새로운 js+html 코드를 받는 순간 이전의 화면에서 처리하던 모든 내용은 reset이 됩니다. 현재는 클라이언트의 `reaction` 함수를 실행시키지만 동시에 `a`태그를 통해 서버로 새 페이지 전송을 요청하고 있죠. 새 페이지를 받아오는 순간 현재 페이지에서 변수로 저장된 모든 값은 사라지게 되는 것입니다.

만일, 클라이언트 사이드에서 페이지가 넘어가도 값을 유지시키고 싶으면 `cookie`나 `local storage` 같은 것을 이용해서 할 수 있습니다. 
혹, 서버에서 해당 값을 유지하고 싶다면, 서버로 그 값을 전송해주는 절차가 필요한데요. `a` 태그에 `id`값을 넘겨주었듯 저장하고 싶은 값을 넘겨주어 그 값을 가지고 페이지를 생성해서 보내줄 수도 있습니다. 그렇게 되면 `reaction` 함수를 쓰지 않아도 되는 것이에요. 

클라이언트의 코드 동작과 서버에서의 코드 동작의 차이와 각각이 어떤 결과를 만들어 내는 것인지 조금 더 고민해 보시면 '아항'하게 될 겁니다. 이미 web1 수업을 들으셨으면 코드와 지식이 아직 만나지 못한 것일 뿐 이미 알고 계시는 개념일 거에요. 

그리고 클라이언트에서 페이지 이동시 값을 유지시키기 위한 방법에 대해서 공부를 해보시면 도움이 될 겁니다. 
`cookie`, `session`, `local storage` 같은 게, 핵심 키워드에요.

**Comment by mokaim** [comment]
정말 감사합니다 ㅠㅠ blackdew 님 ㅠㅠ 제가 진작 그 생각을 못했네요.. 답변이 달린줄 모르고 있다가
뒤늦게 감사의 인사올립니다.. ㅎㅎ 애시당초 한번 페이지를 동기화 시키게 되면 노드의 스크립트 언어전체가 다시 리셋되서 처음부터 컴파일되서 보내지는 걸 깜빡있고 있었네요... 코드를 짤 때 미스가 있었던 것 같습니다... blackdew 님 말씀대로 브라우저에서 보내는 request의 쿠키값으로 조건문을 다시만들어 코드를 짜니 원하는 프로그램으로 탄생했습니다 ㅎㅎ 쿠키를 배우고 짜는데까지 5시간 이상이 걸렸지만...;; 정말 감사합니다 ^^

**Comment by mokaim** [comment]
> 처음 서버와 클라이언트를 동시에 개발할 때에 누구나 겪는 상황이에요. :)
> 
> `reaction` 함수는 브라우저에서 실행이 되는 클라이언트 사이드의 코드입니다.
> 즉, 서버가 전송해 준 js가 포함된 html 파일을 브라우저가 들고 있는 상황에서만 유의미합니다.
> 
> 서버로 새 페이지 전송을 요청하여 새로운 js+html 코드를 받는 순간 이전의 화면에서 처리하던 모든 내용은 reset이 됩니다. 현재는 클라이언트의 `reaction` 함수를 실행시키지만 동시에 `a`태그를 통해 서버로 새 페이지 전송을 요청하고 있죠. 새 페이지를 받아오는 순간 현재 페이지에서 변수로 저장된 모든 값은 사라지게 되는 것입니다.
> 
> 만일, 클라이언트 사이드에서 페이지가 넘어가도 값을 유지시키고 싶으면 `cookie`나 `local storage` 같은 것을 이용해서 할 수 있습니다.
> 혹, 서버에서 해당 값을 유지하고 싶다면, 서버로 그 값을 전송해주는 절차가 필요한데요. `a` 태그에 `id`값을 넘겨주었듯 저장하고 싶은 값을 넘겨주어 그 값을 가지고 페이지를 생성해서 보내줄 수도 있습니다. 그렇게 되면 `reaction` 함수를 쓰지 않아도 되는 것이에요.
> 
> 클라이언트의 코드 동작과 서버에서의 코드 동작의 차이와 각각이 어떤 결과를 만들어 내는 것인지 조금 더 고민해 보시면 '아항'하게 될 겁니다. 이미 web1 수업을 들으셨으면 코드와 지식이 아직 만나지 못한 것일 뿐 이미 알고 계시는 개념일 거에요.
> 
> 그리고 클라이언트에서 페이지 이동시 값을 유지시키기 위한 방법에 대해서 공부를 해보시면 도움이 될 겁니다.
> `cookie`, `session`, `local storage` 같은 게, 핵심 키워드에요.
