### ISSUE TITLE
강의들을 때 듣기만 할까요?

### ISSUE THREAD

**Issue by kkoma2** [codingeverybody/codingyahac#61]
강의 들을때 저는 어려운개념이나 모르는 내용이 나오면 전부 적으면서 듣고있습니다. 이런식으로 들으면 필기할동안 강의가 넘어가서 강의를 일시정지하고 쓰기가 부기지수인데요. 사실 어렸을때도 이런식으로 컴퓨터 강의를 들으면 모르는 것이많아 적다가 수업을 놓칠 때가 많았어요. 코딩야학을 포함해서 컴퓨터 관련
강의를 들을때 굳이 모르는 내용을 전부 필기 하지 않아도 될까요?

**Comment by progh2** [comment]
공부 스타일에 관련된거라 kkoma2님 스타일에 맞춰서 하시면 될 것 같습니다.
오프라인 강의에 비해서 온라인 강의의 가장 큰 장점이 학습자의 속도에 맞춰서 강의를 조절할 수 있다는 점이니까요. =)
모두 다 필기하기 보다는 중요 개념이나 키워드 중심, 관계 중심으로 적고 복습할 때 기억 안나는 부분이나 
애매한 부분만 다시 체크해서 보는 방법도 어떨까하고 제안드려봐요.. ^^

**Comment by egoing** [comment]
필기가 공부에 도움이 된다면 하셔도 좋습니다만, 이제 언제든지 찾아볼 수 있는 시대입니다. 나중에 찾아보기 위한 용도라면 꼭 그렇게 하지 않아도 될 것 같습니다. 제가 추천드리는 방법은 자신을 위한 필기가 아니라, 누구나 볼 수 있는 보편적인 컨텐츠를 만들어보세요. 글도 좋고, 동영상도 좋습니다. 인포그라피도 너무 좋고요. 그걸 정리하는 과정에서 자신이 무엇을 알고 있는지를 자신과 타인에게 증명까지 할 수 있습니다. 생활코딩이 바로 그렇게 만들어진 컨텐츠랍니다~ 물론 사견이었습니다 :)

**Comment by kkoma2** [comment]
답변 감사합니다 ^^
