### ISSUE TITLE
javascript에 대한 질문을 하려고합니다!

### ISSUE THREAD

**Issue by SEONGDONGWON** [codingeverybody/codingyahac#614]
# 해결하고자 하는 문제
안녕하세요. 코딩을 1개월째 독학을 하고 있는 학생입니다!!
궁금한 점이 있어서 질문을 합니다. 
우선 제가 원하는 결과물은 통계그래프입니다.
예를 들면 총 20회가 이루어져 있는 문제집이 있다고 하면, 1회에선 70/100 2회에선 65/100 3회에선 90/100 이런식의 점수가 나온다하면 매 회에 점수를 입력을 사용자로부터 입력을 받아서 그 수치를 토대로 그래프를 javascript로 구현을 하고 싶습니다. 
우선적으로 javascript로 구현이 가능한지 알고 싶습니다.
생활코딩을 통해서 javascript를 공부하고 있는데 prompt를 통해서 사용자에게 입력값을 받아서 토대로
다음작동을 한다는 것을 배웠습니다. 그래서 지금 제가 현재 정보처리기사 자격증 필기를 준비중인데,
매회 점수를 통계값을 넣어서 그래프를 그려보면 어떨까 싶어서 생각해보았습니다.....

* 우선적으로 javascript를 통해서 구현이 가능한 점!
* 구현이 가능하다면 egoing님 께서 항상 말씀하시는, 검색을 하는 능력을 키우기 위한
  검색 키워드를 알려주시면 감사하겠습니다...

# 환경

컴퓨터에 대해 잘 모르고 있어서 저는 윈도우를 사용하고 있으며, 에디터는 ATOM을 사용합니다!!

**Comment by JangsilHyun** [comment]
chart.js를 알아보세요

**Comment by SEONGDONGWON** [comment]
> chart.js를 알아보세요

감사합니다 도움이 많이 되었습니다 !!

**Comment by znffl** [comment]
해당 이슈를 close 하겠습니다.
추가 궁금한 점이 있으시면 다시 open 부탁드려요~
