### ISSUE TITLE
Stackoverflow의 질문 기술

### ISSUE THREAD

**Issue by notkimwol** [codingeverybody/codingyahac#616]
# 해결하고자 하는 문제

Stackoverflow에 질문을 잘 하고 싶습니다.
학우분들 만의 질문하는 요령? 정보가 있나요?

코드에 대하여 물어보는 게 아니다 보니 글이 많이 짧네요 ㅎㅎ...

**Comment by progh2** [comment]
뭐... 일반적으로 이미 있는 질문인지 확인해보고, 확실히 없다면
자신의 상황을 최대한 구체적으로 쓰고, 어떠한 방법을 시도했는지도 나열하고
관련된 이전 사례들(스택오버플로우)도 봤는데 안되더라, 어떻게 하면 좋을까? 식으로 남기는 식으로
적으면 좋을 것 같습니다.

아래 링크가 이러한 것들을 대변해 줄 것 같네요 =D
http://wiki.kldp.org/wiki.php/DocbookSgml/Ask-TRANS
