### ISSUE TITLE
안녕하세요 input tag password type 에 대한 질문을 하려합니다.

### ISSUE THREAD

**Issue by seongdongwon1** [codingeverybody/codingyahac#618]
!! 안녕하세요

현재 스스로 공부를 하면서 회원가입 시스템을 만들어보고 있는 학생입니다.

공부를 하면서 막히는 부분이 있어서 이렇게 질문을 올립니다.

input tag 를 통해서 password type 으로 설정을 해서 사용자로부터 password 를 받으려고 합니다.

그런데, password 라는 것이 개인정보 유출에 위험이 있기 때문에 암호화 하도록 하는 것이

가장 중요하다고 생각을 합니다. 그런데, 제가 확인을 해보니까 password type 때문에 눈앞에 보

이지는 않지만 console.log 를 통해서 확인을 해보니 입력한 글자가 그대로 보이더라구요...

이렇게 된다면, 회원가입 정보를 다 입력을 하고 회원가입버튼을 눌렀을 때 회원정보가 서버로 전

송이 될 거고 전송되는 시점에서 패킷 시니핑을 한다면 정보가 보일 것 같다는 생각이 드는데,

이 부분을 암호화 하는 방법이 있는지 궁금합니다...

# 해결하고자 하는 문제

# 코드 혹은 오류
```
  input tag password type 의 id = pw1
  이 input 박스에 글자를 넣으면 ******* 식으로 표현이 될 것이고,

 페이지 검사를 통해서 console.log(pw1.value); 를 실행 해보니
 a123456 

이렇게 확인이 되더라구요. 원래 이런 것 인지.. 아니면 console.log 를 통해서도 암호화 해서 서버로 전송되도록 하는 방법이 있는지 궁금합니다.


``` 

# 환경

atom. window

# 시도해본 방법
 시도는 아직 해보진 않았지만, value 값을 암호화(?) 해보고 싶어서 검색을 통해서 찾아 보았는데, 정보를 찾을 수가 없었습니다... 
 지금 생각 하고 있는 시도방법은 입력되는 암호를 hash 나 sha256 으로 암호화 해서 서버로 전송되도록...?  지금은 잘 모르고 공부하면서 구현하는 학생이라 열심히 찾아보고 있습니다.

 조언 부탁드리겠습니다~!

**Comment by davidkwak** [comment]
웹 브라우저에서 서버로 전송되는 데이터를 암호화하기 위해서 주로 SSL 을 사용합니다. 
말씀하신 경우에 필요한 기술이지요. 

마침 생활 코딩에 관련 내용이 잘 정리되어 있네요 
https://opentutorials.org/course/228/4894

**Comment by seongdongwon1** [comment]
감사합니다 !! 참고해보겠습니다 !!!

**Comment by znffl** [comment]
https://seyul.tistory.com/34
