### ISSUE TITLE
안녕하세요 javascript value 값에 대해서 여쭤보려고 합니다!!

### ISSUE THREAD

**Issue by seongdongwon1** [codingeverybody/codingyahac#619]
# 해결하고자 하는 문제

안녕하세요 현재 제가 구현하고 있는 것은 회원가입 시스템을 구현해보고 싶어서 진행하고 있습니다.

정규식을 이용해서 email을 정확하게 입력을 했는지 진행을 하고 있습니다.

제가 현재 구현한 방식은

----------------------------------------------------------------------------------------------------------
input box1 @ input box2
----------------------------------------------------------------------------------------------------------
이렇게 input box가 2개로 구현이 되어있습니다.

때문에 저는 현재 box1 과 box2에 사용자가 입력해주는 입력값의 value 를 확인해서

제가 정해놓은 정규식에 적합한지 test를 진행하려고 합니다.

여기서 문제가 있습니다.

box1.value , box2.value  각각의 value 값을 console.log 를 통해서 확인을 하면 제가 입력한 값이

value 값으로 확인이 됩니다.

그런데 전 let emailValue = box1.value +"@"+ box2.value;

이렇게 합쳐진 value 값을 통해서 정규식에 맞는지 확인을 하고싶은데

emailValue 의 값이 console.log 를 통해서 찾을 수 없다고만 나옵니다.

2개의 input box 의 value 값을 제가 위에 선언한 변수를 통해서 합쳐진 값을 한번에 보고 싶은데

불가능한 일인지 궁금합니다. 아니면 틀린 문법인지 궁금합니다!!.........

**Comment by davidkwak** [comment]
안될 이유가 없어보이는데 이상하네요 

![image](https://user-images.githubusercontent.com/8045012/57596001-4593f200-7583-11e9-8eca-93f144530a5b.png)

**Comment by seongdongwon1** [comment]
> 안될 이유가 없어보이는데 이상하네요
> 
> ![image](https://user-images.githubusercontent.com/8045012/57596001-4593f200-7583-11e9-8eca-93f144530a5b.png)



<div class="content">
       <div class="text">
        이메일 입력
       </div>
       <div class="content_box">

         <input id="user_email" type="text" class="email_box" title="이메일 입력" onchange="email_change(this)" onfocusout="email_change(this)">
         &nbsp @ &nbsp
         <input id="user_email2" type="text" class="email_box" value="" disabled title="이메일 주소 입력">
         <select id="email_select" name = "이메일 주소" class="box" onChange = "emailchange();">
           <option value="0">선택하세요</option>
           <option value="naver.com">naver.com</option>
           <option value="gmail.com">gmail.com</option>
           <option value="hanmail.com">hanmail.com</option>
           <option value="yahoo.co.kr">yahoo.co.kr</option>
           <option value="1">직접입력</option>
         </select>


         <h4 id="emailErrorMessage" style="color: red"></h4>
         <h4> 사용할 이메일 주소를 입력해주세요. </h4>
       </div>
      </div>

<script>
        let email  = document.getElementById("user_email");
        let email2 = document.getElementById("user_email2");
        let emailValue = email+"@"+email2;

        let message_email = document.getElementById("emailErrorMessage");
        function emailchange(){
                               if (email_select.value == '1')
                               {
                                email2.disabled = false;
                                email2.value = "";
                                email2.focus();
                               }
                               else {
                                     email2.disabled = true;
                                     email2.value = email_select.options[email_select.selectedIndex].value;
                                    }
                              }

                              let email_change = email => {
                                                            message_email.innerHTML = " ";
                                                          }
</script>


-------------------------------------------------------------------------------------------------------------------

일단은 이렇게 제가 구현을 해보았거든요. 


console 값이

[object HTMLInputElement]@[object HTMLInputElement]

이렇게 나옵니다................

**Comment by davidkwak** [comment]
위에 질문에는 `let emailValue = box1.value +"@"+ box2.value;` 라고 쓰셨는데

밑에 실제코드에는 `let emailValue = email+"@"+email2` 로 쓰셨네요 

위 질문처럼 .value를 붙이시면 될거같습니다.
