### ISSUE TITLE
1. 18 웹호스팅 강의에서 막혔습니다.

### ISSUE THREAD

**Issue by jo910904** [codingeverybody/codingyahac#62]
알려주신대로 파일을 업로드하고 마스터 브랜치로 연결해서 주소까지 얻어냈습니다.
그런데 해당 주소로 접속하면 README.md 페이지가 뜹니다.
제가 원하는 html페이지와 깃허브 주소를 연결하려면 어떻게 해야하나요?

**Comment by manen0122** [comment]
저도 그것때문에 좀 고생ㅎ 했었는데 이게 확실한 해결법인 진 모르겠지만

https://manen0122.github.io/norebang/ 보통 이런식으로 링크가 끝나면
https://manen0122.github.io/norebang/(파일이름) 으로 추가해줬어요! 그랬더니 파일을 찾아 가더라고요 ㅎㅎ
비어있으면 index 파일이 readme 파일인 거 같아요(이비유가 맞는 지는 잘 모르겠습니다만..)

**Comment by dongheegy** [comment]
[깃허브 페이지 설정 강의](https://youtu.be/n1wvs7xuUYk?t=6m18s)를 보고 따라하신 후에
https://[깃허브 아이디].github.io/[저장소 이름]/ 으로 접속하면

> 저장소 가장 상위 디렉토리에
> 
> - index.html이 있을 때, index.html 페이지가 나오고(예: [저장소](https://github.com/dongheegy/web1), [페이지](https://dongheegy.github.io/web1)),
> 
> - index.html이 없을 때, readme.md가 있으면 readme.md 페이지가 나오고(예: [저장소](https://github.com/dongheegy/Git-training), [페이지](http://dongheegy.github.io/Git-training)),
> 
> - index.html과 readme.md가 모두 없으면 404 에러페이지가 나옵니다(예: [저장소](https://github.com/dongheegy/Compare-String), [페이지](http://dongheegy.github.io/Compare-String/)).

**Comment by agriengcmk** [comment]
저장소 이름을 꼭 index.html로 해야 하나요?

**Comment by dhchoi82** [comment]
@agriengcmk
저장소 이름은 각자의 고유한 이름을 써야 하고, 각 저장소의 깃허브 페이지 주소로 접속했을 때 기본적으로 보이는 파일의 이름이 readme.md 나 index.html 이라는 내용입니다.
