### ISSUE TITLE
Javascript object HTMLInputElement 에 대한 질문을 하려고합니다!!

### ISSUE THREAD

**Issue by seongdongwon1** [codingeverybody/codingyahac#620]
![error code](https://user-images.githubusercontent.com/49185772/57839521-dd9f0f00-7801-11e9-8e72-f8383ba3247b.png)

안녕하세요!

음 일단 제가 구현하고 싶은 것은,

위와 사진과 같이 사용자가 앞 input box 에 email(id)를 입력을 하고

뒤 input box 는 select box 를 통해서 제가 입력을 해놓은 email(주소) 를 선택하거나, 직접입력을 선택을 하여서 입력을 받습니다.

받은 입력값들을

새로이 변수를 선언을 합니다. ex) let emailValue = inputbox1 + "@"+ inputbox2

그래서 emailValue 를 제가 정한 정규식에 test 를 하고 정규식에 맞다면, 아무 반응도 없고,

test를 통해서 틀렸다면, 빨간 ErrorMessage 를 출력함으로써, 사용자에게 잘못됐음을 알려

주는 것을 구현하고 싶습니다.

그런데, 제가 여기서 질문을 드리고 싶은 것은.

위 사진과 같이 제가 변수를 선언을 하고 더한 변수를 선언을 했습니다.

제가 예상한 값은 ex input box1 = ehddnjs403      @         inputbox2 = naver.com

이렇게 사용자가 입력을 한다면, console.log(emailValue) = ehddnjs403@naver.com

이렇게 나올 것이라고 예상을 했습니다.

그런데, 

![error](https://user-images.githubusercontent.com/49185772/57839892-89e0f580-7802-11e9-810f-17ac5c07abb0.png)

이런 현상이 나오더라구요. 때문에

여러방법으로 시도를 해보았습니다. ( 제가 전에 올렸던 글에 답글을 달아주셔서...... 그것을 보고 )

link[blog][blog.naver.com/ehddnjs403]

여긴 제가 공부한 내용을 적어보는 블로그 인데, 여러방법으로 시도를 해본 글도 적어 보았습니다.

결론은 지금 제가 입력한 값이 console 을 통해서 확인을 할 수 없다는 것입니다.

그렇기 때문에 정규식을 통해서 test 를 진행 할 수가 없습니다.

object HTMLInputElement 에 대한 해결방법을 알려주셔도 좋습니다.

아니면 참고해볼만한 검색어 나 사이트를 알려주시면 감사하겠습니다.

거의 2일동안 계속 혼자 찾아본다고 찾아보고 이해해본다고 이해해보려고 했는데,

많이 어렵습니다...ㅠㅠㅠ

**Comment by davidkwak** [comment]
콘솔로그를 보시면 "오브젝트"@"오브젝트" 가 출력된걸 보실수 있습니다. 
원하시는 결과는 "string"@"string"이 나와야 되는건데 말이죠. 

`emailValue = email1 + @ + email2 `

부분을 `emailValue = email1.value + @ + email2.value`로 바꾸시면 될것 같습니다. 

지금 email1 과 email2는 string 이 아닌 object이기 때문에 발생하는 문제고 object가 뭔지는 객체지향으로 검색하셔서 공부해보세요

**Comment by seongdongwon1** [comment]
알려주신 내용을 안해본 것이 아니여서요...
알려주신 내용으로 .value 값을 각각 붙여서 console을 해보면
아얘 @ 만 출력이 되네요. email.value 값과 eamil2.value 값이 나오지가 않네요.
음... 제가 구현한 코드가 잘못된건가요...??

![123123](https://user-images.githubusercontent.com/49185772/57905952-3e3a5480-78b3-11e9-98f5-04942eba8917.png)

![gdfgdfg](https://user-images.githubusercontent.com/49185772/57905956-42667200-78b3-11e9-960e-4f39d0feb816.png)


위에 사진이 email에 대한 input 과 select 태크이고

밑에 사진이 javascript 내용입니다.....

**Comment by seongdongwon1** [comment]
아아 제가 잘못이해하고있었습니다.... let emailValue 변수를 else 밑으로 넣으니 확인이 가능해졌습니다.
제가 잘못 이해하고 잘못설명해서 많이 답답하셨을텐데 죄송하고,
답변주셔서 감사합니다!!!!

**Comment by znffl** [comment]
해당 이슈를 close 합니다. 추가 궁금한 점이 있으시면 다시 open 부탁드립니다.
