### ISSUE TITLE
안녕하세요. mysql source 질문입니다.

### ISSUE THREAD

**Issue by seongdongwon1** [codingeverybody/codingyahac#621]
안녕하세요. 수고가 많으십니다. 다들..
질문이 있어서 이렇게 다시 또 찾아 뵙게 되었습니다.

mysql 에서 sql 파일을 불러오기 위해 쓰이는 명령문이
source 라고 알고 있으며, 

`mysql> source [sql파일 경로]`

이렇게 명령문으로 알고 있습니다.

![1](https://user-images.githubusercontent.com/49185772/60572871-73dac480-9db1-11e9-8155-38634d96defe.png)
![2](https://user-images.githubusercontent.com/49185772/60572879-7806e200-9db1-11e9-9803-7317e1553e75.png)

sql의 파일을 바탕화면에 넣었고, 바탕화면에 있는 파일의 경로를 저렇게 찾았습니다.

![3](https://user-images.githubusercontent.com/49185772/60572900-83f2a400-9db1-11e9-86f4-f463d8947dce.png)
![4](https://user-images.githubusercontent.com/49185772/60572961-abe20780-9db1-11e9-91cd-9775fceb02d8.png)

mysql을 실행하고 source 명령문을 실행하기 위해

`source [sql 파일경로]`
로 설정하였는데, error 가나왔습니다.
error에 대한 내용을 찾아보니 경로를 지정할때 역슬래시(\) 를 말고 그냥 슬래시(/) 를 사용해야 된다고 하더라구요.

![5](https://user-images.githubusercontent.com/49185772/60572994-b9978d00-9db1-11e9-9c4f-db69f588f4bf.png)

sql 파일을 열수가 없습니다. 어디서 어떻게 무엇이 잘못인지 궁금합니다.

파일의 사용권한을 알아보라는 외국개발자의 조언도 있었는데,
그 문제가 맞다면 어떻게 권한을 확인하고, 해결하는지 궁금합니다.

제가 초보라서 상세하게 알려주시면 정말 감사하겠습니다!!

**Comment by seongdongwon1** [comment]
여러가지 방법으로 시도해보다가 제가 실수 했다는 것을 알게 되었습니다...
메모장에 mysql문을 입력 하고 저장만 하면 되는줄알았는데,
지속적인 검색엔진을 통해서 'mysql source 명령문' 웹사이트에 작성한사람의 의도를 파악하기 위해서
흘려서 읽지 않고, 차근차근 읽어 보았는데요.

다들 이렇게 설명을 하더라구요.

mysql>source [ 'sql'문 의 경로]

sql문 이라는 것을 생각하고, 제가 저장한 형식을 찾아보았는데,

txt 형식이더라구요.

사실상 제가 만든 파일은        sdtv.sql.txt 였던것입니다.

*txt 형식을 모든파일로 변경 후에

저장을 sdtv.sql 으로 바꾸니, 형식이 sql 로 바뀌었고,

다시 sourece [sql 경로] 를 입력하니 제대로 작동합니다.

**Comment by davidkwak** [comment]
늦게봐서 답변은 못달아드렸습니다만 

열심히 조사하시고 스스로 찾아내셨으니 더 오래 기억에 남으실것같습니다 ^^

그리고 결과까지 이렇게 공유해주셨으니 다음에 비슷한 문제로 고통받는 분이 감사할겁니다.

**Comment by znffl** [comment]
안녕하세요. 하기 이슈를 close 합니다. 추가 궁금한 점이 있으시면 다시 open 부탁드려요
