### ISSUE TITLE
예약 web page 제작 관련

### ISSUE THREAD

**Issue by phot0nMan** [codingeverybody/codingyahac#625]
# 해결하고자 하는 문제

웹에서 예약정보를 받아서 특정 핸드폰이나 메일 혹은 카카오톡 메신저로 예약정보를 전송하게 만들고 싶습니다. 

웹페이지는 어느정도 만들었는데, 이후에 받은 정보를 전달할 때 사용해야할 툴(?)을 모르겠습니다. 키워드만 알려주시면 검색을 통해 해결해 보겠습니다.

**Comment by progh2** [comment]
문자나 메일은 [여기](https://www.google.com/search?rlz=1C9BKJA_enKR803KR804&hl=ko&ei=iKxFXdOlCrKJmAWz34PoAQ&q=%EB%8C%80%EB%9F%89+%EB%AC%B8%EC%9E%90+%EC%9D%B4%EB%A9%94%EC%9D%BC+%EB%B0%9C%EC%86%A1+%EC%84%9C%EB%B9%84%EC%8A%A4&oq=%EB%8C%80%EB%9F%89+%EB%AC%B8%EC%9E%90+%EC%9D%B4%EB%A9%94%EC%9D%BC+%EB%B0%9C%EC%86%A1+%EC%84%9C%EB%B9%84%EC%8A%A4&gs_l=mobile-gws-wiz-serp.3...10613.17986..18108...25.0..15.119.3304.39j5......0....1.......0..0j0i67j0i30j0i5i30j33i21j33i160j30i10.uF-gZY0DNNo)와 같이 검색된 회사 등과 계약해서 api를 호출하는 식으로 구현해야 합니다.
대개 건당 과금 형식으로 되어있습니다.

카카오톡도 아래같은 유료 api를 사용하면 가능할 것 같습니다.
https://www.apistore.co.kr/api/apiView.do?service_seq=558

**Comment by phot0nMan** [comment]
디테일한 답변 감사합니다!

알려주신대로 한번 시도해보겠습니다!

김민수 드림

2019. 8. 4. 오전 12:51, Gihun Ham <notifications@github.com> 작성:

**Comment by znffl** [comment]
하기 이슈를 close 합니다.
추가 궁금한 사항이 있으시면 다시 open 부탁드립니다.
