### ISSUE TITLE
QT 참고자료에 관한 질문입니다.

### ISSUE THREAD

**Issue by Geol2** [codingeverybody/codingyahac#630]
안녕하세요.
c++로 개발자로 입문하는 직장인입니다.
MFC는 요즘 사용하는 것 같진 않고..
QT를 써보려고 하는데 공식홈페이지가 영어라 좀 참고하기가 힘들던데
혹시 한글로 된 참고자료 중 아직 볼만한 것이 존재하나요?? 이왕이면 QT 최신버젼으로 볼 수 있는 자료를 추천 받고 싶습니다!!

**Comment by alisol** [comment]
> nana 는 어떠신가요? 

http://nanapro.org/en-us/

> qt와 nana 비교 설명 슬라이드

https://www.slideshare.net/LazyAhasil/c-gui-qt-nana

>게임용으로는. imgui

https://github.com/ocornut/imgui
튜토리얼 (ImGui Tutorial #1 - Checkbox, SliderFloat, SliderInt.
) https://www.youtube.com/watch?v=ZRE4zhotXHo

**Comment by Geol2** [comment]
@alisol 감사합니다 !!! 좋은 참고가 되었습니다.
