### ISSUE TITLE
링크안에 php파일을 지우고 링크를 걸고 싶습니다

### ISSUE THREAD

**Issue by ysyo6511** [codingeverybody/codingyahac#637]
# 해결하고자 하는 문제
카드에 링크를 걸기위해 php를 해제 하였는데 코드가 활성화되지가 않네요 조언 부탁드립니다.

# 코드 혹은 오류
<?php
while($row=mysqli_fetch_array($result)){
             $escaped_title = htmlspecialchars($row['title']);
             $escaped_writer = htmlspecialchars($row['writer']);
             $card = $card."<li><a 
             href=\"board_card.php?id={$row['id']}\">
             ?>

                   <div class="card">
                  </div>  
                        
                  <?php
                  </a></li>";
            }
                  ?>

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Visual studio code

# 시도해본 방법

**Comment by ysyo6511** [comment]
<?php
while($row=mysqli_fetch_array($result)){
             $escaped_title = htmlspecialchars($row['title']);
             $escaped_writer = htmlspecialchars($row['writer']);
             $card = $card."<li><a 
             href=\"board_card.php?id={$row['id']}\">

             <div class="card"><img src="./images/hmm.png" class="card-img-top" alt="...">
                   <div class="card_header_t  pt-0 ml-1 mr-3">
               <?=$escaped_title?>
               </div>
              <div class="card-body_t mt-0 ml-1 mr-1">
              <div class="card_writer">
              <p class="text-muted"><?=$escaped_writer?></p>
              </div>
              <div class="card_footer text-muted">
              <p class="view text-muted">조회수 154회</p>
              </div>
              <div class="card_comment">
              <p class="comment text-muted">댓글 3개</p>
              <p class="view time text-muted">1분 전</p>
              </div>
                  </div>
            </div>  
            
             </a></li>";
            }
            
                  ?>

**Comment by ysyo6511** [comment]
<?php
while($row=mysqli_fetch_array($result)){
             $escaped_title = htmlspecialchars($row['title']);
             $escaped_writer = htmlspecialchars($row['writer']);
             $card = $card."<li><a 
             href=\"board_card.php?id={$row['id']}\">

             <div class="card">
            </div>  
            
             </a></li>";
            }
            
                  ?>

**Comment by ysyo6511** [comment]
<?php
while($row=mysqli_fetch_array($result)){
             $escaped_title = htmlspecialchars($row['title']);
             $escaped_writer = htmlspecialchars($row['writer']);
             $card = $card."<li><a 
             href=\"board_card.php?id={$row['id']}\">

             <div class="card">
            </div>  
            
             </a></li>";
            }
            
                  ?>

**Comment by ysyo6511** [comment]
<?php
while($row=mysqli_fetch_array($result)){
           <a href=\"board_card.php?id={$row['id']}\">
?>
             <div class="card">
            </div>  
<?php
             </a></li>";
            }
 ?>

**Comment by ysyo6511** [comment]
<?php while($row=mysqli_fetch_array($result)){ <a href=\"board_card.php?id={$row['id']}\">?>
             <div class="card"></div>  <?php</a></li>"; }    ?>

**Comment by ysyo6511** [comment]
코드가 자꾸 짤리네요...

**Comment by Hatser** [comment]
\`\`\`php

(php 코드)

\`\`\`

형태로 작성하시면

코드를 깔끔하게 작성하실 수 있습니다.
좀 더 많은 부분을 보여주시면 확실하게 알려드릴 수 있어요.

먼저 `div`에 링크를 걸고자 한다면
```html
<a href="링크 경로">
    <div class="card>
        내용
    </div>
</a>
```
같은 형태로 만들 수 있고, div내부의 내용을 php에서 그리고자 한다면,
```php
<a href="링크 경로">
    <div class="card">
        <?php
            (php 코드)
        ?>
    </div>
</a>
```
처럼 작성하시면 됩니다.
