### ISSUE TITLE
<p> 태그 관련하여

### ISSUE THREAD

**Issue by manen0122** [codingeverybody/codingyahac#64]
<p>태그를 사용하면 서 느낀 건데, 이걸 쓰고 문단을 쓰다가 너무 글이 길어져서 코딩하기가 불편 할 때

<.p>어쩌구저쩌구이리쿵저리쿵할말은` 참 많고 하늘은 맑고 강산은 푸르고<./p>

<.p>어쩌구저쩌구 이리쿵저리쿵 말읗 `ㄹ43ㅕㄱ8934783294<./p>

이런 식으로 줄을 바꿔서 코딩한다면  나중에 다른 코드를 사용할 때 문제가 되는 부분은 없나요?  여기 입력이 안되서 사이에 한 줄 넣었지만 원래는 한 줄만 바꿔요 ....ㅠㅠ

**Comment by dongheegy** [comment]
적으신 코드
>```html
><p>어쩌구저쩌구이리쿵저리쿵할말은` 참 많고 하늘은 맑고 강산은 푸르고</p>
><p>어쩌구저쩌구 이리쿵저리쿵 말읗 `ㄹ43ㅕㄱ8934783294</p>
>```
를 html 파일로 저장해서 웹브라우저로 열어보면
![image](https://user-images.githubusercontent.com/13765815/34642764-f6932964-f35b-11e7-9382-a17208a1c92b.png)
이렇게 줄이 바뀌어서 표시됩니다.

[줄바꿈에 대한 생활코딩의 강의](https://opentutorials.org/course/3084/18403)를 보시면 p 태그는 문단의 의미, br 태그는 의미없는 단순한 줄바꿈이라는 것을 알 수 있습니다. 그러기에 단순한 줄바꿈을 의도하신 거라면 br 태그를 이용해서 아래와 같이 처리하시는 것이 좋다고 생각합니다.
> ```html
> <p>어쩌구저쩌구이리쿵저리쿵할말은` 참 많고 하늘은 맑고 강산은 푸르고<br>
> 어쩌구저쩌구 이리쿵저리쿵 말읗 `ㄹ43ㅕㄱ8934783294</p>
> ```
![image](https://user-images.githubusercontent.com/13765815/34642794-b5252d3c-f35c-11e7-8da4-c42a8031176f.png)

혹시 줄바꿈을 의도하신 게 아니고, 단순히 코드 편집에서의 편리성을 위한 거라면 p 태그나 br 태그를 중간에 넣지 않고, 소스코드에서 단순히 줄을 바꾸시면 됩니다. html 소스코드에서 스페이스나 엔터는 여러 개가 입력되든, 하나만 입력되든 상관 없이 웹브라우저에서는 공백문자 1칸으로 처리됩니다.
> ```html
> <p>어쩌구저쩌구이리쿵저리쿵할말은` 참 많고 하늘은 맑고 강산은 푸르고
> 어쩌구저쩌구 이리쿵저리쿵 말읗 `ㄹ43ㅕㄱ8934783294</p>
> ```
![image](https://user-images.githubusercontent.com/13765815/34642843-6d322100-f35d-11e7-9e9a-e7adca9ef497.png)

**Comment by blackdew** [comment]
html 태그를 활용하실 때에는 '모양'보다는 텍스트의 '의미'에 중점을 두시고 태그를 사용하시면 좋습니다. 
만약에 '의미'상으로 하나의 블럭으로 묶여 있는게 좋은 텍스트라면 하나의 태그로 묶고, 
'모양'은 css에서 처리하시는 것을 권장드립니다. 

그것이 html에서 css가 파생되어 나온 이유이기도 하니까요. :)
