### ISSUE TITLE
저도 모르게 2일차만에 다완료하고 css진행중입니다 상관없나요???

### ISSUE THREAD

**Issue by kangminkang** [codingeverybody/codingyahac#641]
# 해결하고자 하는 문제

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by kangminkang** [comment]
상관없을까요??

**Comment by egoing** [comment]
상관 없을 뿐 아니라 잘 하셨습니다. 

한가지 걱정되는 것은 너무 진도를 고속으로 나가면 나중에 무엇인가를 만들어보려고 할 때 막막한 무기력증을 느낄 수 있습니다. 

머리속이 더 복잡해지기 전에 프로젝트를 시작해보시면 어떨까 합니다.
