### ISSUE TITLE
안드로이드 API 버전에 따른 AVD 화면 출력이 달라지는 현상

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#642]
# 해결하고자 하는 문제

안녕하세요? 개인 프로젝트로 안드로이드 앱을 만들고 있습니다. 
AVD의 Nexus 5X API 28로 테스트를 하고 있었는데 어느 날 API 29로 테스트를 해보니 화면 크기가 달라지면서 뷰들이 일부 가려지기도 하는 현상을 발견했습니다.
실제 안드로이드 개발자들이 모든 기기에서 테스트를 하기는 쉽지 않을 것 같은데 이 문제에 어떻게 대처하는지 궁금합니다.
감사합니다!

# 환경
안드로이드 스튜디오

**Comment by studroid** [comment]
제가 아는 선에서는, manifest에 targetSdkVersion을 지정하면 상위 버전에서 호환성을 유지할 수 있는 것으로 기억합니다 :)

아래 링크를 참고하여 한번 적용해보시고, 원하시는 답이 아닌 경우에는 한번 더 알려주세요!

https://developer.android.com/distribute/best-practices/develop/target-sdk?hl=ko

https://dreamaz.tistory.com/78

**Comment by kammaii** [comment]
> 제가 아는 선에서는, manifest에 targetSdkVersion을 지정하면 상위 버전에서 호환성을 유지할 수 있는 것으로 기억합니다 :)
> 
> 아래 링크를 참고하여 한번 적용해보시고, 원하시는 답이 아닌 경우에는 한번 더 알려주세요!
> 
> https://developer.android.com/distribute/best-practices/develop/target-sdk?hl=ko
> 
> https://dreamaz.tistory.com/78

가르쳐주신대로 targetSdkVersion에 대해 좀 찾아봤는데 제 targetSdkVersion은 26으로 되어 있었습니다. 그러면 제가 테스트한 AVD 버전이 28, 29이었으니까  모두 26버전 기준으로 출력이 되어야 하는  것이 맞지 않나요? 흠... 화면 크기도 비슷한데 왜 뷰들의 위치가 다르게 나오는지 모르겠습니다. ㅠ
혹시 뷰들의 margin값 단위를 dp로 했는데 이 것이 문제가 될 수 있을까요?

![image](https://user-images.githubusercontent.com/43202563/62353066-e915f280-b533-11e9-9069-c438e28d9578.png)
<왼쪽 API 28, 오른쪽 API 29>

**Comment by studroid** [comment]
실제로 달라지는 화면 크기에 따라 일정한 비율로 뷰의 크기를 유지하려면, dp가 아닌 weight를 쓰셔야 하지 않을까 싶습니다. android layout weight 등의 키워드로 검색해보시면 여러 자료를 찾으실 수 있습니다.

참고로 아래 링크도 하나 보내드립니다 :)

https://yoo-hyeok.tistory.com/56

**Comment by kammaii** [comment]
> 실제로 달라지는 화면 크기에 따라 일정한 비율로 뷰의 크기를 유지하려면, dp가 아닌 weight를 쓰셔야 하지 않을까 싶습니다. android layout weight 등의 키워드로 검색해보시면 여러 자료를 찾으실 수 있습니다.
> 
> 참고로 아래 링크도 하나 보내드립니다 :)
> 
> https://yoo-hyeok.tistory.com/56

화면을 구성하려면 weight뿐 아니라 dp 그리고 다른 여러가지 기능들을 사용해야 할 것 같습니다. 

그런데 위 그림의 문제는 AVD 버전보다 낮은 targetSdkVersion을 사용했음에도 화면이 많이 다르게 출력된다는 것입니다. 
게다가 dp는 기기의 화면 크기에 맞게 자동으로 비율을 조절해주는 단위로 알고 있습니다. 
하지만 제가 테스트 한 'Nexus 5 API29'와 'Nexus 5X API 28'은 심지어 화면 사이즈도 거의 비슷한데  dp단위로 margin과 크기를 설정한 뷰들의 차이가 꽤 있습니다. (사진의 아래 두 버튼은 constraint layout으로 parent 하단에 위치를 지정하여 아래로 밀리지 않고 고정되어 무시하셔도 됩니다.)

혹시나 하여 제 build.gradle 코드 첨부드립니다.
```
android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "net.awesomekorean.baguni"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.0'
    implementation 'com.android.support:design:26.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
