### ISSUE TITLE
디자이너 고용에 대한 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#643]
# 해결하고자 하는 문제

안녕하세요? 개인 프로젝트로 안드로이드 앱을 만들고 있습니다.
이번 앱은 좀 보기좋은 디자인으로 만들어보고 싶고
마침 제가 태국에 거주하고 있어 저렴한 인건비를 활용해보고자 
현지 대학생 or 초급 디자이너를 아르바이트로 고용해 볼 계획을 가지고 있습니다.
하지만 이런 디자이너와의 협업을 전혀 경험해본 적이 없어서 어떤 일을 어떻게 부탁해야 할 지 막막합니다.
무엇을 모르는지도 잘 인지하지 못하는 상황에서 질문하기도 어려운 것 같은데 우선 제가 궁금한 것은

1. 앱 전체 디자인을 맡기려면 UI/UX 디자이너를 고용하는 것이 맞나요?
2. 만약에 앱 아이콘 디자인이나 앱에서 필요한 그림 등도 UI/UX 디자이너가 해 줄 수 있나요? 아니면 다른 전공(?)의 디자이너를 따로 찾아야 하나요?
3. UI/UX 디자이너는 결과물을 포토샵 같은 그림파일로 제공하나요? 아니면 안드로이드 스튜디오의 xml코드도 작성해주나요?
4. 앱 디자인에 걸리는 시간을 어느 정도로 예상할 수 있을까요?
5. 디자이너가 필요한 기간이 확실하지 않을 때 계약기간은 어떻게 정하나요?
6. 제가 코딩 속도가 아주 느려서 대부분의 기능을 거의 다 만든 후에 디자이너를 찾으려고 하는데 혹시 실제 회사에서도 '코딩 후 디자인'의 순서로 일을 진행하나요?
7. 디자인을 완성하더라도 앱 출시 전/후로 수정사항이 분명히 발생할텐데 디자이너가 A/S(?)도 해주는 건가요? 아니면 다시 계약을 해야 하나요?

워낙 이쪽 방면에 문외한이라 질문이 좀 이상할 것 같은데 양해 부탁드립니다. 

감사합니다!!

# 환경
안드로이드 스튜디오

**Comment by studroid** [comment]
1. 앱 전체 디자인을 맡기려면 UI/UX 디자이너를 고용하는 것이 맞나요?

2. 만약에 앱 아이콘 디자인이나 앱에서 필요한 그림 등도 UI/UX 디자이너가 해 줄 수 있나요? 아니면 다른 전공(?)의 디자이너를 따로 찾아야 하나요?

3. UI/UX 디자이너는 결과물을 포토샵 같은 그림파일로 제공하나요? 아니면 안드로이드 스튜디오의 xml코드도 작성해주나요?

4. 앱 디자인에 걸리는 시간을 어느 정도로 예상할 수 있을까요?

5. 디자이너가 필요한 기간이 확실하지 않을 때 계약기간은 어떻게 정하나요?

6. 제가 코딩 속도가 아주 느려서 대부분의 기능을 거의 다 만든 후에 디자이너를 찾으려고 하는데 혹시 실제 회사에서도 '코딩 후 디자인'의 순서로 일을 진행하나요?

7. 디자인을 완성하더라도 앱 출시 전/후로 수정사항이 분명히 발생할텐데 디자이너가 A/S(?)도 해주는 건가요? 아니면 다시 계약을 해야 하나요?

**Comment by studroid** [comment]
이 부분은 개인의 성향에 따라 매우 방향이 달라지고, 정답이 없기 때문에 제 의견으로 말씀을 드려보겠습니다.

제 경우 안드로이드 앱 개발을 처음 시작할 때 만든 앱은 배터리 상태를 확인하는 앱이었구요, 단순히 검은색 배경에 흰 글씨로 현재 배터리 잔량(%), 배터리 종류, 충전 상태, 예상 사용 시간 등을 표시해주는 기능만을 넣었습니다(이때는 안드로이드 기기의 메인 화면에서 배터리 잔량을 %로 표시해주지 않는 경우가 많았음).

이걸 가지고 제 주변에서 디자인을 하는 친구들 혹은 지인들에게 보여주면서 배터리 잔량에 따라 모습이 변하는, 캐릭터 활용 배터리 체커를 만들었고, 여기에서 인연을 맺은 디자이너분들과 아직까지 같이 작업을 하고 있습니다 :)


디자이너와의 협업 경험이 없으시다면, 아마 저 시절의 제 상황과 비슷하실 듯합니다. 이때는 가장 이상적으로는, 고용의 형태보다는 함께 문제를 겪고 해결하면서 배워나갈 분을 찾고, 계속 개선해나가도록 하는 것이 좋지 않을까 싶습니다.

다만 지금 진행하시는 프로젝트가 스스로 개발 스킬을 쌓아나가기 위해서만 진행하는 것이라면, Upwork 같은 프리랜서 구인 사이트 등에서 태국 기반 프리랜서를 찾아보시는 것도 방법이 될 수 있겠습니다.

[Upwork에서 태국 기반 디자이너를 찾으면 이렇게 나옵니다.](https://www.upwork.com/ab/profiles/search/?c=design-creative&loc=thailand)

이때 프로젝트가 구체적일수록 디자이너가 투입해야 하는 시간이 줄어들고 불확실성이 적어지기 때문에, 일반적으로 필요 예산이 적어지고, 프로젝트가 모호한 상태라면 그 반대로 예산이 더 많이 필요해집니다.


위 내용은 참고로 읽어주시고, 질문에 대해서 제 나름의 답을 드려보자면,

> 1. 앱 전체 디자인을 맡기려면 UI/UX 디자이너를 고용하는 것이 맞나요?
-> 저와 같은 부류의 개발자는 아주 단순한 UI를 가진 앱이 아니라면 전체 디자인을 거의 하지 못합니다. 그래서 함께 할 디자이너를 찾거나, 위에서 말씀드린대로 필요한 경우 고용을 할 수도 있겠습니다. 다만 어느 정도 디자인 도구를 사용하실 수 있다면, [이런 사이트](https://thenounproject.com/)나 [저런 사이트](https://icons8.com/) 등에서 필요한 리소스를 찾아 잘 배치해주면 그럭저럭 볼만한 앱이 나올 수도 있습니다.

> 2. 만약에 앱 아이콘 디자인이나 앱에서 필요한 그림 등도 UI/UX 디자이너가 해 줄 수 있나요? 아니면 다른 전공(?)의 디자이너를 따로 찾아야 하나요?
-> 일반적으로 해당 작업은 UI 디자이너가 진행하지만, 아이콘이나 그림이 매우 특별한 경우에는 별도로 디자이너가 필요할 수 있습니다. 예를 들어, 게임 캐릭터 등을 만든다면 캐릭터만을 디자인하는 사람이 따로 있어야 할 확률이 높겠죠?

> 3. UI/UX 디자이너는 결과물을 포토샵 같은 그림파일로 제공하나요? 아니면 안드로이드 스튜디오의 xml코드도 작성해주나요?
PNG, JPG 등의 리소스를 만들어 제공하는 것이 일반적이고, 대부분 psd 등 소스 파일을 함께 제공합니다. xml 코드 등을 작성하는 경우는 매우 드뭅니다.

> 4. 앱 디자인에 걸리는 시간을 어느 정도로 예상할 수 있을까요?
이는 해당 앱이 어떤 것이냐에 따라 아주 많이 달라집니다. 최소 하루 이하, 최대 6개월 이상이 되겠습니다. 

> 5. 디자이너가 필요한 기간이 확실하지 않을 때 계약기간은 어떻게 정하나요?
고용으로 한다면, '앱이 완성될 때까지 특정 기간 동안 얼마' 정도로 지속적으로 고용하는 형태가 되지 않을까 싶습니다. 혹은 대략적인 앱의 기획과 설명이 있다면, 디자이너에게 제시해달라고 말씀해주셔도 되겠습니다.

> 6. 제가 코딩 속도가 아주 느려서 대부분의 기능을 거의 다 만든 후에 디자이너를 찾으려고 하는데 혹시 실제 회사에서도 '코딩 후 디자인'의 순서로 일을 진행하나요?
회사 혹은 팀 단위로 일을 진행할 때에는, 핵심 기능은 먼저 개발하고(연구라고 보는 편이 좋겠습니다) 이에 맞춰 전체적인 시나리오를 기획하며, 일반적으로 디자인이 개발보다 먼저 완료됩니다.
다만 작은 단위(ex. 한 화면마다)로 디자인을 하고 개발을 하다가 수정하기도 하고, 기획 - 디자인 - 개발처럼 디자인이 완료되면 그때서 개발을 들어가기도 합니다(후자의 방식은 사라지는 추세).
마지막에 결국 레이아웃을 맞춰야 하기 때문에, 개발이 완료되고 디자인이 완료된다는 개념은 사실상 일반적인 앱 개발 상황에서는 없다고 봐야겠죠?

> 7. 디자인을 완성하더라도 앱 출시 전/후로 수정사항이 분명히 발생할텐데 디자이너가 A/S(?)도 해주는 건가요? 아니면 다시 계약을 해야 하나요?
고용의 경우 계약에 따라 달라집니다. 이때 A/S는 건당 지불이 될 수도 있고, 시간당 지불이 될 수도 있으며, 특정 기 동안에는 무료일 수도 있겠습니다. 혹은 디자이너가 완료 전후로 사라지는 경우도 있을 수 있겠죠. 그렇기 때문에 업무가 불확실할 때일수록 고용의 형태로 진행하기는 어려워지는 경향이 있습니다.


이것저것 생각나는대로 써보았습니다. 도움이 되시면 좋겠네요! :)

**Comment by kammaii** [comment]
와! 이렇게 자세히 설명해주셔서 감사합니다! 정말 많은 도움이 되었습니다! :)
