### ISSUE TITLE
안드로이드 스튜디오 오디오 재생 관련 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#644]
# 해결하고자 하는 문제

안녕하세요? 아래와 같이 오디오를 재생하는 메소드를 만들었습니다.
우선 string에 직접 파일 이름을 지정하여 테스트를 했는데
mediaPlayer 에서 Null이 발생하는 이유를 잘 모르겠습니다.

감사합니다!

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.start()' on a null object reference
```

# 코드 혹은 오류
```
  public void audioPlay() {

        mediaPlayer = new MediaPlayer();

        String string = "R.raw.con0";

        Uri currentPlay = Uri.parse(string);

        mediaPlayer = MediaPlayer.create(getApplicationContext(), currentPlay);

        mediaPlayer.start();


    }
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by Hatser** [comment]
Docs에서 찾아보니 [`create`](https://developer.android.com/reference/android/media/MediaPlayer.html#create(android.content.Context,%2520android.net.Uri,%2520android.view.SurfaceHolder,%2520android.media.AudioAttributes,%2520int)) 수행 중 실패하면 null이 반환된다고 합니다.

```java
  public void audioPlay() {
        Uri currentPlay = Uri.parse("android.resource://"+getPackageName()+"/" + R.raw.con0);
        
        mediaPlayer = MediaPlayer.create(getApplicationContext(), currentPlay);
        /** 또는
        mediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.con0);
        도 시도해보세요 **/

        mediaPlayer.start();
    }
```

매개변수로 들어가는 값이 잘못돼 실패하면서 null이 반환된 것 같습니다.

**Comment by kammaii** [comment]
> Docs에서 찾아보니 [`create`](https://developer.android.com/reference/android/media/MediaPlayer.html#create(android.content.Context,%2520android.net.Uri,%2520android.view.SurfaceHolder,%2520android.media.AudioAttributes,%2520int)) 수행 중 실패하면 null이 반환된다고 합니다.
> 
> ```java
>   public void audioPlay() {
>         Uri currentPlay = Uri.parse("android.resource://"+getPackageName()+"/" + R.raw.con0);
>         
>         mediaPlayer = MediaPlayer.create(getApplicationContext(), currentPlay);
>         /** 또는
>         mediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.con0);
>         도 시도해보세요 **/
> 
>         mediaPlayer.start();
>     }
> ```
> 
> 매개변수로 들어가는 값이 잘못돼 실패하면서 null이 반환된 것 같습니다.

답변해 주신 부분 중 /** ... **/ 부분처럼 직접 파일 이름을 입력하면 재생이 잘 됩니다. 하지만 오디오 파일명을 매개변수 'currentPlay'로 받아서 하려고 하면 계속 오류가 납니다.

**Comment by studroid** [comment]
R.raw.con0는 해당 프로젝트에 직접 넣으신 리소스일 텐데, 이는 Uri.parse로 가져오는 것이 아니라 프로젝트의 리소스에서 해당 파일을 읽어오는 함수를 사용하셔야 합니다.

아래 링크를 참고하여 진행해보고 알려주세요!

아마 `Uri currentPlay = Uri.parse(string);` 부분을 `int currentPlay = getResources().getIdentifier("con0", "raw", getPackageName());`
로 바꾸면 되지 않을까 싶습니다.

https://stackoverflow.com/a/19093447

**Comment by kammaii** [comment]
> R.raw.con0는 해당 프로젝트에 직접 넣으신 리소스일 텐데, 이는 Uri.parse로 가져오는 것이 아니라 프로젝트의 리소스에서 해당 파일을 읽어오는 함수를 사용하셔야 합니다.
> 
> 아래 링크를 참고하여 진행해보고 알려주세요!
> 
> 아마 `Uri currentPlay = Uri.parse(string);` 부분을 `int currentPlay = getResources().getIdentifier("con0", "raw", getPackageName());`
> 로 바꾸면 되지 않을까 싶습니다.
> 
> https://stackoverflow.com/a/19093447

잘 작동이 됩니다! 감사합니다! ^^ 👍
