### ISSUE TITLE
안드로이드스튜디오에서 오디오 파일 이름을 한글로 할 수 있나요?

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#645]
# 해결하고자 하는 문제

안녕하세요?

제목과 같이 파일 이름이 한글인 오디오를 안드로이드 스튜디오에서 재생하고 싶습니다.
안드로이드스튜디오에서는 한글 파일 이름이 허용되지 않는 것 같은데
혹시 다른 방법이 있을까요?

```
C:\baguni\app\src\main\res\raw\ㄱ.mp3: Error: 'ㄱ' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

감사합니다.

# 환경
안드로이드 스튜디오

**Comment by Hatser** [comment]
안드로이드에서는 컴파일하는 과정에서 실행 코드부를 제외한 나머지 파일들을 `컴파일된 리소스`로 변환합니다.

이 과정에서 리소스들이 각자의 `ID`를 가지면서 R.java 파일에 리소스들의 ID가 적힙니다.
레이아웃파일 내부의 요소들도 마찬가지지요.

ID가 파일의 이름을 따라서 가지기때문에, 기본적으로 JAVA의 [`식별자 규칙`](https://docs.oracle.com/javase/specs/jls/se12/html/jls-3.html#jls-3.8)과, 거기에 엄격함을 더해 `_`를 제외한 다른 특수문자와 대문자를 사용하지 못하도록 한 것입니다.

리소스 파일을 사용하시려면 소문자나 `_`로 시작하고, `소문자`, `숫자`, `_`로만 이루어진 파일명을 사용하셔야 합니다.

**Comment by kammaii** [comment]
> APK를 컴파일하는 과정에서 실행 코드부를 제외한 나머지 파일들을 `컴파일된 리소스`로 변환합니다.
> [참조](https://developer.android.com/studio/build/index.html)
> 
> 이 과정에서 리소스들이 각자의 `ID`를 가지면서 R.java 파일에 리소스들의 ID가 적힙니다.
> 레이아웃파일 내부의 요소들도 마찬가지지요.
> 
> ID를 참조할 수 있는 속성명(`R.id.파일명`)이 파일의 이름을 따라서 가지기때문에, 기본적으로 JAVA의 [`식별자 규칙`](https://docs.oracle.com/javase/specs/jls/se12/html/jls-3.html#jls-3.8)과, 거기에 엄격함을 더해 `_`를 제외한 다른 특수문자와 대문자를 사용하지 못하도록 한 것입니다.
> 
> 리소스 파일을 사용하시려면 소문자나 `_`로 시작하고, `소문자`, `숫자`, `_`로만 이루어진 파일명을 사용하셔야 합니다.

역시 불가능하군요 ㅠ 답변 감사합니다!!
