### ISSUE TITLE
진로를 어떻게 정할지 감을 못잡겠습니다.

### ISSUE THREAD

**Issue by XCIXI** [codingeverybody/codingyahac#646]
정보 보안쪽에 관심이 많고 흥미가 있는 터라 이쪽 계열로 가기 위해 자격증이나 정보를 모아보는 것

외 가상 머신을 이용한 랜섬웨어 테스트를 비롯 패킷 캡쳐 프로그램인 Wire Shark를 이용하여 비밀

번호 평문  전송 & 사이트의 수상한 점을 찾아내어 해당 사이트 관리자에게 문의를 하여 이에 관련한 

답변을 받으면서 미약하게 나마 도움을 드린적이 있지만 마음속 한구석은 무겁기만 합니다.

정식으로 배운 기술이 아닌 구글이나 유튜브를 통해 배운 기술이 전부이며 이 기술을 사용한다고

하더라도 정식으로 배운 분들에게 밀릴수도 있고 실력을 인정받지 못하면 생계가 걱정되며 언어

(C언어 C++)등을 제대로 소화하지 못하면 도태되고 낙오될까봐 정보 보안쪽이 아닌 다른 쪽으로

눈을 돌리고 있는 상황인데 어찌하면 좋을까요...

**Comment by egoing** [comment]
@babomose 님께서 다른 글에 남기신 진로에 대한 글을 링크 드려봅니다.  
https://github.com/codingeverybody/codingyahac/issues/78

추가적인 질문을 주시면 더 자세한 상담을 받으실 수 있을 것 같습니다.

**Comment by babomose** [comment]
안녕하세요.

일단, 정보보안 학사 전공을 했다고해서 모두 기술이 뛰어난 것은 아닙니다.

눈에 보이지 않는 대상과 비교하며, 좌절하시지 않아도됩니다.

오히려 제 경험적으로 정보보안을 전공하지 않고, 컴퓨터를 좋아하시는 분들이 더 기술적으로 뛰어난 경우가 많았습니다.

현재 정보보안 산업은 예전보다 성장해서 다양한 직무가 있습니다.

어떤 일에 관심이가고 하고 싶은지 , egoing님이 답변 주신 링크를 한번 읽고 고민해 보시면 좋을 것 같습니다.

고민 후 궁금한 점이 있다면, 또 알려주세요. :-)

**Comment by XCIXI** [comment]
> 
> 
> 안녕하세요.
> 
> 일단, 정보보안 학사 전공을 했다고해서 모두 기술이 뛰어난 것은 아닙니다.
> 
> 눈에 보이지 않는 대상과 비교하며, 좌절하시지 않아도됩니다.
> 
> 오히려 제 경험적으로 정보보안을 전공하지 않고, 컴퓨터를 좋아하시는 분들이 더 기술적으로 뛰어난 경우가 많았습니다.
> 
> 현재 정보보안 산업은 예전보다 성장해서 다양한 직무가 있습니다.
> 
> 어떤 일에 관심이가고 하고 싶은지 , egoing님이 답변 주신 링크를 한번 읽고 고민해 보시면 좋을 것 같습니다.
> 
> 고민 후 궁금한 점이 있다면, 또 알려주세요. :-)

정보보안의 경우 학사 전공이 아님을 밝힙니다.

컴퓨터 공학과(2년)을 전공하였으며 정보 보안의 경우 전공 수업을 들었기에 다른 사람보다 기술이

밀리고 걱정을 하였는데 답변을 보니 마음이 놓이네요.
