### ISSUE TITLE
Motion estimation (skeleton)

### ISSUE THREAD

**Issue by uyeonH** [codingeverybody/codingyahac#647]
진행해보고싶은 프로젝트인데 감이 안잡혀서 질문 올립니다..! 사람 움직임을 스켈레톤으로 표현해서 피쳐로 저장이 가능한가요? 영상에서 피쳐를 잡는것처럼 동영상 프레임을 뽑아와서 피쳐?를 각각 계산하여 움직임만 스켈레톤으로 재현할 수 잇을까요?

**Comment by studroid** [comment]
[이런 것](https://www.youtube.com/watch?v=XLO3Zz0R8kE)과 비슷한 뭔가를 하고 싶으신 거라면, 아마 3D 스캐너가 필요하지 않을까 싶습니다만...!

카메라 여러 대를 사용해서 각각의 물체를 트래킹하고, 해당 정보를 결합한다면 스켈레톤으로 재현이 가능할 것 같습니다. 이 경우 시작을 위해 [OpenCV](https://opencv.org/)라는 이미지 프로세싱 라이브러리를 사용해보시면 도움이 될 것 같습니다만, 쉬운 작업은 아닐 듯하니 작은 것부터 완성해나가는 것을 추천드립니다!

**Comment by uyeonH** [comment]
@studroid OpenCV는 공부해보았고 기초적인 것만 아는 상태입니다. 저는 사람이 카메라 정면을 바라본 상태에서 2d 상에서 해보고싶었던거에요..! 어쨌든 기초적인 것부터 더 찾아봐야겠습니다. 답변 감사드려요!

**Comment by studroid** [comment]
아하 그럼 [이 영상](https://www.youtube.com/watch?v=OfDdNv-bMBo)처럼 트래킹을 하는 걸 구현하려는 것이군요! 아마 영상에서처럼 손, 손목, 팔꿈치, 어깨 등을 포인트로 잡아 트래킹을 해야 할 것이고, 영상에서 프레임을 가져와 처리해야 할 듯한데, 조금이나마 참고하실 수 있는 사이트도 전달드립니다. (공 트래킹)

https://www.pyimagesearch.com/2015/09/21/opencv-track-object-movement/

작게나마 도움이 되시길..!

**Comment by uyeonH** [comment]
@studroid  감사합니다😊😊👍
