### ISSUE TITLE
스마트양식장을 아두이노로 diy구축을해보려고합니다

### ISSUE THREAD

**Issue by broshin** [codingeverybody/codingyahac#648]
안녕하세요 현재 새우양식장을 준비중인 36세 청년입니다. 양식장을 아두이노를 활용해 노동력을 절감시키고 데이터 축척으로 더좋은 생육시스템을 개발하고싶은대 저는 it비전공자라서 무엇부터 어떻게 준비해야하는지 궁금합니다. Iot 에 도움 될만한 정보좀 부탁드립니다

**Comment by egoing** [comment]
관련된 조력자분들을 링크 걸어드렸습니다. 

broshin님께서 현재 어떤 상태인지 좀 더 자세히 알려주시면 더 섬세한 도움을 얻을 수 있을 것 같습니다.

**Comment by happydeveloper** [comment]
- 아두이노를 이용해서 만들고자 하는 시스템의 기능을 먼저 정의하시면 좋을 것 같습니다. 
예를 들어 노동력을 줄이고 데이타를 축척해서 더 좋은 생육시스템을 개발하고 싶다는 요구사항을 더 구체화하면 기능단위로 조깨보시면 좋을 것 같아요.

예를 들면
- 온도/습도 데이타를 수집
- 물온도 상승할시 알람 기능
- 스케쥴링 단위로 먹이 주기 기능 
- 원격지에서 수도밸브 제어 

그리고 MIT 미디어랩에서 하는 오픈팜 프로젝트도 참고하시면 좋을 것 같습니다.

https://www.media.mit.edu/posts/build-a-food-computer/

**Comment by studroid** [comment]
우선 아두이노를 활용하여 각종 센서를 활용하는 프로젝트를 진행하는 것으로 시작해보시면 어떨까 싶습니다 :)

그러다 보면 어떤 경우에 어떤 센서를 써야 하는지, 또 어떤 것들을 제어해야 하는지 감을 잡으실 수 있을 듯합니다.

이에 대해서는 아주 정리가 잘 되어 있는, [코코아팹이라는 사이트에서 초급 에제](https://kocoafab.cc/tutorial/all?level=1&page=0)를 만들어보는 걸로 시작해보시는 것도 좋을 것 같네요!

양식장에서 어떤 것들을 측정하고 제어해야 할지는 잘 모르지만, 습도로 뭔가를 하실 계획이 있으시다면 [이 예제](https://kocoafab.cc/tutorial/view/111)를 따라 만들어보세요! :)

**Comment by broshin** [comment]
오~ 답장들 감사드려요♡♡

2019년 8월 1일 (목) 오후 10:21, studroid <notifications@github.com>님이 작성:
