### ISSUE TITLE
웹 호스팅 서비스

### ISSUE THREAD

**Issue by seomingyu11** [codingeverybody/codingyahac#649]
# 해결하고자 하는 문제
웹 페이지를 소스코드 공개해서 호스팅 진행하여도 상관 없을까요?

# 환경
WIndows 10 Pro / HTML, CSS, JAVASCRIPT

# 시도해본 방법
현재 파이어베이스에서 호스팅을 돌리고 있는데...
파이어베이스는 DB쪽에 최적화 되어 있으니깐, 다른 서비스로 옮기고 싶은데,
추천해 줄 만한 웹 호스팅 서비스가 없나요?

무료로 사용할 수 있으면서, 괜찮은 서비스 추천해 주세요!!

**Comment by Hatser** [comment]
HTML, CSS, JAVASCRIPT는 서버에서 한 번 전송하면 수시로 내용이 바뀌지 않아도 되는 정적 파일입니다.

Github에서 저장소를 만들어 웹 페이지를 띄울 수 있어요.

마침 생활코딩에 강의가 있으니 참고하시면 좋을 것 같습니다.

[링크](https://opentutorials.org/course/3084/18891)

**Comment by seomingyu11** [comment]
그러면, 오픈코드로 공개하여도, 보안 쪽애는 상관 없겠죠?

**Comment by Hatser** [comment]
> 그러면 나중에 인터넷 게시판 같은 서비스를 만들려고 하는데, 그때도 Github를 이용해서 웹호스팅을 할 수 있나요?
> 
> 그러면, 오픈코드로 공개하여도, 보안 쪽애는 상관 없겠죠?

Github는 정적파일 호스팅만 가능해요.

인터넷 게시판처럼 서버를 직접 작성해서 운영하고 싶으시다면,
cafe24나 Google Cloud Flatform같은 서버 호스팅을 사용하셔야 합니다.

아무래도 공부 목적이시니 저렴한 호스팅업체가 필요하실겁니다.

구글 클라우드 플랫폼같은 경우는 무료로 사용해볼 수 있다고도 하고,
DigitalOcean같은 경우에는 추천 회원가입 등으로 일정 크레딧을 무료로 받을 수 있습니다.

잘 찾아보시고 선택하시면 되겠어요.

**Comment by alisol** [comment]
https://infinityfree.net

dothome.co.kr


둘 다 무료로 사용할 수 있고 좋아요.  닷홈은 한국에서 운영하는 곳이고, 위에 것은 외국에서 운영합니다. 둘다 ftp로 파일 올릴 수 있어서 편합니다.
