### ISSUE TITLE
Issues 답변 권한에 대해

### ISSUE THREAD

**Issue by dongheegy** [codingeverybody/codingyahac#65]
안녕하세요?
다른 사람의 질문, 답변을 구경하다가 문득 생각난 건데요,
코딩야학 조력자가 아닌 사람이 질문에 답변을 달아도 괜찮을까요?

아무래도 답변하는 사람이 많아지면, 해결 속도라든지, 의견의 다양성이라든지에서는 이점이 있을 듯 한데,
저같은 불특정 다수의 답변이 달리기 시작하면, 잘못된 답변이라든지, 답변자의 태도라든지 복잡한 문제도 있을 것 같아서...

어떻게들 생각하시는지 궁금합니다.

**Comment by dongheegy** [comment]
[README.md](../blob/master/README.md) 파일에 이미 "물론 학우들끼리 질문&답변을 주고 받을수도 있습니다." 라고 적으셨군요.

**Comment by egoing** [comment]
간절히 많은 분의 참여를 원합니다. ㅎㅎ
감사해요 ^^
