### ISSUE TITLE
호스팅 할 떄에 파일 확장자 숨기기

### ISSUE THREAD

**Issue by seomingyu11** [codingeverybody/codingyahac#651]
# 해결하고자 하는 문제
보통 유명한(?) 사이트에 들어가 보면
"https://www.example.com/index.html"
이런 형식으로 뒤에 확장자(html)이 안 뜨잖아요.
그래서 이 부분을 어떻게 하면 없앨 수 있는지 궁금합니다.

# 환경
WIndows 10 PRO / HTML, CSS, Javascript

# 시도해본 방법
어떻게 하는지 몰라서 안 해 봤습니다.....

**Comment by egoing** [comment]
apache를 사용하신다고 가정하면 추천 검색어는 아래와 같습니다. 
```apache hide file extension```

mod_rewrite 라는 아파치의 모듈을 사용하시면 해결할 수 있습니다. 

제가 찾아본 정보는 아래 페이지입니다. 
https://stackoverflow.com/questions/1992183/how-to-hide-the-html-extension-with-apache-mod-rewrite

그 중 발취한 내용입니다. 
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d          # is not directory
RewriteCond %{REQUEST_FILENAME}\.html -f     # is an existing html file
RewriteRule ^(.*)$ $1.html                   # rewrite index to index.html
```

위와 같이 mod_rewrite 기능을 설정하면 
요청이 들어왔을 때 
그 요청에 해당하는 디렉토리가 없고, 
그 요청 뒤에 .html이 붙어있는 파일이 있다면 
그 요청 뒤에 .html을 붙인 파일을 응답하라는 뜻입니다. 

더 궁금하신 점이 있으시면 이슈를 다시 열어주세요~
