### ISSUE TITLE
웹호스팅 관련

### ISSUE THREAD

**Issue by HoWWWWWhy** [codingeverybody/codingyahac#652]
# 해결하고자 하는 문제
생활코딩 python 강의 보고 간단한 웹페이지를 만들어보았는데요!
사용 기술은 python cgi, mysql, javascript, html, css를 사용하였습니다. 
홈서버는 보안적으로 위험할 것 같아서 웹호스팅 서비스를 이용하고 싶은데요
깃헙같은 곳은 정적페이지만 되는 것 같아 국내호스팅 업체나 heroku 같은 곳을 이용하려고 했는데 좀 어렵네요...가능한건지도 모르겠습니다.
혹시 추천해주실 만한 사이트가 있으신가요?? 

또 mysql같은 경우 서버 아이디와 비번이 코드에 들어가게되는데
이런 경우 보통 어떤방식으로 정보를 처리하는지 궁금합니다.

# 환경
윈도우즈10, apache, python cgi( mysql, html, javascript, css)

# 시도해본 방법
heroku, pythonanywhere, github
(제가 못하는 건지... 안되는건지 모르겠습니다 ㅜㅜ)

**Comment by egoing** [comment]
우선, 실제로 웹앱을 만드실 때는 django와 같은 웹 프래임워크를 이용하실 것을 추천드립니다.

python으로 mysql을 쉽게 제어하려면 라이브러리를 이용하시는 것이 안전하고 편리합니다.

아래의 검색어로 검색을 해보니
```python mysql library```

아래와 같은 라이브러리를 찾을 수 있었습니다.
https://github.com/PyMySQL/PyMySQL

이 중 일부를 발취해보면 아래와 같습니다.

```
import pymysql.cursors
# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

try:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
finally:
    connection.close()
```

우선 라이브러리를 설치하고, 
위와 같이 코드를 작성하면 
파이썬을 통해서 MySQL의 데이터를 가져올 수 있습니다.

이런 작업을 통해서 웹앱을 구현하기 위해서는 
서버에 python이 설치 되어 있어야 하고, 
사용자가 python으로 동작하는 웹앱의 ip와 port로 접근할 수 있어야 합니다.

github는 정적 호스틍이기 때문에 이용할 수 있고, 
heroku에 python을 설치하고, 이것이 네트워크에 연결될 수 있다면 
애플리케이션을 동작시킬 수 있을 것입니다.

일단 이렇게 말씀 드립니다.
후속 질문이 있으시면 이슈를 다시 열고, 
보다 제사한 질문을 부탁드립니다.

**Comment by HoWWWWWhy** [comment]
빠른 답변 감사드립니다!
안그래도 이번 코딩야학 프로젝트로 cgi로 만든 서비스를 Flask로 바꿔보려고 합니다!
완성될 생각을 하니 뿌듯하네요!! 생활코딩 덕분입니다ㅜㅜ

후속질문을 더 드리자면
1. python mysql은 알려주신 방법과 비슷하게 로컬서버에서 구현하는 것을 성공하였습니다. 제가 궁금했던건 저의 코드에 username, password로 db에 접속을 해야하는데 이 정보는 외부에 노출되면 안되기 때문에 어떻게 처리해야 할지 고민이 됩니다. 검색 결과 github에서 .gitignore 파일을 이용하는 방법이 있는 듯한데 동적페이지이기 때문에 이 방법이 어려울 것 같아서요! 보통 배포할 때 이러한 기밀 정보는 어떻게 하시는지 궁금합니다!

2. heroku와 같이 실제로 배포하는 과정을 강의해주실 계획은 없으신지 궁금합니다! 없으셔도 지금까지로도 너무 큰 것들을 받고 있는 것 같아서 감사드립니다.
