### ISSUE TITLE
open issue 방법

### ISSUE THREAD

**Issue by HoWWWWWhy** [codingeverybody/codingyahac#655]
# 해결하고자 하는 문제
제가 질문을 올렸었는데요. 이슈가 close됐는데 후속질문이 있으면 다시 열어달라고 하셔서요...근데 다시 이슈를 여는 방법을 모르겠습니다..
어떻게 하는지  가르쳐주시고 혹시 이 질문이 성향에 맞지 않는다면 말씀해주시면 삭제하도록 하겠습니다!

**Comment by egoing** [comment]
<img width="1089" alt="Screen Shot 2019-08-01 at 6 55 40 PM" src="https://user-images.githubusercontent.com/303822/62284118-fe384600-b48d-11e9-874a-e376481d4c71.png">
설명이 부족했네요 ㅠㅠ
위의 reopen 버튼을 다시 눌러주세요~

**Comment by HoWWWWWhy** [comment]
![image](https://user-images.githubusercontent.com/44773229/62299811-9fd08f00-b4b0-11e9-96a4-a5c4cca6ed27.png)

저는 왜 Reopen issue 버튼이 안뜰까요....

**Comment by studroid** [comment]
어떤 상황인지는 정확히 모르겠지만, Reopen이 안 되되시면 새로 이슈를 올리시면 해당 질문의 URL을 내용에 붙여넣기 하시면 레퍼런스로 들어가집니다, 참고하셔요! :)
