### ISSUE TITLE
화면단에서 서버로 axios를 사용하여 post요청시에 새 창을 띄운 후에 request body값 전달하는 법이 있을까요?

### ISSUE THREAD

**Issue by ClockMoon** [codingeverybody/codingyahac#656]
# 해결하고자 하는 문제

현재 기상청에서 데이터를 크롤링 한 후에 그 값들을 엑셀파일로 파싱하여 다운받을 수 있게 하는 웹을 제작중입니다.

현재 파싱하여 url 요청을 하면 클라이언트로 엑셀 파일이 다운로드 받아집니다.

그런데 View단에서 post요청을 하니, 코드 실행만 되고 다운은 받아지지 않는 상황입니다.
아마 서버단에서 다운받아지고 있는 것 같습니다. (서버와 클라이언트 포트가 다릅니다.)

View에서 post요청을 하면 서버 주소의 새창이 열린 후에 post로 마저 진행 한 후 요청이 모두 완료되면 새창을 닫는 형식으로 진행하면 해결 될 것 같은데 방법을 잘 모르겠습니다.

키워드나 좋은 해결방법이 있으면 알려주시면 감사하겠습니다.  

# 코드 혹은 오류

> router.post("/excel", (req, res) => {
  makeExcelFile(req, res);
 });

서버쪽은 makeExcelFile 함수에 req,res 넣어 실행시키기만 하면 됩니다.

>   const onExcelTest = async e => {
    e.preventDefault();
    await axios.post("http://localhost:8080/api/card/excel", {
      dummy
    });
  };

프론트 쪽은 현재 onSubmit시 임의의 dummy를 서버로 넘겨주고 있습니다.

이 과정에서 서버는 데이터를 받아 크롤링 까지는 하는것 같고,
현재 브라우저로 파일을 내려주기 때문에 
현 클라이언트 주소에서 못 받고 있는것 같습니다.

# 환경
React , Express

#깃 주소
https://github.com/ClockMoon/WeatherCrawlingService

# 시도해본 방법

**Comment by Hatser** [comment]
[이런](https://gist.github.com/javilobo8/097c30a233786be52070986d8cdb1743) 예제를 하나 찾았습니다. 한 번 시도해보세요

**Comment by jiwon3346** [comment]
동작합니다! 감사합니다!!

**Comment by ClockMoon** [comment]
해결했습니다!! 감사합니다!
