### ISSUE TITLE
리뷰 website 구축에 관하여

### ISSUE THREAD

**Issue by Eunseung** [codingeverybody/codingyahac#657]
# 해결하고자 하는 문제
문제를 해결하고싶어서 코딩을 접하게된지 3개월 인 사람입니다. 
(HTML,CSS,JS까지 공부를했습니다.)
넘쳐나는 식당과 시설들, 우리는 거기서 어떤것을 선택할지 조건이 더 좋은쪽으로 생각하게됩니다. 하지만 맛집어플이며, 네이버에서 검색, 인스타그램을 통하여 여기저기 왔다갔다 해야하는 에너지와 시간을 낭비하게 되죠, 저는 이러한문제점을 해결하고싶어서 흩어졌던 것들을 총합하고, 크라우드소싱을 이용하여, 없어진 식당이나, 영업시간이 바뀌거나 갑작스런 휴무나 일이 생기고, 그리고 네이버 블로그 같은 경우엔 돈주고 맛집이라는 소개가 많은데, 사람들이 실시간으로 평가함으로써 보다 정확한 평점이 나올 수 있는 사이트를 구축하고싶습니다. 

1. 너무나 큰 프로젝트라 어디서부터 접근을 해야할지 감이 잡히지않습니다.
2. 미국의 "Yelp" 라는 사이트가 실제로 이러한 서비스를 제공하고있는데, 사이트 따라하기는 어떻게 하는지 궁금합니다.
3. 아울러 서비스를 제공하기에 앞서, 각 업체들에게 소정의 수수료를 받고 번영할 수 있는 블록체인 기술에는 어떤것이 있을까요
4. 개발자님들의 시선에는 추상적으로 보이시겠지만, 제가 너무나 큰 욕심을 가지고있는지, HTML,CSS,JS 까지 배웠는데 더이상 어떻게 프로젝트를 시작해야할지 모르겠습니다.

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도우 10, Atom을 쓰고있습니다.

# 시도해본 방법

**Comment by studroid** [comment]
와우, 조금씩이라도 3개월간 HTML, CSS, JS를 모두 학습하기는 쉽지 않은데, 정말 열심히 하셨던 듯하네요!
문제를 해결하고 싶다는 동기가 있으시다면 앞으로도 분명 잘 해나가실 것 같습니다.

꽤 구체적인 목표를 두고 있으셔서, 전체적으로 질문에 대한 제 생각을 정리해볼게요 :)

우선 HTML, CSS, JS는 일반적으로 지금 사용하고 계신 브라우저에서 처리를 하여 사용자에게 보여주는, 클라이언트측 언어라고 부르는 것들입니다. 즉, 인터넷에 연결되어 있지 않아도 브라우저를 켤 수만 있으면 처리 결과를 볼 수도 있겠죠. 다만 이것만 가지고는 다른 사람들의 데이터를 가져올 수 없습니다. 내 컴퓨터의 브라우저를 다른 사람이 원격에서 쓸 수는 없을 테니까요.

여기서 다른 사람들의 데이터를 주고받으려면, 보통 '서버'라고 불리우는 특별한 존재를 만들어야 합니다.
브라우저를 켜고 URL을 입력하면, 해당 URL을 담당하는 '서버'로 데이터를 요청하고 그 데이터를 HTML, CSS, JS를 사용하여 출력하는 형태로 만들어야 하는 것이죠.

새로운 개념을 익히셔야 하기 때문에, 조금 막연하게 느껴지실 수 있습니다. 하.지.만! 우리 옆에는 [길을 밝혀주는 등대](https://opentutorials.org/course/3083)가 있지요.

생활코딩 WEB2 과정 중, 다음에서 하나를 택하여 공부하시면 서버에 대한 개념을 익히고 이를 지금까지 배우신 HTML, CSS, JS와 연결하여 결과물을 만드실 수 있을 겁니다.

[PHP](https://opentutorials.org/course/3130)
[Python](https://opentutorials.org/course/3256)
[Node.js](https://opentutorials.org/course/3332)


또, 여기에 블록체인을 응용하여 해볼 만한 것들은 분명 이것저것 있지만, 전반적으로 DApp이라는 것에 대한 개념을 먼저 잡으시면 더 구체화하실 수 있을 것 같습니다. 이를 배우기 위한 가이드라인은 [여기에](https://github.com/codingeverybody/codingyahac/blob/master/DAppReference.md) 올려놨으니 참고하여 학습을 해보세요!

그리고 가장 중요한 것!
개발에 있어 너무나 큰 욕심이라는 건 없습니다. 구체적이고 명확한 목표와 동기를 가지고 계신 만큼, 앞으로 배우실 새로운 개념들도 분명 잘 이해하여 적용하실 수 있으리라 생각합니다. 결국 조금씩 앞으로 나아가다 보면 원하시는 목표점에 도착할 거에요! 저도 응원하겠습니다! :)

**Comment by Eunseung** [comment]
이렇게나 자세히 설명에 대하여 그것도 구체적으로 답변해주시니 엄청나게 감사할따름입니다.
학습에 대하여 어두운길을 혼가 걷고자하는저에게 불을 발혀주는 엄청난 도구인 손전등(등대)을 쥐어주셨습니다. 모험에 있어 도구를 잘활용하고 또 헤쳐나가는 것은 제 몫인데, 보이지않는 장애물을 식별하여 피할 수 있게 해주신점이 너무나 감사합니다 ! 그리고, 또 불편함에 직면할 생각에 너무나 설렙니다. 생활코딩은 저에게 있어 큰 멘토가 되었습니다. 세상을 좀더 유용하게 만들 수 있도록 문제를 해결 할 수 있는 생산자가 되어보겠습니다.
