### ISSUE TITLE
장고걸스 막히는부분이 있어요

### ISSUE THREAD

**Issue by Hyunsungjun** [codingeverybody/codingyahac#659]
# 해결하고자 하는 문제

Post에 빨간줄 그이는거랑 contents부분에 글씨가 표현안되고 none으로 나오는 이유를 모르겠어요
view.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

post_list.html
<!DOCTYPE html>
<html lang="ko">
    <html>
        <head>
            <title>Django Girls blog</title>
        </head>
        <body>
                <div>
                        <h1><a href="/">Django Girls Blog</a></h1>
                    </div>
                    
                    {% for post in posts %}
                    <div>
                        <p>published: {{ post.published_date }}</p>
                        <h1><a href="">{{ post.title }}</a></h1>
                        <p>{{ post.text|linebreaksbr }}</p>
                    </div>
                {% endfor %}
        </body>
    </html>
# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
macos 10.14.5 / 장고 2.0.0 파이썬 3.6 

# 시도해본 방법
csrf 알아보고 커밋도 해보고 바꿔가면서 되는지 안되는지 알아보고 음.. 게시판 제목이랑 시간만 나오다니 웃기는군..요..

**Comment by progh2** [comment]
링크가 안걸리는건 브라우져 설정마다 다르게 나오는 것 같습니다. href=“”  를 href=“./“ 로 바꾸면 아마 사파리에서도 그어질 것 같군요. 링크가 제대로 걸리는 부분은 튜터리얼 맨 마지막 챕터에서 구현합니다
https://tutorial.djangogirls.org/ko/extend_your_application/

Content 부분은 모델 파일에서 제대로 text라는 속성이 만들어졌는지 확인해보세요.
오타가 나서 text가 아니라 tet라던가 하는 식으로 들어가 있다면 그럴 수 있을 것 같습니다.
https://tutorial.djangogirls.org/ko/django_models/

**Comment by Hyunsungjun** [comment]
감사합니다 해결했어요!
