### ISSUE TITLE
Javascript : Atom 패키지 관련입니다.

### ISSUE THREAD

**Issue by dimsssss** [codingeverybody/codingyahac#66]
# 현재 상황
안녕하세요. 현재 개인 프로젝트로 아톰 node.js콘솔창을 진행중입니다.
![2018-01-07 05-49-11](https://user-images.githubusercontent.com/24388846/34643820-8430b112-f36e-11e7-9a29-62bccb6e6d2d.png) node.js를 실행하면 저 화면에 실행 결과를 출력하고 싶습니다.

# 계획한것
1. 컴퓨터에서 node.js 실행파일(?)을 찾는다.
2. 터미널에서 실행시킬때 node+파일명으로 실행시키듯이 파라미터로 
    node+파일명의 문자열을 넘겨주고 실행시킨다.
3. 실행결과를 만든 화면에 출력한다.

# 알고 싶은것
1. node + 파일명의 문자열을 어떻게 노드실행기에 넘기는지?
2. 실행한 결과를 어떻게 받아오는지?
3. 계획한것에 잘못된게 있거나 수정해야할게 있는지
4. 진행하는데 있어서 알아야하는 지식이나 문서가 있는지?

**Comment by egoing** [comment]
첨부하신 저 예제는 어디에서 가져오신건가요?

**Comment by dimsssss** [comment]
atom 홈페이지 튜토리얼에있는 예제를 수정했습니다.

http://flight-manual.atom.io/hacking-atom/sections/package-word-count/

**Comment by azaraks2** [comment]
비슷한 것 같은데 코드를 참고해보세요.
https://github.com/pierregoutheraud/atom-js-console
