### ISSUE TITLE
신입이 실력을 늘릴 수 있는 방법은 뭐가 있을까요?

### ISSUE THREAD

**Issue by hyungjunk** [codingeverybody/codingyahac#663]
이제 1년차가 거의 다 되어가는 신입입니다.

파이썬 플라스크와 DB 조금, 웹 프론트(뷰) 조금의 지식만 가지고 있는 상태입니다.
`프로젝트를 해야 실력이는다`는 말이 많아서 토이프로젝트를 해야겠다는 마음은 있지만, 사실 엄청 만들어보고 싶은건 없어서 매 번 개발환경 세팅하고 깔짝대다가 끝나네요.

비전공자라 기본기가 부족할 거 같아 대학교 운영체제 강의도 보고, 매일 파이썬 중고급 문법 익히느라 시간은 많이 쓰는데 제자리 쳇바퀴 도는 느낌입니다 ㅠ 어떻게 해야 스스로도 만족할만한 실력성장을 할 수 있을까요?

**Comment by alisol** [comment]
1. 간단한 기능으로 나와 주변 사람들에게 도움줄 수 있는 사이트 구상
2. 최대한 빨리 만들어 보기
3. 주변 사람들에게 소개하고 반응 살피기
4. 수정사항 찾아서 개선하기
5. 다시 주변사람들에게 사용해보라고 권유하고 반응 살피기
6. 반복.

**Comment by studroid** [comment]
방금 이슈가 닫히기는 했지만, 추가적으로 의견을 드리자면

1. 다른 사람과 함께 공부하는 스터디에 참여하여, 내가 아는 것을 알려주고 다른 사람이 알지만 나는 몰랐던 것들을 학습하시는 것도 좋을 것 같습니다. 똑같은 언어를 학습해도 개개인이 중요하게 여기는 것들이 다르기 때문에, 경험이 적은 사람에게도 분명 배울 점이 많이 있을 테니까요 :) 
 요새는 온라인에서만 진행하는 스터디들도 많고, [이런 스터디 플랫폼](https://studypie.co/ko/course/python_web_crawling#for-who)을 이용해보시는 것도 도움이 되실 수 있을 듯합니다.

2. 온라인, 혹은 오프라인 등에서 뭔가 목표를 하나 가지고 만들어가는 그룹을 만들거나 만들어진 그룹에 참여하시는 것도 좋은 방법일 듯합니다. 저는 주로 제 지인들을 모아 하나의 서비스를 기획부터 디자인, 개발까지 다 같이 해보는 경험을 하면서 새로운 분야를 배우곤 하는데, 이런 방식이 학습에 대한 동기부여도 잘 되고 끝까지 목표를 달성하게 하는 원동력이 되기도 하더라구요 ㅎㅎ

3. 혼자 [해커톤](https://onoffmix.com/event/main?s=%ED%95%B4%EC%BB%A4%ED%86%A4) 등의 개발 행사에 참여하시는 것도 굉장히 좋은 방법이겠습니다. 다만 요새는 이전에 비해 개인 참여자들이 모여서 당일에  팀을 만드는 해커톤 자체가 적긴 합니다만.. 아직 분명 여기저기서 열리고 있으니 해커톤에 참여해서 짧은 기간(보통 2박3일 정도) 동안 하나의 프로토타입 서비스를 만들어보는 경험을 해보시면 여러모로 도움이 되실 것 같습니다.
