### ISSUE TITLE
Python 원주율 질문.

### ISSUE THREAD

**Issue by XCIXI** [codingeverybody/codingyahac#668]
# 해결하고자 하는 문제

Python 문법 중 원주율을 3.14 부분까지 표기하려고 할 경우 Pi앞에 .을 붙이면 되나요?

# 코드 혹은 오류
   print(math.pi(3.14))

# 환경

Windows 10 Home X64 1903H1

# 시도해본 방법

**Comment by Hatser** [comment]
아래처럼 이용하시면 됩니다.
출력하는 방식을 세 가지로 적어놨는데, 모두 같은 의미입니다.
```py
# 출력만 시킬 때
print(f'{math.pi:.2f}')
print('{:.2f}'.format(math.pi))
print('%.2f' % math.pi)

# 변수의 값으로써 이용할 때
pi = round(math.pi, 2)
print(pi)

'''결과:
3.14
3.14
3.14
3.14
```
