### ISSUE TITLE
공부방법 질문입니다!

### ISSUE THREAD

**Issue by hackyeah039** [codingeverybody/codingyahac#669]
안녕하세요! 저는 비전공자이고 생활코딩님의 영상을 정말로 즐겨보는 학생입니다.

2가지 질문이있습니다.

1.생활코딩님의 영상을 보고 이걸 어디다 적용해서 복기하며 연습해야할까요?
- 거의 모든 영상이 이론영상인데 이걸 연습하려면 영상에서 다뤘던걸 똑같이 구현해보면서 연습을 할까요? 아니면 새로운 예제를 모아놓은 페이지에서 연습을 할까요?

2.선을 잘 모르겠습니다.
- 생활코딩님의 영상을보다가 애매한 내용이 있어서 블로깅이나 구글링을 해보면  많은 현직개발자의 블로그나 글들이 많이뜨는데 , 그럴때마다 항상 직면하는 문제점이 있습니다.

example)제가 알고싶은 개념이 A라고 했을때, 블로그를 키면 그 A를 이해하기위해서 B,C가 필요하다 ..이런식으로 항상 블로깅이 되어있습니다. 그래서 '아 B,C가 이걸이해하는데 필수불가결의 요소구나?? ' 해서 B,C를 찾습니다.

- B,C가 쉬운개념들이면 1~2시간에서 끝나고 A를 이해할수있지만, 
- 대부분 저에겐 엄청 어려운 내용들이라 말미엔 B,C의 내용도 이해가 안되고 그렇다고 A의내용도 이해가 안되는 결말엔 '그럼 A는 ~~이건가?'라는 추측의 영역으로 들어서는 모래성쌓기가 되버립니다 
 이게 저에겐 계속 끝나지않는 for문과같이 반복되는데, 

1) 새로운 개념을 배울때 위의 예를 들었던 B,C를 집요하게 파고들어 이해해서 A까지 같이 이해해야하는 방식으로 접근을 해야하는걸까요?

아니면, 2) A를 응용한 예제를 많이풀면서 개념에대한 이해는 완벽하게 하지못했지만 '나중엔 이해를 못했지만 내 손,뇌에 익숙한 개념들이 쌓이다보면 어느순간 이해하는 날이 오게될꺼야'라는걸 노려야 할까요?

**Comment by Hatser** [comment]
사람마다 공부하는 방법이 다르고, 개인차가 크기때문에 제 의견을 말씀드리자면,

1. 생활코딩님의 영상을 보고 이걸 어디다 적용해서 복기하며 연습해야할까요?
영상을 보시고, 해봐야겠다 하는 간단한 부분은 직접 해보셔도 좋습니다.
다만 코드를 그대로 작성하기보다는 어느정도 응용을 해보시기를 추천드립니다.

중요한 점은 본인이 알고있는 부분에서부터 공부해나가야 한다는 점인데,
사전지식을 모르는 내용을 영상이나 블로그 등을 통해 공부할 순 있지만, 그 기술을 응용하려 들면
자칫 어떻게 구현해야 할 지 길을 잃어버리는 경우가 많습니다.

알고있는 부분부터 공부해 나가면서, 새로운 기술을 배우면 이 기술로 어떤 걸 만들어볼 수 있을까?
하는 생각을 가져보세요 지식을 확장할 수 있는 좋은 기회도 될 것이고, 배운 내용을 상기시키기도 좋습니다.
만드는 과정에서 문제가 발생했거나, 모르는 내용을 알게된다면 이 내용을 기록해놓는 것도 좋은 방법이에요.

2. 선을 잘 모르겠습니다.
어떤 내용을 배우다가 애매한 내용이 생기셨는지 잘 모르겠지만, 사전지식이 분명하게 필요한 내용이었다면 그 이전지식을 먼저 이해하는게 중요합니다. 기술을 익히면 익힐수록 탄탄한 기반과, 그 베이스를 통한 응용이 중요해지거든요.
사전 지식을 이미 배웠고, 어느정도 이해했지만 살짝 애매한 부분이 생긴다면 해당 기술의 문서(Docs)를 찾아보셔도 좋습니다. 문서를 이해하기에는 아직 조금 실력이 안된다고 생각되신다면 먼저 여러번 사용해보시면서 어떻게 사용하는 것이다 부터 이해하신 뒤에 나중에 그 원리를 이해하는 것도 방법입니다.

**Comment by hackyeah039** [comment]
앗! 답변감사합니다!
2)의 예시로는 어제 블로깅하다가 자바스크립트 프로퍼티란 무엇인가를 알고싶어서 구글링을해서 블
로그를 찾았는데 프로퍼티를 알고싶으면 스택(?), 호이스팅(?) 이란 개념과 구동원리를 알아야한다고
 해서 '아 그럼이런걸 알아야 프로퍼티가 뭔지 이해할수있겠구나..' 라고 생각하에 알아볼려고했으나.. 찾는것마다 이해는 안되고 너무어려워서 결국 새로알게된 개념들의 뜻도모르고 , 프로퍼티가 무엇인
지 정확하게모른채 그냥 '자바스크립트에서 프로퍼티란 속성을 말하고 객체내에서 key이름을 달리 말하면 프로퍼티이구나.. 결국 key이름===프로퍼티겠네' 라는 추측80프로의 결과만 나오게되었습니다. 이게 맞으면 좋겠으나 저도 이 결과에 대해서 맞다는 확신이없어서 답답한 나날들에 답변을 남기게 되었습니다.

**Comment by Hatser** [comment]
> 앗! 답변감사합니다!
> 2)의 예시로는
> 어제 블로깅하다가 자바스크립트 프로퍼티란 무엇인가를 알고싶어서 구글링을해서 블로그를 찾았는데 프로퍼티를 알고싶으면 스택(?), 호이스팅(?) 이란 개념과 구동원리를 알아야한다고
> 해서
> '아 그럼이런걸 알아야 프로퍼티가 뭔지 이해할수있겠구나..' 라고 생각하에 알아볼려고했으나..
> 
> 찾는것마다 이해는 안되고 너무어려워서 결국 새로알게된 개념들의 뜻도모르고 , 프로퍼티가 무엇인
> 지 정확하게모른채
> 
> 그냥 '자바스크립트에서 프로퍼티란 속성을 말하고 객체내에서 key이름을 달리 말하면 프로퍼티이구나.. 결국 key이름===프로퍼티겠네' 라는 추측80프로의 결과만 나오게되었습니다.
> 
> 이게 맞으면 좋겠으나 저도 이 결과에 대해서 맞다는 확신이없어서 답답한 나날들에 답변을 남기게 되었습니다.

너무 자세한 부분까지 이해하고 진행하려고 하신 것 같아요.

사실 기초적인 부분일수록 기술이라는 하나의 거대한 기계속의 톱니바퀴처럼 원리로 작용하는 부분이 있지만, 우리가 시계의 시간을 고치기위해 톱니바퀴의 구조를 알 필요는 없죠. 이미 수정하는 바퀴가 달려있으니까요.

자바스크립트의 기초를 공부하는 단계에서는 ~는 대충 ~다. ~는 이렇게 사용하면 된다. 수준에서 넘어가셔도 지장이 없습니다.

자바스크립트에서 속성은, 어떤 객체들이 있고 그 안에 변수처럼 값이 들어있는데 그게 속성이다.
라는 느낌으로요. 글로 적으니 너무 복잡하실 수 있겠어요.

F12를 열어 Console 탭에서 아래 텍스트를 입력해보세요
```js
document.URL
```

페이지의 정보를 담고있는 `document`라는 객체의, 현재 주소를 가지는 `URL`이라는 속성입니다.

이런게 속성이구나 하고 넘어가셔도 좋아요.
자바스크립트를 공부하는거지 자바스크립트 언어 자체의 구조와 자료구조를 공부하고자 하는게 아니니까요.

**Comment by hackyeah039** [comment]
그렇군요! 구조와 자료구조에대한 정의자체가 없는 무지한 상태라 뭐가뭔지를 잘 몰랐던 상황이였던것 같습니다!  엔지니어분이 저같은 사람한테 이런답변을 하다니 코딩야학프로젝트가 너무좋네요ㅠㅠ

**Comment by Hatser** [comment]
> 그렇군요! 구조와 자료구조에대한 정의자체가 없는 무지한 상태라 뭐가뭔지를 잘 몰랐던 상황이였던것 같습니다! 엔지니어분이 저같은 사람한테 이런답변을 하다니 코딩야학프로젝트가 너무좋네요ㅠㅠ

감사합니다. 저도 아직 배우는 입장으로 알아가야 할 게 많습니다. ^^

**Comment by znffl** [comment]
안녕하세요.
하기 이슈를 close하겠습니다. 추가로 궁금한 점이 있으시면 다시 open 부탁드립니다.
