### ISSUE TITLE
Github repository의 파일 소스 embed 방법

### ISSUE THREAD

**Issue by dongheegy** [codingeverybody/codingyahac#67]
아래 그림과 같이 Github Gist의 소스는 embed 코드를 얻어서 다른 웹페이지에서 코드를 쉽게 공유할 수 있습니다.
![image](https://user-images.githubusercontent.com/13765815/34645767-532ab768-f399-11e7-9597-9b7c11aa8679.png)
Github Repository의 소스파일에 대해서도 embed 코드를 얻어서 다른 웹페이지에서 공유할 수 있지 않을까 하고 찾아보았는데 도통 찾을 수가 없네요.
Github Repository의 소스파일에 대한 embed 코드를 얻는 방법이 있을까요? 있다면 어떻게 할 수 있는지 알려주셨으면 합니다.

**Comment by blackdew** [comment]
"Gist-it"이라는 툴이 있나봐요. :) 
http://blog.revathskumar.com/2012/08/embed-files-from-github-repository-into-webpage.html

**Comment by dongheegy** [comment]
감사합니다. 생각보다 쉽게 되네요.
이제 Gist-it 결과물에 CSS를 어떻게 추가로 적용할 수 있을지만 찾아보면 될 것 같네요.
