### ISSUE TITLE
MySQL Workbench에서 csv 파일을 불러올 때 오류가 나요.

### ISSUE THREAD

**Issue by marcwoo94** [codingeverybody/codingyahac#671]
# 해결하고자 하는 문제
도서관이 소장 중인 책 정보를 이용해 데이터베이스 연습을 해보고 있습니다. 엑셀파일로 책 리스트를 가지고 있어 Workbench로 import하고 싶은데 csv 파일을 불러올 때 오류가 나요. 검색해 보니 Non-ASCII 문자가 포함 되어 있어서 그렇다는 것 같은데 Non-ASCII 문자도 포함해서 불러오는 방법이 있을까요? 

# 오류
```
Error importing recordset

error calling Python module function
SQLIDEUtils.importRecordsetDataFromFile
```

# 환경
Window 7 32-bit에서 MySQL과 Workbench를 사용하고 있습니다.

# 시도해본 방법
cvs 파일을 utf-8로 저장해도 같은 에러가 떠요.

**Comment by davidkwak** [comment]
mysql 상의 schema의 데이터가  UTF8로 세팅되어 있는지 확인해보시겠어요?

![image](https://user-images.githubusercontent.com/8045012/62354523-0eacf700-b548-11e9-8005-f7968e8c7a8f.png)

**Comment by marcwoo94** [comment]
네 다 utf-8로 세팅했는데 계속 이러네요.. ㅠㅠ
![Capture](https://user-images.githubusercontent.com/53594727/62373585-0d45f380-b575-11e9-8b3a-fe668d944ea5.PNG)


노트북으로 해보니 다른 오류 메세지가 뜨는데 비슷한 문제인것 같아요..
![Capture1](https://user-images.githubusercontent.com/53594727/62373752-6a41a980-b575-11e9-8bae-8e6df4f34017.PNG)
