### ISSUE TITLE
멜론같은 음악 재생 앱을 만들고 싶은데 뭘 공부해야할지(IOS/Android)

### ISSUE THREAD

**Issue by webdevi** [codingeverybody/codingyahac#675]
멜론같은 음악 재생 앱을 만들고 싶은데 뭘 공부해야할지(IOS/Android) 잘모르겠습니다. 

저는 objective-c로 초기에 IOS앱도 만들어보았고, 
자바로 초기에 안드로이드 앱도 만들어본적이 있습니다. 

요즘 멜론같은 앱을 보면 
내부는 웹처럼 보이고, 밖은 네이티브로 되어 있잖아요. ㅠ 
이런 앱 서비스를 만들고 싶은데, 
도저히 처음 시작을 무엇으로 해야할지를 잘 모르겠습니다. 

딱 모델은 '멜론'이나 '네이버 뮤직' 같은 앱을 만들고 싶은건데요. ㅠㅠ

**Comment by progh2** [comment]
안녕하세요? 멜론 같은 앱을 안써서 정확하지는 않지만
웹처럼 보였다면 하이브리드앱으로 만든건 아닐까 하네요. 
그런데 목적이 그냥 비슷한 앱을 만들어 보는 것에 목적이 있는 것인가요, 아니면 
정말로 서비스를 런칭하는 것까지가 목표인가요?
전자라면 안드로이드라면 화면은 하이브리드앱 개발 프레임워크로 만들거나 또는
액티비티를 웹처럼 보이게 디자인해서 만들고(..) 서비스로 음원을 재생하는 등 
다양한 방법이 있을 것 같지만,
후자라면 저작권 문제가 먼저 해결이 되어야 하고
그 다음에는 음원을 송출할 스트리밍 서버 등을 만들어야 해서 조언해주는 범위가 굉장히 커질 것 같습니다...

**Comment by webdevi** [comment]
하이브리드앱은 아니고요. 
예를들어 네이버 앱 같은 경우도 내부는 웹처럼 보이는데, 
제가 잘못 생각하는 건가요? ㅠ ( 이걸 잘 모르겠어요 ) 
앱은 최종 런칭이 목표이고요.
저작권문제 없고, 스트리밍 서버도 문제는 없습니다. 웹 사이트가 있는데... 
ios같은 경우는 연속재생이 안되다 보니... 
앱으로 만들어야 할 필요가 있어서~ ㅠㅠ 앱을 만들어보려고 하는 것이랍니다. 

** 제 질문에 관심을 가져주시고 답변주셔서 감사합니다. ^^
