### ISSUE TITLE
스마트팜 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by Etreama** [codingeverybody/codingyahac#676]
안녕하세요. 현재 남해에서 조그마한 양식장(생선을 기르는 어업)을 운영하고 있는 생활코딩 학생입니다.

현재 스마트홈 관련 장비들을 이용해서 양식장의 기초적인 iot장비들을 (온도, 전기제어) 운용 중에 있습니다. 

하지만 이미 만들어진 장비들을 이용하다보니 중국난방으로 흩어진 어플리케이션들 때문에 사용

이 복잡해지고 제가 원하는 기능들은 없는 상황입니다.

스마트팜이라는 목표를 가지고 프로젝트를 완성하기 위해 코딩 공부를 시작해 보려고 하지만 코

딩에 관하여 전혀 지식이 없다보니 무엇을 어떻게 공부해 나가야 하는지 조차 모르는 상황입니다.

어디서 부터 시작을 해야할지 너무나 알고 싶어 이렇게 글을 남깁니다. 

관심가지고 읽어 주셔서 감사합니다.

**Comment by RayleighKim** [comment]
원하는 기능, 방향 등을 최대한 구체적으로 적어주실 수 있으실까요?

물론 처음 코딩을 공부하신다면 다들 시작은 비슷한 걸 공부할 수 밖에 없겠지만,
정말 머지 않아서 자신의 목적에 따라 공부해야될 내용의 우선순위들이 바뀌게 될거에요.

최대한 구체적인 예시들을 적어주시면, 역으로 조력자분들이 어떤 기술이 필요할지 추측할 수 있고.
조력자들은 그 추축들을 바탕으로 무엇부터 공부를 하면 될지 경로를 그려낼 수 있을거에요.

**Comment by Etreama** [comment]
1.처음으로 구현하고 싶은 부분은 모니터링 입니다.
현재 저희 양어장에서 사용중인 센서들은 모두 analog out을 4~20ma로 보내주고 있습니다. 이 신호를 읽어서 와이파이나 랜선을 통해 모니터링하고 데이터들을 모아서 db로 만들고 싶습니다.

2. 모니터링 시스템이 완성된다면 이 정보들을 기준으로 220v를 제어하여 선택된 정보들의 조건에 따라 수중모터를 작동시켜 산소를 공급해 준다거나 먹이를 급이하는 시스템으로 나아가고 싶습니다.


> 원하는 기능, 방향 등을 최대한 구체적으로 적어주실 수 있으실까요?
> 
> 물론 처음 코딩을 공부하신다면 다들 시작은 비슷한 걸 공부할 수 밖에 없겠지만,
> 정말 머지 않아서 자신의 목적에 따라 공부해야될 내용의 우선순위들이 바뀌게 될거에요.
> 
> 최대한 구체적인 예시들을 적어주시면, 역으로 조력자분들이 어떤 기술이 필요할지 추측할 수 있고.
> 조력자들은 그 추축들을 바탕으로 무엇부터 공부를 하면 될지 경로를 그려낼 수 있을거에요.

**Comment by RayleighKim** [comment]
이야기를 조금 더 구체적으로 그리기 위해 추가 질문을 드립니다.

예를 들자면  센서1에서는 4ma, 센서2에서는 8ma, 센서3에서는 5ma. 이런식으로 값이 저장되고, 눈으로 확인할 수 있다면.. 마치 엑셀로 확인하듯이.

'아 이럴땐 산소를 공급해야 해'
'아 이럴땐 먹이를 줘야 해'

하고서 데이터를 바탕으로 취해야할 행동을 확실히 하실 수 있나요?

아니면,, 막연하게 이런 정보를 바탕으로 산소를 공급할 타이밍이나 먹이를 줘야할 타이밍을 자동으로 찾아줬으면 좋겠다.  에 가까울까요?

> 1.처음으로 구현하고 싶은 부분은 모니터링 입니다.
> 현재 저희 양어장에서 사용중인 센서들은 모두 analog out을 4~20ma로 보내주고 있습니다. 이 신호를 읽어서 와이파이나 랜선을 통해 모니터링하고 데이터들을 모아서 db로 만들고 싶습니다.
> 
> 1. 모니터링 시스템이 완성된다면 이 정보들을 기준으로 220v를 제어하여 선택된 정보들의 조건에 따라 수중모터를 작동시켜 산소를 공급해 준다거나 먹이를 급이하는 시스템으로 나아가고 싶습니다.
> 
> > 원하는 기능, 방향 등을 최대한 구체적으로 적어주실 수 있으실까요?
> > 물론 처음 코딩을 공부하신다면 다들 시작은 비슷한 걸 공부할 수 밖에 없겠지만,
> > 정말 머지 않아서 자신의 목적에 따라 공부해야될 내용의 우선순위들이 바뀌게 될거에요.
> > 최대한 구체적인 예시들을 적어주시면, 역으로 조력자분들이 어떤 기술이 필요할지 추측할 수 있고.
> > 조력자들은 그 추축들을 바탕으로 무엇부터 공부를 하면 될지 경로를 그려낼 수 있을거에요.

**Comment by Etreama** [comment]
> 이야기를 조금 더 구체적으로 그리기 위해 추가 질문을 드립니다.
> 
> 예를 들자면 센서1에서는 4ma, 센서2에서는 8ma, 센서3에서는 5ma. 이런식으로 값이 저장되고, 눈으로 확인할 수 있다면.. 마치 엑셀로 확인하듯이.
> 
> '아 이럴땐 산소를 공급해야 해'
> '아 이럴땐 먹이를 줘야 해'
> 
> 하고서 데이터를 바탕으로 취해야할 행동을 확실히 하실 수 있나요?
> 
> 아니면,, 막연하게 이런 정보를 바탕으로 산소를 공급할 타이밍이나 먹이를 줘야할 타이밍을 자동으로 찾아줬으면 좋겠다. 에 가까울까요?
> 
> > 1.처음으로 구현하고 싶은 부분은 모니터링 입니다.
> > 현재 저희 양어장에서 사용중인 센서들은 모두 analog out을 4~20ma로 보내주고 있습니다. 이 신호를 읽어서 와이파이나 랜선을 통해 모니터링하고 데이터들을 모아서 db로 만들고 싶습니다.
> > 
> > 1. 모니터링 시스템이 완성된다면 이 정보들을 기준으로 220v를 제어하여 선택된 정보들의 조건에 따라 수중모터를 작동시켜 산소를 공급해 준다거나 먹이를 급이하는 시스템으로 나아가고 싶습니다.
> > 
> > > 원하는 기능, 방향 등을 최대한 구체적으로 적어주실 수 있으실까요?
> > > 물론 처음 코딩을 공부하신다면 다들 시작은 비슷한 걸 공부할 수 밖에 없겠지만,
> > > 정말 머지 않아서 자신의 목적에 따라 공부해야될 내용의 우선순위들이 바뀌게 될거에요.
> > > 최대한 구체적인 예시들을 적어주시면, 역으로 조력자분들이 어떤 기술이 필요할지 추측할 수 있고.
> > > 조력자들은 그 추축들을 바탕으로 무엇부터 공부를 하면 될지 경로를 그려낼 수 있을거에요.

부모님세대 부터 양어장을 운영한지 25년이 넘었기에 값에 대한 행동지침은 다 준비되어 있습니다. 위에 기술한 내용들만 현실화하여 운영 할 수 있다면 직원들이 매 시간마다 측정하여 행하던 일들을 기계에게 맡길 수 있다고 생각하여 구상하게 되었습니다.

**Comment by RayleighKim** [comment]
아! 전혀 막연하지 않은, 구체적인 그림이 있다는 것을 알았습니다!

최종적인 목표와, 그 목표를 자동화하기 위해 필요한 데이터를 명확히 정의하지 못하면...
진행하다가 다시 돌아가야만 하게될 수 있어요.

센서를 설치하고, 데이터를 수집하여 저장하고, 데이터를 바탕으로 의사결정하는  IOT 시스템에 대한 경험이 있으신 조력자분들이 더 구체적으로 답변을 달아드리게 될 것 같습니다!

처음으로 구현하고 싶으신 부분은 다음으로 보입니다.
1. 센서에서 유선/무선으로 보내오는 데이터를 서버용 컴퓨터가 잘 받도록 하는 것
2. 잘 받은 데이터를 DB에 저장하는 것.
3. DB에 저장된 값을 바탕으로 잘 시각화된 리포트를 만드는 것

저는 3번 이후 부터를 전문으로 하고 있습니다.
[Power BI](https://www.google.com/search?q=powerbi&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjqyb7HluTjAhWnwosBHUB8CNgQ_AUIESgB&biw=1342&bih=923)라는 툴을 일단 소개해드리고, 

1,2번을 더 구체적으로 알고 계신분들을 소환하며 물러나겠습니다.

> 부모님세대 부터 양어장을 운영한지 25년이 넘었기에 값에 대한 행동지침은 다 준비되어 있습니다. 위에 기술한 내용들만 현실화하여 운영 할 수 있다면 직원들이 매 시간마다 측정하여 행하던 일들을 기계에게 맡길 수 있다고 생각하여 구상하게 되었습니다.
> 
> 추가하여 제가 직접만들 자동급이기를 통하여 현재 사료는 와이파이 on/off 스위치를 통하여 시간을 제어하여 주는 방식으로 주고 있습니다. 이를 모니터링 한 값을 통해 조금 더 효율적으로 제어 하고 싶습니다.
> 
> > 이야기를 조금 더 구체적으로 그리기 위해 추가 질문을 드립니다.
> > 예를 들자면 센서1에서는 4ma, 센서2에서는 8ma, 센서3에서는 5ma. 이런식으로 값이 저장되고, 눈으로 확인할 수 있다면.. 마치 엑셀로 확인하듯이.
> > '아 이럴땐 산소를 공급해야 해'
> > '아 이럴땐 먹이를 줘야 해'
> > 하고서 데이터를 바탕으로 취해야할 행동을 확실히 하실 수 있나요?
> > 아니면,, 막연하게 이런 정보를 바탕으로 산소를 공급할 타이밍이나 먹이를 줘야할 타이밍을 자동으로 찾아줬으면 좋겠다. 에 가까울까요?
> > > 1.처음으로 구현하고 싶은 부분은 모니터링 입니다.
> > > 현재 저희 양어장에서 사용중인 센서들은 모두 analog out을 4~20ma로 보내주고 있습니다. 이 신호를 읽어서 와이파이나 랜선을 통해 모니터링하고 데이터들을 모아서 db로 만들고 싶습니다.
> > > 
> > > 1. 모니터링 시스템이 완성된다면 이 정보들을 기준으로 220v를 제어하여 선택된 정보들의 조건에 따라 수중모터를 작동시켜 산소를 공급해 준다거나 먹이를 급이하는 시스템으로 나아가고 싶습니다.
> > > 
> > > > 원하는 기능, 방향 등을 최대한 구체적으로 적어주실 수 있으실까요?
> > > > 물론 처음 코딩을 공부하신다면 다들 시작은 비슷한 걸 공부할 수 밖에 없겠지만,
> > > > 정말 머지 않아서 자신의 목적에 따라 공부해야될 내용의 우선순위들이 바뀌게 될거에요.
> > > > 최대한 구체적인 예시들을 적어주시면, 역으로 조력자분들이 어떤 기술이 필요할지 추측할 수 있고.
> > > > 조력자들은 그 추축들을 바탕으로 무엇부터 공부를 하면 될지 경로를 그려낼 수 있을거에요.

**Comment by studroid** [comment]
이전에 다른 분이 올린 비슷한 질문이 있어, 링크를 걸어드립니다 :)

https://github.com/codingeverybody/codingyahac/issues/648

위 질문의 답변으로 드린 사이트들을 참고해보시면, 어떤 것부터 시작해야 할지 감을 잡으실 수 있을 듯하네요!

무엇이 필요한지를 알고 공부를 하시는 만큼, 다른 분들보다 훨씬 재밌게, 효과적으로 학습을 하실 수 있으리라 생각합니다 :)

이것저것 따라 만들다 보면 어느새 양식장에 필요한 것들을 위한 설계가 마구 떠오르실 거에요, 화이팅입니다!

**Comment by Etreama** [comment]
이렇게 답변을 주셔서 너무 감사합니다. 아두이노를 이용한 센서링부터 천천히 시작해보도록 하겠습니다!

**Comment by progh2** [comment]
이런분들의 블로그 글들도 찾아서 보면 아이디어에 도움이 될 것 같습니다.

http://maltugi.blogspot.com/search/label/%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8%20%2F%20%EC%84%BC%EC%84%9C%EB%A5%BC%20%ED%99%9C%EC%9A%A9%ED%95%9C%20%EB%86%8D%EC%97%85

**Comment by TahoLee** [comment]
센서정보를 받는 부분이 밀리암페어단위라면 아마도 마이크로 컨트롤러 레벨의 센서들일거 같습니다. 
온도가 중요할거 같고, BOD같은것도 잴거 같네요.  민물인지 모르겠지만, 바다양식장이라면 염분농도 같은것도 잴거 같구요. 

일단 센서가 작동하고 있다는것은 데이터가 만들어 진다는것을 의미합니다. 
데이터를 가공하고 직관적으로 볼 수 있는 형태로 만들기 위해서는 우선적으로 데이터 베이스에 저장해야합니다. 여기에는 두가지 옵션이 있는데, 
마이크로 컨트롤러( 혹은 제어판) 을 컴퓨터에 연결하고 켬퓨터에서 신호를 읽어서 저장하는 방법입니다. 
말하자면 아두이노를 연결한 컴퓨터에서 값을 읽어서 데이터베이스에 저장하는 방법입니다. 
다른 방법은 마이크로컨트롤러에서 직접 데이터베이스로 연결하여 데이터를 입력하는 방법입니다. 이부분이 흔히 말하는 IOT 에 대한 부분입니다. 그러면 센서에서 측정된 내용을 데이터베이스에 모을 수 있습니다. 
경우에 따라서는 측정된 내용과 부가적으로 추가되는 내용이 같이 저장될 필요도 있습니다. (예를들어 수질과 온도데이터가 기록되면서 수조에 있는 물고기 수를 기록해 주는것등) 

이렇게 데이터가 기록되고 나면 데이터를 이용해서 일련의 리포트를 만들수도 있고, 데이터에 따라서 알림을 받을 수도 있고, 특정 기기를 작동시킬수도 있습니다. 
기기를 작동시키는 부분은 릴레이라는것을 사용하는데, 마이크로 컨트롤러에서 신호를 받아서 전기장치를 제어할 수 있도록 하는 부품입니다. 

아마도 사용하는 센서와 기계들이 상이하다면 플랫폼을 통일하고, 컨트롤하는게 일이될수도 있을거 같습니다. 하지만 무척의미있는일이 될거 같습니다.

**Comment by blackdew** [comment]
안녕하세요. 저도 남해 물건리에 살고 있는데요. 반갑습니다. 
가까이 있으니 한 번 뵙고 여러가지 가이드를 드려도 좋겠네요. 
blackdew7@gmail.com 이쪽으로 메일 주세요. :)
