### ISSUE TITLE
아톰 창 자동 줄바꿈

### ISSUE THREAD

**Issue by aromeyang** [codingeverybody/codingyahac#68]
프로젝트창이 다음과 같이 뜨는데요, 오른쪽으로 스크롤 할 필요없이 줄이 길어지면 아래로 내려와주면 좋겠는데 설정할 수 있나요?
2번 줄이 정직하게 딱 그 줄만 사용하니까 너무 불편해서요!

![image](https://user-images.githubusercontent.com/35183214/34646184-dd659118-f3a4-11e7-94bc-789948a12d95.png)

**Comment by blackdew** [comment]
'아톰 에디터 자동 줄바꿈'으로 검색한 결과입니다. :) 
검색결과를 참고하시면 해결할 수 있을 것 같네요!
https://goo.gl/Lb6dfE

**Comment by aromeyang** [comment]
앗 너무너무 감사합니다:))
