### ISSUE TITLE
Golang 또는 그외 서버 언어로 작성된 제품에서 발생하는 보안이슈

### ISSUE THREAD

**Issue by aid95** [codingeverybody/codingyahac#680]
현재 회사에서 gin으로 서비스중인 제품이 별로 없다고는 생각이 들지만 그 외에 Django나 node.js같은 다른 제품에서 흔히 발생하는 실수나 보안 이슈에 대해 알 수 있을까요?

**Comment by progh2** [comment]
이런 종류의 질문은 해당 기술 별로 관련 커뮤니티 등에 올려야 답변할 수 있지 않을까 합니다. 
(그렇게 올린다 해도 역시 범위가 너무 광범위한 것 같아요...)

**Comment by Hatser** [comment]
[여기](https://github.com/guardrailsio/awesome-golang-security)에서 go언어와 관련한 여러 보안 라이브러리나 가이드, 예제 등을 찾아보실 수 있습니다. 참고해보세요.

**Comment by aid95** [comment]
@Hatser 좋은 정보 감사합니다 :)
