### ISSUE TITLE
안드로이드 버튼 누른 상태로 유지하는 방법

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#684]
# 해결하고자 하는 문제

안녕하세요? 
여러개의 버튼 중에 클릭된 버튼을 누름 상태로 유지하려고 합니다.
검색을 통해 아래와 같이 터치리스너를 사용하는 방법을 찾았는데 
이상하게 각 버튼을 두 번씩 클릭해야 클릭 상태가 유지됩니다.
왜 그런걸까요?
혹시 누름 상태로 유지하는 다른 방법이 있을까요?

# 코드 혹은 오류
```
   @Override
    public void onClick(View view) {

        switch (view.getId()) {

            default :

                selectedBtn = (Button) view;

                selectedBtn.setOnTouchListener(new View.OnTouchListener() {
                    @Override
                    public boolean onTouch(View view, MotionEvent motionEvent) {
                        selectedBtn.setPressed(true);
                        return true;
                    }
                }); 
```

# 환경
안드로이드

**Comment by progh2** [comment]
그런 용도로 토글버튼이 따로 있는데 이걸 쓰시는건 어떨까요?
스타일을 일반 버튼처럼 바꾸면 될 것 같은데요.

토글버튼 소개
https://kd3302.tistory.com/63

토글버튼 스타일 커스터마이즈 하기
http://www.apnatutorials.com/android/android-togglebutton.php?categoryId=2&subCategoryId=70&myPath=android/android-togglebutton.php

**Comment by kammaii** [comment]
> 그런 용도로 토글버튼이 따로 있는데 이걸 쓰시는건 어떨까요?
> 스타일을 일반 버튼처럼 바꾸면 될 것 같은데요.
> 
> 토글버튼 소개
> https://kd3302.tistory.com/63
> 
> 토글버튼 스타일 커스터마이즈 하기
> http://www.apnatutorials.com/android/android-togglebutton.php?categoryId=2&subCategoryId=70&myPath=android/android-togglebutton.php

많이 고민했는데 쉬운 방법이 있었네요! 고맙습니다! :)
