### ISSUE TITLE
현재 만들고 있는 라이브러리의 이름 중복 때문에 고민입니다.

### ISSUE THREAD

**Issue by hgs-github** [codingeverybody/codingyahac#687]
안녕하세요.
저는 현재 react 및 vue 같은 라이브러리를 만들고 있어요.

그런데 고민인 게, 이게 위의 제목에도 볼 수 있듯이
이미 이 라이브러리의 이름을 다른 곳에서 쓰고 있더군요.

그리고 그 곳은 잘 알려져 있지 않은 it 업체 구요.

저는 이 이름에 **react나 vue 같이** 
제 라이브러리의 **로고 및 심볼화를 심화**할 생각임으로
이 문제에 대해서 **매우 신중하게 생각**하고 있어요.

만약에, 만약에... ,이 라이브러리가 
react 및 vue, angular, jquery 처럼 까진 아니더라도
조금이라도 사람들에게 이름이 알려졌을 때

그 이름을 썼던 사람들이, 이 이름에 관하여
**법적인 조치를 치 해서, 이름을 바꿔야 한다면**
이보다 **절망적**인 일이 또 있을까요..

하지만 저는 이 이름을 포기 할 수 없는 게
이 이름으로 된 변수, 함수, 클레스 명 변경은 그렇다 치더라도

아무리 생각해봐도, **이 이름은 이 라이브러리에 잘 맞거든요.**
그 외에 다른 걸, 생각해보려고 해도 **도무지 생각이 나질 않아요.**

지금까지는 괜찮을 거라고 조금 무책임한 태도로
이 문제를 방관하면서 작업을 했는데

프로젝트의 진행율이 올라가면 올라갈 수록
이게 정말 신경이 쓰이네요.

주위에 이런 일을 하는 사람도 없고, 있다 하더라도
이게 완성 될 때 까지는 알리고 싶지 않았기에
물어 볼 수도, 물을 생각도 나지 않았고,

한 번은 오픈소스 저작권에 대해서
여기 저기 조언을 구하러 다녔을 때,
**그런 건 우선 코드를 공개하고 나서 그 때 고민해도**
된 다라, **나중에 저작권은 바 꿀 수 있다**는 말을 듣고 선

왠지 이 문제 또한 사람들에게 말해 봤자

**"그런 건 유명해지고 나서 고민해라"** 같은
전혀 고민 없고 무책임한 조언만 들을 것 같아서
이 문제를 사람들에게 꺼내는 데에 조심스러워져요.

하지만 제 웹 프로그래밍의 root였던
생활코딩에서 만큼은 이 문제를 함께 고민해주지 않을까 하여
간절한 마음으로 이 문제를 조심스럽게 꺼내봅니다.

저도 이고잉님 같이 구글같이 세상을 깜짝 놀래켜주고 싶어요.

제가 이 문제에 대해서 더는 고민하지 않게
**사례**와 **방법** 및 **경험**을 알려주세요 : )

# **항상 고맙고 고맙습니다.**

**Comment by smartbos** [comment]
잘 알려지지 않은 IT 업체라는 곳도 어쩌면 질문을 올려주신 분과 비슷한 야망을 가지고 있을지도 모릅니다. 아직 유명해지지 않았을 뿐.

저작권은 먼저 공개한 사람이 우선권이 있기 때문에 미리 사용한 다른 업체가 주장하면 질 가능성이 있다고 봅니다. 상표에 대해 저작권이 걱정되시면 http://www.kipris.or.kr/khome/main.jsp 를 통해 사용하고자 하는 상표가 이미 등록되어 있는지 검색해보시거나 변리사를 통해 상담을 받아보시기 바랍니다. 아직 등록된 것이 없다면 먼저 등록해서 불안감을 줄이실 수 있을 겁니다. 

다만, 오픈 소스면 사실 말씀하신 것과 같은 문제가 발생할 가능성은 적다고 봅니다.

왜냐하면 오픈 소스 진영에는 원래 같은 이름의 패키지가 존재할 수 밖에 없거든요. 그래서 보통 제작자의 시그니처가 패키지명 앞에 붙어서 고유한 패키지로 구분이 됩니다. 아래 이미지를 보시면 react 라는 이름의 패키지를 만든 많은 제작자가 있음을 알 수 있을 겁니다. 

<img width="761" alt="스크린샷 2019-08-03 오후 2 38 02" src="https://user-images.githubusercontent.com/6157033/62408091-d7008680-b5fd-11e9-9194-ec3f00fad3eb.png">

**Comment by hgs-github** [comment]
react의 경우를 보니 느낌이 확 오는군요.

라이브러리의 이름 보다 중요한 게
그것이, 누구의 그것인 가가 더 중요하군요!

소중한 의견 및 답변 고맙습니다! 👍 👍 👍

**Comment by znffl** [comment]
안녕하세요.
해당 이슈를 close 하겠습니다.
추가로 궁금한 점이 있으시면 open 부탁드립니다.
