### ISSUE TITLE
file /  edit /  view / selection / find / 등등 ...이 사라졌어요...

### ISSUE THREAD

**Issue by yunmossi** [codingeverybody/codingyahac#689]
# 해결하고자 하는 문제
atom 실행하면 상단에 file /  edit /  view / selection / find / 등등 ...이 있잖아요. 제가 이것저것 눌러보다가 전체화면 보기는 아니고 그 아래 거 였나? 그걸 눌렀더니 상단에 있던 메뉴들이 사라져서 아무리 찾아봐도 되돌리는 방법을 못 찾겠네요ㅠㅜ

# 시도해본 방법
이것저것 다 눌러본 것 같은데요...

**Comment by Hatser** [comment]
`Alt`+`V` 키를 누르시면 나타나는 보기(V) 항목 밑에서 메뉴바를 다시 켤 수 있습니다.

**Comment by yunmossi** [comment]
와 정말 감사합니다!! 진짜 한 1시간 동안 쩔쩔 맸었는데 감사합니다!!!ㅠㅜ
