### ISSUE TITLE
style의 특징별로 묶어서 관리할 수 있는 태그가 따로 있을까요?

### ISSUE THREAD

**Issue by SangYunLeee** [codingeverybody/codingyahac#69]
부트트랩의 NavBar 를 관리하는 스타일을 만들었습니다.
하지만 다른 css 스타일들과 섞여져서 관리하기가 불편합니다.
CSS 파일에내에서 Navbar만 따로 관리할 수 있게하는 마치, html의 div나 head, body와 같은 태그철이 있나요??!!!

**Comment by blackdew** [comment]
정확한 질문의 의도를 파악하지 못했습니다. 질문을 보완해주시면 조금 더 정확한 답을 드릴 수 있을 것 같아요. 

css 파일 내에서 스타일을 관리하는 방식은 
tag + class(.) + id(#) 세 가지를 조합을 통해 element를 특정하여 스타일을 줄 수 있습니다.

"css 선택자" 혹은 "css selector" 검색해보시면 도움이 되는 문서를 찾을 수 있을거에요.
