### ISSUE TITLE
안드로이드 'dp' 단위에 대한 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#690]
# 해결하고자 하는 문제

안녕하세요? 
안드로이드에서 API 버전에 따라 뷰들의 크기가 다르게 출력되는 문제에 대해 질문을 드리다 보니 'dp' 단위에 대해 제가 잘못 알고 있는 것 같아서 질문 드립니다.
제가 이해하고 있는 'dp'는 모든 디바이스들의 화면 크기에 맞게 자동으로 치수를 조절해주는 것으로 알고 있는데 테스트를 해 보니 좀 이상합니다.

![1](https://user-images.githubusercontent.com/43202563/62407582-d5769480-b5e4-11e9-87ab-df37680dcc03.jpg)
![2](https://user-images.githubusercontent.com/43202563/62407583-d5769480-b5e4-11e9-9b28-40d1ed17658a.jpg)

안드로이드스튜디오에서 버튼의 크기가 화면 height 방향으로 50% 정도를 차지할 수 있도록 '350dp'로 높이값을 입력했는데 'Nexus 5X API 28' 에서만 비슷한 화면이 출력되고 나머지 AVD에서는 모두 예상한 크기로 출력되지 않습니다.
화면 테두리 부분의 마진도 10dp로 지정했는데 오히려 화면 크기가 가장 큰 'Nexus 10'에서 가장 작아 보입니다.
치수를 어떻게 지정하면 모든 디바이스에서 동일한 화면을 얻을 수 있을까요?

그리고 'dp'의 개념에 대해 제가 오해하고 있는 부분도 가르쳐 주시면 감사하겠습니다.

# 코드 혹은 오류
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="10dp"
    android:orientation="vertical"
    tools:context=".lesson.Test">

    <Button
        android:layout_width="match_parent"
        android:layout_height="350dp" />
</LinearLayout>
```

```android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "net.awesomekorean.baguni"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```

# 환경
안드로이드

**Comment by Hatser** [comment]
`dp`는 `dpi`를 기준으로 크기가 정해집니다.

같은 화면이라도 `dpi`가 다르면 크기가 달라질 수 있어요.

`160 dpi`를 기준으로 하는데, 이 말은 `160 dpi` 에서 `1 인치`를 나타내기 위해 `1 픽셀`을 사용한다는 말입니다.

실제 화면 크기가 같은 `120 dpi` 에서는 `160 dpi`보다 작게 표현해야 같은 크기가 나올 수 있으므로

`120 / 160`을 한 `0.75 px`로 나타나게 됩니다.

자세한 정보는 [여기](https://developer.android.com/guide/topics/resources/more-resources.html#Dimension)와 [여기](https://developer.android.com/training/multiscreen/screendensities)서 찾아볼 수 있어요.

**Comment by kammaii** [comment]
> `dp`는 `dpi`를 기준으로 크기가 정해집니다.
> 
> 같은 화면이라도 `dpi`가 다르면 크기가 달라질 수 있어요.
> 
> `160 dpi`를 기준으로 하는데, 이 말은 `160 dpi` 에서 `1 인치`를 나타내기 위해 `160 픽셀`을 사용한다는 말입니다.
> 
> `160 dpi`인 화면과, 실제 화면 크기가 같은 `120 dpi` 화면이 있다고 할 때,
> `120 dpi`인 화면에서는 `160 dpi`보다 작게 표현해야 같은 물리적인 크기가 나올 수 있으므로
> 
> `120 / 160`을 한 `0.75 px`로,
> `240 dpi`에서는 `1.5 px`로 표시됩니다.
> 
> 자세한 정보는 [여기](https://developer.android.com/guide/topics/resources/more-resources.html#Dimension)와 [여기](https://developer.android.com/training/multiscreen/screendensities)서 찾아볼 수 있어요.

답변 감사합니다! 
위의 세 디바이스에서 같은 dp의 크기가 다르게 표시되는 이유는 디바이스 픽셀 밀도가
Nexus 10 > Nexus 5X > Nexus 5 이기 때문이라는 것을 이해했습니다.
그럼... 모든 디바이스에서 Nexus 5X와 같은 비율의 버튼을 출력하려면 어떻게 해야할까요?ㅠ

**Comment by Hatser** [comment]
[`Guideline`](https://developer.android.com/reference/android/support/constraint/Guideline.html)요소와 `ConstraintRayout`의 [Percent 관련 속성들](https://developer.android.com/reference/android/support/constraint/ConstraintLayout.html#percent-dimension)을 이용해보세요.

**Comment by progh2** [comment]
LinearLayout이라면 weightSum 속성으로 화면 전체 비율을 정의하고 그에 맞춘 비율로 나오게 할 수 있습니다. 

[여기](https://www.google.com/search?rlz=1C9BKJA_enKR803KR804&hl=ko&ei=4ZBFXczxAvTUmAX4_4qABg&q=Linear+Layour+wegithsum&oq=Linear+Layour+wegithsum&gs_l=mobile-gws-wiz-serp.3..0i13j0i13i30l3j0i13i5i30l2j33i160.7998.11360..11491...2.0..0.153.1476.9j6......0....1.........0i8i13i30j0i13i10j0i19j0i13i10i30i19j0i13i5i10i30i19.AWv2zX4ZreQ)를 누르셔서 Weightsum속성에 대해서 알아보세요~

**Comment by kammaii** [comment]
감사합니다! 이제 어떻게 화면을 구성해야 할 지 알 수 있을 것 같습니다! :)
