### ISSUE TITLE
이미지를 폴더에 넣어서 이미지태그로 링크를 타고 화면에 보여지게 하고 싶습니다.

### ISSUE THREAD

**Issue by leebingoo** [codingeverybody/codingyahac#691]
# 해결하고자 하는 문제

지금 생활코딩을 수강하고 있는데 여기서 이미지 태그에 대해서 
공부를 하게 되었습니다 그런데 이번에 이미지태그를 이용해서 화면에 
사진을 올리는 방법에 대해서 알게 되었는데 혹시 이미지를 폴더 안에 넣어두고 
그 폴더 안에 있는 사진을 활용해서 화면에 보여지게 하는 방법은 
어떻게 되는지 궁금합니다 아무래도 사이트를 하나 만들려고 하면 이미지를
정리하는게 훨씬 더 좋을것 같아서요 모쪼록 많은 답변 기다리겠습니다.

img라는 폴더를 만들고 그 안에 사진을 넣어 링크를 타고 화면에 보여지게 하려고 하였으나
실제로 잘 되지 않아서 질문드립니다.

# 코드 혹은 오류
```
<img src="../img/arch.jpg" width=450px alt="main">


```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

윈도우 10/html/atom

# 시도해본 방법

 태그 안에 슬레쉬를 사용하여 시도해보았으나 실제로 화면이 보여지지 않았습니다.

**Comment by smartbos** [comment]
경로 문제일 수 있을 것 같아요. 작업중이신 html 파일의 경로와 이미지 파일의 경로를 알려주시겠어요?

**Comment by leebingoo** [comment]
이미지 파일의 경로는 web/img/arch.jpg로 되어있고 
html 파일 경로는 web/main.html로 되어있습니다.

**Comment by Hatser** [comment]
```html
<img src="./img/arch.jpg" width=450px alt="main">
```

`../` 으로 돼 있었네요. `../`은 상위 디렉토리,

`./`은 현재 디렉토리를 가리킵니다.

**Comment by znffl** [comment]
해당 이슈를 close 합니다.
추가로 궁금한 사항이 있으시면 다시 open 부탁드립니다.
