### ISSUE TITLE
flask css 적용

### ISSUE THREAD

**Issue by HoWWWWWhy** [codingeverybody/codingyahac#693]
# 해결하고자 하는 문제
Flask를 이용해 웹페이지를 제작중인데요.
css파일이 한참 후에 업데이트가 되는 것 같습니다. 
실제로 network를 통해서 css 파일 코드를 봐도 방금 제가 바꾼 코드가 적용되어 있지 않습니다.
전에 cgi로 했을 때도 이런 현상이 일어났었는데
원래 이런 건가요? 아니면 해결책이 있을까요?

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
windows 10, python(html, css, javascript), flask

# 시도해본 방법
기다리는 방법 밖에는 모르겠습니다 ㅜㅜ

**Comment by Hatser** [comment]
#139 이 상황과 같은 경우인 것 같아요.

한 번 확인해보시기 바랍니다.

**Comment by HoWWWWWhy** [comment]
감사합니다!!!!
