### ISSUE TITLE
index.php파일에 db.php를 include하는 과정에서 에러가 납니다

### ISSUE THREAD

**Issue by duswls** [codingeverybody/codingyahac#695]
# 해결하고자 하는 문제

phpMyadmin으로 dp를 생성하고 db.php파일을 생성한 뒤
index.php에 db.php를 include하려하는데 디렉토리에러가 났습니다.

# 코드 혹은 오류

아래 코드이며

  include  $_SERVER['DOCUMENT_ROOT']."/db.php";

Warning: include(C:/Bitnami/wampstack-7.3.7-1/apache2/htdocs/db.php): failed to open stream: No such file or directory in C:\Bitnami\wampstack-7.3.7-1\apache2\htdocs\JinJinDiary\index.php on line 2
에러코드입니다.

디렉토리는 아무리봐도 문제가 없어 보이는데 왜 해결이 안될까요 ㅠㅠ

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by progh2** [comment]
‘’’
include $_SERVER['DOCUMENT_ROOT']."/JinJinDiary/db.php";
‘’’
로 변경해서 해보세요~

**Comment by duswls** [comment]
해결되었어요 정말 감사합니다~!
