### ISSUE TITLE
파이썬 코딩하는데 막힙니다.. (해결했습니다!)

### ISSUE THREAD

**Issue by ndk6879** [codingeverybody/codingyahac#696]
# 해결하고자 하는 문제
밑에는 스스로 하고 있는 프로젝트입니다. 
구현하고 싶은 것은 원하는 재료를 인풋으로 입력했을 때, 그 재료가 있는 메뉴들을 출력하는건데요.

하다보니 쉽게 막히는 부분이 많아서 딕셔너리의 value값에 재료를 명시할 때, '대표'재료들 값을 명시하게 되었고 , 이것을 수정하고 싶습니다.

i.e.) Menu라는 딕셔너리에 닭날개조림이라는 'key'가 있고 'value'는 ['닭', '파']가 있습니다. 
      원래는 value가 ['닭날개', '파']였는데, '닭'이라는 '대표'재료를 넣게 되었습니다. 그 이유는 '닭', '치 
      킨', '닭고기', 또는 '닭봉' 이라는 인풋을 넣었을 때 '닭날개조림'이라는 메뉴도 출력하고 싶어서 
       value에 '닭날개'대신 '닭'을 썻습니다.

함수의 시작부분부터 메뉴 위에 있는 if절(ingredient_dict[i] = i_set[0])만 수정하면 될 거 같습니다.
저 부분을 실행하면 {'대파': '파', '쪽파': '파', '작파': '파', '닭': '닭', '치킨': '닭', '닭고기': '닭', '닭봉': '닭'}이 나오는데
인풋을 닭봉을 넣어서 닭날개조림이 나오려면 

{'파' : '파', '파' : '대파', '파' : '쪽파', '파' : '작파',
'대파' : '파', '대파' : '대파', '대파': 쪽파', '대파': '작파',
'쪽파' : '파', '쪽파' : '대파', '쪽파' : '쪽파', '쪽파' : '작파'
.
.
.
'닭' : '닭봉', '치킨' : '닭봉', '닭고기' : '닭봉', '닭봉' : '닭봉'
} 이 출력되여할거 같습니다..

# 코드 혹은 오류
```

def conv_ingredients_to(재료_input):    
    ingredient_sets = [['파', '대파', '쪽파', '작파'], ['닭', '닭', '치킨', '닭고기', '닭봉']]       
    ingredient_dict = {}

    q = 0
    for i_set in ingredient_sets:           
        for i in i_set[1:]:                 
            ingredient_dict[i] = i_set[0]      

        if 재료_input in ingredient_dict:
            재료_input  = ingredient_dict[재료_input]

    Menu = {"양파덮밥" : ['양파', '계란'],
                "순두부찌개" : ['두부', '계란', '고기'],
                '고추장파닭' : ['파', '닭'],
                "쫄면" : ['쫄면', '양배추', '깻잎'],
                '부추리조또': ['부추', '쌀', '육수', '양파'],
                '닭볶음탕' : ['닭', '감자', '당근', '우동사리'],
                '폭찹 스테이크': ['돼지고기', '양송이버섯', '파프리카'],
                '국수' : ['육수', '소면', '김치', '계란', '만두'],
                '투움바 파스타' :['파스타면', '우유', '케찹', '갓뚜기 야채스프', '새우', '양송이버섯'],
                '콩나물 불고기' : ['백선생sty.', '승우아빠sty.'],
                '까르보나라': ['베이컨', '파마산치즈', '계란', '파스타면'],
                '우동볶음' : ['우동사리', '베이컨', '양배추'],
                '찜닭' : ['당면', '닭', '감자', '양배추'],
                '하이라이스' : ['팽이버섯', '양파', '얇은 돼지고기', '하이라이스'],
                '알리오 올리오': ['파스타면', '새우', '마늘', '페페론치노'],
                '등갈비 김치찜' : ['돼지고기', '김치', '콜드브루육수'],
                '밀푀유 나베': ['콜드브루육수', '양배추', '깻잎', '얇은 소고기'],
                '칠리새우' : ['새우', '감자전분', '기름', '양파'],
                '잡채' : ['파프리카', '양파', '버섯', '당면', '청경채', '얇은 고기'],
                '닭날개조림' : ['닭', '파'],
                '허니갈릭폭립' : ['폭립', '소스', '깻잎', '플레인 시리얼'],
                '탄탄면' : ['에그면', '다진고기', '청경채', '소스'],
                '불맛 짬뽕라면' : ['너구리', '파', '양배추' , '배추', '양파', '얇은 돼지고기' , '간 돼지고기'],
                '강식당 라면' : ['라면', '양념장', '양배추', '튀긴 고기', '계란']}

    i = 0 
    q = 0
    while (i < len(list(Menu.keys()))):
        if 재료_input == ((list(Menu.values())[i])[q]):         
            print(list(Menu.keys())[i])
        else:
            if q < len(list(Menu.values())[i])-1:
                q = q + 1
                continue

            else:
                i = i + 1
                q = 0
                continue
        i = i + 1
        q = 0



input_item = input('Enter an  ingredient to see Menu available: ')
재료_input = input_item
conv_ingredients_to(재료_input)
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Window 10, 파이썬 3.7.3 

# 시도해본 방법
ingredient_sets = [['파', '대파', '쪽파'], ['닭', '치킨', '닭고기', '닭봉']]
ingredient_dict = {}
i = 0

for i_sets in ingredient_sets:
        for q in i_sets:
            ingredient_dict[q] = i_sets[i]

        if q == (len(i_sets) - 1):
            i = i + 1
            q = 0    

print(ingredient_dict)

**Comment by TahoLee** [comment]
이부분은 데이터처리에 관한 것이네요. 일단 각각의 재료에 대해 카테고리를 정하고 접근하는것이 좋을거 같습니다. 
그러니까 '파' 라는 딕셔너리에 파,양파, 쪽파, 대파 등을 넣어두고, '닭' 이라는 딕셔너리에 치킨, 윙봉, 닭가슴, 닭날개 등을 넣어둡니다. 그리고, 검색할때 검색어들이 어떤 카테고리에 검색되는지 확인하고, 해당 카테고리에 있는 단어를 모두 동원해서 음식을 검색하면 원하시는 결과를 얻으실 수 있을거 같아요.
아마도 카테고리를 어떻게 구성하느냐에 따라서 검색에 대한 결과가 달라질 수 있을거 같아요.
그리고, 카테고리를 각 단어에 대해서 구성할 수도 있을거 같아요. 그렇게 되면 각 단어간의 유사성을 계산해서 좀더 의미있는 결과를 만들수도 있을거 같습니다.

**Comment by Hatser** [comment]
우선 생각해두셔야 할 점은,

파이썬의 dictionary는
`key`를 통해 `value`를 찾습니다.
하나의 딕셔너리에 동일한 `key`는 포함될 수 없습니다.


```py
dict1 = {}
dict1['파'] = '파'

print(dict1) # {'파': '파'}

dict1['닭'] = '닭'

print(dict1) # {'파': '파', '닭': '닭'}

dict1['닭'] = '치킨'

print(dict1) # {'파': '파', '닭': '치킨'}
```

호텔을 찾았는데 받은 방 열쇠가 503호인데,
503호가 여러개여선 어디를 들어가야 할 지 알 수 없겠죠?

마찬가지로 같은 이름의 `키`가 여러개가 있다면, 어떤 값을 가져와야 할 지 그 의미가 모호해지기 때문에 dictionary와 같은 `key-value` 구조는 동일한 키가 여러개 존재할 수 없습니다.

따라서 원하시는 결과의 구조를 다르게 생각하셔야 할 것 같아요.

먼저 IDLE 같은 간단한 파이썬 인터프리터를 통해 원하는 샘플 값들을 준비한 뒤, 머리속에 있는 시나리오로 생각했던 결과 구조를 테스트하다보면 어떤 구조로 만들어야 하겠다는 길이 보이게 될 거에요.
