### ISSUE TITLE
Atom editor 충돌

### ISSUE THREAD

**Issue by whynottodo** [codingeverybody/codingyahac#698]
#
atom editor 충돌창이 뜨는데, 해결 방법을 모르겠습니다. 

# 코드 혹은 오류

![image](https://user-images.githubusercontent.com/53653584/62412383-72b0e780-b63c-11e9-9efa-0f064f752ae3.png)

# 
window 7th

**Comment by progh2** [comment]
`사용자 폴더 안에 있는 .atom 디렉토리`를 찾아서 삭제하고 다시 실행해보세요~ 

> (%USERPROFILE%\.atom)

아마 `c:\Users\김민지\.atom` 일 것 같은데 한번 `.atom` 을 찾아서 삭제해보세요~

**Comment by whynottodo** [comment]
> `사용자 폴더 안에 있는 .atom 디렉토리`를 찾아서 삭제하고 다시 실행해보세요~
> 
> > (%USERPROFILE%.atom)
> 
> 아마 `c:\Users\김민지\.atom` 일 것 같은데 한번 `.atom` 을 찾아서 삭제해보세요~


답변 감사합니다!! 
지우고 실행해 보았는데, 폴더에 .atom 이 다시 생성되고 저 화면이 다시 뜹니다...

**Comment by progh2** [comment]
혹시 베타 버전을 쓰신건 아니죠? 
역시 해당 폴더를 지우고 에디터를 삭제한 다음 좀 더 옛날 버전으로 설치를 시도해보면 어떨까 합니다.

`AtomSetup-x64.exe` 파일을 다운받으면 됩니다. 
요거로도 안된다면 아톰 문제가 아니라 다른 뭔가가 있을꺼 같습니다. ㅠㅠ 

마지막 안정버전
https://github.com/atom/atom/releases/tag/v1.39.1

마지막 안정버전의 전버전 
https://github.com/atom/atom/releases/tag/v1.39.0

**Comment by progh2** [comment]
[이 글](https://discuss.atom.io/t/how-to-completely-uninstall-atom-from-windows/17338/5)을 참고해보면 다음 디렉토리들도 같이 삭제해봐야 할 것 같습니다.
`<user name>`을 `김민지`로 바꾸어서 해당 디렉토리를 삭제해보세요~ 
디렉토리가 안보인다면 [이글](https://www.google.com/search?q=%EC%9C%88%EB%8F%84%EC%9A%B0+%EC%88%A8%EC%9D%80+%ED%8C%8C%EC%9D%BC+%EB%B3%B4%EC%9D%B4%EA%B2%8C&rlz=1C9BKJA_enKR803KR804&oq=%EC%9C%88%EB%8F%84%EC%9A%B0+%EC%88%A8%EC%9D%80+%ED%8C%8C%EC%9D%BC+%EB%B3%B4%EC%9D%B4%EA%B2%8C&aqs=chrome..69i57.2892j0j4&hl=ko&sourceid=chrome-mobile&ie=UTF-8)을 읽어보고 숨겨진 디렉토리를 보이게 해서 삭제해보세요

```cmd
C:\Users\<user name>\.atom folder (settings, packages…).
C:\Users\<user name>\AppData\Local\atom (application itself)
C:\Users\<user name>\AppData\Roaming\Atom folder (for cache?)
```

**Comment by whynottodo** [comment]
> 그거야, 베타 버전을 쓰지 않아? 
> 해당 폴더를 지우고 지울 때 다음 단계를 수행하십시오 더 오래된 버전과 설치를 시도하십시오.
> 
> `AtomSetup-x64.exe`파일을 다운받습니다. 
> 다른 사람들도 싫어해. ㅠㅠ
> 
> 버전 별 다운로드 버전 
> https://github.com/atom/atom/releases/tag/v1.39.1
> 
> 마지막 버전의 이전 버전 
> https://github.com/atom/atom/releases/tag/v1.39.0

해결 했습니다!! 감사합니다!!
