### ISSUE TITLE
링크가 연결이 안됩니다.

### ISSUE THREAD

**Issue by neokkk** [codingeverybody/codingyahac#70]
깃허브를 처음 써봐서 제 깃에다가 일단 업로드를 해놨는데 
어떻게 가져오는지를 모르겠네요ㅜㅜ
3.html이 메인 페이지고 비트나미를 이용해 서버 제어 했습니다.
a 태그로 다른 페이지 링크를 걸었는데 제대로 작동이 안되는 것 같습니다.

**Comment by egoing** [comment]
@neokkk 님 가급적 질문을 하나씩 해주시면 더 좋을 것 같습니다. 질문을 좀 더 상세하게 해주시면 답변을 받으실 확률이 높아질 것 같습니다. 시간을 조금 더 들여서 질문을 부탁드려요. 질문하는 과정에서 스스로 알게 되는 것도 많거든요. 기다리겠습니다 :)

**Comment by egoing** [comment]
회신이 없으셔서 우선 답변을 닫아드릴께요. 
궁금한 점이 있으시면 질문을 보강해서 언제든지 다시 open해주세요~
