### ISSUE TITLE
프로젝트 처음입니다 도와주세요!

### ISSUE THREAD

**Issue by junpyo508** [codingeverybody/codingyahac#700]
진로가 인공지능 전문가라서 인공지능 쪽으로 프로젝트 해보고 싶어서
프로젝트를 신청했는데요 어디부터 어떻게 시작해야 할지 아예 감이 안오고 모르겠습니다
도와주세요 ..ㅠㅠ

**Comment by progh2** [comment]
프로젝트를 시작하기 전에 AI관련해서 어떠한 것을 익혔고 무엇을 할 수 있는지가 중요할 것 같습니다. 
그 외에 어떠한 것을 했었는지 배경을 좀 더 알려주시면 그에 적합한 방향을 답변드릴 수 있을 것 같아요.
아무것도 모른다면 우선 인공지능에 대해서 공부해서 내가 하고 싶은게 어떤 것인지부터 알아가는 방법도
있을 것 같고요..

**Comment by junpyo508** [comment]
아직 노베이스라서요.. ㅠㅠ 
챗봇을 한번 기획하고 개발해보고 싶습니다..

**Comment by studroid** [comment]
[구글에서 챗봇 만들기로 검색](https://www.google.com/search?q=%EC%B1%97%EB%B4%87+%EB%A7%8C%EB%93%A4%EA%B8%B0&oq=%EC%B1%97%EB%B4%87+%EB%A7%8C%EB%93%A4%EA%B8%B0&aqs=chrome.0.0l6.1408j0j1&sourceid=chrome&ie=UTF-8) 해보시면, 바로 따라 만들어보실 수 있는 여러 챗봇 예제들이 나오는 듯하네요!
마이크로소프트 봇 프레임워크 등을 이용해서 가장 가볍게 먼저 만들어보시고, 이후 기능을 추가해가면서 더 필요한 부분을 학습하시는 게 가장 빠른 길이지 않을까 생각해봅니다 :)

**Comment by znffl** [comment]
안녕하세요.
위에 이슈를 보니 챗봇관련 프로젝트를 시작하신것 같아 해당 이슈를 close 하겠습니다. 
추가로 궁금한 사항이 있으시면 다시 이슈를 open 부탁드립니다.
