### ISSUE TITLE
png파일 애니메이션에 keyPressed 주려고 하는데 코드 좀 도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by SujinBb** [codingeverybody/codingyahac#702]
# 해결하고자 하는 문제
자바스크립트 생초보자입이다. 
유튜브 보면서 오픈소스들로 겨우 코드 만들었습니다.
png파일 애니메이션에 keyPressed 주었는데 방향키가 먹히다 다시 처음위치로 돌아갑니다..
처음 위치로 안돌아가고 왼쪽 오른쪽 방향키 누르면 애니메이션이 왼쪽 오른쪽으로 이동하는 것으로 실행하려고 합니다.

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```
let hand;
let spritesheet;
let spritedata;
let animation =[];
let x =200;
let y =200;

function preload(){
  spritedata = loadJSON('handani.json');
  spritesheet = loadImage('handani.png');
}

function setup() {
createCanvas (1024,540);
 let frames = spritedata.frames;
 for (let i = 0; i< frames.length; i++){
  let pos= frames [i].position;
  let img = spritesheet.get(pos.x,pos.y,pos.w,pos.h);
  animation.push(img);
 }

console.log(animation);
}

function draw() {
background(255);

let index = floor (frameCount / 4) % animation.length;
image(animation[index],x-200,y-50,320,240);
  
  if (x >= 400){
   x = 0; 
  }
}

function keyPressed() {
  if (keyCode === LEFT_ARROW) {
    x = x - 20;
  } else if (keyCode === RIGHT_ARROW) {
    x = x + 20;
  }
}

# 환경 

# 시도해본 방법
https://sujinbb.github.io/web2/
자바스크립트atom에서 코드 짜서 github이용해서 구현해봤습니다.
들어가셔서 확인해주세요

**Comment by studroid** [comment]
우선 스프라이트 자체가 동일한 포지션에 출력되지 않고, 걷는 모션이 나오도록 x 좌표를 다르게 설정해놓고 있네요.
스프라이트 이미지를 편집해서 동일한 기준점으로 설정해야 더 자연스러울 듯하긴 하지만, 지금 코드에서는

```
if (x >= 400){
  x = 0;
}
```

위 부분을 제거해주시면 키보드 방향키를 누를 때 변경한 시작점이 유지됩니다.

게다가 지금 코드에서는 x 좌표가 400에 도달하면 0으로 바꾸는데, 원래 초기값은 200이라 처음 화면 로딩 후에 나오는 것보다도 더 왼쪽에서 시작하게 되네요

위에 내용 확인하셔서 수정해보세요! :)

**Comment by SujinBb** [comment]
우아 감사합니다!! 코드랑 스프라이트 모두 수정했어요!
만약 모바일에서 실행되게 하려면 어떤걸 추가 또는 공부해야하나요.. 어려울까요?

**Comment by studroid** [comment]
모바일에서는 터치 이벤트를 감지하여 처리해야 할 것이니, 자바스크립트의 이벤츠 처리 부분을 찾아보시면 ontouch 관련 자료들을 보실 수 있을 겁니다. ([예시](https://developer.mozilla.org/ko/docs/Web/API/Touch_events))

이를 바로 활용해서 모바일 지원을 추가할 수도 있을 것이고, 향후 더 많은 기능 추가를 위해 자바스크립트를 더 깊이 공부해보시는 것도 좋을 것 같습니다 :)

생활코딩에도 [자바스크립트 관련 심화 강의](https://opentutorials.org/course/1375)가 많으니, 참고해보세요!

**Comment by znffl** [comment]
해당 이슈를 close 하겠습니다.
추가 문의사항이나 궁금한점이 있으시면 다시 open 부탁드립니다.
