### ISSUE TITLE
html파일인데 주석이 웹 화면에 나타납니다. 

### ISSUE THREAD

**Issue by tomowhite** [codingeverybody/codingyahac#705]
# 해결하고자 하는 문제
link 태그 하단에 /* 주석 */ 을 넣었는데, 웹을 실행시키면 주석 글씨가 나타나버립니다. 
뭘 잘못했는지 모르게습니다. 

# 코드 혹은 오류
```
<!doctype html>
<html>
  <head>
    <title>WEB - CSS</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css">
    /* link  --> style.css를 불러와서 이 곳에 적용해줘 */
    /* 웹에서 우클릭>검사>하단 network탭> 어떤 파일을 불러오고 있는지 보여줌 */
  </head>
  <body>
    <h1><a href="index.html">WEB</a></h1>
    <div id="grid">
      <ol>
        <li><a href="1.html">HTML</a></li>
        <li><a href="2.html">CSS</a></li>
        <li><a href="3.html">JavaScript</a></li>
      </ol>
      <div id="article">
          <h2>CSS</h2>
          <p>
            Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation 
          </p>
      </div>
    </div>
   </body>
  </html>
```
# 환경
-사용중인 운영체제: window 10 home 64bit
-언어: html
-라이브러리의 버전: 아.. 초보라 이런거 잘 모릅니다.  atom과 아톰 안에서 emmet을 설치했습니다
-실행 브라우저: 버전 75.0.3770.142(공식 빌드) (64비트)

# 시도해본 방법
1) 주석을 head 태그에 넣어서 그렇다고 생각해서 맨 밑으로 옮겨봤으나, 맨밑에 글이 나타나더군요
2) /* 기호 다음에 스페이스가 있어야 한다고 생각해서, 처음부터 다시 작성했으나 . 주석글이 웹에 여전히 나타납니다. 
3) 주석기호가 두개여서 나타난다고 생각하여, 한개의 주석기호 안에 주석 글씨를 다 넣었다. 역시 동일 오류가 나옵니다.

**Comment by progh2** [comment]
html은 `<!— 주석내용 —>` 와 같이 주석을 사용합니다. 
/* 주석내용 */ 는 다른 일반적인 프로그래밍 언어에서 쓰는 것으로 html은 다릅니다. 

참고링크 : 
 https://www.google.com/search?q=html%EC%A3%BC%EC%84%9D&rlz=1C9BKJA_enKR846KR846&oq=html%EC%A3%BC%EC%84%9D&aqs=chrome..69i57.4214j0j7&hl=ko&sourceid=chrome-mobile&ie=UTF-8

**Comment by znffl** [comment]
해당 이슈를 close 합니다.
추가 궁금한 점이 있으시면 다시 open 부탁드립니다.
