### ISSUE TITLE
svg 태그로 line 그릴 때 좌표값 지정 관련 질문입니다.

### ISSUE THREAD

**Issue by JaicyChoi** [codingeverybody/codingyahac#706]
# 해결하고자 하는 문제
svg 태그로 원하는 길이 만큼의 직선을 그리려고 합니다. 좌표의 시작점이나 끝나는 지점에 수식을 넣고 싶은데 어떻게 해야할지 모르겠습니다. 

# 코드 혹은 오류
```
<svg width="283px" height="257px">
 <line x1="50" y1="130" x2="100" y2="130" stroke="blue" stroke-width="14"></line>
</svg>
```
예를 들면 위의 line 태그의 x2 속성에 100이라는 값 대신에 100+50이라는 수식을 넣어서, 입력하는 수식에 따라 직선의 길이를 변경하고 싶은데 x2속성에 수식을 넣으면 인식이 되지 않습니다.

수식 자체가 인식이 되지 않아 어떻게 해야 좋을지 잘 모르겠습니다.

# 환경
사용중인 운영체제, 언어 : Ubuntu, JavaScript

**Comment by Hatser** [comment]
HTML
```html
<svg width="283px" height="257px">
 <line class="line1" x1="50" y1="130" x2="100" y2="130" stroke="blue" stroke-width="14"></line>
</svg>
```

Javascript
```js
var line1 = document.getElementsByClassname[0];
line1.setAttribute('x2', 100 + 50)
```

순수 HTML에서는 수식을 사용할 수 없고, javascript를 이용해 식을 처리하셔야 합니다.

**Comment by JaicyChoi** [comment]
감사합니다! 덕분에 배워갑니다 :)
