### ISSUE TITLE
(android studio, Kotlin) fragment에서 DB작업 thread를 다룰 순 없나요?

### ISSUE THREAD

**Issue by 3always8** [codingeverybody/codingyahac#708]
# 해결하고자 하는 문제
DB 작업을 하는 thread를 fragment 에서 실행시키면 오류가 납니다.
아예 구조를 바꿔서 어떻게든 MainActivity에서 작업해야 할까요?
아니면 thread를 대체하는 방법이 있는지 궁금합니다.

# 코드 혹은 오류
    java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-3,5,main] that has not called Looper.prepare()

# 환경
Kotlin 3.4
Android Studio

**Comment by progh2** [comment]
db접속 문제라기보다는 스레드 코드가 문제일 걱 같습니다만 소스가 없으니 확신은 없네요  
아부튼 스레들 대체하려면
asynctask를 사용하면 될듯합니다.

https://www.google.com/search?q=asynctask&oq=asynctask&aqs=chrome..69i57j0l3.4078j0j7&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8

**Comment by 3always8** [comment]
말씀하신대로 스레드 코드를 수정해서 해결했습니다!
덕분에 asynctask 를 배워갑니다..
감사합니다!
