### ISSUE TITLE
(CSS)이걸 구체적으로 어떻게 표현해야 될지 모르겟는데... 질문이 있습니다!

### ISSUE THREAD

**Issue by jjolbo** [codingeverybody/codingyahac#71]
1. table border="1px"; solid black; style="border-collapse: collapse; width: 45%"
2. table style="border: 1px solid black; width:45%; border-collapse: collapse;"

이 둘의 차이가 정확하게 무엇인가요?
구글에 어떻게 검색해야될지 모르겠습니다.
style 안에 넣으면 table 전체만 적용이 되고 그 안에 있는 각 <tr> 태그에는 적용되지 않는 것을 보았습니다. border:이랑 border=는 무슨 차이인가요? 너무 작은 건데.. 이런것도 물어봐도 되나요?

**Comment by blackdew** [comment]
table tag의 속성으로 border를 사용하는 경우는 border=""으로 사용하게 되고요. 
table의 style 속성(css)내에서 표현할 때에 border:1px 이런식으로 사용하게 됩니다. 

1번에 적어주신 코드는 사실상 좀 오류가 있는 코드에요. 보정을 하자면 '; solid black;' 이 부분은 html의 문법에 어긋나게 들어가 있는 상황입니다. <table border="1px" style="border-collapse: collapse; width: 45%"> 이렇게 적어주셔야 맞아요. 

html의 문법도 발전을 거치게 됩니다. html이 등장하라 당시에는 문서의 "모양"과 관련된 코드들도 태그 혹은 태그의 속성으로 지원을 했었습니다. font tag 같은 녀석은 대표적인 태그죠. 문서의 내용가 관련이 없이 글의 폰트 모양에만 관련이 있어요. 태그의 border라는 속성도 '모양'(외곽선을 그릴지 말지)과 관련된 속성이지요. border는 여러 table말고도 다른 태그에서 사용할 수 있습니다. 

그런데, 웹이 발전하면서 웹 문서의 디자인이 중요한 요소가 됩니다. 그래서 디자인과 관련된 태그와 속성들이 html을 뒤덥기 시작했어요. 태그가 텍스트의 의미를 표현하기 보다 보여지는 모양에 집중하게 되다보니 어느 시점부터는 html의 본질을 다시 고민하기 시작했고, 디자인 요소를 html 내에서 분리하는 결정이 내려지게 됩니다. 그것이 CSS의 등장이지요. 
때문에, 현재의 html 내에서 모양과 관련된 태그(font 등)나 속성(border 등)이 여전히 사용가능하지만 그 사용을 지양하고 있습니다. 그리고 디자인과 관련된 내용은 css 에서 처리하는 것을 권장하고 있지요. 

그래서 1번을 사용하지 마시고 2번을 사용하기를 권해드립니다. :)

**Comment by jjolbo** [comment]
감사합니다! 제가 어떤 부분을 틀렸는지도 몰랐네요.. 화면에 잘 나오면 어떤 부분이 틀렸는지 찾아내는것이 힘든 것 같아요:(
