### ISSUE TITLE
MySQL Workbench에 csv 파일 import 할 때 에러가 떠요 ㅠㅠ

### ISSUE THREAD

**Issue by marcwoo94** [codingeverybody/codingyahac#710]
# 해결하고자 하는 문제

도서관 서가 책섞임 정도를 분석해보고 싶어 프로그램을 만들고 있습니다.  일단 도서관이 소장 중인 책들을 데이터베이스화 해보고 있습니다. csv 파일은 아래와 같이 생겼습니다.

![Capture2](https://user-images.githubusercontent.com/53594727/62422956-b9164d00-b6f5-11e9-8b2b-4d364311f061.PNG)

Workbench에서 csv파일을 import 하려고 하는데 자꾸 아래와 같은 에러가 발생합니다.

![Capture1](https://user-images.githubusercontent.com/53594727/62422950-a865d700-b6f5-11e9-99fe-6b4340639921.PNG)

한글이 포함 되어 Schema와 Table 설정을 전부 아래와 같이 UTF-8로 했는데 같은 에러가 계속 발생합니다.

![Capture](https://user-images.githubusercontent.com/53594727/62422964-e6fb9180-b6f5-11e9-9446-63cbe49b4b05.PNG)

# 환경
Windows 10에서 MySQL과 Workbench를 사용중입니다.

# 시도해본 방법
Non-ASCII 코드가 들어있는 것 같아 엑셀 내에서 CLEAN()함수를 이용하여 Non-ASCII코드들을 제거 후 새로 파일을 만들어봐도 같은 문제가 계속 발생합니다... ㅠㅠ

**Comment by TahoLee** [comment]
csv임포트 과정에서 에러가 나면 상당히 짜증이 납니다. 편하게 작업하려고 시도하는데, 작동이 안되는 상황이라서요. 
일단 여기서는 8번째줄에 471이라는 숫자 앞에 " 가 있는데, 상응하는 " 가 없는 거 같아요. 따옴표를 열고 닫는데 잘 맞춰 주시면 좋을거 같습니다. 
문제가 될거 같으면 전체 내용에서 따옴표를 모두 제거하고, 모든 항목에 따옴표를 넣어보는것을 추천 드리겠습니다. 

python 같은것으로 한다면 
for line in file.readlines():
    line.strip().replace('"','')
    items =  line.split(',')
    print ( ','.join([ '"%s"'%x for x in items ]) )

이런 식으로 하면 될거 같습니다. 
코드는 그냥 막써서 한번 확인해 보셔야 할거 같네요 ㅎㅎ

**Comment by marcwoo94** [comment]
@TahoLee ㅠㅠㅠㅠ 감사합니다. 답변해주신 내용 중에서 힌트를 얻어서 해결했어요. 파이썬으로도 돌려보고 이러저리 헤매다가 결국 json 파일로 import하니까 해결됐어요 :) csv로는 왜 안 되는지 아직 모르지만요...
