### ISSUE TITLE
react api list 호출

### ISSUE THREAD

**Issue by MythicDawn24** [codingeverybody/codingyahac#711]
# 해결하고자 하는 문제
![photo](https://user-images.githubusercontent.com/53366868/62425587-2cc85200-b716-11e9-9a55-6343eaf78f92.png)

react 로 google book api를 호출하는데  
.then(json =>json.items)
이렇게하면 items안에있는건 가져올수있는데
items안에있는 list는 어떻게가져오나요 
예를들어  items 안에있는 volumeInfo는
json.items.volumeInfo이렇게 하면 언디파인드 뜨던데 
어떻게하나요?...

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by yoobato** [comment]
`json.items[0].volumeInfo` 이렇게 해보시겠어요? `items`는 배열 타입인 것 같습니다!

**Comment by MythicDawn24** [comment]
감사합니다
