### ISSUE TITLE
안드로이드 getResources() 에러 문제

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#712]
# 해결하고자 하는 문제

안녕하세요? 

코드에서 뷰를 만들 때 뷰의 크기를 pixel 단위로 입력해야 해서 
검색을 통해 dp를 pixel로 바꾸는 코드를 찾았습니다.
지금까지 잘 사용하고 있는데 점점 사용 빈도가 늘어나서
이 코드를 따로 class의 static 메소드로 만들어 필요할 때마다 간편하게 사용하고 싶습니다.

그래서 아래와 같이 class를 만들었는데 getResources()에서 에러가 발생합니다.
해당 class에 activity가 없어서 그런 것 같은데 어떻게 해결해야 할지 모르겠습니다.

# 코드 혹은 오류
```
  public class DpToPx {

    public static int getDpToPx(int dp) {

        final float scale = getResources().getDisplayMetrics().density;
        int pixels = (int) (dp * scale + 0.5f);

        return pixels;
    }

}

```

# 환경
안드로이드

**Comment by Hatser** [comment]
static 메서드의 매개변수에로 호출하고자 하는 부분의 getResources()를 받도록 하시는 건 어떤가요?
```js
public static int getDpToPx(int dp, Resources rsrc) {

        final float scale = rsrc.getDisplayMetrics().density;
        int pixels = (int) (dp * scale + 0.5f);

        return pixels;
    }
```

**Comment by kammaii** [comment]
> static 메서드의 매개변수로 호출하고자 하는 부분의 getResources()를 받도록 하시는 건 어떤가요?
> 
> ```java
> public static int getDpToPx(Resources rsrc, int dp) {
> 
>         final float scale = rsrc.getDisplayMetrics().density;
>         int pixels = (int) (dp * scale + 0.5f);
> 
>         return pixels;
>     }
> ```

해결되었습니다! 감사합니다! :)
