### ISSUE TITLE
django-crontab 에러 질문드립니다.

### ISSUE THREAD

**Issue by gustjd887** [codingeverybody/codingyahac#715]
# 해결하고자 하는 문제
파이썬 스크립트를 주기적으로 실행하기 위해 pip로 django-crontab 패키지를 설치 후 settings.py에 CRONJOBS를 추가 하였습니다.
하지만 적용 시키는 커맨드 입력 시 에러가 납니다.

# 코드 혹은 오류
--------setting.py--------
```
with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as f:
    with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as y:
        CRONJOBS = [
                str((f.readline().rstrip(), f.readline().rstrip()),) for i in range(len(y.readlines())//2)
        ]
```
--------적용 커맨드와 에러--------
```
gustjd887@DELL:~/.pyenv/versions/issue/issue$ python manage.py crontab add
System check identified some issues:

  adding cronjob: (d5d6862038cc59d4a3250b460fbbd0b4) -> ('* * * * *', 'ou.bs4_ou')
  adding cronjob: (7a84fa1b01977b36b79f1dc7f0fae171) -> ('* * * * *', 'ou.bs4_test')
"/tmp/tmp5uyefnl8":0: bad minute
errors in crontab file, can't install.
```
# 환경
운영체제 : Ubuntu 18.04 LTS
언어 : python 3.6.8
라이브러리 버전 : 
django 2.2.4
django-crontab 0.7.1

# 시도해본 방법
settings.py의 CRONJOBS 코드 중
str((f.readline().rstrip(), f.readline().rstrip()),) for i in range(len(y.readlines())//2)을 (f.readline().rstrip(), f.readline().rstrip()), 으로 변경하면 정상적으로 적용됩니다.
앞에 str을 써서 문제가 되는건지, 뭐때문인지 막막합니다.

--------setting.py--------
```
with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as f:
    with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as y:
        CRONJOBS = [
                (f.readline().rstrip(), f.readline().rstrip()),
                (f.readline().rstrip(), f.readline().rstrip()),
        ]
```
--------적용 커맨드 성공--------
```
gustjd887@DELL:~/.pyenv/versions/issue/issue$ python manage.py crontab add
System check identified some issues:

  adding cronjob: (702a25bbd38f772a121c85564cf3c347) -> ('* * * * *', 'ou.bs4_ou')
  adding cronjob: (3f1e72ffe7beadfb63d8461e2d89c027) -> ('* * * * *', 'ou.bs4_test')
```
추가적으로 rsyslog에서 cron 로그를 활성화하여 /var/log/cron.log를 확인 해 보았으나,
python manage.py crontab add 명령으로 적용 실패 시에는 로그가 남지 않았습니다.

**Comment by TahoLee** [comment]
성공하는 경우도 있는것으로 보아 문자열을 다루는 부분에 있어서 문제가 있을수 있는거 같아요. 
f와 y로 표시되는 cron_settings.txt 파일안에 어떤 내용이 있는지에 따라서 어떻게 명령어를 넣어야 하는지 알려드릴 수 있을거 같습니다. 
그리고, 현재 * * * * * 로 설정된 주기는 1분간격으로 명령어를 실행합니다. 이경우 실행하는 내용이 얼마나 많은 일을 하는지에 따라서 명령어가 끝나기도 전에 또 실행되면서 문제가 될 수도 있습니다. 한번쯤 확인해 보는게 좋을거 같아요

크론탭은 사실 리눅스등에서 crontab 명령어로 다루는게 더 수월할 수도 있습니다( 파일경로와 실행상의 환경문제등이 고려되어야 하기에 독립적으로 실행하는게 평할 수 있습니다)

**Comment by gustjd887** [comment]
> 성공하는 경우도 있는것으로 보아 문자열을 다루는 부분에 있어서 문제가 있을수 있는거 같아요.
> f와 y로 표시되는 cron_settings.txt 파일안에 어떤 내용이 있는지에 따라서 어떻게 명령어를 넣어야 하는지 알려드릴 수 있을거 같습니다.
> 그리고, 현재 * * * * * 로 설정된 주기는 1분간격으로 명령어를 실행합니다. 이경우 실행하는 내용이 얼마나 많은 일을 하는지에 따라서 명령어가 끝나기도 전에 또 실행되면서 문제가 될 수도 있습니다. 한번쯤 확인해 보는게 좋을거 같아요
> 
> 크론탭은 사실 리눅스등에서 crontab 명령어로 다루는게 더 수월할 수도 있습니다( 파일경로와 실행상의 환경문제등이 고려되어야 하기에 독립적으로 실행하는게 평할 수 있습니다)

우선 답변 감사드립니다.
결론적으로 str()을 사용할 때 양쪽 끝에 감싸지는 "" 문자 문제였습니다.

str()을 사용할 경우 양쪽 끝에 ""로 감싸지게 되어서, 적용 명령(python manage.py crontab add)이 실패하게 되어도 출력되는 문자가 토씨 하나 안틀리고 성공한 것 처럼 보여 되게 많이 헤맸습니다.

그리고 cron 서비스를 정지시킨 상태에서 crontab에 추가되는 것만을 테스트 하기 위해 * * * * *을 사용하였습니다. 이 주기는 DB에서 값을 불러와 파일에 기록하게 되어 있어 나중에 수정 예정입니다.

현재는 해결된 상태이며, 아래와 같이 변경하였습니다.
--------setting.py--------
```
with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as f:
    with open(os.path.join(BASE_DIR, 'cron_setting.txt')) as y:
        CRONJOBS = [ (f.readline().rstrip(), f.readline().rstrip()) for i in range(len(y.readlines())//2) ]
```
--------cron_setting.txt--------
* * * * *
ou.bs4_ou
* * * * *
ou.bs4_test

--------적용/삭제 커맨드 확인--------
```
gustjd887@DELL:~/.pyenv/versions/issue/issue$ python manage.py crontab add
System check identified some issues:

  adding cronjob: (702a25bbd38f772a121c85564cf3c347) -> ('* * * * *', 'ou.bs4_ou')
  adding cronjob: (3f1e72ffe7beadfb63d8461e2d89c027) -> ('* * * * *', 'ou.bs4_test')

gustjd887@DELL:~/.pyenv/versions/issue/issue$ python manage.py crontab remove
System check identified some issues:

removing cronjob: (702a25bbd38f772a121c85564cf3c347) -> ('* * * * *', 'ou.bs4_ou')
removing cronjob: (3f1e72ffe7beadfb63d8461e2d89c027) -> ('* * * * *', 'ou.bs4_test')
```
