### ISSUE TITLE
옛날 아이프레임  같은건 어떻게 구현 하나요...? (상단에 있는 메뉴 같은거요...)

### ISSUE THREAD

**Issue by gmkjh74** [codingeverybody/codingyahac#72]
이고잉님 강의 하실때 중복을 없애라는 말씀을 많이 하시는데요...

Web을 처음 시작하는 지금 가장 궁금한 부분이 
'''    
    <ol>
      <li><a href="1.html">HTML</a></li>
      <li><a href="2.html">CSS</a></li>
      <li><a href="3.html">JavaScript</a></li>
    </ol>
[강의] https://opentutorials.org/course/3086/18327 
강의 하실때 저 코드를 그대로 보이게 하는 법을 말씀해 주셨는데 기억이 나지 않네요..ㅠㅠ
업무 시간이 시작되서 일단 있다가 찾아 봐야 겠네요

위의 코드 내용이 1.html, 2.html, 3.html ~~~ 모든 웹페이지에 들어가 있습니다.
만일 메뉴가 많아지면 또는 수정이 필요하면 모든 페이지를 수정해야 합니다.
이런 페이지는 어떻게 구성 하는건가요?

전에 학교 다닐때는 iframe를 사용했던것 같은데 말이죠...요즘은 그냥 페이지에 다 넣어 버리내요..
제가 CS쪽만 해서 이런걸 웹개발자에게 물어 보면 그냥 위 방식대로 하라고 하네요...

추가적으로
항상 제가 궁금했던 왜 이걸 사용하지, 왜 이렇게 코딩 하지, 이 차이가 뭐지 하는 궁금증이 많이 풀렸습니다.

수고 하시고..항상 좋은 강의 실속있는 강의 감사 드립니다.

**Comment by smartbos** [comment]
요즘에는 레이아웃 기능을 제공하는 템플릿 엔진을 사용하는 경우가 많습니다.

템플릿 엔진에서는 말씀하신 점을 주로 상속 개념으로 해결합니다.
- 부모 페이지를 만들고, 부모 페이지에는 여러 자식 페이지에서 공통으로 사용할 코드를 넣습니다. 그리고 자식 페이지에서 바뀔 부분은 비워둡니다.
- 자식 페이지에서는 부모 페이지를 상속 받고, 부모 페이지에서 비워둔 부분을 채웁니다.

아래는 인기있는 템플릿 엔진인 Twig의 상속 기능에 대한 설명이 나오는 페이지입니다. 관심있으시면 한 번 살펴보세요. 
https://twig.symfony.com/doc/2.x/tags/extends.html

위 문서가 영문이라 조금 부담 되신다면 아래 문서를 보셔도 어떤 개념인지 파악하는데 도움이 될 것 같습니다.  요즘 가장 인기있는 PHP 프레임워크인 라라벨은 블레이드라는 자체 템플릿 엔진의 상속 기능에 대한 설명인데, 한글로 되어 있어서 조금 더 쉽게 이해하실 수 있을 것 같습니다. 
https://laravel.kr/docs/5.5/blade#template-inheritance

**Comment by dongheegy** [comment]
코드의 중복을 해결하는 단순한 방법은 아래의 강의를 참고하시는 게 어떻까 합니다.
[웹 애플리케이션 만들기 - PHP 실습](https://opentutorials.org/course/1688/9383)

**Comment by gmkjh74** [comment]
답변달아 주신분 감사 드립니다.
아래처럼 답변 달면 되는지 모르겠네요..

@smartbos 웹도 상속으로 구현하면 된다는 것을 알았네요...그렇게 하면 될거라는 생각은 했었는데 주변에 물어 보면 자꾸 CS에 기반해서 웹을 생각하지 말로고만 해서요..
분명 크롬이나 대형 Web Application을 보면 어떤 방법이 있을것이라는 제 생각을 떨쳐 버릴수 없었거등요..
@dongheegy 그리고 제가 아직 JavaScript 강의를 듣고 있어서요...조금 있으면 나오는 거였네요... 감사 합니다.
