### ISSUE TITLE
루비 파이썬 문법 질문.

### ISSUE THREAD

**Issue by XCIXI** [codingeverybody/codingyahac#724]
# 해결하고자 하는 문제

hello airpods 라는 문장을 대문자로 치환할시 루비의 경우 upcase 파이썬의 경우 upper라는 문법

이 있는데 이 up이라는 뜻이 뭔가를 올려준다는 뜻인가요?

C언어에서 쓰이는 문법 중  sub라는 문법의 경우 루비에서 쓰이는 문법과 틀린지요?

**Comment by ghdalsrldi** [comment]
uppercase는 대문자를 뜻하고
lowercase는 소문자를 뜻하기 때문에
upcase, upper라는 이름으로 만들어 진 것이라 생각됩니다.

**Comment by yoobato** [comment]
혹시, C언어에서 쓰이는 문법 중 sub 라는 문법이 어떤 것인지 알려주시겠어요
루비에서의 [sub](https://ruby-doc.org/core-2.4.2/String.html#method-i-sub)는 문자열의 일부분을 정규식으로 찾아, 다른 문자열로 치환하는 함수입니다!

**Comment by XCIXI** [comment]
> 
> 
> 혹시, C언어에서 쓰이는 문법 중 sub 라는 문법이 어떤 것인지 알려주시겠어요
> 루비에서의 [sub](https://ruby-doc.org/core-2.4.2/String.html#method-i-sub)는 문자열의 일부분을 정규식으로 찾아, 다른 문자열로 치환하는 함수입니다!

사용자 정의 함수라고 알고 있습니다...

**Comment by Hatser** [comment]
> > 혹시, C언어에서 쓰이는 문법 중 sub 라는 문법이 어떤 것인지 알려주시겠어요
> > 루비에서의 [sub](https://ruby-doc.org/core-2.4.2/String.html#method-i-sub)는 문자열의 일부분을 정규식으로 찾아, 다른 문자열로 치환하는 함수입니다!
> 
> 사용자 정의 함수라고 알고 있습니다...

사용자 정의 함수는 어떤 모습으로 호출되고, 어떤 동작을 할 지 프로그램을 짜는 사람이 정할 수 있습니다.

보셨던 함수의 이름이 sub였던 것 같은데, 이 함수명도 기존에 존재하는 이름들과 겹치지 않고, 언어의 규칙을 지키는 선에서 마음대로 지을 수 있습니다.
