### ISSUE TITLE
웹에서 음악 재생을 어떻게 구현하는지 궁금합니다

### ISSUE THREAD

**Issue by LuiGee3471** [codingeverybody/codingyahac#726]
음악 재생과 관련된 웹앱을 만들고 있는데요. 음악이 재생되고 끝나면 다른 음악으로 넘어가고 이런 것들을 보통 어떻게 구현하는지 궁금합니다.

지금 생각 중인 건

1. JavaScript로 audio 태그의 src를 바꿔가며 새로 재생한다. (또는 audio태그를 새로 생성)
2. 생활코딩 '겁나 빠른 웹 레시피'에 있는 history 객체를 이용한다.

정도인데 보통 음악 서비스들은 이런 것을 어떻게 구현하는지 궁금하네요.

#환경
Node.js와 MongoDB를 이용해 구현할 생각입니다.

**Comment by yoobato** [comment]
이럴 때는, 보통 콜백(callback) 함수를 사용합니다. 콜백 함수란, 어떤 특정 이벤트가 발생했을 때, 호출되는 함수입니다.

예를 들어, audio 태그에는, 오디오 재생이 종료되었을 때, onended 라는 콜백 함수가 호출됩니다.
따라서, javascript에서 onended 콜백이 호출되었을 때, 다음 음악을 재생하게 하는 코드를 추가하시면 될 것 같습니다.

https://www.w3schools.com/tags/av_event_ended.asp 이 링크를 참고해보세요!

**Comment by Hatser** [comment]
[이 곳](https://webaudio.github.io/web-audio-api/)에 web에서 Audio 관련 기능들을 이용하는 자세한 예제들이 나와있습니다.

단순히

```js
var a = new Audio();
...
a.play()
```
으로 실행하는 방법도 있으나,


오디오 API 노드들을 직접 조작해 사용하는 것이 다양한 기능을 활용할 수 있고, 확장 가능성이 있어 많이 사용하는 편입니다.

간단한 예제를 같이 올려드려요

```js
/* 오디오 컨텍스트 생성 */
const context = new AudioContext();
function setSound()
{
  var url = "https://open.scdn.co/static/audio/fta-en-ca.mp3";
  /* AJAX 요청 생성 */
  var request = new XMLHttpRequest();
  request.open("GET", url, true);
  request.responseType = "arraybuffer";

  /* AJAX 요청의 콜백 */
  request.onload = function()
  {
     /* 사운드의 버퍼 소스 생성 */
     soundSource = context.createBufferSource();

     /* 응답 데이터를 PCM 오디오 데이터로 디코드하는 비동기 함수 */
     context.decodeAudioData(request.response, function(buffer)
     {
		/* 디코드된 오디오 데이터를 버퍼 소스의 버퍼 데이터로 쓴다 */
        bufferData = buffer;
        soundSource.buffer = bufferData;
		/* 버퍼 소스에 컨텍스트를 연결한다. */
        soundSource.connect(context.destination);
		/* 버퍼 소스 시작(사운드 재생) */
        soundSource.start(0);
     }, this.onDecodeError);
  };
  /* AJAX 요청 전송 */
  request.send();
}
```

**Comment by LuiGee3471** [comment]
두분 모두 감사합니다. 참고해서 구현하고 있습니다
