### ISSUE TITLE
안드로이드 텍스트뷰 하이라이트에 클릭 이벤트 설정하는 법

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#728]
# 해결하고자 하는 문제

안녕하세요?

텍스트뷰에 짧은 글을 출력해서 특정 단어에 하이라이트 표시를 하고 
그 하이라이트 된 단어에 클릭 이벤트를 추가하고 싶습니다.
setSpan을 사용하여 하이라이트 표시를 하는 방법은 찾았는데 (HTML보다 훨씬 복잡하네요 ㅜ)
그 하이라이트에 클릭 이벤트를 추가하는 방법은 무엇이 있는지 가르쳐주시면 감사하겠습니다.

# 환경
안드로이드

**Comment by InyoungAum** [comment]
안녕하세요 

Android 의 ClickableSpan을 사용하면 해결이 가능해보입니다. 

https://android--examples.blogspot.com/2016/08/android-clickablespan-example.html

다음의 링크가 도움이 될 것 같네요!

**Comment by kammaii** [comment]
> 안녕하세요
> 
> Android 의 ClickableSpan을 사용하면 해결이 가능해보입니다.
> 
> https://android--examples.blogspot.com/2016/08/android-clickablespan-example.html
> 
> 다음의 링크가 도움이 될 것 같네요!

빠른 답변 감사합니다! :)

알려주신 대로 코드를 잘 작성했는데, 추가 질문이 생겼습니다.
동일한 문자열에서 여러개의 clickableSpan을 설정하려면 어떻게 해야 할까요?
```
        SpannableStringBuilder span = new SpannableStringBuilder(reading.getArticle());
        span.setSpan(clickableSpan, 10,20,0);
        span.setSpan(clickableSpan,30,40,0);
        article.setText(span);
        article.setMovementMethod(LinkMovementMethod.getInstance());
```
위와 같이 코드를 작성하니 문자열 10~20 부분은 설정이 되지 않습니다.
혹시 각각에 대한 SpannableStringBuilder를 따로 생성해줘야 하나요?

**Comment by yoobato** [comment]
> > 안녕하세요
> > Android 의 ClickableSpan을 사용하면 해결이 가능해보입니다.
> > https://android--examples.blogspot.com/2016/08/android-clickablespan-example.html
> > 다음의 링크가 도움이 될 것 같네요!
> 
> 빠른 답변 감사합니다! :)
> 
> 알려주신 대로 코드를 잘 작성했는데, 추가 질문이 생겼습니다.
> 동일한 문자열에서 여러개의 clickableSpan을 설정하려면 어떻게 해야 할까요?
> 
> ```
>         SpannableStringBuilder span = new SpannableStringBuilder(reading.getArticle());
>         span.setSpan(clickableSpan, 10,20,0);
>         span.setSpan(clickableSpan,30,40,0);
>         article.setText(span);
>         article.setMovementMethod(LinkMovementMethod.getInstance());
> ```
> 
> 위와 같이 코드를 작성하니 문자열 10~20 부분은 설정이 되지 않습니다.
> 혹시 각각에 대한 SpannableStringBuilder를 따로 생성해줘야 하나요?

동일한 Span을 여러번 쓸 수는 없습니다. 따라서, 동일한 내용의 Span이어도, 매번 유니크한 Span을 생성해주어야 합니다!

```java
span.setSpan(new ClickableSpan(), 10, 20, 0);
span.setSpan(new ClickableSpan(), 30, 40, 0);
```

**Comment by kammaii** [comment]
> > > 안녕하세요
> > > Android 의 ClickableSpan을 사용하면 해결이 가능해보입니다.
> > > https://android--examples.blogspot.com/2016/08/android-clickablespan-example.html
> > > 다음의 링크가 도움이 될 것 같네요!
> > 
> > 
> > 빠른 답변 감사합니다! :)
> > 알려주신 대로 코드를 잘 작성했는데, 추가 질문이 생겼습니다.
> > 동일한 문자열에서 여러개의 clickableSpan을 설정하려면 어떻게 해야 할까요?
> > ```
> >         SpannableStringBuilder span = new SpannableStringBuilder(reading.getArticle());
> >         span.setSpan(clickableSpan, 10,20,0);
> >         span.setSpan(clickableSpan,30,40,0);
> >         article.setText(span);
> >         article.setMovementMethod(LinkMovementMethod.getInstance());
> > ```
> > 
> > 
> > 위와 같이 코드를 작성하니 문자열 10~20 부분은 설정이 되지 않습니다.
> > 혹시 각각에 대한 SpannableStringBuilder를 따로 생성해줘야 하나요?
> 
> 동일한 Span을 여러번 쓸 수는 없습니다. 따라서, 동일한 내용의 Span이어도, 매번 유니크한 Span을 생성해주어야 합니다!
> 
> ```java
> span.setSpan(new ClickableSpan(), 10, 20, 0);
> span.setSpan(new ClickableSpan(), 30, 40, 0);
> ```

감사합니다!! :)
