### ISSUE TITLE
nodejs alert후 redirect 하는방법 

### ISSUE THREAD

**Issue by cokemania2** [codingeverybody/codingyahac#729]
안녕하세요 nodejs로 간단한 홈페이지를 만들고있는데
nodejs 자체에 alert기능이없어서 
스크립트문으로 alert문을 넣어야하는데
어떻게해야 좋은방법으로 할수있을지 검색을해도 애매하게 나와서
질문드립니다!  

제가하련느것은 session값이 없으면 로그인해주세요 
이런정도로만 뜨게하는것입니다

**Comment by yoobato** [comment]
이전에 같은 질문이 올라온 적이 있습니다! 

https://github.com/codingeverybody/codingyahac/issues/440 여기를 참고해보세요!

**Comment by cokemania2** [comment]
감사합니다
