### ISSUE TITLE
CSS 파일 관리

### ISSUE THREAD

**Issue by SangYunLeee** [codingeverybody/codingyahac#73]
.pa5{
					padding-left: 5%;
    			        padding-right: 5%;
				}

				.navbar-default {
				    background-color: #e3f2fd;
				    border-color: #e3f2fd;
				    border-radius: 0;
				}
				.navbar-default .navbar-brand,
				.navbar-default .navbar-brand:hover,
				.navbar-default .navbar-brand:focus {
				    color: black; font-size: 15px; font-weight: bold;
				}

css파일을 관리하는데 부트트랩의 navbar 에 관련된 이런 코드들이 너무 많아서 navbar와 관련된 코드들만,  한줄로 보이게 만들고 싶습니다. collapse 시킨다고 하는 것 같습니다!! 

html 같은 경우에는 <div> 로 열고 닫음으로써, 코드들이 너무 길 때는 코드들을 가려서 한줄로 보이게 만들었습니다. 그러한 기능이 있을지 궁금합니다!!!!

**Comment by egoing** [comment]
아래처럼 하셔도 됩니다. 그런데 과연 이것이 좋은 방법인지는 모르겠어요 :) 
후속 질문이 있으시면 이슈를 다시 open해주세요
```
.pa5{padding-left: 5%; padding-right: 5%;}
```

**Comment by SangYunLeee** [comment]
알려주셔서 감사드립니다!!!
모르는 것을 설명하기가 너무 어렵네요 ㅜㅜ. 아래와 같은 이유인데 모르는 걸 표현하기가 너무 어렵네요 ㅜ

```
			.navbar-default .navbar-brand,
			.navbar-default .navbar-brand:hover,
			.navbar-default .navbar-brand:focus {
			    color: black; font-size: 15px; font-weight: bold;

			}

                        . pa5{
				padding-left: 5%;
			        padding-right: 5%;
			}
```

위의 코드 중에  navbar 쪽 css가 많아 navbar 관련 스타일이 점점 많아져서 navbar관련 스타일들만 따로 편철?하기 위해, 아래와 같이 html 의 \<div\> 와 같은 방식으로 관리하고 싶은데 html의 div와 같은 묶음 태그가 css에도 있는지 궁금합니다!

```
                 <div>
			.navbar-default .navbar-brand,
			.navbar-default .navbar-brand:hover,
			.navbar-default .navbar-brand:focus {
			    color: black; font-size: 15px; font-weight: bold;
			}
                  </div>
                        . pa5{
				padding-left: 5%;
			        padding-right: 5%;
			}
```


  **도와주셔서 정말 정말 감사드립니다!!!!!**
