### ISSUE TITLE
VSCode에서 최적의 Jupyter Lab(Notebook) + Pipenv 개발환경을 구성하는데 어려움을 겪고 있습니다. 

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#736]
안녕하세요, 파이썬을 공부한 지 꽤 됐지만 아직도 뭘 잘 모르겠는 파린이 입니다. 

이번 코딩 야학 때는 주피터 노트북을 이용해 이것 저것 여러가지 프로젝트를 하려고 하는데요, 여태 귀찮아서 개발환경 세팅에 신경 안쓰고 그냥 비효율적으로 하다가 이러면 안되겠다 싶어 한 번 **제대로 개발환경을 세팅**해보고자 합니다. 그런데 제가 개발 환경 세팅에 익숙치 않아 다음과 같은 저의 세팅이 제 목표에 부합하는 적절한 세팅인 지 알고싶습니다. (제가 잘 못 생각하는 것은 없는지, 혹시 비효율적인 부분은 없는지.) 

* 목표: VSCode에서 Jupyter Lab 및 기본 데이터 분석 패키지를 **주로** 활용하지만 때에 따라 능동적으로 패키지 관리를 할 수 있는 프로젝트 가상환경을 세팅하고 싶음. 

'주로' 라고 쓴 이유는 가끔 Django 프로젝트 같은 것도 같은 개발환경에서 프로젝트를 생성하기를 원하기 때문입니다. (PyCharm에서 넘어온 가장 큰 이유입니다.) 

* 저의 생각 및 질문: 일단 저는 주로 Jupyter Notebook(Lab) 위에서 작업할 것이고 프로젝트마다 의존성 문제를 분리하기 위해선 독립된 가상환경을 설치하는 것이 좋을 것 같아 가상환경을 깔고 Jupyter Notebook을 돌리려고 하는데요, 

이 때, 

1. 모든 프로젝트에 기본적으로 Jupyter Lab, numpy, pandas, sklearn 등의 패키지는 거의 항상 설치하는데, 어떻게 하면 매번 프로젝트 생성시마다 이런 중복된 작업을 줄이면서도 필요할 떄 가상환경 내에서 각각의 패키지 버전 관리를 자유롭게 할 수 있을까요? 

2. 제 부족한 생각으론 매번 필요한 패키지를 중복설치하는 것은 비효율적일 것 같아 (매번 프로젝트 만들 떄 마다 jupyterlab, numpy, pandas 이런거 설치해야 하니까) Anaconda를 활용하여 기본 패키지들을 바로바로 불러오고 기타 필요한 것만 pip으로 별도 설치 해주려고 하는데요, 이 때 conda 가상환경을 써야 할 지, 아니면 pipenv 가상환경을 써도 되는지 궁금합니다. 

pipenv 써보면서 패키지 상호의존성 문제도 잘 해결해주고 가상환경과 pip을 같이 관리해준다는 점이 좋아서 가급적이면 pipenv를 써보고싶은데... anaconda 패키지와 pipenv를 같이 쓰는 것이 **궁합(?)** 이 잘 맞는지, 애초에 둘을 병행해서 사용하는 것이 가능하긴 한건지 잘 모르겠습니다 ㅠㅠ 

결론적으로 다시 정리하자면 매 프로젝트마다 jupyterlab, numpy, pandas 등 자주쓰는 패키지를 중복설치 하지 않으면서 필요하면 pip을 통해 원하는 패키지를 추가할 수 있는 가상환경을 어떻게 세팅하면 좋을지에 대한 질문입니다. 

읽어주셔 감사합니다. 생코 멘토님들께 미리 감사인사 드립니다!

**Comment by znffl** [comment]
안녕하세요.
아나콘다 가상환경을 사용하여 패키지 관리를 하시고, 장고 프레임워크를 이용하시는 것을 추천드립니다.
아나콘다환경에서 장고를 구성하는 url 은 아래와 같습니다.

[아나콘다 가상환경에서 장고 프레임워크 설치1](https://seogwipo.tistory.com/entry/%EC%9C%88%EB%8F%84%EC%9A%B010%EC%95%84%EB%82%98%EC%BD%98%EB%8B%A4-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%9E%A5%EA%B3%A0django%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC-%EC%84%A4%EC%B9%98%ED%95%98%EA%B3%A0-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0)

[아나콘다 가상환경에서 장고 프레임워크 설치2](https://jackerlab.com/django-introduce-and-first-setting/)

p.s 참고로, 프로젝트별 의존성을 피하는 것 뿐 아니라 기존 컴퓨터(노트북)내 레지스트리, 라이브러리와의 영향성도 최소화 하기 위하여 저는 도커를 사용하여 아나콘다 이미지를 받아 파이썬 실습환경을 구축 하였는데요. 
관심있으시면 도커쪽도 보시면 좋을 것 같습니다. 
[도커란?](https://www.44bits.io/ko/post/almost-perfect-development-environment-with-docker-and-docker-compose?utm_source=gaerae.com&utm_campaign=%EA%B0%9C%EB%B0%9C%EC%9E%90%EC%8A%A4%EB%9F%BD%EB%8B%A4&utm_medium=social&fbclid=IwAR1NEQBvj6BXVQtuY5wEMO0E4oUeMTY75LTHn5atDdbwhkjuE1UPkRbSf0o)
[도커로 파이썬 개발환경 구축](https://stophyun.tistory.com/162)

이슈를 close 하오니 해결이 안되었거나 추가로 궁금한 점이 있으시다면 open 부탁드립니다.
