### ISSUE TITLE
아톰 프로그램 문의입니다. ㅠ

### ISSUE THREAD

**Issue by difains** [codingeverybody/codingyahac#74]
아톰 프로그램으로 코딩을 하다가 프로그램 해상도에 따라 코딩한 내용이 줄넘김하는 기능이
어떤건지 알고 싶네요..

자꾸 오른쪽 저 멀리 가버리니 한 눈에 보기가 힘들어서여 ㅠ

**Comment by smartbos** [comment]
Preference -> Editor 로 들어가셔서 Soft Wrap 을 활성화 해보세요.
Soft Wrap 를 활성화하면 창 크기에 맞춰서 줄 바꿈을 해줍니다.
Soft Wrap At Preferred Line Length 를 활성화하면 설정한 Preferred Line Length 값에 따라 줄 바꿈을 해줍니다.

<img width="1342" alt="2018-01-08 9 39 35" src="https://user-images.githubusercontent.com/6157033/34671102-755daba0-f4bc-11e7-954e-6185853f1172.png">
