### ISSUE TITLE
설치방법

### ISSUE THREAD

**Issue by junpyo508** [codingeverybody/codingyahac#742]
python과 flask 설치 방법을 모르겠습니다.

**Comment by Hatser** [comment]
Google에
`Python 설치`, `Flask 설치`라고 검색하시면 그림으로 설명된 글이 많이 있습니다 한 번 참고해보세요.

**Comment by junpyo508** [comment]
파이썬은 했는데 flask 는 모르겠네요 진짜

**Comment by znffl** [comment]
안녕하세요. 
아래 튜토리얼 따라해보세요.
[flask 설치](https://medium.com/@mystar09070907/flask-%EC%84%A4%EC%B9%98-cce8b8c25412)

만약 설치가  안되시면 어디서 막히는지 캡쳐파일도 올리시면 좀 더 빨리 피드백 받으실 수 있습니다.

해당 이슈는 close 하겠습니다.  해결이 안되셨거나 궁금한 점이 있으시면 다시 open 부탁드립니다.
