### ISSUE TITLE
flask

### ISSUE THREAD

**Issue by junpyo508** [codingeverybody/codingyahac#744]
python을 다운받아서 flask를 다운받으려고 pip install flask를 입력하면 
내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다 라고 뜹니다

**Comment by Hatser** [comment]
Python을 설치하실 때 가장 먼저 나타나는 화면에서

Add Python 3.7 to PATH 에 체크하신 후 설치를 진행하셔야 합니다.

**Comment by znffl** [comment]
환경변수 설정이 안되어 있어 발생하는 문제 입니다.
아래 블로그를 참조하여 다시 설정해보세요.

[python 설치 및 환경변수 설정](https://gabii.tistory.com/entry/Python-Python-370-%EC%84%A4%EC%B9%98-%EB%B0%8F-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%84%A4%EC%A0%95)

해당 이슈는 close 하겠습니다. 해결이 안되셨거나 궁금한 점이 있으시면 다시 이슈를 open해주세요.
