### ISSUE TITLE
<a> 이것을 웹페이지에서  보이게 하고 싶습니다

### ISSUE THREAD

**Issue by dahylee** [codingeverybody/codingyahac#749]
안녕하세요 코딩야학 6기에서 '코딩수업'트랙을 통해 코딩을 처음 접하고 공부하고있는 학생입니다
수업을 들으면서 저만의 복습 웹페이지를 만들어가며 실습, 공부 중인데요
웹 페이지에 <a>를 보이게 하고 싶었습니다
아래의 사진과 같이 했지만 
테그가 이것 말고 다른 테그가 있을까 하여 질문드립니다
제가 적은 테그는  →<p><h1><<a>a></h1></P> 이렇게 했었습니다

![image01](https://user-images.githubusercontent.com/53821148/62537185-cb75bf80-b88a-11e9-98b9-13f39bd96cb4.png)

**Comment by znffl** [comment]
안녕하세요.
html 코드를 웹페이지에서 출력하고 싶다고 하신건지요?   
그렇다면 아래와 같은 방법으로 html 코드를 표시하실 수 있습니다.  

1) pre태그 사용, <를 &lt; >를 &gt; 로 치환하여 코드 작성
```
<pre>
&lt;div class="html"&gt;
    &lt;html&gt;
    &lt;head&gt;&lt;title&gt;Title&lt;/title&gt;&lt;/head&gt;
    &lt;body&gt;
    &lt;p&gt;Unrendred html&lt;/p&gt;
    &lt;/body&gt;
    &lt;/html&gt;
&lt;/div&gt;
</pre>
```  

2) xmp 태그 사용
```
<xmp>

<h1> Hi this Test h1 code</h1>
<b> Hi this Rajaram </b> 

</xmp>
```

**Comment by ghdalsrldi** [comment]
웹 브라우저에서 HTML 태그를 보이게 하고싶다는 말씀이신가요?
xmp라는 태그를 사용하시면 되요.
xmp 태그는 안쪽의 내용을 그대로 출력해 줍니다.
```html
<xmp><a>내용</a></xmp>
```
