### ISSUE TITLE
cross domail 문제로 질문합니다.

### ISSUE THREAD

**Issue by Cnk-O** [codingeverybody/codingyahac#75]
script 내부에서 서로 다른 도메인은 호출을 못한다해서
밑에함수를 이용해 호출했습니다.
개발자도구에서 보면 네트워크에 응답데이터가 들어옵니다.
그런데 그 데이터에 접근하는 방법이 무엇이 있나요.
서버에 접근 불가로 callBack 함수는 이용하지 못합니다.
데이터는 json, html, text 파일입니다.
아무리 찾으려해도 방법을 찾지못해 질문합니다!! 
도와주세요.

```
/* load DATA */
    function loadData(url) {
        var script = document.createElement('script');
        
        script.setAttribute('src', url);
        script.setAttribute('type', 'text/javascript');
        document.getElementsByTagName('head')[0].appendChild(script);
    };
```

**Comment by egoing** [comment]
음 우선 검색어를 하나 드려볼께요. 

jsonp라는 기법입니다. 한번 검색해보시고 후속 의문이 있으시면 이슈를 오픈해주시면 도움을 드릴께요. 

화이팅입니다 :)
