### ISSUE TITLE
안드로이드 터치하는 좌표로 이미지 버튼 이동하기

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#750]
# 해결하고자 하는 문제

안녕하세요?

이미지 버튼이 터치한 부분의 좌표로 이동하게 하고 싶습니다.
터치 좌표는 setOnTouchListener로 간단하게 얻을 수 있는데 
뷰의 위치를 좌표로 지정하는 방법을 잘 모르겠습니다.

# 환경
안드로이드

**Comment by Hatser** [comment]
생각보다 간단하게 구현해 낼 수 있는 부분이라 이 부분에 대해서는 본인이 어떤 방식으로 구성할 지 생각해보시길 추천드려요.

view를 움직일 수 있는 속성들로는,

[여기](https://developer.android.com/reference/android/view/View)에서
setLeft, setRight, setTop, setBottom과, margin 에 대해 검색해보시기 바랍니다.

**Comment by kammaii** [comment]
터치한 부분을 기준으로 좌측상단에 이미지버튼을 이동시키고 싶은데 아래와 같이 해보니 이미지 버튼의 좌측상단은 부모레이아웃에 고정된채 터치된 지점까지 뷰가 늘어납니다. 
현재 부모레이아웃은 constraintLayout이며, 이미지뷰에는 제약조건을 설정하지 않고 width, height만 입력했습니다.
'setLeft'와 'setTop'을 모두 입력해보기도 했는데 오히려 뷰가 사라져버렸습니다.

constraintLayout에 제약조건을 설정하지 않으면 좌측상단에 뷰가 배치되는 것은 알지만
뷰의 width, height를 지정해줬는데 터치위치에 따라 왜 값이 변하는지 모르겠습니다.

```
article.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {

                imageButton.setRight((int) motionEvent.getX());
                imageButton.setBottom((int) motionEvent.getY());

                return false;
            }
        });
```

**Comment by Hatser** [comment]
> 터치한 부분을 기준으로 좌측상단에 이미지버튼을 이동시키고 싶은데 아래와 같이 해보니 이미지 버튼의 좌측상단은 부모레이아웃에 고정된채 터치된 지점까지 뷰가 늘어납니다.
> 현재 부모레이아웃은 constraintLayout이며, 이미지뷰에는 제약조건을 설정하지 않고 width, height만 입력했습니다.
> 'setLeft'와 'setTop'을 모두 입력해보기도 했는데 오히려 뷰가 사라져버렸습니다.
> 
> constraintLayout에 제약조건을 설정하지 않으면 좌측상단에 뷰가 배치되는 것은 알지만
> 뷰의 width, height를 지정해줬는데 터치위치에 따라 왜 값이 변하는지 모르겠습니다.
> 
> ```
> article.setOnTouchListener(new View.OnTouchListener() {
>             @Override
>             public boolean onTouch(View view, MotionEvent motionEvent) {
> 
>                 imageButton.setRight((int) motionEvent.getX());
>                 imageButton.setBottom((int) motionEvent.getY());
> 
>                 return false;
>             }
>         });
> ```

setX와 setY는 알려드리지 않았었네요...

Left, Right, Bottom, Top은

부모의 Left, Right, Bottom, Top으로부터 어느정도 만큼 떨어져있을 것인지를 정하는 속성입니다.

setX와 setY도 한 번 시도해보세요.

**Comment by kammaii** [comment]
아! 정말 간단한 문제였군요! 감사합니다!!
