### ISSUE TITLE
안드로이드 스튜디오 질문입니다!

### ISSUE THREAD

**Issue by JmmJam** [codingeverybody/codingyahac#754]
# 해결하고자 하는 문제

급여 프로그램 작성을 하고있는데요, 이용자가 해당 년도, 월을 입력하면 주말, 공휴일을 제외한 출근일수를 알아내는 방법이 궁금합니다.

주말제외는 할 수 있을거 같은데 공휴일은 어떻게 접근해야할지 모르겠습니다ㅜㅜ

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by Hatser** [comment]
먼저 공휴일들을 리스트나 다른 순회 가능한 형태의 구조에 담아놓을 필요가 있겠죠.

주말 제외를 한 뒤, 시작 날짜와 끝 날짜의 사이에 포함되는 공휴일을 추려 내고,

그 공휴일이 주말에 포함되는지 확인하시고 주말에 포함되지않는 공휴일의 갯수만큼 빼시면 되겠습니다.

대체공휴일이 있는 경우에는 대체공휴일이 끝 날짜에 포함되는지 확인하시고 처리하도록 하시면 되겠습니다.

**Comment by InyoungAum** [comment]
https://www.data.go.kr/dataset/15012690/openapi.do

다음과 같은 공휴일 API를 통해 데이터를 가져오는 방법도 있을 것 같습니다.

**Comment by JmmJam** [comment]
감사합니다!
