### ISSUE TITLE
생활코딩 부모자식과 목록인 WEB1-12에서 질문있습니다

### ISSUE THREAD

**Issue by FFF0223** [codingeverybody/codingyahac#757]
<ul>~~~</ul>은 중간에 숫자를 일일이 넣어야 된다는 단점이 있어서 <ol>~~~</ol>코드를 대신 쓸 때가 있다고 하셨잖아요. 근데 ol을 쓰게 되면 그 ul을 썼을 때의 점이 안나타나는데 점도 같이 나오게 할 방법은 없는 거가요?

**Comment by znffl** [comment]
안녕하세요.

ol 태그는 자동으로 숫자, 로마자, 알파벳을 자동 배열 해주는 태그입니다.
기호와 숫자를 둘 다 사용하고 싶으시다면 html 태그를 사용하지 않고 css 속성을 사용하여 숫자를 자동으로 증가시키는 방법이 있습니다.
아래 소스를 보시면 ul로 list-style 모양을 생성하고, counter를 이용하여 숫자를 증가시키는 방법을 사용할 수 있습니다.

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<style>
ul { 
    counter-reset: item;
    list-style-type: disc outside none;
}
  
li:before { 
    content: counter(item) ".  "; 
    counter-increment: item 
}
</style>  
<body>
  <ul>
    <li>HTML</li>
    <li>CSS</li>
  </ul>
</body>
</html>
```

이슈를 close 하겠습니다. 
해결이 안되셨거나 추가로 궁금하신 점이 있으시면 이슈를 다시 open 해주세요.
