### ISSUE TITLE
Ajax와 React의 차이점에 대해 질문 드립니다. 

### ISSUE THREAD

**Issue by YangChoi** [codingeverybody/codingyahac#758]
안녕하세요!

생활코딩의 react 강의를 완강하고 현재 WEB1의 Ajax강의를 들은 상태입니다. 
사실 react강의를 다 이해 하진 못했지만, 이 두 강의의 실습을 해보니 
둘 다 링크 이동 없이 웹페이지에서 내용을 변경을 함으로써 제겐 같은 기능으로 느껴졌습니다. 
그래서 구글링을 해보니 'React에서 Ajax를 요청한다' 라는 표현을 찾았습니다. 
그럼 React 안에 Ajax가 있는 건가요? 
둘은 어떤 식으로 다른가요?

**Comment by Hatser** [comment]
AJAX는 페이지 이동 없이, 페이지 내에서 서버에 데이터 요청을 하고,
서버에서 보내 준 데이터를 화면에 그리는 방식으로 페이지 이동 없이 내용을 변경합니다.

React에서는 미리 서버에서 웹 페이지(웹 앱)의 기능에 필요한 대부분의 내용을 첫 로딩에서 전달받은 후, React의 기능들을 통해 페이지를 변경합니다.

그 중 자주 바뀌는 값들은 서버에서 데이터를 전달받을 필요가 있기 때문에 React에서 Ajax를 통해 데이터를 받아 화면을 변경하는 방식으로 사용되는 것입니다.

**Comment by yoobato** [comment]
위의 조력자 분께서 너무 잘 설명해주셔서, 간단하게만 말씀드리면!

Ajax는 서버-클라이언트 간의 통신을 하기 위한 네트워크 기술입니다.
React는 화면에 원하는 뷰를 띄워주기 위한 기술입니다.

따라서, 위 조력자 분께서 말씀해주신 것처럼, 보통 Ajax를 통해 서버에 필요한 데이터를 요청하고, 받아와서 React로 만든 뷰 컴포넌트 위에 결과를 (예쁘게) 뿌려주게 됩니다!

**Comment by YangChoi** [comment]
답변 감사드립니다!
