### ISSUE TITLE
비교와 블리언 질문.(Python/Ruby)

### ISSUE THREAD

**Issue by XCIXI** [codingeverybody/codingyahac#759]
# 해결하고자 하는 문제

초과 > 미만 < 기호 외 아래에 쓰여져 있는 기호를 사용할 시 True False 값이 표출되는지 

궁금합니다

>=이상 <=이하

# 코드 혹은 오류

 a=3 b= 4

 print(a<=b)

puts(a<=b)
```

**Comment by znffl** [comment]
안녕하세요.
python idle에서 해당 값을 넣고 >=, <= 를 사용했을 때에도 boolean 값을 반환 하는 것을 확인 할 수 있습니다.

```
Python 2.7.5 (default, Oct 30 2018, 23:45:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> a=3
>>> b=4
>>> print(a<b)
True
>>> print(a<=b)
True
>>> print(a>b)
False
>>> print(a>=b)
False

```

해당 이슈를 close 하겠습니다.
해결이 안되셨거나 궁금한점이 있으시면 다시 이슈를 open 해주세요.
