### ISSUE TITLE
Atom 패키지 'Beautify'가 PHP를 인식하지 못하는 문제를 해결하고 싶습니다.

### ISSUE THREAD

**Issue by awwsome** [codingeverybody/codingyahac#76]
# 증상
- 텍스트에디터 Atom에서 '[Beautify](https://github.com/Glavin001/atom-beautify)'라는 패키지를 설치해 사용하고 있습니다(아시겠지만 코드를 정리해주는 패키지입니다). html, css, js 파일 등은 잘 정리해주는데 유독 PHP만 정리를 못하는 문제를 겪고 있습니다. php 파일을 대상으로 beautify를 실행하면 아래와 같은 2개의 에러메시지가 뜹니다.

  > Error: Could not find 'php'. The program may not be installed.

  > Error: Could not find 'php-cs-fixer'. The program may not be installed.

- 현재 첫번째 에러는 어찌어찌 해결을 한 것 같습니다. php 공식 사이트에서 실행 파일이 포함된 압축파일을 받아서 임의의 경로에 풀고, 그 경로를 beautify의 설정 화면에 입력해 주었습니다. 그랬더니 그때부터는 1번 에러는 뜨지 않고 2번만 뜨고 있습니다.
- 해결방법을 구글링했습니다만, 외국 분들이 올려주신 솔루션을 제가 잘 이해하지 못하겠어서 질문을 드립니다. 제가 이해하기로는 [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)를 설치하면 된다는 것 같은데, 설치 방법을 잘 모르겠네요.

# 실행환경과 하고 있는 작업
- Windows 10 64비트.
- 말씀드렸듯 아톰을 사용 중이고, 웹호스팅 서버에 설치된 그누보드를 수정하고 있습니다.
- [remote ftp](https://atom.io/packages/remote-ftp)라는 패키지를 설치하여 수정 즉시 서버에 반영되도록 해 놓은 뒤 작업 중입니다.

# 질문자의 수준
- html, css, js, php의 기초적인 부분들만 배운 상태입니다. CLI를 사용하거나 리눅스 환경에서 뭔가 설치하는 걸 해본적이 없어서 구글링을 해 놓고도 따라하지 못하고 있습니다.

# 시도해본 방법
- 구글링을 하다가 찾은 건 Beautify의 개발자와 어떤 유저 분이 토론한 내용이었는데, 그 유저 분이 결국 해결을 했다고 [코멘트](https://github.com/Glavin001/atom-beautify/issues/394#issuecomment-111261402)를 다셨습니다. 이 내용을 윈도우 환경에서 따라해보려고 시도했습니다.
- git bash를 설치해 명령어를 넣어 보았는데, wget을 찾을 수 없다고 나왔습니다.
- wget이라는 걸 설치해야 되나 싶어서 윈도우 용 인스톨러를 받아 설치했습니다. 그런데 역시 wget을 찾을 수 없다고 나왔습니다.
- 구글링을 하다 보니 wget 말고도 curl이니 composer니 하는 것들이 이것저것 나왔는데, 이것들이 제게는 너무 생소한 것들이라 어디서부터 뭘 깔아야 하는지 약간 길을 잃은 듯한 기분을 느끼고 있습니다.......

제가 모르는 것이 너무 많아서 조력자 분들이 제 수준에 맞는 답변을 해주실 수 있을지 잘 모르겠네요 ㅠㅠ 그래도 도와주시면 정말 감사하겠습니다. 굳이 제가 구글링한 해결책이 아니더라도, 아톰에서 php 코드를 예쁘게 정리할 수 있는 방법이 있다면 알려주셔도 감사하겠습니다.

**Comment by smartbos** [comment]
아톰에서 php-cs-fixer 패키지를 설치하시면 됩니다.
Preference -> install 로 들어가셔서 php-cs-fixer로 검색하셔서 설치해보세요.

<img width="1436" alt="2018-01-08 9 26 34" src="https://user-images.githubusercontent.com/6157033/34670697-c7b397a4-f4ba-11e7-96ec-4e891ccc999f.png">
