### ISSUE TITLE
공부 방법에 대한 고민입니다!

### ISSUE THREAD

**Issue by HoWWWWWhy** [codingeverybody/codingyahac#760]
# 해결하고자 하는 문제
python cgi로 만들었던 웹페이지에 회원가입/로그인 기능을 추가해서 flask로 다시 만들어보고 있는데요! (코딩야학 프로젝트로 진행중입니다.)
유투브에서 좋은 튜토리얼을 찾아 보면서 따라해보는 방식으로 하고 있는데
문득 이런 방법이 맞는건가 싶어서요... 제가 너무 의존적인게 아닌가...
근데 한편으로는 제가 비효율적으로 시간을 오래 걸려서 구현할 부분들을
적당한 api로 구현할 수 있어서 시야를 넓히는 차원에서는 좋은 것 같기도 합니다.
개인 프로젝트를 할 때 어떤 방법을 추천하시나요?? 궁금합니다!!!

**Comment by studroid** [comment]
학습 방법이나 프로젝트 진행 방법은 개인의 성향에 따라 굉장히 많이 달라질 수 있습니다만, 저도 잘 모르는 분야를 배울 때는 튜토리얼을 따라 만들어보고 감을 잡은 뒤 조금 더 깊이 공부하곤 합니다 :)

다만 제 경우에는 공식 사이트의 튜토리얼을 먼저 따라해보고, 이후 추가로 다른 튜토리얼을 찾아 따라 만들어보거나 평소에 만들어보고 싶은 아이디어를 기록해놓고 새로운 기술을 적용해 하나하나 만들어가곤 해요~

예를 들어 플라스크를 배운다면, [공식 사이트](https://palletsprojects.com/p/flask/)의 Documentation에 들어가서 [공식 튜토리얼](https://flask.palletsprojects.com/en/1.1.x/tutorial/#tutorial)을 따라 만들어보고, 이후 뭔가 만들어보면서 공식 문서의 API Reference, User's Guide 같은 것들을 찾아보거나 검색을 통해 다른 자료들을 찾는 방식을 택할 듯합니다.

맞는 방법, 틀린 방법이라는 것은 없지만, 공식 문서를 보고 내가 필요로 하는 정보를 파악할 수 있도록 연습하는 것은 필요하지 않을까 싶어요! 검색을 통해 나오는 정보들은 결국 공식 문서의 내용을 가공하여 정리한 것들이 대부분이라, 생각보다 높은 빈도로 잘못된 정보들도 함께 나오는데, 이를 걸러낼 수 있으려면 공식 문서를 봐야만 하니 말이지요 :) (물론 잘 정리된 유튜브 영상보다 공식 문서의 내용이 더 이해하기 어려운 경우도 많습니다)

유튜브의 튜토리얼에 의존적인 느낌이 드신다면, 공식 문서에 의존해보시는 건 어떨까 한번 의견을 드려봅니다 ㅎㅎ

**Comment by fermat39** [comment]
프로그래밍에는

바보같은 질문도 없고,
왕도도 없는 것 같습니다.
잘 모르고 안 해본 것들이지요.

지금은 의미없는 것처럼 반복하고 따라하겠지만, 
어느 순간 익숙해지고 다른 분들이 만들어 놓은 소스코드를 보면 영감을 얻을 수 있으실 거에요...

로그인 및 회원가입만 해도 생각할 부분이나 고도화하실만한 부분도 많을 거예요...
기본이 없으면 더이상 진행하기 참 어려운 것 같습니다.

화이팅입니다!

**Comment by HoWWWWWhy** [comment]
답변 정말 감사드립니다! 깊이 새겨서 천천히 학습해보도록 하겠습니다!!
