### ISSUE TITLE
일기, todo리스트등을 저장할때는 어떤방식이 좋을까요? + 추가 질문

### ISSUE THREAD

**Issue by mainvoid95** [codingeverybody/codingyahac#761]
# 해결하고자 하는 문제
node.js로 서버를 만들고 실행해서 접속시에 메인웹페이지가 띄워지고 
그 페이지에는 달력, todo-List를 만들어뒀습니다.
달력을 누르면 그 날자에 해당하는 일기를 작성하고 저장하게 하려고하는데
어떤방식으로 저장하는게 좋을까요?
DB를 이용해야할지 아니면 그냥 로컬에 저장해야할지 고민입니다.
todolist도 마찬가지입니다. 어떤식으로 저장해야지 지금 만들어둔것에 적절하게 사용이 가능할지 궁금합니다..

추가로 달력의 날자를 클릭하면 텍스트 에디터가 나와서 일기를 작성하는식으로 하려고하는데
텍스트 에디터는 어떤식으로 제작하면 되는지도 질문드립니다. 

# 코드 혹은 오류
https://github.com/mainvoid95/MyToday 
현재까지 제작한것들을 올려둔 곳입니다.

**Comment by Hatser** [comment]
로컬에 저장하는 방식으로 사용하셔도 DB연결이 필요없거나 하는 장점때문에 편할 수 있죠.
데이터를 JSON 형식으로 날짜별로 저장하면 될 거구요.

DB를 이용해서 처리하시면 서버와 DB를 연동하는 공부가 되어서 좋을거에요.

추가 질문에 대해서는..

우선 텍스트 에디터를 담당할 엘리먼트를 만드셔야겠죠.
이 텍스트에디터는 평소에는 보이지않다가, 달력을 클릭하면 그 위치에 나타나야 합니다.

클릭했을 때 보이게 하기 위해, 달력의 날짜들에 onclick 이벤트를 등록시킵니다.
클릭당한 엘리먼트의 위치에서 어느정도 값을 변경한 위치에 텍스트 에디터를 이동시킵니다. 보이게도 해야겠죠.

텍스트 에디터가 포커스를 잃을 때(`onblur`) 다시 감추는 방식으로 구성하시면 됩니다.

**Comment by mainvoid95** [comment]
답변 감사합니다 
DB공부도 할겸 DB로 만들어보겠습니다.

텍스트 에디터는 엘리먼트 제작하고 
이벤트로 숨시고 보이게하면 된다는거군요!

참고해서 만들어보겠습니다!
