### ISSUE TITLE
Kahoot 같은 단어 퀴즈 게임을 구현하고 싶습니다.

### ISSUE THREAD

**Issue by GoogleKorea** [codingeverybody/codingyahac#763]
기존의 Kahoot 앱을 이용하는 것도 좋겠지만, 제가 생각하고 있는 것은

단어의 정보를 프로그램에 입력해 주었을 때, 그것을 단어 퀴즈로 생성해 내는 프로그램을 만들 고 싶습니다. 

예를 들어, word 파일에 있는 단어장을(가능하면 자동으로) 객관식 퀴즈로 만들어 주는 프로그램을 만들어 보고 싶습니다.

어떤 언어로 어디서부터 시작해야 할 지 막막하여 질문을 드립니다.

**Comment by InyoungAum** [comment]
안녕하세요? 

제가 이해한 느낌으론 

https://play.google.com/store/apps/details?id=com.quizlet.quizletandroid&hl=ko

이것과 같은 형태를 원하시는 것 같은데요 언어나 형태는 정하기 나름이라 선호하시는 형태를 선택하셔서 진행하시면 될 것 같네요 

바로 위에 예시로 들어드린 퀴블렛의 경우도 웹, 앱 두가지 형태를 모두 가지고 있습니다. 

기능이 많이 복잡하지 않다면 웹 언어로 제작하고 따로 앱을 만들지 않고 모바일 최적화 된 화면을 통해 사용하는 것이 좋을 것 같습니다!

**Comment by yoobato** [comment]
단어를 계속해서 업데이트하거나, 추가하실 계획이라면 데이터베이스를 공부하셔야 합니다.

만약, 그렇지 않고 정적인(바뀌지 않고 고정되어 있는) 단어들만을 사용하신다면, 위에서 말씀해주신 것처럼 단어들을 배열이나 딕셔너리 같은 자료구조 안에 넣고 하드코딩해서 사용하셔도 무방합니다.

만약, 데이터베이스를 공부하신다면, 이것을 연동해서 쓸 수 있는 back-end 쪽 언어도 하나 같이 공부하셔야 합니다. PHP, Python 과 같은 언어들이요!

만약, 아직 앱 개발에 대해 잘 모르신다면, 조금 더 쉬운 웹 개발부터 시작하시는 것을 권장합니다!

**Comment by GoogleKorea** [comment]
> 안녕하세요?
> 
> 제가 이해한 느낌으론
> 
> https://play.google.com/store/apps/details?id=com.quizlet.quizletandroid&hl=ko
> 
> 이것과 같은 형태를 원하시는 것 같은데요 언어나 형태는 정하기 나름이라 선호하시는 형태를 선택하셔서 진행하시면 될 것 같네요
> 
> 바로 위에 예시로 들어드린 퀴블렛의 경우도 웹, 앱 두가지 형태를 모두 가지고 있습니다.
> 
> 기능이 많이 복잡하지 않다면 웹 언어로 제작하고 따로 앱을 만들지 않고 모바일 최적화 된 화면을 통해 사용하는 것이 좋을 것 같습니다!
> 
> 시작의 경우는 사람마다 다를 수 있을 것 같습니다만 저의 기준으로 설명 드리면
> 
> 핵심기능과 부가기능으로 나누고 핵심기능부터 만드는 것을 선호합니다.
> 
> 미리 하드코딩으로 입력되어있는 단어 정보들을 가지고 문제를 제작하고
> 
> 퀴즈를 맞추는 기본 기능이 잘 완성되면 이후에 사용자가 데이터를 입력할 수 있게 하고
> 
> 그 다음 워드파일 파싱등의 기능을 추가 하는 것이 좋아보입니다.



> 기존의 Kahoot 앱을 이용하는 것도 좋겠지만, 제가 생각하고 있는 것은
> 
> 단어의 정보를 프로그램에 입력해 주었을 때, 그것을 단어 퀴즈로 생성해 내는 프로그램을 만들 고 싶습니다.
> 
> 예를 들어, word 파일에 있는 단어장을(가능하면 자동으로) 객관식 퀴즈로 만들어 주는 프로그램을 만들어 보고 싶습니다.
> 
> 어떤 언어로 어디서부터 시작해야 할 지 막막하여 질문을 드립니다.



> 단어를 계속해서 업데이트하거나, 추가하실 계획이라면 데이터베이스를 공부하셔야 합니다.
> 
> 만약, 그렇지 않고 정적인(바뀌지 않고 고정되어 있는) 단어들만을 사용하신다면, 위에서 말씀해주신 것처럼 단어들을 배열이나 딕셔너리 같은 자료구조 안에 넣고 하드코딩해서 사용하셔도 무방합니다.
> 
> 만약, 데이터베이스를 공부하신다면, 이것을 연동해서 쓸 수 있는 back-end 쪽 언어도 하나 같이 공부하셔야 합니다. PHP, Python 과 같은 언어들이요!
> 
> 만약, 아직 앱 개발에 대해 잘 모르신다면, 조금 더 쉬운 웹 개발부터 시작하시는 것을 권장합니다!



> 안녕하세요?
> 
> 제가 이해한 느낌으론
> 
> https://play.google.com/store/apps/details?id=com.quizlet.quizletandroid&hl=ko
> 
> 이것과 같은 형태를 원하시는 것 같은데요 언어나 형태는 정하기 나름이라 선호하시는 형태를 선택하셔서 진행하시면 될 것 같네요
> 
> 바로 위에 예시로 들어드린 퀴블렛의 경우도 웹, 앱 두가지 형태를 모두 가지고 있습니다.
> 
> 기능이 많이 복잡하지 않다면 웹 언어로 제작하고 따로 앱을 만들지 않고 모바일 최적화 된 화면을 통해 사용하는 것이 좋을 것 같습니다!
> 
> 시작의 경우는 사람마다 다를 수 있을 것 같습니다만 저의 기준으로 설명 드리면
> 
> 핵심기능과 부가기능으로 나누고 핵심기능부터 만드는 것을 선호합니다.
> 
> 미리 하드코딩으로 입력되어있는 단어 정보들을 가지고 문제를 제작하고
> 
> 퀴즈를 맞추는 기본 기능이 잘 완성되면 이후에 사용자가 데이터를 입력할 수 있게 하고
> 
> 그 다음 워드파일 파싱등의 기능을 추가 하는 것이 좋아보입니다.

정말 감사합니다. 아직 코딩에 익숙하지 않아 입문하는 단계이지만, 말씀해 주신 것이 도움이 많이 되었습니다!

**Comment by GoogleKorea** [comment]
> 단어를 계속해서 업데이트하거나, 추가하실 계획이라면 데이터베이스를 공부하셔야 합니다.
> 
> 만약, 그렇지 않고 정적인(바뀌지 않고 고정되어 있는) 단어들만을 사용하신다면, 위에서 말씀해주신 것처럼 단어들을 배열이나 딕셔너리 같은 자료구조 안에 넣고 하드코딩해서 사용하셔도 무방합니다.
> 
> 만약, 데이터베이스를 공부하신다면, 이것을 연동해서 쓸 수 있는 back-end 쪽 언어도 하나 같이 공부하셔야 합니다. PHP, Python 과 같은 언어들이요!
> 
> 만약, 아직 앱 개발에 대해 잘 모르신다면, 조금 더 쉬운 웹 개발부터 시작하시는 것을 권장합니다!

네:) 앱 개발을 아직 한 번도 안 해봤으니, 정말 웹 개발부터 먼저 시작하는 게 좋을 것 같습니다. 제가 원하던 답변을 해 주셔서 감사합니다!
