### ISSUE TITLE
Django models imageField upload_to 질문

### ISSUE THREAD

**Issue by 2044smile** [codingeverybody/codingyahac#765]
# config/static 폴더에 업로드 하고 python manage.py collectstatic 하면 S3 서버에 올라가도록 만들어놨는데 앱에서 글 작성 시 업로드하는 사진을 models.py 에서 upload to='config/static' 으로 가도록 설정했는데 파일 업로드 시 config/static에 파일이 추가가 안되는데 뭐가 문제일까요?

# 코드 혹은 오류
```
settings.py

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'config/static'),
]
STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

models.py


class Border(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=30)
    text = models.TextField(max_length=500)
    photo = models.ImageField(upload_to='config/static', default='config/static/no_image.png')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

```

# 환경
윈도우10, Python, Django, django 2.2.3

# S3 연동 전에는 잘 되었던거 같은데 이것저것 만지면서 안되는거 같네요.
직접 config/static 폴더에 파일 생성 시에는 문제없이 잘 업로드되는데 모르겠네요 ㅠ

**Comment by TahoLee** [comment]
아마도 s3연동전에 잘된 이유는 파일을 서버로 직접받았기 때문이었을거 같습니다. 
그럴경우에는 서버의 어디에 저장할지 위치를 지정할 필요가 있는데요. 그게 upload_to 라는 구문입니다. 
그런데, 세팅에서 STATICFILES_STORAGE를 이미 s3로정해놓아서 아마도 파일은 서버에 저장되지 않고, s3로 올라갈거 같습니다. 
그러니까 django에서는 서버에 파일을 저장할지 아니면 s3에서 파일을 받을지 정해야 하는데, 위에서 보면 setting에서는 s3가 받는다고 하고, 모델에서는 서버에서 받는다고 하고 있어요. 둘중에 하나로 정해서 정리해야할거 같습니다

**Comment by 2044smile** [comment]
답변 정말 감사합니다!

S3서버에서 받게 하고 싶은데
models.py의 upload_to를 어떻게 변경하면 s3로 넘길 수 있을까요?

지금 설정 값으로는 서버에도 저장이안되고 S3 서버에도 저장이안되네요.

**Comment by TahoLee** [comment]
upload_to를 빼고 저장하시면 될거 같아요. 
저도 사용했던게 예전이라서 가물가물한데, https://simpleisbetterthancomplex.com/tutorial/2017/08/01/how-to-setup-amazon-s3-in-a-django-project.html 이런거 확인해보시면 될거 같아요. (구글링을 하면 한글 자료도 있을거 같습니다)

**Comment by 2044smile** [comment]
감사합니다 ! :)
