### ISSUE TITLE
(android studio, kotlin) Activity의 함수를 다른 Class에서 사용하는 방법 질문드립니다!

### ISSUE THREAD

**Issue by 3always8** [codingeverybody/codingyahac#766]
# 해결하고자 하는 문제

ViewPageAdapter 클래스에서 fragment가 교체될 때 setPrimaryItem 이라는 함수가 호출됩니다.
그 때 MainActivity에 정의된  saveAndFinish 함수가 호출되도록 하고 싶은데 어려움을 겪고 있습니다.

saveAndFinish 함수가
fun **View.**saveAndFinish(){
...
}
이런 형태여서 그런 것 같습니다.

# 코드 혹은 오류
https://github.com/3always8/Willy/tree/master/app/src/main/java/com/ssong/willy

MainActivity
ViewPageAdapter
이렇게 두 개의 클래스 사이에서 문제가 생겼습니다.

# 환경
Android Studio 3.4
Kotlin

# 시도해본 방법
(ViewPageAdapter 파일에서)
            //오류가 나는 문장
            MainActivity().adapter?.currentFragment?.view?.saveAndFinish()

이렇게 하면 saveAndFinish() 함수 자체가 없다고 뜹니다.

**Comment by InyoungAum** [comment]
안녕하세요? 

`ViewPageAdapter`에 interface를 하나 생성하여 `MainActivity`에서 구현하고 그 구현안에 `saveAndFinish()` 를 호출 한뒤 `ViewPagerAdatper`의 `setPrimaryItem`의 마지막에서 interface를 호출해주면 될 것 같습니다. .

**Comment by 3always8** [comment]
> 안녕하세요?
> 
> `ViewPageAdapter`에 interface를 하나 생성하여 `MainActivity`에서 구현하고 그 구현안에 `saveAndFinish()` 를 호출 한뒤 `ViewPagerAdatper`의 `setPrimaryItem`의 마지막에서 interface를 호출해주면 될 것 같습니다. .

코딩야학 기간에 알차게 배우고 갑니다. 감사합니다!
