### ISSUE TITLE
node js 의 내용을 html 에 전달하고 싶습니다.

### ISSUE THREAD

**Issue by woosungchoi** [codingeverybody/codingyahac#767]
# 해결하고자 하는 문제

※ node js(웹서버) 를 이용하여 서버를 구축한 뒤, 서버 에서 API를 호출한 다음 클라이언트 사이드 로 API정보를 전달 (일반적으로 클라이언트에서 API를 해결하는 방식은 이미 만들었고,(ex. JSONP,Fetch API,등) 그것을 좀 더 다듬어서 웹서버로 불러와서 API를 요청한뒤 받은 정보를 클라이언트로 전달하는 것을 만들고자 합니다.

정리하자면,

1. 웹서버를 Node js로 구축

2. 만든 웹서버 에서 기상정보 API를 요청

3. 요청 받은 내용을 웹서버 에서 클라이언트 사이드 로 전송

4.클라이언트 사이드에서 받은 내용 보여줌

실시간 기상 정보 사이트 이며 실시간 으로 맵 을 클릭하면 위치를 전송 받아 해당 위치의 기상 정보를 나타내주는 네이티브 앱입니다.

 ---------------------------------------------------------------------------------------------------

# 코드 혹은 오류

다음 과 같은 오류들이 발생하였습니다.

![image](https://user-images.githubusercontent.com/11676387/62692693-179c3d80-ba0c-11e9-8ad2-864f2cee42d0.png)

문서를 찾아보니  https://requirejs.org/docs/errors.html#notloaded 불러오고자 하는 모듈을 path에 설정한뒤 하나씩 불러오는 구조 인것 같은데 여기서 부터 어떤식으로 접근해야 클라이언트 사이드 에 웹 서버에서 받은 API정보 를 전달할 수 있을까요?아니면 제가 너무 어려운 방법을 택하는 거 같기도 하고,,,,서버쪽은 처음입니다.

제가 잘못 알고 있는 정보나 키워드 혹은 해결 방안 ,등 을 제시해주시면 감사하겠습니다! :)

# 환경
windows 7 64bit, Node js,Express 4.x.x

# 시도해본 방법

※ 과정
- 1. node js 를 이용하여 웹서버를 생성하여 클라이언트 사이드 와 연동

![image](https://user-images.githubusercontent.com/11676387/62687446-c25b2e80-ba01-11e9-8e4d-e3aee6e1e622.png)

- 2. 클라이언트의 Fetch Api,JSONP방식 말고,nodejs 의 express 를 활용하여  CORS(크로스도메인) 문제를 해결

![image](https://user-images.githubusercontent.com/11676387/62687526-ea4a9200-ba01-11e9-8739-e674d8ec4b9f.png)

3) 노드 파일 에 있는 API를 클라이언트 사이드 에 전송 -> 실패

4) require js 를 활용하기 로 함

![image](https://user-images.githubusercontent.com/11676387/62694406-38b25d80-ba0f-11e9-93a9-76b9b975fe6b.png)

![image](https://user-images.githubusercontent.com/11676387/62694447-5089e180-ba0f-11e9-90ff-436b1b6fc0df.png)

![image](https://user-images.githubusercontent.com/11676387/62694478-60a1c100-ba0f-11e9-835b-7c06cba9815b.png)

*노드 파일 을 클라이언트 사이드에 전달하게되면 클라이언트 사이드 의 자바스크립트 는 node js 의require 를 인식하지 못하여 require js 혹은 common js 를 사용하는 것을 알게 되었고, 저는 require js 를 활용하기 로 하였습니다.

※지금까지의 방향은 다음 그림과 같습니다.

1) 

![image](https://user-images.githubusercontent.com/11676387/62688523-ffc0bb80-ba03-11e9-88d7-21f91a45d57c.png)

2)

![image](https://user-images.githubusercontent.com/11676387/62690716-2b45a500-ba08-11e9-896b-66565354d9d2.png)

3) 

![image](https://user-images.githubusercontent.com/11676387/62690899-8b3c4b80-ba08-11e9-8464-cf149cc9ad42.png)

4)

![image](https://user-images.githubusercontent.com/11676387/62691366-8035eb00-ba09-11e9-9ef5-8cd5b1f4cc13.png)

**Comment by Hatser** [comment]
node 환경에 있는 영역을 html으로 서버측에서 그려내려면 ejs, pug 등의 렌더 엔진을 사용하시거나,
send를 통해 node 서버의 스크립트에 html을 직접 써 넣고, 변수가 필요한 곳에 사용하는 방법으로 구성하셔야 합니다.


```js
app.get('/weather', function (res, req) {
    var data = {...데이터 내용...}
    res.send(`<html>
    ...
    <body>
       ${data}
    </body>
</html>
`)
})
```

브라우저 측에서 그려내는 방식으로 하시려면, 서버에서는 브라우저의 요청에 json데이터로 응답하는 방식으로 만드시면 되겠습니다.

브라우저측
```js
<script>
function loadWeather() {
     var req = new XMLHttpRequest();
     var data;
     req.onload = function() {
          if (this.readyState == 4 && this.status == 200) {
               data = JSON.parse(this.response);
          }
     };
  req.open("GET", "/weather", true);
  req.send();
}
</script>
```

node측
```js
app.get('/weather', function (res, req) {
    var data = {...데이터 내용...}
    res.json(data)
})
```

**Comment by woosungchoi** [comment]
답변 감사합니다! 도움 되었습니다:)
