### ISSUE TITLE
안녕하세요. 코딩 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by Atomicphysics** [codingeverybody/codingyahac#769]
안녕하세요

코딩야학의 html과 js 과정을 학습하면서
알게된 예제에서 js와 jquery로 코딩을 해봤는데,

아래 코드에서 "클로킹" 이미지를 클릭했을 때
"레이쓰" 이미지는 사라지고,
"레이쓰가 클로킹 했습니다." 라고 뜹니다.

이를 다시 클릭하면
레이쓰 이미지는 다시 나오고
"레이쓰가 클로킹 했습니다."라는 문구가 사라지게 만들고 싶은데,
현재는 다시 누르면 "레이쓰가 클로킹 했습니다."라는 문구가 추가됩니다.

즉 한 번 누르면 "레이쓰"이미지는 사라지면서 문구는 나타나고
다시 누르면 "레이쓰" 이미지는 나타나면서 문구는 사라지게 만들려면
어떻게 코딩해야 하는지 알고 싶습니다.

# 코드 혹은 오류
```
<!DOCTYPE html>
<html lang="ko" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Starcraft</title>
  </head>
  <body>
      <p><img id="클로킹" src="cloaking.png" alt="cloaking"></p>
      <p><img id="레이쓰" src="wraith.png" alt="wraith"></p>
      <div id="log"></div>
      <script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
      <script>
        $( "#클로킹" ).click(function() {
          $( "#레이쓰" ).fadeToggle( "fast", function() {
            $( "#log" ).append( "<div>레이쓰가 클로킹 했습니다.</div>" );
          });
        });
      </script>
  </body>
</html>
```

# 환경
맥 모하비10.14.6, js, jquery

# 시도해본 방법
[toggle hide or show "same time"]
[toggle reverse]
[toggle 반대로 ] 등을 검색하여 

toggleclass 태그를 실행해봤는데 실패했습니다.

**Comment by Hatser** [comment]
```html
<!DOCTYPE html>
<html lang="ko" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Starcraft</title>
  </head>
  <body>
      <p><img id="클로킹" src="cloaking.png" alt="cloaking"></p>
      <p><img id="레이쓰" src="wraith.png" alt="wraith"></p>
      <div id="log"></div>
      <script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
      <script>
        var faded = false;
        $( "#클로킹" ).click(function() {
        	if(!faded) {
          	$( "#레이쓰" ).fadeOut( "fast", function() {
              faded = true;
              $( "#log" ).append( "<div>레이쓰가 클로킹 했습니다.</div>" );
            });
          } else {
          	$( "#log" ).children('div').remove();
          	$( "#레이쓰" ).fadeIn( "fast", function() {
              faded = false;
            });
          }
        });
      </script>
  </body>
</html>
```

간단하게 짜 보았는데, 이런 결과를 내기 위한 방법이 이 것 뿐은 아니고, 정말 많은 방법이 있습니다.

여러 예시들을 시험해보시면서 편하고 좋은 방법을 찾아나가시면 되겠습니다!

**Comment by Atomicphysics** [comment]
> ```
> <!DOCTYPE html>
> <html lang="ko" dir="ltr">
>   <head>
>     <meta charset="utf-8">
>     <title>Starcraft</title>
>   </head>
>   <body>
>       <p><img id="클로킹" src="cloaking.png" alt="cloaking"></p>
>       <p><img id="레이쓰" src="wraith.png" alt="wraith"></p>
>       <div id="log"></div>
>       <script
>         src="https://code.jquery.com/jquery-3.4.1.js"
>         integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
>         crossorigin="anonymous"></script>
>       <script>
>         var faded = false;
>         $( "#클로킹" ).click(function() {
>         	if(!faded) {
>           	$( "#레이쓰" ).fadeOut( "fast", function() {
>               faded = true;
>               $( "#log" ).append( "<div>레이쓰가 클로킹 했습니다.</div>" );
>             });
>           } else {
>           	$( "#log" ).children('div').remove();
>           	$( "#레이쓰" ).fadeIn( "fast", function() {
>               faded = false;
>             });
>           }
>         });
>       </script>
>   </body>
> </html>
> ```
> 
> 간단하게 짜 보았는데, 이런 결과를 내기 위한 방법이 이 것 뿐은 아니고, 정말 많은 방법이 있습니다.
> 
> 여러 예시들을 시험해보시면서 편하고 좋은 방법을 찾아나가시면 되겠습니다!

김민재님 감사합니다.
제가 원하던대로 코드가 작동하네요.

한가지 더 여쭙고 싶습니다.

지금과 같이 작동되는 코드를 검색하려면
구글이나 jquery에서 어떤 키워드를 찾아야 하는지 알고 싶습니다.

질문하기 전, 스스로 해보면서
[toggle hide or show "same time"]
[toggle reverse]
[toggle 반대로 ]

등 정말 다양하게 검색했는데, 정확한 코드를 찾지 못했던 것 같습니다.

**Comment by Atomicphysics** [comment]
> ```
> <!DOCTYPE html>
> <html lang="ko" dir="ltr">
>   <head>
>     <meta charset="utf-8">
>     <title>Starcraft</title>
>   </head>
>   <body>
>       <p><img id="클로킹" src="cloaking.png" alt="cloaking"></p>
>       <p><img id="레이쓰" src="wraith.png" alt="wraith"></p>
>       <div id="log"></div>
>       <script
>         src="https://code.jquery.com/jquery-3.4.1.js"
>         integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
>         crossorigin="anonymous"></script>
>       <script>
>         var faded = false;
>         $( "#클로킹" ).click(function() {
>         	if(!faded) {
>           	$( "#레이쓰" ).fadeOut( "fast", function() {
>               faded = true;
>               $( "#log" ).append( "<div>레이쓰가 클로킹 했습니다.</div>" );
>             });
>           } else {
>           	$( "#log" ).children('div').remove();
>           	$( "#레이쓰" ).fadeIn( "fast", function() {
>               faded = false;
>             });
>           }
>         });
>       </script>
>   </body>
> </html>
> ```
> 
> 간단하게 짜 보았는데, 이런 결과를 내기 위한 방법이 이 것 뿐은 아니고, 정말 많은 방법이 있습니다.
> 
> 여러 예시들을 시험해보시면서 편하고 좋은 방법을 찾아나가시면 되겠습니다!

김민재님 감사합니다.
제가 원하던대로 코드가 작동하네요.

한가지 더 여쭙고 싶습니다.

지금과 같이 작동되는 코드를 검색하려면
구글이나 jquery에서 어떤 키워드를 찾아야 하는지 알고 싶습니다.

질문하기 전, 스스로 해보면서
[toggle hide or show "same time"]
[toggle reverse]
[toggle 반대로 ]

등 정말 다양하게 검색했는데, 정확한 코드를 찾지 못했던 것 같습니다.

**Comment by Hatser** [comment]
`fadeToggle`같은 메서드를 하나 알게되셨다면

jquery의 Docs를 참조하시는게 가장 정확합니다.

내용의 가장 위쪽에, 카테고리가 나타나 있는데, 같은 카테고리 내에서 둘러보시면 되고,

~을 하는 함수가 있는지 찾기 위해선 검색하는 노하우가 좀 필요할 수 있어요.
그리고 그 노하우는 웹 요소들에 대한 지식(깊은 지식도 필요 없습니다. 대충 ~가 있다, 이런 게 있고 이름은 ~다 정도의 지식이면 됩니다)이 있으면 더 찾기 수월할거에요

예를 들어 요소의 클래스를 바꾸고, 추가하고, 삭제하고, 토글하고 싶다면

`jquery change class`
`jquery add class`
`jquery remove class`
`jquery toggle class`
처럼 찾으시면 되겠습니다.

컴퓨터 분야에서는 어떠한 기능을 의미하는 자주사용하는 단어들이 있습니다.
예를 들면, 뭔가를 껐다가 켜는 의미를 나타내려면 여러 표현들이 있겠지만 toggle을 주로 사용한다던가...
문자로 된 내용을 계산(연산)하고자 할 때는 evaluate 등..
이런 단어들과 익숙해지시면 이후에 어떤 키워드를 이용해 검색할 지 빠르게 생각해 낼 수 있어요.

검색을 통해 예리한 답변을 얻기 위해서는 질문도 예리해져야 합니다.

`어떤 기능이 있는 게시판`을 만들고자 할 때, `~하는 게시판`보다는 당장에 필요한 `~기능을 구현하는 방법`에 대해 검색하시는게 좋습니다.
