### ISSUE TITLE
클립보드 정보 인식

### ISSUE THREAD

**Issue by jintae-song** [codingeverybody/codingyahac#776]
# 해결하고자 하는 문제
안녕하세요. 프로그래밍에 대한 기초지식이 없는 인문계열 학생입니다.
계좌번호를 복사한 채로, ‘토스’와 같은 어플에 접속하면 ‘0000로 이체하시겠습니까?’라는 창이 표시됩니다. 앱이 클립보드의 정보를 인식하는 것인지 궁금했습니다.

그렇다면 이러한 것도 가능할까요? (PC나 모바일 모두) 클립보드에 링크주소가 복사되면, 자동으로 화면에 “사파리 이동/카톡 공유” 선택지의 팝업창이 뜨게 할 수 있나요? 이 기능을 수행할 어플이 필요한 것인지, 어떤 방식으로 설계해야 가능한 것인지 대략적인 과정이 궁금합니다. (애초에 사파리 및 카카오톡에 이러한 코드가 포함되어 있지 않다면 완전히 불가능한 건가요?)

간단히 키워드로 답변해주시면, 직접 정보를 찾으며 공부하겠습니다. 
좋은 하루 되세요. 감사합니다.

# 환경
iOS

# 시도해본 방법
클립보드 관련 정보 리서치

**Comment by Hatser** [comment]
iOS나, 안드로이드에서 내부적으로 어떤 기능을 수행할 때
`내가 이걸 수행했어` 라고 알리는 게 있습니다. 이것을 흔히 `event`라고 부릅니다.

그리고 이런 이벤트들을 기다렸다가, 원하는 기능을 실행하도록 지원하는 객체들을 흔히
`Event Listener`라고 부릅니다.

안드로이드에서는 `Listener` iOS에서는 `Observer`라고 불러요.

설계 방식은,

먼저 클립보드를 관리하는 객체를 얻어 낼 필요가 있습니다.
안드로이드에서는 [`ClipboardManager`](https://developer.android.com/reference/android/content/ClipboardManager.html),
iOS에서는 [`UIPasteboard`](https://developer.apple.com/documentation/uikit/uipasteboard)네요.

찾아보니 두 객체 모두 `addPrimaryClipChangedListener`, `changedNotification`으로 event 리스너를 제공합니다.

이 리스너를 통해 복사했을 때를 알아채고 기능을 실행할 수 있습니다.

자세한 예제들은 `android (또는 iOS) clipboard (iOS에서는 pasteboard) event` 라고 검색해보세요

**Comment by jintae-song** [comment]
친절한 답변 정말 감사합니다! 공부해보겠습니다 :)
