### ISSUE TITLE
'코딩공부'에서 배운것만으로 나만의 독서노트를 만들려고 보니 한계가...

### ISSUE THREAD

**Issue by cyberjuly** [codingeverybody/codingyahac#777]
# 해결하고자 하는 문제

'코딩공부' 동영상만 공부한 완전 초짜입니다. 
나만의 독서노트를 만들고 싶어서 시작한 공부여서, html만으로 일단 시도해봤습니다.
- index.html만들고
- 각 책마다 html페이지를 따로 만들어서 작동은 했습니다만.... (여기까지는 일단 신납니다)

이게 엄청 비효율이잖아요... 어차피 독서노트를 구성하는 내용은 동일하고(저자, 분류, 읽은시기, 감상평 등등), 그 안에 들어가는 컨텐츠만 책별로 바꿔주면 되니까, 특정 양식만 구현하고 그 안에 빈 box만 컨텐츠로 채워놓으면 될것같습니다. 게시판 입력하듯이요.

이런건 뭘 공부해야 구현할수 있나요?

**Comment by Hatser** [comment]
AJAX에 대한 수업을 들어보시면 도움이 될 것 같습니다.

[여기](https://opentutorials.org/course/3281) 에서 찾아보실 수 있습니다.

**Comment by cyberjuly** [comment]
네, 감사합니다
