### ISSUE TITLE
안드로이드 검색 방법 문의

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#779]
# 해결하고자 하는 문제

안녕하세요?

ListView를 사용하기 위해 검색을 했고 대략적인 사용방법을 이해해서 적용했습니다.
간단한 ListView에서는 그냥 이정도까지만 해도 괜찮았는데
기능을 추가하려다보니 코드를 좀 더 이해하고 싶은 마음이 생겼습니다.
단순히 ListView에 대한 이해가 아니라 이 ListView를 예로 들어 앞으로도 생길 궁금증을 어떻게 스스로 찾을 수 있는지를 여쭈어보고 싶습니다.

제 궁금증을 시작하게 해 준 코드는 아래와 같습니다.
```
ArrayAdapter adapter = new ArrayAdapter(getContext(), android.R.layout.simple_list_item_1, readingList);
```
이 코드에서 'simple_list_item_1'이 제 layout 폴더에는 없는데 왜 에러가 뜨지 않고 잘 사용이 되는지에 대해 궁금했습니다. 
검색을 통해 안드로이드에 기본적으로 내장되어 있는 xml 파일이라는 것을 알게 되었습니다.
그럼 우리가 편리하게 사용할 수 있는 내장 레이아웃에 대한 리스트들이 있을 것 같았습니다.
그래서 '안드로이드 developers' 사이트에서 'ArrayAdapter'를 검색해 봤습니다.
하지만 'ArrayAdapter'의 메소드와 생성자만 나와 있고 제가 찾고 싶었던 리스트 같은 것은 없었습니다.
좀 더 검색을 해보니 같은 사이트에서 'R.layout'으로 검색하면 내장 레이아웃들이 나오는 것을 알았습니다.
그런데 파일 이름들만 나열되어 있고 이 파일들이 어떤 레이아웃인지는 알 수 없었습니다.
이 리스트는 별로 쓸모가 없을 것 같았습니다.
좀 더 찾아보니 아래의 Github 사이트가 나왔습니다.
```
https://github.com/aosp-mirror/platform_frameworks_base/tree/master/core/res/res/layout
```
이 Github가 안드로이드 공식(?) 사이트는 아닌 것 같지만 어쨋든 제가 찾던 'simple_list_item_1'의 코드 내용을 볼 수는 있었습니다. 
하지만 문제는 파일들이 너무 많아서 다른 레이아웃을 적용하고 싶을 때 어떻게 찾아야하는지를 알 수 없었습니다.

여기까지가 제 궁금증을 해결하기 위한 노력의 흐름이었습니다.
물론 그냥 Custom ListView를 만들어 사용하면 되겠지만 저 많은 내장 레이아웃들은 분명히 누구든지 편리하게 사용하라고 만든 것일테니 먼저 내가 찾는 것이 있는지를 확인해보고 싶었습니다.
실제 개발자분들은 어떻게 검색을 해서 필요한 것들을 찾아내는지 궁금합니다.

**Comment by InyoungAum** [comment]
안녕하세요? 

저의 경우에는 위에서 예시로 언급해주신 `simple_list_item_1` 과 유사한 형태라도 사실 디자이너와 작업을 하다 보면 디테일이 다른 경우가 많아 다 만들어쓰게 되는 것 같습니다. 

다른분들은 어떨지 모르지만 저는 내장 레이아웃이 없다 생각하고 만들어 쓰는거 같습니다.

**Comment by kammaii** [comment]
> 안녕하세요?
> 
> 저의 경우에는 위에서 예시로 언급해주신 `simple_list_item_1` 과 유사한 형태라도 사실 디자이너와 작업을 하다 보면 디테일이 다른 경우가 많아 다 만들어쓰게 되는 것 같습니다.
> 
> 다른분들은 어떨지 모르지만 저는 내장 레이아웃이 없다 생각하고 만들어 쓰는거 같습니다.

아~ 그렇군요! 오히려 그냥 만드는게 더 편할 수도 있겠네요 :)
