### ISSUE TITLE
진로 : 보안 관련 진로에 대해 질문드리고자 합니다

### ISSUE THREAD

**Issue by DominiQN** [codingeverybody/codingyahac#78]
안녕하세요 저는 비전공자 25살 대학생입니다.

 프로그래밍에 많은 관심을 가지면서 공부를 하려고 하는 도중에 대학에서 사이버 보안 강의를 들으면서 보안 쪽으로 일해보고 싶다고 결심하게 되었습니다.

 제 짧은 인맥으로 그래도 여기저기 물어보고 찾아 본 결과, 보안은 정말 수많은 분야들이 기초가 되는 학문이라고 하여 컴퓨터공학 복수전공을 생각하였지만, 2018년 현재 4학년으로 올라가는 제가 컴퓨터공학을 복수전공을 하기 보다는 차라리 대학원에 진학하는 게 낫다는 말씀에 대학원에 진학하려고 생각을 하고 있습니다.

 비전공자에다가 문과 출신이다보니 어떻게 공부를 시작해야 될지 모른다는 것이, 정보가 없다는 것이 지금 제게 닥친 가장 큰 문제인 것 같습니다. 그런데 코딩야학 3기로 신청을 하면서 현직에 계시는 많은 분들이 이렇게 질문에 답변을 해주시는 이런 활동을 하여, 어두컴컴한 동굴을 걷는 듯한 저에게 조금의 빛이라도 주실 수 있으실까 하여 이렇게 질문을 올리게 되었습니다.

### 3. 보안 직종에는 세부적으로 어떠한 길이 있나요? 두루뭉술하게 보안 관련 직종을 가고 싶다고만 생각하고 있습니다.. ㅠㅠ

**Comment by DominiQN** [comment]
부디 짧게나마 관심을 가지고 답변해주시면 정말 감사하겠습니다..

**Comment by babomose** [comment]
안녕하세요, 답변은 다음과 같습니다.

1. 어떤 보안 직무에서 일을 하느냐에 따라서 다릅니다. 만약 웹보안과 관련된 공부를 하신다면 자주 쓰는
 문법은 공부할 필요가 있습니다. 
만약, 웹 보안에 관심이 있으시다면 게시판이 들어간 웹사이트를 꼭 제작하는 것을 추천해 드립니다.
 게시글 저장, 삭제, 수정 검색 기능 등을 통해 자연스럽게 웹 서버와 DB의 관계를 이해하게 됩니다. 그 후 webgoat와 같은 도구로 웹 해킹을 공부 할 수 있습니다.
참고 URL: https://www.owasp.org/index.php/WebGoat_Installation#Installing_Java_and_Tomcat

2. 대학원에 갈 때는 신중해야 합니다. 2년이라는 세월에 생각보다 소중하기 때문입니다. 일단 무엇 때문에 가는지 묻고 싶습니다. 보통 다음과 같은 이유 때문에 갑니다.
1) 취직  2) 학벌  3) 인맥  4) 연구(향후 박사 과정)  5) 호기심
질문 하신 분의 경우 1) 의 이유로 대학원을 선택하려고 하는 것 같습니다. 저는 일단 대학원에 들어가기 전에 공부를 하며 이력서를 넣어보라고 권하고 싶습니다. 완벽하게 공부가 끝난 후 취직을 하는 경우는 별로 없습니다. 저는 보안 신입들에게 자신이 원하는 보안 직무와 관련한 공부를 하며, 계속해서 이력서를 넣어보라고 권하고 싶습니다. (보통은 자신의 공부가 완벽하게 끝나야 이력서를 넣을 수 있다고 생각합니다.)
사회 초년생이 회사에 들어와서 바로 뛰어난 역량을 보여줄 것이라고 생각하는 경우는 드뭅니다. 차라리 계속해서 공부를하고 있고, 해당 직무와 관련해 관심이 많다는 것을 보여주는 것이 더 빠르게 취직하는 길이라고 생각이 됩니다.
만약 대학원을 생각하신다면, 단순하게 취직을 생각하는 것이 아니라 내가 향후에 지원하고 싶은 보안 직무와 대학원에서 소속될 연구소의 연구주제를 연결해야 합니다. 또한 해당 연구 주제에 깊은 지식을 가지고 있는 교수님의 제자로 가는 것을 추천 드립니다.

3. 정보보안 직종을 나누는 기준은 여러가지지만 제 기준으로는 크게 다음과 같습니다.

1) 정보보안 솔루션 개발자
- 보안 솔루션은 판매하는 기업의 개발자
- 구글에 '정보보안 솔루션' 이라고 검색해서 나오는 많은 기업이 실제 솔루션을 개발하고 판매하고 있습니다.
- 실제 솔루션을 개발해야하기 때문에 보안 지식보다 개발 능력이 더 중요합니다.

2) 모의 해킹 전문가
- 모의 해킹도 분야가 다양합니다.
- 웹해킹, 시스템 해킹, 모바일 해킹 등이 있습니다.
- 실제 사회에서는 웹해킹과 모바일 해킹의 수요가 가장 많습니다. (안랩, 인포섹)
- 그 외에도 리버스 엔지니어링을 통해 소프트웨어, IoT 임베디드 장비를 해킹/컨설팅 해주는 회사도 있습니다. (그래이 해쉬, http://grayhash.com/html/Main.html)

3) 관리적 보안 컨설턴트
- 최근 수요가 많은 관리적 보안컨설팅은 ISMS입니다.(올해 ISMS와 PIMS가 통합될 예정입니다.)
(https://isms.kisa.or.kr/main/)
- ISMS는 일정 규모와 조건이 되는 기업이 지켜야할 정보보호관리체계 인증입니다. 
- 기업이 정보보안 정책을 세우는데 도움을 주는 역할입니다.
- 아래 URL 참고하시면 컨설팅 전문 업체를 확인할 수 있습니다.
https://www.kisa.or.kr/business/protect/protect1_sub4.jsp

4) 관제/CERT
- 관제는 24시간, 365일 IT 자원을 보호하는 일을 합니다.
- 기업을 보호하는 정보보안 장비의 로그를 보고 실제 침해사고 있는지 판단하는 일까지 합니다.
- 더 좋은 대우를 받아야할 직종이지만, 진입장벽이 낮습니다.
- 그리고 고생에 비해서 좋은 대우를 받지 못해 이직률이 높습니다.

- CERT는 침해사고대응 팀을 말합니다. 실제 공격이 이루어졌다면, 어떤 경로를 통해 발생했는지 분석하고, 개선하는 일을 합니다. 

5) 기업의 보안 운영자 (기술적)
- 한 기업의 보안 운영자 입니다.
- 기술적 운영자의 경우, 실제 보안장비(방화벽, IDS, IPS, DLP 등)를 운영 관리합니다.

6) 기업의 보안 운영자 (관리적)
- 관리적 건설팅을 한 기업을 위해서 집중적이고 디테일하게 책임을 갖고 한다고 생각하면 됩니다. 

7) 정보보안 솔루션 엔지니어
- 정보보안 솔루션의 설치, 유지보수를 하는 직업입니다. 
- 관련 솔루션의 정보보안 지식이 필요합니다.


이상 제가 아는 대표적인 정보보안 직무 7가지 였습니다.

좋아하는 것과 잘하는 것을 잘 살펴보시고 좋은 결정을 하셨으면 좋겠습니다.

감사합니다.
