### ISSUE TITLE
아톰으로 만든 코드가 github에 올라가면서 문제가 생길 수도 있나요?

### ISSUE THREAD

**Issue by hy20n** [codingeverybody/codingyahac#781]
# 해결하고자 하는 문제
깃헙 저장소에 코드, 사진을 올린 후 설정에서 링크를 받아낼 때 페이지에서 오류가 듬

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Mac os 10.9 html

# 시도해본 방법
코드에 오류가 있는지 몇시간동안 보고 크롬으로 열어보았을 때도 제가 원하던 대로 잘만 작동했는데 Github에 저장소를 만들고 링크를 추출해낸 후? 링크를 클릭해보니 에러가 뜨거나 README에 적힌 것만 뜹니다

**Comment by yoobato** [comment]
혹시, 작업하고 계신 Github Repository 주소가 https://github.com/hy20n/ootd 이게 맞으신가요?

위 Repository에 대한 Github Pages 에 접근하는 주소는 아래와 같습니다.
https://hy20n.github.io/ootd/

한 번 들어가서 확인해보시겠어요? 저는 이미지가 잘 뜹니다!
