### ISSUE TITLE
깃 커밋 질문입니다.(혼자 해결했습니다)

### ISSUE THREAD

**Issue by hackyeah039** [codingeverybody/codingyahac#783]
# 해결하고자 하는 문제
1. 깃 커밋한 레포 확인이 안됩니다.

# 코드 혹은 오류
깃 커밋은 잘되어서 깃헙에서 얼마나 되었는지 볼려는데 커밋한게 없습니다;;

깃 로그를 봐도 커밋한 흔적이 보이고, git config --list 해도 제 이름과 이메일이 제대로 config 
되었는데 왜 레포에는 커밋이 안올라갔을까요ㅠㅠ

git config --list (결과)
![image](https://user-images.githubusercontent.com/52439116/62818382-b26a5880-bb81-11e9-8277-384c7bf60801.png)

git log(결과)
![image](https://user-images.githubusercontent.com/52439116/62818398-da59bc00-bb81-11e9-8440-d915ed6757b6.png)

제가 commit 하기 원하는 repo에 fork를 해서 clone 해볼려고 시도를 해봤지만 fork 누른순간
```
Can’t find what you’re looking for?
You don’t have permission to fork to these organizations:
```
이런 팝업창이뜹니다. 이건 제 레포이고 제 아이디인데..  어디서 잘못된걸까요?

# 환경
#gitbash, #github,  

# 시도해본 방법
첫번째.우선로그를봐서 히스토리를 봤다.
두번째.히스토리는 제대로 잘나와서 .config가 잘못되었는지 확인을 해봤다.
세번쨰..config상 정보들도 똑같아서 레포에서 직접 fork해서 clone과정을 거쳐야 하는걸로 추측하고
fork 를 시도해봤지만, 허락없이 안된다는 팝업창에 좌절했다;; 

#어떻게 해결했는지
git push 를 안해줬었다..
![image](https://user-images.githubusercontent.com/52439116/62818715-d465da00-bb85-11e9-8753-1298950763b9.png)
이런시식으로 push 를 해주니깐 가만히 있길래 엔터를 쳐도 아무것도 안나오고해서
글자를 치고 엔터를 쳤더니 이런식으로나왔다.. 이상이 있는건가?

**Comment by yoobato** [comment]
혼자 해결하시고, 해결해주신 방법까지 공유해주셔서 감사합니다!
적어주신 것처럼, Git의 경우 Repository에 변경사항을 반영하는 과정이 2단계로 나뉘어져 있습니다.

Commit -> Push 순으로 이루어지는데요,
Commit의 경우 일단 내 로컬(local)에만 변경사항이 적용되어 반영됩니다.
이 상태에서, 원격지(origin)에 있는 Repository에 변경사항을 반영하고 싶다면, Push를 하게 됩니다.

따라서, Push 까지 끝마쳐야, 실제로 원격지의 Repository 까지 반영이 되는 것입니다!
