### ISSUE TITLE
비전공자의 해결하고싶은 문제에대한 진로

### ISSUE THREAD

**Issue by Eunseung** [codingeverybody/codingyahac#784]
안녕하세요.
일전에 기술질문란에 질문을 올렸습니다. 그런데 거기에는 진로관련해서도 질문이 있더라구요 그래서 효율적인 질문을 위하여 여기에 다시올리려고합니다.
----------------------------------------------------------------------------------------------------------
문제를 해결하고싶어서 코딩을 접하게된지 3개월 인 사람입니다.
(HTML,CSS,JS까지 공부를했습니다.)
넘쳐나는 식당과 시설들, 우리는 거기서 어떤것을 선택할지 조건이 더 좋은쪽으로 생각하게됩니다. 하지만 맛집어플이며, 네이버에서 검색, 인스타그램을 통하여 여기저기 왔다갔다 해야하는 에너지와 시간을 낭비하게 되죠, 저는 이러한문제점을 해결하고싶어서 흩어졌던 것들을 총합하고, 크라우드소싱을 이용하여, 없어진 식당이나, 영업시간이 바뀌거나 갑작스런 휴무나 일이 생기고, 그리고 네이버 블로그 같은 경우엔 돈주고 맛집이라는 소개가 많은데, 사람들이 실시간으로 평가함으로써 보다 정확한 평점이 나올 수 있는 사이트를 구축하고싶습니다.

너무나 큰 프로젝트라 어디서부터 접근을 해야할지 감이 잡히지않습니다.
1. 미국의 "Yelp" 라는 사이트가 실제로 이러한 서비스를 제공하고있는데, 사이트 따라하기는 어떻게 하는지 궁금합니다.
2. 아울러 서비스를 제공하기에 앞서, 각 업체들에게 소정의 수수료를 받고 번영할 수 있는 블록체인 기술에는 어떤것이 있을까요
3. 개발자님들의 시선에는 추상적으로 보이시겠지만, 제가 너무나 큰 욕심을 가지고있는지, 
4. HTML,CSS,JS 까지 배웠는데 더이상 어떻게 프로젝트를 시작해야할지 모르겠습니다.
--------------------------------------------------------------------------------------------------------
2,3,4 번에 관한 답변은 감사히 받았습니다. 
1번과, 그리고 네이버 블로그, 인스타그램, 여러다른 시설소개사이트들에대한 데이터를 클릭하면 그곳으로 넘어갈 수 있게 하고싶은데, 찾아보니 저작권에 관련해서 제재를 받는다고 하는데 방법이 없는 것일까요
긴 글 읽어주셔서 감사합니다.

**Comment by studroid** [comment]
우선 제가 https://github.com/codingeverybody/codingyahac/issues/657 이슈에 답글을 달아드린 것처럼, 웹2, 그리고 이후엔 [웹3](https://opentutorials.org/course/3167)까지 학습하고 개념을 이해하시는 것이 먼저일 듯합니다.

Yelp처럼 이미 하나의 큰 완성된 서비스는, 웹 개발에 대한 전반적인 지식 없이는 따라만들기 어렵습니다. 생활코딩에서 웹1, 웹2, 웹3까지 학습을 하신 후에 프로젝트 설계를 하고 진행하시는 걸 추천드립니다. 너무 급하게 가려고 생각하지는 않으시는 게 좋을 듯해요! 100m 달리기가 아닌, 마라톤이라고 생각하시면 좋겠습니다 :)

웹 서비스 개발에 대한 이해가 먼저 되신다면, 특정한 사이트를 따라만드는 것은 생각보다 쉬울 수 있습니다.
구글에 [yelp clone coding](https://www.google.com/search?q=yelp+clone+coding&oq=yelp+clone+coding&aqs=chrome..69i57j69i64.3322j0j4&sourceid=chrome&ie=UTF-8) 이라고 검색을 해보시면, Yelp를 따라 만드는 과정들이 나와있어요. 대부분 영문이기는 하지만, 서버, 데이터베이스, 클라이언트 등에 대한 개념을 알고 계시면 영어를 잘 몰라도 따라갈 수 있답니다.

---

다른 사이트로 넘어가게 하는 것 자체는 저작권에 이슈가 없습니다. 다만 다른 사이트의 정보를 가져와 내 사이트에 보여주겠다고 한다면 저작권 이슈가 생길 여지가 있습니다만, 컨텐츠를 단순히 복제하여 내 사이트에서 이윤을 만들어내는 게 아니라 원본 사이트로 연결하여 매출 등에 도움이 되도록 하신다면, 문제가 되지 않거나 원본 사이트와의 제휴를 통해 해결할 수 있는 가능성도 있습니다.

대표적인 예로는 [쿠폰모아](https://www.couponmoa.com/index.do)라는 곳이 있는데, 여기서는 각종 소셜커머스의 정보를 모아서 보여주고, 제품 구매를 위해서는 실제 페이지로 링크를 연결하고 있어요. 이런 방식이라면 큰 문제가 되지는 않으리라 생각합니다 :)

**Comment by Eunseung** [comment]
와진짜 어떻게 이렇게 정성스럽게 답장을 해주시나요,, 두번쨰 답변까지 너무너무 감사드립니다..

**Comment by fermat39** [comment]
의욕이 있으시면 분명히 하실 수 있으실거예요...
방법론적으로 쪼개고 쪼개고 쪼개서 작은 단위부터 시작해보시는 것을 어떠실까요?
그리고, 재미있고 해보고 싶은 것부터 시작해보세요...

또한, 혼자서 하면 외로울 수도 있고 아이디어가 잘 구현이 되지 않으실 수도 있어요.
같이 할 수 있는 동료 및 네트워크를 활용해보시는 것도 좋을 것 같아요...

코딩야학은 며칠로 끝나겠지만, 이곳에 계신 다른 멘토님들도 계속해서
도움은 주실 수 있으실 것 같습니다.

저도 기다리고 있습니다! ㅎㅎ 화이팅입니다!

**Comment by studroid** [comment]
> 와....진짜 어떻게 이렇게 정성스럽게 답장을 해주시나요,, 두번쨰 답변까지 너무너무 감사드립니다..
> 제가 기프티콘이라도 보내드리고싶은데 어떻게 보답할 수 있는 방법이 없을까요?

나중에 프로젝트를 훌륭하게 마무리하시고, 코딩야학이나 생활코딩 커뮤니티에 성공적으로 만드신 사이트를 올려주신다면 그보다 큰 보답은 없을 듯하네요~ ㅎㅎㅎ

짧지 않은 길이지만, 분명히 완주하시리라 믿습니다 :) (물론 이후 다른 프로젝트로 바꾸실 수도 있겠죠!)
앞으로도 의논이 필요하신 부분이 있으면 언제든 알려주세요!
