### ISSUE TITLE
sublimetext의 sidebar enhance 패키지 기능의, F12기능이 실행되지 않습니다

### ISSUE THREAD

**Issue by tomowhite** [codingeverybody/codingyahac#785]
하위 링크의 강의에서 sidebar Enahance 패키지를 설치하고, 실행하는 것에 대한 질문입니다.
https://opentutorials.org/module/406/3609

# 해결하고자 하는 문제
sublimetext의 sidebar enhance 패키지 기능의, F12기능이 실행되지 않습니다

# 코드 혹은 오류

```
실행할 파일의 jsbasic.html 파일의 코드 입니다. 
<!DOCTYPE>
<html>
  <head>
    <meta charset="utf-8">
      <title></title>
  </head>
  <body>
    <script>
      alert('Hello world');
    </script>
  </body>
</html>
```

``` 
Edit project preview urls 에 작성한 코드 입니다.
{
	"‪E:\cording\JS\jsbasic.html":{
		"url_testing":"http://testing",
		"url_production":"http://domain.tld"
	},
	"C:/Users/luna/some/domain2.tld":{
		"url_testing":"http://testing1",
		"url_production":"http://productiontld2"
	}
}
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도우10, html, 라이브러리 모름, sublimetext 공부중 

# 시도해본 방법
1. sidebar를 선택 설치하고 나서 설치 성공했다는 문구를 보지 못했습니다. 그래서 다시 설치하려니 sidebar enhance로 검색을 하니 enhancements to sblime text sidbar, files and folders 가 나오지 않았습니다. 그래서 설치가 잘 되었다고 판단했습니다.
2. 그러나 해당 파일에서 F12키를 눌러도 실행되는 창이나 표시 등이 나오지가 않습니다.
3. 그래서 "파일 우클릭> project> Edit project preview urls"을 선택하여 열리는 창에, 상위 코드를 복붙하고 저장을 하고 다시  jsbasic.html 파일에서 F12를 눌렀으나 여전히 아무것도 실행되지 않습니다. 
4. 도와주세요~

**Comment by znffl** [comment]
안녕하세요.
`Preferences > Package Settings > Side Bar > Key Bindings - User` 을 선택 하신 뒤
아래 코드를 추가한 뒤 restart 후 F12를 누르면  됩니다.

```
[ 
	{ "keys": ["f12"], 
		"command": "side_bar_open_in_browser" , 
		"args":{"paths":[], "type":"testing", "browser":""} 
	}, 
	{ "keys": ["alt+f12"], 
		"command": "side_bar_open_in_browser", 
		"args":{"paths":[], "type":"production", "browser":""} 
	}, 
	{ "keys": ["ctrl+t"], 
		"command": "side_bar_new_file2" 
	}, 
	{ "keys": ["f2"], 
		"command": "side_bar_rename" 
	}, 
]
```
[참고 URL 사이트 ](https://webdir.tistory.com/398)

확인 후 해결이 안되셨거나 궁금한점이 있으시면 이슈를 다시 open 해주세요.
