### ISSUE TITLE
코딩야학; 깃허브에서 아이프레임 지원안하나요?

### ISSUE THREAD

**Issue by eungseok** [codingeverybody/codingyahac#787]
# Web1강의를 듣고 있습니다.
강의에서 나온대로 유튜브에 있는 공유(iframe)소스를 복사해 웹페이지에서 실행해보니
제 컴에에서 재생이 되는데 깃허브를 통해 온라인상에서는 발행하니 전혀 뜨지가 않습니다. 
그냥 복붙한 똑같은 파일인데; 둘의 차이를 잘 모르겠어서 질문드립니다 ㅠ

<iframe width="560" height="315" src="https://www.youtube.com/embed/XI9MU6pPU20" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by yoobato** [comment]
혹시, 테스트하고 계신 Github repository 주소가 https://github.com/eungseok/test2 이게 맞나요?

https://eungseok.github.io/test2/1.html
위 링크에 들어가보니까, 저는 iframe 안의 유투브가 정상적으로 뜨는데, 한 번 확인해보시겠어요?

**Comment by nurikim1** [comment]
저도 그러네요 해결하셨나요..?

**Comment by yoobato** [comment]
@eungseok @nurikim1 혹시, 어떤 웹브라우저 사용하세요?

**Comment by nurikim1** [comment]
@yoobato 저는 크롬이요! 크롬에서는 안되고 익스에서는 되는데 ㅠㅠ이유가뭘까요ㅠ

**Comment by yoobato** [comment]
@nurikim1 아무것도 뜨지 않으시는건가요? 아니면, 오류 화면이 뜨나요?

혹시, iframe 태그를 통해 띄우려는 페이지의 주소가 https 가 아닌, http로 시작하나요?
(그렇다면, https://stackoverflow.com/questions/48612913/simple-iframe-is-not-displayed-on-github-pages 이것도 한 번 참고해보세요!)

**Comment by nurikim1** [comment]
@yoobato 아예 화면이 흰화면으로 나와요,,! 이따 다시확인해봐야겠어요!!! 감사합니다!

**Comment by nurikim1** [comment]
@yoobato 안녕하세요 yoobato님 말씀대로 http로 되어있네요.. 
그럼 현재로서는 방법이 없는건가요?ㅠㅠ

**Comment by yoobato** [comment]
@nurikim1 

https 안에서, http 페이지를 띄우는 것은 보안 문제 때문에 대부분의 웹 브라우저에서 막고 있는 것으로 알고 있습니다. iframe 안에 띄우는 페이지도 https 를 사용해야 합니다.

**Comment by nurikim1** [comment]
@yoobato 그렇군요 ㅠㅠ 답변 너무 감사합니다!

**Comment by eungseok** [comment]
@yoobato 아 저도 해결이 됐습니다. 답변 감사드립니다!ㅠㅠ
