### ISSUE TITLE
이미지를 첨부했는데 웹에서 다른건 다 뜨는데 한개가 안떠요..

### ISSUE THREAD

**Issue by heehyeon1** [codingeverybody/codingyahac#79]
안녕하세요^^ 늘 좋은강의 감사하게 생각하며 
강의 보면서 열심히 실습하고 있는데 이미지가 한개 안 떠서요...
그냥 안 뜨는 이미지를 삭제 할까 했는데 왜 그런지 궁금하더라고요..
다른 이미지들 처럼 500크기로 했는데 유독 안 이미지만 안뜨길래 강의에서 알려주신대로 이미지 속성을 100% 로도 해보고 16px라고도 해보고 16이라고도 해보고 했는데도 안되요..
알려주시면 참 속이 시~~~~원 할것 같은데....도와주세요~~^^
![20180109_000422](https://user-images.githubusercontent.com/35229218/34678078-65b5fbf8-f4d5-11e7-9d6f-59d57370e0c6.jpg)

사실 이 사이트도 온통 영어라 잘 모르지만 어찌어찌 회원가입하고 어찌어찌 질문은 하는데 이렇게 하는게 맞는지 확신은 잘 안 갑니다... ㅎㅎ 이사이트에 대한 설명 강의도 혹시...있나요?^^;;;ㅎㅎ 라이브 화면에 질문하기 주소 치고 들어오긴했는데 여기가 어떤 사이트이고 어떻게 활용하는 웹인지 사실 감이 잘 안와요.. ㅎㅎ 영어 공부 부터 해야 되나봐요 ㅎㅎ 감사합니다~^^

**Comment by blackdew** [comment]
1. 실제 폴더 내에 이미지가 존재하는지 이미지 파일명에 오타는 없는지 확인하시면 좋을 것 같습니다. 
2. 윈도우라면 파일명 뒤에 다른 확장자명이 붙어있는 데 숨김으로 표시되지 않는 경우가 있습니다. ("파일명.jpg"로 표시되나 실제 파일명은 "파일명.jpg.txt"되 되어있을 수 있습니다.)
3. 파일을 어딘가에서 다운로드 받으셨다면, 받은 원본 파일이 깨져있거나 다운로드 받으면서 파일이 깨졌을 수 있습니다.  

생활코딩 원격저장소 및 github 관련 강의입니다. 
https://opentutorials.org/course/2708/15395
