### ISSUE TITLE
(사소함 주의) pipenv 가상환경에서 터미널의 pipenv)가 안뜹니다. 

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#792]
사소한 문제긴 한데... 해결이 안되어 올려봅니다 ㅠㅠ 없어도 사는데는 지장 없지만 넘나 신경 쓰이네여... 

# 해결하고자 하는 문제

VSCode 에서 pipenv 가상환경을 시작한 후 터미널에 (pipenv)가 뜨지 않는 문제 해결 

# 코드 혹은 오류
```
J@J-PC MINGW64 /e/VSCodeProjects/likelion
$ pipenv shell
Creating a virtualenv for this project…
Pipfile: E:\VSCodeProjects\likelion\Pipfile
Using c:\programdata\anaconda3\python.exe (3.6.4) to create virtualenv…
[=== ] Creating virtual environment...Already using interpreter c:\programdata\anaconda3\python.exe
Using base prefix 'c:\\programdata\\anaconda3'
New python executable in C:\Users\J\.virtualenvs\likelion-WdsTZA1R\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\J\.virtualenvs\likelion-WdsTZA1R
Creating a Pipfile for this project…
Launching subshell in virtual environment…

J@J-PC MINGW64 /e/VSCodeProjects/likelion
$ pipenv shell
Shell for C:\Users\J\.virtualenvs\likelion-WdsTZA1R already activated.
No action taken to avoid nested environments.
```

# 환경
윈도우 10, VSCode IDE, Bash shell, 파이썬 프로젝트 할 예정. (pipenv) 

# 시도해본 방법

구글링 해보았으나 방법을 찾을 수 없었음. venv의 설정은 .virtualenv/likelion-WdsTZA1R/Scripts/activate 에 있다고 하여 파일을 열어 보았으나 어느 부분을 고쳐야 (pipenv) 가 나오게 할 수 있는지 알 수 없었음 ㅠㅠ

**Comment by fermat39** [comment]
pipenv 말고 virtualenv 로 해보시는 것은 어떠신지요?
저는 virtualenv가 더 깔끔하더군요...

**Comment by yoobato** [comment]
아래 링크 한 번 확인해보시겠어요?
http://blog.daum.net/_blog/BlogTypeView.do?blogid=0fjLE&articleno=29&_bloghome_menu=recenttext

**Comment by jaepil-choi** [comment]
답변 감사합니다. 

@fermat39  저도 뒤늦게 더 찾아보니 pipenv는 편리하지만 [아직 해결되지 않은 몇몇 이슈가 있어서](https://velog.io/@doondoony/pipenv-101) virtualenv가 가장 확실한 방법이라고 하더라고요. 

@yoobato 감사합니다. 참고하여 현재는 pipenv, conda, 오리지날 virtualenv를 다 활용하고 있습니다 ㅋㅋ
