### ISSUE TITLE
안드로이드 activity 전환 시 원하는 viewPager로 이동하는 법

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#795]
# 해결하고자 하는 문제

안녕하세요?

어떤 activity에서 intent를 사용하여 MainActivity로 이동하려고 합니다.
그런데 MainActivity에는 ViewPager가 설정되어 있고, 제가 원하는 ViewPager가 바로 보일 수 있도록 하고 싶습니다.

# 시도해본 방법

intent의 putExtra에 전환하고 싶은 viewPager 정보를 넣었습니다.
```
                intent = new Intent(this, MainActivity.class);
                intent.putExtra("viewPager", 3);
                startActivity(intent);
```
그리고 MainActivity에서는 최초 앱을 실행할 때가 아닌 intent로 페이지가 열렸을 때만 getExtras()를 통해 viewPager 정보를 얻는 방법을 시도해 봤습니다.
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        viewPager = findViewById(R.id.viewPager);
        adapterViewPager = new ViewPagerAdapter(getSupportFragmentManager());
        viewPager.setAdapter(adapterViewPager);

        Intent intent = getIntent();
        if(intent != null) {
            viewPager.setCurrentItem(intent.getExtras().getInt("viewPager"));
        }
```
앱을 처음 구동할 때는 intent가 null이 될 줄 알았는데 아니었습니다.
그래서 본 코드로는 처음 구동 시 에러가 발생했습니다.

**Comment by InyoungAum** [comment]
안녕하세요? 

어떤 Activity에서 MainActivity를 호출 할 때 MainActivity의 상태는 finish()가 되어있는 상태인가요 아니면 Background stack에 가있는 상태인가요? (종료가 안 된) 또 오류 메시지 내용을 불러주시면 답변이 수월 할 것 같습니다!

**Comment by kammaii** [comment]
제가 조금 복잡하게 생각을 했던 것 같습니다.
다시 설명을 드리면,
ViewPager가 설정되어 있는 A 액티비티에서 intent를 통해 B 액티비티로 넘어가고
B 액티비티에서 작업이 끝나면 단순히 B 액티비티만 사라지게 하면 될 것 같습니다.
즉, 뒤로가기 버튼을 누른 것 처럼 B 액티비티는 사라지고 A 액티비티의 직전 페이지(프레그먼트)가 다시 나타나게 하고 싶었습니다.

간단하게, startActivityForResult 로 B 액티비티를 열고 finish() 명령으로 해결했습니다 ^^
감사합니다~

**Comment by kammaii** [comment]
다른 문제가 발생했습니다 ㅜ.ㅜ

A 액티비티로 전환은 잘 되었는데 B 액티비티에서 작업한 데이터가 A 액티비티의 리스트뷰에 반영이 되어 있지 않습니다.
아래와 같이 adapter.notifyDataSetChanged()를 해서 데이터는 반영이 되었지만
```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if(resultCode == RESULT_OK) {
            adapter.notifyDataSetChanged();

        }
    }
```
아마 Fragment 가 새로 불러지지 않고 기존 상태 그대로 유지되고 있는 것 같습니다.
그래서 다른 Fragment로 전환했다가 다시 돌아오면 변경된 데이터가 리스트뷰에 반영이 되어 있습니다.
해당 Fragment를 새로고침(?) 하는 방법이 있을까요?

**Comment by yoobato** [comment]
B 액티비티에서 작업한 데이터를 A 액티비티의 어댑터에 붙어있는 List에 실제로 반영을 하지 않으신 것 같습니다.
A 액티비티에서 `adapter.notifyDataSetChanged()`를 호출하기 전에, 실제 List에 변경된 데이터를 적용하셨는지 확인 부탁드립니다!

정리하자면, B 액티비티에서 작업한 데이터를 어떤식으로 A 액티비티의 adapter에 반영하셨는지요? (A 액티비티에서 `adapter.notifyDataSetChanged()`를 호출하기 전에요!)

**Comment by kammaii** [comment]
아! 답변 덕분에 해결했습니다!
A 액티비티의 해당 fragment가 처음 호출 될 때 Db라는 class에 있는 문자열을 불러오는 메소드(getCollection)를 만들었고 변경된 데이터는 Db class에 바로 적용이 되었는데
B 액티비티에서 finish()를 통해 A액티비티로 전환이 되었을 때 이 메소드가 실행되지 않아서 변경된 데이터가 반영되지 않았던 것이었습니다.
```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if(resultCode == RESULT_OK) {
            list = getCollection(false);    
            adapter = new CollectionListViewAdapter(getContext(), list);
            listView.setAdapter(adapter);
        }
    }
```
그래서 아예 리스트뷰를 새로 불러오도록 수정했습니다.
그런데 adapter.notifyDataSetChanged()로 변경된 부분만 업데이트를 할 수 있으면 더 좋을 것 같은데
이렇게 매번 리스트뷰를 새로 만들면 Db class에 문자열 데이터가 1000개 이상으로 많아졌을 때 앱이 버벅대지는 않을지 걱정입니다.

**Comment by InyoungAum** [comment]
모바일 환경에서 한번에 많은 데이터를 불러오는 것은 지양됩니다. 
만약 서버통신을 통해 리스트를 전체를 로드한다면 볼지 안볼지 모르는데이터들을 로드하여 데이터 낭비나 로딩 시간이 오래걸리는 문제가 발생하기 때문입니다.  

따라서 리스트 뷰에 Pull-to-refresh등을 이용하여 데이터를 업데이트 하거나 
scroll이 끝에 닿았을 때 조금 더 당기는 제스쳐를 통해 남은 데이터를 추가로 로드하는 방법들이 많이 사용 되고 있습니다. 

다음의 링크가 도움이 될 것 같습니다!

https://github.com/shontauro/android-pulltorefresh-and-loadmore

**Comment by kammaii** [comment]
정말 감사합니다!
말씀해주신 대로 리스트뷰의 마지막까지 스크롤을 했을 때 아이템을 10개씩 나눠서 불러올 수 있도록 수정했습니다! ^^
