### ISSUE TITLE
PHP에서 여러개의 체크박스 값 가져오는 법이 있을까요? ㅠㅠ

### ISSUE THREAD

**Issue by marcwoo94** [codingeverybody/codingyahac#798]
# 해결하고싶은 문제
PHP에서 여러개의 체크박스 값 가져오는 방법을 알고싶습니다 ㅜㅜ

도서관 서가의 책 순서 섞임 정도를 분석하는 툴을 만들고 있습니다. 도서관에서 운영하는 DB에 접근 할 권한이 없어 모든 책 정보를 엑셀로 출력한 후, 제가 따로 MySQL로 DB를 만들어 진행하고있습니다. 

아래와 사진들과 같이 id 범위를 지정하면 책 정보를 불러오고, 체크박스들을 클릭한 후 update를 누르면 checkbox1=1&checkbox3=3 이런식으로 주소로 넘어가게까지 만들었습니다.

CO = Checked Out: 대출 중
NiP = Not in Place: 책이 제자리에 안 꽃혀 있고 다른 곳에 있음
CB = Checkbox: 체크 후 update하면 NiP가 Y로 바뀜

![checkbox=value](https://user-images.githubusercontent.com/53594727/62878959-1731d880-bd65-11e9-9df6-7b46c4eed641.PNG)

![list](https://user-images.githubusercontent.com/53594727/62879790-e2bf1c00-bd66-11e9-9666-47d6803e1d9a.PNG)

이제 제가 하고싶은 건 저렇게 주소로 넘어온 체크박스 값들로 쿼리를 날려 NiP값을 업데이트하는 것 입니다. 그런데 며칠 째 끙끙대며 여러 방법을 사용해도 방법을 모르겠습니다...

**체크 안 된 체크박스들도 포함해서 모든 체크박스의 값을 한번에 추출할 수 있는 방법을 알고싶습니다.** 

# 코드 혹은 오류
```
<?php
    echo "<div style='float:left;'>";
      echo "<table>
              <tr>
                <th class='id'>NiP</th>
                <th class='id'>CB</th>
              </tr>
            </table>
      <form action='/test.php', method='get'>"; 

      while($row_nip=mysqli_fetch_assoc($sql_nip_result)){
        $id=$row_nip['id'];
        $nip=$row_nip['nip'];
          echo "<table>
                  <tr>
                    <td class='id'>$nip</td>
                    <td class='id'>
                      <input type='checkbox' style='margin:-3px;' id='$id' name='checkbox' value='$id'>
                    </td>
                 </tr>
                </table>";
      }

    echo "</div>";

      <input type="submit" value="Update">
      <input style="display:none;" name="from" value="<?php echo $from; ?>">
      <input style="display:none;" name="to" value="<?php echo $to; ?>">
    </form>
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

Window 10에서 HTML, PHP, MySQL을 돌리고있습니다.

# 시도해본 방법

$_GET[] 함수를 사용하면 맨 마지막 checkbox값만 출력이 됩니다 ㅠㅠ
JavaScript를 이용하여 아래와 같이 배열로 출력을 해도 어떻게 쿼리를 날려야 하는지 감이 안 옵니다...

![array](https://user-images.githubusercontent.com/53594727/62880931-8c071180-bd69-11e9-8486-fd0a7c3112e6.PNG)

긴 질문 읽어주셔서 감사합니다!

**Comment by Hatser** [comment]
먼저 서버와 클라이언트의 관계에 대한 이해를 확실히 잡아 드리는게 이해하시기 좋을 것 같아요.

우리가 사용하는 HTTP 프로토콜은 기본적으론 비연결성 통신입니다.

이 말은,
PHP 스크립트를 사용해서 완성된 하나의 HTML코드를 한 번 브라우저에게 전송하면 브라우저에서 완성된 페이지 화면을 볼 뿐 서버와 어떤 추가적인 통신도 하지 않아요.

체크박스를 켰다가, 끄는 동작을 하는 사람은 브라우저, 다시 말하면 클라이언트죠.

서버 입장에선 이미 보내버린 편지에 브라우저가 어떤 낙서를 하던지 알 길이 없습니다.

결국 체크박스 값을 `추출`해낸다는 개념보다는, 브라우저가 가지고 있는 체크박스 값을 `다시 서버로 전송`한다는 개념으로 접근하시는 게 이해하기 좋으실 것 같아요.

체크박스의 수정을 서버가 알도록 하는 방법은 정말 많은 방법이 있는데, 대략적인 방향만 말씀드리자면 [`AJAX`](https://opentutorials.org/course/3281)에 대해 알아보시면 좋은 해답을 찾으실 것 같습니다.

**Comment by studroid** [comment]
PHP에서 체크박스 값을 그룹화하여 하나의 배열로 받으시려면 name에 `[]`을 추가해주시면 됩니다.

새로운 업데이트를 받으시면 모든 설정값을 초기화하고 배열의 value로 넘어온 것들만 다시 업데이트하는 방식으로 구현하시면 금방 하실 듯합니다 :) 이후 코드 최적화를 통해 퍼포먼스를 올리시는 방향으로 구현해보시면 어떨까요?

[생활코딩의 예전 강의](https://opentutorials.org/course/1565/74)에서 체크박스 부분을 확인해보시고, 구글에서 php checkbox 로 검색하여 나오는 결과 중 [한 블로그](https://recollectionis.tistory.com/57)를 참고 링크로 드립니다.

**Comment by marcwoo94** [comment]
@Hatser 친절한 설명 감사합니다 :) 

웹 개발 공부 시작한지 얼마 안돼서 기본적인 개념이 많이 부족하네요.. ㅠㅠ

젤 어렵게 느껴지는 자바스크립트를 최대한 안 쓰는 방향으로 가게 되다보니 php만 써서 추출한다는 개념으로 가다보니 어렵게 느껴졌던 것 같아요. 말씀해주신 AJAX도 계속 공부해보겠습니다. 감사합니다!

**Comment by marcwoo94** [comment]
@studroid 쉬운 설명 감사드립니다! 딱 제 수준에 맞는 방법인 것 같아요 :) 👍 

말씀해주신 방법으로 checkbox 값들을 하나의 배열로 받아 foreach문으로 쿼리를 날리는 것 까지는 했어요! 그런데 한번에 업데이트가 안 되고 새로고침을 한 번해야 제가 날린 쿼리가 적용이 되더라구요? 왜 그럴까요??

`      if (isset($_GET['checkbox'])){
        $checkbox_value = $_GET['checkbox'];
        $checkbox_count = count($checkbox_value);
          foreach ($checkbox_value as $checkbox_count){
            $sql_nip_fix = "UPDATE not_in_place SET nip='T' WHERE id = $checkbox_count";
            $sql_nip_fix_result = mysqli_query($conn, $sql_nip_fix);
          };
      }
`

**Comment by yoobato** [comment]
> @studroid 쉬운 설명 감사드립니다! 딱 제 수준에 맞는 방법인 것 같아요 :) 👍
> 
> 말씀해주신 방법으로 checkbox 값들을 하나의 배열로 받아 foreach문으로 쿼리를 날리는 것 까지는 했어요! 그런데 한번에 업데이트가 안 되고 새로고침을 한 번해야 제가 날린 쿼리가 적용이 되더라구요? 왜 그럴까요??
> 
> ` if (isset($_GET['checkbox'])){ $checkbox_value = $_GET['checkbox']; $checkbox_count = count($checkbox_value); foreach ($checkbox_value as $checkbox_count){ $sql_nip_fix = "UPDATE not_in_place SET nip='T' WHERE id = $checkbox_count"; $sql_nip_fix_result = mysqli_query($conn, $sql_nip_fix); }; }`

DB로 업데이트 하는 PHP 코드와, DB에서 불러오는 PHP 코드가 같은 페이지에 있나요?
그렇다면, `UPDATE` 쿼리를 실행하는 코드가, `SELECT` 쿼리를 실행하는 코드보다 위에 있어야 합니다!

**Comment by marcwoo94** [comment]
@yoobato 우앗 감사합니다! 이제 한번에 돼요!!! 👍 👍 

아직 실력이 부족해서 한 페이지에 다 담으려고만 하네요 ㅠㅠ
