### ISSUE TITLE
안녕하세요. 공부 방향에 대해서 질문을 드리고 싶습니다.

### ISSUE THREAD

**Issue by haung921209** [codingeverybody/codingyahac#799]
안녕하세요
저는 이제 4학년을 마치고, 다음 학기부터 취업 전선에 뛰어들게 된 학생입니다.
요즘 고민이 있어요.

다름이 아니라, 제가 재미있게 한 것에 대해서, 자기소개서에 어떻게 펼쳐야 할지에 대한 것에서 시작한 고민입니다.
이것저것 만들기도 하고, 실제로 결과물로 나온 것도 있는데, 정작 제가 한 것은 코드 기워넣기밖에 없는 것 같아요....
실제 사용자가 많은 서비스를 만들어 내지도 못했고, 단순히 그냥 구현만 해낸 것 같아요.
그러니까, 코너케이스(?)에 대한 경험이 없는 것 같아요.

어떤 서버를 만들고, 그 서버에 예를 들면 천명이 들어오고, 만명이 들어왔을 때를 생각해서 만든 경험이 전혀 없고, 없는게 보통인데, 그런 경험을 해보고 싶어요. 단순히 구현이 목적이 아니라, 사용자가 많이 들어왔을 때 어떻게 대처해야 할까? 어떻게 코드를 짜야 할까에 대한 고민을 해보고 싶은데, 그런 상황을 만드는 방법을 잘 모르겠어요..... 인위적으로 새로고침이라도 하도록 매크로를 짜야 할까요.....??.......

또, 코드 스타일에 대한 고민이 있어요. 사수가 있으면 좋겠다라고 생각했지만, 학생이다보니 그럴 경험은 없고, 프로젝트를 하더라도 현업의 경험이 없는 사람들이 모여서 하는 경우가 많다보니, 제 나름의 스타일로 굳어지게 될까 겁이 나요..... 오픈소스나 다른 사람의 코드를 살펴보면 배울점이 많다고 하는데 그 중에서 공통점을 찾기도 너무 힘들어요..... 참조할 만한 교과서가 있으면 좋겠는데.... 아니면 누가 '그런거 없어 / 그런거 여기 있어'라고 말해주면 좋겠다는 생각이 드는데.... 없는 것 같아서 슬퍼요...

정리하면, 단순 구현에서 그치는게 아니라, 실제로 특정 상황이 일어나는 것을 인위적으로 만드는 그런 기법이나 방법이 있을까요? 몇건의 프로젝트가 단지 기워넣기만 된 것 같아서, 그래서 자소서에 쓸 말 하나도 쥐어 짜내야 하는 것 같아서 그래서 조언을 구하고자 합니다.

**Comment by TahoLee** [comment]
안녕하세요. 말씀하시는 부분은 경험적인 영역에 속한다고 할 수 있을거 같아요. 
아무래도 취업을 생각하면 개발에서 실제적으로 일을 해야하니까요. 
하지만 이런 경험은 사실 정답이 없는 거 같아요 ㅎㅎ 만명의 동시접속을 해결했다고 백만명의 사용자에 대한 문제에 바로 적용할 수 없을것이고, 일억, 십억의 사용자의 경우는 또다른 문제를 만들수 있어요. 그러니까 실전문제집같은 (정답이 정해진 ) 교과서는 없다고 보는게 나을거 같습니다. 

물론 개발을 어떻게 해서 해결했다고 하는, 일련의 개발을 통해 문제를 해결했던 경험담은 있겠지만, 그런 문제해결은 다가오는 미지의 문제에 적용가능할지 알 수 없습니다.  개발능력을 일련의 문제집으로 해결할 수 있다면, 그것은 과거의 문제만을 다루게됩니다. 미래의 필요한 기술은 아직 도전받지않고, 개발되지 않았습니다. 
그러면 어떻게 해야 할까요? 
아마도 이미 시도하셨고, 성과를 이루셨으리라 생각합니다. 학교에서 이거저거 만들었다고 하셨는데, 그런 만들기를 통해서 소위 말하는 개발에 대한 근육을 키울 수 있습니다. 해결해야 하는 문제는 필요한 부분을 구현하면서 서서히 닥쳐오게됩니다. 물론 문제의 난이도는 편차가 있을 수 있지만, 해결못할 수 없는 문제는 없습니다. 인류의 역사가 말해주고 있듯, 원하는 바를 추구하면서 다가오는 어려움을 해결하는것이 변화에 적응하고, 문제를 해결하는 개발능력을 키우는 길입니다. 
제가 드리는 얘기가 다소 뜬금없을 수도 있습니다. 혹은 솔루션이 아니라고 생각할 수도 있습니다. 하지만, 개발은 경험적으로 누적된 능력이 나중에 빛을 발하게 되는데, 그과정에서 거쳐가는 과정은 정답이 존재하지 않고, 사람마다 다른것으로 생각됩니다. 

우선 맘속에 가장 먼저 생각나는, 가장 설레는, 그런 것들을 만들어 보세요. 고잉님이 흔히 얘기하는 "보편적이지 않은 코딩" 에 해당하는 것들을 차근차근 시도해보시는걸 추천 합니다. 

그리고 더 중요한 것은 지금 시작하는것입니다.

**Comment by yoobato** [comment]
저 또한 지금 말씀해주신 것들은 모두 현업에서 배운 것 같습니다.

실제로 회사에서 사람을 뽑을 때, 갓 대학을 졸업한 신입에게 요구하는 역량이 지금 말씀해주신 것들은 아닐 것이라 생각합니다. 저 또한, 여러 회사를 다녀보았고, 인터뷰를 보거나, 면접관 역할도 해보았지만, 대졸 신입에게 물어보는 것들은 수천만명이 들어오는 서버를 설계하라는 등의 문제가 아니라, 학부 수준의 자료구조 혹은 알고리즘 문제를 많이 받거나, 제가 실제로도 많이 물어보게 되는 것 같습니다.

회사를 다니시면, 배우게 되실테니 조급해하지 않으셔도 될 것 같습니다 😄 
혹은, 인턴을 해보시는 것도 추천해드려요!

**Comment by studroid** [comment]
위에 다른 조력자분들이 답변해주신 것을 보시면 아마 스스로도 이미 잘해나가고 계시다는 것을 느끼실 듯하지만, 더 구체적으로 와닿도록 제 경험을 공유해드려보겠습니다 :) (저도 거의 8년 전 자료를 스스로 되돌아보면서...)

---

## 개발 경험

질문에서 말씀하신 것처럼 천 명, 만 명이 동시에 들어오는 서버를 개인이 만들어 유지하는 경우는 없지는 않지만 굉장히 드뭅니다. 그 정도 되면 사실 창업의 영역으로 들어선다고 봐야겠죠? (한 마디로 이 정도 되면 뭘 만드셨든지 큰 수익을 얻으실 겁니다)

창업이 아닌 **취업**을 위해서라면, 사용자가 많은 서비스를 만드실 필요가 없습니다. 사용자가 **있는** 서비스를 만들기만 하면 되는 거죠. 실제로 사용자가 쓰는 서비스를 만드는 것은, 개발자에게 단순히 알고리즘을 개발하는 것보다 훨씬 더 넓은 영역의 능력을 요합니다. 이를 통해 쌓는 경험 자체도 물론 값지지만, 여기서 발견하고 해결해내신 문제들을 잘 정리만 하신다면 누구나 인정해주는 포트폴리오를 만드실 수 있을 거에요.

제가 모바일 개발 처음 시작할 때 만든 앱들과 그 자료들을 통해 구체적인 예를 들어드릴게요(저도 스스로 되돌아보는 건 참 힘드네요... ㅎㅎㅎㅎ).

- [배터리 체커](http://www.tstore.co.kr/userpoc/game/view?pid=0000255017) (현재 플레이스토어에서는 내려감): 첫 업로드는 2일만에 만든 화면 1개짜리 배터리 확인 앱이었습니다. 그땐 배터리 잔량이 %로 표시 안 되는 기기가 대부분이었어요!

- [배터리 체커 홍보 글](https://www.androidpub.com/index.php?_filter=search&mid=appnews&category=214722&search_target=title&search_keyword=battery+checker&document_srl=1696681): 지금 보면 스팸글 같기도... 하지만 이 글을 통해 몇 천 다운로드 이상 올라갔습니다

- [애니멀 배터리](https://www.androidpub.com/2076125): 역시 스토어에선 내려갔습니다만, 배터리 체커 이후로 디자이너 친구들과 함께 만든 진화형 앱입니다...

- [땡구 배터리](https://www.onestore.co.kr/userpoc/apps/view?pid=0000410866): 다른 디자이너 친구와 만든 배터리 체커... 앱이에요 ^^;

위 3개의 앱들은 모두 처음엔 아주 간단하게 시작해서(ex. 캐릭터 1개만 가지고 시작), 계속 업데이트를 하면서 사용자들에게 알려나갔습니다. 그리고 그 과정에서 겪었던 문제들과 해결 방법을 잘 정리하였더니, 여기저기 알려지면서 유저도 조금씩 늘고 개발 강의도 하게 되고 회사도 들어가게 되는 등, 그야말로 제 사회 생활의 시작점이 되었죠. 지금은 여러 경험을 더하면서 다른 영역의 개발을 주로 하고 있고요.

아마 @haung921209 님께서 만든 서비스도, 분명 만드시는 과정에서 여러 문제를 발견하고 해결해나가셨을 겁니다. 그것만 잘 정리해도 충분히 좋은 자료가 될 것이고, 서비스의 사용자를 늘리기 위해 이런저런 업데이트를 적용해보시면서 새로운 문제를 해결해나가신다면, 어떤 서비스가 됐든지 그냥 구현만 해냈다는 느낌은 들지 않으실 거에요 :) (새로운 사용자들을 통해 내 서비스에 대한 코너케이스를 발견하는 걸 목적으로 두셔도 될 거 같아요!).

## 사용자가 많을 때의 대처 방법을 고민하고 싶으시다면

취업을 위해서가 아니라, 개발자로서 더 큰 문제를 만나고 해결해나가고자 하는 욕구가 당연히 있을 수 있습니다. 하지만 위에 말씀드린 것처럼 많은 사용자를 통해 이런 상황을 만나는 것은, 개인 개발자로서는 쉽지 않은 일이죠.

그러나 다행히도, 말씀하신 것처럼 *인위적으로 새로고침하는 매크로* 같은 서비스들이 있습니다.
보통은 부하 테스트 도구, 스트레스 테스트 도구 등으로 불리우는 것들인데, [AWS에서 이에 대해 잘 정리해놓은 자료](https://aws.amazon.com/ko/blogs/korea/how-to-loading-test-based-on-aws/)가 있으니 참고해보시면 좋을 것 같아요!

## 코드 스타일에 대해

코드 스타일에도 역시 정답은 없습니다만(그러니 여러 오픈소스 프로젝트에서도 모두 코드 스타일이 다른 것이겠죠?), 개발을 주로 혼자 하시다 보면 이에 대해 계속 고민이 들곤 하죠. 저도 그랬고요!

하지만 하나의 프로젝트에 대해서는 하나의 규칙을 적용하는 것이 여러모로 이점이 많겠죠. 그래서 언어마다 스타일의 표준안으로 정해놓는 것들을 보통 *코딩 컨벤션*이라고 합니다.

이 컨벤션에 맞게 코딩이 되어 있는가 검사해주는 도구를 일반적으로 Lint라고 하고, 컨벤션에 맞게 스타일을 바꿔주는 것을 Code Formatter라고 해요. 특히 포맷터는 대부분의 IDE에서 기본적으로 제공하는 기능 중에 하나이기도 합니다.

이 두 종류의 도구를 잘 활용하시면, 일관된 스타일의 코드를 **자동으로** 만드실 수 있습니다(참고로 저도 아직 잘 활용하지는 않습니다..;)

아래 사이트들을 참고해보세요! :)

* [Linter를 이용한 코딩스타일과 에러 체크하기](https://subicura.com/2016/07/11/coding-convention.html)
* [리액트 프로젝트에 ESLint 와 Prettier 끼얹기](https://velog.io/@velopert/eslint-and-prettier-in-react)

물론 위 도구들로 모든 게 다 뚝딱 해결되지는 않습니다만, 아마 시작점으로는 충분히 참고할 만한 자료가 될 듯합니다.


# 무엇보다 가장 중요한 것

제 생각에는 *자신감*입니다. @haung921209 님께서는 이미 충분히 잘 해나가고 계시고, 지금까지 한 것만으로도 충분히 자신감을 가지셔도 됩니다. 자소서를 쓰실 때에도, 자신감 있게 쓴 글과 아닌 글은 한 줄만 읽어도 티가 팍 나곤 하니, 꼭 코딩야학을 통해 *자신감*을 얻어가시면 좋겠습니다.

내가 한 게 아무것도 아니다라는 생각을 버리시고, 난 남들이 시키는 것만 하고 놀 때 이런 것도 *스스로* 했어! 라고 생각하시길 바라요!

**Comment by haung921209** [comment]
@TahoLee 
답변 감사합니다:) 여러가지 간단한(?) 한두달짜리 프로젝트를 경험해보고 하다보니, 제가 재미있다고 생각하는 것을 만드는게 당장 도움이 될까?하는 두려움이 있었나봐요..ㅜㅜ 좋은 말씀 감사합니다!

@yoobato
감사합니다:) 인턴은 경험해보고 싶지만, 아무래도 하반기 취업 준비와 여러가지 것들에 어떻게 해야 할지 고민이 많이 있습니다.... 중간에 다른 시험 준비로 2~3년정도가 남들보다 늦은 편이거든요..... 막연한 고민이 아니라 제가 어떻게 해야 할지에 대한 고민을 할 수 있게 된 것 같아요! ㅎㅎ 답변 정말 감사힙니다

@studroid 와! 정말 긴 글이네요 감사합니다:)
게다가 제가 생각했던 것에 대해서도 이렇게 길게 언급해주시다니 ㅜㅜ......

학교에서 배운 것에 대해서는 이것저것 해보고 할 때에도, 여전히 그 안에서 활동하는 느낌이었고, 궁금한 것들이나 필요한 것들 또한 그 안에서 찾을 수 있는 느낌이었는데, 간단한 프로젝트라도 제가 만들어나가려고 하다 보니까, 단순히 궁금한 것도 어떻게 찾아야 할지 몰라서, 또는 찾아도 없는 경우에는 다른 부분이 문제가 있을 것인데 그 문제를 찾을 근육이 훈련되지 않아서 좀 막막한 기분이 많이 들었습니다. 글을 읽어보니 제가 하는 방향에서 조언을 더해서 나아가면 분명 저도 좋은 개발자로 성장할 수 있을 것이다라는 기대감을 가지게 되었습니다. :)

답변 모두 감사합니다. 저도 다음이나 다다음 코딩야학때는 제 분야에서 답변을 달아주는 사람이 되고 싶어졌네요 ㅎㅎ!
