### ISSUE TITLE
sql문 질문입니다.

### ISSUE THREAD

**Issue by kwonminki** [codingeverybody/codingyahac#80]
안녕하세요.  웹 상에서 회원들의 정보를 표로 만들어 출력하는 무언가를 만들었는데요.
문제는 정보를 수정하고, 제거하는 것은 구현을 했으나 새로운 회원을 데이터베이스에 어떻게 넣어야 할지 몰라 질문드립니다. 현재 웹상에는 회원명 회원정보 수정 삭제 이렇게 구성되어있습니다. 하단에 따로 새로운 회원을 추가하는 코드를 만드려합니다. 
질문드립니다. 

1234567891011121314151617181920212223242526272829303132 | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd"><mapper namespace="usermanager">    <select id="searchuser" parameterType="map" resultType="map">        SELECT  USER_NO, USER_NAME, USER_AGE, USER_IMAGE, ROLE        FROM    USERINFO        WHERE     1=1        <if test="searchName != ''">            AND USER_NAME = #{searchName}        </if>        <if test="searchAge != ''">            AND USER_AGE = #{searchAge}        </if>        <if test="searchNo != ''">            AND USER_NO = #{searchNo}        </if>    </select>    <update id="updateuser" parameterType="map" >        UPDATE    USERINFO        SET        USERINFO.USER_AGE = #{updateAge}        WHERE    USERINFO.USER_NAME = #{updateName}    </update>    <delete id="deleteuser" parameterType="map">        DELETE        FROM        USERINFO        WHERE    USERINFO.USER_NAME = #{deleteName}    </delete>    <insert id="pushuser" parameterType="map">        INSERT INTO USERINFO(USER_NO, USER_ID, USER_PSWD, USER_NAME, USER_AGE, USER_IMAGE, USER_ADDRESS, USER_PHONENUMBER, MAILPUSH_USE, ROLE)        VALUES(#{pushNo}, 'id', '1234', #{pushName}, #{pushAge}, 'sample1.png', '주소', '01012345678', '1', 'ROLE_ADMIN');    </insert></mapper>Colored by Color Scripter | cs
-- | -- | --
![image](https://user-images.githubusercontent.com/33779055/34730335-6f0faf3c-f5a2-11e7-9182-9eb28be46957.png)

mapper 파일입니다.

DROP TABLE USERINFO;

CREATE TABLE USERINFO(
  USER_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(50),
  USER_PSWD VARCHAR2(150), --> 암호화 저장 
  USER_NAME VARCHAR2(50),
  USER_AGE NUMBER CHECK(USER_AGE >= 10 AND USER_AGE <= 100),
  USER_IMAGE VARCHAR2(100),
  USER_ADDRESS VARCHAR2(200) NOT NULL,
  USER_PHONENUMBER VARCHAR2(50),
  MAILPUSH_USE INTEGER, --> 1/0, 1 : push yes, 0 : push no
  ROLE VARCHAR2(20) NOT NULL, --security auth option
  PRIMARY KEY(USER_ID)
);

sqldeveloper상에서 친 코드입니다.

저는 데이터베이스에 직접 데이터를 올려놓고 테스트를 하였는데 그 때 만들어놓은 테이블형식입니다.

INSERT INTO USERINFO(
  USER_NO, USER_ID, USER_PSWD, USER_NAME, USER_AGE, USER_IMAGE, USER_ADDRESS, USER_PHONENUMBER, MAILPUSH_USE, ROLE) 
VALUES(
  1, 'id', '1234', '이름', 20, 'sample1.png', '주소', '01012345678', '1', 'ROLE_ADMIN');

어떻게 해야 새로운 정보를 insert 할 수 있는지 묻고싶습니다.

추가로 color scripter이라는 사이트를 사용하여 붙여넣었는데 저렇게 나오네요. 코드를 어떻게해야 가독성좋게 올릴수있나요?  
  
  어제 질문했는데 답변이 없어 혼자 이것저것 해보았는데 계속하여 500에러가 납니다. ㅠㅜ 제이슨 형식으로 넘어가는것 까지는 확인했는데, 넘어간 후 파일처리가 안되는 듯 합니다. 

$.ajax({                                url: "http://localhost:8090/controller/pushuserdb",                                type: 'POST',                                dataType: 'json',                                data: trans_json,                                contentType: 'application/json',                                mimeType: 'application/json',                                beforeSend:function(){                                        $('.wrap-loading').removeClass('display-none');                                    },                                    complete:function(){                                        $('.wrap-loading').addClass('display-none');                                    },                                success: function(retVal){                                    alert("success ajax..." + '/' + retVal.val);                                    if(retVal.resultCode == 1){                                        var infodialog = new $.Zebra_Dialog('<strong>Message:</strong><br><br><p>등록성공</p>',{                                            title: 'Blog Test Dialog',                                            type: 'confirmation',                                            print: false,                                            width: 760,                                            position: ['right - 20', 'top + 20'],                                            buttons: ['닫기'],                                            onClose: function(caption){                                                                                            }                                        });                                    } else if(retVal.resultCode == 0){                                        var infodialog = new $.Zebra_Dialog('<strong>Message:</strong><br><br><p>등록실패</p>',{                                            title: 'Blog Test Dialog',                                            type: 'warning',                                            print: false,                                            width: 760,                                            position: ['right - 20', 'top + 20'],                                            buttons: ['닫기'],                                            onClose: function(caption){                                                                                            }                                        });                                    }                                    Colored by Color Scripter | cs
-- | --

![image](https://user-images.githubusercontent.com/33779055/34730274-40b44882-f5a2-11e7-82f2-4113091fca9e.png)

이렇게 넘겼고, pushuserdb를 통해 상단의 mapper파일로 이동되는 형태를 띄고있습니다.

**Comment by kwonminki** [comment]
코드 어떻게 이쁘게 올리나요 ㅠㅠㅠㅠ

**Comment by haebin** [comment]
해달 질문의 경우, 가독성이 떨어져서 답변이 어렵네요.
다음에 질문을 올리실때는 개발환경(Sptring, MyBatis), 에러가 날때는 에러 메시지와 스택 트레이스를 올려주시면 조력자분들이 답변을 다는데 도움이 됩니다.

우선, Spring MyBatis CRUD는 아래 예제를 참고하시고,


혹시, 아래 내용이 원인이 아닐까요?
(에러 메시지로 구글에서 검색하면, 관련한 영문 자료들이 많이 나옵니다.)
https://stackoverflow.com/questions/28114007/crud-using-spring-and-mybatis
