### ISSUE TITLE
미국대학교 Computer Science 학부생

### ISSUE THREAD

**Issue by ndk6879** [codingeverybody/codingyahac#800]
안녕하세요.

미국 대학교 2학년까지 마친 유학생입니다.

컴싸는 대학교 들어와서 처음으로 접하는 과목입니다.

학교에서는 파이썬 Intermediate까지 배우고 개인적인 사정으로 휴학해서 1년정도의 시간이 있습니다.

그래서 최근에 온라인 강의 이것저것 듣고 있는데 문제는

진로를 아직은 못 정하고 있습니다.

어떤 직업이 있고 어떤 직업이 뭘 하는지 몰라서 진로를 명확히 정하지는 못햇는데요. 아직은 그저 배운 걸 토대로 프로젝트를 하면서 실력 쌓자. 이것저것 하다보면 눈이 뜨이고 알게 되고 좋아하는게 생기겟지. 정해 지겟지.

싶었지만 너무 하염없이 기다는 것보다 일단 물어보고 조언을 얻는게 더 나을 거 같아서 이렇게 글 남깁니다.

미국에서 인턴도 하고, 졸업하곤 취업도 해서 한동안 정착하면서 지내고 싶은데 무엇을 어떻게 준비하면 좋을까요?

많은 댓글/조언 부탁드리고 선 감사드립니다!!

**Comment by TahoLee** [comment]
제가 흔히 하는 말인데,  "망치를 들고 있으면 모든 문제가 못으로 보이고, 드라이버를 들고 있으면 모든 문제가 나사못으로 보인다" 는 얘기를 합니다.
세상은 객관적으로 보이긴하지만, 보는사람에 따라 상대적으로 반응하게됩니다. 

짊문하신분의 입장에서는 코딩을 배워서 앞으로 어떤일을 할 수 있을지 가늠이 안되어서 물어보신거 같습니다. 애매할수록 좋을거 같습니다. 코딩을 배워서 할 수 있는것이 명확하다면, 코딩에 대한 직업이 정해져 있고, 할수있는 일과 미래에 대한 직업이 정해져있다고 할 수 있습니다. 이런삶은 뭔가 따분하고, 재미없어 보이지 않나요?

결론적으로 말씀드리면, 개발을 배워서 개발자를 하지 않을수 있고, 코딩이나 기획을 하지 않을 수도 있습니다. 오히려 다른 잼있는 일을 하는데 필요한 기술로 존재할 수 있습니다. 
저도 개발자이지만, 저는 이전에 생명공학을 전공했습니다. 그리고, 유전적인 분석을 하는데, 코딩을 사용하면서 코딩을 실제적으로 적용하게되었습니다. 그리고, 개인적인 메모와 지식의 정리, 생각을 더 개선할 수 있도록 하는데 코딩을 이용했습니다. 
코딩은 충분히 유용하지만, 코딩자체보다 더 중요한 것들이 있을 수 있습니다. 혹은 코딩의 기반을 다져서 프로그램을 더 좋게 만드는데 기여할 수 있습니다. 
중요한것은, 지금 내가 원하는것이 무엇인가를 확인하는것입니다. 손에 들고있는 망치나 드라이버에 해당하는것을 잠시 내려놓고, 산책을 하거나 생각을 하면서 코딩과 개발에 가려져있던, 재미난 무언가를 찾아 보는것이 중요할거 같아요. 그러면 손에서 놓았던 것이 가장 애정하는 것일수도 있고, 다른것이 맘에 들어오면서 코딩은 그저 유틸리티같이 자리잡을 수도 있습니다. 
현재 위치에서 아예다른것들을 접한다 하더라도 이제까지 배웠던 것들은 매우 유용하게 인생의 길에서 동반자 처럼 지낼수 있고, 보다 전문적인 개발자의 길을 선택한다면 아마도 개발의 다른 영역이 재미있게 다가올것입니다. 이미 가던 길보다 매력적이라면 그런길로 성큼 발을 디뎌 보시길 바랍니다!

**Comment by yoobato** [comment]
만들어보고 싶은 것들이 있으시다면, 그런 것들을 지금 배우신 파이썬으로 만들어보는 작은 토이 프로젝트를 한 번 해보시는게 좋을 것 같습니다.

예를 들어, 파이썬으로 일기장 프로그램을 만들 수도 있고, 투두(To-Do) 리스트를 관리하는 프로그램을 만들 수도 있을 것 같아요 😄

**Comment by fermat39** [comment]
앞서 이야기 했지만 
바보 같은 질문도 없고
왕도도 없습니다.

그냥 내가 좋아서 즐겨서 하는 일이 내가 하는 일이 아닐까 생각합니다.

남이 짜준 커리큘럼대로 하는데 당연히 안 맞을 수도 있습니다. 
정작 중요한 것은 내가 재미있어서 내가 하고픈 것 할 때 궁금한 것에 대해서
탐구하고 방법을 찾는 것이 올바른 길이 아닐까 생각합니다.

분명 외롭고 막막하실거예요....
그래도 이곳이 있습니다! 언제든지 연락주세요~~~

**Comment by studroid** [comment]
위에 많은 조력자분들께서 답변해주신 것에 더해, 제가 아래 글들에 남긴 코멘트도 참고해보시면 좋을 것 같아요!

특히 지금 상황에서는 미국이나 한국에서 열리는 해커톤에 참가해보시는 것도 좋을 듯하네요 :)
아래 글들을 참고해보세요!

https://github.com/codingeverybody/codingyahac/issues/663

https://github.com/codingeverybody/codingyahac/issues/799

**Comment by ndk6879** [comment]
@TahoLee 
댓글 감사합니다! 막연히 답답하기만 햇었는데 마음이 어느정도 위안이 됩니다!!
@yoobato 댓글 감사합니다! 뭘 어떻게 앞으로 할지 대충 머리속으로 그려집니다!!
@fermat39 감사합니다!! 어떤 말씀인줄 알겟고 위안됩니다!
@studroid 댓글 너무 감사드립니다!!! 다음에 해커톤도 참여해보고 이것저것 많이 해봐야겠네용!!

모든 분들 댓글 감사합니다!!
두서없이 불안했던 마음이 진정되고 근 몇달간 뭘 해야할지 대충 감이 잡힙니다!!
머리속에 말을 일일이 표현하기는 힘들지만 그래도 어떻게 해야할지는 알겠습니다.
댓글 너무 감사드립니다!!
