### ISSUE TITLE
안드로이드 데이터 관리에 관한 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#802]
# 해결하고자 하는 문제

안녕하세요?

예를 들어 사용자가 안드로이드 앱에 단어를 저장할 수 있는 기능을 만든다고 하면
단어 정보를 저장하고 불러올 수 있는 방법이 여러가지가 있을 것 같습니다.
먼저 서버를 사용하게 되면 앱의 용량은 줄일 수 있겠지만 인터넷에 접속해 있지 않으면 앱을 사용할 수 없을테니 저는 가급적 앱 안에 저장하는 방법을 사용하고 싶습니다.
지금 제 수준에서 생각할 수 있는 방법은 String[] 을 정의하거나 csv 파일을 생성하여 그 안에 단어들을 저장/수정/삭제 하는 방법 정도 입니다.
String[]은 따로 파일이 만들어지는 것이 아니니까 앱을 재실행 하면 단어들이 다 사라질 것 같고 남은 방법은 csv 밖에 없는데, 혹시 현업에서는 어떤 방법을 주로 사용하는지 궁금합니다.

**Comment by TahoLee** [comment]
현업에서 기술구현의 판단은 사용자에서부터 시작합니다. 
사용자의 사용성에서 어느정도까지 허용할 수 있는지 확인해봐야 할거 같습니다. 

만약에 사전같은 앱인데, 사용자가 바로바로 확인해야한다면, 사전의 내용은 모두 오프라인에 있어야합니다. 
단어를 저장하는데, 최근단어는 자주 확인해본다고 가정하면, 최근단어들은 반드시 보여야 하고, 과거의 단어들은 오프라인에서 안보여도 되는 상황이 될것이고, 그렇다면 최근 단어들만 안드로이드 기기에 저장할 수 있을거 같습니다. 
그리고 기술적으로는, 안드로이드앱 내부에서는 sqlite 라고 하는 database가 사용되고 있습니다. 그래서 단어같은 것들은 충분히 내부 데이터 베이스에 저장할 수 있고, 단어들이라고 하면 현대적인 핸드폰들에서는 저장장치 이슈는 많이 없을거 같습니다. 
그리고 android의 firebase기술을 이용한다면 nosql 데이터베이스처럼 단어들을 저장하면서 클라우드 서비스를 통해서 데이터 저장에 대한 이슈와 오프라인에 대한 대비를 같이 해볼수도 있을거 같습니다.

**Comment by yoobato** [comment]
안드로이드 앱 내부(로컬)에서 데이터를 불러오거나 저장하는 방법 중 가장 유명한(?) 방법은 위에 태호님께서 말씀해주신대로 안드로이드 앱 내부에 포함된 [SQLite](https://developer.android.com/training/data-storage/sqlite)를 사용하는 것입니다. 고맙게도, 구글에서는 이를 사용하기 어려울 수도 있다고 판단했는지, [Room](https://developer.android.com/training/data-storage/room)이라는 라이브러리를 제공하고 있습니다. Room은 내부적으로는 SQLite를 사용하고, SQLite를 조금 더 쉽게 쓸 수 있도록 해주는 라이브러리라고 생각해주시면 될 것 같습니다.

저는 개인적으로, [Realm](https://realm.io/products/realm-database)이라는 외부 라이브러리를 주로 사용하는데, 사용하기 어렵지 않고, 빠르며, 오류가 거의 발생하지 않습니다.

**Comment by kammaii** [comment]
답변 감사합니다!
언급해주신 프로그램 이름들이 다 처음 들어보는 것들이라 하나하나 찾아보고 결정하면 될 것 같습니다! :)
