### ISSUE TITLE
진로 상담 부탁드립니다! (재업)

### ISSUE THREAD

**Issue by ndk6879** [codingeverybody/codingyahac#804]
혹시 Computer Scienece 학부생이나 졸업하신 분 계시나요?

안녕하세요.

미국 대학교 2학년까지 마친 유학생입니다.

컴싸는 대학교 들어와서 처음으로 접하는 과목입니다.

학교에서는 파이썬 Intermediate까지 배우고 개인적인 사정으로 휴학해서 1년정도의 시간이 있습니다.

그래서 최근에 온라인 강의 이것저것 듣고 있는데 문제는

진로를 아직은 못 정하고 있습니다.

어떤 직업이 있고 어떤 직업이 뭘 하는지 몰라서 진로를 명확히 정하지는 못햇는데요. 아직은 그저 배운 걸 토대로 프로젝트를 하면서 실력 쌓자. 이것저것 하다보면 눈이 뜨이고 알게 되고 좋아하는게 생기겟지. 정해 지겟지.

싶었지만 너무 하염없이 기다는 것보다 일단 물어보고 조언을 얻는게 더 나을 거 같아서 이렇게 글 남깁니다.

미국에서 인턴도 하고, 졸업하곤 취업도 해서 한동안 정착하면서 지내고 싶은데 무엇을 어떻게 준비하면 좋을까요?

많은 댓글/조언 부탁드리고 선 감사드립니다!!

+) 어제 올렸었는데 글이 삭제가 됫는지 안보이네욤...ㅇㅅㅇ'

**Comment by yoobato** [comment]
어제 올려주신 글에 달린 답변 확인해보시면 좋을 것 같습니다.
https://github.com/codingeverybody/codingyahac/issues/800

다른 조력자 분께서 문제가 해결된 것으로 간주하여, 이슈를 닫으신(close) 것 같습니다.
닫힌(closed) 이슈도, Github 대시보드나 검색을 통해 찾으실 수 있습니다!

**Comment by ndk6879** [comment]
감사합니다!

**Comment by ndk6879** [comment]
> 어제 올려주신 글에 달린 답변 확인해보시면 좋을 것 같습니다.
> #800
> 
> 다른 조력자 분께서 문제가 해결된 것으로 간주하여, 이슈를 닫으신(close) 것 같습니다.
> 닫힌(closed) 이슈도, Github 대시보드나 검색을 통해 찾으실 수 있습니다!

감사합니다!
