### ISSUE TITLE
취업 도전 해봐도 될까요? + 포트폴리오 평가 부탁드립니다.

### ISSUE THREAD

**Issue by jiwon3346** [codingeverybody/codingyahac#805]
신입 개발자로 공부 중에 있습니다.
이번달 안에 이력서를 내보려고 포트폴리오를 만들어봤는데, 객관적으로 어떻게 보이는지 궁금합니다.
무엇을 더 채우고 무엇을 빼야 할지 조언해주시면 감사하겠습니다.

프론트엔드 신입으로 넣을 생각입니다.

[포폴.pdf](https://github.com/codingeverybody/codingyahac/files/3500065/default.pdf)

**Comment by yoobato** [comment]
정말 잘 만드신 것 같은데요? 가능하시면, 이걸 웹페이지로 만들어서 Github Pages에 올려보는건 어떠세요!?
혹은, 개인 웹페이지를 만들어보시는 것도 좋을 것 같아요.

또, 시간이 되신다면 각각의 Github Repository에 README 추가해서 개발 환경 설정이나 어떻게 설치하는지, 어떤 기술을 사용하셨는지 등을 적어놓으시는 것도 좋을 것 같아요!

**Comment by jiwon3346** [comment]
개인 웹 페이지는 아직 하고 싶은 프로젝트가 많아서, 미루고 있었는데 내일 하루동안 느긋하게 만들어 봐야 겠습니다.

그리고 README에 기술에 대해 서술 하는것은 정말 좋은 생각인거 같습니다!

조언 감사합니다.
