### ISSUE TITLE
web1 html 6기를 참여하고 난뒤 생기는 질문들 문의드립니다.

### ISSUE THREAD

**Issue by martinyoon0821** [codingeverybody/codingyahac#806]
안녕하세요 이번 2019년 8월에 web1 html수업을 듣고 질문이 생겨서 문의드립니다.

1. 6기 수료증은 8월19일에 구글이메일로 오는게 맞을까요?
2. 다른 web2 (css,파이썬,자바스크립트..)는 수료증이나 기수가 따로 없나요?
3. 현재 web1 html을 듣고 -> web2 css->  web2 python ->언어 python&ruby
       -> web2 javascript -> 언어 javascript 순서로 수업 들으려고하는데 괜찮을까요?
4. 제 전공이 컴퓨터과인데 머신러닝이랑 빅데이터같은 수업에서 
    도움이 될만한 코딩야학 수업이 있을까요??
----------------------------------------------------
html web1 수업 질문
1) 부록 : 코드의 힘 - 댓글 기능 추가(https://opentutorials.org/course/3084/18594)
이 수업에서 댓글을 만드는 코드를 가져와서 index.html에 넣어서 댓글창을 만들어주는 것을 실습하였는데 이게 원래 
1.html
2.html
3.html 
이 세곳에는 적용이 저는 안되는데 원래 안되도록 코딩되어있는건지 저만 안되는건지 알고 싶습니다.

2) 웹호스팅 (github pages)(https://opentutorials.org/course/3084/18891)
이 수업에서 깃허브에 페이지를 맡겨서 대행업체에 호스팅해서 웹을 개설하는 수업을 진행하였는데 깃허브에 웹을 호스팅하면 평생 제 개인페이지가 개설되는건가요?(개수 제한이나 기간제한이 있는지 알고 싶습니다.)

**Comment by progh2** [comment]
1.2. 
수료증은 “코딩야학 6기”를 참여한 것에 대한 것으로 특정 수업마다 있는 것은 아닙니다. 
(물론 여기서는 web1또는프로젝트 구분은 있지만요) ^^

3. 
한 과정을 이수한 후의 시각으로 매번 다음 강좌들에 대한 내용을 보고 조정해보세요~
사람마다 모두 같은 필요는 없으니까요. 
더 적절해보이는게 있다면 그걸로 방향을 바꿔도 됩니다. 너무 스킬트리에 대해서 고민하지 마세요.
공부하고싶은게 계속 바뀔 수도 있어요~

4.
당장은 해당분야는 파이썬이 직접적으로 관련이 있긴 합니다만.. 검색해보면 해당분야에 대한 수많은 강좌가 있으니 골라 잡아서 보시면 될듯합니다. 
너무 많아서 선택장애가 올 지경일꺼에요.
책도 많이 나와있고요.

**Comment by progh2** [comment]
밑에 수업질문

1. 
각 페이지마다 코드 추가해주셔야 합니다. 
index만 수정했으니 거기만 나올꺼에요. 

2.
깃허브에서 개인 홈페이지나 프로젝트 사이트 운영하라는 용도로 주는 것이라 특별한 제약은 없습니다. 다만 php 등 서버사이드 언어가 안돌아가고 좀 느리다는 점이 한계라고 할까요? 해당 기능을 이용해서 오픈소스 프로젝트 홈페이지를 운영하는 곳도 많으니 정적페이지(html javascript css)만으로만 만든다면 걱정은 별로 안하셔도 될꺼에요.
