### ISSUE TITLE
App 개발 아이폰 AWS

### ISSUE THREAD

**Issue by kimsijin33** [codingeverybody/codingyahac#808]
# 해결하고자 하는 문제
우선 아직은 무엇을 해결하고자 하는 건 아니고요 
궁금한게 있어서요 
AWS 에 App 도 만들어서 올릴수 있다고 들었는데
어떤식으로 되는 건가요? 아이폰 앱은 마켓에 올리는 것으로 알고 있는데요

안드로이드, IOS 둘다 AWS 올릴 수 있나요?

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by yoobato** [comment]
아마도, AWS에서 제공하는 Amplify 서비스를 말씀하시는 것 같아요.

AWS Amplify는 앱을 만들거나, 배포하는 곳은 아닙니다. 다만, Amplify를 사용하면, iOS/Android 앱을 만들 때, 필요한 AWS의 서비스들을 쉽게 사용할 수 있습니다 😄 
iOS, Android, React Native, Web App 등을 지원하는걸로 알고 있습니다.

아래 링크 한 번 참고해보세요!
https://aws.amazon.com/ko/amplify/
