### ISSUE TITLE
[질문] 웹페이지에 프로세싱 코드 삽입하기

### ISSUE THREAD

**Issue by izalam** [codingeverybody/codingyahac#81]
제가 만든 웹페이지에 프로세싱으로 짠 코드를 삽입하고 싶습니다. 
아래 URL 내용을 참고했는데 잘 되지 않았어요. 
http://visualize.tistory.com/141
프로세싱 코드에 class탭을 따로 빼서 코드를 작성했기 때문인지, 
원인을 잘 모르겠습니다. 무엇 때문에 오류가 난 것인지,
오류를 개선해 웹페이지에서 프로세싱 결과물을 볼 수 있도록 구현 가능한지 궁금합니다.

[최종결과물 html 삽입 시도.zip](https://github.com/codingeverybody/codingyahac/files/1612285/html.zip)

**Comment by dongheegy** [comment]
적절한 답변이 될런지 모르겠지만 제가 만든 저장소[저장소](https://github.com/dongheegy/web1/tree/master/example/ProcessingJS)와 [페이지](https://dongheegy.github.io/web1/example/ProcessingJS/processing.html)를 참고하시는 건 어떨까 합니다.
제가 지금까지 해봐서 성공한 경우는... processing 파일을 먼저 추가한 다음 script 태그 안에 processing 구문을 적는 것이었습니다.

**Comment by izalam** [comment]
앗 감사합니다 확인해볼게요 :)!!

2018년 1월 10일 오전 1:24, Choi, Donghui <notifications@github.com>님이 작성:
