### ISSUE TITLE
제가 구상하는 홈페이지입니다. 한번 봐주세요!어떤 comment도 감사!

### ISSUE THREAD

**Issue by Hak-I-Seup** [codingeverybody/codingyahac#812]
현업의 마케팅부족으로 어려움에 직면하여 홈페이지를 구상하였으나,
진전이 없어 헛바퀴도는 심정입니다. 대면하여 문제점과 해결하는 과정으로 완성하고픈 마음입니다.
 원하는 바: 
       1.먼저 layout잡은 후에 contents는 현업을 진행하면서 채워갈렵니다.
       2.반응형 홈페이지 Wordpress Theme를 customization하여 운영하였으면 합니다.
       3.업무 특성이 대여업처럼 판매에 그치지 않고 물품을 돌려받는 과정이 있읍니다.
       4.홈페이지/블로그/카페/SNS/Youtube에 upload시 한번 작성한 것를 공통으로 사용할 수있는 
           flatform이랄까 어떤 형태의 작성방법이 가능한지요?
![layout](https://user-images.githubusercontent.com/53962312/63025845-08722f80-bee5-11e9-9ae5-41e7f5030ad1.JPG)

**Comment by progh2** [comment]
기본적으로 워드프레스를 블로그형태로 운영하는 것 + 특정 안내 페이지로의 바로가기 링크 + 특정 기능페이지 식으로 구성하면 되겠네요~
다만 반응형으로 하기에는 올리신 레이아웃 화면이 너무 자잘한게 많아 보인다고 생각됩니다. 
일단 가장 중요한 기능들 먼저 하나씩 넣어가면서 고쳐나가는게 좋을 것 같습니다. (수리가 메인이니 수리부터 하나씩...)

가장 기본적인 내용인
회사 소개, 역사, 찾아오는 길, 수리스탭 소개,
수리 안내, 요금, 예약안내, 수리기 같은 내용이 
보는사람 입장에서는 가장 필요할 것 같아요. 
콘텐츠를 작성한 후 그 링크를 다른 사이트나 유튜브 등에 링크로 남겨서 서로 오갈 수 있게 하면 말씀하신대로 내용은 이 사이트에 다 모여있게 되겠지요. 유튜브는 따로 채널 파서 재생목록으로 나누어 관련 영상들을 모아놓으면 그쪽에서도 찾아올 수도 있겠고요. 

한번에 많은 것을 하기보다 하나씩 추가하면서 수정해나가면 어떨까요?
특히 콘텐츠가 없는 상황에서는~

**Comment by Hak-I-Seup** [comment]
조언 감사드립니다.
지적하신 내용 하나하나 곱씹어 보면서 이해한 후 연락드리겠습니다.
넘 감사드립니다.
오늘도 즐거운 하루되시길...
전철에서 급히 응신합니다.

2019년 8월 16일 (금) 오전 1:13, Gihun Ham <notifications@github.com>님이 작성:
