### ISSUE TITLE
자바스크립트 클래스 선택 질문드려요.

### ISSUE THREAD

**Issue by heathera2016** [codingeverybody/codingyahac#815]
자바스크립트의 경우
document.querySelector 을 해서 태그나 클래스, 아이디를 선택할 경우 첫번째 것이 디폴트 값으로 선택된다고 알고 있는데 전체 클래스를 선택하고자 할 경우 꼭 document.querySelectorAll과 함께 반복문을 써줘야 하는지요?
CSS에서는 클래스만 선택하면 전체가 바뀌는데, 그에 비해서 너무나 비효율적이어서 여쭤봅니다. 전체 바꾸는 것은 없나요?

**Comment by Hatser** [comment]
`document.querySelectorAll`을 실행하면 어떤 결과이든 배열 형식이 반환됩니다.

이런 배열을 다루기 위해서는 결국  반복문을 사용하셔야 하고. `querySelectorAll`과 유사한 기능을 하는 다른 라이브러리나, 사용자 정의 함수 같은 경우에도 반복문을 사용합니다.

css도 내부적으로 제 기능을 하기 위해 반복문이 사용되지 않을 수 없을거에요. 이 경우에 사용하는 반복문의 기준이랑은 좀 다른 관점일 수는 있겠지만요.

CSS의 기능도 결국 브라우저에서 조건에 맞춰 실행하기 때문에, 작성함에 있어 편리한 것이지 완벽히 효율적이라고 보기는 어렵습니다.

jQuery같은 경우에는 `$.find`로 얻어낸 요소들을 한 번에 조작하는 것이 가능한데,

`$.find('div').addClass('my-div')`

이도 결국 반복문을 사용한 것으로, 실제 성능면에서는 직접ment.querySelectorAll`을 실행하면 어떤 결과이든 배열 형식이 반환됩니다.

이런 배열을 다루기 위해서는 결국  반복문을 사용하셔야 하고. `querySelectorAll`과 유사한 기능을 하는 다른 라이브러리나, 사용자 정의 함수 같은 경우에도 반복문을 사용합니다.

css도 내부적으로 제 기능을 하기 위해 반복문이 사용되지 않을 수 없을거에요. 이 경우에 사용하는 반복문의 기준이랑은 좀 다른 관점일 수는 있겠지만요.

CSS의 기능도 결국 브라우저에서 조건에 맞춰 실행하기 때문에, 작성함에 있어 편리한 것이지 완벽히 효율적이라고 보기는 어렵습니다.

jQuery같은 경우에는 `$.find`로 얻어낸 요소들을 한 번에 조작하는 것이 가능한데,
(`$.find('div').addClass('my-div')`)

이도 결국 반복문을 사용한 것으로, 실제 성능면에서는 순수 자바스크립트로 작성하는 것과 성능면에서 큰 차이가 있습니다.

`querySelector`를 이용하는 경우에도, `querySelector`의 매개변수 문자열에 여러 조건을 추가하는 것 과, 이 조건을 직접, programatical 한 방법으로 체크하는 것은 성능 면에서 많은 차이가 납니다.

[여기](https://jsperf.com/jquery-vs-native-selector-and-element-style/30)에서 성능 차이를 확인하실 수 있어요!

**Comment by heathera2016** [comment]
@Hatser  와 Hatser 님 전문적인 답변 정말 감사합니다!! 주신 링크 들어가서 보니 확실히 jquery보다 순수한 자바스크립트가 빠르네요. 비록 초보지만 이런 퍼포먼스 비교 정말 유익하고 좋은 것 같아요. 뭔가 더 나은 코드를 지향할 수 있을 것 같구요^^ 저도 꿈이 깔끔하고 퍼포먼스 뛰어난 코드를 짜고 싶거든요..^^ 상세한 답변 감사합니다. 즉 프로그램 속에서 전체 선택은 없고, 겉으로 그렇게 보일 뿐 다 반복을 통해서 구해진다는 것 잘 알겠습니다. 좋은 밤  되십시오!! 정말 감사합니다^^
