### ISSUE TITLE
git에 마스터 브런치에 있는 테스트 코드 커밋 되돌리기

### ISSUE THREAD

**Issue by MoonSupport** [codingeverybody/codingyahac#819]
git으로 마스터 브런치만 이용해서 커밋 중에 있었습니다.
그런데 테스트 코드가 생기고도 계속 마스터 브런치에 커밋을 했는데
배포 할려고 보니 테스트 브런치와 배포 브런치 마스터 브런치를 분리하면 좋을꺼 같더군요.

테스트 브런치의 커밋은 그대로 두고
배포 브런치를 새로 파서 리셋으로 테스트 코드 작성 전으로 돌렸습니다.

마스터 브런치도 배포 브런치처럼 해주려고 revert를 하는데
error: a cherry-pick or revert is already in progress

해당 에러가 발생 합니다 어떻게 하면 좋을까요?

**Comment by studroid** [comment]
커맨드라인 도구를 사용해서 git을 사용하시는 거라면, 아래 명령어를 써서 진행 중이던 revert를 중지하고 다시 시도해보시면 좋을 듯합니다 :)

`git cherry-pick --abort`

[이 링크](https://stackoverflow.com/a/12865179)도 참고해서 보시고, 다른 도구를 사용하시는 경우 다시 한번 알려주세요!
