### ISSUE TITLE
POST 405 Error 에 대해 질문드립니다.(Node.js) 

### ISSUE THREAD

**Issue by woosungchoi** [codingeverybody/codingyahac#824]
# 해결하고자 하는 문제

서버 에 런칭 하는 데에 405 에러 가 발생합니다.리소스를 허용하지 않은 문제라는 것은 알겠는데,구체적인 해결 방안 이 떠오르지 않습니다. 사실 리소스를 어떻게 허용해야되는 지 잘 모르겠습니다...서버는 github 에서 기본으로 제공하는 것을 사용하고 있습니다.  

# 코드 혹은 오류

다음 과 같은 오류가 발생 하였습니다...

![image](https://user-images.githubusercontent.com/11676387/63572693-70e49f00-c5be-11e9-87cd-38450430292f.png)

# 시도해본 방법
   CORS 에서 메소드 를 전부  허용하는 방법을 채택해봤는데도 발생하게 됩니다.또한 app 를 전
  부 all 로 개방하여도 오류는 지속됩니다.

<서버 측>
  
![image](https://user-images.githubusercontent.com/11676387/63572923-02541100-c5bf-11e9-8c6b-7fa6e4865bd3.png)

![image](https://user-images.githubusercontent.com/11676387/63573061-565ef580-c5bf-11e9-96a0-2ac85c931dca.png)

<클라이언트 측>

![image](https://user-images.githubusercontent.com/11676387/63573012-392a2700-c5bf-11e9-9a94-fe7bf164f671.png)

# 환경
 win 7 64bit,Node js 10+

**Comment by progh2** [comment]
요청시 헤더를 잘못 넣으신 것 같습니다. json으로 보내는게 아니니 올바르지 않은 토큰이 나왔다는 에러네요

아래 링크 예제를 참고해보세요.
https://codeburst.io/build-a-simple-weather-app-with-node-js-in-just-16-lines-of-code-32261690901d?gi=2c1e9e8fa720

**Comment by woosungchoi** [comment]
감사합니다!많이 도움 되었습니다!
