### ISSUE TITLE
(github)홈페이지 수정방법

### ISSUE THREAD

**Issue by kim18778** [codingeverybody/codingyahac#83]
https://kim18778.github.io/web2
라는 홈페이지의 일부를 수정할려고
apache2 - htdocs 에 수정내용을 올렸습니다.
다음 절차를 알려주세요

**Comment by egoing** [comment]
아래 주소로 들어가셔서 수정된 파일을 업로드 하시면 됩니다. 
https://github.com/kim18778/web2/upload/master

혹은 1.html 파일을 수정하고 싶으시다면 
아래 주소로 들어가셔서 
https://github.com/kim18778/web2/blob/master/1.html

아래 버튼을 누르시면 온라인에서 수정할 수도 있습니다. 

<img width="369" alt="screenshot 2018-01-09 15 06 47" src="https://user-images.githubusercontent.com/303822/34707072-bb7edc34-f54e-11e7-84c5-ea887c349d14.png">
