### ISSUE TITLE
GIt 레포에 커밋된 코드들을 파이썬으로 어떻게 가져와야 할까요? 

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#838]
# 해결하고자 하는 문제

 깃허브 레포에 커밋된 코드들을 가져와 별도 작성한 메모와 코드라인을 연결시켜주는 프로젝트를 하려고 하는데 깃허브 레포를 어떻게 가져와야 할 지 모르겠습니다. 
 검색해서 몇몇 결과가 나오긴 하는데 혹시 여기에 경험자가 있으신지 궁금하여 먼저 여쭙고자 합니다. 

좀 더 자세히 프로젝트 디자인을 적어보자면, 

프로젝트의 목표: 에버노트, 원노트 등의 메모 앱을 써보니 코딩 강좌를 들으며 필기하기가 너무 어려웠기 때문에 소스코드 내 comment로 하기 어려운 노트 필기를 소스코드의 코드라인 1개와 노트블록객체 1개를 각각 연결시켜 해결하고자 합니다. 즉, 소스코드를 편집하다가 필기를 남기고 싶은 라인을 정해 특정 심볼을 남기고 별도의 노트 연습장에 그 라인에 관련된 필기를 하고자 합니다.

이 때 코드라인과 노트를 연결시키는 방법으로 깃 리모트에 커밋된 코드 텍스트를 읽어와 심볼을 Regex로 찾아내고자 하는데, 이 때 깃 리모트에서 커밋과 그 코드 소스를 가져오는데 어려움을 겪는 중입니다. 

프로젝트 순서를 적어보면

1. 코딩을 하다가 필기를 하고 싶은 부분에 특정 심볼을 남기고, 그 부분에 들어갈 노트를 파이썬에서 작성함. (간단한 텍스트노트나 이미지를 포함한 노트 등) 
2. 코드 내에 특정 심볼을 남기고 리모트에 커밋한 것을 파이썬에 불러온다. 
3. 해당 심볼과 노트를 '연결'시킴. 즉, 노트를 읽을 때 해당 심볼이 들어간 코드라인을 함께 읽을 수 있게 함.  

예:
```
def foobar(apple):
  howmany = apple.count() # <@1@>
  return howmany # <@2@> 
```
라는 리모트에 커밋된 코드를 파이썬에서 불러와 <@1@> 자리에 .count() 매소에 대한 설명을 적은 노트를 연결시켜 필기도 하고 나중에 읽어보기도 하고 <@2@> 자리에도 마찬가지로 함수의 return에 대해 참고할 만한 자료를 정리한 노트를 연결시켜 나중에 읽어보기도 함.  

입니다. 

그 외 프로젝트에 대한 기타 조언도 환영합니다. 

# 환경

윈도우10, Python 3.6+

**Comment by Hatser** [comment]
깃허브라면 깃허브API 사용을 추천드립니다.

[여기](https://github.com/octokit/octokit.rb/blob/master/README.md)있는 API를 사용하셔서, `download_url` 값을 받아 raw 데이터의 경로를 얻을 수 있고, 

`download_url` 의 경로에 접근해 raw데이터를 받을 수 있습니다.

커밋 목록에 관련한 정보를 얻기 위해서는 [여기](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository)를 참조하시면 되겠습니다.

**Comment by jaepil-choi** [comment]
@Hatser 와 역시... 여기에 여쭤보길 잘 했습니다. 프로젝트 디자인만 해놓고 뭘 써야할지 몰라서 막막했는데 이걸 토대로 프로젝트 진행해 보겠습니다. 감사합니다!
