### ISSUE TITLE
올라가면 안되는 파일이 이미 옛저녁에 remote까지 올라갔을 때 어떻게 하나요? 

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#839]
# 해결하고자 하는 문제

https://imgur.com/a/HSg1aGq
위의 이미지와 같은 상황입니다. 마스터 브랜치 두 번째 코밋부터 올라가면 안되는 파일이 커밋되고 리모트에도 올라간 상태입니다. 그 후에 feature branch를 두 개나 만들어놔서 해당 커밋으로 돌아가서 나머지 작업을 다 다시하기엔 좀 부담되네요. 

이 경우 제가 원하는건 해당 커밋에서 .vscode/settings.json만 슬쩍 없애버리는건데 혹시 이게 가능한가요? 

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

윈도우10
소스트리 Git 관리 프로그램
VSCode 에디터
파이썬 3.7

또.... 하나 추가질문을 드리자면 분명히 .gitignore에 .vscode/* 라고 표시를 해놨는데도 깃에 해당 파일이 추가가 됐습니다. 너무 이상해서 혹시나 해서 .vscode/ 라고 표시를 바꿔보니 이젠 정상적으로 해당 디렉토리와 하위파일/폴더들이 무시되네요. 왜 /* 를 썼을 땐 제대로 ignore 되지 않았을까요? 제가 임의로 /* 를 붙인거도 아니고 공식 .gitignore 문서에서 그대로 복붙한건데 이상하네요.

**Comment by Hatser** [comment]
해답을 찾을 수 있는 내용이 [여기](https://git-scm.com/book/ko/v1/Git-%EB%8F%84%EA%B5%AC-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%8B%A8%EC%9E%A5%ED%95%98%EA%B8%B0#filter-branch%EB%8A%94-%ED%8F%AC%ED%81%AC%EB%A0%88%EC%9D%B8)에 올라와있습니다. 한 번 확인해보세요

내용이 [여기](https://git-scm.com/book/ko/v1/Git-%EB%8F%84%EA%B5%AC-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%8B%A8%EC%9E%A5%ED%95%98%EA%B8%B0#filter-branch%EB%8A%94-%ED%8F%AC%ED%81%AC%EB%A0%88%EC%9D%B8)에 올라와있습니다. 한 번 확인해보세요

두번째 질문에 대한 토론을 [여기](https://stackoverflow.com/questions/8783093/gitignore-syntax-bin-vs-bin-vs-bin-vs-bin)에서 보실 수 있습니다.

**Comment by jaepil-choi** [comment]
@Hatser 답변 감사합니다. 

어찌 저찌 해결하긴 했느데,,, 이후 추가 질문이 생겨서 이렇게 글을 남깁니다. 

[이 스크린샷](https://imgur.com/a/mV6il44)을 참고해주시기 바랍니다. 

1. 답변에서 알려주신대로 잘 못 올라간 파일을 없애기 위해 filter-branch를 했더니 막 깃이 돌아가더니 같은 커밋이 2개씩 생기고 정체불명의 새로운 브랜치가 생겼습니다. filter-branch를 하면 원래 이렇게 되는 것이 정상인가요? 

2. 또한 pull과 push 또한 갑자기 이상하게 18 commits behind remote / 19 commit ahead remote 이런식으로 이상하게 뜨더라고요... (소스트리 상에서) 이것도 filter branch 때문에 그런건지, 정상적인 일인건지 궁금합니다. 

3. 마지막으로, 그리고 가장 궁금한 것은 다른 스택오버플로우 답변과의 차이인데요 

https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

처음 문제 생겼을 때 구글링해서 해당 포스트를 찾았었습니다. 여길 읽어보면 크게 

- 1) git rm --cached <file> 해라 
- 2) git update-index --skip-worktree <file> 해라
- 3) Hatser님이 알려주신 git filter-branch ... 해라 

가 있는 듯 한데 같은 상황에서 문제를 해결하는 다양한 방법이 있는건지, 아님 셋 다 하는 일이 다른건지 잘 모르겠습니다. 각자 기능이 다르니 명령어도 다를 듯 한데, 이런 상황에서는 그냥 딱 filter-branch만 써야 하는건지 아니면 목적에 따라 명령어가 달라질 수 있는지 궁금합니다. 솔직히 그냥 잘못올린 파일 내린다 라고 추상적으로만 생각했지 구체적인 차이를 잘 모르겠어요 ㅠㅠ

**Comment by Hatser** [comment]
filter-branch 명령은 모든 브랜치에서 해당 명령을 수행해 다시 커밋하기 때문에, 내용이 바뀌므로 모든 커밋들의 해쉬값이 바뀝니다.
화면에서는 해당 프로그램이 자체적으로 커밋들의 내용을 캐싱해 보여주고 있다가 다른 해쉬의 커밋이 나타나자 그 커밋들도 보여주는 것으로 보입니다.


`git rm --cached`
`git update-index --skip-worktree`

위 명령들은 깃에 포함시킬 파일들의 캐시를 정리한 후, 다시 재인덱싱하는 과정입니다.

.gitignore 를 수정한 후에도 기존 깃 파일에 캐싱된 인덱스를 이용해 커밋하기 때문에 이를 재정의하는 과정을 거친 것입니다.

**Comment by jaepil-choi** [comment]
@Hatser 감사합니다. 현재 깃 브랜치의 문제는 완전히 해결되었고 알려주신 /*와 /의 차이도 이번 기회에 확실하게 알게 되어 또 track되면 안되는 파일이 stage되어 커밋이 꼬이는 일을 미연에 방지할 수 있게 되었습니다. 

온라인 상으로 드릴 수 있는 감사의 표시가 글과 좋아요밖에 없는 것이 아쉬울 정도로 많은 도움을 받았습니다. 앞으로도 열심히 코딩하며 모르는게 있을 때 틈틈이 묻고 제가 아는게 나오면 답변해보는 선순환에 참여하겠습니다. 도와주셔 감사합니다.
