### ISSUE TITLE
HTML : 부분적으로 링크가 걸리지 않습니다.

### ISSUE THREAD

**Issue by dkssud852** [codingeverybody/codingyahac#84]
수업듣고 아톰 이용해서 만들어보고 있었는데요.
1~3.html 링크거는 부분에서 그대로 시도 했는데 어디선가 뭐가 잘못되었는지 
링크가 걸리지 않습니다.

# 증상
```html
  <li><a herf="1.html">html</a></li>
  <li><a herf="2.html">css</a></li>
  <li><a herf="3.html">javascript</a></li>
```

# 실행환경
윈도우 10 + 마이크로소프트 엣지

![default](https://user-images.githubusercontent.com/35251531/34708079-53e92bd2-f554-11e7-88ef-0486c5de3134.jpg)

**Comment by MinGeun** [comment]
a 태그 속성 값이 href가 아니고 herf로 되어있네요

**Comment by dkssud852** [comment]
헙;; 제 눈이 이상했나봐요 ㅠ 감사합니다~!
