### ISSUE TITLE
아톰 <strong> 웹 적용시 오류

### ISSUE THREAD

**Issue by park-moen** [codingeverybody/codingyahac#847]
![KakaoTalk_20191105_233608331](https://user-images.githubusercontent.com/57402711/68217035-43d45400-0025-11ea-8314-6b9b2a00658d.jpg)
이번에 아톰으로 htlm 독학중인데 Hypertext Markup Language (HTML) is the standard markup language for (<)strong(>)creating web pages(<)/strong(>) and web applications. 이렇게 아톰에 작성하고 저장후의 크롬으로 폴더를 열면 굵은 글씨로 creating web pages가 적히지 않고 (<)strong(>)creating web pages(<)/strong(>) 이렇게 프로그램에 작성한 모습이랑 똑같이 적혀 있네요... 밑에 htlm으로 설정했지만 그대로 입니다.
부등호<에 ()로 굵은 글씨체를 막은 겁니다. ()모양은 무시하셔도 됩니다.

# 해결하고자 하는 문제
 아톰 편집기에 (<)strong(>) creating web pages</strong(>) 라고 적었는데 크롬창에 글자의 변화는 없이 <strong> creating web pages</strong> 이렇게 뜨는 이유는 뭘까요? 참고로 전 윈도10 유저입니다.

# 코드 혹은 오류
Hypertext Markup Language (HTML) is the 
standard markup language for (<)strong(>)creating 
web pages(<)/strong(>) and web applications.

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도10입니다.  언어는 htlm입니다. 라이브러리는 잘모르겠습니다.

# 시도해본 방법
구글링, 유튜브

**Comment by progh2** [comment]
확장자를 `htlm` 에서 `html`로 수정해보세요~ 
Hyper Text Markup Language라는 뜻이라서 html 입니다.
브라우져가 확장자가 `htm` 또는 `html` 이 아니면 텍스트 문서로 인식해서 내용 그대로 보여줄꺼에요~
