### ISSUE TITLE
이고잉님이 강의진도가이드로 사용하시는 '서말'에 사용된 cytoscape를 제 사이트에 적용해보고 싶습니다.

### ISSUE THREAD

**Issue by tajava2006** [codingeverybody/codingyahac#848]
# 해결하고자 하는 문제
현재 생활코딩에서 학습한 Node.js, Express 등을 사용하여 개인적인 사이트를 만들어서 잘 활용 중입니다. 그 와중에 서말 서비스가 참 좋아보여서 그걸 활용한 웹 앱을 개발해보려고 하는데요, 시작부터 막혔습니다.

cytoscape.js 에서 getting-started 를 무작정 따라해보고 있는데, 샘플 그래프가 도무지 표출이 되지를 않습니다. 일단 바로 제 사이트에 적용을 하진 않았구요, Express의 가장 기본적인 샘플에서부터 하려고 하는데...

코드 주소는 여기 있습니다

https://github.com/tajava2006/owdb

보시다시피 더이상 간단할 수도 없을 정도인데 왜 표출이 안되는 것일까요?

안되는 영어로 cytoscape측의 문서를 읽어보면

If you are running Cytoscape.js in Node.js or otherwise running it headlessly, you will not specify the container option. In implicitly headless environments like Node.js, an instance is automatically headless. To explicitly run a headless instance (e.g. in the browser) you can specify options.headless as true.

Very commonly used options
container : A HTML DOM element in which the graph should be rendered. This is unspecified if Cytoscape.js is run headlessly. The container is expected to be an empty div; the visualisation owns the div.

이 부분이 뭔가 관련이 있는 설명인 거 같은데요, node.js 처럼 headless한 환경에서 돌리면 div가 비어져 있을 수 있다..

뭔가 서버 사이드에서 렌더링 해서 보내줄려면 Cytosnap.js 라는 것을 이용해보라는 말인 거 같은데 기초지식이 없다 보니 정확히 무슨 말인지 모르겠습니다.

제 프로젝트 폴더에서 yarn add cytosnap 로 저 모듈을 설치하고 그쪽 문서에 있는대로 code.js를 수정해 봐도 그래프가 나오진 않구요.

무엇이 문제일까요? 답답합니다..

# 코드 혹은 오류
```
main.js

var express = require('express');
var app = express();



app.use("/", express.static(__dirname + '/data'));

app.get('/', function (req, res) {
  
  res.send(`<!doctype html>
  <html>
  <head>
    <title>OWDB</title>
    <meta charset="utf-8"> 
    <link rel="stylesheet" type="text/css" href="/style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.10.2/cytoscape.esm.js"></script>   
  </head>
  <body>
    <h1>asdfzxc</h1>
    <div id="cy"></div>
    <script type="text/javascript" src="/code.js"></script>
  </body>
  </html>`);
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});







code.js

var cytoscape = require('cytoscape');


var cy = cytoscape({

  container: document.getElementById('cy'),

  elements: [ // flat array of nodes and edges
    { // node n1
      group: 'nodes', // 'nodes' for a node, 'edges' for an edge
      // NB the group field can be automatically inferred for you but specifying it
      // gives you nice debug messages if you mis-init elements


      data: { // element data (put json serialisable dev data here)
        id: 'n1', // mandatory (string) id for each element, assigned automatically on undefined
        parent: 'nparent', // indicates the compound node parent id; not defined => no parent
        // (`parent` can be effectively changed by `eles.move()`)
      },

      // scratchpad data (usually temp or nonserialisable data)
      scratch: {
        _foo: 'bar' // app fields prefixed by underscore; extension fields unprefixed
      },

      position: { // the model position of the node (optional on init, mandatory after)
        x: 100,
        y: 100
      },

      selected: false, // whether the element is selected (default false)

      selectable: true, // whether the selection state is mutable (default true)

      locked: false, // when locked a node's position is immutable (default false)

      grabbable: true, // whether the node can be grabbed and moved by the user

      pannable: false, // whether dragging the node causes panning instead of grabbing

      classes: ['foo', 'bar'] // an array (or a space separated string) of class names that the element has
    },

    { // node n2
      data: { id: 'n2' },
      renderedPosition: { x: 200, y: 200 } // can alternatively specify position in rendered on-screen pixels
    },

    { // node n3
      data: { id: 'n3', parent: 'nparent' },
      position: { x: 123, y: 234 }
    },

    { // node nparent
      data: { id: 'nparent' }
    },

    { // edge e1
      data: {
        id: 'e1',
        // inferred as an edge because `source` and `target` are specified:
        source: 'n1', // the source node id (edge comes from this node)
        target: 'n2'  // the target node id (edge goes to this node)
        // (`source` and `target` can be effectively changed by `eles.move()`)
      },

      pannable: true // whether dragging on the edge causes panning
    }
  ],

  layout: {
    name: 'preset'
  },

  // so we can see the ids
  style: [
    {
      selector: 'node',
      style: {
        'label': 'data(id)'
      }
    }
  ]

  

});
```

# 환경
windows10 64 bit
node v10.15.3

# 시도해본 방법

**Comment by egoing** [comment]
nodejs 코드 보다는 최종적으로 만들어지는 html 페이지를 공유해주시면 좋을 것 같습니다. 또 디버거를 통해서 나타나는 오류 메시지가 있다면 그것을 첨부해도 좋을 것 같습니다.

**Comment by tajava2006** [comment]
안녕하세요. 이고잉님. 평소 많은 걸 배우고 있던 분께 직접 답변을 받으니 정말 기쁩니다. 크게 도움 받고 있습니다. 최종적으로 만들어진 웹페이지는

http://125.131.85.196:3000/

여기로 접속하시면 볼 수 있습니다. 저번에 배웠던 aws를 이용해서 공유해봅니다.

**Comment by tajava2006** [comment]
안녕하세요. 이고잉님. 평소 많은 걸 배우고 있던 분께 직접 답변을 받으니 정말 기쁩니다. 크게 도움 받고 있습니다. 최종적으로 만들어진 웹페이지는

http://13.125.245.122/

으로 접속하시면 볼 수 있습니다. 생활코딩에서 배웠던 aws ec2 수업을 되살려 가면서 웹서버 만들었습니다. 네트워크 규칙 때문에 한참 헤맸네요

**Comment by egoing** [comment]
아래 주소의 코드를 페이지에 삽입하고 한번 해보시겠어요? 
https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.9.4/cytoscape.min.js

:)

**Comment by tajava2006** [comment]
스크립트 태그를 해당 링크로 바꾸고 code.js에서 첫 줄을 지우고 나니 해결됐습니다 감사합니다!
