### ISSUE TITLE
[질문] Atom에서 줄 바꾸기가 안됩니다.

### ISSUE THREAD

**Issue by jmy9671** [codingeverybody/codingyahac#85]
Atom으로 코딩을 할 때 다음 줄로 넘어가서 코딩을 하고 싶은데 Enter키를 누르거나 커서로 다음 줄을 클릭해보아도 다음줄이 생성되지가 않습니다. 
그래서 한줄을 거의 꽉 채워 쓰다가 어느순간에 갑자기 다음줄을 쓸수있게 열리는데 이게 좀 불편하네요 ㅠ
어느 곳에서는 Enter+Shift나 Enter+Ctrl을 누르면 다음줄로 넘어가 쓸수있다고 하는데 저는 이런 단축기도 먹히지 않습니다. 어떻게 해야 다음줄로 편하게 넘어갈수있나요?
감사합니다.

**Comment by blackdew** [comment]
Atom이 정상적으로 설치가 이루어지지 못해서 버그가 발생한 상황이거나, 아톰의 문제가 아니라 다른 곳에서 발생한 버그가 아톰 사용에서 나타나고 있는 것일 수도 있습니다. 

아톰을 재설치 해도 같은 현상이 있고, 해결 방안이 잘 보이지 않는다면 다른 에디터를 사용하시길 권장드립니다.
