### ISSUE TITLE
html과 css로 웹사이트를 만들었는데 이미지 하나가 제대로 뜨지 않아요.-

### ISSUE THREAD

**Issue by paran019** [codingeverybody/codingyahac#851]
# 해결하고자 하는 문제
html 수업과 css 수업을 들으면서 웹사이트를 만들어서 깃허브에 올렸는데요.
c드라이브로 시작하는 주소로 확인했을 땐 이미지가 잘 뜨는데,
깃 허브 서버를 이용한 웹사이트에서는 이미지 한 개가 아이콘 모양으로 뜹니다.
웹페이지에 이미지를 2개 넣었는데 하나는 잘 뜨고 하나는 안 뜨고있어요.

정상적으로 이미지가 뜨는 페이지
https://paran019.github.io/paran_coding_web/1_html.html
이미지가 뜨지 않는 페이지
https://paran019.github.io/paran_coding_web/2_css.html

c드라이브에서는 잘 뜨는 것을 캡쳐했는데 사진을 어떻게 올리는지 모르겠네요ㅠㅠ

# 코드 혹은 오류
`<br><img src="개발자도구_요소.png" width="600"> <br>`

# 환경
윈도우7, 한글. 라이브러리버전은 잘 모르겠어요, 죄송해요ㅠㅠ

#문제 해결하려고 한 노력
https://github.com/codingeverybody/codingyahac/issues/79
답변을 참고했습니다.

파일은 해당 폴더에도 존재하고, 깃허브 폴더?에도 존재하구요.
이미지 파일명에도 오타가 없고, 그래서 c드라이브 주소에서는 잘 뜹니다.
이미지 파일 확장자명은 속성에서 확인했는데 png가 맞아요ㅠㅠ
캡쳐 한 것이기 때문에 다운받은 이미지가 아니에요 8ㅁ8

**Comment by smartbos** [comment]
파일명을 영문으로 한 번 바꿔보세요.
시스템에 따라 한글을 잘 인식하지 못하는  경우도 있어서요.

**Comment by progh2** [comment]
대소문자를 가립니다. 
개발자도구_요소.`png`  를 개발자도구_요소.`PNG` 로 변경해주세요~ 

[개발자도구_요소.PNG](https://paran019.github.io/paran_coding_web/%EA%B0%9C%EB%B0%9C%EC%9E%90%EB%8F%84%EA%B5%AC_%EC%9A%94%EC%86%8C.PNG) 입니다.

![개발자도구_요소.PNG](https://paran019.github.io/paran_coding_web/%EA%B0%9C%EB%B0%9C%EC%9E%90%EB%8F%84%EA%B5%AC_%EC%9A%94%EC%86%8C.PNG)
