### ISSUE TITLE
수강신청을 했는데요

### ISSUE THREAD

**Issue by whdmsgur** [codingeverybody/codingyahac#855]
수강신청때 등록한 이메일 계정이 휴면 계정이어서 진행증을 이메일로 못 받았습니다.

다시 받을수 있을까요?(여기에 이런거 써도 괜찮겠죠?)

이메일 주소는 speedstacks11@naver.com

**Comment by progh2** [comment]
그냥 한번 더 신청하셔도 괜찮을 것 같습니다. 👍

**Comment by egoing** [comment]
@progh2 님이 말씀하신 것처럼 한번 더 신청하시면 다시 보내드린답니다 :)
