### ISSUE TITLE
코딩진도 완료후 프로젝트까지 완료해야 완료증을 주시는 건가요?

### ISSUE THREAD

**Issue by shinnew99** [codingeverybody/codingyahac#857]
# 해결하고자 하는 문제
안녕하세요. 참가 신청할때 코딩 공부로 신청해서 막힘없이 방금 막 수강을 다 마쳤습니다. 혹시 프로젝트까지 참여해서 제가 스스로 계획한 프로젝트까지 다 완료해야 완료증을 주시는 건가요..??

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by egoing** [comment]
아니요~ 
완주하시면 신청하실 수 있습니다. 
졸업식 전에 이메일로 수료증을 신청하는 방법을 보내드립니다. 
그 때 신청하시면 됩니다 :) 

완주 축하드려요!
