### ISSUE TITLE
안드로이드) 하루에 한 번만 실행시키는 법

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#859]
# 해결하고자 하는 문제
안녕하세요? 
앱에 로그인을 하면 MainActivity 에서 앱에 필요한 유저 정보들을 firebase 에서 불러오는 코드를 만들었습니다.
이 정보들은 출석부와 같이 하루에 한 번만 불러오면 되는 것들인데 
매번 MainActivity를 불러올 때마다 firebase에 접속을 하면 시간이나 비용이 낭비될 것 같습니다.
하루에 한 번만 실행시키는 코드를 구현하는 방법이 궁금합니다.

# 환경
안드로이드

**Comment by studroid** [comment]
안드로이드에서는 [SharedPreferences](https://developer.android.com/reference/kotlin/android/content/SharedPreferences.html)라는 인터페이스를 통해서 앱에서 사용할 데이터를 저장하거나 불러올 수 있습니다.

또, 자바와 코틀린 모두 시스템의 시간값을 가져올 수 있는 함수들이 다양하게 있지요. 예를 들면 자바에서는 `System.currentTimeMillis()`, 코틀린에서는 `getTimeMillis()`, 그 외에도 Date 관련 클래스를 써서 시간, 날짜값 등을 가져올 수 있습니다.

이 둘을 조합해서, 처음 앱을 켜면 SharedPreferences에 실행한 시간값을 저장한 후, 이후 실행했을 때 저장되어 있는 값을 비교해서 하루가 지났으면 Firebase에서 데이터를 불러와 갱신하는 코드를 만드시면 될 듯합니다.

자바를 사용하는 안드로이드 개발 환경에서의 예시는 아래 링크를 보시면 나와있습니다 :)
https://stackoverflow.com/questions/12343014/how-to-save-and-retrieve-date-in-sharedpreferences

**Comment by kammaii** [comment]
감사합니다! SharedPreferences에 대해 몰랐는데 아주 유용한 기능이네요 :)
