### ISSUE TITLE
(404 에러)github 질문

### ISSUE THREAD

**Issue by PREST7** [codingeverybody/codingyahac#86]
수업진행중 하시던데로 가입, 업로드, 셋팅 github page에서 master branch 후 싸이트 클릭 했더니 404 에러로 나오고 있습니다. 그래서 index.html을 마지막에 넣었더니 역시나 같은 현상입니다. 왜 그런건가요?

**Comment by egoing** [comment]
주소 알려주셔요~

**Comment by PREST7** [comment]
PREST7/WEB1 입니다~
좋은 강의 항상 감사드립니다-----Original Message-----

**Comment by azaraks2** [comment]
url은 대소문자를 구분합니다.

**Comment by dongheegy** [comment]
INDEX.html 이라는 파일 이름을 index.html 이라고 소문자로 바꾸어 보세요.
![image](https://user-images.githubusercontent.com/13765815/34730354-7c5cfc6c-f5a2-11e7-991e-56300178cd53.png)

**Comment by PREST7** [comment]
네~감사합니다. 알려주신데로 INDEX.HTML를 소문자로 고치니까 홈으로 바로 연결되었습니다. 하지만 연결된 후 목록을 클릭하면 404 에러 메세지가 나타납니다. 그래서 주소창을 보니까 1.HTML으로 나오네요. 보시면 아시겠지만 저는 1.html소문자로 입력되어 있는데 위에 처럼 대문자로 표시되는데 어떻게 하면 되나요?

**Comment by azaraks2** [comment]
@PREST7 html 소스에는 그대로 대문자인데요?

**Comment by PREST7** [comment]
지금 말씀하신 html 소스가 그대로 대문자라는 것을 이해를 잘 못하겠습니다. 제가 1.html, 2.html, 3.html로 업로드가 되어 있는데 어떤 부분이 대문자로 표시 되어 있는 건가요?

**Comment by azaraks2** [comment]
@PREST7 https://github.com/PREST7/web1/blob/master/index.html#L15-L17

**Comment by PREST7** [comment]
네~감사합니다. 파일명만 대문자에서 소문자로 바꾸면 되는 줄 알았는데 소스코드에도 대문자를 쓰면 안되는 군요..알려주신 방법으로 해보니까 정상적으로 작동합니다. 너무 감사합니다.

**Comment by zzaerim** [comment]
index.html README.md 둘 다 있는데 404 에러 뜨면 어떻게 하나요?ㅠ
