### ISSUE TITLE
안드로이드 int[] 에 값이 추가되면 메소드를 실행하는 법

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#862]
# 해결하고자 하는 문제

안녕하세요?

앱을 시작하면 MainActivity가 실행되고 MainLesson 이라는 프레그먼트도 실행됩니다.
이 때 MainActivity는 firebase에 접속하여 사용자의 정보들을 가져오고
그 중에 lessonComplete라는 array를 MainLesson의 뷰를 만들 때 사용하려고 합니다.

그런데 문제는 MainActivity가 firebase에 접속하여 사용자의 정보들을 받기도 전에 
MainLesson의 뷰만들기가 실행되어 NullPointerException이 발생합니다.

MainLesson에서 직접 firebase에 접속하여 필요한 정보를 가져와서 뷰를 그리기 시작하면 될 것 같지만 불필요하게 firebase에 두 번 접속해야 해서 좋은 방법은 아닌 것 같습니다.
다른 방법이 있을까요?

# 코드 혹은 오류
```
- MainActivity 
    public static List<Integer> lessonComplete;

- MainLesson
    ArrayList<LessonItem> list = new ArrayList<>();
        if(MainActivity.lessonComplete != null) {
            for(int i=0; i<MainActivity.lessonComplete.size(); i++) {
                list.get(MainActivity.lessonComplete.get(i)).setIsCompleted(true);
            }
        }

```

**Comment by MoonSupport** [comment]
asynchronous와 같은 것이 키워드일꺼 같은데 찾아보면 어떨까요?
안드로이드 개발을 해본적이 없어서 잘 모르지만
android Asynctask와 같은 기술이 도움이 되시지 않을까요?

**Comment by progh2** [comment]
파이어베이스로 구현했다면 `onDataChange(DataSnapshot dataSnapshot)` 메소드를 만들어서 값을 가져와야합니다.(값을 가져왔다고 하니 이미 값을 가져와서 lessonComplete 배열에 넣는 코드를 넣어줬겠죠?) 또한 값이 변경되면 자동으로 화면이 다시 그려져야 할테니 위 메소드 안에서 화면을 (다시) 그려주는 코드가 포함되어야 값이 변경되었을 때 화면 뷰가 자동으로 그려집니다.
화면에 그려주는 코드를 파베에서 값 가져오는 코드 다음에 넣어주세요~ (함수로 빼서 호출해주면 더 좋겠죠)

**Comment by progh2** [comment]
아래 링크에 보시면 글 하단에 목록 어댑터 갱신하는 내용도 있으니 참고해보시면 좋을꺼에요~

https://m.blog.naver.com/PostView.nhn?blogId=nife0719&logNo=221049879862&proxyReferer=https%3A%2F%2Fwww.google.com%2F

**Comment by kammaii** [comment]
답변 감사합니다! :)
