### ISSUE TITLE
Visual Studio Code ESLint 질문입니다.

### ISSUE THREAD

**Issue by HoJin9622** [codingeverybody/codingyahac#865]
# 해결하고자 하는 문제
Visual Studio Code에서 ESLint를 사용하려고 합니다.
https://youtu.be/SydnKbGc7W8
위 영상을 보고 ESLint 를 세팅하였습니다.
그런데 위 영상의 json 파일의 셋팅은 새로운 프로젝트를 생성하였을 때는 적용이 안되는 것 같습니다.
새로운 프로젝트를 생성할 때 마다 밑에 작성한 코드를 터미널에서 프로젝트를 생성할 때 마다 실행해줘야 하는건가요?

# 코드 혹은 오류
```
npm i -D eslint prettier eslint-plugin-prettier eslint-config-prettier eslint-plugin-node eslint-config-node
npx install-peerdeps --dev eslint-config-airbnb
npm i -g eslint
eslint --init
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Window10, Visual Studio Code

# 시도해본 방법
구글링

**Comment by MoonSupport** [comment]
프로젝트마다 실행하는 것을 권장합니다.

물론 프로젝트마다 실행하지 않아도 됩니다. 

명령어를 살펴보면
``` 
npm i -D eslint prettier eslint-plugin-prettier eslint-config-prettier eslint-plugin-node eslint-config-node 
npx install-peerdeps --dev eslint-config-airbnb
```
해당 코드는 프로젝트 내부에 프로그램들을 설치하는 과정입니다.
그에 반해
``` npm i -g eslint ```
해당 코드는 ``` -g ``` 옵션으로 인해 global하게 eslint라는 프로그램이 설치 되기 때문에, 운영체제에서 경로만 잘 지정되어 있다면 어떤 프로젝트도 접근 가능하게 됩니다.

그렇기 때문에 -g 옵션이 없는 위 코드들에게 -g 옵션을 주고 그 경로를 모든 프로젝트가 인식하게 한다면 이론상 가능할 것 같긴 합니다.
```
eslint --init

```
로 생성되는 린트파일 역시 상위 폴더들을 살펴봅니다.
그렇기 때문에, 프로젝트보다 상위 폴더에 위치하여 있으면 정상 작동할 것입니다.

다만, 어떤 프로젝트의 세팅을 global하게 관리하는 것은 훌륭한 선배 개발자분들의 철학과 조금 어긋난 거 같기도 합니다.
훌륭한 개발자분들은 항상 변수나 파일들을 가능한 좁은 범위에서만 활동하게 고민하시더라구요.

만약 eslint와 같은 글로벌한 세팅들이 수십개가 늘어났을 때,
어느 순간부터 프로젝트를 생성할때마다 에러가 발생한다면 어떤 세팅들 때문에 문제가 발생하는지 찾기 힘들어 지게 됩니다.
특히 세팅 각각의 문제가 아니라, 여러 세팅이 얽히고 섥혀 문제를 발생한다면 더욱 문제점을 찾기 어려워 지구요.

그렇기 때문에 항상 global 하기 보단 local하게 만들어 가시면 좋을 것 같습니다!!
