### ISSUE TITLE
github페이지에서  master branch를 설정한 이후에 얻은 링크를 들어가봤는데 404에러가뜹니다

### ISSUE THREAD

**Issue by insomnia310** [codingeverybody/codingyahac#866]
제가 적은 코드의 오류는 없을것같지만 혹시나 잘못적었을수도 있으니
제github페이지 링크를 입력하겠습니다.
https://github.com/insomnia310/web7

계속 404에러가 뜨는링크주소입니다
https://insomnia310.github.io/web7/
뒤에 index.html을 붙여도 에러가 사라지지않습니다.

이 문제때문에 이틀간을 해매고 있습니다.
도와주세요

**Comment by insomnia310** [comment]
> 제가 적은 코드의 오류는 없을것같지만 혹시나 잘못적었을수도 있으니
> 제github페이지 링크를 입력하겠습니다.
> https://github.com/insomnia310/web7
> 
> 404에러가 뜨던 링크가 이젠 web7라는 단어만 뜹니다.
> https://insomnia310.github.io/web7/
> 뒤에 index.html을  쳐도 그대로입니다.
> 
> 이 문제때문에 이틀간을 해매고 있습니다.
> 도와주세요

**Comment by MoonSupport** [comment]
문제가 해결 되신 것으로 보입니다. 맞나요?

**Comment by insomnia310** [comment]
네, 해결 되었습니다.
