### ISSUE TITLE
안녕하세요! 코딩야학!! 학습 방법 및 시간이 오래 걸리는 공부를 지치지 않고 하는 방법이 있을까요?

### ISSUE THREAD

**Issue by MoonSupport** [codingeverybody/codingyahac#869]
안녕하세요! 코딩야학!! 학습 방법 및 시간이 오래 걸리는 공부를 지치지 않고 하는 방법이 있을까요?

일단 저는 현재 첫 직장생활을 시작한지 3개월이 조금 넘은 신입입니다 :)
신입이기도 하고, 저에겐 정말 과분한 회사에 입사하다보니 업무를 하면서 정말 배울 것이 너무 많습니다.

새로운 기술은 물론이고, 때론 변수명 하나 짓는데도 하루가 다 갈때도 있습니다.

저는 업무를 하는 것이 저에게 가장 필요한 공부라고 생각해서, 업무 시간 외에도 일하는 데 시간을 쏟아 붓고 있습니다.

그런데 회사 직장분들께서는, 업무 시간 외에는 개인 공부를 하라고 항상 권하십니다.

그래서 지금은 low level의 언어를 공부하거나  개인 프로젝트로써 서버, OS, 컴파일러와 같은 기술의 기저들을 Tiny하게 직접 코드로 짜보고, 깃헙에서 훌륭한 개발자분들이 작성하신 코드들을 읽어보고 있습니다.

이때, 문제가 생겼습니다.

업무를 하면서 배우는 것은 금방 써먹을수 있고,  학습을 하는 대로 학습에 대한 보상이 바로 주어지는 느낌이라면,

개인 공부는 정말 내가 알고 싶은 것이고, 언젠가 개발자로써 성장하기 위해 꼭 필요한 것이지만 학습시간이 오래 걸리기 때문에 학습에 대한 보상을 받는데 오래 걸리고, 그로 인해 초조함을 느끼는 것 같습니다.

그 때문에, 저도 모르게 저 스스로한 약속을 지키지 못하고 전자에 시간 투자를 하게 됩니다.
저는 이러한 것이 
1. 후자를 공부하면서 느끼는 초조함
2. 내가 생각하는 오늘 할 업무의 마무리를 마치지 못하면서, 개인 시간에 투자.

로 인해 발생한다고 생각합니다.

이때, 질문을 요약하자면
1. 시간이 오래걸리는 공부를 할 때, 초조하지 않고 지속적으로 공부할 수 있는 방법이 있을까요?
( 생활코딩 영상에도 WEB1 과 같은 짧은 시리즈가 있는 반면, JAVA나 JS같은 긴 시리즈가 있는데 비슷한 경험을 가지신 적 없으셨을까요?

2. 업무와 개인시간을 분리할 수 있는 방법이나 요령이 있을까요?

3. 굳이 제가 설정한 학습 이외에 더 좋은 방법이나 의견이 있을까요? 

-- ---
마지막으로 생활코딩에 감사인사를 드리고 싶어요.
대학교 4학년 코딩야학 4기를 통해서 처음 생활코딩을 접하게 되었는지 1년이 훌쩍넘었네요 
#258  ( 역사적인 첫 이슈 )
이 때까지만 해도 제가 개발자가 될 거라고 생각도 못했고 정적인 웹페이지 하나도 도저히 혼자 힘으로 완성하지 못했었네요. ㅎㅎ 
지금은 패기넘치게 뭐든 만들 수 있(을것만 같)은 신입 개발자로써, 너무 좋은 회사에서 좋은 분들과 재미난 일을 하고 있습니다 :)

제 계획에는 없던 이런 재미난 삶에 첫 발을 내딛게 해주셔서 감사합니다 :)

**Comment by studroid** [comment]
와우, 저도 코딩야학 4기부터 조력자 활동을 시작했는데, 제 시작과 함께 하신 분이 실제로 개발자가 되어 일하고 계시다니 뿌듯함이 느껴지기도 하고, 코딩야학은 @MoonSupport 님 같은 정말 대단하신 분들이 함께 한다는 생각이 드네요! 과연 저라면 꾸준히 해낼 수 있었을지 모르겠습니다.

찾아보니 4기에서 [제가 함께 한 이슈](https://github.com/codingeverybody/codingyahac/issues/819)도 하나 있었는데, 도움이 되셨었을지 모르겠네요 ㅎㅎㅎ

우선 개발자의 길을 성공적으로 걷고 계신 @MoonSupport 님, 정말 축하드립니다!! 🎉🎉🎉

---

글을 쓰다 보니 길어져서, 의견만 먼저 요약하면 아래와 같습니다 :)

1. 시간이 오래걸리는 공부를 할 때, 초조하지 않고 지속적으로 공부할 수 있는 방법이 있을까요?
    * 제 경험에선 초조함은 막연함에서 비롯되곤 했던 듯합니다. 비교적 단기간에 보상을 받을 수 있는 대회나 행사 참여, 같은 분야를 공부하는 다른 사람들과의 교류 등을 통해 막연한 것들을 구체적인 것들로 바꿔나가면 어떨까요?

2. 업무와 개인시간을 분리할 수 있는 방법이나 요령이 있을까요?
    * 업무에 관한 것을 배우면 금방 써먹을 수 있고, 보상이 바로 보이신다면 개인 시간에 굳이 다른 분야의 공부를 할 필요는 없지 않을까 싶습니다.
    * 업무에 관한 것에서 정체가 느껴질 때, 새로운 분야에 대한 호기심과 갈망이 생기면 그때 가장 효과적인 학습을 할 수 있을 듯합니다.

3. 굳이 제가 설정한 학습 이외에 더 좋은 방법이나 의견이 있을까요?
    * 새로운 분야의 학습에 집중하고 싶으시다면, 스스로의 의지를 강제하는 뭔가를 생활에 하나 집어넣는 것도 좋을 듯합니다.
    * 돈을 내고 온오프라인 강의를 듣거나, 스터디를 만들어 진행하거나, 같이 공부할 친구와 서로 퀴즈를 내고 풀어보는 방식 등을 통해 내 의지를 내가 제어할 수 없게끔 하는 거죠 ㅎㅎㅎ

---

요약하신 질문에 대한 의견을 드리기 전에, 먼저 제가 이전에 다른 글에 작성한 의견들을 참고로 봐주시면 좋을 듯합니다.

1. https://github.com/codingeverybody/codingyahac/issues/663#issuecomment-518277515 - (1)
2. https://github.com/codingeverybody/codingyahac/issues/799#issuecomment-521082134 - (2)

위 두 코멘트를 참고로 해서 요약 질문에 의견을 드려보자면, 

## 1. 시간이 오래걸리는 공부를 할 때, 초조하지 않고 지속적으로 공부할 수 있는 방법이 있을까요? ( 생활코딩 영상에도 WEB1 과 같은 짧은 시리즈가 있는 반면, JAVA나 JS같은 긴 시리즈가 있는데 비슷한 경험을 가지신 적 없으셨을까요?

뭔가를 배우는 도중에 초조함을 느낀다는 것은, 제 경험상에선 대부분 '막연함' 때문이었던 것 같습니다. 말씀하신 것처럼 학습에 대한 보상이 당장 보이지 않는 것도 하나의 '막연함'이고, 또는 '다른 사람들은 아주 빠르게 배우면서 치고 나가는 듯한데 나만 뒤처지는 것은 아닐까?' 하는 막연한 비교, '내가 공부하는 방향이 맞는 방향인가?'하는 방향성에 대한 막연함 등등.. 
공부한 것들이 바로 내게 도움이 되지 않기 때문에 불확실함, 막연함을 느끼고 이로 인해 그저 더 빨리 배워야겠다는 생각이 들어 초조함이 느껴지는 것 아닐까요?

만약 그게 맞다면, 불확실함을 확실함으로 바꾸고, 막연한 것들을 구체적인 것들로 바꾸면 덜 초조해지지 않을까 싶습니다.

제가 초조함을 느낄 때 하는 써보는 방법들을 예로 들어보면,

### 보상이 당장 보이지 않는다 -> 보상이 당장 보이게 하기

* (1)에서 언급한 해커톤 같은 행사에 참여하기
* 내가 배우고 있는 것으로 참여할 수 있는 외부 프로그래밍 대회 등에 참가해보기
* (2)에서 언급한 것처럼 아주 간단한 앱부터 만들어서 광고 등으로 수익화해보기

### 나만 뒤처지는 것 같다 -> 내 수준을 정확하게 파악하기

* (1)에서 언급한 온라인 스터디 플랫폼, 또는 오프라인 스터디 참여 등을 통해 다른 사람들이 배우는 내용과 내가 알고 있는 내용 비교해보기
* 내가 공부하고 있는 것에 관련 있는 공식 세미나 등에 참여해서 최근에 생겨나는 정보들 확인하기
* 내가 공부하는 것과 관련 있는 온라인 커뮤니티에 가입하여 활동하기

### 내 공부 방향에 확신이 없다 -> 공부 방향에 확신 먼저 가지기

* 먼저 내가 공부하는 분야가 앞으로도 의미가 있을 분야인지 참고하기 위해, [구글 트렌드](https://trends.google.com/) 등을 통해 트렌드 확인해보기
* <내 수준 정확하게 파악하기>에서처럼 다양한 스터디 참여, 또는 그 스터디에서 쓰이는 과정, 튜토리얼 사이트들을 참고하기

물론 상황에 따라, 또는 개인의 성향에 따라 다른 식의 방법이 더 효과적일 수 있습니다. 위에 언급한 것들은 예시들일 뿐이고, @MoonSupport 님께 더 적절한 방법을 고민해보시면 생각보다 쉽게 답이 나올 수도 있을 듯해요 :) 이미 잘 해나가고 계시니까요!

## 2. 업무와 개인시간을 분리할 수 있는 방법이나 요령이 있을까요?

> 전 이 부분을 개인 시간에 업무 외 분야를 학습해야 하는가에 대한 질문으로 받아들였습니다 :)

현재 업무를 하면서 배우시는 것들이 금방 써먹을 수 있고, 학습에 대한 보상이 바로 주어지는 느낌이 드신다면 개인 시간에도 현재 업무에 도움이 되는 것들을 위주로 공부하시는 게 가장 좋은 방법이 아닐까 싶어요! ㅎㅎ

개인 공부를 굳이 업무와 관련 없는 것들만으로 할 필요가 없고, 개인 공부가 업무에 많은 도움이 된다면 그야말로 금상첨화 아닐까요..? 업무와 관련 없는 개인 공부는, 내 개인 공부만으로는 업무에 도움이 거의 되지 않는다고 느껴질 때, 새로운 분야에 대한 호기심과 갈망이 생길 때 하는 게 가장 효과적일 듯합니다 :)

보통 `개인 시간에 업무에 관한 것에 투자하는 것, 개인 공부에 투자하는 것` 두 개를 분리하는 것보다는 `개인 시간에 뭔가 공부할 것에 투자하는 것` 자체를 어려워하지 않을까요..? 그런 점에서 다시 한번, 역시 @MoonSupport 님 정말 엄청난 분 같습니다.. 💪💪💪

개인 시간에 업무에 관한 것 외에 다른 분야의 공부에 집중하고 싶으시다면, 아래 의견을 참고로 봐주세요 :)

## 3. 굳이 제가 설정한 학습 이외에 더 좋은 방법이나 의견이 있을까요?

제 경우에는 새로운 것을 배울 때, 제 의지를 강제하는 뭔가를 하나 생활에 집어넣었습니다. 예를 들면 돈을 내고 어떤 강의를 듣는다든가, 온라인이든 오프라인이든 매주 모여야 하는 스터디를 만들어 매주 서로 퀴즈를 내고 풀어본다든가, 내가 공부하는 것들을 매주 정리해서 다른 사람들이 보고 학습할 수 있게 한다든가 하는 식으로 말이죠 :)

개인 시간에는 업무에 관한 것 외에 새로운 분야에 집중하고 싶은데 자꾸 업무에 관한 것에 집중이 되신다면, 위와 같이 @MoonSupport 님의 의지를 새로운 분야에 집중하도록 강제하는 뭔가를 하나 만들어보시면 어떨까요?


원글에서 @MoonSupport 님의 의지와 열정이 마구 느껴져서 꽤 긴 글을 쓰게 되었네요 ㅎㅎㅎ
저도 의견을 드리면서 제 스스로 정리를 해보는 기회가 됐습니다. 함께 해주셔서 감사합니다!

**Comment by MoonSupport** [comment]
의견을 찬찬히 읽어보고 또 고민해보면서, 학습에 구체성과 강제성을 만들어보기로 했습니다 :) 

긴 답변 감사합니다 !!
