### ISSUE TITLE
어도비 brackets 태그 자동완성을 끄고 싶습니다

### ISSUE THREAD

**Issue by nok-du** [codingeverybody/codingyahac#870]
# 해결하고자 하는 문제
brackets를 설치해서 사용하려고 하는데 태그가 자동완성되는게 너무 거슬립니다.
예를 들면 < h1 >
이라고 치면 딱 이렇게만 나왔으면 좋겠는데 
< h1> </ h1 >
이렇게까지 자동완성 됩니다. 쓰다보면 편리할 것 같기도 하지만 지금 당장은 끄고 싶은 불편한 기능이고 기존에 적었던 내용에 태그를 추가할 때는 불편한 기능일 것 같습니다. 그래서 이 자동완성을 끄고 싶어요. 끌 수 없는 기능인가요? ㅠㅠ

# 환경
brackets 1.14.1 버전 사용하고 있고
컴퓨터는 윈도우7 사용하고 있습니다.

# 시도해본 방법
디버그 탭-환경설정 파일 열기로 환경설정 들어가서 코드 입력해보았습니다. 
구글에 검색해서
{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "livedav.multibrowser": true,
    "closeBrackets": false,
    "closeTags: false,"
    "showLinenumbers": true
}
이렇게까지 입력해보았는데 여전히 자동완성이 비활성화 되어있습니다.
어떤 코드를 입력해야, 어떤 메뉴를 들어가야 이 자동완성을 끌 수 있을까요??
자동완성이 없는 다른 에디터를 설치해야 될까요??
가볍고 용량 적은 에디터로 쓰고 싶은데..

**Comment by progh2** [comment]
안녕하세요? 아래처럼 수정해보세요. 
요령은 붙여넣기 하지 마시고(저도 붙여넣기 하니 에러가 뜨더군요.( 웹에서 공백문자 등 뭔가 문제되는 문자가 붙여들어갔는지..) 직접 " 쓰고 closeT  까지 쓰시면 아마 closeTags 등 제안이 뜰꺼에요. 거기서 선택하는 식으로 넣어주시면 될 것 같습니다. 그렇게 선택하는 방법을 쓰면서 설정을 넣어주니 에러없이 태그 닫는게 동작 안합니다. 💯 

![image](https://user-images.githubusercontent.com/1307187/71763346-69df7d00-2f1e-11ea-9069-2900a3a27e72.png)

**Comment by nok-du** [comment]
감사합니다! 완전히 잘못된 방법으로 코드를 치고 있었네요.. ㅜㅜ 이게 정확한 코드를 쉼표 하나 빠트리지 않고 쳐줘야 제대로 동작하는 거군요.. 코딩 2일차 덕분에 큰 깨달음 얻고 많이 배우고 갑니다 아직 어렵지만 점점 잘할 수 있도록 열심히 해야겠어요 ㅎㅎ
