### ISSUE TITLE
윈도우10-x64 아톰 플러그인 설치 오류

### ISSUE THREAD

**Issue by LucyLee123** [codingeverybody/codingyahac#872]
#아톰 플러그인 설치오류
emmet / beautify ... 
![why](https://user-images.githubusercontent.com/59510297/71768696-f6f4f700-2f5b-11ea-9afa-41d426493383.png)

# 환경
Windows 10 / i5-9400F / 16RAM / x64

# 시도해본 방법
구글에서 찾아봤으나, 해결방법을 못찾을 걸 보면 오류가 아니라 제가 컴퓨터를 못해서 그런 것 같은데... 맥북에는 그냥 설치됐는데 윈도우에 설치가 안됩니다. Disable 이 상태로 한참시간이 지나도 변하지 않습니다. 
1. uninstall 누르고 다시 해봤으나 동일
2. 아톰 재설치 동일
3. 인터넷이 느려서 오래걸리나 싶어서 ping -t 해봤는데, 정상

**Comment by o2-basta** [comment]
아톰을 쓰질않아서 뭐라 말씀은 못드리지만, 깔려있는 다른플러그인과 충돌나는것은 아닌지 모르겠습니다. 
아톰을 설치하고 가장먼저 저 플러그인을 설정해보면 어떨까요?

**Comment by LucyLee123** [comment]
실패했지만... 맥북으로 사용하겠습니다. 맥북이 짱이네요.
