### ISSUE TITLE
안드로이드 메뉴관련 사소한 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#875]
# 해결하고자 하는 문제

안녕하세요?
안드로이드 코딩을 할 때 주로 안드로이드 스튜디오 아래 메뉴 중 'Run'을 보면서 해야 하는데
안드로이드 스튜디오를 업데이트 한 이후로 AVD를 실행시킬 때마다 'Run' 창이 닫혀서
매번 클릭해서 열어줘야 하는 번거로움이 있습니다.
'Run' 창이 항상 열려있게 할 수 있는 방법이 없을까요?

![image](https://user-images.githubusercontent.com/43202563/71775424-64804200-2fb3-11ea-82a1-fe4eb143f2c3.png)

**Comment by studroid** [comment]
우선 Run 창을 여는 단축키가 맥의 경우 CMD + 4, 윈도우의 경우 아마 CTRL + 4일 겁니다 :)
단축키를 통해 여닫기를 하시면 클릭해서 하는 것보다는 훨씬 쉽게 컨트롤하실 수 있을 듯하고,

Run 창의 우측 상단을 보시면 설정 아이콘을 통해 Dock Pinned 모드를 설정하실 수 있습니다.
<img width="1257" alt="스크린샷 2020-01-06 오후 11 23 27" src="https://user-images.githubusercontent.com/4001790/71824004-df447c80-30db-11ea-886b-0743e88f7cd8.png">

제가 상황을 잘 이해를 한 건지 모르겠네요 ^^;
확인해보시고, 다른 상황이시라면 알려주세요!

**Comment by kammaii** [comment]
> 우선 Run 창을 여는 단축키가 맥의 경우 CMD + 4, 윈도우의 경우 아마 CTRL + 4일 겁니다 :)
> 단축키를 통해 여닫기를 하시면 클릭해서 하는 것보다는 훨씬 쉽게 컨트롤하실 수 있을 듯하고,
> 
> Run 창의 우측 상단을 보시면 설정 아이콘을 통해 Dock Pinned 모드를 설정하실 수 있습니다.
> <img alt="스크린샷 2020-01-06 오후 11 23 27" width="1257" src="https://user-images.githubusercontent.com/4001790/71824004-df447c80-30db-11ea-886b-0743e88f7cd8.png">
> 
> 제가 상황을 잘 이해를 한 건지 모르겠네요 ^^;
> 확인해보시고, 다른 상황이시라면 알려주세요!

답변 감사합니다~ 이해하신 부분이 맞기는 한데
일단 CRTL+4 를 눌러도 아무 반응이 없고 'Dock Pinned'는 이미 체크되어 있는 상태입니다. ㅠㅠ

**Comment by studroid** [comment]
아 찾아보니 윈도우에선 ALT + 4 를 하셔야 할 듯하네요!

Run 창이 있을 때 해보세요~ :)

**Comment by kammaii** [comment]
고정시키는 건 안되지만 단축키만으로도 아주 큰 도움이 될 것 같습니다. 감사합니다! :)
