### ISSUE TITLE
맥 언어 전환 단축키 프로그램을 만들고싶습니다. 어떻게하면 맥 현재 인풋언어 정보를 알 수 있을까요?

### ISSUE THREAD

**Issue by leochoo** [codingeverybody/codingyahac#878]
#해결하고자 하는 문제
**어디서 부터 시작해야할까요?**

3개국어 이상을 쓰다보면 ctrl + space 로 언어를 전환하는게 상당히 번거롭습니다.
그래서 밑과 같이 언어인풋과 키보드 레이아웃을 같이 바꿔주는 프로그램을 만들고 싶습니다.
ctrl + 1 영어
ctrl + 2 일본어 
ctrl + 3 한국어
ctrl + 4 중국어

기존 솔루션을 사용한 결과, 100% 작동하는 솔루션은 없고, Karabiner 같이 세팅을 직접 해야하는 번거로움을 없애고 싶습니다.

그런데 어디서 시작을 해야할 지 모르겠습니다.
어떻게하면 현재 맥OS의 인풋언어 정보를 알아내고, 그걸 어떻게 바꿔야 할 지 도큐멘테이션을 어디를 봐야할지 잘 몰라서 방향을 여쭙고자 합니다.

# 시도해본 방법
Apple Documentation에서
system configuration, IOKit, InputMethod 등을 읽고있습니다만..
광할한 doc 안에서 상당히 헤메고 있습니다.
어디를 봐야지 아시는 분 혹시 계실까요?

# 환경
macOS 10.15.2 Catalina

**Comment by studroid** [comment]
저도 잘 모르는 부분이기는 합니다만, 아마 아래 두 링크를 참고하시면 도움이 되지 않을까 싶습니다.

[Kawa](https://github.com/utatti/kawa/tree/master) 프로젝트의 [InputSourceManager.swift](https://github.com/utatti/kawa/blob/master/kawa/InputSourceManager.swift)

[Text Input Service 관련 스택오버플로 글](https://stackoverflow.com/a/6460526)

꽤 오래 전 정보라, 요즘에도 비슷한 방식으로 적용이 되나 모르겠습니다 ^^;

[공식 문서](https://developer.apple.com/documentation/appkit/nstextinputcontext/1529156-keyboardinputsources)에서는 read-only 로만 되어 있는 듯합니다만, 현재 제 환경이 MacOS Catalina인데 Kawa가 잘 작동하는 것을 보니 아마 될 듯합니다 :)

**Comment by leochoo** [comment]
감사합니다! 참고로 저는 이쪽을 보고 있었는데요, 이걸로 sample code를 짜보고 싶은 데 어떻게 실행을 해야하는 걸까요...? xcode에서 single view app을 만들고 함수를 부르는 데서 부터 막혀서 어떻게 해야할 지 감이 잘 안옵니다 ㅠㅠ
1. 이쪽 링크들은 어덯게 생각하시나요?
[NSTextInputSourceIdentifier](https://developer.apple.com/documentation/appkit/nstextinputsourceidentifier)

2. 혹시 제가 시도한 코드를 올리면 봐주실 수 있으실지요?

**Comment by studroid** [comment]
1. Kawa 프로젝트를 보면, 입력 언어를 바꿀 때 tisInputSource 라는 객체를 통해 언어 변경을 제어하는데, 공식 문서에는 해당 내용이 없어서 저도 NSTextInputSourceIdentifier로 가능할진 모르겠네요 ^^;

2. 도움이 필요하시다면 올려주시면 저도 함께 볼 수는 있습니다만, 저도 해보지 않은 것들이라 도움이 되어드릴 수 있을지는 확신할 수 없습니다 ㅎㅎㅎ;
