### ISSUE TITLE
CSS: CSS 클래스 중 navbar 관련 클래스만 묶어서 관리하기 (재질문)

### ISSUE THREAD

**Issue by SangYunLeee** [codingeverybody/codingyahac#88]
```
			.navbar-default .navbar-brand,
			.navbar-default .navbar-brand:hover,
			.navbar-default .navbar-brand:focus {
			    color: black; font-size: 15px; font-weight: bold;

			}

                        . pa5{
				padding-left: 5%;
			        padding-right: 5%;
			}
```

위의 코드 중에  navbar 쪽 css가 많아 navbar 관련 스타일이 점점 많아져서 navbar관련 스타일들만 따로 편철?하기 위해, 아래와 같이 html에서 그 용도로 쓰는 \<div\> 와 같은 방식으로 관리하고 싶은데 html의 div와 같은 묶음 태그가 css에도 있는지 궁금합니다!

```
                 <div>
			.navbar-default .navbar-brand,
			.navbar-default .navbar-brand:hover,
			.navbar-default .navbar-brand:focus {
			    color: black; font-size: 15px; font-weight: bold;
			}
                  </div>
                        . pa5{
				padding-left: 5%;
			        padding-right: 5%;
			}
```

  **도와주셔서 정말 정말 감사드립니다!!!!!**
  
  이전 글에서 한번 올렸었는데, 이고잉신님께서 더 질문이 있다면 re-open 해달라하셨는데 re-open 기능이 없더라구요 ㅜ 그래서 다시 올리게 되었습니다!!
구글에선 repto 가 닫으면 열수업게 만들었다고 합니다!!
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by SangYunLeee** [comment]
이고잉신님께서 더 질문이 있다면  re-open 해달라하셨는데 re-open 기능이 없더라구요 ㅜ
구글에선 repto 가 닫으면 열수업게 만들었다고 합니다!!
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by leezche** [comment]
sass나 less를 사용하면 좀 더 효율적으로 css코드를 생성할 수 있을것 같습니다. 
https://opentutorials.org/course/277/1748

**Comment by SangYunLeee** [comment]
감사합니다!!

**Comment by leezche** [comment]
넵... 도움이 되셨으면 좋겠습니다. ^^
