### ISSUE TITLE
모바일 웹을 만들기 위해 프로토타입까지는 만들었습니다. 이것을 코딩으로 다시 구현하는건가요?

### ISSUE THREAD

**Issue by lee-insu** [codingeverybody/codingyahac#882]
생활코딩 덕분에 짧은 시간 안에 간단한 웹 페이지 만드는 것 까지 성공했습니다. 감사합니다.

제 목표는 모바일 웹 페이지를 만드는 것인대요. 
아무래도 코딩을 접한 시간이 얼마 되지 않아서 많이 서툽니다 ㅠㅠ

막히는 부분
제가 css로 제가 스케치 한 것을 표현하려 했지만 생각 만큼 표현되지 않고 시간도 오래걸려서
먼저 프로토타입을 만드는 것이 효율적인 것 같아 adobe xd를 통해 프로토타입을 만들었습니다.
여기서 고민되는 것은 xd를 통해 구현 했던 것을 html로 돌아와서 처음부터 코딩을 입력 해야하는 것인가요?? 좀 더 효율적인 방법이 있나 검색해 봤지만 자료가 없길래 질문해봅니다!

**Comment by o2-basta** [comment]
adobe xd가 어떤것인지 몰라서 검색해봤더니, 훌륭한 툴이더군요 ㅎㅎㅎ

원하시는 것들을 쉽게 만드는것에서는 경쟁할 녀석이 없을거 같습니다. 

그냥 웹서버에 올리시면 될거 같아요 ㅎㅎㅎ

굳이 코딩을 추가한다면 기본적인 html에 좀더 많은 기능을 넣거나, 데이터 베이스와 연결하는등의 추가적인 작업이 있을때 하면 될거 같아요. 
그렇지 않다면 그냥 프로토타입작업이 그대로 웹서버에 올라가도 좋을거 같네요 ㅎㅎㅎ

**Comment by lee-insu** [comment]
그렇군요 !! 감사합니다!
