### ISSUE TITLE
mysql utf8 인코딩(한글 깨짐 현상)

### ISSUE THREAD

**Issue by b00db** [codingeverybody/codingyahac#886]
# 해결하고자 하는 문제
회원 정보를 등록하고 회원 목록을 가져오는 프로그램입니다.

# 코드 혹은 오류
```
+--------------------------+---------------------------------------------------------+
| Variable_name            | Value                                                   |
+--------------------------+---------------------------------------------------------+
| character_set_client     | euckr                                                   |
| character_set_connection | euckr                                                   |
| character_set_database   | latin1                                                  |
| character_set_filesystem | binary                                                  |
| character_set_results    | euckr                                                   |
| character_set_server     | latin1                                                  |
| character_set_system     | utf8                                                    |
| character_sets_dir       | C:\Program Files\MySQL\MySQL Server 5.6\share\charsets\ |
| collation_connection     | euckr_korean_ci                                         |
| collation_database       | latin1_swedish_ci                                       |
| collation_server         | latin1_swedish_ci                                       |
| completion_type          | NO_CHAIN                                                |
| concurrent_insert        | AUTO                                                    |
| connect_timeout          | 10                                                      |
| core_file                | OFF                                                     |
+--------------------------+---------------------------------------------------------+
```
<br> my.ini 파일을 수정해보아도, 혹시나해서 기존에 있던 데이터베이스들을 다 지우고 했는데도, database랑 server가 자꾸 latin에서 utf8로 안바뀝니다.

# 시도해본 방법
```
1. request.getParameter("name");을 호출 하기 전에
request.setCharacterEncoding("UTF-8");도 해주었습니다.
2. 톰캣 server.xml에 들어가서 URIEncoding="UTF-8"도 추가해줬습니다.
3. my.ini 파일입니다.(mysql)
[client]
default-character-set = utf8

[mysqld]
init_connect = "SET collation_connection = utf8_general_ci"
init_connect = "SET NAMES utf8"
default-character-set = utf8
character-set-server = utf8
collation-server = utf8_general_ci
# basedir = C:\Program Files\MySQL\MySQL Server 5.6
# datadir = C:\Program Files\MySQL\MySQL Server 5.6

[myspldump]
default-character-set = utf8

[mysql]
default-character-set = utf8
```

한글이 ??? 물음표로 나옵니다.
(회원 등록할 때 한글이름을 가진 회원을 등록하면, 회원 목록에서 한글이름을 가진 회원의 한글이름이 물음표로 깨져보입니다.)

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
Windows10, eclise/servlet프로그래밍(JAVA), MySQL Workbench

**Comment by o2-basta** [comment]
데이터베이스와 톰캣은 utf8인거 같네요. 브라우저가 혹시 euc-kr인 상황이 아닌지 궁금하네요. 
그리고, 보다 확실히 한다면, 데이터베이스에 있는 내용만 확인해보시거나, 톰캣에서 확인할 수 있는 서블릿 혹은 jsp를 utf8으로 보여지게 해서 확인해 보는것을 추천드립니다. 
확인해 볼것이 많으면 하나씩 확인해서 변경되는 요소를 줄여보는게 중요할거 같습니다.

**Comment by b00db** [comment]
> 데이터베이스와 톰캣은 utf8인거 같네요. 브라우저가 혹시 euc-kr인 상황이 아닌지 궁금하네요.
> 그리고, 보다 확실히 한다면, 데이터베이스에 있는 내용만 확인해보시거나, 톰캣에서 확인할 수 있는 서블릿 혹은 jsp를 utf8으로 보여지게 해서 확인해 보는것을 추천드립니다.
> 확인해 볼것이 많으면 하나씩 확인해서 변경되는 요소를 줄여보는게 중요할거 같습니다.

다른 한글은 잘 나오는데, 회원등록에 회원정보를 한글로 작성하고 submit하고나서, 회원정보를 보면 방금 등록한 회원의 한글만 깨져요...! 어떻게 확인해 봐야하나요...? ㅠㅠ

**Comment by b00db** [comment]
> 데이터베이스와 톰캣은 utf8인거 같네요. 브라우저가 혹시 euc-kr인 상황이 아닌지 궁금하네요.
> 그리고, 보다 확실히 한다면, 데이터베이스에 있는 내용만 확인해보시거나, 톰캣에서 확인할 수 있는 서블릿 혹은 jsp를 utf8으로 보여지게 해서 확인해 보는것을 추천드립니다.
> 확인해 볼것이 많으면 하나씩 확인해서 변경되는 요소를 줄여보는게 중요할거 같습니다.

![0](https://user-images.githubusercontent.com/48580026/72001887-b366f980-3289-11ea-83b4-b2fa89b23de9.png)
![1](https://user-images.githubusercontent.com/48580026/72001888-b366f980-3289-11ea-8d7d-91da175ad408.png)

**Comment by mkhong-otu** [comment]
my.ini 파일 수정 후 mysql 서버를 재구동 하셨나요?
my.ini 수정 후 적용을 위해서는 mysql 서버 재구동이 필요합니다.

참고로 올려주신 세팅대로 실행해본 결과

```confg
[mysqld]
init_connect = "SET collation_connection = utf8_general_ci"
init_connect = "SET NAMES utf8"
# default-character-set = utf8 # 이부분에서 오류가 발생합니다. 삭제하세요
character-set-server = utf8
collation-server = utf8_general_ci
# basedir = C:\Program Files\MySQL\MySQL Server 5.6
# datadir = C:\Program Files\MySQL\MySQL Server 5.6
```
mysqld의 default-character-set 부분을 삭제하시면 정상적으로 character_set 들이 변경됩니다.
```
mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```


이미 생성된 데이터베이스는 데이터베이스, 테이블, 데이터 모두 인코딩을 변경해야 하니
데이터베이스를 새로 생성하는게 좋을 것 같습니다.

본 세팅이 적용된 mysql에서 데이터베이스 생성시 기본으로 utf8로 데이터베이스가 생성되지만
그렇지 않은 경우
```sql
CREATE DATABASE db_name default charset utf8;
```

이렇게 생성해 주시면 utf8 인코딩을 사용하는 데이터베이스가 생성됩니다.

**Comment by b00db** [comment]
> my.ini 파일 수정 후 mysql 서버를 재구동 하셨나요?
> my.ini 수정 후 적용을 위해서는 mysql 서버 재구동이 필요합니다.
> 
> 참고로 올려주신 세팅대로 실행해본 결과
> 
> ```
> [mysqld]
> init_connect = "SET collation_connection = utf8_general_ci"
> init_connect = "SET NAMES utf8"
> # default-character-set = utf8 # 이부분에서 오류가 발생합니다. 삭제하세요
> character-set-server = utf8
> collation-server = utf8_general_ci
> # basedir = C:\Program Files\MySQL\MySQL Server 5.6
> # datadir = C:\Program Files\MySQL\MySQL Server 5.6
> ```
> 
> mysqld의 default-character-set 부분을 삭제하시면 정상적으로 character_set 들이 변경됩니다.
> 
> ```
> mysql> show variables like 'char%';
> +--------------------------+----------------------------+
> | Variable_name            | Value                      |
> +--------------------------+----------------------------+
> | character_set_client     | utf8                       |
> | character_set_connection | utf8                       |
> | character_set_database   | utf8                       |
> | character_set_filesystem | binary                     |
> | character_set_results    | utf8                       |
> | character_set_server     | utf8                       |
> | character_set_system     | utf8                       |
> | character_sets_dir       | /usr/share/mysql/charsets/ |
> +--------------------------+----------------------------+
> ```
> 
> 이미 생성된 데이터베이스는 데이터베이스, 테이블, 데이터 모두 인코딩을 변경해야 하니
> 데이터베이스를 새로 생성하는게 좋을 것 같습니다.
> 
> 본 세팅이 적용된 mysql에서 데이터베이스 생성시 기본으로 utf8로 데이터베이스가 생성되지만
> 그렇지 않은 경우
> 
> ```sql
> CREATE DATABASE db_name default charset utf8;
> ```
> 
> 이렇게 생성해 주시면 utf8 인코딩을 사용하는 데이터베이스가 생성됩니다.

자꾸 번거롭게 질문드려서 죄송합니다만,,,

말씀대로 수정하고 재구동을 해봤음에도 불구하고

```
mysql> show variables like 'char%';
+--------------------------+---------------------------------------------------------+
| Variable_name            | Value                                                   |
+--------------------------+---------------------------------------------------------+
| character_set_client     | euckr                                                   |
| character_set_connection | euckr                                                   |
| character_set_database   | latin1                                                  |
| character_set_filesystem | binary                                                  |
| character_set_results    | euckr                                                   |
| character_set_server     | latin1                                                  |
| character_set_system     | utf8                                                    |
| character_sets_dir       | C:\Program Files\MySQL\MySQL Server 5.6\share\charsets\ |
+--------------------------+---------------------------------------------------------+
```
왜 charset이 변경되지 않는 걸까요... ㅠㅠㅠ

**Comment by b00db** [comment]
> init_connect = "SET NAMES utf8"
