### ISSUE TITLE
안드로이드 언어 현지화 관련 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#889]
# 해결하고자 하는 문제

안녕하세요? 
안드로이드 언어 현지화 기능을 적용하려고 합니다.
필요한 내용들은 모두 strings.xml에 넣은 상태이고
안드로이드 스튜디오의 'Open Translations Editor'  를 통해 다양한 나라의 언어의 strings.xml을 만들 수 있다는 것까지 확인했습니다.
이렇게 하면 현지화된 국가에서 접속하는 사용자는 자동으로 해당 언어로 앱을 사용할 수 있는 것이 맞나요?

그리고 저는 앱 안에서 옵션 메뉴를 통해 사용자가 직접 언어를 선택할 수 있는 기능도 넣고 싶습니다.
코드에서 strings를 선택할 수 있게 해야 할 것 같은데 어떻게 해야 하는지 잘 모르겠습니다.

**Comment by o2-basta** [comment]
https://developer.android.com/training/basics/supporting-devices/languages?hl=ko

이런것을 참고하시면 될거 같아요. 그리고, 각각의 언어에 대한 strings.xml을 만드는것이 아니라, 표시될 메세지에 대한 각언어적 표현을 모두 모아서 strings.xml에 담아놓으면, 언어가 바뀔때 해당언어로 바꾸어 표현해주게 됩니다. 당연히 데이터베이스에 있는 내용등은 별도로 번역하지 않는한 다국어 지원을 할 수 없지만, 기본적인 메뉴나 메세지등은 언어적인 장벽을 없앨수 있을거 같아요 ㅎㅎ

**Comment by kammaii** [comment]
감사합니다! :)
