### ISSUE TITLE
자바스크립트 페이지 넘어가게 하는 법...

### ISSUE THREAD

**Issue by G0Dpapa** [codingeverybody/codingyahac#89]
<img width="1280" alt="2018-01-09 6 42 21" src="https://user-images.githubusercontent.com/34954785/34714709-a5143e16-f56d-11e7-8db8-e653160dbe20.png">

제가 하고 싶은건 country가 바뀌면 그 country의 웹페이지로 넘어가게 하고 싶은데(Korea를 선택하면 KR.html로 넘어가가도록....) 도저히 모르겠어서 질문을 올립니다

**Comment by egoing** [comment]
이런 경우라면 jsfiddle.net 이나 codepen.io 와 같은 서비스를 이용해서 질문해주시면 답변자들이 실시간으로 테스트해보면서 도움을 드리기 쉬울 것 같습니다. 답변을 한번 보강해보셔요~

**Comment by ghdalsrldi** [comment]
```javascript
function CountryHandler() {
	alert(); return;
  var x = document.getElementById('country').value;

  // 선택된 country 값이 없다면 이동하지 않는다
  if (!x) {
    return false;
  }

  
  // 선택된 country 페이지로 이동
  window.location.href = x + '.html';

}

```

**Comment by G0Dpapa** [comment]
@ghdalsrldi 
<img width="1280" alt="2018-01-10 8 55 48" src="https://user-images.githubusercontent.com/34954785/34749310-11b1d27e-f5e4-11e7-9126-52e97f5d13ca.png">
이렇게 바꿨는데 잘 동작이 안되네요....
어디가 문제인가요..ㅠ

**Comment by swon223** [comment]
`window.location.herf`가 함수 안으로 들어야할 것 같습니다
변수 x가 함수 내부에 선언되어 있어서 밖에서는 접근이 안 되네요
