### ISSUE TITLE
안드로이드 파이어베이스 저장소의 오디오 재생하기

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#893]
# 해결하고자 하는 문제

안녕하세요?
파이어베이스의 저장소에 저장된 오디오 파일을 안드로이드에서 재생하는 코드를 만들었습니다.
결과적으로 재생은 잘 됩니다.
재생은 잘 되는데 아래의 에러도 함께 출력되어 찝찝한 마음에 질문 드립니다.
```
W/MediaPlayer: Couldn't open https://firebasestorage.googleapis.com/...
    java.io.FileNotFoundException: No content provider: https://firebasestorage.googleapis.com/v0/b/podo-705c6.appspot.com/o/assy%2Fassy_004.mp3?alt=media&token=6ad10f55-f38f-42e5-a6ae-42b2af911782
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1663)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1493)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1410)
        at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1102)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1074)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1002)
        at net.awesomekorean.podo.lesson.lessonHangul.LessonHangulAssembly$2.onSuccess(LessonHangulAssembly.java:185)
        at net.awesomekorean.podo.lesson.lessonHangul.LessonHangulAssembly$2.onSuccess(LessonHangulAssembly.java:180)
```
에러가 가리키고 있는 부분은 아래 코드에서 이 부분입니다.
```
                try {
                    mediaPlayer.setDataSource(context, uri);
                } catch (IOException e) {
```
저장소의 파일을 잘 찾아서 재생까지 잘 하는데 왜 FileNotFoundException 이 발생하는지 모르겠습니다.

# 코드 혹은 오류
```
       // 저장소에서 오디오 재생하기
    public void playAudio(String audioFile) {
        StorageReference storageRef = storage.getReference().child("assy").child(audioFile);
        storageRef.getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
            @Override
            public void onSuccess(Uri uri) {
                MediaPlayer mediaPlayer = new MediaPlayer();
                try {
                    mediaPlayer.setDataSource(context, uri);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                try {
                    mediaPlayer.prepare();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                mediaPlayer.start();
            }
        });
    }

```

# 환경
안드로이드

**Comment by studroid** [comment]
전달해주신 로그를 보고 구글에서 [java.io.FileNotFoundException No content provider firebase ](https://www.google.com/search?sxsrf=ACYBGNSQfHqC2EFAyodKIEXFqzrySntKww%3A1578622282356&ei=St0XXvKXFdyHr7wPwuuS8As&q=java.io.FileNotFoundException+No+content+provider+firebase&oq=java.io.FileNotFoundException+No+content+provider+firebase&gs_l=psy-ab.3..33i21l2.5295.10892..10971...9.0..0.156.2086.1j17......0....1..gws-wiz.......35i39j0i203j0j33i160.4Fdy15AiNVg&ved=0ahUKEwjy5P6i-vfmAhXcw4sBHcK1BL4Q4dUDCAs&uact=5) 라고 검색해보니, [동일한 문제에 대한 답](https://stackoverflow.com/questions/42106294/android-media-stream-error-java-io-filenotfoundexception-no-content-provider/42160256#42160256)이 올라온 글이 있네요 :)

`mediaPlayer.setDataSource(context, uri);` 이 부분을 `mediaPlayer.setDataSource(uri);` 이렇게 변경해주시면 문제없이 돌아가실 듯합니다. 확인 한번 해보세요! :)

**Comment by kammaii** [comment]
> 전달해주신 로그를 보고 구글에서 [java.io.FileNotFoundException No content provider firebase ](https://www.google.com/search?sxsrf=ACYBGNSQfHqC2EFAyodKIEXFqzrySntKww%3A1578622282356&ei=St0XXvKXFdyHr7wPwuuS8As&q=java.io.FileNotFoundException+No+content+provider+firebase&oq=java.io.FileNotFoundException+No+content+provider+firebase&gs_l=psy-ab.3..33i21l2.5295.10892..10971...9.0..0.156.2086.1j17......0....1..gws-wiz.......35i39j0i203j0j33i160.4Fdy15AiNVg&ved=0ahUKEwjy5P6i-vfmAhXcw4sBHcK1BL4Q4dUDCAs&uact=5) 라고 검색해보니, [동일한 문제에 대한 답](https://stackoverflow.com/questions/42106294/android-media-stream-error-java-io-filenotfoundexception-no-content-provider/42160256#42160256)이 올라온 글이 있네요 :)
> 
> `mediaPlayer.setDataSource(context, uri);` 이 부분을 `mediaPlayer.setDataSource(uri);` 이렇게 변경해주시면 문제없이 돌아가실 듯합니다. 확인 한번 해보세요! :)

정말 간단하게 해결되었습니다! 감사합니다~ :)
