### ISSUE TITLE
[파이썬|웹크롤링] 어떤 사이트가 '변했는지' 어떻게 확인하면 좋을까요?

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#899]
개인적으로 웹크롤링 프로젝트를 진행 중인데, 구현이 잘 안돼 조언을 구합니다. 

# 해결하고자 하는 문제

**어떤 게시판을 1분마다 확인하면서 새로운 글이 올라왔는지 알고싶습니다.** 

질문의 맥락을 위해 제 프로젝트 시나리오를 간단히 소개해보겠습니다. 
취준생으로서, 매번 여러 관심 회사와 채용사이트를 확인하기 힘들어 한 개의 프로그램으로 채용 공고를 모두 크롤링해 알림을 받으려고 합니다. 이 때, **일반적인 크롤링 방식으로 각각의 사이트에 딱 맞게 크롤링하는 것이 아닌, 범용적으로 웬만한 사이트 모두에서 크롤링을 쉽게 할 수 있는** 프로그램을 만드려고 합니다. 

이를 위해 어떤 게시글의 css selector을 먼저 확인하여 크롤링하는 방식이 아니라, 게시판에 어떤 게시글이 새로 올라오면 그 **새로** 추가된 게시글의 css selector을 역으로 확인하여 크롤링할 css selector을 특정하는 방식을 쓰려고 합니다. 

결국 프로젝트 플로우를 요약하자면:

웹사이트의 변화를 감지하여 --> 그 변화를 일으킨 element의 내용을 봐서 채용/모집 관련이면 --> 그 element의 css selector을 타겟으로 잡고 앞으로 그 사이트에서 발견한 css selector을 통해 통상적으로 크롤링

하는 구조입니다. 우선 웹사이트의 변화를 감지하여 변화를 감지한 element가 무엇인지 알아내는 것이 첫 발자국인데, 이 부분에서 애를 먹고있습니다. 

# 코드 혹은 오류
```
코드로 여러 시도를 해봤으나 코드 직접 첨부는 생략하고 설명으로 갈음하겠습니다. (아래 참조)
```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

윈도우10, Python 3.7, Conda 환경에서 BeautifulSoup, urllib 등 사용 중. 

# 시도해본 방법

html 텍스트 기반 비교를 시도해봤습니다. 

가장 무식한 방법으로, A사이트 게시판의 HTML을 가져와 저장하고 5분 뒤 다시 HTML을 저장해 두 HTML을 비교하려고 했습니다. 
하지만 한 3초만 간격을 두어도, 새로 올라온 게시글이 없음에도 불구하고 사이트 내부적으로 뭐가 바뀌는게 있는건지 계속 처음 가져온 HTML이 나중 HTML과 다르다는 결과가 나왔습니다. 
HTML을 텍스트로 변환해 하는 방식은 너무 작은 변화에도 취약하고, 변화를 일으킨 핵심 element를 알아차리기 힘들다는 생각을 했습니다. 

텍스트 기반은 너무 별로인 것 같은데.... HTML 트리를 비교할 수 있는 방법은 없을까요? 

조언 기다립니다.

**Comment by taiholee** [comment]
오 잼난걸 하고 계시군요 ㅎㅎㅎ

일단 파이썬을 쓰신다면 [[https://www.crummy.com/software/BeautifulSoup/]]을 추천드립니다. 

코드가 없어서 확인하기 어렵지만, 아마도 url을 이용해서 페이지를 그냥 가져오시는거 같아요. 그럴경우에는 전체 html내용이 복잡하게 들어와서 구분해 내기 어렵습니다. 이런 난감한 상황을 구해줄려고 나온 라이브러리가 BeautifulSoup입니다. 
라이브러리는 사용해보시면 알거 같고, 업뎃되는 부분은 확인하는데 여러 방법이 있을거 같아요. 
아마도 목록에서 가져오는 거라면 목록에 해당하는 테이블, ul 등의 엘리먼트에서 제일 첫번째 녁석을 가지고 구분해 보면 좋을거 같아요. 보통은 데이터베이스에서 데이터를 가져와서 순서대로 보여주는 거라서 제일 첫번째가 같은경우라면 추가된 내용이 없는 것으로 판단하고, 달라졌다면 이전에 첫번째가 나올때까지 한개씩 꺼내보는 방법을 써보면 어떨까요?
물론 여기서 최근에 꺼내본 첫번째에 대한 정보는 크롤링하는 프로그램에서 가지고 있어야 할거 같아요

**Comment by jaepil-choi** [comment]
@taiholee 네! 당연히 뷰티블숲 쓰면서 하고 있습니다. 그런데 BeautifulSoup object로 받아와도 페이지 전체를 받아왔을 때 어느 부분이 바뀌었는지 알아보는 방법이 쉽지 않더라고요... "목록에서 가져온다면 db의 마지막에 저장된 것과 비교하는 방법" 을 말씀하셨는데 좋은 방법입니다만 어느 "목록" 에서 가져올 지 사전에 모르는 채로 웹사이트의 달라진 element를 쭉 볼 수 있는 방법은 없을까요?

db의 최신정보와 비교하는 방법은 확실히 좋은 방법인 것 같은데 그 이전에 사이트 자체가 바뀌었는지 detect하는 방법도 궁금하네요..
