### ISSUE TITLE
질문 web2광고가 어디있죠?

### ISSUE THREAD

**Issue by still7200** [codingeverybody/codingyahac#90]
웹사이트에 광고를 달아서 돈을 벌고 싶은 사람은 web2 광고 수업을 들으라고 하셨는데 찾지를 못하겠어서 여쭤봅니다! 수업 잘 들었습니다.

**Comment by dongheegy** [comment]
[WEBn - 생활코딩 코스 소개 페이지](https://opentutorials.org/course/3083)를 보시면
2018년 1월 10일 현재 **WEB2 광고 수업**은 아직 만들어져 있지 않은 것 같네요.
![image](https://user-images.githubusercontent.com/13765815/34730088-c90492f6-f5a1-11e7-9bf0-18218ace910c.png)

**Comment by egoing** [comment]
아직 만들어지기 전이랍니다~

2018년 1월 10일 (수) 오전 1:03, Choi, Donghui <notifications@github.com>님이 작성:
