### ISSUE TITLE
제가 한 프로젝트를 어디에 올려야하나요??

### ISSUE THREAD

**Issue by WONILLISM** [codingeverybody/codingyahac#900]
프로젝트 진행하면서 질문하고싶은데 제 프로젝트를 어디에 올려야하나요?

**Comment by jaepil-choi** [comment]
본인 깃 레파지토리에 푸쉬하시면 될 것 같습니다. 그리고 링크해주시면 멘토분들이 소스코드를 보고 참고하실 수 있을 것 같아요. - 또다른 멘티가 -

**Comment by WONILLISM** [comment]
감사합니다.
