### ISSUE TITLE
안드로이드 현재 오디오 위치 표시 기능

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#906]
# 해결하고자 하는 문제

안녕하세요?
읽기 연습을 할 수 있는 액티비티가 있습니다.
화면에 길지 않은 글이 있고 그 글을 읽어주는 오디오가 재생이 되는데
현재 오디오가 읽어주는 위치에 노래방 화면처럼 하이라이트나 색깔로 표시를 해주고 싶습니다.
어떤 기능이 필요할까요?
검색을 하려고 해도 키워드를 잡기가 어려워 문의 드립니다.

**Comment by taiholee** [comment]
오우 잼있는 질문이네요 ㅎㅎㅎ

일단 글을 읽는다는것은 음의 장단이 있어서 같은속도로 진행되지는 않을거 같네요. 만약 등속으로 읽는다면, 흡사 TTS같은 느낌이 들거 같아요. 
그래서 읽는 속도의 완급에 따라 진행을 해야 할거 같은데, 간단한 버전과 난이도 있는버전이 있을거 같아요. 

우선 간단하게는 글자를 읽으면서 단어가 넘어갈때마다 시간을 기록해서 같이 표시하는 방법이 있을거 같아요. 
그러면, 단어를 읽으면서 각단어별로 커서가 움직이거나 색을 채우는식으로 진행할  수 있을거 같아요. 

좀 난이도 있는방법은, 글을 읽으면서 마우스등으로 글의 길이만큼을 쭉 드래그 하는식으로 트랙킹 데이터를 구하고, 이것을 글의 길이에 맞추어 표현해주는 방식이 있을거 같아요.

아마도 후자의 경우에 좀더 노래방스러운 그림이 나올거 같은데, 일단 구현한다는 입장에서는 첫번째가 쉬울거 같아요. 

그럼 잼난거 만드시면서 행복하게 코딩하시길 바래요 ㅎㅎㅎ

**Comment by kammaii** [comment]
답변 감사합니다!

일단 간단한 버전만 생각을 해 봤습니다.
지금 제가 알고 있는 기능으로는
위치 표시는 SpannableStringBuilder로 하면 되고
시간에 따른 변화는 Handler 의 postDelayed 를 여러번 중첩 사용해서 구현하는 것이 떠오르는데

위치 표시를 부드럽게 하려 하면 할 수록 더욱 많은 Handler가 중첩되어 상당히 지저분한 코드가 될 것 같습니다. (사실 Handler 기능이 중첩해서 사용할 수 있는지도 확신이 없습니다. ^^;)
혹시 시간을 지정해 줄 수 있는 다른 기능이 있을까요?

**Comment by studroid** [comment]
안드로이드의 MediaPlayer에 연결되어 있는 [SubtitleData](https://developer.android.com/reference/android/media/SubtitleData) 클래스를 참고해보시면 힌트를 좀 얻으실 수 있지 않을까 싶습니다.

자막에 관한 표준 데이터 형태를 보시면 보통 시작 시간, 지속 시간 등을 포함하는 형태를 띕니다. 이것처럼 화면에 있는 길지 않은 글을 자막의 형태처럼 시간 데이터를 포함하도록 만들면, 타이머 등으로 주기적인 확인을 통해 오디오의 위치를 표시할 수 있지 않을까 싶습니다 :)

**Comment by kammaii** [comment]
답변 감사합니다! SubtitleData 에 대해 공부해봐야겠습니다! :)
