### ISSUE TITLE
마스터 브랜치로 저장했는데 웹페이지가 이상하게 뜨네요

### ISSUE THREAD

**Issue by ghost** [codingeverybody/codingyahac#91]
분명 파일들도 다 저장했는데 수업 화면처럼 안 뜨고 딱 WEB-1만 뜨네요;; 문제가 있는 건가요? 확인 부탁드립니다 ㅠㅠ
https://github.com/rainbowbread12/Web-1

**Comment by ghdalsrldi** [comment]
혹시 Push 하셨는지 확인해 보세요

**Comment by egoing** [comment]
주소로 접근했을 때 페이지가 없다고 나오네요~
주소 확인 부탁 드려봅니다

2018년 1월 9일 (화) 오후 8:52, mkhong <notifications@github.com>님이 작성:
