### ISSUE TITLE
서버 컴퓨터에 접속했을 때 a 태그 링크가 걸려 있는 것을 열면 에러가 뜹니다.

### ISSUE THREAD

**Issue by nayeonshin** [codingeverybody/codingyahac#910]
# 해결하고자 하는 문제
웹 브라우저와 웹 서버 운영하기 (윈도우)에서, 서버 컴퓨터에 접속했을 때 a 태그 링크 ("http://www.illumination.com/")가 걸려 있는 것을 열면 에러가 뜹니다. (index.html을 여는 것에는 문제가 없습니다.)

아래는 순서대로 제 index.html 코드, index.html 사진, 링크가 걸려있는 첫 문단의 첫 단어 "Minions"를 눌렀을 때의 사진입니다.

(첨부 사진에서 IP 주소랑 리퀘스트 아이디는 공개적으로 올려도 되는지 안 되는지를 잘 몰라서 일단은 가렸습니다.)

# 코드 혹은 오류
```
<!doctype html>
<html>
<head>
  <title>MINIONS - Welcome</title>
  <meta charset="utf-8">
</head>
<body>
  <h1><a href="index.html">MINIONS</a></h1>
  <ol>
    <li><a href="1.html">Kevin</a></li>
    <li><a href="2.html">Stuart</a></li>
    <li><a href="3.html">Bob</a></li>
  </ol>
  <h2>Minions란 무엇인가?</h2>
  <p><a href="http://www.illumination.com/" target="_blank" title="illumination">Minions</a> (/ˈmɪnjənz/) are <strong><u>yellow</u> creatures</strong> that appear in the Despicable Me franchise, which started with Despicable Me (2010), and are characterized by their childlike behavior and unique language, which is almost intelligible at times.
  They are also the official mascots of Illumination, a division of Universal Pictures, which produces the films. Following Comcast's purchase of NBCUniversal, they have been described as being a corporate icon for Universal and Comcast, on par with Disney's Mickey Mouse and WarnerMedia's Bugs Bunny, although Woody Woodpecker is still considered a mascot for Universal Studios.</p>
  <img src="minions.png" width="100%">
  <p>Kevin, Stuart, and Bob are three of the most familiar minions, who appear as stars in the film Minions. Many other Minions are mentioned by name in the films and other media in the franchise.</p>
</body>
</html>
```

![코야](https://user-images.githubusercontent.com/52480305/72128100-c3411500-333f-11ea-95cb-aace26ca4979.png)

![코야 2](https://user-images.githubusercontent.com/52480305/72128108-c89e5f80-333f-11ea-9e98-1eec9660ffdf.png)

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
윈도우, HTML, ["라이브러리 버전"이라는 것은 무엇인지 모르겠습니다.]

# 시도해본 방법
확실히 스마트폰과 노트북 둘 다 같은 네트워크 안에 있습니다.
노트북 방화벽은 다 껐습니다.

읽어주셔서 대단히 감사합니다.

**Comment by taiholee** [comment]
cloud front 에서 에러가 났네요. 

아마도 웹서버를 설정해서 앞쪽에 cloud front를 두셨거나, 혹은 s3에 파일을 올려두시고, cloud front로 캐싱을 하시는거 같네요. 
테스트하는 중이면, 아마도 트래픽이 과도하게 몰리거나 하지는 않을거 같으니, 아마도 설정상에서 연결이 올바르지 않은 부분이 있을거 같은데, 자세히 살펴보시면 될거 같아요. 혹은 cloud front설정과 그뒤에 연결되어 있는 부분에 대해서 좀더 자세히 알 수 있으면 더 자세한 조력자분들의 도움을 받으실 수 있을거 같아요 ㅎㅎㅎ

**Comment by nayeonshin** [comment]
답변해 주셔서 감사합니다!
