### ISSUE TITLE
카페 24를 통해서 웹 호스팅을 하려고 합니다. node.js 와 vue.js

### ISSUE THREAD

**Issue by dodi258** [codingeverybody/codingyahac#923]
# 해결하고자 하는 문제
<현재 상황> 
카페 24를 통해 돈을 내고 호스팅을 샀습니다. 
![image](https://user-images.githubusercontent.com/55937575/72219050-24a5f580-3585-11ea-8ad4-e40153ffe80d.png)
그림과 같이 카페 24에 제가 접근할 수 있는 git 저장소가 주어져서 
저는 거기에 코드를 푸쉬하고 
cafe24에서 준 도메인 으로 가면, 푸쉬한 코드가 빌드되서 보여지는 그런 형식입니다. 

저는local 컴퓨터에서는 
 web_project/as4라는 디렉토리 아래 backend폴더와 frontend폴더를 두고 있습니다.
![image](https://user-images.githubusercontent.com/55937575/72219101-88c8b980-3585-11ea-977c-47f3531995f1.png)
backend는 node.js 로 구성한 서버이며 
frontend는 vue/cli로 구성한 vue 프론트 입니다. 
서로는 이어져 있습니다!! 

먼저 web_project/as4 에 git 저장소를 clone했고, 
as4에 있는 backend와 frontend 파일을 push 하고 부여받은 도메인 heartravel.cafe24app.com
으로 갔지만 오류 메세지만 계속해서 보입니다..
backend에 있는 파일이라도 하려고 
검색해서 나오는 블로그에 있는 메뉴얼을 다 따라서 해보았지만 작동하지 않아서요... 

또, 어떻게 backend frontend 같이 올려서 호스팅 할 수 있을까요..? ㅜ 
모든 블로그에는 backend만 간단하게 한 것 같은데... 둘다 package.json이 존재하는데 또 어떻게 구분을 시켜야할지 막막하기도 합니다. 

또, 절대 경로로 지정된 파일같은 경우에는 local 디렉토리가 아니고 cafe24를 통한 경로로 바꿔줘야할 것 같은데 방법을 모르겠습니다.. ㅜㅜ 

이렇게 두서없이 질문 드렸는데 ㅜ 
혹시 도와주실 수 있을까요...?
 

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```
cafe24가 보여준 오류는 503오류인데
설명은 서버에 접근할 수 없다는 오류라고 합니다. 

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
window, javascript, node.js v12.13.0, vue/cli 4.1.2

# 시도해본 방법
1. backend파일을 backend에서 다 꺼내고, web.js라는 실행파일을 만들어서 (cafe24가 web.js를 인식한다고 하네요!) 다 같은 디렉토리에 있게 한 후 push 해서 실행해봄. 
2. node_modules 디렉토리를 backend에서 지워서 push를 하여 오류가 났다는 생각에 다시 npm install 하여 그 파일을 push 한 후 실행해 봄. 
3. frontend파일을 지워서 push 해 봄. 
4. mysql 도 연동해야하지만, 아직 오류가 날 것 같아 그 부분은 코드에 넣지 않았음.

**Comment by fermat39** [comment]
안녕하세요... 503 이면 설정 문제가 가장 먼저 예상됩니다.
아니면, 방화벽으로 인해 접근이 안 되는 문제일 수 있을 것 같네요...

**Comment by dodi258** [comment]
설정을 잘못했던거 같아요..!조언 감사합니다
