### ISSUE TITLE
안드로이드 뷰페이저 휴대폰 에러 문제

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#932]
# 해결하고자 하는 문제

안녕하세요?
AVD 대신 직접 휴대폰에서 테스트를 해봤는데 MainActivity 의 뷰페이저 작동 시 
'애플리케이션이 예상치 않게 중지되었습니다' 라는 에러가 발생하며 종료됩니다.
AVD에서는 전혀 문제가 없었던 부분인데 무슨 에러가 났는지 볼 수도 없어 어떻게 해결해야 할 지 전혀 모르겠습니다.
어떤 부분을 확인해야 할까요?

# 코드 혹은 오류
-ViewPagerAdapter

```
 public class ViewPagerAdapter extends FragmentPagerAdapter {

    MainActivity mainActivity;

    public ViewPagerAdapter(FragmentManager fragmentManager, MainActivity mainActivity) {
        super(fragmentManager);
        this.mainActivity = mainActivity;
    }

    @Override
    public int getCount() {
        return 5;
    }

    @Override
    public Fragment getItem(int position) {

        switch (position) {

            case 0 :
                return MainLesson.newInstance(mainActivity);

            case 1 :
                return MainReading.newInstance(mainActivity);

            case 2 :
                return  MainWriting.newInstance(mainActivity);

            case 3 :
                return MainCollection.newInstance(mainActivity);

            case 4 :
                return MainQna.newInstance();

            default :
                return null;
        }
    }

}

```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.

# 시도해본 방법

**Comment by Hatser** [comment]
[개발자 옵션]의 [USB 디버깅] 옵션을 사용하시면 Android Studio의 Logcat을 통해 안드로이드 기기에서 발생하는 로그들을 확인하실 수 있습니다.

[여기](https://developer.android.com/studio/debug/dev-options)에서 자세한 설명을 보실 수 있어요.

**Comment by kammaii** [comment]
아! 이렇게 하면 볼 수 있군요. 감사합니다! :)
Logcat을 보니 Room entity 의 내용을 변경했을 때 나오는 에러가 발생하고 있었습니다.
보통 AVD 에서 Room 의 entity를 변경할 때마다 AVD를 재설치하는 방법으로 에러를 해결했는데
실제 모바일에서는 앱을 삭제하고 다시 설치해도 Room 이 제거가 되지 않는 건가요?

**Comment by Hatser** [comment]
Room은 어플리케이션에 종속된 개념이 아니기 때문에 어플리케이션을 삭제하더라도 Room에서 알아채지 못해 데이터를 삭제하지 못하는 것 같네요.

대신, entity가 수정될 때의 행동(DB 버전이 바뀌었을때의 행동)을 어플리케이션 내에서 지정할 수 있습니다.

`[여기](https://developer.android.com/training/data-storage/room/migrating-db-versions)`에서 확인하실 수 있어요.

**Comment by kammaii** [comment]
firebase DB에도 데이터를 백업하고 있어 Room 에서는 따로  백업하지 않도록 
```
        android:allowBackup="false"
        android:fullBackupContent="false"
```
이렇게 설정해서 해결했습니다
답변 감사합니다! :)
