### ISSUE TITLE
안드로이드 시간에 관한 질문

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#934]
# 해결하고자 하는 문제

안녕하세요?
현재 만들고 있는 앱에 있는 기능을 간단히 설명드리면,

1. 앱에서 사용자가 글을 작성하고 이 글을 firebase의 DB에 저장
2. 웹에서 다른 사람이 그 글을 가져와서 수정을 하고 DB에 저장
3. 앱 사용자는 앱에서 수정된 글을 볼 수 있음

이런 기능을 만들고 있는데 여기에 시간에 관한 문제가 있습니다.
앱에서 처음 글을 작성했을 때와
웹에서 글을 수정했을 때 각각 현재 시간을 입력하게 되어있는데
앱 사용자와 웹 사용자는 거주 국가가 다를 수 있기 때문에 현재시간에 차이가 발생하게 됩니다.

이 시간 차이를 어떻게 해결해야 할까요?

고민을 해 보았는데 DB에 저장되는 어떤 특정 국가의 시간으로 통일해서 저장을 하고
앱이든 웹이든 접속할 때마다 접속 지역을 알아내어 DB에서 받아온 시간을 변환해서 출력하는 방법을 사용하면 될 것 같은데 
접속 지역을 알아내고 시간을 변환하고 하는 작업이 어떻게 이루어져야 할 지 모르겠습니다.
혹시 다른 좋은 방법이 있으면 가르쳐주시면 감사하겠습니다.

**Comment by Hatser** [comment]
`UNIX 타임스탬프`로 시간을 관리하시면 더 편할 것 같아요. 시간대에 독립적인 수치이거든요.

안드로이드와 자바스크립트 모두 시간대를 관리하는 기능들이 있으니 참고해보시면 도움이 될 것 같습니다.

`[ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)`도 참고해보실 수 있습니다.
`ISO_8601`같은 경우에는 `2020-01-14T10:37:34+09:00` 같은 모습으로 문자열 형태의 시간과 시간대의 offset을 함께 나타냅니다.

**Comment by kammaii** [comment]
> [`UNIX 타임스탬프`](https://ko.wikipedia.org/wiki/%EC%9C%A0%EB%8B%89%EC%8A%A4_%EC%8B%9C%EA%B0%84)로 시간을 관리하시면 더 편할 것 같아요. 시간대에 독립적인 수치이거든요.
> 
> UNIX 타임스탬프로 받은 수치를 시간으로 나타내는 방식으로 처리하시면 되겠습니다.
> 
> 안드로이드와 자바스크립트 모두 시간대를 관리하는 기능들이 있으니 참고해보시면 도움이 될 것 같습니다.
> 
> [`ISO_8601`](https://en.wikipedia.org/wiki/ISO_8601)도 참고해보실 수 있습니다.
> `ISO_8601`같은 경우에는 `2020-01-14T10:37:34+09:00` 같은 모습으로 문자열 형태의 시간과 시간대의 offset을 함께 나타냅니다.

아! UNIX 타임스탬프라는 것이 있었네요. 이거면 쉽게 해결될 것 같습니다. 감사합니다! :)

ㅏ!
