### ISSUE TITLE
웹서버에 대한 개념이해

### ISSUE THREAD

**Issue by eileenpxh** [codingeverybody/codingyahac#935]
아직 개념에대한 이해가 부족한것 같아 질문드립니다. 
1. Github와 같은 Web hosting은 html파일을 저장해주는 저장소의 역할을 하는건가요? 
2. 그렇다면 Apache를 통해 사용하는 Web Server는 제가사용 하는 컴퓨터 외의 또하나의 서버가 맞나요?
3. 코딩야학 수업중 [웹서버와 웹브라우저의 통신19.1.3] 부분에서 같은 네트워크를 공유하는 두대의 컴퓨터중 한대가 상대의 IP로 접속했을때 제작한 웹페이지가 나온다는 것은 무엇을 의미하는건가요? 웹페이지를 서로 주고 받는다고 하는데, IP주소를 입력하면 웹페이지가 나타난다는 것이 <<<<IP 입력= 해당IP의 웹페이지 결과물>>>>이렇게 해석되는데 IP주소는 컴퓨터서버의 주소로 더 큰 개념 아닌가요? 왜 웹페이지를 바로 읽어들일 수 있는건가요? 혹시 Apache 웹서버로 하나의 페이지만 저장/읽기 가 가능한건가요?

**Comment by o2-basta** [comment]
1. github은 git을 호스팅하고 있으며, github에서 제공하는 서비스중 하나가 html정보를 보여주는 것이며, 기본적으로는 git에 저장해서 푸시한 모든 파일을 관리하고, 필요한 경우에 clone할 수 있도록 해주는 서버입니다. 그러니까 html파일을 포함한 모든 git저장파일을 다루고 있습니다. 

2. web server는 명시적으로 web client와 구분되는 서버 프로그램입니다. 프로그램은 사실 하나의 컴퓨터에서 같이 실행될 수 있어요. 그러니까, 구분할 수 있는것은 서버와 클라이언트이며, 물리적인 컴퓨터는 같이있거나 따로 있을 수 있습니다 

3. 이부분은 네트워크에서 IP와 포트를 구분해볼 필요가 있어요. 보통 웹은 80번 포트에서 서비스를 하고 있어요. 물론 443에서 https를 서비스 하지만, 80을 기준으로 한다면, 어떤 IP에서 html을 받는 다는것은 해당 IP의 80번 포트에서 받는다는것을 의미합니다. 그러니까 웹브라우저에서 http://IP주소:80 하는것과 같은방식이며, 80번 포트가 생략된 것입니다. Apache서버는 80번으로 요청되는 기본 파일을 아무런 파일명이 없어도 제공하지만, 특정파일에 대해서 요청하면, 해당파일을 내어주게 되어 있습니다. 

이제 점점더 질문과 숙고를 통해서, 우리의 주변에서 돌아다니는 웹과 네트웍을 이해하실 수 있으신거 같네요 ㅎㅎㅎ

새로운것들을 발견하고 익히는 재미를 많이 느끼시길 바래요 ㅎㅎ

**Comment by eileenpxh** [comment]
> 1. github은 git을 호스팅하고 있으며, github에서 제공하는 서비스중 하나가 html정보를 보여주는 것이며, 기본적으로는 git에 저장해서 푸시한 모든 파일을 관리하고, 필요한 경우에 clone할 수 있도록 해주는 서버입니다. 그러니까 html파일을 포함한 모든 git저장파일을 다루고 있습니다.
> 2. web server는 명시적으로 web client와 구분되는 서버 프로그램입니다. 프로그램은 사실 하나의 컴퓨터에서 같이 실행될 수 있어요. 그러니까, 구분할 수 있는것은 서버와 클라이언트이며, 물리적인 컴퓨터는 같이있거나 따로 있을 수 있습니다
> 3. 이부분은 네트워크에서 IP와 포트를 구분해볼 필요가 있어요. 보통 웹은 80번 포트에서 서비스를 하고 있어요. 물론 443에서 https를 서비스 하지만, 80을 기준으로 한다면, 어떤 IP에서 html을 받는 다는것은 해당 IP의 80번 포트에서 받는다는것을 의미합니다. 그러니까 웹브라우저에서 [http://IP주소:80](http://IP%EC%A3%BC%EC%86%8C:80) 하는것과 같은방식이며, 80번 포트가 생략된 것입니다. Apache서버는 80번으로 요청되는 기본 파일을 아무런 파일명이 없어도 제공하지만, 특정파일에 대해서 요청하면, 해당파일을 내어주게 되어 있습니다.
> 
> 이제 점점더 질문과 숙고를 통해서, 우리의 주변에서 돌아다니는 웹과 네트웍을 이해하실 수 있으신거 같네요 ㅎㅎㅎ
> 
> 새로운것들을 발견하고 익히는 재미를 많이 느끼시길 바래요 ㅎㅎ
