### ISSUE TITLE
페이지가 뜨질 않습니다.

### ISSUE THREAD

**Issue by rainbowbread** [codingeverybody/codingyahac#94]
강의에서 나온대로 master branch로 저장하고 페이지를 눌렀는데

404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

라고 뜨네요. 이메일 인증도 했는데 무슨 문제가 있는 건가요?

제 주소는 https://rainbowbread.github.io/Web1/입니다.

**Comment by ghdalsrldi** [comment]
현재 정상적으로 접속되고 있어요

https://rainbowbread.github.io/Web1/

<img width="830" alt="2018-01-09 9 53 23" src="https://user-images.githubusercontent.com/8347865/34721803-903de018-f587-11e7-952c-6443c465b2a0.png">

**Comment by azaraks2** [comment]
처음 사이트 생성할 때는 시간이 좀 걸릴 수 있습니다.

**Comment by rainbowbread** [comment]
감사합니다~!!!!
