### ISSUE TITLE
node.js 페이지를 실행하면, client쪽에서 설정한 url를 인식하지 못해 404 오류가 발생합니다. 

### ISSUE THREAD

**Issue by dodi258** [codingeverybody/codingyahac#941]
<상황>
backend - node.js, express 모듈 환경 세팅
frontend - vue.js 

# 해결하고자 하는 문제
front 쪽에서 npm run build를 하고, 배포 파일을 만들어서 backend쪽에 주었습니다. 
backend로 cmd창을 열어 npm start를 해서 앱을 실행시켰는데요, 

첫 메인화면은 잘뜨는데, 
예를들어
localhost:3000
라는 주소를 주소창에 치면 메인화면은 나오는데, 
localhost:3000/login
라는 주소를 주소창에 치면 
![image](https://user-images.githubusercontent.com/55937575/72437016-25d55d80-37e5-11ea-931e-14bfbc3f5c01.png)
이렇게 페이지를 찾지 못합니다...

아마 backend에서 app.get('/')설정을 하지 않아서 그런것 같긴한데..
frontend에 모든 .vue파일이 있는데 
그것을 어떻게 app.get('/')을 이용해 모든 페이지들을 연결해주어야 할지 막막합니다...

배포과정에서 절대적인 도움이필요합니다 ..ㅠㅠㅠ

혹시 몰라서
backend의 app.js 를 올립니다. 

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
```
cmd창
GET /login? 404 211.181 ms - 1083

app.js 코드
![image](https://user-images.githubusercontent.com/55937575/72437235-a1cfa580-37e5-11ea-9e8d-384b5d2edcf8.png)

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
운영체제: window 8
언어: javascript
라이브러리: node.js12.13.0 , express 4.16.1 , vue (vue/clie) 4.1.2

**Comment by mkhong-otu** [comment]
404 Not Found는 해당 경로(/login)에 해당되는 페이지가 없다는 오류메세지입니다.
백엔드에서 /login 에 대한 요청을 받아 처리하는 부분이 없기 때문입니다.

백엔드(Express)에서 /login 라우팅 처리를 하여 멀티페이지 웹사이트를 만드시거나,
백엔드, 프론트엔드를 완전히 분리하여 백엔드는 API 서버 역할만.. 프론트앤드는 서버사이드 랜더링을 통해 구현하는 방법이 좋을 것 같습니다.

서버사이드 랜더링은 아래의 링크를 참고해 주세요.
https://kr.vuejs.org/v2/guide/ssr.html
