### ISSUE TITLE
Data Analyst 관련 공부 방향

### ISSUE THREAD

**Issue by jasminekim** [codingeverybody/codingyahac#947]
안녕하세요. 코딩야학 7기 수강생입니다. 조력자님들 감사합니다.
제가 원하는 분야가 있는지 검색 중에 다음과 같은 표현이 있었는데요.
엔지니어나 개발자 쪽은 아닌데 회사에서 요구하는 최소 2년 경력의 주니어 레벨 데이터 분석 업무 담당자의 필수요건이 아래와 같다면, 저같은 완전초보 비전공인은 무엇을 어떻게 시작해서, 어떤 방향으로 공부하면 좋을까요. 또 어느 정도 배우면 될까요. 
나중에 미래에 기회가 주어진다면 지원하고 싶은 분야여서, 천천히 차근차근 공부해보고 싶어서 여쭤보게 되었습니다. 감사합니다. 
  
Experience in working with large datasets with SQL, Python, and/or R.

**Comment by znffl** [comment]
안녕하세요.
해외는 어떤지 모르겠지만 국내 기준 아는 선에서 답변드리겠습니다.
데이터분석팀은 보통 통계학과 출신이 대부분입니다. 비전공자도 같은 공과계열(컴공)이 대부분입니다.
 ```Experience in working with large datasets with SQL, Python, and/or R.``` 요구하는 기준과 같이  SQL, Python, R 을 다루는 기술도 필요하지만 통계공부가 필수적입니다. 우선 순차적으로 언어와 함께 통계쪽도 심도있게 공부해보시면 좋을 것 같습니다.
cour

**Comment by RayleighKim** [comment]
첨언을 하나 드릴께요. 
통계학과에서 R을 잘한다라는 말은 사실, 통계를 잘한다라는 말이 내포되어 있어요.

프로그래밍 랭귀지로써의 R이 아니라, 통계 분석툴로써 R이기 때문에., 문제 정의, 적절한 기법선택, 결과 해석 등은 코딩의 영역이 아닌경우가 많아요.

통계도 같이 공부해야 함에 찬성합니다.

**Comment by jasminekim** [comment]
아 신 조력자님, 고맙습니다. (어제 차분한 음성으로 사연 읽어주셔서 어떤 분이신지 궁금했는데 이렇게 좋은 답변 주시다니.. 감동입니다. )
학교 때 경제학 통계학 공부하며 SQL 배웠던 기억이 가물가물. 
쉽지 않겠지만, 통계도 차차 도전하겠습니다.
코세라와 KOCW 추천도 감사드립니다. (앱 바로 설치했어요!)
공부할게 많이 생겨서 마구 도전의식 샘솟는데 걱정도 되네요. 
조언 감사드립니다. 생활코딩에서 자주 뵙겠습니다. :)

레일리님 답변 감사합니다.
R 공부도 해야겠네요. 통계분석을 위한 툴이라니 예전에 소홀했는데 
다시 힘내서 도전해보겠습니다. 고맙습니다.
