### ISSUE TITLE
인공 지능 관련 공부를 하고 싶은데 어디서부터 시작할지 모르겠습니다.

### ISSUE THREAD

**Issue by soldier4443** [codingeverybody/codingyahac#95]
헉 실수로 그냥 만들어버렸네요....

머신 러닝, 딥 러닝 등에 대한 이야기는 많이 들어보았지만
어디서부터 시작해야 할지를 잘 모르겠습니다.

제 목적은 인공 지능 최신 분야의 연구는 아니고,
인공 지능 기술을 활용해서 게임 시스템에 활용할 수 있는 방안을 찾아보는 것인데요..
가능하다면 블록 체인 기술에도 인공 지능을 적용해보고 싶습니다.

자세히는 아니더라도 시작할 수 있는 지점을 알려주시면 감사하겠습니다ㅠ
(입문 수준의 강의 목록, 딥 러닝 분야의 논문 목록 등등.. 영어 자료도 좋아요!)

**Comment by davidkwak** [comment]
안녕하세요. 

입문수준의 강의는 Andrew Ng 교수님의 coursera 강의가 제일 유명하고 
국문으로는 홍콩과기대 Sung Kim 교수님의 "모두의 딥러닝"이 유명합니다. 
참고1 : https://www.coursera.org/learn/machine-learning/lecture/zcAuT/welcome-to-machine-learning
참고2 : https://www.youtube.com/watch?v=BS6O0zOGX4E&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm

최신 자료는 reddit에서 보시는게 가장 빠르고, 국문 자료는 페북 "텐서플로 코리아" 그룹에서 얻으실 수 있을겁니다. (눈팅하시면 좋은 논문이나 공부할 거리는 끝없이 던져주십니다... 제가 안해서 그렇지..)

참고 1 : https://www.reddit.com/r/MachineLearning/
참고 2 : https://www.facebook.com/groups/TensorFlowKR/

**Comment by soldier4443** [comment]
좋은 자료 감사합니다 ㅎ 먼저 모두의 딥러닝으로 시작해봐야겠네요!
