### ISSUE TITLE
repository 안에 특정 파일을 지우고 싶어요!

### ISSUE THREAD

**Issue by ksb0511** [codingeverybody/codingyahac#951]
git bash를 이용하지 않고 깃허브 내 혹은 비주얼스튜디오 내에서 특정 파일 삭제가 가능한가요?

**Comment by studroid** [comment]
깃허브의 저장소에서 지우고 싶으신 파일을 클릭해서 들어가신 후, 파일 설명의 상단에 보시면 지우기 버튼이 있습니다 :)
![스크린샷 2020-02-01 오후 4 23 26](https://user-images.githubusercontent.com/4001790/73588666-2ec96d00-450f-11ea-877d-6063d924e89c.png)
