### ISSUE TITLE
프로젝트 아이디어를 평가받고 싶습니다. (텍스트 기반 웹 크롤러)

### ISSUE THREAD

**Issue by jaepil-choi** [codingeverybody/codingyahac#954]
Q: 새로운 텍스트 기반 Web Scraping 방식을 생각해봤는데, 혹시 이미 있는 방법일까요?

사이트 하나하나마다 직접 css selector을 선택하는 방법이 아닌, 텍스트 기반으로 (거의) 어떤 사이트에서도 작동하는 robust한 web scraper을 만들어 봤습니다. 나름 참신한 방법이라 생각하는데 혹시 이미 있거나 일반적으로 알려진 방법이 아닌가 궁금하네요. 검색으론 안나옵니다만...

좀 더 구체적으로 설명을 써보면:

채용공고 게시판이나 타 게시판에 새 글 올라오는지 일일이 확인하기 귀찮아서 새 글 알림 scraper을 만드는 중입니다.

보통 web scraping 배울 때 어렵지 않게 타깃 게시판에서 개발자도구 켜서 글들의 css selector을 보고 규칙을 찾아내 그 사이트에 맞는 scraper을 짜게 되는데요, 이러면 사이트 하나하나마다 만들어줘야 합니다.

그래서 게시판의 텍스트를 기반으로 어느 사이트에서라도 게시글들 간의 css selector 규칙을 프로그램이 스스로 찾아내 게시글을 다 긁어오는 scraper을 만들어봤습니다.

스스로 나름 참신한 방법이라 생각했는데 별로 어려운 방식도 아니고 해서 혹시 이미 있는 방법은 아닌지, 비슷한 방법이 일반적으로 쓰이진 않는지 궁금합니다. 혹시 있다면 그 쪽 자료를 좀 더 찾아보는데 활용하려고요.

혹시 들어보신 적 있으시면 알려주시면 감사하겠습니다.

**Comment by j1hwan** [comment]
이야기하신 방식의 스크래퍼 아이디어는 아래와 같은 서비스를 참고하시면 도움이 될 것 같습니다.

https://tryspider.com
https://www.scraping-bot.io
http://crawly.diffbot.com

최근에는 브라우저 확장 프로그램과 연계하여, 페이지 구조를 모르는 사용자도 추출 범위를 손쉽게 설정하고 결과를 확인할 수 있는 NoCode 서비스도 늘어나고 있습니다.

https://webscraper.io
https://simplescraper.io

**Comment by jaepil-choi** [comment]
@j1hwan 와 하나씩 봐봤는데 UI도 너무 깔끔하게 잘되어있네요. 백엔드를 제가 볼 수는 없겠지만 서비스들이 텍스트처리를 기반으로 하는 것은 아닌 것으로 보이긴 합니다. 

하지만 서비스 데모들을 보니 그냥 크롬 확장프로그램을 통해 화면에 오버레이를 하든가 해서 하면 되니까 훨씬 간편하고 굳이 텍스트 기반일 필요가 없을 수도 있겠다... 라는 생각도 드네요 ㅠㅠ 

저는 이런것들이 있는 줄도 몰랐는데 좋은 서비스 찾아주셔 감사합니다. 아이디어를 발전시키는데 참고해보도록 하겠습니다.
