### ISSUE TITLE
안녕하세요 퍼블리셔로써 더 공부하기위한 질문을 드립니다.

### ISSUE THREAD

**Issue by pung8146** [codingeverybody/codingyahac#96]
제가 퍼블리셔 교육을 받고 HTML.CSS,간단한 제이쿼리 자바스크립트 배우고 퍼블리셔로 취직 하게되었습니다.

 회사규모가 작은편이라 직원들중에 프로그램 관련사람이없어 , 제가 페이지 기획부터 디자인 제작 호스팅과 도메인까지 도맡아서 하고있습니다.

 처음에 이런 많은 경험이 도움이 될줄 알았지만 지금은 페이지 제작보다 포토샵으로 웹디자인을 하는일이 더많아 직장에 대한 고민이 생기고 있습니다.

 컴퓨터 에 잘아는 직원도없고 검토받을때  프론트쪽 기술보단 웹디자인 사진을 더중시하니 
코딩관련시간보다 포토샵을 여는시간이 더많습니다.

 이럴때 이직을 하는게 좋을지 아님 이회사에서  제스스로 개인적으로 계속 공부하는게좋을지 고민의 길에 빠져있습니다.

**Comment by blackdew** [comment]
회사를 그만 둘지 계속 다녀야 하는지 이 부분에서는 pung8246 보다 더 깊게 고민할 수 있는 사람은 없는 것 같아요. 
본인의 판단을 믿으시고 선택하시는게 가장 좋을 것 같습니다. 

다만, 그만두고 이직을 하는 것은 다시 되돌릴 수 없는 결정이니까요. 그런 선택을 하기 전에 고민과 더불어 
상황을 긍정적인 측면으로 바꿀 수 있을 만한 이런 저런 시도들을 해보시면 어떨까 싶어요.
