### ISSUE TITLE
머신러닝에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by youngwon2** [codingeverybody/codingyahac#97]
안녕하세요 저는 27살 물류학과를 졸업한 사회과학계열 학생입니다
코딩야학을 시작하고 코딩에 대해서 공부하던 중에
아마존이라는 회사가 제 전공과도 관련이 있었기에 자연스레 관심이 많이 갔습니다. 

상용 머신러닝 API, DSSTNE, SageMaker 등
여러가지 툴들이 있더라구요

제 현재 상태는 막 웹 공부하고 자바, 파이썬, C++ 등을 접해보려고 하는데
머신러닝에 대해서 유튜브 라이브방송때 질문을 드리니
이쪽으로 질문하면 전문가분이 계시다고 하시더라구요.

주변에 이공계친구들은 많아도 막상 머신러닝 분야에 대해 물어보면
잘 아는 친구들이 없더라구요.
어떤 식으로 공부를 하셨는지, 요즘 트렌드는 어떠한지 궁금합니다!!
이 분야에 입문하기 위한 조언을 해주시고 싶으시다면 더욱 감사드리구요.

최근 날씨가 쌀쌀하니 많이 추워졌는데 감기 조심하세요^^

**Comment by davidkwak** [comment]
안녕하세요. 아래 다른분 질문하신 것과 유사한 내용인것 같아 한번 더 복붙합니다.

입문수준의 강의는 Andrew Ng 교수님의 coursera 강의가 제일 유명하고
국문으로는 홍콩과기대 Sung Kim 교수님의 "모두의 딥러닝"이 유명합니다.
참고1 : https://www.coursera.org/learn/machine-learning/lecture/zcAuT/welcome-to-machine-learning
참고2 : https://www.youtube.com/watch?v=BS6O0zOGX4E&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm

최신 자료는 reddit에서 보시는게 가장 빠르고, 국문 자료는 페북 "텐서플로 코리아" 그룹에서 얻으실 수 있을겁니다. (눈팅하시면 좋은 논문이나 공부할 거리는 끝없이 던져주십니다... 제가 안해서 그렇지..)

참고 1 : https://www.reddit.com/r/MachineLearning/
참고 2 : https://www.facebook.com/groups/TensorFlowKR/

**Comment by youngwon2** [comment]
davidkwak님 감사합니다^ㅡ^
