### ISSUE TITLE
오렌지 다운로드 오류

### ISSUE THREAD

**Issue by risingsun100** [codingeverybody/codingyahac#976]
# 해결하고자 하는 문제
오렌지3 다운로드 받았는데 실행이 안되고 오류메시지가 뜨네요
프로그램을 다시 설치해 보았는데도 똑같은 메시지가 뜹니다.

# 코드 혹은 오류
![오렌지오류](https://user-images.githubusercontent.com/69622696/90108774-c7298f80-dd85-11ea-9b84-ed9a7b3fed1c.JPG)

# 환경
윈도우 10

# 시도해본 방법

**Comment by progh2** [comment]
아래 두 가지 방법을 한번 시도보실래요? 
둘 다 안되면 오랜지3 설치 방법 중에서 아나콘다에서 pip으로 설치하는 방법을 시도해봐야 할 것 같습니다. 

https://m.blog.naver.com/PostView.nhn?blogId=jamiet1&logNo=221154575287&proxyReferer=https:%2F%2Fwww.google.com%2F

https://doongkibangki.tistory.com/24

**Comment by leems-github** [comment]
설치완료후 실행하자마자 동일한 에러가 나는데 혹시 설치경로 폴더명이 한글인것은 상관없는지요?
예) c:\users\이름\AppData\Local\Orange

**Comment by risingsun100** [comment]
제가 거의 컴맹수준이라 질문을 해 놓고 답변을 제대로 소화하지 못하고 있었습니다.
그러다가 주위의 도움을 받아 조력자님들의 조언대로 실행하였더니 그 덕분에 설치하는데 성공하게 되었습니다.
폴더명에 한글이 들어가지 않은 프로그램 파일의 경로로 해서 실행을 하니 설치가 되었습니다.
정확한지 모르겠지만 아마도 설치경로 폴더명에 한글이 들어가 있는 것이 원인이 아니었나 생각됩니다.
조력자님들의 조언에 깊은 감사의 말씀을 드립니다.
감사합니다.~~
