### ISSUE TITLE
인턴이나 계약직으로라도 경력을 쌓을 수 있는 곳 있을까요

### ISSUE THREAD

**Issue by heejong9** [codingeverybody/codingyahac#977]
제가 정통 졸업예정자인데 생활코딩을 너무 늦게 알아서 이제야 재미가 붙었습니다. 그런데 아직 이력서에 쓸게 없습니다. 혹시 이런 아무것도 없는 저라도 가서 현장을 느끼고 코딩을 할 수 있는 경력을 쌓을수있는 곳이 있을까요?ㅜㅜ

**Comment by RayleighKim** [comment]
앗, 서로 만나 미니프로젝트등을 같이 진행하거나.. 머신러닝 자체가 재미있다면, 캐글을 하는 모임을 먼저 찾아가보시는 것이 어떨까요?

혹은 스타트업위주로 찾아보는 것도 방법일 수 있습니다.

**Comment by fermat39** [comment]
안녕하세요....

데이콘이나 캐글 대회 같이 참여하고자 하는 모임들이 많이 진행되고 있습니다.
같이 고민해보시지요...

**Comment by Hanuu** [comment]
+추가로 온라인 알고리즘 대회를 몇가지 추천드립니다.

구글 킥스타트 - https://codingcompetitions.withgoogle.com/kickstart (보통 매달 열립니다)
삼성 SCPC - https://research.samsung.com/scpc (18일 까지 신청입니다)
