### ISSUE TITLE
대학 학과 선택을 고민하고 있는 현 고등학교 재학생입니다.

### ISSUE THREAD

**Issue by psychologisthhb** [codingeverybody/codingyahac#979]
현재 저는'컴퓨터 공학과' 또는 '소프트웨어 학과' 또는 '정보 보안 학과'를 지향하고 있는 고등학교 2학년 재학생입니다.  대학교 진학과 관련해서 이 3종류의 학과의 차이점도 정확히 모르겠고, 조금 찾아본 결과 우리나라의 정보 보안이 세계 최고라는 이야기도 있어 그 쪽으로 가야하나? 라는 생각도 듭니다. 정확히 '세 학과가 가르치는 내용, 취업 전망'에 대한 정보가 부족해서 진학 결정을 내리기에 힘이 듭니다.  현재 저는 웹사이트, Python, Java에 대한 기본 내용까지 배웠으며 내신 등급은 일반고 2.6등급입니다. 
 이 고민을 보시게 되신다면 '세 학과의 차이점과 대학 학과를 선택할 때의 주의할 점, 개발자라는 관점에서 대학 학과가 가지는 의미'에 대해 조금이라도 적어주시면 감사하겠습니다. 
Q1. 저는 어느 학과를 가야할까요? (컴퓨터 공학과 / 소프트웨어 학과 / 정보 보안 학과)
Q2. 개발자를 업으로 삼을 때, 대학교 이름이 얼마나 영향을 미칠까요?
Q3. 더욱더 현 개발자의 입장에서 '개발자가 가지는 이점'이 무엇이라 생각하시나요?

**Comment by KIMGEEK** [comment]
가르치는 내용은 대학교 홈페이지 들어가서 교과과정 보세요. 컴퓨터공학과와 소프트웨어공학과의 경우 대학마다 이름이 다르거나 혹은 두 과가 모두 있는 경우가 있어요. 대학에서 소프트웨어학과로 이름을 정했다면 하드웨어보단 소프트웨어 특화 인재 양성이란 의지가 강한 대학이예요. 컴퓨터공학과는 하드웨어까지 다루느냐하면 그건 꼭 그러한 건 아니예요. 커리큘럼을 보면 소프트웨어학과나 컴퓨터공학과가 별반 차이가 없는 경우도 있어요. 하지만 앞서 말했다시피 학과 이름은 대학의 의지예요. 소프트웨어학과라는 타이틀을 내건만큼 컴퓨터공학과로 이름을 선정한 대학들에 비해 비단 교육과정이 비슷하더라도 교수님들께서 학생들이 소프트 쪽으로 진로를 결정하길 장려하겠죠. 안 그러면 굉장히 우스운 일이니까요.

**Comment by KIMGEEK** [comment]
하드웨어, 소프트웨어가 뭔지 궁금할 거예요. 하드웨어는 컴퓨터에서 로우 레벨 기술을 포함해요. 컴퓨터가 어떻게 작동하는지를 아는거예요. 이를테면 전자제품에 들어가는 작은 컴퓨터(임베디드라고 하던데)를 만드는 일에 종사할 수도 있겠어요. 라즈베리파이 같은 컴퓨터도 조작할 수 있고요. 소프트는 [머신러닝,딥러닝,인공신경망, 운영체제, 네트워크, 게임, 커널, 3d] 지금 나열한 것처럼 분야가 매우 나뉘어 있어요.  사실 더 많아요. 대학교 컴퓨터공학부(혹은 소프트웨어학부)를 들어가보시면 지금 나열한 것을 가르치는 대학도 있고 아닌 대학도 있어요. 스스로 뭘 하고 싶은지 생각해보셔야 할 것 같아요. 정보 보안도 사실 시스템 수준까지의 지식을 갖고 일하는 사람도 있고, 커널과 같이 로우 레벨의 기술 영역에서 일하는 사람이 있잖아요.
웹 개발자도 프론트 개발(사용자에게 보여지고 직접 상호작용하는 영역), 백엔드 개발(프론트엔드로부터 변환된 신호를 전달받아 실제 작동하는 영역)로 인터페이스에서 크게 두 사람이 나뉘어서 일하듯이 혼자서 모든 걸 다하지는 않거든요. 서비스를 만들 때 근본적인 기술을 이해하는 개발자도 필요하지만, UI를 예쁘게 만들어서 사용자가 쉽게 서비스를 제공할 수 있도록 하는 UI 개발자도 필요해요. 어떤 사람이 더 우월하기 때문에 회사에서 뽑기보다 역할에 따라서 필요한 사람을 뽑는 거예요. 구글에서도 얼마든지 고졸 출신의 엔지니어가 뽑히는 이유이고요.

**Comment by KIMGEEK** [comment]
제 부족한 지식이 도움이 될지는 모르겠습니다만, 여러 사람들의 생각 중 하나의 생각이라고 생각하세요. 정답은 없고, 상황에 따라 통하는 의견만이 있을 뿐이니까요. 고등학교 2학년이시면 개발 관련 책을 읽어보세요. 생기부에다 올릴 수도 있고요. 유튜브에 생활코딩님 뿐만 아니라 코딩의 신 아샬님, 노마드 코더에서 소개해주는 책 몇 권 있는데 좋은 책들이 많아요. 읽어주셔서 감사합니다.

**Comment by KIMGEEK** [comment]
대학은 일단 잘 가는게 좋죠. 대학을 잘 활용할 수 있다면요. 대학에서 좋은 환경과 기회를 제공해주는 곳을 가세요. 2.6이면 좀 더 열심히 공부해서 건국대 생각해보는 것도.. 근데 나중엔 실력을 다 보니까요. 대학은 약간 그런거죠. 게임이든, 악기 연주든 내가 무슨 직업에 종사할 때 뭐라도 잘 하는 게 많을수록 좋은 거잖아요.

**Comment by RayleighKim** [comment]
개발자를 업으로, 대학교의 네임벨류
> 개발자로서 어떻게 살아가느냐가 나와야 답변이 가능합니다.
> 또한, 취직 전략에 따라 달라집니다.  전혀 대학교가 상관없는 경우 부터,  큰영향을 주는 경우까지 너무 다양해요.
> 하지만 지금은 그보다..  이분야가 재밌어 보이는지//아닌지가 더 많은 것을 결정할거에요.
