### ISSUE TITLE
egoing님이 해주시는 국어? 강의도 듣고싶어요.

### ISSUE THREAD

**Issue by linguaxe** [codingeverybody/codingyahac#98]
저는 배운 내용을 정리하거나 남에게 설명할때 적절한 단어가 잘 떠오르지도 않고 조리있게 설명도 못하겠어요. 질문 글을 적으려 해도 너무 어렵구요.

그러다 이고잉님이 해주시는 강의를 들으면 이해도 잘되고 너무 재미있어요. 글도 공감되면서 술술 읽히게 되구요. 

이러한 국어능력을 키울 수 있는 방법이나 남들에게 잘 설명할 수 있는 기술, 이고잉님만의 노하우같은 것들을 시간나실때 한 번 강의로 만들어주시면 정말 좋을 것 같다는 생각이 들어요.
오픈튜토리얼스에도 도움이 될 것 같구요.

영어나 수학같은 제가 힘들어했던 과목들도 이고잉님한테서 배웠다면 정말 행복하게 배웠을 것 같아요. ㅎㅎ

**Comment by linguaxe** [comment]
코딩도 배우고 싶지만, 
저는 이고잉님의 철학, 배움을 배우는 방법이나 설명하는 방법같은 훌륭한 점들을 더 많이 배우고 싶어요.

**Comment by dongheegy** [comment]
[프로그래밍 오리엔테이션 - 생활코딩](https://opentutorials.org/course/1189)
원하시는 강의일지는 모르겠지만, 여러가지 재미있는 이야기가 있으니 참고하세요.
