### ISSUE TITLE
머신러닝 교양까지 듣고서... 이게 가능한지요

### ISSUE THREAD

**Issue by hungryo-dev** [codingeverybody/codingyahac#986]
# 해결하고자 하는 문제
정해진 양식이 없는 상태에서 특정 품목, 수량 등을 뽑아낼 수 있을까요?

예시로 월말에 수많은 문서를 취합합니다.
문서에는 다양한 품목과 판매량이 적혀있는데 문서 포맷이 정해져있지 않습니다.
예로 A4의 어떤 문서에는 오른쪽 상단에 갤럭시=30 이 적혀있고, 또다른 문서에는 왼쪽 하단에 갤럭시=20, 아이폰=50이 적혀있습니다.
이렇게 다양한 템플릿에서 저 품목의 수량들을 캐치하여 뽑아낼 수 있을지요?
필요한 기술이나 키워드만 말씀해주셔도 감사하겠습니다!

**Comment by RayleighKim** [comment]
조금 더 질문이 구체적이라면 다른 조력자 분들도 구체적으로 답변을 다실 수 있게될 것 같습니다.

푸시고자 하는 문제가.. 취합되는 문서가 hwp, txt등의 파일이 아니라, 실제 종이 문서인것이라면...OCR, 정규식 등이 가장 밀접한 기술일 것 같습니다.

**Comment by chongkong** [comment]
실제 데이터를 보지 않고서는 말씀을 드리기 조심스럽지만 Rayleigh Kim님 말씀처럼 OCR로 먼저 문자열을 뽑아내고 그 후에 어떻게 가공할지를 고민해볼 수 있을거 같아요

**Comment by jiyongjung0** [comment]
위에 답변해주신 대로 OCR을 사용하는 방법도 있지만, 요즘은 한 발 더 나아가서 문서 자체를 바로 인식하는 방향 역시 업무 자동화를 위해 많이 시도되는 것 같습니다. 구글에서도 [Document AI](https://cloud.google.com/solutions/document-ai?hl=ko)라는 제품을 내놓고, 국내에도 여러 가지 솔루션이 판매되고 있습니다.

기술적인 부분은 Structured document recognition / extraction 등으로 검색해보시면 찾아보실 수 있을 것 같습니다.

**Comment by hungryo-dev** [comment]
> 조금 더 질문이 구체적이라면 다른 조력자 분들도 구체적으로 답변을 다실 수 있게될 것 같습니다.
> 
> 푸시고자 하는 문제가.. 취합되는 문서가 hwp, txt등의 파일이 아니라, 실제 종이 문서인것이라면...OCR, 정규식 등이 가장 밀접한 기술일 것 같습니다.

답변 감사드립니다!
좀 더 디테일하게 설명하면, 각 거래처마다 서로 다른 템플릿에 작성된 파일을 A4로 획득하고, 담당자는 품목별 수량을 별도 시스템에 입력 후 증빙용으로 핸드폰으로 사진을 찍어 첨부파일을 업로드하는 시스템입니다.
모든 템플릿을 다 커버하기보다는 가장 많이 사용되는 템플릿을 몇가지 추려 학습된 템플릿일 경우는 별도로 입력하지 않고 파일만 올리면 자동 맵핑되게 하려합니다.
또다른 궁금증은 OCR로 여러 문자들을 각각의 단어로는 추출이 가능할꺼 같은데요
갤럭시=S10. 이런식으로 key-value 셋트로 묶어서도 각각의 데이터를 웹 개발자가 핸들링 가능할까요?

**Comment by hungryo-dev** [comment]
> 위에 답변해주신 대로 OCR을 사용하는 방법도 있지만, 요즘은 한 발 더 나아가서 문서 자체를 바로 인식하는 방향 역시 업무 자동화를 위해 많이 시도되는 것 같습니다. 구글에서도 [Document AI](https://cloud.google.com/solutions/document-ai?hl=ko)라는 제품을 내놓고, 국내에도 여러 가지 솔루션이 판매되고 있습니다.
> 
> 기술적인 부분은 Structured document recognition / extraction 등으로 검색해보시면 찾아보실 수 있을 것 같습니다.


위에 답변쓰고 Document AI 검색해서 샘플 테스트해보니까 가능할꺼 같네요! 
감사드립니다><
