### ISSUE TITLE
머신러닝을 이용하여 악보를 변환하는 프로그램을 만드려고 하는데, 이번 머신러닝 야학 강좌중 어떤 걸 참고하면 좋을까요?

### ISSUE THREAD

**Issue by ghost** [codingeverybody/codingyahac#988]
# 해결하고자 하는 문제

 일반 악보 -> 기타 TAB 악보로 변환하는 프로그램을 만들어보고자 합니다. 일반 악보의 이미지 파일을 학습시켜, 
기타 TAB 악보를 이미지나 프로그램 형식으로 출력시킬 수 있다는 확신은 가지고 있습니다만, 구현하기엔 아직
제 기술적인 부분에서 부족한 것 같습니다. 지금은 머신러닝1의 공개되고 있는 강좌만 듣고 있습니다만, 혹시
이외에도 제가 이 프로그램을 만들어보는 데 직접적인 도움이 될 강좌는 어떤 것인지 여쭤보고자 질문을 작성
하게 되었습니다.

# 환경
Windows 10, 기본적인 Python  사용법을 알고 있습니다.

# 시도해본 방법

 머신러닝 1 강좌에서 소개된 Teachable Machine로 구현이 가능할 지 생각해 보았습니다만, 예를 들어 강좌에서
소개 된 웹캠을 통해 자신이 손톱을 물어 뜯으면 알려주는 프로그램의 경우 (정상, 손톱)의 2가지 형태의 출력만
가능하여 학습시키는데 어려움이 없었던 반면, 악보의 경우 작곡가의 의도에 따라 출력시켜야 할 형태가 무한하여
Teachable Machine 학습시키기에 적합한 모델은 아니라는 생각이 들었습니다.

 제가 생각하기에 머신러닝을 사용하여 해결할 수 있는 방법은 다음 2가지인 것 같습니다.

1. 이미지 to 이미지 : 입력 악보 이미지와 출력 tab악보 이미지를 학습시켜, 임의의 악보 이미지를 tab 악보 이미지로
바꿀 수 있도록 한다.

2. 이미지 to 코드 : 입력 된 이미지를 코드로 작성할 수 있도록 학습시켜, 작성된 코드를 외부 프로그램에 입력, 외부 프로그램을
통하여 출력한다.

조잡합니다만, 질문을 읽으시는 데 도움이 되도록 이미지도 함께 첨부했습니다.  (빨간 화살표 부분 위주로 봐주시면 됩니다.)

![CamScanner 08-15-2020 19 32 02_1](https://user-images.githubusercontent.com/55381168/90311041-17455500-df32-11ea-833e-bed3de7108b3.jpg)

위에서 말한 방법 이외에도, 머신러닝으로 구현할 수 있는 부분이 있는지, 어떤 강의를 통해 배울 수 있는지 알고 싶습니다.

 질문이 길어서 죄송합니다만, 이번 머신러닝 야학에서 실제 상황에 적용할 수 있을 만큼 배워가고자 하는 마음입니다.

 질문 읽어주셔서 감사합니다.

**Comment by jiyongjung0** [comment]
일단 제가 음악에는 지식이 많지 않아서 정확한 답변을 드릴 수 있을지 모르겠습니다만, 제 생각에도 teachable machine 만으로는 조금 확장이 어렵지 않을까 싶긴 합니다.

악보의 인식은 매우 중요한 문제이다보니 연구도 어느 정도 되어있고 제품도 좀 있는 것 같습니다. https://en.wikipedia.org/wiki/Optical_music_recognition 일단 드는 생각은 기존의 방식들을 연구해보신 다음, midi 등으로 악보를 변환한 후 여기서 다시 기타 코드를 생성하는 방식이 좋을 것 같습니다. 그렇다고 말씀하신 이미지-to-이미지 방식이 불가능하지는 않을텐데요.
다만, 머신러닝에서 중요한 것 중 하나는 학습데이터를 아주 많이 모아야한다는 것인데, 이 부분을 고려하면 문제를 두 단계로 나누어 푸는 편이 데이터를 모으기에 훨씬 쉽지 않을까 싶습니다.

**Comment by hephaex** [comment]
기타를 좋아하시는 분들이라면 TAB 체보에 대해서 많은 관심이 있어서, 깃헙에 태그로 #optical-music-recognition 라고 검색하시면 다음의 태그에 관련된 페이지가 나옵니다. [link](https://github.com/topics/optical-music-recognition)

가장 많은 Star를 받은 프로젝트가 audiveris 이네요. [linkk](https://github.com/Audiveris/audiveris)
윈도우즈 용으로 릴리즈도 되어 있으시 한번 사용해 보시는 것도 좋을 듯 싶구요. 
깃헙에 또 다른 프로젝트도 있으니 관심을 가지고 한번 씩 들어가 보셔서 원하시는 것을 얻으셨으면 좋겠습니다.

**Comment by ghost** [comment]
먼저 연구된 사례가 있었군요! 먼저 중점적으로 공부해보겠습니다. 감사합니다.
