### ISSUE TITLE
수학 전공생입니다. 내년에 저희 과가 소프트웨어 학과로 통폐합 되는데, 진로를 어떻게 하면 좋을까요?

### ISSUE THREAD

**Issue by ghost** [codingeverybody/codingyahac#989]
현재 수학과 3학년을 수료한 상태고 휴학중입니다.

제가 수학을 좋아하는 학생이라 신입생 때부터 진로라 하면 학부-대학원 연계과정만 생각하고 있었습니다만, 

이번 통폐합으로 수학과 대학원도 사라질 예정이여서 고민이 많아졌습니다. 

타 학교에서 등록금을 내면서까지 수학과 대학원에 진학하고 싶은 지도 확신이 서질 않고요.

그렇다고 남은 1년의 수업으로, 제가 다른 컴공이나 sw과 학생만큼 알게 된다고 보기도 어려울 것 같아요.

일단 1. 타 대학원 진학, 2. 자 sw대학원 연계과정, 3. sw과 학부 졸업으로 취업준비 시작. 정도를 생각하고 있는데요,  

(연계과정 같은 경우 다음 학기 등록과 함께 신청해야만 합니다.)

 지금 이렇게 머신러닝 강좌도 듣고, 정보처리기사 자격증도 준비하고는 있습니다만,  아직 소프트웨어는 제게 타전공입니다.

제가 남은 2학기 동안 대학 수업도 듣고, 직접 프로젝트나 공부를 통해 열심히 준비한다고는 해도, 1년 반 후의 제가

sw과 졸업생으로서 다른 컴공과, sw과 학생들과 경쟁하여 취업할 수 있는 수준이 되는지, 만약 당장 연계과정을 시작한다 하면

내년의 제가 sw과 대학원 수업을 잘 들을 수 있을 만큼의 수준을 갖출 수 있는지, 판단하기가 너무 힘이 듭니다.

또 어느 한 쪽으로 갈래를 잡았다 해도, 어떻게 준비해나가야 하는지 사실 잘 모르겠습니다.

 진로 관련하여 깊이 생각하지 않은 것은 제 불찰이 확실합니다만, 저와 같은 사례가 없는 만큼 도움을 청할 수 있는 곳이

마땅히 없습니다... 조력자 분들께서 잠시라도 읽어주시고 어떻게 하면 좋을지 알려주신다면 정말 감사하겠습니다.

**Comment by RayleighKim** [comment]
다른 조력자분들하고 의견이 다를 것만 같습니다..
힘들고 악랄한 상황일수록..  무엇을 재밌어하는지 찾는 시간을 길게 가져가주셨으면 합니다.
부디 탐색하셔야 합니다. 난 무엇을 재밌어 하는가.  누가 안시켜도 밥먹고 멍때리다 보면 자연스럽게 하고 있을 수 있을 일.

아직도 수학을 좋아하실까요? 그렇다면, 다른 대학원의 수학과로 대학원 진학하는 것 전혀 나쁘지 않습니다. 어쩌면 학과 편입도 좋을 수 있습니다.  그 와중에, 머신러닝이라는 분야가 재미있어 보인다면.. 응용수학 하시는 교수님의 연구실을 가면 될 것 같아요. 가능하면 재미있는 것 / 전공  <- 이 두가지는 살릴 수록 유리합니다.

저는 SW와  머신러닝은 따로 보고있습니다. 사실, 학교에서 배우는 SW는 전혀 모릅니다.

하지만 던질 질문은 여전히 한가지입니다.  SW 좋아하실 수 있을까요? 조금이라도 겪어보셨을 것 같습니다. 재미있나요?

사람이 재미있는 것만 하고 살 수 없다지만... 한국에서 살아간다고 한다면, 재미있는 것을 하는 것이 최고로 장기적인 전략이라고 확신합니다. 재미없다면 버틸 수 없습니다.

**Comment by egoing** [comment]
컴공과에 간다고 수학이 필요없어지는 것은 결코 아니랍니다.
저는 수포자였고, 수포자라고 프로그래밍을 할 수 없는 것은 아니지만 
수학적인 개념이 필요한 일들을 피해다닐 수 밖에 없었답니다. 
수학에 날개를 달아주는 도구가 컴퓨터라고 생각하신다면 어떨까요?

**Comment by fermat39** [comment]
안녕하세요...

수학과 전산을 복수전공하고 이 쪽 분야에서 거의 15년 가까이 먹고 살고 있는 사람입니다. ㅎㅎ
전공이 매우매우 중요하지 않습니다. 정말 중요한 것은 역량입니다.

해당 조직에서 어떤 업무를 창조적으로 해결해나갈 수 있는 능력말이지요...
최근에는 블라인드 채용이라고 해서 학교, 전공, 학점 등을 질문할 수 없습니다.
자기소개서에도 넣을 수도 없고요...

전공은 업무에 조금이나마 도움이 줄 수는 있겠지만 필수 조건은 아닙니다.

국회의원들은 그럼 정치를 하니 정치외교학과를 나와야 하는 것일까요?
공무원들은 그럼 행정학과를 나와야하는 것일까요?

[수학의 쓸모 ] (http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791165210991&orderClick=LAG&Kc=#N)
안녕하세요...

현재 무엇을 어떤 생각으로 하느냐가 중요한 것 같습니다!
화이팅입니다! 힘들 때 언제든지 연락주세요~~~

![image](https://user-images.githubusercontent.com/1271980/90350815-3ac6e780-e079-11ea-9980-1d4ffcebaf8d.png)

**Comment by ghost** [comment]
다들 진지하게 읽어주시고 자신의 경험들도 들려주셔서 많은 도움이 됐습니다 정말 감사합니다.
