### ISSUE TITLE
React+spring 프레임워크 개발환경 질문드립니다.

### ISSUE THREAD

**Issue by wasonit** [codingeverybody/codingyahac#99]
안녕하세요 멘토님들 오늘도 코드와 소통하시느라 고생이 많으세요~

다름아니라 제가하고싶은 부분은 View영역은 react.js로 개발하고 서버컨트롤러부분은 java spring으로 구현하고 싶은데요. 초기개발환경을 어떻게 구현해야하는지 모르겠어요. 
찾아봐도 잘 못찾겠던데... 도와주시면 매우 감사하겠습니다.

**Comment by blackdew** [comment]
저는 직접 react나  spring을 만져 본 적은 없네요. 
검색해보니 참고할 만한 링크 같아셔 답변 남깁니다. 

https://goo.gl/jHoUa9
(원글 https://spring.io/guides/tutorials/react-and-spring-data-rest/ 을 구글 번역기로 돌린 결과에요.)

**Comment by wasonit** [comment]
감사합니다~ 참고해서 구현해보겠습니다
