### ISSUE TITLE
머신러닝 야학 중 독립/종속변수의 관계에 관한 질문

### ISSUE THREAD

**Issue by swang-jisoo** [codingeverybody/codingyahac#990]
3일차 수업 중 "독립/종속변수 관계 설명에서 둘의 관계가 인과관계이고, 인과관계는 상관관계에 포함된다" 라고 하셨습니다.
1. 먼저 이해를 재확인하고자 하는 데요. 상관관계에서 일정한 패턴이 발견된다고 할 때, 인과관계가 있다고 하는 건가요?

2. "종속변수와 상관관계에 있지만, 인과관계인지는 알 수 없는 변수"를 부르는 단어가 있나요?

3. 머신러닝 모델은 독립/종속변수로 이루어진 데이터셋으로만 만들 수 있는 건가요? 즉, "종속변수와 상관관계에 있지만, 인과관계인지는 알 수 없는 변수"는 사용할 수 없는 건가요? 아니면 어느 정도 이상의 상관관계가 있다고 판명이 될때만 포함시킬 수 있는건가요? 이 상관관계를 수치화/판명하는 방법도 있나요?

4. 상관관계보다 인과관계를 추론하는 게 더 어렵다고 하시는데, 인과관계를 확정하는 방법은 무엇이 있나요?

**Comment by fermat39** [comment]
안녕하세요...

너무 어렵게 접근하시려는 것은 아닌지 생각이 됩니다. 제가 책 몇권 추천해드릴게요...
아래 2권은 swang-jisoo님께서 생각하시는 부분을 좋은 사례로 설명을 해줍니다.
또한, 데이터 분석에 대한 좋은 인사이트들도 얻으실 수 있을거예요
조금이나마 도움이 되셨기를 합니다.

[원인과 결과의 경제학]
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788901226750&orderClick=LEa&Kc=

![image](https://user-images.githubusercontent.com/1271980/90350397-03a40680-e078-11ea-80d2-acc87b392f27.png)

[데이터 분석의 힘]
http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791186560792&orderClick=LAG&Kc=

![image](https://user-images.githubusercontent.com/1271980/90350482-4b2a9280-e078-11ea-9d8f-936ce0f45f50.png)

**Comment by RayleighKim** [comment]
> 먼저 이해를 재확인하고자 하는 데요. 상관관계에서 일정한 패턴이 발견된다고 할 때, 인과관계가 있다고 하는 건가요?

아닙니다. 쉽게만 풀어보자면   x가 y의 원인인경우, x가 y의 결과인경우, x랑 y가 서로영향주는경우, 다른 무언가가 x와 y에 동시에 영향을 주는 경우 등을 전부 x와 y가 상관관계가 있다고 합니다.
즉, **상관은 인과를 포함합니다.**

그 중, 몇가지 조건에 따라서 (제가 가장 좋아하는 것은 시간적 우선성입니다.) 인과관계라고 부르는 경우가 있습니다.

우리는 전단지를 많이 뿌릴 수록 레몬에이드 판매량이 늘어날 것이라 생각했지만..
사실은 손님들이 레몬에이드를 사면서 전단지를 한장씩 가져간다면.

레몬에이드를 산다는 사실이 우선하고, 전단지를 가져간다는 사실이 뒤따르기 때문에
레몬에이드 판매가 원인이 되고, 전단지를 가져가는것이 결과가 되겠지요.


>"종속변수와 상관관계에 있지만, 인과관계인지는 알 수 없는 변수"를 부르는 단어가 있나요?

상관관계에 있는 변수라고 하면 됩니다.  상관은 인과를 포함하니까요.

> 머신러닝 모델은 독립/종속변수로 이루어진 데이터셋으로만 만들 수 있는 건가요? 즉, "종속변수와 상관관계에 있지만, 인과관계인지는 알 수 없는 변수"는 사용할 수 없는 건가요? 아니면 어느 정도 이상의 상관관계가 있다고 판명이 될때만 포함시킬 수 있는건가요? 이 상관관계를 수치화/판명하는 방법도 있나요?

여기서 독립변수라는 말은, X들끼리 독립이라는 표현이지 (정말 조심스럽게 사용해야하는 표현이긴 합니다.) X와 Y가 독립이란 뜻이 아닙니다.  즉, Y와 상관관계에 있는 변수는 전부 포함가능합니다. 예측/인과해석만 조심하면 됩니다.

상관관계를 수치화 하는 방식도 여러가지가 있습니다.  상관관계가 있다고 판명될때만 포함시키는 것도 존재하는 방법이고, 그렇지 않고 진행한 후 파악해도 좋습니다.

> 상관관계보다 인과관계를 추론하는 게 더 어렵다고 하시는데, 인과관계를 확정하는 방법은 무엇이 있나요?

일반적으로 세가지를 이야기 하지만, 저는 처음 두개를 가장 좋아합니다.
마지막 3번은.. 인과관계 추론을 '간단하고 명료'하게 할 때 생길수 있는 이슈입니다.

1. 시간 순서 : 원인이 선행하게 된다.
2. 공변성 : 원인이 변화되면 결과도 변화되어야 한다. 
3. 외부 설명 배제 : 다른 원인이 있는 경우 힘들어짐.

**Comment by swang-jisoo** [comment]
@fermat39 감사합니다! 추천해주신 책 모두 목차를 보니 예시가 다양해 도움이 될 것 같습니다. 잘 읽어보겠습니다. 
 
@RayleighKim 쉽고 간결하게 설명해주셔서 헷갈렸던 부분에 대한 이해가 명확히 되었습니다. 답변 정말 감사합니다~
