### ISSUE TITLE
첫번째 딥러닝 - 레모네이드 판매 예측 - 종속 변수 관련 질문

### ISSUE THREAD

**Issue by dojinyou** [codingeverybody/codingyahac#996]
딥러닝 모델을 학습시킨 후의 궁극적으로 답을 모르는 문제에 적용하는 것이라고 생각했습니다. 레모네이드 판매 예측을 하는 모델을 만들 때 종속변수가 온도입니다. 그런데 미래의 온도는 현재에선 알 수 없는 변수인데 내일 혹은 모래의 판매량을 예측할 때는 온도 역시 예측해서 사용해야하는 건가요??
이렇게 현재 시점에서는 알 수 없는 데이터를 학습에서 사용하면 실제 예측시에는 어떤 식으로 독립변수를 입력해야되는 지 궁금합니다. 비워도 예측이 되는 지? 혹은 신뢰도 높은 예측값을 다시 구해서 사용해야되는지?

**Comment by jiyongjung0** [comment]
레모네이드 예제에서 `온도`는 `독립변수`이고, `판매량`이 `종속변수`입니다. 하고 싶은 일은 "일기 예보 상의 온도(독립변수)를 보고
몇 개가 판매(종속변수)될지 예측하는 것"이지요. 

위 예에서는 전날 저녁에 일기예보를 보고 온도를 확인한다음, 판매를 예측하게 되겠네요. 😄  즉, 온도는 외부에서 주어지는 값을 사용합니다.

**Comment by jjimini98** [comment]
현재 시점을 알 수 없는 경우 비슷한 과거의 상황을 가지고 예측하지 않을까요..? 레몬에이드 예를 들자면 작년 올해 이맘때쯤 온도가 어땠고 판매량이 어땠다는 데이터를 가지고와서 예측하는 식으로요

**Comment by RayleighKim** [comment]
많이 중요한 지점입니다.

예측 시점에서 예측 재료(x)들은 반드시 내 손안에 있어야 합니다.
학습용 데이터는 내 손안에 전부 있기 때문에 자기도 모르게 실수하는 경우가 생기게 됩니다.

예측 문제에서 X와 Y의 시차/시점 정보는 매우 중요합니다.
예측하는 시점에 손에 넣을 수 없는 데이터로 모델을 구성하면 안됩니다.

(질문주신 예시는, 온도가 항상 기상청 예보등을 이용한 데이터라고 가정하신다면 조금 매끄러워지실겁니다.
 전날 온도라고 생각해도 나쁘지 않겠습니다)

**Comment by dojinyou** [comment]
> 많이 중요한 지점입니다.
> 
> 예측 시점에서 예측 재료(x)들은 반드시 내 손안에 있어야 합니다.
> 학습용 데이터는 내 손안에 전부 있기 때문에 자기도 모르게 실수하는 경우가 생기게 됩니다.
> 
> 예측 문제에서 X와 Y의 시차/시점 정보는 매우 중요합니다.
> 예측하는 시점에 손에 넣을 수 없는 데이터로 모델을 구성하면 안됩니다.
> 
> (질문주신 예시는, 온도가 항상 기상청 예보등을 이용한 데이터라고 가정하신다면 조금 매끄러워지실겁니다.
> 전날 온도라고 생각해도 나쁘지 않겠습니다)

그렇다면 만약 향후 1주일간 날씨를 예측하는 모델을 만들 때
2일을 학습하고 1일을 예측하는 모델을 만들고 예측값들을 다시 입력으로 처리해서 일주일을 예측하는 것은 안되나요?
일주일을 예측하고자 하는 시점에 첫째날을 제외하곤 항상 데이터가 없는 상태이지만 예측값을 만들어내서 사용하는 것은 안되는 방법인가요?

**Comment by RayleighKim** [comment]
>그렇다면 만약 향후 1주일간 날씨를 예측하는 모델을 만들 때
2일을 학습하고 1일을 예측하는 모델을 만들고 예측값들을 다시 입력으로 처리해서 일주일을 예측하는 것은 안되나요?
일주일을 예측하고자 하는 시점에 첫째날을 제외하곤 항상 데이터가 없는 상태이지만 예측값을 만들어내서 사용하는 것은 안되는 방법인가요?

구조적으로 가능합니다.
RNN 을 사용하실 수 있게되면, 쉽게 예측값들을 다시 인풋으로 사용할수도 있어요.

하지만 예측 절차가 중복되면.. 항상 오차가 이슈가 됩니다. 그부분만 주의하신다면 일단 좋습니다

**Comment by dojinyou** [comment]
> > 그렇다면 만약 향후 1주일간 날씨를 예측하는 모델을 만들 때
> > 2일을 학습하고 1일을 예측하는 모델을 만들고 예측값들을 다시 입력으로 처리해서 일주일을 예측하는 것은 안되나요?
> > 일주일을 예측하고자 하는 시점에 첫째날을 제외하곤 항상 데이터가 없는 상태이지만 예측값을 만들어내서 사용하는 것은 안되는 방법인가요?
> 
> 구조적으로 가능합니다.
> RNN 을 사용하실 수 있게되면, 쉽게 예측값들을 다시 인풋으로 사용할수도 있어요.
> 
> 하지만 예측 절차가 중복되면.. 항상 오차가 이슈가 됩니다. 그부분만 주의하신다면 일단 좋습니다

답변 감사합니다.
